;----------------------------------------
;@Habitat:オネット／市役所／受付
;@Person:客
;@Figure:おじさんD
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_OZISAN_A
MSG_ONET_TOWNHALL_OZISAN_A;市庁舎
◆There are lots of snakes and stray dogs around Onett.@KEY()↓
◆Is the mayor going to let them just run around, doing whatever they want?@KEY()↓
◆I’m here to protest!
;jpn:◆オネットのまちの しゅうへんに↓
;jpn: ヘビとか のらイヌとか↓
;jpn: たくさん いるだろう。@KEY()↓
;jpn:◆ああいうものを そのままに↓
;jpn: しておいて いいのか?!@KEY()↓
;jpn:◆わしは こうぎに きたんだ。
@KEYNP()
』


;@Habitat:オネット／市役所／部屋１
;@Person:役人A
;@Figure:サラリーマンA
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_A
MSG_ONET_TOWNHALL_A;
◆I work for City Hall,@WI(15) but somehow Mayor Pirkle bugs me.@KEY()↓
◆Let’s keep this between you and me.
;jpn:◆わたしは しやくしょに↓
;jpn: つとめているんだけど@KEY()↓
;jpn:◆なんとなく ピカールしちょうを↓
;jpn: すきに なれない‥‥@KEY()↓
;jpn:◆ないしょ だけどね。
@KEYNP()
』


;@Habitat:オネット／市役所／部屋１
;@Person:役人B
;@Figure:サラリーマンB
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_C
MSG_ONET_TOWNHALL_C;
◆We don’t have any openings for part−time employees at this time.
;jpn:◆アルバイトなら↓
;jpn: いまは ぼしゅうしてないよ!
@KEYNP()
』


;@Habitat:オネット／市役所／部屋１
;@Person:客A
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_OLDMAN
MSG_ONET_TOWNHALL_OLDMAN;
◆Did I tell you that I saw a Giant Ant one time at Giant Step?@KEY()↓
◆...@KEY()↓
◆Oh,@WI(10) sorry.@WI(30)  I did ant mean to spoil it for you.
;jpn:◆「ジャイアントステップ」で↓
;jpn: むかし でっかいアリを↓
;jpn: みたことが あってのう。@KEY()↓
;jpn:◆アリッ?@KEY()↓
;jpn:◆‥‥‥↓
;jpn: しらけたか。@WI(15) すまん。
@KEYNP()
』


;@Habitat:オネット／市役所／部屋１
;@Person:客B
;@Figure:OL・D
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_WOMAN
MSG_ONET_TOWNHALL_WOMAN;
◆Some suspicious−looking kids are hanging out in the woods north of the library.@KEY()↓
◆I wonder if they are members of the Sharks.@KEY()↓
◆To stop the spread of the gang,@WI(15) someone should shut down their gathering places,@KEY()↓
◆don’t you think?@KEY()↓
◆I’ll start a movement that will stop all of the bad influences on the children of Onett.@KEY()↓
◆I’ll call it the ”Fresh Breeze Movement.”@WI(15)  Hum de dum dum...
;jpn:◆としょかんの きたのもりにも↓
;jpn: シャークだんの みならいみたいな↓
;jpn: わるガキが たむろしているのよ。@KEY()↓
;jpn:◆これいじょう ふりょうが↓
;jpn: ふえないように@KEY()↓
;jpn:◆ああいう たまりばを↓
;jpn: ぶっつぶしてもらわなきゃ@WI(10) ね。@KEY()↓
;jpn:◆ねっ!@KEY()↓
;jpn:◆こどもたちの きょういくに↓
;jpn: あくえいきょうを およぼすものを↓
;jpn: オネットから いっさいなくす@KEY()↓
;jpn:◆「そよかぜうんどう」を↓
;jpn: していくざます。@WI(10)↓
;jpn: ランラララン。
@KEYNP()
』


;@Habitat:オネット／市役所／部屋２
;@Person:役人
;@Figure:サラリーマンA
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_B
MSG_ONET_TOWNHALL_B;職員B
◆I’m really in a foul mood.@KEY()↓
◆Why?@WI(20)  Because the Mayor doesn’t like me.@KEY()↓
◆I think I’ll just kick back for a while.@KEY()↓
◆It just may take me a couple of hours to sign this paper. ＊snicker＊ ＊snort＊
;jpn:◆しちょうに きらわれてるので↓
;jpn: わたしは すねている。@KEY()↓
;jpn:◆てっていてきに サボッてやる。@KEY()↓
;jpn:◆はんこひとつ おすのに↓
;jpn: ２じかんくらい かけたりして‥。↓
;jpn: ヒッヒッヒ。
@KEYNP()
』


;@Habitat:オネット／市役所／部屋２
;@Person:客
;@Figure:おじさんA
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TOWNHALL_OZISAN_B
MSG_ONET_TOWNHALL_OZISAN_B;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Oh,@WI(15) aren’t you @DSP_NAME(0)?@KEY()↓
◆Is it a school holiday today?@WI(15)  Have you done your homework?@KEY()↓
◆Remember to brush your teeth before going to bed.@KEY()↓
◆Have you been wetting your bed?
;jpn:◆@DSP_NAME(0)
;jpn:@GOSUB(MSG_SUB_KUN_CHAN)
;jpn:じゃないか。↓
;jpn: きょうは がっこうは やすみか。@WI(15)↓
;jpn: しゅくだいは したのか。@KEY()↓
;jpn:◆ねるまえに ちゃんと↓
;jpn: はをみがいているか。@WI(15)↓
;jpn: おねしょは してないか。
@KEYNP()
』


;@Habitat:オネット／市役所／秘書室
;@Person:秘書
;@Figure:OL・A
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_DONNA
MSG_ONET_DONNA;
@CHKFGOTO(FLG_TEMP_1,_ONET_DONNA_TMP)
@CHKFGOTO(FLG_WIN_FRANK,_ONET_DONNA2)
◆The Mayor’s office is on the second floor.@KEY()↓
◆You need an appointment before you visit.@KEY()↓
◆I’m going to have to stop you if you try to see the Mayor.
;jpn:◆２かいは しちょうしつですから↓
;jpn: かってに はいっては こまるわ。@KEY()↓
;jpn:◆きっと あなたは↓
;jpn: わたしが とめても↓
;jpn: はいっていくんでしょうけどね。
@KEYNP()
』
_ONET_DONNA_TMP;
◆Look.@WI(20)  I told you so...
;jpn:◆‥‥ほらね。@WI(20)↓
;jpn: わたしが とめたでしょ。
@KEYNP()
』
_ONET_DONNA2;
@CHKFGOTO(FLG_KEY_TABIGOYA,_ONET_DONNA3)
◆Since you beat up the Sharks,@WI(15) you’re the talk of the town.@KEY()↓
◆Mayor Pirkle is waiting for you.
;jpn:◆シャークだんを やっつけたって↓
;jpn: だいひょうばんよ。@WI(15)↓
;jpn: ピカールしちょうが おまちよ。
@KEYNP()
』

_ONET_DONNA3;＃
◆You look like someone who’s going to do something big.
;jpn:◆あなたって なんかやりそうね。
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_DONNA_END)
@KEYNP()
』
_ONET_DONNA_END;＆
@KEY()↓
◆What am I saying−−@WI(15)you did something big!
;jpn:◆‥‥というより なんか↓
;jpn: おおきなことを やった!@WI(15)って↓
;jpn: かんじ。
@KEYNP()
』

;@Habitat:オネット／市役所／市長室
;@Person:市長
;@Figure:ゲーハーピカール
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_PIKARL
MSG_ONET_PIKARL;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_PIKARL_END)
@CHKFGOTO(FLG_KEY_TABIGOYA,_ONET_PIKARL2)
◆Hey@WI(10) hey@WI(10) hey!@WI(15)  I’m Mayor B.H. Pirkle.@WI(15)  It’s so nice to meet you.@KEY()↓
◆You beat up the town bullies,@KEY()↓
◆punched them out big time,@WI(10) kicked their butts,@WI(10) bit their heads off,@KEY()↓
◆spit in their eyes,@WI(30) and made them wet their pants.@KEY()↓
◆Then you forced them to promise not to make any more trouble.@WI(15)  Thank you!@KEY()↓
◆What?@WI(15)↓
◆You want a key to the touring entertainers’ shack?@KEY()↓
◆For someone as great as you,@WI(15) giving you the key could help keep the town peaceful.@KEY()↓
◆However,@WI(15) if you encounter a dangerous situation,@KEY()↓
◆please don’t ask me to take any responsibility.@KEY()↓
◆Do you think I’d have to be responsible for any trouble?↓
  <YES>  <NO>
;jpn:◆や@WI(10)や@WI(10)や@WI(10)や@WI(10)や はじめまして↓
;jpn: @DSP_STS(STS_PC_NAME_NES)さん。@WI(15)↓
;jpn: しちょうのG.H.ピカールです。@KEY()↓
;jpn:◆まちのワルどもを↓
;jpn: まるめてダンゴにして↓
;jpn: ボコボコにたたきまくって@KEY()↓
;jpn:◆けっとばして かみついて↓
;jpn: ツバをひっかけて↓
;jpn: おしっこちびらせて‥‥@KEY()↓
;jpn:◆もうにどと わるさはしません@WI(15) と↓
;jpn: あやまらせてくださったそうで↓
;jpn: かんしゃしております!@KEY()↓
;jpn:◆えっ なんですと?@WI(15)↓
;jpn: たびげいにんのこやの↓
;jpn: カギが ほしいと‥‥@KEY()↓
;jpn:◆よろしいですとも。↓
;jpn: あなたのような すばらしいかたが↓
;jpn: おっしゃることだ。@KEY()↓
;jpn:◆きっと まちのへいわのために↓
;jpn: おおいに やくだつことでしょう。@KEY()↓
;jpn:◆ただし きけんなめに あっても@KEY()↓
;jpn:◆わたしの せきにんを↓
;jpn: ‥‥‥@KEY()↓
;jpn:◆ついきゅうしないようにね。↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_PIKARL_NO,_ONET_PIKARL_YES)
@GOTO(_ONET_PIKARL_YES)
;英語では質問が逆になったので上を変更追加

_ONET_PIKARL_NO;
◆I’m a very important man in these parts.@KEY()↓
◆Do you think I’m important?↓
  <YES>  <NO>
;jpn:◆あなたいじょうに わたしは↓
;jpn: だいじなにんげんなんだ!@KEY()↓
;jpn:◆みのほどを わきまえてください。↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_PIKARL_YES,_ONET_PIKARL_NONO)

_ONET_PIKARL_NONO;
◆Look,@WI(10) I’m the big cheese around here,@KEY()↓
◆and a brat like you should realize when someone is trying to be nice.
;jpn:◆おとなが おとなしく↓
;jpn: たのんでるうちに↓
;jpn: いうことを きくんだ!
@KEYNP()
』

_ONET_PIKARL_YES;
◆You’re such a smart kid...@WI(20)  Here’s the key to the shack.
;jpn:◆はなしのわかる しょうねんだ。↓
;jpn: これが こやのカギです。@WI(15)どうぞ。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_ONET_PIKARL_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_TABIGOYA)
@SAVE_GLOBAL_REG()
@GOSUB(MSG_SUB_GETGOODS_S)
@SETF(FLG_KEY_TABIGOYA)
@KEYNP()
』

_ONET_PIKARL_ITEMFULL;ピカール
@SE(SE_se05_undo)
←
◆Although it’s small,@WI(15) the key is very important.@KEY()↓
◆You seem to have too much to carry.@KEY()↓
◆Get rid of some stuff you don’t need,@WI(15) and come back for the key later on.
;jpn:◆ちいさいものとはいえ↓
;jpn: だいじなカギだ。@KEY()↓
;jpn:◆それにしては↓
;jpn: きみの にもつは いっぱいで↓
;jpn: もう もちきれないようですね。@KEY()↓
;jpn:◆いらないものを しまつして↓
;jpn: また きてください。
@KEYNP()
』

_ONET_PIKARL2;
◆Hey,@WI(30) what’s your name!@KEY()↓
◆I’m so busy with my election that I don’t have time to meet with you.
;jpn:◆やぁ@WI(15) ええと‥‥ナントカさん!↓
;jpn: いま せんきょで いそがしくてね@WI(20)↓
;jpn: おあいてしてられないんですよ。
@KEYNP()
』
_ONET_PIKARL_END;＆
◆Oh,@WI(15) @DSP_STS(STS_PC_NAME_NES)@KEY()↓
◆I saw a picture in the international newspaper of someone who looks like you,@KEY()↓
◆but there’s no way it was you.@KEY()↓
◆Maybe you want to study hard to become Mayor?  Wa ha ha!@KEY()↓
◆Since I returned peace to the town of Onett I was re−elected Mayor.@KEY()↓
◆Are you here to celebrate?↓
  <YES>  <NO>
;jpn:◆おお @DSP_STS(STS_PC_NAME_NES)くん↓
;jpn: がいこくの しんぶんに↓
;jpn: きみににたコが でてたよ。@KEY()↓
;jpn:◆まさか きみじゃないとは↓
;jpn: おもうけど。@KEY()↓
;jpn:◆しっかり べんきょうして↓
;jpn: いずれは しちょうさんにでも↓
;jpn: なりたいってか?!@KEY()↓
;jpn:◆ワッハッハ! わたしは↓
;jpn: オネットのまちの へいわを↓
;jpn: とりもどしたということで@KEY()↓
;jpn:◆また しちょうせんきょに↓
;jpn: とうせんしたんだよ。@KEY()↓
;jpn:◆おいわいに きたんだろう?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_PIKARL_END_YES,_ONET_PIKARL_END_NO)
_ONET_PIKARL_END_NO;
◆Don’t be so shy!@WI(20)  A child shouldn’t be so self conscious.
;jpn:◆てれなくても いいんだ!@WI(20)↓
;jpn: コドモは もっと↓
;jpn: すなおでなくちゃ。
@KEYNP()
』
_ONET_PIKARL_END_YES;
◆Thanks a lot.@KEY()↓
◆From this day forward...  until the day I die...＊sniff＊@KEY()↓
◆I will dedicate my life ＊sniff＊ to peace in Onett...＊boo hoo＊
;jpn:◆いや ありがとう。@KEY()↓
;jpn:◆これからも しぬまで↓
;jpn: オネットのために↓
;jpn: からだをはって がんばるよ。
@KEYNP()
』


;@Habitat:オネット／市役所／市長室
;@Person:側近
;@Figure:おじさんB
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_MAYOR_OZISAN
MSG_ONET_MAYOR_OZISAN;＃
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_MAYOR_OZISAN_END)
◆In the next election please give a speech supporting Mayor Pirkle.@KEY()↓
◆Hee hee hee.
;jpn:◆このつぎの せんきょのときには@KEY()↓
;jpn:◆ぜひ ピカールしちょうの↓
;jpn: おうえんえんぜつを↓
;jpn: おねがいしますね。@KEY()↓
;jpn:◆エッヘッヘ。
@KEYNP()
』
_ONET_MAYOR_OZISAN_END;＆
◆Since way,@WI(10) way back,@WI(15) you and I been very tight.@WI(20)  Pals basically.@KEY()↓
◆Ya ha ha ha ha.
;jpn:◆むかしから ずいぶん↓
;jpn: あなたと わたしは↓
;jpn: なかよしでしたよねぇ。@KEY()↓
;jpn:◆エッヘッヘッヘ。
@KEYNP()
』

;@Habitat:オネット／市役所／市長室
;@Person:ガードマン
;@Figure:警官
;@AppearanceKey:0
;@ActionScript:＊演出コンテ#1.8(FLG_WIN_FRANKによって変化)
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_MAYOR_COP

;----------------------------------------
;@Habitat:オネット／住宅B／住宅B
;@Person:住人
;@Figure:青年
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOUSE_B
MSG_ONET_HOUSE_B;
◆City Hall is to the East,@WI(15) you know,@WI(10)  where the sun rises!
;jpn:◆しやくしょは しがしにあるけど↓
;jpn: しがしってのは あさしがのぼる↓
;jpn: ほうがくでぇい。
@KEYNP()
』


;@Habitat:オネット／住宅C／住宅C
;@Person:住人
;@Figure:ダンゴ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOUSE_C
MSG_ONET_HOUSE_C;
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_ONET_HOUSE_C_MAIN);ポーラ家に帰ってたら‥‥
@CHKFGOTO(FLG_POLA,_ONET_HOUSE_C_LATER)
@CHKFGOTO(FLG_POLA_GRFD,_ONET_HOUSE_C_LATER)
_ONET_HOUSE_C_MAIN;
◆I moved here from the way,@WI(15) way,@WI(15) way away next town.@KEY()↓
◆Her mother has the...what is the name?@WI(20)...uh...Polar Star pre−school.@KEY()↓
◆The pre−school is at @DSP_STS(STS_PC_NAME_PAULA)’s house.@KEY()↓
◆@DSP_STS(STS_PC_NAME_PAULA) uses...what is it called?@WI(15)...uh...magic.
;jpn:◆あたち となりまちから↓
;jpn: おひっこし してきたの。@KEY()↓
;jpn:◆ポーラスターようちえんの↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)おねえちゃまって↓
;jpn: まほうが ちゅかえるのよ。
@KEYNP()
』
_ONET_HOUSE_C_LATER;
@CHKFGOTO(FLG_GLOBAL_POLA_KIDNAPPED,_ONET_HOUSE_C_MAIN);誘拐中
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_ONET_HOUSE_C_MAIN)
◆I wanted to see you, @DSP_STS(STS_PC_NAME_PAULA)!
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)おねえちゃまに↓
;jpn: あいたかったの!
@KEY()↓
』


;@Habitat:オネット／住宅E／住宅E
;@Person:住人
;@Figure:おじさんD
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOUSE_E
MSG_ONET_HOUSE_E;
◆When you’re in trouble,@WI(15) do you think you’d ever like to have a hint?@KEY()↓
<Yes>
<No>
;jpn:◆くるしいとき ヒントがあれば↓
;jpn: いいなーと おもったことは↓
;jpn: ありますか?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_HOUSE_E_YES,_ONET_HOUSE_E_NO)

_ONET_HOUSE_E_NO;
◆All righty then,@WI(15) you’re on your own.@WI(15)  Good luck!
;jpn:◆では いつまでもひとりで↓
;jpn: ガンバッてください。
@KEYNP()
』

_ONET_HOUSE_E_YES;
◆Why don’t you get a hint from the next house?
;jpn:◆では ヒントはとなりのいえで↓
;jpn: きいてみてください。
@KEYNP()
』


;@Habitat:オネット／住宅G／住宅G
;@Person:住人
;@Figure:ハット
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOUSE_G
MSG_ONET_HOUSE_G;
@CHKFGOTO(FLG_TLPT_TWSN,_ONET_HOUSE_G_LATER)
◆Mr. Lier X. Agerate,@WI(15) the treasure hunter,@WI(15) finally found something interesting.@KEY()↓
◆I heard he will only show it to you.
;jpn:◆トレジャー・ハンターの↓
;jpn: ライヤーさん‥‥とうとう↓
;jpn: へんなものを みつけたらしいね。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)ちゃんだけには↓
;jpn: みせるとかって はなしだよ。
@KEYNP()
』
_ONET_HOUSE_G_LATER;
◆The hotel is located in the East.@KEY()↓
◆I’m sad ’cause I only got this short message.
;jpn:◆ホテルは にし。@KEY()↓
;jpn:◆おれ こんなセリフしかなくって↓
;jpn: さみしいよ。
@KEYNP()
』


;@Habitat:オネット／住宅H／住宅H
;@Person:住人
;@Figure:少女C
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOUSE_H
MSG_ONET_HOUSE_H;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_HOUSE_H_AFTER)
◆I wonder if ”EarthBound” has been released yet.
;◆It’s been delayed for a long time.
;jpn:◆「マザー２」って↓
;jpn: もう はつばいになったのかな。↓
;jpn: ずいぶん おくれてたけど‥‥。
@KEYNP()
』
_ONET_HOUSE_H_AFTER;＆
◆Listen to this!@WI(20)  I finished EarthBound!
;jpn:◆ねぇ きいてきいて↓
;jpn: わたし 「マザー２」↓
;jpn: エンディングまで いったのよ。
@KEYNP()
』

;----------------------------------------
;@Habitat:オネット／図書館／受付
;@Person:受付嬢
;@Figure:OL・G
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_LUCY
MSG_LIBRARY_LUCY;
◆Hi!
;jpn:◆ハーイ!
@KEY()↓
@CHKFGOTO(FLG_ONET_LUCY_CHU,_LIBRARY_LUCY_2)
@CHKFGOTO(FLG_ITEM_MAP,_LIBRARY_LUCY_2)
@CHKFGOTO(FLG_ITEM_MUKUCHI,_LIBRARY_LUCY_MUKUCHI)
◆Kids can borrow only maps at this library.@KEY()↓
◆Do you want to borrow one?↓
<Yes>
<No>
;jpn:◆こどもに かしだしできるのは↓
;jpn: ちず くらいのものだけど いい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_LIBRARY_LUCY_MAP_YES,_LIBRARY_LUCY_MAP_NO)
_LIBRARY_LUCY_MAP_NO;
◆A man without a map isn’t popular with the girls.@KEY()↓
◆Do you want one?@KEY()↓
<Yes>
<No>
;jpn:◆ちずも もってないおとこなんて↓
;jpn: もてないわよ。もってくでしょ?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_LIBRARY_LUCY_MAP_YES,_LIBRARY_LUCY_MAP_NO)
@GOTO(_LIBRARY_LUCY_MAP_NO)

_LIBRARY_LUCY_MAP_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_LIBRARY_LUCY_MAP_GOODSFULL)
◆Here’s a map.@KEY()↓
◆Onett isn’t the only thing on the map.@KEY()↓
◆All the info is there, except for the info that isn’t there.@KEY()↓
◆Pressing the X Button allows you to view the map at any time.@WI(15)  How convenient!@KEY()↓
◆You know, the X Button...located near the top.@WI(15)  Ha ha ha.
;jpn:◆じゃ どうぞ。@KEY()↓
;jpn:◆オネットのまちだけじゃなく↓
;jpn: のっていないばしょ いがいは↓
;jpn: ぜんぶ このちずにのってるし@KEY()↓
;jpn:◆Xボタンをおせば いつでも↓
;jpn: すぐに みることができるから↓
;jpn: べっんりよぉ。@KEY()↓
;jpn:◆ウフッ Xボタンっていうのは↓
;jpn: ‥‥あなたのしってる その↓
;jpn: あおい ボタンよ。@WI(15)ウフフ。
@KEY()↓
@GOODSIN_PLAYER(0,GDS_TOOL_TOWN_MAP)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_ITEM_MAP)
@KEYNP()
』
_LIBRARY_LUCY_MAP_GOODSFULL;
◆I suggest you bring a map along, even if you have to give up something else.@KEY()↓
◆You seem to be carrying many worthless items.
;jpn:◆わたしなら↓
;jpn: ほかのものを すてても↓
;jpn: ちずを もっていくけど@KEY()↓
;jpn:◆あなたのにもつは↓
;jpn: つまんないもので↓
;jpn: いっぱいのようね。
@KEYNP()
』
_LIBRARY_LUCY_2;
◆It’s not necessary to return the map now.@KEY()↓
◆Come back in the year ２００１ to return it.
;jpn:◆まちのちずは↓
;jpn: まだ かえさなくっても↓
;jpn: だいじょうぶよ。@KEY()↓
;jpn:◆２００１ねんくらいになったら↓
;jpn: かえしにきてちょうだいね!
@KEYNP()
』

_LIBRARY_LUCY_MUKUCHI;
◆Please return our book ”Overcoming Shyness” later!
;jpn:◆「むくちをなおすほん」↓
;jpn: そのうち かえしにきてね!
@KEYNP()
』
MSG_LIBRARY_LUCY_RECEIVE;無口をなおすほん使うと
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_BOOK_CHAT)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
@CHKFGOTO(FLG_WIN_GIEGU,_LUCY_RECEIVE_CHU)
◆That book’s great!@WI(20)  Study it hard.
;jpn:◆そのほん いいほんよ。↓
;jpn: しっかり べんきょうしてね。
@KEYNP()
』
_LUCY_RECEIVE_CHU;
◆...Finally,@WI(15) you’ve come to return the book.@WI(20)  Seems like you finished it.@KEY()↓
◆You’re such a good boy.@WI(20)  As a reward,@WI(15) I’ll give you a kiss.@WI(30)  Smack!
;jpn:◆‥‥やっと かえしにきたわね。@WI(20)↓
;jpn: そうとう よみこんだようね。@KEY()↓
;jpn:◆べんきょうかね あなた。@WI(20)↓
;jpn: ごほうびに チューしてあげる。@WI(30)↓
;jpn: ‥‥チュッ。
@SE(SE_se74_my_get)
@KEYNP()
@GOODSOUT(PC_ALL,GDS_TOOL_BOOK_CHAT)
@SETF(FLG_ONET_LUCY_CHU)
』

;@Habitat:オネット／図書館／受付
;@Person:客
;@Figure:船長
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_LIBRARY_OLDMAN
MSG_ONET_LIBRARY_OLDMAN;図書館の老人
◆At ”Giant Step” there’s a monster guarding that spot from the outside world.@KEY()↓
◆No one knows when the monster made Giant Step its territory.@KEY()↓
◆I wonder if he’s stronger than my wife...
;jpn:◆「ジャイアントステップ」↓
;jpn: というところには↓
;jpn: いつのまにやら@KEY()↓
;jpn:◆その ばしょを まもる↓
;jpn: ばけものが すみつくように↓
;jpn: なったというが‥‥そいつは@KEY()↓
;jpn:◆うちの かーちゃんよりも↓
;jpn: つよいだろうか。
@KEYNP()
』


;@Habitat:オネット／図書館／受付
;@Person:無口の本情報の人
;@Figure:マスク
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_MUKUCHI
MSG_LIBRARY_MUKUCHI;
@CHKFGOTO(FLG_CAPSULE_OK,_LIBRARY_MUKUCHI_LATER)
◆.....↓
◆     .....↓
◆          .....@KEY()↓
◆(A man of few words.@WI(15)  It’s useless talking to him now.)
;jpn:◆‥‥‥。↓
;jpn:    ‥‥‥。↓
;jpn:       ‥‥‥。@KEY()↓
;jpn:◆(かれは とても むくちなので↓
;jpn: いまは これいじょう↓
;jpn: はなしかけても むだだ)
@KEYNP()
』

_LIBRARY_MUKUCHI_LATER;＃
@CHKFGOTO(FLG_ITEM_MUKUCHI,_LIBRARY_MUKUCHI_END)
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_LIB_MUKUCHI_LATER_NESS_DEAD)
◆Oh,@WI(10) hi @DSP_STS(STS_PC_NAME_NES).@KEY()↓
;jpn:◆やぁ @DSP_STS(STS_PC_NAME_NES)くんじゃないか↓
_LIB_MUKUCHI_LATER_2;
◆It’s another nice day.  What?@WI(15)  You’d like the book ”Overcoming Shyness”?@KEY()↓
◆I’ve read it.@WI(10)  It’s a great book.@WI(10)  So you want to overcome shyness also?@KEY()↓
◆You should be able to find it on the bookcase.
;jpn: きょうも いいてんきだねぇ。↓
;jpn: えっ むくちをなおすほんかい?@KEY()↓
;jpn:◆そのほんだったら ぼくも↓
;jpn: よんだのさ。それはとっても↓
;jpn: いいほんだよ。@WI(15)あっ きみも@KEY()↓
;jpn:◆むくちをなおしたいんだね。@WI(20)↓
;jpn: ほんだなを よくチェックすれば↓
;jpn: あのほん‥‥@WI(15)あるはずだよ。
@KEYNP()
@SETF(FLG_LIBRARY_INFO_MUKUCHI)
』
_LIB_MUKUCHI_LATER_NESS_DEAD;
◆Are you a friend of @DSP_STS(STS_PC_NAME_NES)?↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)くんのともだちかい?
↓
@GOTO(_LIB_MUKUCHI_LATER_2)

_LIBRARY_MUKUCHI_END;無口を直す本を手に入れた後
◆Hi!@WI(20)  Nice to meetchya!@KEY()↓
◆I’d really love to sit down and chat with you someday.@KEY()↓
◆I’ll talk about my adventure,@KEY()↓
◆and you can tell me about all of your mistakes.
;jpn:◆ハーイ!@WI(20)↓
;jpn: ナイス ツー ミーチュー。@KEY()↓
;jpn:◆また いつか きみとは↓
;jpn: ゆっくり おしゃべりしたいな。@KEY()↓
;jpn:◆ぼくの ぼうけんや↓
;jpn: きみの しっぱいだんをね!
@KEYNP()
』

;@Habitat:オネット／図書館／ブックルーム１
;@Person:無口A
;@Figure:少女A
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_PEOPLE_A
MSG_LIBRARY_PEOPLE_A;
@CHKFGOTO(FLG_TEMP_1,_LIBRARY_PEOPLE_A2)
◆.....
;jpn:◆‥‥‥
@KEYNP()
@SETF(FLG_TEMP_1)
』

_LIBRARY_PEOPLE_A2;
◆Shhh!@WI(30)  You’re bothering people!
;jpn:◆しーっ!@WI(30)↓
;jpn: まわりのひとに めいわくでしょ!
@KEYNP()
@CLRF(FLG_TEMP_1)
』
MSG_LIBRARY_A_RECEIVE;無口を
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_BOOK_CHAT)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆The truth is,@WI(15) I like to talk!@KEY()↓
◆Since I’m in a library,@WI(15) I’m trying to be quiet.  Oh man!
;jpn:◆わたしは ほんとうは↓
;jpn: おしゃべりが すきなのよ!@KEY()↓
;jpn:◆としょかんだから↓
;jpn: しずかにしてるだけなのに↓
;jpn: バカね。
@KEYNP()
』

;@Habitat:オネット／図書館／ブックルーム１
;@Person:UFO情報の人
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_PEOPLE_C
MSG_LIBRARY_PEOPLE_C;＃
@CHKFGOTO(FLG_WIN_GIEGU,_LIBRARY_PEOPLE_C_END)
◆Recently,@WI(15) I sensed the presence of UFO’s flying around...@KEY()↓
◆or am I just dreaming?
;jpn:◆このごろ ずいぶん UFOが↓
;jpn: とんできてるような↓
;jpn: きがするんだけど‥‥@KEY()↓
;jpn:◆めの さっかくかなぁ。
@KEYNP()
』
_LIBRARY_PEOPLE_C_END;＆
◆These days have been peaceful.@KEY()↓
◆I miss the UFO’s and monsters,@WI(15) ’cause they haven’t been around recently.
;jpn:◆このところ しばらく↓
;jpn: へいわなんだよね。@KEY()↓
;jpn:◆でなくなってみると↓
;jpn: UFOや ばけものたちも↓
;jpn: なつかしいなぁ。
@KEYNP()
』


;@Habitat:オネット／図書館／ブックルーム２
;@Person:無口B
;@Figure:少年B
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_PEOPLE_D
MSG_LIBRARY_PEOPLE_D;
@CHKFGOTO(FLG_TEMP_2,_LIBRARY_PEOPLE_D2)
◆.....@KEYNP()
@SETF(FLG_TEMP_2)
』

_LIBRARY_PEOPLE_D2;
◆Quiet!
;jpn:◆おしゃべりするなってば!
@KEYNP()
@CLRF(FLG_TEMP_2)
』
MSG_LIBRARY_D_RECEIVE;無口を直す本を
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_BOOK_CHAT)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆Shh!@WI(15)  Shh!@KEY()↓
◆You’re too loud!@WI(20)  Try to move around quietly,@WI(15) Mr. Noisy pants.
;jpn:◆しーっ しーっ!@KEY()↓
;jpn:◆ほんを バサバサするなよ。↓
;jpn: うるさいから。
@KEYNP()
』

;@Habitat:オネット／図書館／ブックルーム２
;@Person:無口C
;@Figure:OL・F
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_PEOPLE_A


;@Habitat:オネット／図書館／ビデオルーム
;@Person:Gステップ情報の人
;@Figure:サラリーマンD
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LIBRARY_PEOPLE_B
MSG_LIBRARY_PEOPLE_B;＃
@CHKFGOTO(FLG_WIN_GIEGU,_LIBRARY_PEOPLE_B_END)
◆I’m researching ”Giant Step.”@WI(15)  It’s located in the Northwest position of Onett.@KEY()↓
◆I heard it possesses a special power!
;jpn:◆オネットのまちの ほくせいにある↓
;jpn: ジャイアントステップについて↓
;jpn: しらべてるんだ。@KEY()↓
;jpn:◆なんか どうも とくべつの↓
;jpn: パワーを もってる↓
;jpn: ばしょらしいんだよ。
@KEYNP()
』
_LIBRARY_PEOPLE_B_END;＆
◆Clap,@WI(10) clap,@WI(10) clap.@KEY()↓
◆When I see you,@WI(15) I get the urge to give you a hand.
;jpn:◆パチ パチ パチ。@WI(20)↓
;jpn: きみにあうと つい↓
;jpn: はくしゅしたくなっちゃうんだ。
@KEYNP()
』

;----------------------------------------
;@Habitat:オネット／病院／受付
;@Person:受付嬢
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOSPITAL_USHER
MSG_ONET_HOSPITAL_USHER;@MaltaAppended
@GOSUB(MSG_NURSE_ONET)
』


;@Habitat:オネット／病院／診察室
;@Person:医者
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOSPITAL_DOCTOR
MSG_ONET_HOSPITAL_DOCTOR;@MaltaAppended
@GOSUB(MSG_DOCTOR_ONET)
』


;@Habitat:オネット／病院／診察室
;@Person:付き添い
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOSPITAL_NURSE
MSG_ONET_HOSPITAL_NURSE;
◆I heard that around here,@WI(15) our doctor is No. １.  Hee hee hee...
;jpn:◆うちの せんせいって↓
;jpn: このへんじゃ ピカ１のうでまえ@KEY()↓
;jpn:◆らしいのよね。うふふ‥‥
@KEYNP()
』


;@Habitat:オネット／病院／廊下
;@Person:ケガ人
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOSPITAL_PATIENT
MSG_ONET_HOSPITAL_PATIENT;
◆When I came to visit my friend at this hospital,@KEY()↓
◆I somehow slipped and fell in the hallway.@KEY()↓
◆So now I’m staying in the hospital too.@KEY()↓
◆This could be the basis for a great, tragic tearjerker.@WI(20)  Well, maybe not...!
;jpn:◆このびょういんに↓
;jpn: ともだちの みまいにきてね。@KEY()↓
;jpn:◆ろうかで すべって↓
;jpn: ころんで↓
;jpn: じぶんが にゅういんしたんだ。@KEY()↓
;jpn:◆このはなし↓
;jpn: ドラマチックだろ。@KEY()↓
;jpn:◆そうでもない‥‥か。
@KEYNP()
』


;----------------------------------------
;@Habitat:オネット／水野さんの家／１階
;@Person:水野さん
;@Figure:水野さん
;@AppearanceKey:FLG_1FMIZUNO_APPEAR/on
;@ActionScript:＊ドア塞いで正面向き
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_INSEKI_MIZUNO_1F
MSG_INSEKI_MIZUNO_1F;
@CHKFGOTO(FLG_WIN_GIEGU,MSG_ONET_MIZUNO_END)
@CHKFGOTO(FLG_TLPT_TWSN,_INSEKI_MIZUNO_1F2)
◆I’m doing this because I trust you.@KEY()↓
◆First,@WI(15) let’s go to the basement.
;jpn:◆あんたを おとことみこんで↓
;jpn: そうだんしたい。@KEY()↓
;jpn:◆まず ちかしつを みせてやるよ。
@KEY()
@CLOSEALL()
@WI(60)
@OPEN(1)
◆Ah!@WI(15)  I can tell by the look on your face you don’t want to hang out,@WI(10) do you?@KEY()↓
◆That’s all right.@WI(20)  After all,@WI(15) we are not even related.@KEY()↓
◆I know you think I’m a big liar but maybe I’ll surprise you!
@KEYNP()
;jpn:◆あっ!@WI(15) おれと つきあうのが↓
;jpn: イヤなんだな‥‥@WI(20)かおで わかる。@KEY()↓
;jpn:◆もういい。@WI(15) おれと あんたは↓
;jpn: しょせんは たにんだ。@KEY()↓
;jpn:◆おれを ただのホラふきだと↓
;jpn: なめている あんたを‥‥↓
;jpn: びっくりさせてやろうかね。@KEY()
@CLOSEALL()
@GOSUB(MSG_EVT_13_MIZUNO_A);水野さん地下へ降りて行く→Sイベントファイルへ。
@CLRF(FLG_1FMIZUNO_APPEAR)
@SETF(FLG_B1MIZUNO_APPEAR)
』

_INSEKI_MIZUNO_1F2;
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_INSEKI_MIZUNO_1F2_NESS_DEAD)
◆I’m doing this because I trust you.@KEY()↓
◆First,@WI(15) let’s go to the basement.@KEY()↓
◆Ah!@WI(15)  I can tell by the look on your face you don’t want to hang out,@WI(10) do you?@KEY()↓
◆That’s all right.@WI(20)  After all,@WI(15) we are not even related.@KEY()↓
◆Someone like you should just hang around that dreamer Gerardo Montague.
;jpn:◆あんたを おとことみこんで↓
;jpn: そうだんしたい。@KEY()↓
;jpn:◆まず ちかしつを みせてやるよ。@KEY()↓
;jpn:◆あっ!@WI(15) おれと つきあうのが↓
;jpn: イヤなんだな‥‥@WI(20)かおで わかる。@KEY()↓
;jpn:◆もういい。@WI(15) おれと あんたは↓
;jpn: しょせんは たにんだ。@KEY()↓
;jpn:◆あんたも ショージ・モッチーと↓
;jpn: つるんで ゆめをみてれば↓
;jpn: いいんだ。
@KEYNP()
』
MSG_ONET_MIZUNO_END;＆
◆You’re being vain, @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆Life is...@WI(20)  Not that easy.@KEY()↓
◆You just saved the Earth from a crisis...@WI(15)  Don’t act so stuck up.@KEY()↓
◆...When I was younger I too saved the Earth many times.@KEY()↓
◆I live a modest life.@WI(20)  That’s the way it should be.@KEY()↓
◆Don’t you think a real hero is someone like me?@KEY()↓
<Yes>
<No>
;jpn:◆@DSP_STS(STS_PC_NAME_NES)ちゃん@WI(15)↓
;jpn: あんたは いま↓
;jpn: てんぐになっているとおもうけど@KEY()↓
;jpn:◆じんせいってのはね‥‥@WI(20)↓
;jpn: そんなもんじゃないんだ。@KEY()↓
;jpn:◆ちょっとくらい↓
;jpn: ちきゅうのききを↓
;jpn: すくったからって‥‥@KEY()↓
;jpn:◆いいきにならないほうが いいよ。@KEY()↓
;jpn:◆‥‥おれも わかいときは↓
;jpn: なんども ちきゅうのききを↓
;jpn: すくったけど@KEY()↓
;jpn:◆けんきょに いきてきた。@WI(20)↓
;jpn: ま そういうことだ。@KEY()↓
;jpn:◆ほんとうのヒーローは↓
;jpn: いがいと おれみたいな↓
;jpn: おとこだろうな。@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_MIZUNO_END_YES,_ONET_MIZUNO_END_NO)
_ONET_MIZUNO_END_NO;いいえ
◆@DSP_STS(STS_PC_NAME_NES),↓
◆Don’t be such a snob!
;jpn:◆あんたは てんぐになってる!
@KEYNP()
』
_ONET_MIZUNO_END_YES;はい
◆When you grow up,@WI(15) why don’t you become my partner and we’ll make lots of money.
;jpn:◆おとなになったら↓
;jpn: おれと てをくんで↓
;jpn: ひとやま あてようや。
@KEYNP()
』
_INSEKI_MIZUNO_1F2_NESS_DEAD;
◆You might think me a fool but when I do a job,@WI(15) I do it well.@KEY()↓
◆I’m a@WI(15) man@WI(10)’s man.  I’ll be a big hero.@KEY()↓
◆Ignore me for now if you want...
;jpn:◆あんたは ばかにして↓
;jpn: いるかもしれないが@KEY()↓
;jpn:◆なにせ おれは@WI(20)
;jpn: やるときゃやる!@WI(20) おとこだ。@KEY()↓
;jpn:◆ゲームがおわったころには↓
;jpn: ヒーローになってるかもしれんよ。@KEY()↓
;jpn:◆せいぜい いまは↓
;jpn: むししているが いいさ。
@KEYNP()
』

;----------------------------------------
;@Habitat:オネット／隠れ家／隠れ家
;@Person:ひみつ基地隊員A
;@Figure:ハット
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_KAKUREGA_A
MSG_KAKUREGA_A;＆
@CHKFGOTO(FLG_WIN_GIEGU,_KAKUREGA_A_END)
@CHKFGOTO(FLG_TEMP_1,_KAKUREGA_A2)
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_KAKUREGA_A_NESS_DEAD)
◆You’ve grown since I last saw you.@WI(20)  You’re beginning to look like a man.@KEY()↓
◆You’re so cool!@KEY()↓
◆I...@WI(15)  I think I really like you.@KEY()↓
◆Well,@WI(15) you know what I mean.
;jpn:◆@DSP_STS(STS_PC_NAME_NES)@WI(15) ちょっとみないうちに↓
;jpn: おとこっぽい かおつきに↓
;jpn: なったなぁ。@KEY()↓
;jpn:◆すっごく カッコイイよ。@KEY()↓
;jpn:◆おれ‥‥@WI(15)↓
;jpn: すきに なっちゃいそうだ。@KEY()↓
;jpn:◆いや↓
;jpn: そういういみじゃ なく。
@KEYNP()
@SETF(FLG_TEMP_1)
』
_KAKUREGA_A2;
◆You know what I mean.
;jpn:◆そういういみじゃ ないんだよ。
@KEYNP()
』
_KAKUREGA_A_NESS_DEAD;
◆Aren’t you @DSP_STS(STS_PC_NAME_NES)’s new friend?@KEY()↓
◆How could I tell?@WI(20)  It’s just a feeling!@KEY()↓
◆You might have the feeling that @DSP_STS(STS_PC_NAME_NES) is around.
;jpn:◆@DSP_STS(STS_PC_NAME_NES)の↓
;jpn: あたらしい↓
;jpn: ともだちだね?@KEY()↓
;jpn:◆どうしてわかるかって?↓
;jpn: ふんいきだよ ふんいき!@KEY()↓
;jpn:◆なんか @DSP_STS(STS_PC_NAME_NES)が↓
;jpn: そばに いそうな さ。
@KEYNP()
』
_KAKUREGA_A_END;＆
◆Hi, @DSP_STS(STS_PC_NAME_NES)!@WI(20)  It’s starting to get crowded in this hide out.@KEY()↓
◆I was considering moving to Beak’s Point.@KEY()↓
◆What do you think?↓
<Yes>
<No>
;jpn:◆やあ @DSP_STS(STS_PC_NAME_NES)!↓
;jpn: このカクレガも↓
;jpn: ちょっと てぜまになったから@KEY()↓
;jpn:◆クチバシみさきあたりに↓
;jpn: ひっこそうと おもうんだけど↓
;jpn: どうだろう?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_KAKUREGA_A_YES,_KAKUREGA_A_NO)
_KAKUREGA_A_NO;いいえ
◆You’re right.@WI(30)  This area might be just the right size for us.
;jpn:◆そうだな。@WI(30)↓
;jpn: おれたちには これくらいの↓
;jpn: ひろさが ぶんそうおうかな。
@KEYNP()
』
_KAKUREGA_A_YES;
◆Do you really agree?@WI(20)  Let’s build a strong,@WI(15) sturdy shack.
;jpn:◆そうか さんせいしてくれるか。@WI(20)↓
;jpn: また りっぱな こやを↓
;jpn: たてようぜ。
@KEYNP()
』

;@Habitat:オネット／隠れ家／隠れ家
;@Person:ひみつ基地隊員B
;@Figure:インディー
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_KAKUREGA_B
MSG_KAKUREGA_B;
@CHKFGOTO(FLG_WIN_GIEGU,_KAKUREGA_B_END)
@CHKFGOTO(FLG_POLA_GRFD,_KAKUREGA_B2)
@CHKFGOTO(FLG_POLA,_KAKUREGA_B2)
◆I had a dream about you,@WI(20) and you were traveling with a cute girl.@KEY()↓
◆If the dream comes true,@WI(15) say hi to her.@WI(20)  After all,@WI(15) I’m single...
;jpn:◆おれ おまえが カワイイ@KEY()↓
;jpn:◆おんなのこと たびをしてる↓
;jpn: ゆめを みたよ。@KEY()↓
;jpn:◆もし ほんとになったら↓
;jpn: よろしく いっといてくれよ。@WI(15)↓
;jpn: おれも どくしん だし‥‥。
@KEYNP()
』

_KAKUREGA_B2;
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_KAKUREGA_B_NESS_DEAD)
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_KAKUREGA_B_PAULA_DEAD)
◆Love!
;jpn:◆ラブ!
@KEYNP()
』

_KAKUREGA_B_PAULA_DEAD;
◆I maybe wrong,@WI(15) but I feel like you’re being accompanied by a cute girl.
;jpn:◆なんかおまえが カワイイ@WI(30)↓
;jpn: おんなのこを つれてるような↓
;jpn: きがするけど@KEY()↓
;jpn:◆きのせいかなあ‥‥
@KEYNP()
@!
_KAKUREGA_B_END;＆
◆You...@WI(20)seem to be gaining self confidence or something...@KEY()↓
◆During your trip,@WI(15) were you popular at your destinations?@KEY()↓
◆...I’m jealous.@WI(15)  I wish I was popular like you...
;jpn:◆おまえ‥‥@WI(20)なんだか↓
;jpn: おとこの「じしん」みたいなものが↓
;jpn: でてきたなぁ。@KEY()↓
;jpn:◆たびさきで もてたりしたわけ?@WI(20)↓
;jpn: ‥‥いいなぁ@WI(15)↓
;jpn: おれなんか ダメさ。
@KEYNP()
』
_KAKUREGA_B_NESS_DEAD;
◆How did you find this hide out?@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES) must have told you about it.
;jpn:◆おまえ@GOSUB(MSG_SUB_TATI) よく↓
;jpn: この カクレガを↓
;jpn: みつけられたなぁ。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)が↓
;jpn: このばしょを↓
;jpn: ばらしちゃったんだな。
@KEYNP()
@!

;@Habitat:オネット／隠れ家／隠れ家
;@Person:ひみつ基地隊員C
;@Figure:ヘルメット
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_KAKUREGA_C
MSG_KAKUREGA_C;
@CHKFGOTO(FLG_WIN_GIEGU,_KAKUREGA_C_END)
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_KAKUREGA_C_NESS_DEAD)
@CHKFGOTO(FLG_ITEM_KAKUREGA_C,_KAKUREGA_C2)
◆I’ll give you my @DSP_GOODS(GDS_EQUIP_CAP_MISTER),@WI(15) I know you’ve wanted it for a long time.@KEY()↓
◆It’s the best cap for someone really brave like you.
;jpn:◆まえから @DSP_STS(STS_PC_NAME_NES)が↓
;jpn: ほしがってた↓
;jpn: ミスターベースボールの ぼうし@KEY()↓
;jpn:◆おまえに やるよ。@KEY()↓
;jpn:◆ゆうかんな おまえにこそ↓
;jpn: ふさわしいと おもってさ。
@KEY()↓
_KAKUREGA_C_MAIN;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_KAKUREGA_C_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_EQUIP_CAP_MISTER)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_ITEM_KAKUREGA_C)
@KEYNP()
』
_KAKUREGA_C_ITEMFULL;
←
@SE(SE_se05_undo)
◆Ah!@WI(20)  You can’t carry anything else.@KEY()↓
◆You should either sell or throw away some junk and come back.
;jpn:◆えっ! もちきれなそうだぞ。@WI(15)↓
;jpn: ほかのガラクタを うるなり↓
;jpn: すてるなりして またおいでよ。
@KEYNP()
』
_KAKUREGA_C2;
◆I’d like to go on an adventure with you once I become a little stronger.
;jpn:◆おれも もうすこし つよけりゃ↓
;jpn: おまえと ぼうけんしてみたいな。
@KEYNP()
』
_KAKUREGA_C_NESS_DEAD;
@CHKFGOTO(FLG_ITEM_KAKUREGA_C,_KAKUREGA_C_DEAD_B)
◆I’ll give you my @DSP_GOODS(GDS_EQUIP_CAP_MISTER), I know @DSP_STS(STS_PC_NAME_NES) wanted it for a long time.@KEY()↓
◆Putting this cap on will make you stronger.@WI(15)  Yep,@WI(5) yep,@WI(5) yep!
;jpn:◆まえから @DSP_STS(STS_PC_NAME_NES)が↓
;jpn: ほしがってた↓
;jpn: ミスターベースボールの ぼうし@KEY()↓
;jpn:◆おまえに やるよ。@KEY()↓
;jpn:◆これを かぶって↓
;jpn: いっそう つよくなれよ!@KEY()↓
;jpn:◆な!
@KEY()↓
@GOTO(_KAKUREGA_C_MAIN)

_KAKUREGA_C_DEAD_B;
◆Are you @DSP_STS(STS_PC_NAME_NES)’s friend?@KEY()↓
◆Did he ever talk about me?@KEY()↓
<Yes>
<No>
;jpn:◆おまえ @DSP_STS(STS_PC_NAME_NES)の
;jpn: ともだちか。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)↓
;jpn: おれのこと↓
;jpn: いつも うわさしてただろ?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_KAKUREGA_C_DEAD_B_YES,_KAKUREGA_C_DEAD_B_NO)
_KAKUREGA_C_DEAD_B_NO;＠
◆Maybe he didn’t talk much about his friends.
;jpn:◆おとこどうしの↓
;jpn: ゆうじょうについては↓
;jpn: あんまり かたらないやつだった。
@KEYNP()
』
_KAKUREGA_C_DEAD_B_YES;
◆Oh!@WI(20)  That’s the @DSP_STS(STS_PC_NAME_NES) I know...!
;jpn:◆そうかー↓
;jpn: @DSP_STS(STS_PC_NAME_NES)のやつー!
@KEYNP()
』
_KAKUREGA_C_END;＆
◆@DSP_STS(STS_PC_NAME_NES),@WI(15) I’ve been thinking about our gang’s name.@KEY()↓
◆It’s ”We’ll laugh about it tomorrow.”@KEY()↓
◆How do you like it?↓
<Yes>
<No>
;jpn:◆@DSP_STS(STS_PC_NAME_NES) おれ@KEY()↓
;jpn:◆おれたちのチームの↓
;jpn: キャッチフレーズを↓
;jpn: かんがえたんだ。@KEY()↓
;jpn:◆「ともよ あした わらおう」↓
;jpn: っていうんだ。@KEY()↓
;jpn:◆どうかな?↓
;jpn: いいと おもうかい?↓
;jpn:  <いい>  <そうでもない>
@DSP_ITEM(2)
@SELGOTO(_KAKUREGA_C_END_YES,_KAKUREGA_C_END_NO)
_KAKUREGA_C_END_NO;そうでもない
◆...Okay.@WI(30)  Laugh doesn’t really mean ”laugh.”@KEY()↓
◆It means ”chuckle.”
;jpn:◆‥‥そうか。@WI(30)↓
;jpn: 「わらおう」っていうのはさぁ↓
;jpn: わらうっていうことじゃなく@KEY()↓
;jpn:◆あかるくっていうような↓
;jpn: いみなんだけどな。
@KEYNP()
』
_KAKUREGA_C_END_YES;いい
◆My philosophy is ”peace to all men”!@KEY()↓
◆Really? You like it?@WI(20)  I knew you would understand.
;jpn:◆コンセプトは↓
;jpn: 「おとこのゆうじょう」って↓
;jpn: ことなんだよ。@KEY()↓
;jpn:◆そうか きにいってくれたか。@WI(20)↓
;jpn: @DSP_STS(STS_PC_NAME_NES)なら↓
;jpn: わかると おもったよ。
@KEYNP()
』
;----------------------------------------
;@Habitat:オネット／フィールド／隕石跡
;@Person:はぐれたピッキー
;@Figure:ピッキー
;@AppearanceKey:FLG_INSEKI/off
;@ActionScript:＊ネスに近寄って台詞MSG_INSEKI_PICKEY発行
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_INSEKI_PICKEY
;★特殊イベントメッセージ(S_EVENT.MSG)へ

;@Habitat:オネット／フィールド／水野さんの家の前
;@Person:水野さん
;@Figure:水野さん
;@AppearanceKey:FLG_ONET_AMBRAMI/off
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_INSEKI_MIZUNO
MSG_INSEKI_MIZUNO;ライヤー・ホーランドさん
@CHKF(FLG_YAZIUMA_DISAPPEAR)@FALSE_GOTO(_INSEKI_MIZUNO_YAZIUMA)
@CHKFGOTO(FLG_PICKEY,_INSEKI_MIZUNO_LATER)
◆Hey,@WI(10) @DSP_STS(STS_PC_NAME_NES)!@KEY()↓
◆I was too busy to investigate,@WI(15) but I heard a child’s voice on the hilltop.@KEY()↓
◆I’m a busy man,@WI(15) but when I do a job,@WI(15) I do it well.@WI(20)  I’m a@WI(10) man@WI(5)’s man.
;jpn:◆やぁ @DSP_STS(STS_PC_NAME_NES)ちゃん@KEY()↓
;jpn:◆ちいさいこどもが うえのほうに↓
;jpn: いたみたいだったけど↓
;jpn: おれは いそがしくてさ。@KEY()↓
;jpn:◆なにせ いそがしいから‥‥↓
;jpn: おれって にんげんは↓
;jpn: やるときゃやるおとこだけどね。
@KEYNP()
』

_INSEKI_MIZUNO_YAZIUMA;
@CHKFGOTO(FLG_TEMP_9,_INSEKI_MIZUNO_YAZIUMA_TEMP)
◆Hey @DSP_STS(STS_PC_NAME_NES),@WI(15) hiya buddy!@KEY()↓
◆A meteorite fell down and went boom!@WI(20)  It was a real mess for a while.@KEY()↓
◆I was fine because I always eat garlic and workout to help make my body stronger.@KEY()↓
◆However,@WI(15) the weaker citizens probably fainted.@KEY()↓
◆I also want to tell you...@WI(15) whoops!@KEY()↓
◆I almost told you about my...@KEY()↓
◆Uh,@WI(15) by the way @DSP_STS(STS_PC_NAME_NES),@WI(15) did you check my billboard?@KEY()↓
◆I wrote the message myself.@KEY()↓
◆That’s my real job,@WI(15) you know...I’m a billboard guy.@KEY()↓
◆Why don’t you check out my work?
;jpn:◆やぁ @DSP_STS(STS_PC_NAME_NES)ちゃん。@KEY()↓
;jpn:◆いんせきが@WI(30)↓
;jpn: ごーーーーーーーっと@KEY()↓
;jpn:◆すごいおとをたてて おちてねぇ@WI(15)↓
;jpn: そりゃもう たいへんだった。@KEY()↓
;jpn:◆おれは いつも@KEY()↓
;jpn:◆ニンニクをたべて からだを↓
;jpn: つよくしてるから↓
;jpn: へいきだったけど@KEY()↓
;jpn:◆いっぱんのしみんなら↓
;jpn: きを うしなってたろうね。@KEY()↓
;jpn:◆それにしても けいかんが↓
;jpn: うろちょろしてるうちは@KEY()↓
;jpn:◆おれの じんせいをかけた↓
;jpn: ひみつの たからさがしも‥‥@KEY()↓
;jpn:◆おっと くちが↓
;jpn: すべりそうになっちゃったよ。@KEY()↓
;jpn:◆そんなことより @DSP_STS(STS_PC_NAME_NES)ちゃん@WI(20)↓
;jpn: この すばらしい カンバンは↓
;jpn: チェックしてくれたかい?@KEY()↓
;jpn:◆おれが もじを かいたんだ‥‥@WI(20)↓
;jpn: その しごとが↓
;jpn: ほんしょくだからな。
@KEYNP()
@SETF(FLG_TEMP_9)
』
_INSEKI_MIZUNO_YAZIUMA_TEMP;
◆Sigh.@WI(20)  I wonder when the cops will leave...
;jpn:◆おまわりさんたちは↓
;jpn: いつになったら↓
;jpn: ひきあげるのかね まったく。
@KEYNP()
』

_INSEKI_MIZUNO_LATER;
◆@DSP_STS(STS_PC_NAME_NES), buddy...I have something to tell you,@WI(15) and only you.@KEY()↓
◆Can you come visit me later,@WI(15) alone?
;jpn:◆@DSP_STS(STS_PC_NAME_NES)ちゃん‥‥あんただけに↓
;jpn: ちょいと はなしがあるんだけど@KEY()↓
;jpn:◆あとで ひとりで‥‥↓
;jpn: おれんとこに きてくれ。
@SE(SE_se72);あやしいヒント
@KEYNP()
』


;@Habitat:オネット／フィールド／GiantStep入り口
;@Person:GiantStep見張り警官
;@Figure:警官
;@AppearanceKey:FLG_ONET_KANBANCOP_APPEAR/on
;@ActionScript:＊ネスに近寄って台詞MSG_ONET_POLICE_KANBAN発行
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POLICE_KANBAN
MSG_ONET_POLICE_KANBAN;
@CLRF(FLG_ONET_KANBANCOP_APPEAR)
@SETF(FLG_POLICE_KANBANCOP_APPEAR)
@OPEN(1)
◆Hey you,@WI(15) the board says@WI(15) ”Do No Enter.”@WI(20)  Couldn’t you read it?@KEY()↓
<Yes>
<No>
;jpn:◆ちょっと ちょっと キミ キミ↓@KEY()
;jpn:◆たちいりきんしの カンバンが↓
;jpn: よめなかったのだね?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_POLICE_KANBAN_YES,_ONET_POLICE_KANBAN_NO)

_ONET_POLICE_KANBAN_NO;
◆What a rebellious kid!@WI(15)  Come to the Onett Police Station later!
;jpn:◆はんこうてきな ガキだな!@WI(15)↓
;jpn: あとで オネットけいさつしょに↓
;jpn: しゅっとうしろ!
@KEYNP()
@CLOSEALL()
』

_ONET_POLICE_KANBAN_YES;
◆Hey, you must not be able to read,@WI(10) kid.@KEY()↓
◆Get yer butt to the Onett Police Station later!
;jpn:◆じの よめないしょうねんよ!@WI(15)↓
;jpn: あとで オネットけいさつしょに↓
;jpn: きなさい!
@KEYNP()
@CLOSEALL()
』


;@Habitat:オネット／フィールド／隠れ家
;@Person:見張り役
;@Figure:ボロ
;@AppearanceKey:0
;@ActionScript:＊いったりきたり
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_KAKUREGA_GUARD
MSG_KAKUREGA_GUARD;＆
@CHKFGOTO(FLG_WIN_GIEGU,_KAKUREGA_GUARD_END)
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_KAKUREGA_GUARD_NESS_DEAD)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0),@WI(15) I’m staking out the hideout.@WI(20)  Can you take over?↓
<Yes>
<No>
;jpn:◆@DSP_NAME(0)さん かくれがの↓
;jpn: みはりを こうたいして↓
;jpn: くれるんですか?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_KAKUREGA_GUARD_YES,_KAKUREGA_GUARD_NO)

_KAKUREGA_GUARD_NO;
◆You’re busy.@WI(15)  I understand.
;jpn:◆いそがしそう ですもんね。
@KEYNP()
』

_KAKUREGA_GUARD_YES;
◆Just kidding.@WI(15)  Stake outs are my job.
;jpn:◆あ うそ うそ。@WI(15)↓
;jpn: みはりは ぼくのやくめですから。
@KEYNP()
』

_KAKUREGA_GUARD_NESS_DEAD;
◆Ah!@KEY()↓
◆Did you realize this is the hideout?↓
<Yes>
<No>
;jpn:◆あっ!@KEY()↓
;jpn:◆ここが カクレガって↓
;jpn: わかったんですか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_KAKUREGA_GUARD_DEAD_YES,_KAKUREGA_GUARD_DEAD_NO)
_KAKUREGA_GUARD_DEAD_NO;
◆(Oh!...@WI(20)Hmmm)@KEY()↓
◆This is not a hideout!
;jpn:◆(ドギマギ)@KEY()↓
;jpn:◆こ@WI(15) こ@WI(15) ここ↓
;jpn: カクレガじゃ↓
;jpn: ないですから‥‥!
@KEYNP()
』
_KAKUREGA_GUARD_DEAD_YES;
◆I must totally stand out...
;jpn:◆かえって↓
;jpn: ぼくが めじるしに↓
;jpn: なっちゃったのかなぁ。
@KEYNP()
』
_KAKUREGA_GUARD_END;＆
◆@DSP_STS(STS_PC_NAME_NES), that rocks!@KEY()↓
◆Yesterday,@WI(15) I finally became a hideout member.@WI(20)  Please come back and visit.
;jpn:◆@DSP_STS(STS_PC_NAME_NES)さん↓
;jpn: うれしいニュースです。@KEY()↓
;jpn:◆きのう ぼく↓
;jpn: せいしきにカクレガの↓
;jpn: メンバーに なれたんです。@KEY()↓
;jpn:◆これからも↓
;jpn: よろしくおねがいします。
@KEYNP()
』

;@Habitat:オネット／フィールド／旅芸人の小屋前
;@Person:旅芸人プリッツ
;@Figure:芸人
;@AppearanceKey:FLG_ITEM_PRETZ/off
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_PRETZ
MSG_ONET_PRETZ_2;
@CHKFGOTO(FLG_OPEN_TABIGOYA,_ONET_PRETZ_2_LATER)
◆I heard there’s a big foot print on the hilltop behind this shack.@KEY()↓
◆I haven’t seen it myself...@WI(15)  It’s just a rumor.
;jpn:◆こやの むこうにゃ↓
;jpn: でっけえ あしあとが↓
;jpn: あるらしいんだよ。@KEY()↓
;jpn:◆おれは みてないんだけどね。@KEY()↓
;jpn:◆ウワサでさ‥‥。
@KEYNP()
』
_ONET_PRETZ_2_LATER;
◆Uh, huh.@WI(15)  The big foot print is called Giant Step.@WI(20)  What a way cool name!
;jpn:◆へえー↓
;jpn: でっけえ あしあとは@KEY()↓
;jpn:◆ジャイアントステップって↓
;jpn: いうのかい。@KEY()↓
;jpn:◆イキな なまえだね。
@KEYNP()
』
MSG_ONET_PRETZ_RECEIVE;二人とも。カギを使った時
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_KEY_TABIGOYA)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
@GET_CHAR_DIR(PRSN_ONET_FIELD_E,1,PC_NESS)
@SET_CHAR_DIR(PRSN_ONET_FIELD_E,0)
@GET_CHAR_DIR(PRSN_ONET_FIELD_1N,1,PC_NESS)
@SET_CHAR_DIR(PRSN_ONET_FIELD_1N,0)
◆Yep,@WI(15) that’s the key!@WI(20)  Hurry and open the door.
;jpn:◆おお そのカギだ!@WI(20)↓
;jpn: はやく あけてくれよ。
@KEYNP()
』

MSG_ONET_PRETZ;
@CHKFGOTO(FLG_OPEN_TABIGOYA,_ONET_PRETZ1)
◆This shack was locked by someone from City Hall,@WI(15) so we can’t use it.@KEY()↓
◆The reason it was closed was ’cause a punk named Frank may have trashed the place.@KEY()↓
◆What a drag.@KEY()↓
◆We can’t even change our clothes,@WI(15) and hotels are too expensive...
;jpn:◆むかしからの たびげいにんたちの↓
;jpn: こやに しやくしょが↓
;jpn: カギをかけちまってよ。@KEY()↓
;jpn:◆つかえなくなってよう。@KEY()↓
;jpn:◆フランクとかって↓
;jpn: わるガキが わるさをするんで↓
;jpn: しめちまったらしいんだ。@KEY()↓
;jpn:◆こまったよ。@KEY()↓
;jpn:◆きがえも できやしないし↓
;jpn: ホテルは たかいしさ。
@KEYNP()
』
_ONET_PRETZ1;
@CHKFGOTO(FLG_ITEM_PRETZ,_ONET_PRETZ2)
◆Wow.@WI(15)  You opened the door!@WI(15)  All right!@KEY()↓
◆Here’s a trinket for good luck.@WI(15)  It’s the @DSP_GOODS(GDS_EQUIP_AMULET_TABI)!
;jpn:◆おお カギあけてくれたのかい。↓
;jpn: サンキュー!@WI(15)↓
;jpn: たびのおまもりを やるよ。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_ONET_PRETZ_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_EQUIP_AMULET_TABI)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_ITEM_PRETZ)
@KEYNP()
』

_ONET_PRETZ_ITEMFULL;
←
@SE(SE_se05_undo)
◆I decided that...@KEY()↓
◆you have too many items to carry, and are unable to carry more.@KEY()↓
◆After you’ve organized your items why don’t you come back.
;jpn:◆と おもったけど‥‥@KEY()↓
;jpn:◆にもつが いっぱいで↓
;jpn: これいじょう↓
;jpn: はいりそうにねぇな。@KEY()↓
;jpn:◆にもつを せいりしてから↓
;jpn: また きなよ。
@KEYNP()
』

_ONET_PRETZ2;
◆Do you like traveling too?
;jpn:◆あんたも たびがすきなのかい。
@KEYNP()
』


;@Habitat:オネット／フィールド／図書館近く
;@Person:図書館行った女の子
;@Figure:少女D
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_GIRL
MSG_ONET_GIRL;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_GIRL_END)
@CHKFGOTO(FLG_TEMP_8,_ONET_GIRL_AFTER)
@CHKFGOTO(FLG_ITEM_MAP,_ONET_GIRL_LATER)
_ONET_GIRL_MAIN;
◆A library is a nice place to learn stuff.@KEY()↓
◆I received a lot of info about EarthBound.@KEY()↓
◆You can borrow maps for nothing!
;jpn:◆としょかんに いくと↓
;jpn: べんきょうになるわぁ!@KEY()↓
;jpn:◆「マザー２」のこととかも↓
;jpn: いっろいろ わかっちゃった。@KEY()↓
;jpn:◆いまなら むりょうで↓
;jpn: ちずも かりられるのよ!
@KEYNP()
』
_ONET_GIRL_LATER;
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_ONET_GIRL_MAIN)
◆What a cute, yellow backpack.
;jpn:◆あなたの きいろいリュック↓
;jpn: かわいいわね。
@KEYNP()
@SETF(FLG_TEMP_8);メッセージ切り換え用
』

_ONET_GIRL_AFTER;
◆It’s a good idea to talk to lots of people.
;jpn:◆よく はなしかけてくれるわね。↓
;jpn: そのこころがけは↓
;jpn: いいとおもうわ。
@KEYNP()
』
_ONET_GIRL_END;＆
@CHKFGOTO(FLG_ONET_LUCY_CHU,_ONET_GIRL_END_2)
◆If she’s is a good mood,@WI(15) a lady in the library will kiss you.
;jpn:◆としょかんの おねえさんって↓
;jpn: きげんがいいと↓
;jpn: チューしてくれるのよね。
@KEYNP()
』
_ONET_GIRL_END_2;＃
◆Hey!@WI(15)  You have lipstick on your cheek.
;jpn:◆あ@WI(15) ほっぺに くちべにが↓
;jpn: ついてるわよ。
@KEYNP()
』


;@Habitat:オネット／フィールド／街の至る所
;@Person:モグラのホリー
;@Figure:モグラのホリー
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_MOLEHOLLY
MSG_ONET_MOLEHOLLY;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_MOLEHOLLY_END)
◆(I’m not an enemy.@WI(20)  I’m just a friendly mole.@KEY()↓
◆I’ll tell you how to distinguish between your friends and enemies.@KEY()↓
◆It’s easy to tell an enemy just by looking at them.@KEY()↓
◆Enemies look like humans with weird−colored faces.@WI(15)  Beware of them.@KEY()↓
◆However...you can’t get more powerful if you avoid your enemies.)
;jpn:◆(おれは てきじゃない。@WI(20)↓
;jpn: ただの もぐらさ。@KEY()↓
;jpn:◆てきのみわけかたを↓
;jpn: おしえてあげよう。@KEY()↓
;jpn:◆いかにも てきらしいやつは↓
;jpn: みればわかる。@KEY()↓
;jpn:◆にんげんの すがたのてきは↓
;jpn: えらく かおいろが わるいから↓
;jpn: それを ちゅういすればいい。@KEY()↓
;jpn:◆‥‥でも↓
;jpn: にげてばっかりいたんじゃ↓
;jpn: つよくは なれないよ)
@KEYNP()
』
;＆
_ONET_MOLEHOLLY_END;
◆(You listened to my advise and fought courageously.@WI(15)  You rock!)
;jpn:◆(おれの ちゅうこくをまもって↓
;jpn: ゆうきをもって↓
;jpn: たたかったようだね。@KEY()↓
;jpn:◆いや たいしたもんだ)
@KEYNP()
』

;@Habitat:オネット／フィールド／街の至る所
;@Person:街の人A
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_C
MSG_ONET_C;
@CHKFGOTO(FLG_WIN_FRANK,_ONET_C_LATER)
◆The arcade is full of Sharks.@WI(20)  I can’t play there.
;jpn:◆ゲームセンターに いっても↓
;jpn: シャークだんの やつらが↓
;jpn: せんりょうしてて あそべないや。
@KEYNP()
』

_ONET_C_LATER;
◆Hurray!@WI(15)  The Sharks are gone from the arcade!@WI(15)  Now I can go in...@KEY()↓
◆Even though I don’t have any money to play the games...
;jpn:◆シャークだんが↓
;jpn: おとなしくなっても@KEY()↓
;jpn:◆おかねがないから↓
;jpn: ゲームはできない。@WI(20)↓
;jpn: ‥‥ということが わかりました。
@KEYNP()
』


;@Habitat:オネット／フィールド／街の至る所
;@Person:街の人B
;@Figure:レゲエ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_F
MSG_ONET_F;
@CHKFGOTO(FLG_POLA,_ONET_F_LATER)
@CHKFGOTO(FLG_POLA_GRFD,_ONET_F_LATER)
_ONET_F_MAIN;
◆A girl named @DSP_STS(STS_PC_NAME_PAULA) lives in Twoson.@WI(15)  Her mother runs a pre−school out of their home.@KEY()↓
◆I can’t remember the name of the school,@WI(15) but I heard @DSP_STS(STS_PC_NAME_PAULA)’s really special.@KEY()↓
◆Why is she special?@KEY()↓
◆I forgot to ask.@WI(15)  Oh, well...
;jpn:◆ツーソンの なんとかようちえんに↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)ってむすめがいてね@WI(15)↓
;jpn: これがとにかく すげぇんだって。@KEY()↓
;jpn:◆なにが すげぇって‥‥@KEY()↓
;jpn:◆あ そこいらへんのとこは↓
;jpn: まだ きいてなかったな。@WI(15)↓
;jpn: ま いいや。
@KEYNP()
』
_ONET_F_LATER;
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_ONET_F_MAIN);ポーラ家に帰ってたら‥‥
@CHKFGOTO(FLG_GLOBAL_POLA_KIDNAPPED,_ONET_F_MAIN);誘拐中
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_ONET_F_MAIN)
◆Ah, it’s you...@WI(20)  I’ve seen you in the newspaper.@KEY()↓
◆Aren’t you the extraordinary girl from Twoson?↓
<Yes>
<No>
;jpn:◆あ このおんなのコ‥‥↓
;jpn: しんぶんで↓
;jpn: みたことあるような きがする。@KEY()↓
;jpn:◆たしか ツーソンの↓
;jpn: すげぇ おんなのこだろ?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_F_YES,_ONET_F_NO)
_ONET_F_NO;
◆I see...@WI(20)  Maybe you’re not especially special.
;jpn:◆そうか‥‥@WI(20)↓
;jpn: あんまり すごくないのか。
@KEYNP()
』
_ONET_F_YES;
◆”Can I have your autograph?”@WI(20) is an airheaded question.@WI(15)  I won’t ask you for it.
;jpn:◆サインしてくれ なんて↓
;jpn: ミーハーなことは‥‥@WI(20)↓
;jpn: おれは いわない。
@KEYNP()
@!
