;
; $Id: e01onet0.msg,v 1.18 1995/03/24 13:20:27 masa Exp $
;
;--------------------------------------

MSG_ONET_SHARK_INFO_FRANK;フランクを倒したら消える
◆What?@WI(20)  You want to meet our boss,@WI(10) Frank?@KEY()↓
◆He’s in the backyard of the game arcade,@WI(15) thinking about peace and love.@KEY()↓
◆You might want to visit him.@KEYNP()
』

;
;@Habitat:オネット/ゲームセンター/1階
;@Person:裏口を塞ぐ団A
;@Figure:シャーク団
;@AppearanceKey:FLG_ONET_GUARDSHARK_DISAPPEAR/off
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_D
MSG_ONET_SHARK_D;
@CHKFGOTO(FLG_ONET_GUARDSHARK_DISAPPEAR,MSG_SYS_HANASU_NG)
@CHKFGOTO(FLG_WIN_FRANK,_ONET_SHARK_D2)
◆Hey kid!@WI(20)  Do you wanna become a member?↓
<Yes>
<No>
@DSP_ITEM(2)
@SELGOTO(_ONET_SHARK_D_YES,_ONET_SHARK_D_NO)

_ONET_SHARK_D_NO;
◆Don’t be such a snob!
@KEY()
@GOSUB(MSG_BATTLE_SHARK_D)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_ONET_GAME_1F_A,OBJFX_HIDE_NONE)
@SETF(FLG_ONET_GUARDSHARK_DISAPPEAR)
』

_ONET_SHARK_D_YES;
◆Come back after you finish EarthBound!
@KEYNP()
』

_ONET_SHARK_D2;
◆Hello!@KEYNP()
』


;@Habitat:オネット/ゲームセンター/1階
;@Person:シャーク団A
;@Figure:シャーク団
;@AppearanceKey:0
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_C
MSG_ONET_SHARK_C;ゲーム
@CHKFGOTO(FLG_ONET_SHARK_C_DISAPPEAR,MSG_SYS_HANASU_NG)
@OPEN(1)
@CHKFGOTO(FLG_WIN_FRANK,_ONET_SHARK_C2)
◆It was you!@WI(20)  YOU beat up my buddy,@WI(15) didn’t you?@KEY()↓
◆You’d better just beat it!
@KEY()
@CLOSEALL()
@GOSUB(MSG_BATTLE_SHARK_C)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_ONET_GAME_1F_B,ANIM_BLINK_SUICIDE);シャーク団を消す
@SETF(FLG_ONET_SHARK_C_DISAPPEAR)
』

_ONET_SHARK_C2;
◆Yeah?
@KEYNP()
@CLOSEALL()
@REMOVE_CHAR(PRSN_ONET_GAME_1F_B,ANIM_PEOPLEWALK1)
』


;@Habitat:オネット/ゲームセンター/1階
;@Person:シャーク団B
;@Figure:シャーク団
;@AppearanceKey:0
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_F
MSG_ONET_SHARK_F;
@CHKFGOTO(FLG_WIN_FRANK,_ONET_SHARK_F2)
◆Uh huh...Uh huh...@KEY()↓
◆You sound like a real whiner to me.@KEY()↓
◆Don’t get lippy,@WI(10) or I’ll kick your butt!
@KEYNP()
』

_ONET_SHARK_F2;
◆You sure are strong!@WI(20)  You got me,@WI(15) at least...
@KEYNP()
』


;@Habitat:オネット/ゲームセンター/2階
;@Person:シャーク団C
;@Figure:シャーク団
;@AppearanceKey:0
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_E
MSG_ONET_SHARK_E;
◆Spit spit spit@WI(15)↓
  Saliva spit spit@WI(15)↓
  Do you want some gum?@KEY()↓
◆Get yer own,@WI(15) twit.
@KEYNP()
』


;@Habitat:オネット/ゲームセンター/2階
;@Person:シャーク団D
;@Figure:シャーク団
;@AppearanceKey:0
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_G
MSG_ONET_SHARK_G;シャーク団3
◆To tell you the truth,@KEY()↓
◆I like drinking tea and eating fresh vegetables,@KEY()↓
◆but that doesn’t fit my super cool image.@KEY()↓
◆I guess I just have to accept this about myself.
@KEYNP()
』


;@Habitat:オネット/ゲームセンター/2階
;@Person:シャーク団E
;@Figure:ゴロつき
;@AppearanceKey:0
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_GOROTUKI
MSG_ONET_SHARK_GOROTUKI;ゲームセンター4
@CHKFGOTO(FLG_WIN_FRANK,_ONET_SHARK_GOROTUKI_LATER)
◆Frank has an incredibly powerful weapon.@KEY()↓
◆If you get your hands on it, you can stand against any enemy.
@KEYNP()
』

_ONET_SHARK_GOROTUKI_LATER;
◆So you’re a real Rambo−type guy?@KEY()↓
◆I didn’t think so.
@KEYNP()
』


;----------------------------------------
;@Habitat:オネット/ドラッグストア/ドラッグストア
;@Person:店員A
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_DRUG1
MSG_ONET_DRUG1;@MaltaAppeded
;◆Hey, kid!↓
; What’ll it be?@KEY()
@GOSUB(MSG_SHOP_ONET_DRUG1)
』

;@Habitat:オネット/ドラッグストア/ドラッグストア
;@Person:店員B
;@Figure:サラリーマンD
;@AppearanceKey:0
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_DRUG2
MSG_ONET_DRUG2;@MiuraAppeded
;◆Hi there...
; What can I help you with?@KEY()
@GOSUB(MSG_SHOP_ONET_DRUG2)
』

;@Habitat:オネット/ドラッグストア/ドラッグストア
;@Person:客
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_DRUG_BOY
MSG_ONET_DRUG_BOY;
@GET_ORDER_PLAYER(1)
@EQ(PC_NESS)@FALSE_GOTO(_ONET_DRUG_BOY_DEAD)
◆Hey,@WI(15) I know your hard−earned cash is important to you,@KEY()↓
◆but you should call your mom.@KEY()↓
◆She’s probably got an ulcer from worrying about you.
@KEYNP()
』
_ONET_DRUG_BOY_DEAD;
◆The younger manager of this shop has a strange way talking...@KEY()↓
◆Anyway,@WI(15) be sure to pick up some items that would be helpful in the future,@KEY()↓
◆not just stuff you need right now.
@KEYNP()
』

;◆You should stock up on what@KEY()↓
;◆you need now, and on what you think↓
;  you might need in the future.@KEY()↓
;◆Having supplies is always useful.@KEYNP()
;』
;----------------------------------------
;@Habitat:オネット/ネスの家/1階リビング
;@Person:(階段塞ぐ)母親
;@Figure:ネスママ
;@AppearanceKey:FLG_MYHOME_MAMA_YEAH/off
;@ActionScript:*東向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MYHOME_MAMA_0
MSG_MYHOME_MAMA_0;
@CHKFGOTO(FLG_MYHOME_PHONE,_MYHOME_MAMA_PHONE)
@CHKFGOTO(FLG_MYHOME_MAMA_YEAH,MSG_MYHOME_MAMA1)
@CHKFGOTO(FLG_MYHOME_POKEY,_MYHOME_MAMA)
@CHKFGOTO(FLG_PAPA_MYHOME,_MYHOME_MAMA_POKEY)
@CHKFGOTO(FLG_MYHOME_POKEY_ENTER,_MYHOME_MAMA_POKEY)
◆My land!@WI(20)  Who could be knocking at the door at this time of night?@KEY()↓
◆Would you answer it?
@KEYNP()
』

_MYHOME_MAMA_POKEY;
◆Pokey’s waiting for you.@WI(20)  You should listen to what he has to say.
@KEYNP()
』

_MYHOME_MAMA_PHONE;
◆Could you get that?
@KEYNP()
』

_MYHOME_MAMA;
@OPEN(1)
◆I know that the dog is unreliable,@WI(15) but you should take @DSP_STS(STS_PARTY_DOG_NAME) along.@KEY()↓
◆The Cracked Bat in Tracy’s room could help out at a time like this...@KEY()↓
◆No matter what anyone says,@WI(15) you’re a courageous,@WI(15) strong boy.@KEY()↓
◆You’re my very own natural born fighter...You’ll go far...@KEY()↓
◆Remember to@WI(15) ”Go for it!”
@SETF(FLG_MYHOME_MAMA_YEAH)
@CHKFGOTO(FLG_MYHOME_NES_CHANGE,_MYHOME_MAMA_YEAH_BUT)
@KEYNP()
@CLOSEALL()
@WI(1)
』
_MYHOME_MAMA_YEAH_BUT;ネス着替えてない
@KEY()↓
◆But,@WI(15) I think you should change out of your jammies before you leave.
@KEYNP()
@CLOSEALL()
@WI(1)
@CLRF(FLG_MYHOME_NES_CHANGE)
@WARP(WARP_MYHOME_2ND);着替えてベッドから
』

;@Habitat:オネット/ネスの家/1階リビング
;@Person:(うろつく)母親
;@Figure:ネスママ
;@AppearanceKey:FLG_MYHOME_MAMA_YEAH/on
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MYHOME_MAMA1
MSG_MYHOME_MAMA1;
@CHKFGOTO(FLG_WIN_GIEGU,_MYHOME_MAMA_END)
@CHKFGOTO(FLG_ONET_DOOR_CLOSE,_MYHOME_MAMA_XYZ)
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_MYHOME_MAMA2)		;ネス死んでたら泊めてくれない
@CHKFGOTO(FLG_TLPT_ONET,_MYHOME_MAMA2)
◆Yeah,@WI(15) sure,@WI(15) you’re cool!@WI(20)  Whatever...
@KEYNP()
』

_MYHOME_MAMA2;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
@EQ(1)
@TRUE_GOTO(_MYHOME_MAMA_GOODNIGHT)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Any friend of @DSP_NAME(PC_NESS) is welcome in our home...@KEY()↓
◆I think it’s great the way you kids have been working together.
@KEYNP()
』

_MYHOME_MAMA_GOODNIGHT;
@CHKFGOTO(FLG_MYHOME_SLEEP,_MYHOME_MAMA_TMP)
@CHKF(FLG_ONET_AMBRAMI)@FALSE_GOTO(_MYHOME_MAMA_GOODNIGHT_TMP)
◆You’re back!@WI(20)  Don’t bother yourself with talking now,@WI(15) you look too tired.@KEY()↓
◆Mothers understand these things.@WI(20)  Eat some @DSP_STS(STS_PARTY_FAVORITE_FOODS) and scoot up to bed.
@KEY()
@CLOSEALL()
;-----
@GOSUB(MSG_GLOBAL_CHECK_HOMESICK);ホームシック検査
;-----
;体力回復(暗転ワープあり、BGM使用、夜鍋あり、セリフ替えあり)
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_MYHOME_2ND)
@SETF(FLG_MYHOME_SLEEP)
』
_MYHOME_MAMA_GOODNIGHT_TMP;ポーキーを連れている場合
◆You’re hungry already?@KEY()↓
◆Why don’t you have some↓
  @DSP_STS(STS_PARTY_FAVORITE_FOODS)?@KEY()↓
◆Pokey,@WI(15) you don’t like↓
  @DSP_STS(STS_PARTY_FAVORITE_FOODS),@WI(10) do you?@KEY()↓
@MESSAGE_SOUND(3)
◆
@MESSAGE_SOUND(1)
T
@MESSAGE_SOUND(3)
・@WI(15)
@MESSAGE_SOUND(1)
O
@MESSAGE_SOUND(3)
・@WI(15)
@MESSAGE_SOUND(1)
O
@MESSAGE_SOUND(3)
・@WI(15)
@MESSAGE_SOUND(1)
BAD!@KEYNP()
;体力回復(暗転ワープなし、BGM使用、夜鍋なし、セリフ替えなし)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
』

_MYHOME_MAMA_TMP;
@Q_MEMBER(2)
@FALSE_GOTO(_MYHOME_MAMA_TMP_PARTY)
@CHKFGOTO(FLG_TEMP_1,_MYHOME_MAMA_TMP_TMP)
◆Good morning,@WI(15) sleepy bones!@WI(20)  Are you ready to start your adventure?@KEY()↓
_MYHOME_MAMA_TMP_TMP;
◆I’m so proud of you!@WI(20)  My little man is growing up too fast...
@KEYNP()
@SETF(FLG_TEMP_1)
』
_MYHOME_MAMA_TMP_PARTY;
@CHKFGOTO(FLG_TEMP_1,_MYHOME_MAMA_TMP_PARTY_TMP)
◆Good morning everyone!@WI(20)  Are you ready for your adventure?@KEY()↓
◆I think all of you are the bee’s knees.@WI(20)  Yes,@WI(10) I do!@KEY()↓
_MYHOME_MAMA_TMP_PARTY_TMP;※メッセージなし
◆You are all so... cool!@WI(20)  Yes,@WI(10) you’re hip!@KEYNP()
』

_MYHOME_MAMA_XYZ;マジカント後:マイホーム夜(室内も暗くする)※()何?
@CHKFGOTO(FLG_TEMP_9,_MYHOME_MAMA_XYZ_TMP)
◆Oh,@WI(10) @DSP_NAME(PC_NESS)!@WI(20)  You finally showed up...@KEY()↓
◆There are plenty of creepy monsters running around Onett now.@KEY()↓
◆The townspeople are barricaded into their homes,@WI(15) afraid to go out.@KEY()↓
◆I’m fine...@WI(20)  But I am a bit scared.@KEY()↓
◆Everything will be okay if we just sit here quietly in the dark.@KEY()↓
◆Are you hungry?@KEY()↓
◆Do you want to eat some @DSP_STS(STS_PARTY_FAVORITE_FOODS)?↓
<Yes>
<No>
;jpn:◆まぁ まぁ‥‥↓
;jpn: よくここまで たどりついたわね。@KEY()↓
;jpn:◆いま オネットは↓
;jpn: とんでもない バケモノが↓
;jpn: うようよ してて@KEY()↓
;jpn:◆まちのひとは みんな↓
;jpn: ガタガタふるえて@KEY()↓
;jpn:◆うちのなかに↓
;jpn: とじこもっているのよ。@KEY()↓
;jpn:◆ママは へいきなの。@WI(20)↓
;jpn: ‥‥でも ちょっとコワイから↓
;jpn: しずかにしてるのよ。@KEY()↓
;jpn:◆おなか すいてるでしょ?↓
;jpn: @DSP_STS(STS_PARTY_FAVORITE_FOODS)たべる?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_MAMA_XYZ_YES,_MYHOME_MAMA_XYZ_NO)
_MYHOME_MAMA_XYZ_NO;
◆It’s not good for you to eat too much...
;jpn:◆たべすぎは カラダに↓
;jpn: わるいものね。
@KEYNP()
@SETF(FLG_TEMP_9)
』
_MYHOME_MAMA_XYZ_YES;回復
@CLOSEALL()
;体力回復(暗転ワープなし、BGMあり、夜鍋あり、セリフ替えなし)
;@MOVE_GOM_CHAR( GOM_HIT_CHR,ANIM_INTO_NIGHT,OBJFX_SHOW_NONE )	;フェードアウト
;@WAITSYS()
@BGMSTOP(0)
@GOSUB(MSG_JEFF_YONABE)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@OPEN(1)
◆Are you more relaxed?@KEY()↓
;jpn:◆すこしは おちついた?
_MYHOME_MAMA_XYZ_TMP;繰りかえし点
◆Okay...
;jpn:◆‥‥じゃ@KEY()↓
;jpn:◆‥‥‥。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_GLOBAL_CHECK_HOMESICK);ホームシック検査
』

_MYHOME_MAMA_END;&最終戦闘後のママのセリフ
@CHKFGOTO(FLG_MYHOME_PHONE_RING,_MYHOME_MAMA_END_RING);電話が鳴ってたら
@CHKFGOTO(FLG_ONET_MYHOME_END_MAMA,_MYHOME_MAMA_END_LATER)
◆Wow,@WI(10) you’ve become such a strong,@WI(10) young man.@KEY()↓
◆I’d like to hear all of your stories,@KEY()↓
◆but I don’t want to annoy you as soon as you walk through the door.@KEY()↓
;jpn:◆まあ @DSP_STS(STS_PC_NAME_NES)↓
;jpn: すっかり たくましくなって。@KEY()↓
;jpn:◆いろいろ ききたいことも↓
;jpn: いっぱいあるけど@KEY()↓
;jpn:◆かえってきたそうそう↓
;jpn: しつもんぜめじゃ↓
;jpn: うるさがられちゃうわね。
@KEY()↓
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_MYHOME_MAMA_END_JUMP)

◆I want to have a chance to get to know your little girlfriend.@KEY()↓
◆It’s good to meet you,@WI(15) @DSP_NAME(PC_PAULA).@KEY()↓
◆When your adventure is
;jpn:◆‥‥ママ↓
;jpn: あなたの ガールフレンドに↓
;jpn: きらわれたくないもん。@KEY()↓
;jpn:◆よく いらっしゃったわね↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)ちゃん。@KEY()↓
;jpn:◆もし じぶんたちのようじが↓
@GOTO(_MYHOME_MAMA_END_MAIN)

_MYHOME_MAMA_END_JUMP;
◆When your adventure is
;jpn:◆もし じぶんのようじが↓

_MYHOME_MAMA_END_MAIN;
 finally over,@WI(15) please come back here.@KEY()↓
◆The photo−man brought an album by.@KEY()↓
◆I’d like to look at it with you...
;jpn: ぜーーーんぶ かたづいたら@KEY()↓
;jpn:◆もういっかい こえをかけて↓
;jpn: ちょうだい。@KEY()↓
;jpn:◆さっき しゃしんやさんが↓
;jpn: アルバムを とどけてくれたのよ。@KEY()↓
;jpn:◆いっしょに みたいから。
@KEYNP()
@CLOSEALL()
@SETF(FLG_ONET_MYHOME_END_MAMA)
@CHKF(FLG_MAKYO_TRADER_DEBT)@FALSE_GOTO(MSG_END)
@WI(60)						;借金してたら
@REMOVE_CHAR(PRSN_ONET_NES_1F_3A,ANIM_TEL_RING)	;電話鳴る
@SETF(FLG_MYHOME_PHONE_RING)			;電話鳴りつづける
』

_MYHOME_MAMA_END_RING;電話が鳴ってたら
◆@DSP_NAME(PC_NESS),@WI(15) could you get the phone?
;jpn:◆@DSP_STS(STS_PC_NAME_NES)!@WI(20) でてちょうだい!
@KEYNP()
』

_MYHOME_MAMA_END_LATER;次にはなすと
◆Did you do finish doing everything that you wanted to?@KEY()↓
<Yes> <No>
;jpn:◆すっかり じぶんのようじは↓
;jpn: すんだのね?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_MAMA_END_YES,_MYHOME_MAMA_END_NO)
_MYHOME_MAMA_END_NO;
◆You’d better do everything,@WI(15) because once you start looking at the album,@KEY()↓ 
◆you can’t stop!
;jpn:◆じゃ やりのこしたことは↓
;jpn: ぜんぶ やっといたほうが↓
;jpn: いいわよ。@KEY()↓
;jpn:◆アルバムを みはじめたら↓
;jpn: きりがないんだから。
@KEYNP()
』
_MYHOME_MAMA_END_YES;はい
◆Okay!@WI(20)  Now you can finally share your incredible experiences with me...@KEY()↓
◆You did so well!
;jpn:◆じゃあ ゆっくり↓
;jpn: あなたの おもいでを↓
;jpn: わけてもらうことにするわ。@KEY()↓
;jpn:◆よくやったわね @DSP_STS(STS_PC_NAME_NES)。
@KEY()
@CLOSEALL()
;-----
@GOSUB(MSG_GLOBAL_DELIVERY_RESET)	;場面転換時に配達を中止
;-----
@GOSUB(MSG_SUB_BGM_FADEOUT_2SECOND)
;エンディングへ
;@GOTO(_MSG_DEBUG_PHOTO)
@BGMSTART(0,BGM_end1)
@SET_PARTY_DIR(DIR_M_DOWN)
;ネスと(もし居たら)ポーラを南向きの足踏みに
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_TO_BE_POLA_INAI)
@HIDE_PLAYER(PC_PAULA,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_POLA,ANIM_SEAL_PC_PAULA_DIRDOWN,OBJFX_SHOW_NONE)
@WI( 1 )
@REMOVE_GOM_CHAR( GOM_POLA, ANIM_PEOPLEWALK0 )
_TO_BE_POLA_INAI;
@HIDE_PLAYER(PC_NESS,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR( GOM_NES, ANIM_SEAL_PC_ALL_DIRDOWN, OBJFX_SHOW_NONE)
@WI( 1 )
@REMOVE_GOM_CHAR( GOM_NES, ANIM_PEOPLEWALK0 )
;ママ南向く
@SET_CHAR_DIR(PRSN_ONET_NES_1F_A,DIR_M_DOWN)
@REMOVE_CHAR(PRSN_ONET_NES_1F_A,ANIM_PEOPLEWALK0)
;犬南向く
@SET_CHAR_DIR(PRSN_ONET_NES_1F_E,DIR_M_DOWN)
@REMOVE_CHAR(PRSN_ONET_NES_1F_E,ANIM_PEOPLEWALK0)
@WI(120)
@WI(120)
@WI(120)
@WI(120)
@WI(120)
;トレーシーが来る
;@SE(SE_se61_escape)	;階段の音
@WI(60)
@MOVE_GOM_CHAR(GOM_TRACY,ANIM_TRACY_APPEAR,OBJFX_SHOW_NONE)
;
@WI(60)
@WI(100)
@MOVE_GOM_CHAR( GOM_HIT_CHR,ANIM_BLACKOUT,OBJFX_SHOW_NONE )	;フェードアウト
@WAITSYS()
@FUNC(11)
@GOSUB(MSG_SUB_BGM_FADEOUT_2SECOND)
;
_MSG_DEBUG_PHOTO;
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
;写真屋が降りて来る
@WARP(WARP_EVT_ENDING_PHOTO)
@BGMSTART(0,BGM_end2)
@MOVE_GOM_CHAR(GOM_PHOTO,ANIM_END_PHOTOMAN,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_SHADOW_FALL,ANIM_END_SHADOW,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_CAMERA,ANIM_END_CAMERA,OBJFX_SHOW_NONE)
@WAITSYS()
;
@FUNC(12)
@WI(60)
;@WI(180)
;@WI(180)
;@WI(180)
;@WI(180)
;@WI(180)
@GOSUB(MSG_EVT_TO_BE_CONTINUED);S_EVENT2へ
;@DISKEY()
』


;@Habitat:オネット/ネスの家/1階リビング
;@Person:スヌーピー
;@Figure:ネスの犬
;@AppearanceKey:FLG_DOG/off
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MYHOME_DOG
MSG_MYHOME_DOG;
@CHKFGOTO(FLG_WIN_GIEGU,_MYHOME_DOG_END)
@CHKFGOTO(FLG_WIN_OSCAR,_MYHOME_DOG_LATER)
@CHKF(FLG_YAZIUMA_DISAPPEAR)@FALSE_GOTO(_MYHOME_DOG_YAZIUMA)
@CHKFGOTO(FLG_INSEKI,_MYHOME_DOG_SORRY)
@CHKFGOTO(FLG_MYHOME_MAMA_YEAH,_MYHOME_DOG_1)
◆(I’ve got fleas sucking me dry,@WI(15) so I’m just going to lie still for now.)
;jpn:◆(からだについたノミに↓
;jpn: ちを すわせてるんでね@WI(15)↓
;jpn: じっとしてるんだ。@WI(15)いまは ね)
@KEYNP()
』
_MYHOME_DOG_YAZIUMA;
◆(Besides humans,@WI(15) dogs also sleep at night.@WI(20)  Why aren’t you asleep?)
;jpn:◆(イヌも ひとも↓
;jpn: よるは ねるもんだぜ@KEY()↓
;jpn:◆ねろよ!)
@KEYNP()
』
_MYHOME_DOG_1;
◆(Do you want me to go with you?)↓
  <Yes>  <No> 
;jpn:◆(ぼくに ついてきて ほしい?)↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_DOG_YES,_MYHOME_DOG_NO)
_MYHOME_DOG_NO;
◆(Oh,@WI(10) I get it.@WI(20)  You just wanted to talk to me because I’m so lovable.)
;jpn:◆(なんだ。@WI(15)ぼくが かわいいから↓
;jpn: はなしかけた だけなんだな)
@KEYNP()
;
;階段をふさがなくなったので以下コメントアウト
;起き上がって階段を塞ぐ位置を離れて移動後のイヌに替わる。
;@CHKFGOTO(FLG_DOG_LATER_APPEAR,MSG_END)
;@GOSUB(MSG_EVT_5_MYDOG)
;@SETF(FLG_DOG_LATER_APPEAR)
;@SETF(FLG_DOG);はじめに出現していた犬を消す為(臨時に設定)
』
_MYHOME_DOG_YES;
◆(I guess I have no choice.@WI(20)  Let’s go.)
;jpn:◆(しょうがない。@WI(15) いこうかな)
@KEY()
@SE(SE_se10_present_open)
@GOSUB(MSG_ADD_DOG)
@CLRF(FLG_DOG_LATER_APPEAR)
@SETF(FLG_MYHOME_DOG_MOVED)
』
_MYHOME_DOG_SORRY;
@CHKF(FLG_MYHOME_DOG_MOVED)@FALSE_GOTO(_MYHOME_DOG_MED)
◆(I don’t wanna go out anymore.@KEY()↓
◆I don’t care if everyone thinks I’m a stubborn mutt.)
;jpn:◆(もう ぼくは どこへも↓
;jpn: いきたくない。@WI(20)↓
;jpn: わがままな イヌと‥‥@KEY()↓
;jpn:◆よばれても いい)
@KEYNP()
』
_MYHOME_DOG_LATER;
◆(At this point,@WI(15) you guys just might be the strongest force in the world,@KEY()↓
◆don’t you think?)
;jpn:◆(きみたち もしかしたら↓
;jpn: いま せかいじゅうで↓
;jpn: いちばんつよいんじゃない?)
@KEYNP()
』
_MYHOME_DOG_END;&
◆(Other dogs haven’t figured it out yet,@KEY()↓
◆but I know that you guys saved the world!)
;jpn:◆(せかいじゅうの ほかのいぬは↓
;jpn: きがついてないかもしれないけど↓
;jpn: ぼくは しってるよ。@KEY()↓
;jpn:◆きみたちの おかげで↓
;jpn: せかいは すくわれたんだね)
@KEYNP()
』
_MYHOME_DOG_MED;連れてかなかった場合
◆(I like being at home,@WI(10) relaxing quietly...@KEY()↓
◆Can’t ya see−−@WI(15)I don’t wanna go outside!)
;jpn:◆(ぼくは うちのなかで↓
;jpn: めいそうしているのが↓
;jpn: すきなんだ。@KEY()↓
;jpn:◆どこにも いきたくないよ)
@KEYNP()
』

;@Habitat:オネット/ネスの家/1階リビング
;@Person:電話
;@Figure:電話
;@AppearanceKey:0
;@ActionScript:*正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TELE_PAPA_MYHOME
MSG_TELE_PAPA_MYHOME;
@CHKFGOTO(FLG_WIN_GIEGU,_TELE_PAPA_MYHOME_END);ギーグ倒してたら
_TELE_PAPA_MYHOME_MAIN;
@CLRF(FLG_SYS_PHONE_MYHOME)
@CLRF(FLG_SYS_PHONE_MYHOME2)
@CHKFGOTO(FLG_PAPA_MYHOME,MSG_GLOBAL_TELEPHONE)
@CHKFGOTO(FLG_MYHOME_PHONE,_TELE_PAPA_MYHOME_1)
@SE(SE_se0b_tel_put)@WI(20)
MSG_GLOBAL_PHONE_NG;ビーーーかな(三浦)汎用電話無言
◆Beeeep...
;jpn:◆ツーツーツー@WI(15)↓
;jpn: ツーツーツー
@KEYNP()
@SE(SE_se0b_tel_put)
』

_TELE_PAPA_MYHOME_1;
◆@DSP_STS(STS_PC_NAME_NES) answered the phone.@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)は じゅわきをとった。@KEY()↓
@SE(SE_se0b_tel_put)@WI(20)
@GOSUB(MSG_EVT_6_RING)
◆”Hello,@WI(10) it’s your dad.@KEY()↓
◆”Work to exhaustion when you’re young...”@KEY()↓
◆Have you ever heard of a weird saying like this?@KEY()↓
◆Just remember,@WI(15) I’m always behind you 100%.  Don’t be afraid.@KEY()↓
◆I know that you’re brave.@WI(20)  You can do it!@KEY()↓
◆Don’t forget to call me periodically during your adventure.@KEY()↓
◆I can make a record of your progress when you call me.@KEY()↓
◆Oh yeah,@WI(15) I deposited $30 into your bank account.@KEY()↓
◆Do you have your ATM card?@KEY()↓
◆Withdraw your money from any cash machine and buy whatever you need.@KEY()↓
◆Good Luck,@WI(15) m’boy!@WI(20)  I feel like such a hero!@KEY()↓
◆What?@WI(10)  Well,@WI(10) the father of a hero,@WI(10) at least.  Wa ha ha!@KEY()↓
◆Slam!@WI(20)  Beeeeeeeep!
;jpn:◆もしもし パパだ。@KEY()↓
;jpn:◆わかいときの くろうは↓
;jpn: かってでも しろ!@KEY()↓
;jpn:◆というコトバも あるじゃないか。@KEY()↓
;jpn:◆パパは いつでも↓
;jpn: おまえの みかただ。@KEY()↓
;jpn:◆おそれずに ゆうきをもって↓
;jpn: やってみなさい。@KEY()↓
;jpn:◆ぼうけんの ふしめふしめには↓
;jpn: かならずパパのところに↓
;jpn: でんわしなさい。@KEY()↓
;jpn:◆ぼうけんのきろく を↓
;jpn: つけてあげるからね。@KEY()↓
;jpn:◆おまえの ぎんこうこうざに↓
;jpn: 30ドル↓
;jpn: ふりこんでおいたよ。@KEY()↓
;jpn:◆キャッシュカードを↓
;jpn: もっているだろう?@KEY()↓
;jpn:◆キャッシュディスペンサーから↓
;jpn: ひきだして↓
;jpn: じゆうに つかいなさい。@KEY()↓
;jpn:◆けんとうを いのる。@KEY()↓
;jpn:◆パパだって↓
;jpn: ヒーロー!@KEY()↓
;jpn:◆‥‥の ちちおやに↓
;jpn: なれるなら↓
;jpn: わるいきはしないぞ。@KEY()↓
;jpn:◆ワハハハハ!@KEY()↓
;jpn:◆ガチャン@WI(15) ツーツーツー
@KEYNP()
@SE(SE_se0b_tel_put)
@SETF(FLG_PAPA_MYHOME)
@CLRF(FLG_MYHOME_PHONE)
@CLRF(FLG_MYHOME_PHONE_RING);アニメーション検査用。電話鳴らない
@CLRF(FLG_MYHOME_DOOR_CLOSE)
@SETF(FLG_SYS_PHONE_PAPA)
@DEPOSIT_MONEY_BANK(30)
@SAVE_GAME();オープング終了につきセーブ
@SET_COMEBACK_POS(TLPT_ONETT)
』
_TELE_PAPA_MYHOME_END;ギーグ倒してたら
@CHKF(FLG_MYHOME_PHONE_RING)@FALSE_GOTO(_TELE_PAPA_MYHOME_MAIN);鳴ってない
@CHKF(FLG_MAKYO_TRADER_DEBT)@FALSE_GOTO(_TELE_PAPA_MYHOME_MAIN);借金してない
@SE(SE_se0b_tel_put)@WI(20)
@GOSUB(MSG_EVT_6_RING)
@OPEN(1)
◆Hello?@WI(20)  Is this @DSP_NAME(PC_NESS)’s residence?@WI(20)  Is @DSP_NAME(PC_NESS) around?@KEY()↓
◆Ah!@WI(20)  You’re @DSP_NAME(PC_NESS),@WI(15) right?@KEY()↓
◆It’s me,@WI(15) the tough business man!@KEY()↓
◆You remember−−@WI(15)from the Deep Darkness.@KEY()↓
◆I never got the money back that you borrowed,@KEY()↓
◆but,@WI(15) lucky you,@WI(15) I bumped into your dad and he paid the debt for you.@KEY()↓
◆I just wanted to let you know.@KEY()↓
◆Gotta go now−−@WI(15)busy,@WI(10) busy,@WI(10) busy!@KEY()↓
◆Slam.@WI(20)  Beeeeep!
;jpn:◆もしもし↓
;jpn: @DSP_STS(STS_PC_NAME_NES)さんの おたくですね?@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)さんは おいでですか?@KEY()↓
;jpn:◆あ あなた‥‥でしたね。@WI(20)↓
;jpn: まきょうで あった↓
;jpn: ガッツある しょうしゃまん!@KEY()↓
;jpn:◆‥‥それは わたしです。@KEY()↓
;jpn:◆あなたのために↓
;jpn: たてかえた おかねを↓
;jpn: かえしてもらってませんでした。@KEY()↓
;jpn:◆‥‥しかし なんたるぐうぜん!@WI(20)↓
;jpn: あなたの おとうさまに↓
;jpn: おあいして@KEY()↓
;jpn:◆かわりに↓
;jpn: かえしていただいたんです。@KEY()↓
;jpn:◆そのことを↓
;jpn: おつたえしておこうと↓
;jpn: おもいまして‥‥。@KEY()↓
;jpn:◆じゃ わたしは いそがしいので。@WI(30)↓
;jpn: ガチャン ツーツーツー
@KEYNP()
@SE(SE_se0b_tel_put)
@CLOSEALL()
@CLRF(FLG_MAKYO_TRADER_DEBT)
@CLRF(FLG_MYHOME_PHONE_RING)
』


;@Habitat:オネット/ネスの家/1階リビング
;@Person:ドア塞ぐポーキー
;@Figure:ポーキー
;@AppearanceKey:FLG_MYHOME_POKEY_DISAPPEAR/off
;@ActionScript:*演出コンテ#1.1
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MYHOME_POKEY
MSG_MYHOME_POKEY;
@CHKFGOTO(FLG_MYHOME_POKEY,_MYHOME_POKEYYES_1)
;@CHKFGOTO(FLG_PAPA_MYHOME,_MYHOME_POKEY_CONTINUE)
@CLOSEALL()
@WI(30)
@BGMSTART(0,177);poky0
@WI(120)@WI(120)
@MUSISTART()
@OPEN(1)
◆Hey!@WI(15)  L−@WI(15)L−@WI(15)Listen to what I’ve got to say!@KEY()↓
◆When I took Picky to the place where the meteorite landed...
;jpn:◆た@WI(15) た@WI(15) たた@KEY()↓
;jpn:◆たいへんなんだよ!@KEY()↓
;jpn:◆なにがって なにがじゃないよ。@WI(15)↓
;jpn: あのいんせきの おちたところに↓
;jpn: ピッキーを つれてったらさ
@KEY()↓
@GET_CHAR_DIR(PRSN_ONET_NES_1F_D,2,PRSN_ONET_NES_1F_A);ママの方を向く
@SET_CHAR_DIR(PRSN_ONET_NES_1F_D,0)
◆Oh!@WI(20)  Good evening ma’am.@WI(20)  You’re looking lovely as usual.  *snicker*
;jpn:◆あ@WI(15) おばさん こんばんは。@WI(20)↓
;jpn: いつも きれいですね へへへ。
@KEY()↓
@GET_CHAR_DIR(PRSN_ONET_NES_1F_D,1,PC_NESS);ネスの方を向く
@SET_CHAR_DIR(PRSN_ONET_NES_1F_D,0)
◆Anyway,@WI(15) as I was saying,@KEY()↓
◆the police that were guarding the meteorite landing left suddenly@KEY()↓
◆to deal with the Sharks.@WI(15)  You know the Sharks,@WI(10) they’re the local ruffians,@KEY()↓
◆and they were really going wild.@WI(20)  Suddenly,@WI(20) I noticed that Picky was gone.@KEY()↓
◆I blame the cops...it certainly wasn’t my fault at all.@KEY()↓
◆When my dad gets back,@WI(15) I know I’m gonna get it...@KEY()↓
◆You’re my bestest friend.@WI(20)  Won’t YOU help me find Picky?@KEY()↓
<Yes> <No>
;jpn:◆えーと つまり ピッキーを↓
;jpn: つれてったらさ@KEY()↓
;jpn:◆けいさつは シャークだんが↓
;jpn: あばれてるからって↓
;jpn: そっちへ いっちゃってて‥‥@KEY()↓
;jpn:◆だから ピッキーが↓
;jpn: いなくなっちまったんだよ。↓
;jpn: けいさつが わるいんだよ。@KEY()↓
;jpn:◆ぼくは わるくなくってさ。@KEY()↓
;jpn:◆でも とーちゃんが↓
;jpn: かえってきたら↓
;jpn: おれが おこられるだろ。@KEY()↓
;jpn:◆けつたたき 100かいだ。@KEY()↓
;jpn:◆いっしょに ピッキーを さがしに↓
;jpn: いってくれるだろ?@KEY()↓
;jpn:◆しんゆうだって ことでさぁ。↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_POKEYYES,_MYHOME_POKEY1)

_MYHOME_POKEY1;
◆If you refuse me,@WI(15) I’ll say something that’ll cut you like a knife.@KEY()↓
◆Will you come with me?↓
<Yes> <No>
;jpn:◆そんな つめたいこと いうと↓
;jpn: こころが はりさけそうなことを↓
;jpn: いうぞ!@WI(15) いってくれるだろ?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_POKEYYES,_MYHOME_POKEY2)

_MYHOME_POKEY2;
◆Okay, okay...I won’t say anything to hurt you.@KEY()↓
◆Will you please come with me?↓
<Yes> <No>
;jpn:◆こころが はりさけそうなことを↓
;jpn: いわないから↓
;jpn: いっしょに いってくれ。@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_POKEYYES,_MYHOME_POKEY1)
@GOTO(_MYHOME_POKEY1)

_MYHOME_POKEYYES;
@SETF(FLG_MYHOME_POKEY)
◆Ok,@WI(15) good buddy!@WI(20)  Let’s blow this popsicle stand...@KEY()↓
◆Before we go,@WI(15) why don’t you say ”goodbye” to your mom.

;jpn:◆そうか ともよ!@WI(15)↓
;jpn: レッツで ゴーだぜ!@KEY()↓
;jpn:◆ちゃんと ママに あいさつを↓
;jpn: してから いけよォ。
@WI(15)↓
@GET_CHAR_DIR(PRSN_ONET_NES_1F_D,2,PRSN_ONET_NES_1F_A);ママの方を向く
@SET_CHAR_DIR(PRSN_ONET_NES_1F_D,0)
  Don’t you agree,@WI(15) ma’am?
;jpn: ねぇ@WI(10) おばさん。
@KEY()
@CLOSEALL()
@WI(1)
@REMOVE_CHAR( PRSN_ONET_NES_1F_A, ANIM_PEOPLEWALK1_LIVE )
』

_MYHOME_POKEYYES_1;
@CHKFGOTO(FLG_MYHOME_MAMA_YEAH,_MYHOME_POKEY_BAT)
◆Before we go,@WI(15) why don’t you say ”goodbye” to your mom.
;jpn:◆ちゃんと ママに あいさつを↓
;jpn: してから いけよォ。
@KEYNP()
@CLOSEALL()
@WI(1)
@REMOVE_CHAR( PRSN_ONET_NES_1F_F, ANIM_PEOPLEWALK1_LIVE )
』

_MYHOME_POKEY_BAT;
@Q_EQUIP(PC_NESS,GDS_EQUIP_BAT_BORO)@TRUE_GOTO(_MYHOME_POKEY_LETSGO)
@CHKFGOTO(FLG_BOX_ONET_NES_NES_BAT,_MYHOME_POKEY_EQUIP)
◆You’re not taking anything on our big adventure?@KEY()↓
◆Why don’t you look around for your @DSP_GOODS(GDS_EQUIP_BAT_BORO) or something?
;jpn:◆こんな だいぼうけんのたびだちに↓
;jpn: てぶらは ないだろ。@KEY()↓
;jpn:◆ボロのバットかなんか↓
;jpn: さがしてこいよ。
@KEYNP()
』

_MYHOME_POKEY_EQUIP;
◆Sorry about giving you this game−type advice,@WI(15)
;jpn:◆ゲームくさいことを いって↓
;jpn: わるいけど
;@WI(15)↓
@GET_PLAYER_DIR(PC_NESS,3,GOM_POKEY);ネスからポーキーの方向を調べる
@SET_PLAYER_DIR(PC_NESS,0)
 but you should equip your weapon!@KEY()↓
◆Do you know what ”equip” means?↓
<Yes> <No>
;jpn: ぶきは ちゃんと そうびしろよ。@KEY()↓
;jpn:◆「そうび」って わかるか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_POKEY_EQUIP_YES,_MYHOME_POKEY_EQUIP_NO)

_MYHOME_POKEY_EQUIP_NO;
◆It means ”use” or ”wear.”@KEY()↓
◆You must equip items in order to use or wear them.@KEY()↓
◆”Equip” is used a lot in games like this,@KEY()↓
◆but you already knew that...
;jpn:◆「みに つける」っていみだよ!@WI(15)↓
;jpn: ロールプレイングゲームなんかじゃ↓
;jpn: じょうしきだぜ。
@KEY()
@GOTO(_MYHOME_POKEY_LETSGO)

_MYHOME_POKEY_EQUIP_YES;
◆Okay,@WI(15) that’s good.@WI(20)  Be sure to pay attention to details like that.
;jpn:◆そんなら いいんだ。@WI(15)↓
;jpn: こういう こまかいことに↓
;jpn: ちゃんと きをつけようぜ。
@KEY()↓
@GOTO(_MYHOME_POKEY_LETSGO)

_MYHOME_POKEY_LETSGO;
←
◆All right!@WI(20)  You go out in front,@WI(15) and I’ll follow at a safe distance.@KEY()↓
◆Let’s get going!
;jpn:◆よーし!@WI(15)↓
;jpn: おまえが せんとうにたつんだ!@WI(15)↓
;jpn: いこうぜ!
@KEY()
@CLOSEALL()
@SETF(FLG_MYHOME_POKEY_DISAPPEAR)
@SETF(FLG_POKEY)
@SETF(FLG_INSEKI_PICKEY_APPEAR)
@GOSUB(MSG_ADD_POKEY)
@CLRF(FLG_MYHOME_POKEY2_APPEAR)
@CLRF(FLG_MYHOME_POKEY_APPEAR)
@CLRF(FLG_MYHOME_TRACY_DISAPPEAR)
@CLRF(FLG_MYHOME_1F_TRACY_APPEAR)
』


;@Habitat:オネット/ネスの家/トレーシーの部屋
;@Person:トレーシー
;@Figure:トレーシー
;@AppearanceKey:0
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MYHOME_TRACY
MSG_MYHOME_TRACY;
@CHKFGOTO(FLG_WIN_GIEGU,MSG_MYHOME_TRACY_END)
@CHKFGOTO(FLG_ONET_STONE_REJECTED,_TRACY_STONE)
@CHKFGOTO(FLG_ITEM_TRACY,MSG_TRACY)
◆I’ll do everything I can to help you!@WI(20)  Good luck on your adventure.@KEY()↓
◆You might get hungry along the way,@WI(15) so here is a @DSP_GOODS(GDS_FOOD_COOKIE).
;jpn:◆わたし おにいちゃんの↓
;jpn: ぼうけんを おうえんするわ。@KEY()↓
;jpn:◆おなかがへるかも しれないから↓
;jpn: わたしのクッキーを あげるね。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_MYHOME_TRACY_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_FOOD_COOKIE)
@SETF(FLG_ITEM_TRACY)
@GOSUB(MSG_SUB_GETGOODS)
@KEY()↓
◆You can also leave anything you don’t need with me.@KEY()↓
◆Do you want me to hang on to something?↓
<Yes> <No>
;jpn:◆じゃまな にもつがあったら↓
;jpn: あずかってあげるわよ。↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MYHOME_TRACY_YES,_MYHOME_TRACY_NO)
_MYHOME_TRACY_NO;
◆Be careful!
;jpn:◆じゃ きをつけてね!
@KEYNP()
』
_MYHOME_TRACY_YES;
_MYHOME_TRACY1;
@GOSUB(MSG_TRACY_AZUKERU)
』

_MYHOME_TRACY_ITEMFULL;
←
@SE(SE_se05_undo)
◆You have too much stuff.
;jpn:◆もちものが いっぱいよ!
@KEYNP()
』

_TRACY_STONE;音の石をあずかっている
◆What?@WI(20)  The Sound Stone?@KEY()↓
◆I wonder when I got this from you?@WI(20)  Let me give it back to you...
;jpn:◆えっ@WI(15) 「おとのいし」?@WI(20)↓
;jpn: ‥‥あら ほんと@WI(15)↓
;jpn: いつのまに あずかったのかしら?@KEY()↓
;jpn:◆おにいちゃんに かえすわね。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TRACY_STONE_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_SOUND_STONE)
@SETF(FLG_ITEM_TRACY)
@GOSUB(MSG_SUB_GETGOODS_S)
@KEYNP()
@CLRF(FLG_ONET_STONE_REJECTED)
』
_TRACY_STONE_GOODSFULL;
◆Ooops!@WI(20)  You seem to be carrying too much stuff already!
;jpn:◆あら でも↓
;jpn: もちものが いっぱいね!
@KEYNP()
』
MSG_MYHOME_TRACY_END;&
@CHKFGOTO(FLG_MYHOME_TRACY_FINAL,_MYHOME_TRACY_END_FINAL)
◆Goody!@WI(20)  My brother is back!@KEY()↓
◆You’ve got a lot of catching up to do with your schoolwork, *Hyork*!@KEY()↓
◆If you have any problems with your assignments,@WI(15) I’ll help you.@KEY()↓
◆Don’t get freaked out.@KEY()↓
◆Did Escargot Express,@WI(15) my old company,@WI(15) help you?@KEY()↓
◆I’ve saved some money,@WI(15) so we’ll do the lunch thing sometime.@KEY()↓
◆You also got a new girlfriend?@KEY()
◆Your adventure must have been pretty good!
;jpn:◆わーい おにいちゃんが↓
;jpn: かえってきた。@KEY()↓
;jpn:◆がっこうの べんきょう↓
;jpn: ずいぶん↓
;jpn: おくれちゃったんじゃない?@KEY()↓
;jpn:◆わからないところがあったら↓
;jpn: わたしが おしえてあげるから↓
;jpn: だいじょうぶよ。@KEY()↓
;jpn:◆わたしの アルバイトしてた↓
;jpn: エスカルゴうんそう↓
;jpn: やくにたった?@KEY()↓
;jpn:◆アルバイトのおかげで↓
;jpn: ずいぶん おかね たまったから↓
;jpn: こんど おごってあげるね。@KEY()↓
;jpn:◆ガールフレンドも↓
;jpn: できたみたいだし。@KEY()↓
;jpn:◆いいたびだったわね。
@KEY()↓
_MYHOME_TRACY_END_FINAL;
◆Do you need help with anything other than your schoolwork?@KEY()↓
<Yes> <No>
;jpn:◆しゅくだい いがいで↓
;jpn: まだ わたしに↓
;jpn: してあげられることは ある?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(MSG_TRACY_GLOBAL_START2,_MYHOME_TRACY_END_NO)
_MYHOME_TRACY_END_NO;いいえ
◆Okay,@WI(15) you relax now.
;jpn:◆じゃ@WI(15) ゆっくり やすんでね。
@KEYNP()
』

;◆Oh, I almost forgot...↓
;  Can I help you with your stuff?@KEY()↓
;<Leave> <Pick up>
;◆あ わたしの でばんね。@WI(15)↓
; ごようは なーに?↓
;  <あずける>  <もちだす>
;@DSP_ITEM(2)
;@SELGOTO(_MYHOME_TRACY_AZUKERU,_MYHOME_TRACY_MOTIDASU)
;』

;_MYHOME_TRACY_AZUKERU;
;@Q_TRACYFULL()
;@TRUE_GOTO(_MYHOME_TRACY_TRACYFULL)
;◆(Sorry for inconvenience due to my work.)
;◆(せいさくちゅうにつき↓
; ごめいわくを おかけします)@KEY()↓
;@GOTO(_MYHOME_TRACY_BYE)
;』

;@SEL_GOODS()
;@FALSE_GOTO(_MYHOME_TRACY_)
;@TRACY_IN(0)
;◆Okay, I’ll keep↓
;  @DSP_GOODS(0) safe.@KEY()↓
;◆Do you have anything else for me to hold?
;<Yes> <No>

;◆@DSP_GOODS(0)ね。↓
; だいじに しまっとくわ。@WI(15)↓
; ほかに あずけるものは ある?@KEY()↓
;  <ある>  <ない>
;@DSP_ITEM(2)
;@SELGOTO(_MYHOME_TRACY_AZUKERU,_MYHOME_TRACY_BYE)
;@GOTO(_MYHOME_TRACY_BYE)

;_MYHOME_TRACY_MOTIDASU;※使っていないはず
;←
;◆(Sorry for inconvenience due to my work.)
;◆(せいさくちゅうにつき↓
; ごめいわくを おかけします)@KEY()↓
;@GOTO(_MYHOME_TRACY_BYE)
;』

;@SUB(SUB_SELECT_AND_ADD_POSSESS)
;◆@DSP_GOODS(0).  OK.↓
; Take care of it.@KEY()↓
;◆Is there anything else you want back?↓
;  <Yes>  <No>
;◆@DSP_GOODS(0)ね。@WI(15)↓
; だいじに してね。@WI(15)↓
; ほかに もっていくものは ある?@KEY()↓
;  <ある>  <ない>↓
;@SELGOTO(_MYHOME_TRACY_MOTIDASU,_MYHOME_TRACY_BYE)

;_MYHOME_TRACY_BYE;
;◆See you around!  Be good!
;◆じゃ きをつけてね!@KEY()
;』

;_MYHOME_TRACY_TRACYFULL;
;◆Sorry.
;	My locker is full.
;◆ごめんなさい。@WI(15)↓
; ロッカールームが↓
; いっぱいになっちゃったの。@KEY()
;@GOTO(_MYHOME_TRACY_BYE)
;』

;----------------------------------------

;@Habitat:オネット/バーガーショップ/バーガーショップ
;@Person:店員左手
;@Figure:ウェイトレスB
;@AppearanceKey:0
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HAMBURGER_WAITRESSA
MSG_ONET_HAMBURGER_WAITRESSA;
@CHKFGOTO(FLG_TEMP_2,MSG_ONET_HAMBURGER_TMP)
;◆Alright, what’re ya havin’?! 
;◆あら いらっしゃい。@WI(15)↓
; なにを おもとめかしら?@KEY()
@GOSUB(MSG_SHOP_ONET_HAMBURGER)
;@SETF(FLG_TEMP_1);SHOP.MSGの買い物後にセット
』

MSG_ONET_HAMBURGER_TMP;
◆If you buy something from me,@KEY()↓
◆I’ll give you a big discount,@WI(15) tee hee hee.
;jpn:◆わたしから かいものすれば↓
;jpn: すこし サービスして↓
;jpn: あげたのにねぇ@WI(15) フフッ。
@KEYNP()
』

;@Habitat:オネット/バーガーショップ/バーガーショップ
;@Person:店員右手
;@Figure:ウェイトレスB
;@AppearanceKey:0
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HAMBURGER_WAITRESSB
MSG_ONET_HAMBURGER_WAITRESSB;
@CHKFGOTO(FLG_TEMP_1,MSG_ONET_HAMBURGER_TMP)
;◆Hi.  What’ll it be today? 
;◆あら いらっしゃい。@WI(15)↓
; なにを おもとめかしら?@KEY()
@GOSUB(MSG_SHOP_ONET_HAMBURGER_2)
;@SETF(FLG_TEMP_2);SHOP.MSGの買物後にセット
』

;@Habitat:オネット/バーガーショップ/バーガーショップ
;@Person:客A
;@Figure:おばさんB
;@AppearanceKey:0
;@ActionScript:*小範囲でうろつく
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HAMBURGER_OBASAN
MSG_ONET_HAMBURGER_OBASAN;
◆It seems like I’m always here...@WI(20)  I hope you don’t mind!
;jpn:◆あたし いつも このみせに↓
;jpn: いるような きがするんだけど@WI(15)↓
;jpn: きにしないでね。
@KEYNP()
』


;@Habitat:オネット/バーガーショップ/バーガーショップ
;@Person:客B
;@Figure:リボン
;@AppearanceKey:0
;@ActionScript:*小範囲でうろつく
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HAMBURGER_GIRL
MSG_ONET_HAMBURGER_GIRL;
◆I’m so much more relaxed here...@KEY()↓
◆They never ask me@WI(30) ”Would you like fries with that shake?”
;jpn:◆このみせは ハンバーガーを↓
;jpn: かっても 「おのみものは?」とか↓
;jpn: いわないから きらくだよね。
@KEYNP()
』


;----------------------------------------
;@Habitat:オネット/ヒントショップ/ヒントショップ
;@Person:ヒントオヤジ
;@Figure:ヒント屋
;@AppearanceKey:0
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HINTMAN
;MSG_ONET_HINTMAN;ショップ2へ移動
;@MUL_ACTIVE_PLAYER(35)
;@GOTO(MSG_SUB_HINTSHOP)
;@GOTO(MSG_HINT);グローバルのヒントメッセージへ
;◆Hang on just a second, young man! 
;	I want to give you a hint. 
;	I don’t know how to say this... 
;◆Please don’t hate me. 
;◆ちょっとまった!ヤングマン@WI(20)↓
; ヒントを あげたいんだけど↓
; まだ おもいつかないんだ。@KEY()↓
;◆わるいね。@KEYNP()
;』


;----------------------------------------
;@Habitat:オネット/ベーカリー/ベーカリー
;@Person:店員
;@Figure:コック
;@AppearanceKey:0
;@ActionScript:*正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_BAKERY_CLERK
MSG_ONET_BAKERY_CLERK;
;◆Welcome.
;◆いらっしゃい。@KEY()↓
@GOSUB(MSG_SHOP_ONET_BAKERY)
』


;@Habitat:オネット/ベーカリー/ベーカリー
;@Person:客A
;@Figure:おばさんB
;@AppearanceKey:0
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_BAKERY_OBASAN
MSG_ONET_BAKERY_OBASAN;パン屋客 おばさん
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_BAKERY_OBASAN_END)
@CHKFGOTO(FLG_ONET_BAKERY_OBASAN,_ONET_BAKERY_OBASAN_3)
@CHKFGOTO(FLG_TEMP_1,_ONET_BAKERY_OBASAN_2)
◆I want to tell you the story of the creature from the vegetable soup,@KEY()↓
◆but I won’t because I don’t want to bother you with a story@KEY()↓
◆that has nothing to do with your adventure.@KEY()↓
◆If I keep talking about unrelated stuff,@KEY()↓
◆you might start ignoring important messages.@KEY()↓
◆It’s important for you to talk to people.@KEY()↓
◆Also,@WI(15) a person might give you a different message,@KEY()↓
◆depending on when you speak to them.

;jpn:◆わたし↓
;jpn: 「やさいスープのかいじん」の↓
;jpn: はなしを‥‥@KEY()↓
;jpn:◆しようとおもったんだけど@KEY()↓
;jpn:◆ゲームにかんけいあると↓
;jpn: おもわれると こまるんで↓
;jpn: やめとくわ。@KEY()↓
;jpn:◆そういう よけいなことを↓
;jpn: あんまり はなしてると@KEY()↓
;jpn:◆だいじな はなしを↓
;jpn: きかない くせが↓
;jpn: ついちゃうでしょ。@KEY()↓
;jpn:◆でもね ほんとに いろんなひとと↓
;jpn: こまめに はなしをすることが↓
;jpn: だいじよ。@KEY()↓
;jpn:◆おんなじひとでも↓
;jpn: じょうきょうによって↓
;jpn: はなすことが かわるんだから。
@KEYNP()
@SETF(FLG_TEMP_1)
』
_ONET_BAKERY_OBASAN_2;
◆Thank you for taking the time to talk to me again.@KEY()↓
◆Ah!@WI(30)  So you see what I mean!@WI(15)  It’s important to take time out to talk with many people.
;jpn:◆あなた やっぱり↓
;jpn: もういっかい↓
;jpn: はなしかけてくれたわね。@KEY()↓
;jpn:◆‥‥と いうぐあいに↓
;jpn: こまめに はなすことが↓
;jpn: だいじなのよ。
@KEYNP()
@SETF(FLG_ONET_BAKERY_OBASAN);セリフ替え
』
_ONET_BAKERY_OBASAN_3;
◆Yes!@WI(15)  Keep the lines of communication open.@WI(15)  Just like you are doing now.
;jpn:◆そう そう!@WI(20)↓
;jpn: そんなふうに こまめにね。
@KEYNP()
』
_ONET_BAKERY_OBASAN_END;&
◆Isn’t it nice to talk to so many people?
;jpn:◆たくさんの ひとと↓
;jpn: たくさんの かいわができて↓
;jpn: よかったわね。
@CHKFGOTO(FLG_ONET_BAKERY_OBASAN,_ONET_BAKERY_OBASAN_END_2)
@KEYNP()
』
_ONET_BAKERY_OBASAN_END_2;
@KEY()↓
◆I gave you some advice when I spoke to you the first time,@WI(15) right?
;jpn:◆はじめてあったときに↓
;jpn: わたしが ちゅうこくしたでしょ。
@KEYNP()
』
;◆When I dropped my bread,
;	the crows got it. 
;◆Do you think they know the taste of bread? 
;◆パンを おとしたら↓
; カラスに とられちゃってね。@KEY()↓
;◆あいつら パンのあじが↓
; わかるのかしらねぇ。@KEYNP()
;』


;@Habitat:オネット/ベーカリー/ベーカリー
;@Person:客B
;@Figure:OL・G
;@AppearanceKey:0
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_BAKERY_MADAM
MSG_ONET_BAKERY_MADAM;パン屋 奥さん
◆I like cottage cheese on bread!@KEY()↓
◆You haven’t tried it?@WI(20)  It’s the latest craze in culinary circles!
;jpn:◆わたくし パンに なっとうを↓
;jpn: のせて たべるのが↓
;jpn: すきですのよ。@KEY()↓
;jpn:◆なっとうを しらないの?!@WI(15)↓
;jpn: おくれてるわねぇ。
@KEYNP()
』


;----------------------------------------
;@Habitat:オネット/ポーキーの家/1階
;@Person:ミンチ氏
;@Figure:ミンチ氏
;@AppearanceKey:FLG_ONET_MINCES_APPEAR/on
;@ActionScript:*演出コンテ#1.5
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_AMBRAMI_MINCE
;★特殊イベントメッセージ(S_EVENT.MSG)へ


;@Habitat:オネット/ポーキーの家/1階
;@Person:ミンチ夫人
;@Figure:ラードナー
;@AppearanceKey:FLG_ONET_MINCES_APPEAR/on
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_LARDNA_MINCE
MSG_LARDNA_MINCE;
@CHKFGOTO(FLG_WIN_GIEGU,_LARDNA_MINCE_END)
@CHKFGOTO(FLG_POKEY,_LARDNA_MINCE_POKEY)
◆My husband is very soft−hearted.
;jpn:◆ほんとに うちのひとの↓
;jpn: おひとよしにゃ あきれるよ。
@KEYNP()
』
_LARDNA_MINCE_POKEY;
◆Where in sam hill have you boys been?@KEY()↓
◆I’ll have to think of a suitable punishment!
;jpn:◆いったい どこを↓
;jpn: ほっつき あるいてたんだい↓
;jpn: あんたたちは!@KEY()↓
;jpn:◆おしおきだよ!
@KEYNP()
』
_LARDNA_MINCE_END;&松
◆As usual,@WI(15) you’re wearing your grubbies!@WI(20)  So,@WI(10) what do you want?@KEY()↓
◆My son isn’t at home now.@WI(20)  He’s walking around somewhere.@KEY()↓
◆My husband is also gone.@WI(30)  Oh yes,@WI(15) this is Mr. Prettyman.@KEY()↓
◆He always has great advice.@WI(15)  He’s a real gentleman,@WI(10) he is.@KEY()↓
◆You’ll be happy that you met him.
;jpn:◆あら @DSP_STS(STS_PC_NAME_NES)ちゃん↓
;jpn: あいかわらず↓
;jpn: チープな ふくきて どうしたの?@KEY()↓
;jpn:◆うちの ブタむすこなら↓
;jpn: いないわよ。@KEY()↓
;jpn:◆どこを ほっつきあるいてんだか。@KEY()↓
;jpn:◆ていしゅも↓
;jpn: あそびに でかけちゃったまま↓
;jpn: かえってこないし‥‥。@KEY()@WI(20)↓
;jpn:◆あ@WI(10) こちら いま いろいろと↓
;jpn: そうだんに のってもらっている↓
;jpn: カラーマンさん。@KEY()↓
;jpn:◆すばらしい しんしよ。@WI(30)↓
;jpn: これからも よろしくね。
@KEYNP()
』

MSG_ONET_MINCE_COLORMAN;&カラーマン氏
◆Salutations!@WI(20)  You’re the boy living next door.@KEY()↓
◆I heard that your family is in debt.@WI(20)  Ms. Minch told me about it.@KEY()↓
◆Well live and learn.@WI(20)  You just have to keep plugging away.
;jpn:◆はじめまして あなたが↓
;jpn: ばくだいなしゃっきんをしている↓
;jpn: おとなりの ちょうなんですね。@KEY()↓
;jpn:◆ミンチふじんから いろいろと↓
;jpn: おはなしは きいています。@KEY()↓
;jpn:◆ま@WI(10) しゃっきんは↓
;jpn: しゃっきんとして@WI(15) これからも↓
;jpn: なかよく やっていきましょう。
@KEYNP()
』


;@Habitat:オネット/ポーキーの家/2階
;@Person:しかられポーキー
;@Figure:ポーキー
;@AppearanceKey:FLG_ONET_2FPOKEY_APPEAR/on
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POKEY
MSG_ONET_POKEY;
◆My dad really got after me.@KEY()↓
◆He said I get no dessert for the rest of the decade...
;jpn:◆とーちゃんに どえらく↓
;jpn: どやされちまったよ。@KEY()↓
;jpn:◆ああ おしりがいたい。
@KEYNP()
』


;@Habitat:オネット/ポーキーの家/2階
;@Person:しかられピッキー
;@Figure:ピッキー
;@AppearanceKey:FLG_ONET_2FPICKEY_APPEAR/on
;@ActionScript:*小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_PICKEY
MSG_ONET_PICKEY;自宅ピッキー
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_PICKEY_LATER)
◆I don’t wanna look at the meteorite anymore.
;jpn:◆もう いんせきなんて↓
;jpn: みに いきたくないよ。
@KEYNP()
』
_ONET_PICKEY_LATER;&
◆I haven’t seen you in a while.@WI(20)  You look cool.@KEY()↓
◆I’m nowhere near as cool as you.@WI(20)  I’m just average cool.@KEY()

;jpn:◆あれ @DSP_STS(STS_PC_NAME_NES)↓
;jpn: しばらく かおを みなかったけど↓
;jpn: げんきそうだね。@KEY()↓
;jpn:◆ぼくは あんまり↓
;jpn: げんきそうじゃないよ。@WI(15)↓
;jpn: ふつう‥‥かな。
@KEYNP()
』
;-------------------------------------------------

;@Habitat:オネット/ホテル/受付
;@Person:フロントマン
;@Figure:おじさんB
;@AppearanceKey:0
;@ActionScript:*正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOTELMAN
MSG_ONET_HOTELMAN;
;◆Welcome to Hotel Onett.
;◆ホテルオネットへ ようこそ。@KEY()↓
;@GOSUB(MSG_GLOBAL_HOTEL)
;←
;◆Thank you.  Please come again.
;◆また どうぞ‥‥↓
;@GET_ORDER_PLAYER(1)
;@SET_REG(0)
; @DSP_NAME(0)さま。@KEYNP()
;@GOSUB(MSG_TEST_HOTEL)
』


;@Habitat:オネット/ホテル/受付
;@Person:ボーイ
;@Figure:ホテルボーイ
;@AppearanceKey:0
;@ActionScript:*正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOTELPORTER
MSG_ONET_HOTELPORTER;
◆Our nightly rate is not cheap,@KEY()↓
◆but we have clean sheets, and the rooms are secure.@KEY()↓
◆I hope you understand that this keeps us very busy.
;jpn:◆ホテルのりょうきんは↓
;jpn: けっして やすくないけど@KEY()↓
;jpn:◆シーツのせんたくとか↓
;jpn: あんぜんの かくほとか@KEY()↓
;jpn:◆いろいろたいへんなんですから↓
;jpn: わかってくださいね。
@KEYNP()
』


;@Habitat:オネット/ホテル/受付
;@Person:電話
;@Figure:電話
;@AppearanceKey:0
;@ActionScript:*正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

;@Habitat:オネット/ホテル/CDルーム
;@Person:キャッシュディスペンサ
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:*正面向いて固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;@Habitat:オネット/ホテル/廊下
;@Person:客♀
;@Figure:OL・C
;@AppearanceKey:FLG_ONET_HOTELCOUPLE/off
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOTEL_WOMAN
MSG_ONET_HOTEL_WOMAN;
◆You look like a real target for the Sharks.@WI(20)  You’d better be careful.
;jpn:◆あんたも シャークだんとかに↓
;jpn: いんねんつけられそうな↓
;jpn: かおしてるから きをつけるのよ。
@KEYNP()
』


;@Habitat:オネット/ホテル/廊下
;@Person:客♂
;@Figure:サラリーマンA
;@AppearanceKey:FLG_ONET_HOTELCOUPLE/off
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOTEL_MAN
MSG_ONET_HOTEL_MAN;
◆Can you believe it?@KEY()↓
◆A group of ruffians spit their gum on me as I was passing by...
;jpn:◆まちの チンピラどもに↓
;jpn: ガムを ペッて されたよ。
@KEYNP()
』


;@Habitat:オネット/ホテル/部屋1
;@Person:客♀
;@Figure:OL・C
;@AppearanceKey:FLG_ONET_HOTELCOUPLE/on
;@ActionScript:*広範囲あわてる
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOTEL_WOMAN2
MSG_ONET_HOTEL_WOMAN2;
◆Do you think you can come up and talk to me anytime you want?
;jpn:◆そんなに きがるに↓
;jpn: はなしかけるものじゃ ないわよ!
@KEYNP()
』


;@Habitat:オネット/ホテル/部屋1
;@Person:客♂
;@Figure:サラリーマンA
;@AppearanceKey:FLG_ONET_HOTELCOUPLE/on
;@ActionScript:*広範囲あわてる
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_HOTEL_MAN2
MSG_ONET_HOTEL_MAN2;
◆I’ve seen you around a lot lately.  He he he.
;jpn:◆きみとは よくあうね。へへへ。
@KEYNP()
』


;----------------------------------------
;@Habitat:オネット/警察署/受付
;@Person:警察署長
;@Figure:警察署長
;@AppearanceKey:FLG_ONET_5COP_APPEAR/off
;@ActionScript:*正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POLICEOFFICER_A
MSG_ONET_POLICEOFFICER_A;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_STRONG_END)
@CHKFGOTO(FLG_ONET_GATEOPEN,_ONET_STRONG_2)
@CHKFGOTO(FLG_POWR_GIAN,_ONET_STRONG)
◆The townspeople are in a state of confusion.@KEY()↓
◆At times like this,@WI(15) riots break out,@WI(15) or people start acting wild,@KEY()↓
◆so we police are being ultra cautious.

;jpn:◆まちは いま みょうに↓
;jpn: ざわめいておる。@KEY()↓
;jpn:◆こういうときは ぼうどうが↓
;jpn: おきたり@KEY()↓
;jpn:◆わるさをするやつが でてくるんで↓
;jpn: けいさつは ピリピリしてるんだ。
@KEYNP()
』

_ONET_STRONG;
◆Why is the road to Twoson closed?@WI(20)  An emergency,@WI(10) of course.@KEY()↓
◆At times like this,@WI(15) kids like you should be playing Nintendo games.@KEY()↓
◆Anyway,@WI(15) are you sure you want to go to Twoson?↓
<Yes> <No>
;jpn:◆ツーソンへの みちが↓
;jpn: ふさがれてるって?@KEY()↓
;jpn:◆とうぜんじゃないか。↓
;jpn: いまは ひじょうじ なのだ。@KEY()↓
;jpn:◆こどもは うちで↓
;jpn: ニンテンドーでも してればよい。@KEY()↓
;jpn:◆どうしても ツーソンに↓
;jpn: いくつもりなのかな?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_STRONG_YES,_ONET_STRONG_NO)

_ONET_STRONG_NO;
◆Well then,@WI(15) perhaps you should just crawl back to your shack,@WI(15) little mister.
;jpn:◆それでは おうちに↓
;jpn: かえりなさい。ぼうや。
@KEYNP()
』

_ONET_STRONG_YES;
◆Okay, *chortle*@WI(15)  Follow me.
;jpn:◆そうか‥‥。@KEY()↓
;jpn:◆ふふふ‥‥それでは@WI(20)↓
;jpn: わたしに ついてきなさい。
@KEY()
@SETF(FLG_POLICE_5COP_APPEAR)
@CLRF(FLG_ONET_COPA_DISAPPEAR)
@CLRF(FLG_ONET_COPB_DISAPPEAR)
@CLRF(FLG_ONET_COPC_DISAPPEAR)
@CLRF(FLG_ONET_COPD_DISAPPEAR)
@CLRF(FLG_ONET_COPE_DISAPPEAR)
@CLOSEALL()
@GOTO(MSG_EVT_22_STRONG)
』

_ONET_STRONG_2;
◆I’ve been playing ”EarthBound” lately...@WI(20)  I’m having a tough time.
;jpn:◆さいきん「マザー2」を↓
;jpn: やっているのだが なかなか↓
;jpn: くろうしてるよ。
@KEYNP()
』
_ONET_STRONG_END;&
◆So you’ve traveled all over the world.@KEY()↓
◆I bet you haven’t met anyone stronger than I,@WI(10) did you?@KEY()↓
◆I know that you didn’t ...Wa ha ha ha!

;jpn:◆せかいじゅうを↓
;jpn: たびしてきたらしいが@KEY()↓
;jpn:◆わたしより つよいものは↓
;jpn: いなかっただろう?@KEY()@WI(10)↓
;jpn:◆そうか いなかったか@WI(10)↓
;jpn: ワッハッハ!
@KEYNP()
』

;@Habitat:オネット/警察署/受付
;@Person:受付嬢
;@Figure:女店員A
;@AppearanceKey:0
;@ActionScript:*正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POLICEOFFICER_C
MSG_ONET_POLICEOFFICER_C;
@CHKFGOTO(FLG_ONET_GATEOPEN,_ONET_POLICEOFFICER_C_LATER)
◆I would rather be working as a parking meter cop...@KEY()↓
◆It’s just been too busy lately.@WI(15)  I’m sick of it.
;jpn:◆ちゅうしゃいはんの↓
;jpn: とりしまりでも してたほうが↓
;jpn: らくだったのに@KEY()↓
;jpn:◆なんだか いそがしくなって↓
;jpn: いやぁねぇ。
@KEYNP()
』

_ONET_POLICEOFFICER_C_LATER;
◆Well,@WI(15) the riot’s over.@WI(15)  Now I can move on to parking enforcement!@KEY()↓
◆Hooray!@WI(15)  Life is good.@WI(20)  Dum dee dee dee...
;jpn:◆そうどうが おさまったんで↓
;jpn: だいすきな ちゅうしゃいはんの↓
;jpn: とりしまりに せいをだせるわ。@KEY()↓
;jpn:◆うれしいなっ。ランラン。
@KEYNP()
』


;@Habitat:オネット/警察署/受付
;@Person:受付係♂
;@Figure:警官
;@AppearanceKey:0
;@ActionScript:*正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POLICEOFFICER_B
MSG_ONET_POLICEOFFICER_B;
@CHKFGOTO(FLG_ONET_GATEOPEN,_ONET_POLICEOFFICER_B_LATER)
◆Man,@WI(15) am I steamed...@WI(20)  Don’t even try talking to me.
;jpn:◆ピリピリしてるんだ!↓
;jpn: はなしかけないでくれ。
@KEYNP()
』

_ONET_POLICEOFFICER_B_LATER;
◆Why are you asking about a driver’s license?@KEY()↓
◆You’re way too young to even think about getting behind the wheel,@WI(15) you little pest.
;jpn:◆じどうしゃめんきょのことなんか↓
;jpn: こどもが そうだんして↓
;jpn: どうするんだ。@WI(15)めんどくさい。
@KEYNP()
』


;@Habitat:オネット/警察署/受付
;@Person:Gステップの見張り
;@Figure:警官
;@AppearanceKey:FLG_POLICE_KANBANCOP_APPEAR/on
;@ActionScript:*ネスに近寄って台詞MSG_ONET_POLICE_KANBAN_SCOLD発行
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POLICE_KANBAN_LATER
MSG_ONET_POLICE_KANBAN_LATER;
@CHKFGOTO(FLG_TEMP_1,_ONET_POLICE_KANBAN_TMP)
◆So here you are.@KEY()↓
◆You’re the little delinquent that came back from Giant Step!@KEY()↓
◆Now you listen here...@KEY()↓
◆”Don’t Enter” means just that−−@WI(30) DO NOT ENTER!@WI(10)  You got that?@KEY()↓
◆And furthermore...@KEY()↓
◆Blah@WI(10) blah@KEY()↓
◆Blah@WI(10) blah@KEY()↓
;jpn:◆やっと きたか。@WI(20)↓
;jpn: ジャイアントステップがえりの↓
;jpn: なまいきな しょうねんよ!@KEY()↓
;jpn:◆いいか よくきけ!@WI(20)↓
;jpn: 「たちいりきんし」ということは↓
;jpn: たちいりを きんじるといういみで@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
_ONET_POLICE_KANBAN_TMP;
◆It’s usually those tax evaders who...@KEY()↓
◆Blah blah@KEY()↓
◆Blah blah@KEY()↓
◆We don’t enjoy blocking off the roads,@WI(15) you know...@KEY()↓
◆Blah blah@KEY()↓
◆Blah blah@KEY()↓
◆It’s usually the local whiners that make a big deal about emergencies and meteorites!@KEY()↓
◆Blah blah@KEY()↓
◆Blah blah@KEY()↓
◆Blah blah
;jpn:◆ぜいきんも まともに↓
;jpn: はらわないやつにかぎって@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆こっちだって すきで↓
;jpn: あちこち ふうさしてるわけじゃ@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥
@KEYNP()
@SETF(FLG_TEMP_1)
』
;◆It’s always those who don’t pay 
;  their fair share of taxes...
;◆that make the most noise about
;  emergencies like this meteorite! 
;◆Blah, blah...
;◆Blah, blah...
;◆Blah, blah...
;◆ぜいきんも まともに↓
; はらわないやつにかぎって@KEY()↓
;◆ひじょうじたい だの↓
; いんせき だのと↓
; おおさわぎするんだ!@KEY()↓
;◆くどくど‥‥@KEY()↓
;◆くどくど‥‥@KEY()↓
;◆くどくど‥‥@KEYNP()
;』

MSG_ONET_POLICE_KANBAN_SCOLD;
◆Didn’t you see the ”Don’t Enter” sign?@KEY()↓
◆That means I’m there to stop you when you’re on your way out!@KEY()↓
◆So pay attention next time...@KEY()↓
◆And furthermore...@KEY()↓
◆Blah,@WI(10) blah@KEY()↓
◆Blah,@WI(10) blah 
;jpn:◆たちいりきんしのカンバンが↓
;jpn: あったということは@KEY()↓
;jpn:◆たちいりを きんししてると↓
;jpn: いうことなんだぞ。@KEY()↓
;jpn:◆ちゅうごしで はいろうが↓
;jpn: はいつくばって はいろうが@KEY()↓
;jpn:◆た@WI(10)ち@WI(10)い@WI(10)り@WI(10) ということ なのだ!@WI(15)↓
;jpn: わかるか?@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥@KEY()↓
;jpn:◆くどくど‥‥
@KEYNP()
@SETF(FLG_POLICE_KANBANCOP_HEAR)
』


;@Habitat:オネット/警察署/廊下
;@Person:刑事
;@Figure:サラリーマンC
;@AppearanceKey:0
;@ActionScript:*中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_POLICE_GANG
MSG_ONET_POLICE_GANG;
◆Psst!@WI(20)  I’m not really one of the gang.@KEY()↓
◆I’m a cop,@WI(15) even if I don’t look like it.
;jpn:◆おれを ぼうりょくだんと↓
;jpn: まちがえるなよ。@WI(15)こうみえても↓
;jpn: けいかんなんだからな。
@KEYNP()
』


;@Habitat:オネット/警察署/道場
;@Person:五人抜きA
;@Figure:警官
;@AppearanceKey:FLG_ONET_COPA_DISAPPEAR/off
;@ActionScript:*演出コンテ#1.10
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_COPA


;@Habitat:オネット/警察署/道場
;@Person:五人抜きB
;@Figure:警官
;@AppearanceKey:FLG_ONET_COPB_DISAPPEAR/off
;@ActionScript:*演出コンテ#1.10
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_COPB


;@Habitat:オネット/警察署/道場
;@Person:五人抜きC
;@Figure:警官
;@AppearanceKey:FLG_ONET_COPC_DISAPPEAR/off
;@ActionScript:*演出コンテ#1.10
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_COPC


;@Habitat:オネット/警察署/道場
;@Person:五人抜きD
;@Figure:警官
;@AppearanceKey:FLG_ONET_COPD_DISAPPEAR/off
;@ActionScript:*演出コンテ#1.10
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_COPD


;@Habitat:オネット/警察署/道場
;@Person:五人抜きE
;@Figure:警官
;@AppearanceKey:FLG_ONET_COPE_DISAPPEAR/off
;@ActionScript:*演出コンテ#1.10
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_COPE
MSG_ONET_COPE;
◆Let’s go,@WI(15) go@WI(10) og!@WI(15)  Oops!@WI(15)  My mistake,@WI(10) go!
;jpn:◆いくぞ いくぞ くいぞォ!↓
;jpn: あっ まちがえた いくぞォ!
@KEYNP()
@GOSUB(MSG_BATTLE_5COPS_E)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@OPEN(1)
←
◆’scuse me!@WI(20)  Uuuuuh...yeah.
;jpn:◆どーも しつれいいたしやしたっ!↓
;jpn: ジャン ジャン。
@KEYNP()
@SETF(FLG_ONET_COPE_DISAPPEAR)
』
;-----------------------------------------------------------