;@Habitat:ツーソン/カオス劇場/楽屋
;@Person:ミーハーのミチコ
;@Figure:少女A
;@AppearanceKey:MSG_TWSN_MICHIKO_APPEAR/off
;@ActionScript:◆止ったまま落ち着きない
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_MICHIKO_EXCITED
;楽屋でトンズラ・ラッキーといっしょ
MSG_TWSN_MICHIKO_EXCITED;
◆I’m so excited!@WI(20)  I might just wet myself.@WI(20)  My heart is going pitter patter!
;jpn:◆わたし かんげきして↓
;jpn: あたまが まっしろだしー。↓
;jpn: ドキドキ ワクワク。
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/楽屋
;@Person:ゴージャス
;@Figure:ゴージャス
;@AppearanceKey:FLG_TWSN_TONZURA_FREE/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_TONZURA_GORGEOUS
MSG_TWSN_TONZURA_GORGEOUS;
;トンズラのゴーヂャス(リーダー)
@CHKFGOTO(FLG_TEMP_2,_TWSN_GORGEOUS_AFTER)
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_GORGEOUS_AFTER)
◆Shaba do wap, diddly dee da.@WI(20)  Shaba di doo bee, bop wah.@KEY()↓
◆I got those debt blues, hm mm mm.@KEY()↓
◆If I had 10,000 dollars,@WI(15) I could pay off my debts and move on to the next town.@KEY()↓
◆I wonder if our bus still runs.@WI(20)  It may be rusted out...
;jpn:◆音 シャバドゥワ ダディダ↓
;jpn: シャバドゥビ ダー音@WI(20)↓
;jpn: しゃっきんブルース @WI(15)イエイ@KEY()↓
;jpn:◆1まんドルあれば↓
;jpn: しゃっきんも かえせて↓
;jpn: つぎのまちへ いける。@KEY()↓
;jpn:◆トラベリング・バスも もう↓
;jpn: さびついちまって↓
;jpn: うごくか どうか‥‥。
@KEYNP()
』
;演奏後のセリフ
_TWSN_GORGEOUS_AFTER;
◆Mr. Poochyfud, the Manager,@WI(15) is staring at you.@WI(20)  I wonder what he wants?
;jpn:◆しはいにんの↓
;jpn: ドッグフードのやつが@KEY()↓
;jpn:◆あんたのほうを↓
;jpn: みてたぜ。@WI(20)↓
;jpn: ‥‥なんなんだろう?
@KEYNP()
』
;「さつたば」つかうと
MSG_TWSN_GORGEOUS_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_SATSUTABA)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆Don’t try to use your play money here, kid.@KEY()↓
◆Oh...my...gosh...!@WI(20)  That’s not real money,@WI(15) is it?@WI(15)  Wow!
;jpn:◆そんな おもちゃの↓
;jpn: かねを みせびらかさんでくれ。@KEY()↓
;jpn:◆ま@WI(10)さ@WI(10)か‥‥@WI(20)おもちゃだろ?
@KEYNP()
』

;@Habitat:ツーソン/カオス劇場/楽屋
;@Person:ラッキー
;@Figure:ラッキー
;@AppearanceKey:FLG_TWSN_TONZURA_FREE/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_TONZURA_LUCKY
MSG_TWSN_TONZURA_LUCKY;
;トンズラのラッキー
@CHKFGOTO(FLG_TEMP_2,_TWSN_LUCKY_AFTER_TMP)
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_LUCKY_AFTER)
;DAN:This guy talks like a country guy.
◆Well,@WI(15) yeah, in the old days,@WI(15) there was lots o’ dancers and acts at this theater.@KEY()↓
◆’cept now,@WI(15) we’re the only act playin’ here.@KEY()↓
◆We even gone into debt here,@WI(15) so we’re pretty near stuck, hyuk, hyuk, hyuk.@KEY()↓
◆The folks of Twoson’ll enjoy the Runaway Five show for quite a few years,@KEY()↓
◆it looks like ta me.
;jpn:◆むかしは このカオスも↓
;jpn: かわいらしい おどりこが↓
;jpn: ようけ おったんや。@KEY()↓
;jpn:◆いまは わてらだけの↓
;jpn: ワンマンステージちゅうこっちゃ。@KEY()↓
;jpn:◆しゃっきんがあるから↓
;jpn: しばられとるんやけどな。↓
;jpn: カッカッカッ(わらいごえ)。@KEY()↓
;jpn:◆しゃっきんが あるかぎり↓
;jpn: せんねんでも まんねんでも@KEY()↓
;jpn:◆ツーソンの みなさんは↓
;jpn: おれたちの ステージを↓
;jpn: たのしめるって わけや。
@KEYNP()
』
;演奏後のセリフ
_TWSN_LUCKY_AFTER;
◆So, whaddya think?@KEY()↓
◆Do ya wanna see one more show?↓
  <Yes>  <No>
;jpn:◆どないだ?!@KEY()↓
;jpn:◆もう ワンステージ↓
;jpn: たのしんでいくか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_LUCKY_AFTER_YES,_TWSN_LUCKY_AFTER_NO)
_TWSN_LUCKY_AFTER_NO;
◆So, our sound is too much for ya, right?@WI(20)  I figured as much.
;jpn:◆わしらの おとは↓
;jpn: ヘビーやからな!@WI(20)↓
;jpn: むりもないわ!
@KEYNP()
』
_TWSN_LUCKY_AFTER_YES;
◆This is your chance fer a once in a lifetime event.
;jpn:◆めったにない↓
;jpn: チャンスやからな!
@KEYNP()
@CLRF(FLG_TWSN_CHAOS_STAGE_START)
@SETF(FLG_TEMP_2)
』
_TWSN_LUCKY_AFTER_TMP;
◆Ya got a once in a lifetime opportunity.@WI(20)  How ’bout watchin’@WI(15) one more show?
;jpn:◆めったにない↓
;jpn: チャンスやからな!@KEY()↓
;jpn:◆もう ワンステージ↓
;jpn: たのしんでいきな。
@KEYNP()
』

;「さつたば」つかうと
MSG_TWSN_LUCKY_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_SATSUTABA)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆Well, hello!  Ya got cash!@WI(20)  And some nice stuff ta boot!  Hyuk, hyuk, hyuk.
;jpn:◆おー かねや かねや↓
;jpn: ええもん もっとるなぁ↓
;jpn: カッカッカッカ!
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/楽屋
;@Person:ナイス
;@Figure:ナイス
;@AppearanceKey:FLG_TWSN_TONZURA_FREE/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_TONZURA_NICE
MSG_TWSN_TONZURA_NICE;
;トンズラBrs.のナイス
@CHKFGOTO(FLG_TEMP_2,_TWSN_NICE_AFTER)
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_NICE_AFTER)
◆Hey,@WI(15) ya get to see our show, you lucky kid!@WI(20)  I hope ya pay attention.
;jpn:◆ハーイ。@WI(20)↓
;jpn: わしらのステージが みられて↓
;jpn: ラッキーなやつじゃのう。@KEY()↓
;jpn:◆わしの ひろしまなまりを↓
;jpn: きにせんでくれ。
@KEYNP()
』
;演奏後のセリフ
_TWSN_NICE_AFTER;
◆That was a great gig!@KEY()↓
◆We can’t be this good all the time, can we? 
;jpn:◆なんねんぶりの↓
;jpn: グーな ステージじゃったわ。@KEY()↓
;jpn:◆とくしたのう!
@KEYNP()
』
;「さつたば」つかうと
MSG_TWSN_NICE_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_SATSUTABA)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆If you give him a chance,@WI(15) the theater manager will cheat you out of your money,@KEY()↓
◆he he he.
;jpn:◆そんなもん みせびらかすと↓
;jpn: ここの しはいにんに↓
;jpn: だましとられるぞ。@KEY()↓
;jpn:◆アハハハハハ。
@KEYNP()
』

;@Habitat:ツーソン/カオス劇場/楽屋
;@Person:オッケー
;@Figure:オッケー
;@AppearanceKey:FLG_TWSN_TONZURA_FREE/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_TONZURA_OKEY
MSG_TWSN_TONZURA_OKEY;
;トンズラのオッケー
@CHKFGOTO(FLG_TEMP_2,_TWSN_OKEY_AFTER)
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_OKEY_AFTER)
@CHKFGOTO(FLG_TEMP_1,_TWSN_TONZURA_OKEY_TEMP)
◆I wrote the lyrics to most of the Runaway Five songs.
;jpn:◆トンズラブラザーズのうたは↓
;jpn: ほとんど ぼくの さくしなんだ。
@KEY()↓
_TWSN_TONZURA_OKEY_TEMP;
◆Money, @WI(20)that’s what I want@WI(20)↓
  money, @WI(20)that’s what is hot@WI(20)↓
  money, @WI(20)that’s what I want@KEY()↓
◆money, @WI(20)it’s what we ain’t got ’cept freedom, freedom,@KEY()↓
◆freedom is what we’ve really sought!
;jpn:◆音かね @WI(20)それは ほしいもの@WI(20)↓
;jpn: かね @WI(20)とても ほしいもの@WI(20)↓
;jpn: かね @WI(20)おれの ほしいもの@KEY()↓
;jpn:◆音かね @WI(20)みんな ほしいもの@WI(20)↓
;jpn: だけど じゆうは もっとほしい@WI(20)↓
;jpn: 音それにつけても‥‥
@KEYNP()
@SETF(FLG_TEMP_1)
』
;演奏後のセリフ
_TWSN_OKEY_AFTER;
◆Cash, @WI(20)that’s what I want@WI(20)↓
  cash, @WI(20)that’s what is hot@WI(20)↓
  cash, @WI(20)that’s what I want@KEY()↓
◆...hey, I just made up a new song.
;jpn:◆音ぜに@WI(20) それは ほしいもの@WI(20)↓
;jpn: ぜに@WI(20) とても ほしいもの@WI(20)↓
;jpn: ぜに@WI(20) おれの ほしいもの@KEY()↓
;jpn:◆‥‥あたらしいうたが↓
;jpn: できそうだぞ。
@KEYNP()
』
;「さつたば」つかうと
MSG_TWSN_OKEY_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_SATSUTABA)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆Wow!  10,000 dollars!@WI(20)↓
  I can make another song now.@KEY()↓
◆Ten G’s,@WI(20)  ten G’s.@WI(20)↓
  That’s dollars,@WI(20) baby, dollars.@WI(20)↓
  Yeah yeah yeah.
;jpn:◆おお 1まんドルか!↓
;jpn: これは また うたになるなぁ。@KEY()↓
;jpn:◆いっちまんー@WI(20) ドルドル音↓
;jpn: イェイ イェイ@WI(20) イェイ音
@KEYNP()
』






;@Habitat:ツーソン/カオス劇場/楽屋
;@Person:グルービー
;@Figure:グルービー
;@AppearanceKey:FLG_TWSN_TONZURA_FREE/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_TONZURA_GROOVY
MSG_TWSN_TONZURA_GROOVY;
;グルービー
@CHKFGOTO(FLG_TEMP_2,_TWSN_GROOVY_AFTER)
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_GROOVY_AFTER)
◆I want some bread.@KEY()↓
◆I need the coinage.@KEY()↓
◆I want more dough all the time.
;jpn:◆かねが ほしい。@WI(20)↓
;jpn: いつも いつでも↓
;jpn: かねが ほしい。
@KEYNP()
』
;演奏後のセリフ
_TWSN_GROOVY_AFTER;
◆I didn’t make a spectacle of myself, did I?
;jpn:◆おれ ステージで↓
;jpn: あんまり めだたなかっただろ?
@KEYNP()
』
;「さつたば」つかうと
MSG_TWSN_GROOVY_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_SATSUTABA)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆That is exactly what I want.@KEY()↓
◆I can’t believe that you have that much...
;jpn:◆まるで おいらが↓
;jpn: ほしいもの。@KEY()↓
;jpn:◆いいなぁ↓
;jpn: こんなのがあったら‥‥。
@KEYNP()
』

;@Habitat:ツーソン/カオス劇場/支配人の部屋
;@Person:カオス支配人
;@Figure:カオス支配人
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:MSG_TWSN_CHAOS_RECEIVE
;@CheckMessage:0
;@Message:MSG_TWSN_CHAOS
MSG_TWSN_CHAOS;
;カオス劇場の支配人(ドッグフードさん)
@CHKFGOTO(FLG_TWSN_FIELD_TONZ_DISAPPEAR,_TWSN_DOGFOOD_STAGE)
_TWSN_CHAOS_MAIN;
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,_TWSN_CHAOS_LATER)
◆The Runaway Five owe me a lot of money.@KEY()↓
◆They’ll stay here until they pay me back.@KEY()↓
◆They might be here for 100 years,@KEY()↓
◆unless you decide to pay off their debt...  Heh, heh, heh.
;jpn:◆トンズラブラザーズのやつらにゃ↓
;jpn: たいへんなかねを かしてるんだ。@KEY()↓
;jpn:◆かえしてもらえるまでは↓
;jpn: 100ねんでも 200ねんでも↓
;jpn: ここで はたらいてもらうさ。@KEY()↓
;jpn:◆それとも あんたが かわりに↓
;jpn: かえしてくれるってのかい?↓
;jpn: アハハハハ。
@KEYNP()
』

_TWSN_CHAOS_LATER;
◆The Runaway Five are free to leave.@KEY()↓
◆I’ve got no complaints now that I have my money.
;jpn:◆トンズラブラザーズは↓
;jpn: もう じゆうのみだ。@WI(20)↓
;jpn: かねさえもらえば もんくはない。
@KEYNP()
』

MSG_TWSN_CHAOS_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_SATSUTABA)
@TRUE_GOTO(_TWSN_CHAOS_RECEIVE_SATUTABA)
@GOTO(MSG_SYS_GOODS_USE_NG)

_TWSN_CHAOS_RECEIVE_SATUTABA;
@CHKF(FLG_TWSN_CHAOS_STAGE_START)@FALSE_GOTO(_TWSN_DOGFOOD_STAGE);ステージ前だったら
@GET_ORDER_PLAYER(1)
@GET_PLAYER_DIR(0,2,PRSN_TWSN_CHAOS_MAN_A)
@XCHG()
@SAVE_REG()
@EQ(DIR_M_UP)
@TRUE_GOTO(_TWSN_DOGFOOD_RECEIVE_F)
@LOAD_REG()
@EQ(DIR_M_UP_RIGHT)
@TRUE_GOTO(_TWSN_DOGFOOD_RECEIVE_F)
@LOAD_REG()
@EQ(DIR_M_UP_LEFT)
@TRUE_GOTO(_TWSN_DOGFOOD_RECEIVE_F)
;
@SE(SE_se76_my_give)
@GET_CHAR_DIR(PRSN_TWSN_CHAOS_MAN_A,1,PC_NESS);ネスの方を向く
@SET_CHAR_DIR(PRSN_TWSN_CHAOS_MAN_A,0)
◆Yipes!@WI(60)  You surprised me.@WI(20)  Now I’m not sure what to do.
;jpn:◆(タラッ)@WI(60)びっくりして↓
;jpn: あせでちゃったよ。
@KEY()↓
@GOODSOUT(PC_ALL,GDS_TOOL_SATSUTABA)
◆I got the money, of course,@WI(15) and now the Runaway Five are free to leave.@KEY()↓
◆I’ve got no complaints now that I have my money.
;jpn:◆たしかに うけとった。@KEY()↓
;jpn:◆トンズラブラザーズは↓
;jpn: もう じゆうのみだ。@WI(20)↓
;jpn: かねさえもらえば もんくはない。
@KEY()
@SETF(FLG_TWSN_TONZURA_FREE)
@SETF(FLG_TWSN_TONZURABUS_APPEAR)
@CLRF(FLG_TWSN_TONCHIKI_APPEAR)
@GOTO(MSG_EVT_40_DOGFOOD)
』

;002_p
_TWSN_DOGFOOD_RECEIVE_F;
◆’scuse me?@WI(15)  What’s that you got there?  Let me take a re@WI(5)e@WI(5)e@WI(5)e@WI(5)al close look.
;jpn:◆そ それは なんだ?!↓
;jpn: もっと ちかくで みせてくれ!@KEY()↓
;jpn:◆おれの かおの すぐそばで!
@KEYNP()
』
_TWSN_DOGFOOD_STAGE;
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_CHAOS_MAIN)
◆Pardon?@WI(30)  You want to talk about money?@KEY()↓
◆How about later, after the show, even if we’re talking big bucks.@KEY()↓
◆I’ve got definite rules about how I handle my money matters...
;jpn:◆なに?@WI(30)↓
;jpn: カネのはなしだって?@KEY()↓
;jpn:◆たとえ もうけばなしでも↓
;jpn: ステージのあとにしてくれ。@KEY()↓
;jpn:◆おれは そういうことだけは↓
;jpn: ちゃんとしている↓
;jpn: にんげんなんだ。
@KEYNP()
』

;----------------------------------------
;@Habitat:ツーソン/トンチキの家/トンチキの家
;@Person:トンチキさん
;@Figure:ヌスットヌシ
;@AppearanceKey:FLG_TWSN_TONZURA_FREE/off
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_TONCHIKI
MSG_TWSN_TONCHIKI;
;ヌスット広場のトンチキさん
;ヌスットひろばのヌシのような存在。
;悪いことばかりしているらしいのだが、妙に正直なやつ。
@CHKFGOTO(FLG_TWSN_ITEM_TONCHIKI,_TWSN_TONCHIKI_LATER)
@CHKFGOTO(FLG_POLA,_TWSN_TONCHIKI_OK)
@CHKFGOTO(FLG_POLA_GRFD,_TWSN_TONCHIKI_POLA)
@CHKFGOTO(FLG_TWSN_WIN_TONCHIKI,_TWSN_TONCHIKI_WIN)
◆Wah ha ha ha ha!@WI(20)↓
  Why don’t we chat later−after  we’ve locked horns!
;jpn:◆ヌハハハハハハハッ!@WI(20)↓
;jpn: とにかく はなしは↓
;jpn: おれを たおしてからだ。
@KEY()
@GOSUB(MSG_BATTLE_TONCHIKI)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@OPEN(1)
◆Yes, I’m Everdred, boss of Burglin Park.@KEY()↓
◆When I jumped off the roof,@WI(15) I twisted my ankle.@KEY()↓
◆Anyway, I lost and nothing will change that.@KEY()↓
◆You know,@WI(15) you’re pretty strong.@KEY()↓
◆Yeah, I know that you want to find out about a girl named @DSP_NAME(PC_PAULA).@KEY()↓
◆She went off to a secret hideout in the Peaceful Rest Valley.@KEY()↓
◆A chubby boy and a weird guy in a blue outfit have kidnapped her, though.@KEY()↓
◆They said that they were going to make @DSP_NAME(PC_PAULA) some sort of human sacrifice.@KEY()↓
◆They were definitely hard−core strange.@KEY()↓
◆You know, she might be gone already.@WI(20)  You’d better hurry.@KEY()↓
;jpn:◆たしかに おれが↓
;jpn: ヌスットひろばのボスの↓
;jpn: トンチキだ。@KEY()↓
;jpn:◆やねから とびおりたとき↓
;jpn: あしを ねんざしちまってな。@KEY()↓
;jpn:◆‥‥とはいえ おれの↓
;jpn: まけは まけ。@KEY()↓
;jpn:◆たいした ぼうやだぜ。@KEY()↓
;jpn:◆どうせ ゆくえふめいの↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)って おんなのこの↓
;jpn: ことを ききたいんだろう。@KEY()↓
;jpn:◆おれは グレートフルデッドの↓
;jpn: たににある ひみつのこやを↓
;jpn: かしてやっただけだぜ。@KEY()↓
;jpn:◆デブのこどもと↓
;jpn: あおいふくをきた あやしいやつが↓
;jpn: さらってったんだ。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)ってこを↓
;jpn: なんとかきょうの いけにえに↓
;jpn: するとかって@KEY()↓
;jpn:◆はりきってたぜ。@KEY()↓
;jpn:◆もう ころされてるかも↓
;jpn: しれねぇな。@WI(20)はやく いってやれ。
@KEY()
_TWSN_TONCHIKI_WIN;
◆If you save @DSP_NAME(PC_PAULA),@WI(15) be sure to come back here, okay?@WI(15)  Don’t@WI(20) forget!
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)ってこを すくいだせたら↓
;jpn: また かならず ここにこい。@WI(60)↓
;jpn: か@WI(10)な@WI(10)ら@WI(10)ず@WI(10)だぜ!
@KEYNP()
@CLOSEALL()
@SETF(FLG_TWSN_WIN_TONCHIKI)
』

_TWSN_TONCHIKI_POLA;
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_TWSN_TONCHIKI_PAULA_NESS_DEAD)
@SET_LOOPREG(PC_PAULA)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_TWSN_TONCHIKI_PAULA_PAULA_DEAD)
◆First, you must take her to her parents.@WI(20)  They’re really worried.@KEY()↓
◆I also have something to give you,@WI(15) so be sure to come back here.@KEY()↓
◆Promise?@WI(20)  All right.
;jpn:◆おんなのこを とにかく はやく↓
;jpn: うちに つれてってやんな。@WI(20)↓
;jpn: おやが しんぱいしてるぜ。@KEY()↓
;jpn:◆そのあとで わたすものがあるから↓
;jpn: また かならず ここにこい。@WI(20)↓
;jpn: か@WI(10)な@WI(10)ら@WI(10)ず@WI(10)だぜ!
@KEYNP()
』

_TWSN_TONCHIKI_PAULA_NESS_DEAD;
◆@DSP_STS(STS_PC_NAME_PAULA)!@KEY()↓
◆I thought you were with your little hero, the kid in the red cap.@KEY()↓
◆You seem cold.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)ちゃん!@KEY()↓
;jpn:◆あかい ぼうしの↓
;jpn: いのちの おんじんと↓
;jpn: いっしょじゃ なかったのかい。@KEY()↓
;jpn:◆あんまり↓
;jpn: つめたいじゃないか。
@KEYNP()
』

_TWSN_TONCHIKI_PAULA_PAULA_DEAD;
◆I heard that you’ve been pretty proud of yourself since you saved @DSP_NAME(PC_PAULA)’s life.@KEY()↓
◆Think about it,@WI(15) you didn’t actually save her.@KEY()↓
◆Come back when you’ve accomplished something.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)を↓
;jpn: たすけたとかいって↓
;jpn: イキがってるらしいけど@KEY()↓
;jpn:◆そのようすじゃ↓
;jpn: たすけたことに↓
;jpn: ならねぇぜ。@KEY()↓
;jpn:◆ちゃんとして↓
;jpn: また こい。
@KEYNP()
』

_TWSN_TONCHIKI_OK;
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_TWSN_TONCHIKI_OK_NESS_DEAD)
◆I was going to ask you to be my partner,@KEY()↓
◆but I know you’ll refuse.@WI(20)  It’s written all over your face.@KEY()↓
◆If you accepted,@WI(15) I was going to give you some money.@KEY()↓
◆Actually, I can’t keep the money now anyway.@WI(20)  Let me give you this Briefcase.@KEY()↓
◆Inside is 10,000 dollars.@KEY()↓
◆Use the money any way you like.@WI(20)  You cannot refuse my generosity.@WI(20)  Just accept it.@KEY()↓
◆Now I plan on looking for the evil Mani Mani Statue@KEY()↓
◆that Lier X. Agerate unearthed in Onett.@KEY()↓
◆I’ll see you at another time, in another space.
;jpn:◆おまえを なかまにしたいものだが@WI(20)↓
;jpn: ことわるって↓
;jpn: かおにかいてあるな。@KEY()↓
;jpn:◆こぶんになったら↓
;jpn: わたそうとおもった↓
;jpn: かねだが‥‥@KEY()↓
;jpn:◆ひっこめるわけにも↓
;jpn: いかねぇ。↓
;jpn: このトランクは おまえにやる。@KEY()↓
;jpn:◆なかに 1まんドルの↓
;jpn: さつたばが はいっている。@KEY()↓
;jpn:◆いいことにでも わるいことにでも↓
;jpn: おもいっきり つかってくれ。@KEY()↓
;jpn:◆かえそうとしても ムリだ。↓
;jpn: あきらめて もっていきな!@KEY()↓
;jpn:◆おれは オネットで↓
;jpn: ライヤー・ホーランドとかって↓
;jpn: こあくとうが ほりだした@KEY()↓
;jpn:◆「マニマニのあくま」とやらを↓
;jpn: いただきに でかけるつもりだ。@KEY()↓
;jpn:◆えんがあったら またあおう。
@KEY()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_TONCHIKI_OK_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_SATSUTABA)
@GOSUB(MSG_SUB_GETGOODS_S)
@SETF(FLG_TWSN_ITEM_TONCHIKI)
@KEYNP()
』

_TWSN_TONCHIKI_OK_ITEMFULL;
@WI(60)↓
@SE(SE_se05_undo)
◆Your backpack is filled with junk.@WI(20)  Get rid of something!@KEY()↓
◆I’ll put the money in a safe place until you get back.
;jpn:◆あんまり だいじじゃないもので↓
;jpn: おまえのリュックは↓
;jpn: まんたんだな。@KEY()↓
;jpn:◆ひとつ すてるか うってきな!@KEY()↓
;jpn:◆それまで このかねは↓
;jpn: だいじに もっててやるから。
@KEYNP()
』

_TWSN_TONCHIKI_OK_NESS_DEAD;
◆I need to talk to @DSP_NAME(PC_NESS).@KEY()↓
◆Even if you’re his friend,@WI(15) I won’t talk to you.
;jpn:◆おれは @DSP_STS(STS_PC_NAME_NES)と↓
;jpn: はなしが してぇんだ。@KEY()↓
;jpn:◆いくら なかまだといっても↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)ちゃん↓
;jpn: あんたにゃ はなしはねぇ!
@KEYNP()
』

_TWSN_TONCHIKI_LATER;@MiuraAdapted
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_TWSN_TONCHIKI_OK_NESS_DEAD)
◆Please use the 10,000 dollars any way you wish.@KEY()↓
◆You cannot refuse my generosity,@WI(15) just accept it.
;jpn:◆1まんドルの さつたばは↓
;jpn: いちばん おまえにふさわしい↓
;jpn: つかいかたを すればいい。@KEY()↓
;jpn:◆かえそうとしても ムリだ。↓
;jpn: あきらめて もっていきな!
@KEYNP()
』

;----------------------------------------
;@Habitat:ツーソン/マッハピザ/マッハピザ
;@Person:店員
;@Figure:ウェートレスA
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_MACH
MSG_TWSN_MACH;
@CHKFGOTO(FLG_WIN_GIEGU,_TWSN_MACH_END)
@CHKFGOTO(FLG_SYS_PHONE_PIZZA,_TWSN_MACH_LATER)
◆Welcome to Mach Pizza!@KEY()↓
◆We don’t sell pizza here.@WI(20)  We only deliver.@KEY()↓
◆Let me give you our number so you can place an order sometime.@KEY()↓
◆The best pizza is Mach Pizza.@WI(20)  The number is...*psst psst psst*.@KEY()↓
◆You got that?
;DAN:Hiso,hiso is sound of whispering.
;jpn:◆マッハピザでーす。@KEY()↓
;jpn:◆うちは デリバリーせんもんで↓
;jpn: ここでは ピザは↓
;jpn: うってないんでーす。@KEY()↓
;jpn:◆でんわばんごうを おしえますから↓
;jpn: でんわでオーダーしてください。@KEY()↓
;jpn:◆おいしいピザなら マッハピザ。@WI(20)↓
;jpn: でんわは‥‥ヒソヒソヒソ。↓
;jpn: おぼえましたね。
@KEYNP()
@SE(SE_se74_my_get)
@SETF(FLG_SYS_PHONE_PIZZA)
』
_TWSN_MACH_LATER;
@CHKFGOTO(FLG_TEMP_9,_TWSN_MACH_TMP)
◆*Munch*@WI(30)munch*@WI(30)gulp*@KEY()↓
◆Uh...no,@WI(15) I didn’t take a piece of pizza.@WI(20)  I would never think of doing that!@KEY()↓
◆It was delicious, though.@WI(20)  Enjoy!
;jpn:◆ムグムグ@WI(30) ゴックン@KEY()↓
;jpn:◆‥‥@WI(30)わたし いま↓
;jpn: ピザのつまみぐいなんて↓
;jpn: ぜんぜん してませんでした。@KEY()↓
;jpn:◆‥‥でも@WI(30) おいしかったです。↓
;jpn: おきゃくさまも↓
;jpn: ぜひ おためしくださいね。
@KEY()↓
_TWSN_MACH_TMP;
◆As you may know,@WI(15) you need to order by phone, okay?
;jpn:◆ごぞんじかとは おもいますが↓
;jpn: ごちゅうもんは おでんわで ね。
@KEYNP()
@SETF(FLG_TEMP_9)
』
_TWSN_MACH_END;
◆I wonder if we’re going out of business?@KEY()↓
◆I thought business was pretty good.@KEY()↓
◆Oh well,@WI(15) I don’t think I want to deliver pizza.@WI(20)  I’d just get too tired...
;jpn:◆このおみせ もう↓
;jpn: つぶれちゃうのかしら‥‥@KEY()↓
;jpn:◆けっこう↓
;jpn: はんじょうしてたのになぁ。@KEY()↓
;jpn:◆‥‥でも わたし↓
;jpn: はいたつは したくない。@WI(20)↓
;jpn: つかれそうだから。
@KEYNP()
』
;----------------------------------------
;@Habitat:ツーソン/ホテル/受付
;@Person:電話
;@Figure:電話
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

;@Habitat:ツーソン/ホテル/受付
;@Person:フロントマン
;@Figure:おじさんB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOTELMAN
MSG_TWSN_HOTELMAN;@MaltaAppended
@GOSUB(MSG_GLOBAL_HOTEL)
』


;@Habitat:ツーソン/ホテル/受付
;@Person:ボーイ
;@Figure:ホテルボーイ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOTELPORTER
MSG_TWSN_HOTELPORTER;
;ホテル受付ボーイ
◆You must be quite a rich boy to stay at such a nice,@WI(15) first class hotel like this one.
;jpn:◆おきゃくさま おわかいのに↓
;jpn: こんなこうきゅうホテルに↓
;jpn: おとまりなんて‥‥すごいですね。
@KEYNP()
』


;■ツーソンホテルの右の部屋■■■■■■■■■■■■■■■■■■■■■■■■
;added 0717
MSG_TWSN_HOTEL_KINOKO
@CHKFGOTO(FLG_TEMP_0,_TWSN_HOTEL_KINOKO_YES_2)	;2度めに聞いた場合
◆Do I have a mushroom on my head?↓
  <Yes>  <No>
;jpn:◆ぼくのあたまに↓
;jpn: キノコ ついてる?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_HOTEL_KINOKO_YES,_TWSN_HOTEL_KINOKO_NO)

_TWSN_HOTEL_KINOKO_YES
;(はい)
←
@SETF(FLG_TEMP_0)		;以下のセリフ聞いたらFLG_TEMP_0=TRUE
◆That’s what I thought...@KEY()↓
◆Recently,@WI(15) I couldn’t walk quite right.@WI(20)  It was because of this mushroom.@KEY()↓
◆It’s actually kind of fun, so I’ll leave it there.
;jpn:◆やっぱり‥‥。@KEY()↓
;jpn:◆さいきん どうも↓
;jpn: あるきかたが フラフラすると↓
;jpn: おもったけど@KEY()↓
;jpn:◆それはこいつの↓
;jpn: せいだったんだ。@KEY()↓
;jpn:◆おもしろいから↓
;jpn: そのままに しておこっと。
@KEYNP()
』

_TWSN_HOTEL_KINOKO_NO
←
◆You’re one of those people that says ”no” right off the bat to any question, right?
;jpn:◆とりあえず 「いいえ」って↓
;jpn: こたえてみるタイプなんだね↓
;jpn: きみって。
@KEYNP()
』

_TWSN_HOTEL_KINOKO_YES_2
;(はい用のセリフを聞いたら、その後は以下のセリフ)
◆Don’t I look very stylish with the mushroom?
;jpn:◆ぼくのキノコ↓
;jpn: にあうだろ?
@KEYNP()
』



;@Habitat:ツーソン/ホテル/CDルーム
;@Person:キャッシュディスペンサ
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;----------------------------------------
;@Habitat:ツーソン/病院/受付
;@Person:受付嬢
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOSPITAL_USHER
MSG_TWSN_HOSPITAL_USHER;@MaltaAppended
@GOSUB(MSG_NURSE_TWSN)
』


;@Habitat:ツーソン/病院/診察室
;@Person:医者
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOSPITAL_DOCTOR
MSG_TWSN_HOSPITAL_DOCTOR;@MaltaAppended
@GOSUB(MSG_DOCTOR_TWSN)
』


;@Habitat:ツーソン/病院/診察室
;@Person:付き添い
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOSP_GIRL
MSG_TWSN_HOSP_GIRL;
;病院診察室診察付き添い
◆My shot didn’t hurt.@KEY()↓
◆I’m sure everyone is talking about it,@WI(20) but don’t worry about me.
;jpn:◆あたしの ちゅうしゃは↓
;jpn: いたくないって ひょうばんよ。@WI(20)↓
;jpn: あんしんしててね。
@KEYNP()
』


;----------------------------------------
;@Habitat:ツーソン/バスステーション/バスステーション
;@Person:待ち人
;@Figure:サラリーマンC
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_BUS_B
MSG_TWSN_BUS_B;
@CHKFGOTO(FLG_WIN_GEPPU,_TWSN_BUS_B_LATER)
◆I’m thinking about catching a bus to Threed.@WI(20)  I heard there are ghosts along the way.@KEY()↓
◆I wonder if the bus will have to turn around and come back.
;jpn:◆バスで スリークのまちに↓
;jpn: いこうとおもうんだけど@KEY()↓
;jpn:◆とちゅうで↓
;jpn: オバケがでるって はなしでさ@KEY()↓
;jpn:◆バスがひきもどされちゃうって↓
;jpn: ほんとかなぁ。
@KEYNP()
』

_TWSN_BUS_B_LATER;
◆To get to Threed,@WI(15) the bus is the most convenient.
;jpn:◆スリークに いくのは↓
;jpn: やっぱり バスがべんりだね。
@KEYNP()
』


;@Habitat:ツーソン/バスステーション/バスステーション
;@Person:待ち人
;@Figure:ゴロツキ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_BUS_BU
MSG_TWSN_BUS_BU;
;通行人BU(バス停)
@CHKFGOTO(FLG_WIN_GEPPU,_TWSN_BUS_BU_LATER)
◆To take the bus, or not to take the bus...hmmm.@KEY()↓
◆I get scared pretty easily...
;jpn:◆バスにのろうかなぁ↓
;jpn: やめようかなぁ@WI(20)↓
;jpn: おれ こわがりだからなぁ。
@KEYNP()
』

_TWSN_BUS_BU_LATER;
◆To take the bus, or not to take the bus...hmm.@KEY()↓
◆I get sick pretty easily...
;jpn:◆バスに のろうかなぁ↓
;jpn: やめようかなぁ@WI(20)↓
;jpn: おれ バスにようからなぁ‥。
@KEYNP()
』


;@Habitat:ツーソン/バスステーション/バスステーション
;@Person:待ち人
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:◆じっと待つ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_BUS_C
MSG_TWSN_BUS_C;
;バスステーション待ち人C
◆I was in the last war,@WI(20) so I’m not scared of ghosts.@KEY()↓
◆Actually,@WI(15) I’m more scared of my old lady, ha!
;jpn:◆わしは まえのせんそうのとき↓
;jpn: いちど いのちをすてたおとこだ。@WI(20)↓
;jpn: オバケなんか こわくない。@KEY()↓
;jpn:◆うちのバーさんのほうが↓
;jpn: ずっと こわい。
@KEYNP()
』


;@Habitat:ツーソン/バスステーション/バスステーション
;@Person:バス案内係
;@Figure:おじさんA
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_BUS_INFO
MSG_TWSN_BUS_INFO;
;バスステーション案内係
◆This town’s bus system is a little strange.@KEY()↓
◆Be sure to check the bus stop signs.@WI(20)  I wonder who came up with this system?
;jpn:◆ここのバスは ちょっとかわった↓
;jpn: システムでな‥‥@KEY()↓
;jpn:◆バスストップのマークを↓
;jpn: チェックするんだ。↓
;jpn: ‥‥だれが かんがえたんだか。
@KEYNP()
』


;@Habitat:ツーソン/バスステーション/バスステーション
;@Person:バス運転手
;@Figure:おじさんA
;@AppearanceKey:0
;@ActionScript:◆じっと待つ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_BUS_D
MSG_TWSN_BUS_D;
;バスステーションバス運転手
◆That’s right,@WI(15) I’m a bus driver.@WI(20)  For now,@WI(15) I’m resting.@KEY()↓
◆Life is long...take it easy,@WI(15)
;jpn:◆たしかに わたしは↓
;jpn: バスのうんてんしゅですが↓
;jpn: いまは やすんでおるのです。@KEY()↓
;jpn:◆じんせいは ながい。@WI(20)↓
;jpn: おちつきなさい↓
@GET_ORDER_PLAYER(1)
@ONGOSUB(_BUS_NESS,_BUS_PAULA,_BUS_JEFF,_BUS_POO)
@KEY()↓
;街の地図情報
@Q_HAVE(PC_ALL,GDS_TOOL_TOWN_MAP)
@FALSE_GOTO(_TWSN_BUS_D_NOTHAVE)
;持っている場合
◆Why don’t you check out your town map and learn about this area.
;jpn:◆「まちのちず」でもながめて↓
;jpn: すこし このへんのことを↓
;jpn: べんきょうしていたら どうかね。
@KEYNP()
』
_TWSN_BUS_D_NOTHAVE;持っていない場合
◆You don’t have a town map?@WI(15)  You didn’t borrow one from the Onett library?
;jpn:◆‥‥「まちのちず」も↓
;jpn: もっていないのか?@KEY()↓
;jpn:◆オネットのとしょかんで↓
;jpn: かりてこなかったのかい?
@KEYNP()
』

_BUS_NESS;
 chubs.
;jpn:	まるがおの しょうねんよ。
@!

_BUS_PAULA;
 girlie girl.
;jpn:	リボンのしょうじょよ。
@!

_BUS_JEFF;
 specs.
;jpn: メガネくんよ。
@!

_BUS_POO;
 pajama boy.
;jpn: あたま ちょんちょろりんの
;jpn:◆わかいしゅう。
@KEY()↓
@!

;----------------------------------------
;@Habitat:ツーソン/ビーナス母の家/母の部屋
;@Person:ビーナス母
;@Figure:ビーナスの母
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_VENUSMOM
MSG_TWSN_VENUSMOM;
;ビーナスの母
@CHKFGOTO(FLG_ITEM_BANANA,_TWSN_VENUSMOM_LATER)
◆My daughter left for the big city to become a superstar.@KEY()↓
◆She’s using a stage name−−@WI(20)Vein...oh, vein something...she’s working hard.
;jpn:◆うちのむすめは↓
;jpn: スーパースターになるって↓
;jpn: だいとかいに いってしまった。@KEY()↓
;jpn:◆なんとかナスって↓
;jpn: げいめいで がんばってるらしい。@KEY()↓
;jpn:◆‥‥ナス!@WI(20)じゃ‥‥あんまり↓
;jpn: うけないと おもうんだけどねぇ。
@KEYNP()
』

_TWSN_VENUSMOM_LATER;
;ビーナスと話した後
◆I got a letter from my daughter.@WI(20)  She wants me to see her next show.@KEY()↓
◆A book of photographs of her is coming out soon.@KEY()↓
◆I really hope she kept her clothes on...@WI(20)  Times have sure changed...
;jpn:◆むすめから てがみがきたよ。@WI(20)↓
;jpn: こんどステージを↓
;jpn: みにきてくれってさ。@KEY()↓
;jpn:◆しゃしんしゅうも だすって↓
;jpn: はなしだけど‥‥ヌードの。@KEY()↓
;jpn:◆じだいは かわったもんだよ。
@KEYNP()
』

;----------------------------------------
;@Habitat:ツーソン/住宅A/2階
;@Person:住人
;@Figure:キャップ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOUSE_A
MSG_TWSN_HOUSE_A;
;住宅A2階住人
@CHKFGOTO(FLG_WIN_GIEGU,_TWSN_HOUSE_A_END)
@CHKFGOTO(FLG_WIN_CARPAINTER,_TWSN_HOUSE_A_AFTER)
◆Dad and mom have left for Happy−Happy Village.@KEY()↓
◆They wanna meet with the founder of the religion in the village.
;jpn:◆パパとママは↓
;jpn: ハッピーハッピーむらの↓
;jpn: きょうそさまに あうって@KEY()↓
;jpn:◆でかけてるんだ。
@KEYNP()
』
_TWSN_HOUSE_A_AFTER;#
◆Dad and mom said they won’t go to Happy−Happy Village.@KEY()↓
◆I’m not sure why, but now I’m happy.
;jpn:◆パパもママも↓
;jpn: もう ハッピーハッピーむらには↓
;jpn: いかないって!@KEY()↓
;jpn:◆なんだか しらないけど↓
;jpn: よかった!
@KEYNP()
』
MSG_TWSN_HOUSE_A_PAPA;パパ
◆You woke me from that nightmare.
;jpn:◆きみたちの おかげで↓
;jpn: めがさめたよ。
@KEYNP()
』
MSG_TWSN_HOUSE_A_MAMA;ママ
◆I’m sorry that I made you worry...
;jpn:◆こどもにまで↓
;jpn: しんぱいかけて‥‥@KEY()↓
;jpn:◆はんせいしてるわ。
@KEYNP()
』

_TWSN_HOUSE_A_END;
◆Now I get it.@WI(20)  You’re not from this town.@KEY()↓
◆So, where do you come from?@WI(15)  Can you play with me again someday?
;jpn:◆おにいちゃん↓
;jpn: このまちのひとじゃ↓
;jpn: なかったんだね。@KEY()↓
;jpn:◆どこに すんでるの?@WI(20)↓
;jpn: また いつか あそべるかなぁ。
@KEYNP()
』


;@Habitat:ツーソン/住宅B/2階
;@Person:住人
;@Figure:少女D
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOUSE_B
MSG_TWSN_HOUSE_B;#
;住宅B2階住人
@CHKFGOTO(FLG_ITEM_TACO_ERASER,_TWSN_HOUSE_B_LATER)
◆Did you know that two young inventors live in this town?@KEY()↓
◆I want to invent something, too.
;jpn:◆はつめいかの おにいちゃんが↓
;jpn: このまちには↓
;jpn: ふたりも すんでるのよ!@KEY()↓
;jpn:◆わたしも なにか↓
;jpn: はつめいしたいな。
@KEYNP()
』
_TWSN_HOUSE_B_LATER;
◆The other day,@WI(15) did you speak to a boy who invents stuff?
;jpn:◆あなた こないだ↓
;jpn: はつめいかの おにいちゃんと↓
;jpn: はなしてたでしょ?
@KEYNP()
』


;@Habitat:ツーソン/住宅E/住宅E
;@Person:飼い猫
;@Figure:ヒントキャット
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_HOUSE_E_CAT
MSG_TWSN_HOUSE_E_CAT;
;住宅Eの猫
◆Meow.
;jpn:◆ニャア
@KEYNP()
』


;----------------------------------------
;@Habitat:ツーソン/デパート/1階.返品コーナー
;@Person:CD
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆正面向いて固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;@Habitat:ツーソン/デパート/1階.返品コーナー
;@Person:公衆電話
;@Figure:電話ボックス
;@AppearanceKey:0
;@ActionScript:◆正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

;@Habitat:ツーソン/デパート/1階.返品コーナー
;@Person:返品係
;@Figure:女店員A
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPART_RETURNGOODS
MSG_TWSN_DEPART_RETURNGOODS;@MaltaAppended
@GOSUB(MSG_DP_HENPIN)
』


;@Habitat:ツーソン/デパート/1階.返品コーナー
;@Person:カオスチケット係
;@Figure:OLA
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPART_TICKETPIA
MSG_TWSN_DEPART_TICKETPIA;
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,_TWSN_DEPART_TICKETPIA_LATER)
◆Do you want to buy a ticket for the Runaway Five show?↓
  <Yes>  <No>
;jpn:◆いまだいひょうばんの↓
;jpn: トンズラブラザーズの↓
;jpn: チケットをおもとめですか?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_DEPART_TICKETPIA_YES,_TWSN_DEPART_TICKETPIA_NO)

_TWSN_DEPART_TICKETPIA_NO;
◆Oh, I mistook you for a customer.
;jpn:◆なーんだ。↓
;jpn: おきゃくさまかと おもったわ。
@KEYNP()
』

_TWSN_DEPART_TICKETPIA_YES;
◆The main floor and balcony seats are sold out.@KEY()↓
◆We only have box seats, which cost 20 dollars.@WI(20)  Would that be okay?@KEY()↓
◆Oh, wait...the box seats sold out a long time ago.  Oops.@WI(20)  My mistake.@KEY()↓
◆The box seats are the most popular.
;jpn:◆Aせき Bせきは うりきれで↓
;jpn: Sせきは 12ドルです。@WI(15)↓
;jpn: よろしいですか?@KEY()↓
;jpn:◆あ Sせきも もう↓
;jpn: とっくに うりきれだったわ。↓
;jpn: ごめんなさいね。@KEY()↓
;jpn:◆なにしろ だいにんきだから‥‥。
@KEYNP()
』

_TWSN_DEPART_TICKETPIA_LATER;
◆Sorry.@WI(15)  The Chaos Theater is being remodeled.@WI(20)  There is no concert.
;jpn:◆もうしわけございません。@WI(15)↓
;jpn: ただいま カオスげきじょうは↓
;jpn: かいそうこうじちゅうです。@KEY()↓
;jpn:◆コンサートは ございません。
@KEYNP()
』


;@Habitat:ツーソン/デパート/1階.返品コーナー
;@Person:客A
;@Figure:青年
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_A
MSG_TWSN_DEPT_A;
@CHKFGOTO(FLG_TEMP_1,_TWSN_DEPT_A_IIYANE)
@CHKFGOTO(FLG_TWSN_DEPT_A,_TWSN_DEPT_A_LATER)
@GOSUB(_TWSN_DEPT_A_IIYANE)
@SETF(FLG_TWSN_DEPT_A)
@SETF(FLG_TEMP_1)
』

_TWSN_DEPT_A_IIYANE;
◆This department store isn’t crowded.@WI(20)  I like that.
;jpn:◆このデパートは↓
;jpn: すいてて いいやね。
@KEYNP()
』

_TWSN_DEPT_A_LATER;
◆Didn’t you talk to me before?@WI(20)  I believe I said,@KEY()↓
◆”This department store isn’t crowded.@WI(20)  I like that”...@KEY()↓
◆or something to that effect.
;jpn:◆きみ まえにも ぼくに↓
;jpn: はなしかけなかったっけ?@WI(20)↓
;jpn: そのとき ぼくは たしか‥‥@KEY()↓
;jpn:◆このデパートは↓
;jpn: すいてて いいやね。@KEY()↓
;jpn:◆って いったんだ。
@KEYNP()
』


;@Habitat:ツーソン/デパート/2階.食品売り場
;@Person:食料店員A
;@Figure:ウェートレスB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPART_GROCERY_A
MSG_TWSN_DEPART_GROCERY_A;@MaltaAppended
@GOSUB(MSG_SHOP_TWSN_HAMBURGER)
』


;@Habitat:ツーソン/デパート/2階.食品売り場
;@Person:食料店員B
;@Figure:ウェートレスB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPART_GROCERY_B
MSG_TWSN_DEPART_GROCERY_B;@MaltaAppended
@GOSUB(MSG_SHOP_TWSN_BAKERY)
』


;@Habitat:ツーソン/デパート/2階.食品売り場
;@Person:客B
;@Figure:おばあさん
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_B
MSG_TWSN_DEPT_B;
;デパート2階食品売り場客B
@CHKFGOTO(FLG_ITEM_GREATORANGE,_TWSN_DEPT_B_LATER)
◆I think that my grandchild is older than you.@WI(20)  He’s a famous inventor.@KEY()↓
◆He lives here, and people call him Orange Kid.@KEY()↓
◆He seems to be popular with the girls,@WI(15) because he’s...groovy?
;jpn:◆わたしのまごは↓
;jpn: あんたより ちょっと↓
;jpn: としうえだとおもんだけど@KEY()↓
;jpn:◆このまちじゃ ひょうばんの↓
;jpn: はつめいしょうねんなのよ。@KEY()↓
;jpn:◆オレンジキッドって↓
;jpn: よばれているの。@KEY()↓
;jpn:◆おんなのコなんかにも↓
;jpn: にんきが あるらしいの。@KEY()↓
;jpn:◆‥‥かっこいいから。
@KEYNP()
』
_TWSN_DEPT_B_LATER;
◆We’ve bumped into each other before.@WI(20)  You seem to love department stores.@KEY()↓
◆I do too.
;jpn:◆よくあうわねぇ。↓
;jpn: デパートが すきなのね。@KEY()↓
;jpn:◆わたしもよ。
@KEYNP()
』


;@Habitat:ツーソン/デパート/2階.食品売り場
;@Person:客C
;@Figure:アーティスト
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_C
MSG_TWSN_DEPT_C;
;デパート2階食品売り場客C
@CHKFGOTO(FLG_TLPT_SUMS,_TWSN_DEPT_C_LATER)
◆I heard a meteorite crashed onto a hilltop near Onett.@KEY()↓
◆That must have been exciting!
;jpn:◆オネットのいなかに↓
;jpn: いんせきがおちて↓
;jpn: タイヘンだったらしいねぇ。
@KEYNP()
』
_TWSN_DEPT_C_LATER;
◆I saw you a long time ago...@KEY()↓
◆maybe about the time that the meteorite hit Onett...
;jpn:◆むかーし おまえに↓
;jpn: あったことない?@KEY()↓
;jpn:◆たしか‥‥オネットに↓
;jpn: いんせきが↓
;jpn: おちたとかいうころさ。
@KEYNP()
』


;@Habitat:ツーソン/デパート/3階.ドラッグストア
;@Person:店員
;@Figure:女店員A
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_DRUG1
MSG_TWSN_DEPT_DRUG1;@MaltaAppended
@GOSUB(MSG_SHOP_TWSN_DRUG1)
』

;@Habitat:ツーソン/デパート/3階.ドラッグストア
;@Person:店員
;@Figure:サラリーマンD
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_DRUG2
MSG_TWSN_DEPT_DRUG2;@MaltaAppended
@GOSUB(MSG_SHOP_TWSN_DRUG2)
』

;@Habitat:ツーソン/デパート/3階.ドラッグストア
;@Person:客D
;@Figure:少女C
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_D
MSG_TWSN_DEPT_D;
;デパート3階ドラッグストア&ゲームセンター客D
◆I wanna visit my boyfriend in Threed ’cept the bus won’t go there.@KEY()↓
◆I wonder why.
;jpn:◆スリークにすんでる こいびとに↓
;jpn: あいたいんだけど↓
;jpn: バスが いってくれないのよね。@KEY()↓
;jpn:◆どうしてなんだろう。
@KEYNP()
』


;@Habitat:ツーソン/デパート/3階.ドラッグストア
;@Person:客E
;@Figure:少年A
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_DEPT_E
MSG_TWSN_DEPT_E;
;デパート3階ドラッグストア&ゲームセンター客E
@CHKFGOTO(FLG_WIN_GIEGU,_TWSN_DEPT_E_END)
@CHKFGOTO(FLG_TLPT_THRK,_TWSN_DEPT_E_LATER)
@CHKFGOTO(FLG_WIN_CARPAINTER,_TWSN_DEPT_E_AFTER)
◆Happy−Happy Village is getting to be more and more blue.@WI(20)  Do you get it?
;jpn:◆ハッピーハッピーむらは↓
;jpn: どんどん あおくなっていくね。@WI(20)↓
;jpn: いってるいみ わかるかなぁ。
@KEYNP()
』
_TWSN_DEPT_E_AFTER;
◆Someday, Happy−Happy Village will be truly happy.
;jpn:◆ハッピーハッピーむらも↓
;jpn: ほんとのハッピーに↓
;jpn: なることだろうよ。
@KEYNP()
』
_TWSN_DEPT_E_LATER;
◆You’re always wearing the same clothes...@KEY()↓
◆Do you wash them, or what?↓
<Yes>
<No>
;jpn:◆きみ いつも↓
;jpn: おんなじふく きてるけど↓
;jpn: ‥‥ちゃんと あらってるの?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_DEPT_E_YES,_TWSN_DEPT_E_NO)

_TWSN_DEPT_E_NO;いいえ
◆Well, they look clean enough,@WI(15) but who knows?
;jpn:◆ま きれいそうにみえるから↓
;jpn: いいのかも しれないね。
@KEYNP()
』
_TWSN_DEPT_E_YES;はい]
◆Hmm.@WI(30)  I wouldn’t have believed it...
;jpn:◆へーえ。@WI(30)↓
;jpn: そいつは いがいだった。
@KEYNP()
』
_TWSN_DEPT_E_END;&
◆Hey, it’s the boy who wears the same outfit all the time!@KEY()↓
◆You seem happy enough,@WI(15) but who knows?
;jpn:◆おお いつもおなじふくの↓
;jpn: しょうねん。@KEY()↓
;jpn:◆えらくきげんが いいじゃないか。
@KEYNP()
』
;-------------------------------------------------
