;
; $Id: e02twsn0.msg,v 1.17 1995/03/25 13:53:00 masa Exp $
;
;-----------------------------------------------------
;            at the bicycle shop
;@Habitat:ツーソン/サイクルショップ/サイクルショップ
;@Person:チャーリー
;@Figure:パンク青年
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_CYCLE_WELCOME
MSG_TWSN_CYCLE_WELCOME;
;「自転車屋のチャーリー」
;自転車を愛し、自転車を売ることを愛し、パンクロックを
;愛する地道な青年。しかし、彼は自転車に乗れないのだ。
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_TWSN_CYCLE_NESS_DEAD)
@CHKFGOTO(FLG_TWSN_ASHI,_TWSN_CYCLE_LATER)
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_TWSN_CYCLE_GREET);ポーラ帰したら自転車借りれる
@CHKFGOTO(FLG_POLA,_TWSN_CYCLE_LATER2)
@CHKFGOTO(FLG_POLA_GRFD,_TWSN_CYCLE_LATER2)
_TWSN_CYCLE_GREET;
◆This is the cycle shop@WI(5) ”Punk−Sure”!@KEY()↓
◆Bicycles are so much fun and are so convenient...@KEY()↓
◆It’s a lot faster than walking.@KEY()↓
◆You’ll be really popular with the biking crowd.@KEY()↓
◆Do you want a bicycle?↓
<Yes> <No>
;DAN:We say "pank" for "flat tire."
;jpn:◆サイクルショップ「パンク」だよ。@WI(15)↓
;jpn: じてんしゃは たのしくて↓
;jpn: べんりなアイテムだぜ。@KEY()↓
;jpn:◆あるくより すこしは はやいし↓
;jpn: じてんしゃマニアの ギャルに↓
;jpn: もてもてに なっちゃうぞ。@KEY()↓
;jpn:◆ほしいかい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_CYCLE_HOSHII,_TWSN_CYCLE_NO)

_TWSN_CYCLE_NO;
@Q_HAVE(PC_ALL,GDS_TOOL_BICYCLE)
@TRUE_GOTO(_TWSN_CYCLE_KAESU)
@CHKFGOTO(FLG_ITEM_CYCLE,_TWSN_CYCLE_NOTHAVE)
◆Oh...you don’t know how to ride a bike.@KEY()↓
◆Me neither.
;jpn:◆そうか。@WI(15)のれないのか‥‥。↓
;jpn: ‥‥‥@KEY()↓
;jpn:◆おれと おなじだな。
@KEYNP()
』

_TWSN_CYCLE_HOSHII;
@CHKFGOTO(FLG_ITEM_CYCLE,_TWSN_CYCLE_KARITERU)
◆Unfortunately, we don’t have any more bikes for sale.@WI(20)  We only have rentals.@KEY()↓
◆Do you want to rent one?↓
<Yes> <No>
;jpn:◆ざんねんだなぁ。レンタルしか↓
;jpn: のこってないんだ。@KEY()↓
;jpn:◆かりるかい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_CYCLE_YES,_TWSN_CYCLE_NO)
@GOTO(_TWSN_CYCLE_NO)

_TWSN_CYCLE_YES;
◆I really like your straight−forward style.@KEY()↓
◆I’ll tell you what,@WI(15) I’ll let you borrow a bike for free.
;jpn:◆「はい」という すなおなへんじが↓
;jpn: きにいったね。@WI(15)ただで かすよ。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_CYCLE_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_BICYCLE)
@GOSUB(MSG_SUB_GETGOODS)@KEY()↓
@SETF(FLG_ITEM_CYCLE)
◆You know that two people can’t ride on one bicycle,@KEY()↓
◆so of course three or four people on a bike would be impossible!@KEY()↓

◆Did you also know that you can’t ride a bike with anything following you?@KEY()↓
◆Teddy bears, for example...@KEY()↓
◆Carrying a bear and riding is impossible for you.
◆And don’t even think about riding a bike into a cave.
;jpn:◆ふたりのりは もちろん↓
;jpn: さんにんのりとか よにんのりは↓
;jpn: できないからな!@KEY()↓
;jpn:◆どうくつやなんかで のるのも↓
;jpn: やめてくれよ。
@KEYNP()
』

;◆ツーソンのまちのなかなら↓;二人のりは禁止だけど‥‥
; のりほうだいだ。@WI(20)↓
; ちゃんと かえしに こいよな。@KEYNP()
』

_TWSN_CYCLE_ITEMFULL;
←
@SE(SE_se05_undo)
◆You have too many items.@WI(20)  Why don’t you get rid of something and come back.@KEY()↓
◆I know you want it now,@WI(15) but my hands are tied...
;jpn:◆もちものが いっぱいだぜ。@WI(20)↓
;jpn: いちど にもつを せいりしてから↓
;jpn: また きなよ。@KEY()↓
;jpn:◆はやる きもちは わかるけどな。
@KEYNP()
』

_TWSN_CYCLE_KARITERU;
←
◆Didn’t you already borrow a bicycle?@WI(20)  We don’t have any more right now...
;jpn:◆もう 1だい かしてるだろ。@WI(20)↓
;jpn: うちには もうのこってないよ。
@KEYNP()
』

_TWSN_CYCLE_KAESU;
←
@GOODSOUT(PC_ALL,GDS_TOOL_BICYCLE);@TRUE_GOTO(_TWSN_CYCLE_NOTHAVE)
◆You’re here to return your bike?@KEY()↓
@SETF(FLG_TWSN_ASHI)
@CLRF(FLG_ITEM_CYCLE)
◆Look how low your seat is!@WI(20)  Geez,@WI(15) you must have short legs.@KEY()↓
◆That’s it!@WI(20)  I’ll call you stubby legs!
;jpn:◆かえしにきたのか。@WI(20)↓
;@SETF(FLG_TWSN_ASHI)
;@CLRF(FLG_ITEM_CYCLE)
;jpn: あらま ずいぶんサドルを↓
;jpn: ひくくして‥‥。@KEY()↓
;jpn:◆あし@WI(20)↓
;jpn: みじかいんだねぇ。@KEYNP()↓
;◆ヘーイ! あしみじかいやつ!
@KEYNP()
@SE(SE_se76_my_give)
』

_TWSN_CYCLE_NOTHAVE;
←
◆Yeah,@WI(10) yeah,@WI(5) sure, sure.@WI(20)  You’ve already borrowed a bicycle.
;jpn:◆そうだよな。↓
;jpn: 1だい かしてるもんな。
@KEYNP()
』

_TWSN_CYCLE_LATER;
◆Hey!@WI(15)  Stubby legs!
;jpn:◆ヘーイ! あしみじかいやつ!
@KEY()↓
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_TWSN_CYCLE_GREET);ポーラ帰したら自転車借りれる
@CHKFGOTO(FLG_POLA_GRFD,_TWSN_CYCLE_LATER2)
@CHKFGOTO(FLG_POLA,_TWSN_CYCLE_LATER2)
@GOTO(_TWSN_CYCLE_GREET)

_TWSN_CYCLE_LATER2;
@SET_LOOPREG(PC_NESS)
◆Do you wanna ride a bike?@KEY()↓
◆That’s not gonna work...two people on one bike is strictly forbidden.@KEY()
;jpn:◆じてんしゃに のりたいのかい?@KEY()↓
;jpn:◆ざんねんだな。ふたりのりは↓
;jpn: きんしだよ。
@Q_HAVE(PC_ALL,GDS_TOOL_BICYCLE)
@TRUE_GOTO(_TWSN_CYCLE_RETURN)
@KEYNP()
』

_TWSN_CYCLE_RETURN;
@KEY()↓
◆You’re here to return the bicycle?↓
<Yes> <No>
;jpn:◆かえしにきたのかい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_CYCLE_KAESU,_TWSN_CYCLE_RETURN_NO)

_TWSN_CYCLE_RETURN_NO;
◆Well,@WI(15) don’t forget to return it...@WI(20)  You’re gonna have to sooner or later.
;jpn:◆ちゃんと かえしに こいよ。@KEY()↓
;jpn:◆おまえのじんせいと↓
;jpn: プライドのすべてを かけてナ!
@KEYNP()
』

_TWSN_CYCLE_NESS_DEAD;
◆You know that two people can’t ride a bike,@KEY()↓
◆but did you know that you can’t ride a bike@KEY()↓
◆when you are carrying an unconscious friend’s stuff?
◆Carrying a lot of items and riding aroud is impossible for you.
;jpn:◆ふたりのりも↓
;jpn: きんしだけど@KEY()↓
;jpn:◆「ふたりのりふう」↓
;jpn: ‥‥っていうのも↓
;jpn: きんしなんだよ。@KEY()↓
;jpn:◆「ふたりのりふう」の↓
;jpn: 「ふう」は@KEY()↓
;jpn:◆「てうちふう」とか↓
;jpn: 「てづくりふう」の↓
;jpn: 「ふう」だ!
@KEYNP()
』

;----------------------------------------
;@Habitat:ツーソン/幼稚園/遊技室
;@Person:ポーラ母
;@Figure:ポーラ母
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_ISABELLA
MSG_TWSN_ISABELLA;
;やる時ゃやるタイプのおかぁさん。「ポーラを信じているので
;何も心配しない」というが、細かい心づかいもあるのです。
;《幼稚園児をいつもゾロゾロひきつれて登場する》
@CHKFGOTO(FLG_WIN_GIEGU,_TWSN_ISABELLA_END)
@CHKFGOTO(FLG_GLOBAL_POLA_KIDNAPPED,_TWSN_ISABELLA_MAIN);誘拐中
@CHKFGOTO(FLG_TWSN_ITEM_TONCHIKI,_TWSN_ISABELLA_LATER)
@CHKFGOTO(FLG_TWSN_ITEM_ISABELLA,_TWSN_ISABELLA_GOODLUCK)
@CHKFGOTO(FLG_POLA_GRFD,_TWSN_ISABELLA_OK)
◆Whistle, whistle anywhere@WI(10)↓
  It makes me smile@WI(10)↓
  all the while.@KEY()↓
◆I’m @DSP_NAME(PC_PAULA)’s mother.@WI(20)  I’m busy taking care of these kids.
;jpn:◆音くちぶえふけば おとがでる@WI(20)↓
;jpn: どーんなときでも ニッコニコ音@KEY()↓
;jpn:◆わたしは @DSP_STS(STS_PC_NAME_PAULA)のママですが@WI(20)↓
;jpn: ようちえんの こどもたちの↓
;jpn: せわが たいへんなのよ。
@KEY()↓
_TWSN_ISABELLA_MAIN;誘拐中
◆You shouldn’t worry about @DSP_NAME(PC_PAULA).@WI(20)  She has a guardian angel,@WI(15) it seems.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)のことなら↓
;jpn: なんのしんぱいも いらないわ。@WI(20)↓
;jpn: あのこには カミサマがついてる。
@KEYNP()
』

_TWSN_ISABELLA_OK;
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_ISABELLA_OK_DEAD)
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_ISABELLA_OK_NES_DEAD)
◆Yahoo!@WI(5)  I knew it!@WI(20)  You saved @DSP_NAME(PC_PAULA).
;jpn:◆ヤッホー! やっぱり↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)をたすけてくれたのね。
@KEY()↓
@GOSUB(_TWSN_ISABELLA_GOODLUCK)↓

_TWSN_ISABELLA_ITEM;
◆@DSP_NAME(PC_PAULA) if you must take a trip,@WI(15) be sure to bring this along.@KEY()↓
◆It’s my very own hand−made band−aid!@WI(20)  Ooo!@WI(15) that rhymes!
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)@WI(15) たびにでるなら↓
;jpn: これを もっておゆき。@WI(20)↓
;jpn: ハンドメイドのバンドエイドよ。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_ISABELLA_OK_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_HAND_AID)
@GOSUB(MSG_SUB_GETGOODS)@KEYNP()
@SETF(FLG_TWSN_ITEM_ISABELLA)
←
◆Did you meet dad?@KEY()↓
◆He was sorry that he suspected Mr. Everdred in Burglin Park.
;DAN:"Nusutto" means "Burglar's"
;jpn:◆パパには もうあった?@KEY()↓
;jpn:◆パパったら ヌスットひろばの↓
;jpn: トンチキさんを↓
;jpn: うたがっていたことを@KEY()↓
;jpn:◆こうかいして おちこんでいたわ。
@KEYNP()   
』
_TWSN_ISABELLA_OK_DEAD;
◆Is that you, @DSP_NAME(PC_PAULA)?@WI(20)  Oh,@WI(15) I thought she would be back,@WI(15) but not yet...@KEY()↓
◆Oh no, I’m not worried...I’ll be okay.
;jpn:◆ああ @DSP_STS(STS_PC_NAME_PAULA)↓
;jpn: やっぱり かえって‥‥@KEY()↓
;jpn:◆きたようにおもったけど↓
;jpn: まだみたいね。@KEY()↓
;jpn:◆いえ @DSP_STS(STS_PC_NAME_NES)さん↓
;jpn: わたし しんぱいなんか↓
;jpn: してませんわ。@KEY()↓
;jpn:◆へーっちゃら音
@KEYNP()
』

_TWSN_ISABELLA_GOODLUCK;
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_ISABELLA_GOODLUCK_DEAD)
◆I don’t really understand it,@KEY()↓
◆but I know that @DSP_NAME(PC_PAULA)’s miraculous power@KEY()↓
◆and your great courage will allow you to stand up to any challenge.
;jpn:◆わたしには よくわかんないけど↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)の ふしぎなちからと↓
;jpn: あなたのゆうきが あわされば@KEY()↓
;jpn:◆きっと どんなこんなんにも↓
;jpn: たちむかえると おもうの。@KEY()↓
;jpn:◆しんぱいもない わけじゃないけど@WI(20)↓
;jpn: よろこんで むすめを↓
;jpn: おくりだすわ。
@KEYNP()
』
_TWSN_ISABELLA_OK_NES_DEAD;ネス気絶
◆Yahoo!@WI(15)  I knew it!@WI(20)  You got back here with no problem.@KEY()↓
◆Isn’t @DSP_NAME(PC_NESS) with you?@KEY()↓
◆...@DSP_NAME(PC_PAULA),@WI(15) your mom is trusting his courage and your miraculous power.@KEY()↓
◆I won’t say I’m not worried.@KEY()↓
◆But I’ll let you go along...It’s for a good cause...
;jpn:◆ヤッホー@WI(15) やっぱり↓
;jpn: げんきで かえってきたわね。@KEY()↓
;jpn:◆あの @DSP_STS(STS_PC_NAME_NES)って おとこのコと↓
;jpn: いっしょじゃなかったのね‥‥。@KEY()↓
_TWSN_ISABELLA_GOODLUCK_DEAD;
;jpn:◆‥‥@DSP_STS(STS_PC_NAME_PAULA)‥‥。@KEY()↓
;jpn:◆ママは あのコのゆうきと↓
;jpn: あなたのふしぎなちからを↓
;jpn: しんじるわ。@KEY()↓
;jpn:◆まったく しんぱいもないって‥‥↓
;jpn: わけじゃないけど@KEY()↓
;jpn:◆あのコのちからに↓
;jpn: なってあげると いいわ。@KEY()↓
;jpn:◆きっと それは↓
;jpn: たいせつなことだと おもったの。
@CHKFGOTO(FLG_TWSN_ITEM_ISABELLA,_TWSN_ISABELLA_OK_DEADEND)
@KEY()↓
@GOTO(_TWSN_ISABELLA_ITEM)

_TWSN_ISABELLA_OK_DEADEND;
@KEYNP()
』

_TWSN_ISABELLA_LATER;
@CHKFGOTO(FLG_TWSN_ITEM_ISABELLA,_TWSN_ISABELLA_LATER1)
◆@DSP_NAME(PC_PAULA),@WI(15) if you must go,@WI(15) be sure to bring this along.@KEY()↓
◆It’s my very own hand−made band−aid!@WI(20)  I love the way that rhymes!
;jpn:◆たびにでるなら↓
;jpn: これを もっておゆき。@WI(20)↓
;jpn: ハンドメイドのバンドエイドよ。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_ISABELLA_OK_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_HAND_AID)
@GOSUB(MSG_SUB_GETGOODS)@KEYNP()
@SETF(FLG_TWSN_ITEM_ISABELLA)
』

_TWSN_ISABELLA_OK_ITEMFULL;イザベラ
←
◆What’s that?@WI(15)  You’re being a little impatient...@KEY()↓
◆You need to sell,@WI(15) use or drop something.@WI(20)  After that,@WI(15) I can give this to you.
;◆Huh?  You seem like you can’t wait.@KEY()↓
;◆Sell or use or drop your goods and come back.@KEY()↓
;◆I’ll give you,then.
;jpn:◆あら@WI(15) もちきれないみたいね。@WI(20)↓
;jpn: もちものを うるかつかうか↓
;jpn: すてるかしてきなさい。@KEY()↓
;jpn:◆あらためて あげるから。
@KEYNP()
』

_TWSN_ISABELLA_LATER1;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Well, here you are,@WI(15) @DSP_NAME(PC_NESS).@KEY()↓
◆I’ll make you some @DSP_STS(STS_PARTY_FAVORITE_FOODS),@WI(20) even though I’m not a very good cook.
;jpn:◆まぁまぁ ようこそ @DSP_NAME(0)!@WI(20)↓
;jpn: じゃ あんまりおいしくない↓
;jpn: @DSP_STS(STS_PARTY_FAVORITE_FOODS)をつくるわねッ。
@KEY()
;体力回復(暗転ワープなし、BGMあり、夜鍋なし、セリフ替えなし)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
』

_TWSN_ISABELLA_END;&最終戦闘後のママ
◆You’ve lost some weight since I saw you last, @DSP_NAME(PC_NESS).@KEY()↓
◆@DSP_NAME(PC_PAULA) must have had quite an adventure!@WI(20)  I’m glad you live so close to us.@KEY()↓
◆Why don’t you drop by more often?@WI(20)  I’m working at making better @DSP_STS(STS_PARTY_FAVORITE_FOODS).

;jpn:◆まえに あったときより↓
;jpn: @DSP_STS(STS_PC_NAME_NES)ちゃん↓
;jpn: ちょっと やせたかしら。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)にも↓
;jpn: いろいろ きっと いいけいけんに↓
;jpn: なったとおもうわ。@KEY()↓
;jpn:◆いえも となりまちなんだし↓
;jpn: これからも ちょくちょく↓
;jpn: あそびにきてね。@KEY()↓
;jpn:◆@DSP_STS(STS_PARTY_FAVORITE_FOODS)を↓
;jpn: じょうずに つくれるように↓
;jpn: しておくから。
@KEYNP()
』

;@Habitat:ツーソン/幼稚園/遊技室
;@Person:園児A
;@Figure:少年A
;@AppearanceKey:0
;@ActionScript:◆落ちつかない
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_POLESTAR_A
MSG_TWSN_POLESTAR_A;
;「幼稚園の子供」
@CHKFGOTO(FLG_POLA,_TWSN_POLESTAR_A_LATER)
@CHKFGOTO(FLG_POLA_GRFD,_TWSN_POLESTAR_A_LATER)
◆@DSP_NAME(PC_PAULA) isn’t here!@KEY()↓
◆She suddenly left,@WI(15) and I don’t know where she went.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)は いないよ。@WI(20)↓
;jpn: さっき あわてて↓
;jpn: どこかへ いったんだ。
@KEYNP()
』

_TWSN_POLESTAR_A_LATER;
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_POLESTAR_A_DEAD)
◆(He’s smiling).
;jpn:◆にこにこ。
@KEYNP()
』
_TWSN_POLESTAR_A_DEAD;
◆Oh, @DSP_NAME(PC_PAULA)!@WI(20)  Uh...sorry,@WI(15) I thought you were @DSP_NAME(PC_PAULA).
;jpn:◆あ @DSP_STS(STS_PC_NAME_PAULA)!↓
;jpn: おっと@WI(20) みまちがえた。
@KEYNP()
』

;@Habitat:ツーソン/幼稚園/遊技室
;@Person:園児B
;@Figure:リボン
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_POLESTAR_C
MSG_TWSN_POLESTAR_C;
;「幼稚園の子供C」
@GET_ORDER_PLAYER(1)
@EQ(PC_PAULA)@TRUE_GOTO(_TWSN_POLESTAR_B_PAULA)
@CHKFGOTO(FLG_POLA,_TWSN_POLESTAR_B_LATER)
@CHKFGOTO(FLG_POLA_GRFD,_TWSN_POLESTAR_B_LATER)
◆Well,@WI(15) I wanted to play with @DSP_NAME(PC_PAULA),@WI(15) but she’s gone some place...
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)と↓
;jpn: あそぼうとおもったのに↓
;jpn: どこかへ いっちゃってさ‥‥。
@KEYNP()
』

_TWSN_POLESTAR_B_LATER;
@CHKFGOTO(FLG_GLOBAL_POLA_KIDNAPPED,_TWSN_POLESTAR_B_DEAD);誘拐中
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_POLESTAR_B_DEAD)
◆Thank you for saving @DSP_NAME(PC_PAULA).@WI(20)  You are my hero.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)を たすけてくれて↓
;jpn: ありがとう。@WI(20)↓
;jpn: ‥‥にくいひと!
@KEYNP()
』
_TWSN_POLESTAR_B_DEAD;
◆Help @DSP_NAME(PC_PAULA)!@WI(20)  Hurry, hurry!
;jpn:◆はやく @DSP_STS(STS_PC_NAME_PAULA)を↓
;jpn: たすけてきてよー。
@KEYNP()
』
_TWSN_POLESTAR_B_PAULA;
◆@DSP_NAME(PC_PAULA),@WI(15) I was worried about you.@KEY()↓
◆I’m not going to ask the two of you where you were wandering...
;DAN:"U fufufu..." is laugh ...
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)おねえちゃん↓
;jpn: しんぱいしちゃったじゃないの。@KEY()↓
;jpn:◆どこにいってたかは↓
;jpn: きかないわ。@KEY()↓
;jpn:◆ウ・フ・フ‥‥。
@KEYNP()
』
 

;@Habitat:ツーソン/幼稚園/遊技室
;@Person:園児C
;@Figure:ヘルメット
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_POLESTAR_B
MSG_TWSN_POLESTAR_B;
;「幼稚園の子供B」
@GET_ORDER_PLAYER(1)
@EQ(PC_PAULA)@TRUE_GOTO(_TWSN_POLESTAR_C_PAULA)
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_POLESTAR_C_DEAD)
;DAN: He talks like an adult.
◆@DSP_NAME(PC_PAULA) is like a mother to me.@KEY()↓
◆You may not be able to comprehend my emotions.@KEY()↓
◆I might have a baby face,@WI(15) but I possess the mind of an adult.@KEY()↓
◆I beg your pardon.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)は おいらにとって↓
;jpn: おっかさんのような そんざいさ。@WI(20)↓
;jpn: おまえさんにゃあ わかるまいが。@KEY()↓
;jpn:◆おれ かおは おさないけど↓
;jpn: かんがえかたが ふけてるんだ。@WI(20)↓
;jpn: ゆるせ。
@KEYNP()
』
_TWSN_POLESTAR_C_DEAD;松(切り方変?)
◆@DSP_NAME(PC_PAULA)?@KEY()↓
◆You know,@WI(15) I thought I saw her@KEY()↓
◆for a second out of the corner of my eye...maybe I was just dreaming...
;jpn:◆おっと @DSP_STS(STS_PC_NAME_PAULA)ちゃん@WI(60)↓
;jpn: おいらのめには@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)ちゃんが↓
;jpn: ここにいなさるように↓
;jpn: おもえたが‥‥@KEY()↓
;jpn:◆まぼろしを みたのかなぁ。
@KEYNP()
』
_TWSN_POLESTAR_C_PAULA;
◆@DSP_NAME(PC_PAULA),@WI(15) you look nice and healthy.@WI(20)  What great timing having you show up now!
;jpn:◆おっと @DSP_STS(STS_PC_NAME_PAULA)ちゃん@WI(20)↓
;jpn: げんきで いなすったか。@KEY()↓
;jpn:◆あらわれるタイミングが↓
;jpn: なんとも イキだねぇ。
@KEYNP()
』

MSG_TWSN_POLESTAR_D;園児D(ポーラいない)
@GET_ORDER_PLAYER(1)
@EQ(PC_PAULA)@TRUE_GOTO(_TWSN_POLESTAR_D_PAULA)
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_POLESTAR_D_DEAD)
;DAN: She talks like a baby.
◆When I grow up,@WI(15) I wanna be ju@WI(5)u@WI(5)u@WI(5)u@WI(5)st like @DSP_NAME(PC_PAULA).
;jpn:◆わたち おとなになったら↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)おねえちゃんに↓
;jpn: なりたいの。
@KEYNP()
』
_TWSN_POLESTAR_D_PAULA;救出時
@CHKFGOTO(FLG_TLPT_THRK,_TWSN_POLESTAR_D_PAULA_LATER)
◆You skinned your knee,@WI(10) huh.
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)おねぇちゃん↓
;jpn: ひざこぞ すりむいてる。
@KEYNP()
』
_TWSN_POLESTAR_D_DEAD;死んでる。
◆What happened to @DSP_NAME(PC_PAULA)?
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)おねえちゃんは↓
;jpn: どうちちゃったの?
@KEYNP()
』
_TWSN_POLESTAR_D_PAULA_LATER;通常
◆When I get big,@WI(15) I’m gonna be grown−up @DSP_NAME(PC_PAULA).@KEY()↓
◆Then,@WI(20) later I’ll be old lady @DSP_NAME(PC_PAULA).
;jpn:◆わたち おとなになったら↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)おねえちゃんになって@WI(20)↓
;jpn: そのあと‥‥@KEY()↓
;jpn:◆もっと おとなになったら↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)おばあちゃんになるの。
@KEYNP()
』

;@Habitat:ツーソン/幼稚園/両親の部屋
;@Person:ポーラ父
;@Figure:ポーラ父
;@AppearanceKey:0
;@ActionScript:◆演出コンテ#2.3(改)FLG..UPSETであわてる
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_PAUL
MSG_TWSN_PAUL;
;ポーラの父「ポール・ジョーンズ」氏
;頭はカタイが気はやさしい。ゆうずうの効かないところが
;ちょっと困りものではあるが、若い時はならしたという
;暴力的なまでの正義感は、頼りがいがある。
@CHKFGOTO(FLG_WIN_GIEGU,_TWSN_PAUL_END)
@CHKFGOTO(FLG_TWSN_ITEM_TONCHIKI,MSG_TWSN_PAUL_LATER)
@CHKFGOTO(FLG_POLA,MSG_TWSN_PAUL_OK1)
@CHKFGOTO(FLG_POLA_GRFD,MSG_TWSN_PAUL_OK)
@CHKFGOTO(FLG_TWSN_PAUL_UPSET,_TWSN_PAUL_POPO)
@CHKFGOTO(FLG_TWSN_PAUL,_TWSN_PAUL_NO_1)
◆So,@WI(15) you wanna see @DSP_NAME(PC_PAULA)?@KEY()↓
◆Many come here to see her miraculous powers,@WI(15) but they’re just leeches.@KEY()↓
◆So...are you from a TV station, or what?↓
<Yes> <No>
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)に あいたいって?@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)のふしぎなちからを↓
;jpn: りようしようとして↓
;jpn: いろんなやつが たずねてくるが@KEY()↓
;jpn:◆みんな ろくなもんじゃない。@KEY()↓
;jpn:◆あなたも テレビきょくか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_PAUL_YES,_TWSN_PAUL_NO)

_TWSN_PAUL_NO;
◆To meet you or not to meet you can only be decided by @DSP_NAME(PC_PAULA).@KEY()↓
◆@DSP_NAME(PC_PAULA) has said that she would only meet with a boy named @DSP_NAME(PC_NESS).@KEY()↓
◆So you’re @DSP_NAME(PC_NESS)!@KEY()↓
◆You’re the one that was in @DSP_NAME(PC_PAULA)’s dream.@WI(20)  You will save the world!@KEY()↓
◆Let me go call @DSP_NAME(PC_PAULA).
;jpn:◆あいにきた にんげんに↓
;jpn: あうべきか あうべきでないかは↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)じしんが きめる。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)は @DSP_STS(STS_PC_NAME_NES)という↓
;jpn: しょうねんだけには あうと↓
;jpn: いっておったが‥‥@KEY()↓
;jpn:◆えっ きみが @DSP_STS(STS_PC_NAME_NES)!@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)のゆめに↓
;jpn: でてきたという↓
;jpn: せかいを すくう しょうねんか。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)をよんでこよう。
@KEY()
@GOSUB(MSG_EVT_28_PAUL)
◆She doesn’t seem to be here.@KEY()↓
◆I wonder where she went?@WI(20)  I’m sorry,@WI(20) could you come back later?
;jpn:◆いないようだ。@WI(20)↓
;jpn: どこへ でかけたんだろう?@KEY()↓
;jpn:◆わるいが でなおしてください。
@KEYNP()
@SETF(FLG_TWSN_PAUL)
@SETF(FLG_TWSN_POLA_TELEPATHY);ポーラのテレパシーセット
;@SETF(FLG_TEMP_1)
』

_TWSN_PAUL_YES;
◆Please leave.@KEY()↓
◆My daughter does’nt want to talk to media monkeys like you.
;jpn:◆かえってくれ。@WI(20)↓
;jpn: うちのむすめは↓
;jpn: サルぐんだんじゃない!
@KEYNP()
』

_TWSN_PAUL_NO_1;
◆Now where did she go?@KEY()↓
◆I’m sorry,@WI(15) could you come back after a while?
;jpn:◆どこへ でかけたんだろう?@WI(20)↓
;jpn: わるいが でなおしてください。
@KEYNP()
』

_TWSN_PAUL_POPO;
@SET_LOOPREG(1)
@GET_PLAYER_NAME(PC_PAULA)
@SET_REG(0)
◆@DSP_CHAR(0)@WI(5) @DSP_CHAR(0)@WI(5) @DSP_NAME(PC_PAULA)’s not home yet.@KEY()↓
◆Everdred in Burglin Park might know something.@KEY()↓
◆Oh, boy!@WI(20)  Now I’m really worried.
;jpn:◆@DSP_CHAR(0) @DSP_CHAR(0) @DSP_STS(STS_PC_NAME_PAULA)が↓
;jpn: まだ もどらないんだ。@KEY()↓
;jpn:◆ヌスットひろばの↓
;jpn: トンチキってボスが↓
;jpn: どうも あやしいらしいんだが‥‥@KEY()↓
;jpn:◆うー@WI(20) うー‥‥@WI(60)しんぱいだっ!
@KEYNP()
@SETF(FLG_TWSN_INFO_TONCHIKI)
』

MSG_TWSN_PAUL_LATER;
@CHKFGOTO(FLG_GLOBAL_POLA_KIDNAPPED,_TWSN_PAUL_LATER_PAULA_DEAD);誘拐中
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_PAUL_LATER_NES_DEAD)
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_PAUL_LATER_PAULA_DEAD)
◆You’re both fine...I’m so relieved!@KEY()↓
◆Why don’t you get some rest here?↓
<Yes> <No>
;jpn:◆おお @DSP_STS(STS_PC_NAME_NES)くん。@DSP_STS(STS_PC_NAME_PAULA)!@WI(20)↓
;jpn: げんきそうで なによりだ。@KEY()↓
;jpn:◆きょうは ここに とまりなさい。↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_PAUL_LATER_YES,_TWSN_PAUL_LATER_NO)

_TWSN_PAUL_LATER_NO;
◆Come on,@WI(15) why don’t you put your dogs up and re@WI(5)e@WI(5)e@WI(5)e@WI(5)lax.
;jpn:◆ゆっくり やすんだらいいのに。
@KEYNP()
』

_TWSN_PAUL_LATER_YES;
◆@DSP_NAME(PC_NESS), you’ll sleep on the couch in the den...
;jpn:◆べつべつの へやにな‥‥。
@KEY()
;体力回復(暗転ワープあり、BGMあり、夜鍋あり、セリフ替えなし)
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_PAULASTAR_BED)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
←

;◆さらば @DSP_STS(STS_PC_NAME_PAULA)!↓
; パパ@WI(20) ないてなんかいないぞ。@KEYNP()
』
_TWSN_PAUL_LATER_PAULA_DEAD;ポーラ死に
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_PAUL_LATER_BOTH_DEAD)
◆Hey!  Come on in!@KEY()↓
◆No, I don’t need to hear about what happened...@WI(20)  @DSP_NAME(PC_PAULA) will be okay.@KEY()↓
◆Why don’t you just rest for now.@KEY()↓
◆You know where the couch in the den is...
;jpn:◆やあやあ いらっしゃい。@KEY()↓
;jpn:◆いやいや じじょうは↓
;jpn: きくまい。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)は どうせ↓
;jpn: げんきにきまっとる。@KEY()↓
;jpn:◆ゆっくり やすんでいきなさい。
@KEY()
;体力回復(暗転ワープあり、BGMあり、夜鍋あり、セリフ替えなし)
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_PAULASTAR_BED)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
』
_TWSN_PAUL_LATER_NES_DEAD;ネス死に
@SET_LOOPREG(PC_PAULA)			;ポーラのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_PAUL_LATER_BOTH_DEAD)
◆Oh @DSP_NAME(PC_PAULA)!@KEY()↓
◆So even a tomboy like you thinks of her father occasionally!@KEY()↓
◆You should rest,@WI(15) seeing how this is your own home.@KEY()↓
◆How about we share a piece of pie like we used to?  Ha ha ha!
;jpn:◆おお @DSP_STS(STS_PC_NAME_PAULA)か!@KEY()↓
;jpn:◆おまえみたいな↓
;jpn: おてんばでも@KEY()↓
;jpn:◆たまには パパのことを↓
;jpn: おもいだしたりもするんだな。@KEY()↓
;jpn:◆なつかしの わがやで↓
;jpn: きょうは↓
;jpn: ゆっくりしていきなさい。@KEY()↓
;jpn:◆パパと おふろにはいるか?@WI(20)↓
;jpn: ワハハハハハ!
@KEY()
;体力回復(暗転ワープあり、BGMあり、夜鍋あり、セリフ替えなし)
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_PAULASTAR_BED)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
』
_TWSN_PAUL_LATER_BOTH_DEAD;
◆Hmm...I understand.@KEY()↓
◆So you’re a friend of @DSP_NAME(PC_PAULA)’s?@KEY()↓
◆Look me in the eye...@WI(20)Yes, you’re telling the truth.@KEY()↓
◆Would you like to get some shut eye?
;jpn:◆フムフム。@WI(20)↓
;jpn: なるほど。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)の↓
;jpn: ともだちなのか。@KEY()↓
;jpn:◆わたしのめを みなさい。@KEY()↓
;jpn:◆‥‥‥@WI(60)↓
;jpn: うそを ついてるわけでは↓
;jpn: なさそうだ。@KEY()↓
;jpn:◆あたたかい ベッドで↓
;jpn: やすんでいきなさい。
@KEY()
;体力回復(暗転ワープあり、BGMあり、夜鍋あり、セリフ替えなし)
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_PAULASTAR_BED)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
』
_TWSN_PAUL_END;&
◆You’re a very strong, young man.@WI(20)  My opinion of you has changed.@KEY()↓
◆Perhaps you should continue dating @DSP_NAME(PC_PAULA).@KEY()↓
◆Just treat her right...@KEY()↓
◆Come by and visit anytime.@KEY()↓
◆You can even sleep on the living room couch instead of the one in the den...
;jpn:◆@DSP_STS(STS_PC_NAME_NES)くん↓
;jpn: きみは ほんとうに↓
;jpn: しっかりした しょうねんだ。@KEY()↓
;jpn:◆あらためて みなおしたよ。@KEY()↓
;jpn:◆もし きみが のぞむなら↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)と これからも↓
;jpn: こうさいしてくれたまえ。@KEY()↓
;jpn:◆せいねんらしい↓
;jpn: せいせいどうどうとした↓
;jpn: つきあいを たのむよ。@KEY()↓
;jpn:◆たまには↓
;jpn: あそびにきてくれたまえ。@KEY()↓
;jpn:◆わたしの へやにも↓
;jpn: とまれるし‥‥。
@KEYNP()
』

;----------------------------------------
;@Habitat:ツーソン/有望青年Aの家/有望青年Aの家
;@Person:オレンジキッド
;@Figure:有望青年A
;@AppearanceKey:FLG_TWSN_CHAOSAPPLE_APPEAR/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_ORANGE
MSG_TWSN_ORANGE;
;将来有望な青年A(オレンジキッド)
;ツーソンの町で評判の神童のひとり。いろんな工夫や
;発明をしてNESを助けてくれそう。純真で利発そうな瞳は
;プレイヤーたちの信頼をえずにはいられないが、ろくでも
;ないやつに、すぐなりさがる。(オレンジは、黄信号の意と記憶しよう)
@CHKFGOTO(FLG_WIN_GIEGU,_TWSN_ORANGE_END_A)
@CHKFGOTO(FLG_TWSN_ORANGE_THANKS,_TWSN_ORANGE_THANKS_MAIN)
@CHKFGOTO(FLG_TWSN_INFO_TACO,_TWSN_ORANGE_2)
◆Greetings.@WI(20)  I’m Orange Kid, the inventor.@KEY()↓
◆Have you heard of me?@WI(20)  I’m a bit embarrassed about my reputation.@KEY()↓
◆I have a lot of inventions in development, but I’m running short of cash.@KEY()↓
◆I’m basically a happy−go−lucky person,@WI(15) so I’m not worried.@KEY()↓
◆You know,@WI(15) I’m working on this machine@KEY()↓
◆that would really help you in Peaceful Rest Valley.@KEY()↓
◆I hope it’s ready soon...what?@KEY()↓
◆You’re actually willing to help finance the project?↓
<Yes> <No>
;jpn:◆ようこそ。↓
;jpn: ぼくが はつめいかの↓
;jpn: オレンジキッドです。@KEY()↓
;jpn:◆ぼくの ひょうばんを↓
;jpn: きいたんですか‥‥いやぁ↓
;jpn: てれちゃうなぁ。@KEY()↓
;jpn:◆いま かいはつちゅうの はつめい↓
;jpn: いろいろあるんですが@KEY()↓
;jpn:◆おかねが たりなくて↓
;jpn: くろうしてます。@KEY()↓
;jpn:◆でも ぼく へいきです。@WI(20)↓
;jpn: あかるいせいかくですから。@KEY()↓
;jpn:◆グレートフルデッドのたにの↓
;jpn: うわさのモンスターを たおすにも@WI(20)↓
;jpn: このマシンさえ かんせいすれば‥@KEY()↓
;jpn:◆‥‥しきんを えんじょして↓
;jpn: くれるんですか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_ORANGE_YES,_TWSN_ORANGE_NO)

_TWSN_ORANGE_NO;
◆I guess I was just too hopeful.@WI(20)  Oh well, never mind.
;jpn:◆ちょっとでも あてにした↓
;jpn: ぼくが あまかったです。@WI(20)↓
;jpn: きに しないでください。
@KEYNP()
』

_TWSN_ORANGE_YES;
◆Oh goody!@WI(20)  Would it be okay to get $200 to buy materials?↓
<Yes> <No>
;jpn:◆そしたら ざいりょうひってことで↓
;jpn: 200ドル↓
;jpn: おねがいします。@KEY()↓
@WINR_MONEY()
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_ORANGE_THANKS,_TWSN_ORANGE_NO)
@GOTO(_TWSN_ORANGE_NO)

_TWSN_ORANGE_THANKS;
@Q_MONEY(200)
@TRUE_GOTO(_TWSN_ORANGE_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(200)
@WINR_MONEY()
;
_TWSN_ORANGE_THANKS_THANKS;
◆Thank you very much!@KEY()↓
◆Your support should have a tremendous impact on all mankind.
;jpn:◆ありがとうありがとう。@WI(20)↓
;jpn: これは せかいてきに↓
;jpn: いみのあるおこないと いえます!
@KEY()↓
@SETF(FLG_TWSN_ORANGE_THANKS)
;
_TWSN_ORANGE_THANKS_MAIN;
@CHKFGOTO(FLG_ITEM_GREATORANGE,_TWSN_ORANGE_LATER_1)
◆Let me give you my new ”Super Orange Machine.”@KEY()↓
◆I call it ”@DSP_GOODS(GDS_TOOL_GREORE_MACHINE)” for short.@KEY()↓
;jpn:◆さっそく かんせいしたばかりの↓
;jpn: 「グレートオレンジマシーン」↓
;jpn: りゃくしょう‥‥@KEY()↓
;jpn:◆「グレオレマシーン」を↓
;jpn: さしあげましょう!
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_ORANGE_THANKS_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_GREORE_MACHINE)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_ITEM_GREATORANGE)
@KEY()↓
◆Please use it for spreading peace and goodwill on Earth.
;jpn:◆せかいへいわのために↓
;jpn: やくにたててください。
@KEYNP()
』

;(使うと「オレンジキッドをたたえるうたが きこえた」)
_TWSN_ORANGE_THANKS_GOODSFULL;
◆Ah ha!@WI(20)  You have too many items.@KEY()↓
◆I hope you’ll accept the @DSP_GOODS(GDS_TOOL_GREORE_MACHINE),@WI(15) even if you have to toss some of your food...
;jpn:◆ああ にもつが↓
;jpn: いっぱいのようですね。@KEY()↓
;jpn:◆たべものの ひとつやふたつ↓
;jpn: すててでも マシーンを↓
;jpn: もっていってほしいなぁ‥‥。
@KEYNP()
』

_TWSN_ORANGE_NOMONEY;
◆What?!@WI(15)  You don’t have that much money?@KEY()↓
◆Well, perhaps you shouldn’t be yappin’ about having cash then,@WI(15) buddy.
;jpn:◆エッ?!↓
;jpn: まさか‥‥おかねがない?@KEY()↓
;jpn:◆あなた くちさきばっかりの↓
;jpn: にんげんみたいですね。
@KEYNP()
』

_TWSN_ORANGE_LATER_1;
@CHKF(FLG_ITEM_GREATORANGE)@FALSE_GOTO(_TWSN_ORANGE_THANKS_MAIN)
@CHKFGOTO(FLG_TWSN_ORANGE_LATER,_TWSN_ORANGE_LATER_2)
◆I’m hard at work...don’t worry,@WI(15) my brilliant invention will be ready soon.@KEY()↓
◆Okay, okay...@WI(20)  I’ll get back to work!
;jpn:◆がんばってますから もうすぐ↓
;jpn: かんせいしますよ。@WI(20)↓
;jpn: よーし! やるぞぉ!
@KEYNP()
@SETF(FLG_TWSN_ORANGE_LATER)
』

_TWSN_ORANGE_LATER_2;
◆I’m having more trouble than I expected.@KEY()↓
◆I found a problem in one of Einstein’s theories...
;jpn:◆おもったより くしんしています。@WI(20)↓
;jpn: アインシュタインのげんりに↓
;jpn: ちょっと もんだいがあって‥‥。
@KEYNP()
@CLRF(FLG_TWSN_ORANGE_LATER)
』

_TWSN_ORANGE_2;
◆You didn’t invest any money in my venture,@KEY()↓
◆but someone else donated a few million bucks,@WI(15) so everything is great.@KEY()↓
◆So would you like to invest,@WI(10) say,@WI(15) 50 bucks?↓
<Yes> <No>
;jpn:◆あなたは ぼくに↓
;jpn: とうし してくれませんでしたが@KEY()↓
;jpn:◆とくめいの かたから@KEY()↓
;jpn:◆なんびゃくまんおくドルの↓
;jpn: きふの もうしこみが↓
;jpn: あったんですよ!@KEY()↓
;jpn:◆あなたも 50ドルばかり↓
;jpn: とうし しますか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_ORANGE_2_YES,_TWSN_ORANGE_2_NO)

_TWSN_ORANGE_2_NO;
◆Oh,@WI(15) I’m sorry to hear that.@KEY()↓
◆...And you never heard how much money I got, too.@WI(15)  Right? *wink* *wink*...
;jpn:◆あ ごめんなさい↓
;jpn: おたがい きかなかったことに↓
;jpn: しましょう。
@KEYNP()
』

_TWSN_ORANGE_2_YES;
@Q_MONEY(50)
@TRUE_GOTO(_TWSN_ORANGE_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(50)
@WINR_MONEY()
@GOTO(_TWSN_ORANGE_THANKS_THANKS)

_TWSN_ORANGE_END_A;&
;投資していない
@CHKFGOTO(FLG_TWSN_ORANGE_THANKS,_TWSN_ORANGE_END_B)
◆Well, you never invested in my genius,@WI(15) did you?@KEY()↓
◆You had no idea of what I could do...@KEY()↓
◆*chortle*@KEY()↓
◆You sorry loser.
;jpn:◆ぼくという てんさいを↓
;jpn: いちども しえんしなかった↓
;jpn: @DSP_STS(STS_PC_NAME_NES)さん。@KEY()↓
;jpn:◆ぼくが どれくらい↓
;jpn: たいしたおとこか↓
;jpn: とうとう しらないままに@KEY()↓
;jpn:◆‥‥ふっふっふ@WI(20)↓
;jpn: ‥‥なりましたね。
@KEYNP()
』
_TWSN_ORANGE_END_B;投資した
◆Did you come here to get your investment money back?@KEY()↓
◆No?@WI(15)  Can you wait a little longer?@KEY()↓
◆I promise I’ll finish my brilliant invention.@KEY()↓
◆I rely on your support,@WI(15) even though I am a super genius.
;jpn:◆@DSP_STS(STS_PC_NAME_NES)さん↓
;jpn: いままで とうししたおかねの↓
;jpn: かいしゅうに きたんですか?@KEY()@WI(20)↓
;jpn:◆あ ちがう。@KEY()↓
;jpn:◆‥‥もうちょっと↓
;jpn: まってさえくれれば@KEY()↓
;jpn:◆かならず はつめいは↓
;jpn: かんせいしますから。@KEY()↓
;jpn:◆きながに ぼくという↓
;jpn: てんさいを みまもってください。
@KEYNP()
』

;----------------------------------------
;@Habitat:ツーソン/有望青年Bの家/有望青年Bの家
;@Person:アップルキッド
;@Figure:有望青年B
;@AppearanceKey:FLG_TWSN_CHAOSAPPLE_APPEAR/off
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_APPLEKID
;将来有望な青年B(アップルキッド)
;もうひとりの神童。デブで目つきは悪いが、やっぱり
;たいしたやつらしい。なんとなくゴロゴロしててたよりになり
;そうもなく見えてしまうが、本当はこいつが心強い味方に
;なってくれるのだ。マウスという名のねずみを飼っている。

MSG_TWSN_APPLEKID;
MSG_TWSN_APPLE;
@CHKFGOTO(FLG_ITEM_PHONE,_TWSN_APPLE_BYE)
@CHKFGOTO(FLG_TWSN_APPLE_THANKS,_TWSN_APPLE_THANKS)
@CHKFGOTO(FLG_TWSN_APPLE_FOOD,_TWSN_APPLE_FOOD)
◆Well,@WI(15) I have sort of neglected doing my housework...@KEY()↓
◆I know it’s a bit of a pig sty,@WI(15) but anyway...@KEY()↓
◆I’m Apple Kid.@KEY()↓
◆I haven’t taken a bath in quite a while,@WI(15) so I may be kind of stinky.
;DAN:"take a shower" is better for American teeens?  Also, is it better to say "I'm a little stink.”?
;jpn:◆そうじしてないから ちらかってて↓
;jpn: きたないけど‥‥@KEY()↓
;jpn:◆‥‥‥@KEY()↓
;jpn:◆ぼくが アップルキッドですが↓
;jpn: ‥‥おふろはいってないから↓
;jpn: ちょっと きたないけど‥‥
@KEY()↓
@WI(60)
◆By the way,@WI(15) I’m starving.@WI(20)  Do you have something to eat?@KEY()↓
◆If you do,@WI(15) can I have some?↓
;jpn:◆はらへったなぁ。↓
;jpn: なにか たべもの ありますか?@KEY()↓
;jpn:◆そして それを くれますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_TWSN_APPLE_YES,_TWSN_APPLE_NO)

_TWSN_APPLE_NO;
◆Well, go ahead and make yourself comfortable anyway.@WI(15)  You can flop down anywhere.
;jpn:◆じゃ そこいらへんで↓
;jpn: ごろごろしててください。↓
;jpn: じゃまにならないように。
@GOTO(_TWSN_APPLE_END)

_TWSN_APPLE_YES;
◆What can you give me?
;jpn:◆どれを くれるんですか?
@KEY()
@DSP_PL()
@GOSUB(MSG_SEL_GOODS)
↓
@FALSE_GOTO(_TWSN_APPLE_NO)		;キャンセル?
@SAVE_REG()				;主レ=PLAYER_ID:副レ=GOODSの位置で保存
@GET_PLAYER_GOODS(0,0)			;主レ=PLAYER_ID:副レ=GOODS_ID
@GOODS_TYPE_P(TYPE_EAT)			;グッズタイプチェック。
@TRUE_GOTO(_TWSN_APPLE_SELECT_FOOD)	;食べ物?
◆Please choose something edible...I’m not a garbage can, you know.
;jpn:◆たべものに してください。↓
;jpn: ぼくは ゴミばこじゃないんで‥。
@GOTO(_TWSN_APPLE_END)

_TWSN_APPLE_SELECT_FOOD;
@LOAD_REG()				;主レ=PLAYER_ID:副レ=GOODSの位置
@GOODSOUT_PLAYER(0,0)			;グッズ削除。
@SE(SE_se76_my_give)				;??
@WI(1)
◆Thanks.@WI(20)  You seem very nice.@WI(20)  Uh,@WI(15) I wonder if...
;jpn:◆ありがとう。↓
;jpn: あなた いいひとですね。@KEY()↓
;jpn:◆ついでみたいで わるいけど
@KEY()↓
@SETF(FLG_TWSN_APPLE_FOOD)
;
_TWSN_APPLE_FOOD_MAIN;
◆Maybe you would like to invest some money in my inventions?@KEY()↓
;jpn:◆ぼくのはつめいに しきんの↓
;jpn: えんじょを してくれますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_TWSN_APPLE_OK,_TWSN_APPLE_NO)
@GOTO(_TWSN_APPLE_NO)

_TWSN_APPLE_OK;
◆Yes!  Yes!  Yes!  Oh.  Excuse me.  I mean thank you!@KEY()↓
◆By the way, I could really use $200.
;jpn:◆そうか。やったなぁ。いいぞ。@KEY()↓
;jpn:◆さっそくですけど 200ドル↓
;jpn: おねがいします!↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_TWSN_APPLE_PAYOK,_TWSN_APPLE_NO)
@GOTO(_TWSN_APPLE_NO)
_TWSN_APPLE_PAYOK;
@Q_MONEY(200)
@TRUE_GOTO(_TWSN_APPLE_NOMONEY)
@MONEYOUT(200)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(1)
_TWSN_APPLE_THANKS;
◆Thank you.@WI(20)  I won’t let you down.
;jpn:◆ありがとう。↓
;jpn: できるかぎり がんばってみます。
@KEYNP()
@CLOSEALL()
@SETF(FLG_TWSN_APPLE_THANKS)
@SETF(FLG_WARP_APPLE_TWSN)
@FUNC(5)				;マップ上での全滅禁止
@GOTO(MSG_EVT_27_APPLE);ネズミ移動
』
_TWSN_APPLE_NOMONEY;@MiuraAppended
◆Oh, you don’t have any money, do you?
;jpn:◆あっ。↓
;jpn: おかね ないんですね。
@KEY()↓
@GOTO(_TWSN_APPLE_NO)

_TWSN_APPLE_BYE;
◆Maybe you shouldn’t spend too much time wandering around Twoson.
;jpn:◆いつまでも ツーソンで↓
;jpn: うろうろしてても しょうがない。↓
;jpn: ぼくは そうおもうんですよ。
_TWSN_APPLE_END;
@KEYNP()
@!

;食べ物をあげている場合のスタート
_TWSN_APPLE_FOOD;
◆It seems like you are expecting something from me.
;jpn:◆なんか ぼくに↓
;jpn: きたいしてくれてる↓
;jpn: みたいですね。
@KEY()↓
@GOTO(_TWSN_APPLE_FOOD_MAIN)


;@Habitat:ツーソン/有望青年Bの家/有望青年Bの家
;@Person:ペット
;@Figure:ねずみ
;@AppearanceKey:FLG_TWSN_CHAOSAPPLE_APPEAR/off
;@ActionScript:◆演出コンテ#2.5
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_MOUSE_0
MSG_TWSN_MOUSE_0;
;アップルキッドのねずみ(マウス)
;アップルにはマウスが付きものなので登場した。
@CLRF(FLG_WARP_APPLE_TWSN)
@CHKFGOTO(FLG_ITEM_PHONE,_TWSN_MOUSE_LATER)
@CHKFGOTO(FLG_TWSN_APPLE_THANKS,_TWSN_MOUSE)
_TWSN_MOUSE_LATER;
◆I am a mouse.@WI(20)  No one has given me a name yet.
;DAN: This script came from a famous Japanese novel written by Souseki Natsume.Majority of Japanese must know this line.
;jpn:◆わがはいは マウスである。@WI(30)↓
;jpn: なまえは まだない。
@CHKFGOTO(FLG_TEMP_3,_TWSN_MOUSE_BYE);マウスドアにいたら移動
@KEYNP()
』

_TWSN_MOUSE;
@FUNC(6)				;マップ上での全滅許可
◆I am a mouse.@WI(20)  No one has give me a name yet.@KEY()↓
◆You took care of my master.@KEY()↓
◆In return,@WI(15) I want to give you this.@WI(20)  Please take it and say nothing.
;jpn:◆わがはいは マウスである。@WI(30)↓
;jpn: なまえは まだない。@KEY()↓
;jpn:◆しゅじんが↓
;jpn: せわになった おれいに↓
;jpn: こんなものを さしあげたい。@KEY()↓
;jpn:◆えんりょなく もらってくれ。
@KEY()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_MOUSE_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_PHONE_RECEIVER)
@GOSUB(MSG_SUB_GETGOODS_S)
@SETF(FLG_ITEM_PHONE)
@CHKFGOTO(FLG_TEMP_3,_TWSN_MOUSE_BYE);マウスドアにいたら移動
@KEYNP()
』

_TWSN_MOUSE_BYE;
@KEY()↓
◆Oh! @WI(20) I must be bothering you!@WI(10) *zziipp!*
;DAN:"Sasa"is sound of moving fast.
;jpn:◆‥‥あ↓
;jpn: わがはいが ここにいたら↓
;jpn: じゃまだったな。@WI(10) ササッ!
@KEY()
@CLOSEALL()
@GOSUB(_SUB_CHK_MOUSE_DIR)
@GOSUB(MSG_EVT_27_MOUSE)
@CLRF(FLG_WARP_APPLE_TWSN)
@CLRF(FLG_TEMP_3)	;もうドアの前にいない。
』

_TWSN_MOUSE_ITEMFULL;
@WI(60)↓
◆Unfortunately,@WI(15) you have too many items.@WI(20)  Therefore, I can’t give this to you.
;jpn:◆しかし きみは にもつが↓
;jpn: いっぱいのようだ。@WI(20)↓
;jpn: ざんねんながら わたせないな。
@CHKFGOTO(FLG_TEMP_3,_TWSN_MOUSE_BYE);マウスドアにいたら移動
@KEYNP()
』

_SUB_CHK_MOUSE_DIR;
@GET_PLAYER_DIR(PC_ALL,2,PRSN_TWSN_APPLE_B)
@XCHG()
@SAVE_REG()
@EQ(1)
@TRUE_GOTO(_SUB_MOUSE_SETF)
@LOAD_REG()
@EQ(2)
@TRUE_GOTO(_SUB_MOUSE_SETF)
@LOAD_REG()
@EQ(8)
@TRUE_GOTO(_SUB_MOUSE_SETF)
@!
_SUB_MOUSE_SETF;
@SETF(FLG_ANIM_PORT_0)
@!

;----------------------------------------
;@Habitat:ツーソン/カオス劇場/受付
;@Person:切符きり(キャロットちゃん)
;@Figure:アーティスト
;@AppearanceKey:FLG_TWSN_CARROT_B_APPEAR/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:MSG_TWSN_CARROT_RECEIVE
;@CheckMessage:0
;@Message:MSG_TWSN_CARROT
MSG_TWSN_CARROT;
@CHKFGOTO(FLG_TLPT_THRK,_TWSN_CARROT_LATER)
@CHKFGOTO(FLG_TEMP_1,_TWSN_CARROT_TEMP)
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,_TWSN_CARROT_BYE)
@GET_PLAYER_DIR(PC_ALL,2,PRSN_TWSN_CHAOS_FRONT_A)
@GOSUB(MSG_SUB_Q_FRONT)
@FALSE_GOTO(_TWSN_CARROT_BYE)
◆Hello,@WI(15) please present your ticket.
;jpn:◆こんにちは。↓
;jpn: チケット おねがいします。
@KEYNP()
』

_TWSN_CARROT_LATER;
◆Sorry,@WI(15) the show is closed for a while.
;jpn:◆しばらく ショーは おやすみよ。
@KEYNP()
』

_TWSN_CARROT_BYE;
◆Oh, pardon me.
;jpn:◆あら ごめんなさい。
@KEY()
@CLOSEALL()
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,_TWSN_CARROT_BYE_R)
@GOSUB(MSG_EVT_31_CARROT_D)
@SETF(FLG_TEMP_1)
』
_TWSN_CARROT_BYE_R;
@GOSUB(MSG_EVT_31_CARROT_R)
@SETF(FLG_TEMP_1)
』

_TWSN_CARROT_TEMP;
◆See you.
;jpn:◆ごくろうさまです。
@KEYNP()
』

MSG_TWSN_CARROT_RECEIVE;
@SAVE_REG()
@CHKFGOTO(FLG_TEMP_1,_TWSN_CARROT_RECEIVE_TEMP)
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,_TWSN_CARROT_RECEIVE_LATER)
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SAVE_REG()
@EQ(GDS_TOOL_BACKSTAGE_PASS)
@TRUE_GOTO(_TWSN_CARROT_RECEIVE_TICKET)
;@LOAD_REG()
;@EQ(GDS_TOOL_THEATER_TICKET_X)
;@TRUE_GOTO(_TWSN_CARROT_RECEIVE_IMITATION)
;-----
@GET_PLAYER_DIR(PC_ALL,2,PRSN_TWSN_CHAOS_FRONT_A)
@GOSUB(MSG_SUB_Q_FRONT)		;前からじゃなかったら
@FALSE_GOTO(_TWSN_CARROT_BYE)	;下に移動
◆Please show me your ticket.
;jpn:◆チケット おねがいします。
@KEYNP()
』

_TWSN_CARROT_RECEIVE_TICKET;
@GET_PLAYER_DIR(PC_ALL,2,PRSN_TWSN_CHAOS_FRONT_A)
@GOSUB(MSG_SUB_Q_FRONT)		;前からじゃなかったら
@FALSE_GOTO(_TWSN_CARROT_BYE)	;下に移動
@SE(SE_se76_my_give)
;@GOODSOUT(PC_ALL,GDS_TOOL_BACKSTAGE_PASS)
◆Here you go.@WI(15)  Hurry!@WI(20)  You’re just in time to see the Runaway Five Show!
;jpn:◆どうぞ。ちょうどいまなら↓
;jpn: トンズラブラザーズの ステージに↓
;jpn: まにあうわよ。
@KEY()
@GOSUB(MSG_EVT_31_CARROT_R)
@SETF(FLG_TWSN_FIELD_TONZ_DISAPPEAR)
@SETF(FLG_TEMP_1)
』

;_TWSN_CARROT_RECEIVE_IMITATION;
;@SE(SE_se76_my_give)
;@GOODSOUT(PC_ALL,GDS_TOOL_THEATER_TICKET_X)

;◆あらら このチケットは↓
; にせものよ。@WI(20)ほら よくみると↓
; スカシがはいってないでしょ。@KEY()↓
;◆あなた わるいひとたちの↓
; なかまなんじゃないの。@KEYNP()
;』

_TWSN_CARROT_RECEIVE_LATER;
◆The show is closed for a while.
;jpn:◆しばらく ショーは おやすみよ。
@KEYNP()
』

_TWSN_CARROT_RECEIVE_TEMP;
◆How do you do?
;jpn:◆こんにちは。
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/受付
;@Person:(チケットを渡した後の)切符きり(キャロット)B
;@Figure:アーティスト
;@AppearanceKey:FLG_TWSN_CARROT_B_APPEAR/on
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:MSG_TWSN_CARROT_RECEIVE
;@CheckMessage:0
;@Message:MSG_TWSN_CARROT_B
MSG_TWSN_CARROT_B;
◆Oh, here you are!@WI(20)  Hurry up, you’re just in time to see the Runaway Five show.
;jpn:◆どうぞ。ちょうどいまなら↓
;jpn: トンズラブラザーズの ステージに↓
;jpn: まにあうわよ。
@KEY()
』

;@Habitat:ツーソン/カオス劇場/受付
;@Person:客
;@Figure:青年
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_TWSN_CHAOS_F
MSG_TWSN_CHAOS_F;
;カオス劇場受付客
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,_TWSN_CHAOS_F_TMP)
◆I guess I lost my ticket,@WI(15) so now I can’t get in.@KEY()↓
◆The ticket counter at the department store was even sold out.
;jpn:◆チケットをなくしちまって↓
;jpn: にゅうじょう できないんだよ。@KEY()↓
;jpn:◆デパートのチケットうりばでも↓
;jpn: もう うりきれなんだろうなぁ。
@KEYNP()
』
_TWSN_CHAOS_F_TMP;トンズラ解放時のメッセージ
◆*Sniff*@WI(15) I suppose I’ll never see the Runaway Five’s show again.
;DAN:He's sad.
;jpn:◆ぼく いっしょう↓
;jpn: トンズラブラザーズの↓
;jpn: ステージを みられないのか‥‥。
@KEYNP()
』
MSG_TWSN_CHAOS_E_LATER;&
◆Didn’t I see you at the Topolla Theater in Fourside?@KEY()↓
◆So you’re a Runaway Five groupie, too!
;DAN:I'm not sure about spelling of groopy.Also,groopy may be slightly different in the US.and Japan.Let’s discuss.
;jpn:◆やぁ。@WI(20)フォーサイドの↓
;jpn: トポロげきじょうで↓
;jpn: きみのかおを みたよ。@KEY()↓
;jpn:◆きみも トンズラの↓
;jpn: 「おっかけ」だったんだね。
@KEYNP()
』

;@Habitat:ツーソン/フィールド
;@Person:アップルマウス
;@Figure:ねずみ
;@AppearanceKey:FLG_TWSN_CHAOSAPPLE_APPEAR/on
;@ActionScript:◆ちょこまかと
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_CHAOS_MOUSE
MSG_TWSN_CHAOS_MOUSE;
;幼稚園前にいるマウス
◆I am a mouse.@KEY()↓
◆My master, Apple Kid, has been waiting for you.@KEY()↓
◆We started to nod off while waiting...
;jpn:◆わがはいは マウスである。@WI(20)↓
;jpn: しゅじんのアップルキッドは↓
;jpn: あんたを まっていた。@KEY()↓
;jpn:◆‥‥ふたりで↓
;jpn: あくびをしておった。
@KEYNP()
』

; なかにいる。@KEY()↓

;◆なにをしてるかは↓
; わがはいは しらぬ。@KEYNP()
;』


;@Habitat:ツーソン/カオス劇場/ホール
;@Person:ミーハーのミチコ
;@Figure:少女A
;@AppearanceKey:MSG_TWSN_MICHIKO_APPEAR/on
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_MICHIKO
MSG_TWSN_MICHIKO;
@CHKFGOTO(FLG_TWSN_TONZURA_FREE,MSG_TWSN_MICHIKO_LATER)
@CHKFGOTO(FLG_TWSN_MICHIKO_THANKYOU,_TWSN_MICHIKO_THANKYOU)
◆Lucky of the Runaway Five told me I could go backstage,@WI(15) but I don’t have a pass.@KEY()↓
◆I’m sure security will stop me.@WI(20)  Hey!@WI(20)  Really?@WI(30)  You have a pass?@KEY()↓
◆I can’t believe it!@WI(20)  Can you take me with you, please@WI(5) please@WI(10) please?@KEY()↓
◆I could pose as your sister.@WI(15)  Yes?  This rocks.@WI(15)  Let’s go.@KEY()↓
◆Ooo.@WI(15) My heart is pounding.
;jpn:◆トンズラのラッキーさんに↓
;jpn: がくやに あそびにおいでって↓
;jpn: いわれたんだけどー@KEY()↓
;jpn:◆バックステージパスを↓
;jpn: もってないから↓
;jpn: とめられちゃうのよね。@KEY()↓
;jpn:◆‥‥えー@WI(10) うっそー!@WI(15)↓
;jpn: なんで あなたがパスもってるの?@WI(20)↓
;jpn: しんじられなーい!@KEY()↓
;jpn:◆ねえ ねえ わたしのこと↓
;jpn: いもうとだってことにして↓
;jpn: がくやに つれてってよ。@KEY()↓
;jpn:◆やったー!↓
;jpn: サイコーじゃん!↓
;jpn: いこ いこ。@KEY()↓
;jpn:◆‥‥ドキドキするう。@KEY()
;◆はずかしくって ひとりじゃ↓
; いけないわけ。↓
; @WI(15)いっしょにきて くれる?@KEY()↓
;◆たのもしいしー。↓
; いこ。@WI(15)↓
; ‥‥ドキドキするう。
@KEY()
@CLOSEALL()
@GOSUB(MSG_EVT_39_MICHIKO)
@CLRF(FLG_TWSN_MICHIKO_APPEAR)
@SETF(FLG_TWSN_MICHIKO_THANKYOU)
』

_TWSN_MICHIKO_THANKYOU;
◆Thank you for your kindness!
;jpn:◆このあいだは↓
;jpn: どうもありがとー!
@KEYNP()
』


MSG_TWSN_MICHIKO_LATER;
◆I’m gonna miss the Runaway Five when they finally leave.@WI(20)  But that’s life!
;jpn:◆トンズラのみんなが↓
;jpn: このまちをでちゃうのは↓
;jpn: さみしいけどー‥‥。
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/ホール
;@Person:客A
;@Figure:ツッパリ
;@AppearanceKey:0
;@ActionScript:◆○○向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_CHAOS_A
MSG_TWSN_CHAOS_A;
;カオス劇場ホール客A
◆The Runaway Five are going to be a world−famous band someday.
;jpn:◆トンズラブラザーズって↓
;jpn: いつかは せかいにはばたく↓
;jpn: バンドになるぜ。
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/ホール
;@Person:客B
;@Figure:インディ
;@AppearanceKey:0
;@ActionScript:◆○○向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_CHAOS_B
MSG_TWSN_CHAOS_B;
;カオス劇場ホール客B
◆Do you like baseball?↓
<Yes> <No>
;jpn:◆おまえ やきゅうがすきなの?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TWSN_CHAOS_B_YES,_TWSN_CHAOS_B_NO)

_TWSN_CHAOS_B_NO;
◆Ah...I see.@KEY()↓
◆Well, you don’t look like you could figure out@KEY()↓
◆a sophisticated game like baseball anyway.
;jpn:◆ヘタそうだもんな。
@KEYNP()
』
_TWSN_CHAOS_B_YES;
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_TWSN_CHAOS_B_YES_POLA)
◆I knew it!@WI(20)  Your cap gave it away.
;jpn:◆ぼうしで わかったんだ。
@KEYNP()
』
_TWSN_CHAOS_B_YES_POLA;ポーラの時「ハイ」
◆You have the graceful movement of a baseball player.@KEY()↓
◆I’m on a baseball team,@WI(15) so I can recognize these things.
;jpn:◆そのめは やきゅうぶの めだ。@WI(30)↓
;jpn: おれも やきゅうぶだから↓
;jpn: わかるのさ。
@KEYNP()
』

;@Habitat:ツーソン/カオス劇場/ホール
;@Person:客C
;@Figure:ゴロツキ
;@AppearanceKey:0
;@ActionScript:◆○○向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_CHAOS_C
MSG_TWSN_CHAOS_C;
;カオス劇場ホール客C
◆Hey, hey, hey!@WI(15)  Don’t get too close to me.@KEY()↓
◆I just farted,@WI(15) heh, heh...sorry.
;jpn:◆おれに ちかよるんじゃねぇ!↓
;jpn: ‥‥‥↓
;jpn: ‥‥‥@KEY()↓
;jpn:◆いま へをしたところなんだ。↓
;jpn: わるかったな。
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/ホール
;@Person:客D
;@Figure:OLG
;@AppearanceKey:0
;@ActionScript:◆○○向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_CHAOS_D
MSG_TWSN_CHAOS_D;
;カオス劇場ホール客D
◆You kids are bouncing around,@WI(15) talking to everyone.@WI(20)  It’s getting annoying.
;jpn:◆あちこち はなしかけてるから↓
;jpn: めざわりで しょうがないわ。↓
;jpn: うるさいガキどもね。
@KEYNP()
』


;@Habitat:ツーソン/カオス劇場/ホール
;@Person:アップルキッド
;@Figure:有望青年B
;@AppearanceKey:FLG_TWSN_CHAOSAPPLE_APPEAR/on
;@ActionScript:◆○○向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TWSN_APPLE_CHAOS
MSG_TWSN_APPLE_CHAOS;
;ヌスット広場前
@CHKFGOTO(FLG_ITEM_TACO_ERASER,_TWSN_APPLE_CHAOS_LATER)
◆I’m feeling really out of it because lately I’ve been working all night,@KEY()↓
◆but finally the @DSP_GOODS(GDS_TOOL_KEY_TAKOKESHI) is ready.@KEY()↓
◆This machine will eradicate all pencil−shaped figures in just one second.@KEY()↓
◆It’s incredibly powerful.@WI(20)  Just don’t use it near a shop that serves pencil.@KEY()↓
◆Here, it’s yours now.
;DAN:TAKO is,as you know, Octopus.KESHI means to erase.
;jpn:◆てつやが つづいて↓
;jpn: ぼーっとしてますけど↓
;jpn: タコけしマシンが できてます。@KEY()↓
;jpn:◆これは タコのかたちをしたものを↓
;jpn: いっしゅんのうちに↓
;jpn: けしてしまう‥‥@KEY()↓
;jpn:◆おそろしいウエポンです。@WI(20)↓
;jpn: タコヤキやの きんじょで↓
;jpn: つかわないでくださいね。@KEY()↓
;jpn:◆さぁ もってっていいです。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TWSN_APPLE_CHAOS_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_TAKOKESHI)
@GOSUB(MSG_SUB_GETGOODS_S)
@KEY()↓
◆If I invent some other brilliant item,@WI(15) I’ll call you.
;jpn:◆また なにかあったら↓
;jpn: でんわします。
@KEYNP()
@CLOSEALL()
@CLRF(FLG_TWSN_CHAOSAPPLE_APPEAR)
@SETF(FLG_HAPPY_SWITCH)
@SETF(FLG_ITEM_TACO_ERASER)
』

_TWSN_APPLE_CHAOS_ITEMFULL;
◆Oh, it won’t fit in your backpack.@KEY()↓
◆Come back after you have gotten rid of some stuff.
;jpn:◆おっと にもつのリュックに↓
;jpn: はいりきれませんね。@KEY()↓
;jpn:◆にもつを へらしてから↓
;jpn: また きてください。
@KEYNP()
』

_TWSN_APPLE_CHAOS_LATER;
◆This machine will eradicate all pencil−shaped figures in just one second.@KEY()↓
◆It’s incredibly powerful.@WI(20)  Just don’t use it near a shop that serves pencil.@KEY()↓
◆I’ll call you if I invent another brilliant item.
;jpn:◆これは タコのかたちをしたものを↓
;jpn: いっしゅんのうちに↓
;jpn: けしてしまう‥‥@KEY()↓
;jpn:◆おそろしいウエポンです。@WI(20)↓
;jpn: タコヤキやの きんじょで↓
;jpn: つかわないでくださいね。@KEY()↓
;jpn:◆また なにかあったら↓
;jpn: でんわします。
@KEYNP()
』
;-------------------------------------------------
