;-------------------------------------
;@Habitat:Gデッド谷／谷の小屋／監視室
;@Person:鉄格子越しのポーラ
;@Figure:ドア
;@AppearanceKey:MSG_POLA_GRFD/off
;@ActionScript:◆正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_POLA
MSG_GRFD_POLA;
;ポーラ
;幼いころから、「ふしぎなちからを持つ少女」として、ツーソンの
;まちでは有名。幼稚園を経営する両親の手伝いをしているが、「NES」
;に助けられて後、共に冒険の旅に出る。
@CHKFGOTO(FLG_WIN_CARPAINTER,_GRFD_POLA_LATER)
@CHKFGOTO(FLG_ITEM_FRANKLINBADGE,_GRFD_POLA_1)
@CHKFGOTO(FLG_TEMP_9,_GRFD_POLA_TMP)
◆...Who?...@KEY()↓
◆...Are you @DSP_NAME(PC_NESS)?@KEY()↓

◆@DSP_NAME(PC_NESS)!  I’m so glad it’s you.@KEY()↓
◆I had a dream that a boy named @DSP_NAME(PC_NESS) was my destiny.@KEY()↓
◆I know it’s hard to believe.
@KEY()↓
;jpn:◆‥@WI(20)‥@WI(20)だれ?@KEY()↓
;jpn:◆‥@WI(20)‥@WI(20)@DSP_STS(STS_PC_NAME_NES)じゃない?@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)ね!@WI(30)↓
;jpn: ああ よかった。↓
;jpn: @DSP_STS(STS_PC_NAME_NES)というなの ひとが@KEY()↓
;jpn:◆わたしと うんめいを↓
;jpn: ともにするって‥‥@WI(30)そんなゆめを↓
;jpn: たしかに みたの。@KEY()↓
_GRFD_POLA_TMP;
◆Thank you.@WI(15)  I knew you would rescue me.@KEY()↓
◆If you didn’t come,@WI(15) I would have had to try to bust out of here.
@KEY()↓
;jpn:◆ありがとう‥‥@WI(20)↓
;jpn: やっぱり↓
;jpn: たすけにきてくれたのね。@KEY()↓
;jpn:◆あなたが きてくれなかったら@WI(20)↓
;jpn: わたし‥‥@WI(60)↓
;jpn: なきだしちゃうところだった。@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
◆You can’t open the door.@KEY()↓
◆You’ll have to get the key from Carpainter.  He’s got it hidden away.@KEY()↓
◆I heard Carpainter can control lightning.@KEY()↓
◆In that case,@WI(15) you should wear this @DSP_GOODS(GDS_HAVE_FRANKLIN_BADGE), okay?
;◆ここのカギをもった↓;こちらに変更したいけど複雑
; わるいひとが↓
; さっき あわててでていったわ。@KEY()↓
;◆まだ そのへんに↓
; いるかもしれない。@WI(20)↓
; きをつけて!@KEYNP()
;』
;jpn:◆ここのカギは↓
;jpn: いまの わたしたちじゃ↓
;jpn: あけられないわ。@KEY()↓
;jpn:◆カーペインターが↓
;jpn: かくしもっているカギを↓
;jpn: とってこないと‥‥。@KEY()↓
;jpn:◆でも カーペインターは↓
;jpn: カミナリを あやつるらしいの。@KEY()↓
;jpn:◆このフランクリンバッジを↓
;jpn: つけていくと いいわ。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_GRFD_POLA_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_HAVE_FRANKLIN_BADGE)
@GOSUB(MSG_SUB_GETGOODS_S)
@KEY()↓
@SETF(FLG_ITEM_FRANKLINBADGE)
@SETF(FLG_GRFD_POKEY_APPEAR)
@CLRF(FLG_ONET_POLA_TELEPATHY);ポーラに会ったらテレパシーは聞けない
@CLRF(FLG_TWSN_POLA_TELEPATHY)
◆I’ll wait here until you return.@KEY()↓
◆Come back here and get me out once you defeat Carpainter.@KEY()↓
◆Don’t worry about me, just kick butt like I know you can!
@KEYNP()
;jpn:◆わたし ここでまってるから@KEY()↓
;jpn:◆きっと あいつをたおして↓
;jpn: むかえにきてね。@KEY()↓
;jpn:◆わたし いつまでだって↓
;jpn: まっていられるわ。@KEY()↓
;jpn:◆あなたのちから↓
;jpn: しんじているもの。@KEY()↓
;jpn:◆しんぱいしないで↓
;jpn: がんばってね。@KEYNP()
@SETF( FLG_SYS_MONSTER_OFF )	;モンスター出現禁止
@FUNC(5)			;マップ上での全滅禁止
』

_GRFD_POLA_ITEMFULL;
@SE(SE_se05_undo)
◆What−−@WI(15)do you want to get fried by lightning?@KEY()↓
◆Get rid of something so I can give you the @DSP_GOODS(GDS_HAVE_FRANKLIN_BADGE).
@KEYNP()↓
;jpn:◆もちものが いっぱいで↓
;jpn: 「フランクリンバッジ」を↓
;jpn: もてないのね。@KEY()↓
;jpn:◆なにか うるか つかうかして↓
;jpn: もちものを へらしてくると↓
;jpn: いいとおもう。@KEYNP()
@SETF(FLG_TEMP_9)
』

_GRFD_POLA_1;
◆If you didn’t come,@WI(15) I would have had to try to bust out of here.@KEY()↓
;jpn:◆あなたが きてくれなかったら@WI(20)↓
;jpn: わたし‥‥@WI(60)↓
;jpn: なきだしちゃうところだった。@KEY()↓
;jpn:◆‥‥‥。@KEYNP()
;
;◆There was a bad looking person
;  rushing out of here with 
;  a key of this room.
;◆He might be still around here.
;  Be careful!

;◆ここのカギをもった↓
; わるいひとが↓
; さっき あわててでていったわ。@KEY()↓
;◆まだ そのへんに↓
; いるかもしれない。@WI(20)↓
; きをつけて!@KEYNP()
』

_GRFD_POLA_LATER;
;◆@DSP_STS(STS_PC_NAME_NES)!
;
;◆@DSP_STS(STS_PC_NAME_NES)↓
;jpn: カギを とってきてくれたのね!@KEY()↓
_GRFD_POLA_LATER_TMP;
◆@DSP_NAME(PC_NESS)!  You got the key!@KEY()↓
◆Are you hurt?↓
<Yes> <No>
;jpn:◆けがは ない?@WI(20)↓
;jpn: だいじょうぶ?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_GRFD_POLA_LATER_YES,_GRFD_POLA_LATER_NO)

_GRFD_POLA_LATER_NO;
_GRFD_POLA_LATER_YES;
◆I’m sorry for all the trouble I’ve caused you.
@KEYNP()
;jpn:◆わたしのために‥‥↓
;jpn: ごめんなさい。@KEYNP()
』
;◆Great!
;◆I’ve been believing you.
;◆So, let me out of here quickly!
;◆やったー!@WI(15)↓
; わたし しんじてたわ。@WI(15)↓
; はやくここから だして!@KEYNP()
;』


;@Habitat:Gデッド谷／谷の小屋／牢や
;@Person:ポーラ
;@Figure:ポーラ
;@AppearanceKey:MSG_POLA_GRFD/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_POLA_LATER_USEKEY
;MSG_GRFD_POLA_LATER_USEKEY;
;牢内のポーラ
;◆I’m so happy!
;◆You’re someone as I expected.
;◆Let’s return to Twoson.
;◆うれしいっ!@WI(15)↓
; わたしの おもったとおりの↓
; ひとだった。@KEY()↓
;◆さぁ ツーソンに もどりましょ。@KEY()
;@SETF(FLG_POLA_GRFD)
;@SE(SE_se10_present_open)
;@GOSUB(MSG_ADD_PAULA)
;』


；----------------------------------------

;@Habitat:Gデッド谷／フィールド／谷の小屋の前
;@Person:ポーキー
;@Figure:ポーキー
;@AppearanceKey:FLG_GRFD_POKEY_APPEAR/on
;@ActionScript:◆ネスに近寄ってセリフ発行
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_POKEY

;@Habitat:Gデッド谷／フィールド／谷の小屋の前
;@Person:ポーキー子分A
;@Figure:HH教信者
;@AppearanceKey:FLG_GRFD_POKEY_APPEAR/on
;@ActionScript:◆ポーキーの合図でネスにケンカ売る
;@GoodsMessage:0
;@CheckMessage:0
;@Message:0

;@Habitat:Gデッド谷／フィールド／谷の小屋の前
;@Person:ポーキー子分B
;@Figure:HH教信者
;@AppearanceKey:FLG_GRFD_POKEY_APPEAR/on
;@ActionScript:◆ポーキーの合図でネスにケンカ売る
;@GoodsMessage:0
;@CheckMessage:0
;@Message:0

;-------------------------------------------------

MSG_GRFD_SIGNPOST_A;
;ポーキーがセットした偽標識
;フランクリンバッジを手に入れた後は消滅する
◆(Cross bridge to Happy−Happy Village)
@KEYNP()
;jpn:◆(ハッピーハッピーむらへ↓
;jpn: おいでのかたは このはしを↓
;jpn: わたってください)@KEYNP()

;◆Left
;  Short cut.
;◆(It appears to be
;  very bad hand writing.)

;◆ひだり↓
; ちかみちでございませ。@KEY()↓
;◆(なにやら ずいぶん↓
;  ヘタクソな もじだ)@KEYNP()
』

;@Habitat:Gデッド谷／リリパットステップのダンジョン／大広間
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_LLPT_BOSS/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_LLPT_BOSS
MSG_GRFD_LLPT_BOSS;
@CHKFGOTO(FLG_WIN_LLPT_BOSS,MSG_SYS_HANASU_NG)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆You finally got here.@KEY()↓
◆This is the second ”Your Sanctuary” location.@WI(20)  But it’s mine now.@KEY()↓
◆Take it from me,@WI(30) if you dare...
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは ２ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし いまは↓
;jpn: わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_LLPT_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_GRFD_LILIPUT_1_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_LLPT_BOSS)
』

MSG_GRFD_KINOKO_GIRL;
@GOSUB(MSG_SUB_GRFD_KINOKOGIRL)
@!
;---------------------------------------------------

MSG_GRFD_SHINTO_A;壊れた橋の信者
◆I wonder who made the bridge impassable?@KEY()↓
◆Why would someone do this?@WI(15)  Crud...
@KEYNP()
;jpn:◆だれかが はしを↓
;jpn: とおれなくしちまったんだよぅ。@KEY()↓
;jpn:◆どーして こんなことを↓
;jpn: するんだろう‥‥まったく。@KEYNP()
』
;---------------------------------------------------

MSG_GRFD_SYSMSG_GUTS;＄β
◆(I’m not an enemy.@KEY()↓
◆I’m just a regular mole.@KEY()↓
◆Would you like to know about how to survive battles.)@KEY()↓
<Yes> <No>
;jpn:◆(おれは てきじゃない。↓
;jpn: ただの もぐらさ。@KEY()↓
;jpn:◆「ガッツ」について↓
;jpn: おれのしってることを↓
;jpn: ぜんぶ はなそうか?)@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_GRFD_SYSMSG_GUTS_YES,_GRFD_SYSMSG_GUTS_NO)
_GRFD_SYSMSG_GUTS_NO;
◆(Well, you seem to know a lot already, even if you don’t look like it.)
@KEYNP()
;jpn:◆(おまえって いがいと↓
;jpn: ガッツありそうだもんな)@KEYNP()
』
_GRFD_SYSMSG_GUTS_YES;
◆(You may have noticed that, when you have been badly hurt in battle,@KEY()↓
◆you may survive a mortal attack and still have １ HP.  If this has happened,@KEY()↓
◆it was because of your Guts.  Your survival may depend on your Guts level.@KEY()↓
◆Also, more Guts helps you get more SMAAAAASHing hits.@KEY()↓
◆Beyond Guts, you should have noticed that it takes some time@KEY()↓
◆for damage to be taken from you.
◆This is because of the rolling action of your HP meter.  Oops! I mean your life.
◆If an enemy deals mortal damage to you, but you defeat all enemies@KEY()↓
◆before your life is gone, you survive.  This is all I know.)
@KEYNP()
;jpn:◆(たたかいのなかで↓
;jpn: きぜつするほどの↓
;jpn: ダメージをうけたはずなのに@KEY()↓
;jpn:◆たいりょくが「１」で↓
;jpn: ふみとどまった ‥‥なんて↓
;jpn: けいけん あるかい?@KEY()↓
;jpn:◆もし あったとしたら↓
;jpn: それは おまえの「ガッツ」が↓
;jpn: すごかったからだよ。@KEY()↓
;jpn:◆どたんばで↓
;jpn: ふんばりがきくかどうか。↓
;jpn: それは「ガッツ」しだいってこと。@KEY()↓
;jpn:◆それとね 「ガッツ」が↓
;jpn: たくさんあるやつは‥‥@KEY()↓
;◆@WI(20)SMAAAAASH!!↓
;jpn: @WI(30)‥‥が でやすくなるんだ。@KEY()↓
;jpn:◆しってることは それだけさ)@KEYNP()
』
;---------------------------------------------------
