;-------------------------------------------------------------

;@Habitat:グレープフルーツの滝/フィールド/ゲップー基地入り口
;@Person:合言葉の敵
;@Figure:ヒットくん
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_PASSWORD

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/入り口付近
;@Person:ゲップー手下A(ハエ蜜検査)
;@Figure:ムッド
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_MINIGEPPU_A
MSG_GPFT_MINIGEPPU_A;
@CHKFGOTO(FLG_GPFT_MINIGEPPU_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@OPEN(1)
◆Did you bring some ”Fly Honey”?@KEY()↓
◆It’s Master Belch’s favorite.↓
<YES> <NO>
;jpn:◆ゲップーさまの だいこうぶつの↓
;jpn: 「はえみつ」を↓
;jpn: もってきたのか?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_GPFT_MINIGEPPU_A_YESNO,_GPFT_MINIGEPPU_A_NO)

_GPFT_MINIGEPPU_A_NO;
◆Then, why are you here?!
@KEY()
;jpn:◆じゃ なにをしにきたんだ!@KEY()
@CLOSEALL()
@GOSUB(MSG_BATTLE_MINIGEPPU_A)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_GPFT_GEPPU_1_A,ANIM_BLINK_SUICIDE)
@SETF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
』

_GPFT_MINIGEPPU_A_YESNO;
@Q_HAVE(PC_ALL,GDS_FOOD_HAEMITSU)
@TRUE_GOTO(_GPFT_MINIGEPPU_A_YES)
◆You didn’t bring it?@WI(20)  You seem kind of suspicious to me...@KEY()↓
◆You cannot pass through here!
@KEY()
;jpn:◆もってないじゃないか!@WI(15)↓
;jpn: あやしいやつめ↓
;jpn: ここは とおせぬ!@KEY()
@CLOSEALL()
@GOSUB(MSG_BATTLE_MINIGEPPU_A)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_GPFT_GEPPU_1_A,ANIM_BLINK_SUICIDE)
@SETF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
』

_GPFT_MINIGEPPU_A_YES;
◆Ok, you may pass through.@KEY()↓
◆Hey, be careful!@WI(20)  Be sure you don’t drop it!
@KEY()
;jpn:◆よし とおれ。@WI(15)↓
;jpn: こぼさないように↓
;jpn: きをつけて いけよ!@KEY()
@CLOSEALL()
;@ANIM(ANIM_RETIRE)
』


;@Habitat:グレープフルーツの滝/ゲップーダンジョン/どこか
;@Person:ゲップー手下B
;@Figure:ムッド
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_MINIGEPPU_B
MSG_GPFT_MINIGEPPU_B;
◆Urp!@KEY()↓
◆...It’s hard to make the gross sounds that Master Belch does.@KEY()↓
◆I know I can’t do it.
@KEYNP()
;jpn:◆ゲーップ!@WI(15)↓
;jpn: ‥‥なかなかゲップーさまのような↓
;jpn: きたならしいおとが でないなぁ。@KEYNP()
』

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/どこか
;@Person:ゲップー手下C
;@Figure:ムッド
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_MINIGEPPU_C
MSG_GPFT_MINIGEPPU_C;
◆Master Belch is the slimiest!@KEY()↓
◆However, I heard he’s also serving some Giygas guy.@WI(15)  That I cannot believe.
@KEYNP()
;jpn:◆ゲップーさまは すごいけど@WI(15)↓
;jpn: ゲップーさまだって↓
;jpn: ギーなんとかさまの@KEY()↓
;jpn:◆ぶかだっていうじゃないか。@WI(15)↓
;jpn: かんがえられねぇよなぁ‥‥。@KEYNP()
』

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/どこか
;@Person:ゲップー手下D
;@Figure:ムッド
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆近寄ってくる
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_MINIGEPPU_D
MSG_GPFT_MINIGEPPU_D;
@CHKFGOTO(FLG_GPFT_MINIGEPPU_D_DISAPPEAR,MSG_SYS_HANASU_NG)
@OPEN(1)
◆Aren’t you the Fly Honey delivery boy?@WI(15)  What’s the password!@KEY()↓
◆It doesn’t mean I don’t trust you.@WI(15)  Just say it!@KEY()↓
◆Say it now!@KEY()↓
◆Someone so quiet is either extremely shy or extremely dangerous...@KEY()↓
◆What a suspicious fellow!
@KEY()
;jpn:◆「はえみつ」の はいたつか?@WI(15)↓
;jpn: いちおう あいことばを いえ!@WI(15)↓
;jpn: うたがうわけじゃないけどな。@KEY()↓
;jpn:◆はやく いえよ!@KEY()↓
;jpn:◆いえってば!@KEY()↓
;jpn:◆こんなに だまってるってことは↓
;jpn: ものすごくむくちなやつか↓
;jpn: てき!@WI(15)ってことだぞ。@KEY()↓
;jpn:◆くせもの!!@KEY()
@CLOSEALL()
@GOSUB(MSG_BATTLE_MINIGEPPU_D)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_GPFT_GEPPU_1_D,ANIM_BLINK_SUICIDE)
@SETF(FLG_GPFT_MINIGEPPU_D_DISAPPEAR)
』

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/どこか
;@Person:ゲップー手下E
;@Figure:ムッド
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆近寄ってくる
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_MINIGEPPU_E
MSG_GPFT_MINIGEPPU_E;
@CHKFGOTO(FLG_GPFT_MINIGEPPU_E_DISAPPEAR,MSG_SYS_HANASU_NG)
@OPEN(1)
◆So, you’re the ones who destroyed the zombies that I assigned to Threed!!
@KEY()
;jpn:◆スリークに おくりこんだ↓
;jpn: ゾンビを やっつけたのは↓
;jpn: おまえたちだったんだな!!@KEY()
@CLOSEALL()
@GOSUB(MSG_BATTLE_MINIGEPPU_E)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_GPFT_GEPPU_1_E,ANIM_BLINK_SUICIDE)
@SETF(FLG_GPFT_MINIGEPPU_E_DISAPPEAR)
』

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/ベルトコンベア付近
;@Person:囚われの土星さんA
;@Figure:土星さん
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_DOSEI_A
MSG_GPFT_DOSEI_A;
@FONTBAKA()
◆Tired.@KEY()↓
◆But so good.  Ding!
@KEYNP()
;jpn:◆くたびれたー。↓
;jpn: でも↓
;jpn: だいじょうぶさ。@KEYNP()
@FONTSTD()
』

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/ベルトコンベア付近
;@Person:囚われの土星さんB
;@Figure:土星さん
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_DOSEI_B
MSG_GPFT_DOSEI_B;
@FONTBAKA()
◆Ah!  So@WI(5)o@WI(5)o@WI(5)o...
  Honest!@KEY()↓
◆Smile.  Boing!
@KEYNP()
;jpn:◆あー もー‥‥。↓
;jpn: ほんとにー!@WI(20)↓
;jpn: ニコニコ。@KEYNP()
@FONTSTD()
』

;@Habitat:グレープフルーツの滝/ゲップーダンジョン/出口前
;@Person:ゲップー
;@Figure:大ムッド
;@AppearanceKey:FLG_WIN_GEPPU/off
;@ActionScript:◆止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_GEPPU
MSG_GPFT_GEPPU;$
;とにもかくにも、でかい、強い、汚い。
;ギーグの部下のなかでも最悪のモンスター。
;ギーグ自身も気持ちわるがっているらしく、出世コースからは
;外れているという。
@CHKFGOTO(FLG_WIN_GEPPU,MSG_SYS_HANASU_NG)
@BGMSTART(0,BGM_msc10);ゲップ入りの曲
@SE(SE_se4e_foe_gepu)
◆Buuurp!@KEY()↓
◆So you are @DSP_NAME(PC_NESS)?@KEY()↓
;jpn:◆@SE(SE_se4e_foe_gepu)@WI(40)グエーップ!@WI(15)↓
;jpn: おまえが @DSP_STS(STS_PC_NAME_NES)か。@KEY()↓
@SET_LOOPREG(PC_NESS)			;ネスのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_GPFT_GEPPU_DEAD)
◆...I see...Gyork!@WI(15)  Gyork!@WI(15)  Gyork!@KEY()↓
◆There’s a prophecy that a boy will destroy Master Giygas.@KEY()↓
◆Heeg!  Heeg!  Heeg!↓
  You make me laugh so hard,...@KEY()↓
;jpn:◆‥‥そうか‥‥ゴゲゴゲゴゲ。@KEY()↓
;jpn:◆おまえが ギーグさまを↓
;jpn: たおすと↓
;jpn: よげんが あったらしいぞ。@KEY()↓
;jpn:◆ゲハゲハゲハゲハ↓
;jpn: わらわせるなぁ。@WI(15)↓
;jpn: こんな くそったれを‥‥@KEY()↓
;@SE(SE_se4e_foe_gepu)@WI(40)↓
◆If Master Giygas is scared of someone...@KEY()↓
@SE(SE_se4e_foe_gepu)
◆he would have to be worse than the greatest evil...@KEY()↓
◆Garg!  Ga!  Garg!  Ga!  Ga!  Ga!@KEY()↓
;jpn:◆ギーグさまが すこしでも↓
;jpn: おそれているとしたら‥‥@KEY()@SE(SE_se4e_foe_gepu)@WI(40)↓
;jpn:◆よのなか おにも あくまも↓
;jpn: ないものか‥‥ゲヒヒヒヒヒ。@KEY()↓
;@SE(SE_se4e_foe_gepu)@WI(40)↓
◆I’ll take you down big time, so get ready for the worst fight of your life!
@KEY()↓
;jpn:◆おれさまが いまから↓
;jpn: さいあくのたたかいで↓
;jpn: おまえを しまつしてやる!@KEY()↓
@SE(SE_se4e_foe_gepu)@WI(40)↓

_GPFT_GEPPU_MAIN;合流点
◆Gha Gha Gha!↓
  Get ready to feel the pain of true nausea!@KEY()↓
@SE(SE_se4e_foe_gepu)@WI(40)
◆Ghe Ghe!↓
  Come on, let’s go!
@KEY()
;jpn:◆グッグッグッグッ↓
;jpn: へどまみれになって くるしめ!@KEY()@SE(SE_se4e_foe_gepu)@WI(40)↓
;jpn:◆ゴゲッ ゴゲッ↓
;jpn: さぁ こい!@KEY()
@GOSUB(MSG_BATTLE_GEPPU)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@OPEN(1)
;---------
@BGMSTART(0,BGM_msc10);ゲップ入りの曲
;---------
◆@SE(SE_se4e_foe_gepu)@WI(40)Looks like it was an even fight...@WI(20)  Buurp!@KEY()↓
◆But, Master Giygas has managed to get the Mani Mani statue into Fourside.@WI(20)@SE(SE_se4e_foe_gepu)@WI(40)@KEY()↓
◆The city will soon be in worse condition than living in your own puke!@KEY()↓
◆Suffer, spanky!@WI(20)@SE(SE_se4e_foe_gepu)↓
  @WI(40)Gha, Gha, Gha, Gha, Gha!@KEY()↓
◆Bu@WI(5)u@WI(5)u@WI(5)urp!@SE(SE_se4e_foe_gepu)@WI(40)
;jpn:◆@SE(SE_se4e_foe_gepu)@WI(40)グブグブ@WI(20) ゲーゲ@WI(10) ゲーゲ@WI(15)↓
;jpn: おれとのたたかいは じじつじょう↓
;jpn: ひきわけってことだな。@KEY()↓
;jpn:◆ゲーーーップ!@WI(20)↓
;jpn: だが ギーグさまが↓
;jpn: しゅうとうにしかけた@KEY()↓
;jpn:◆@WI(20)@SE(SE_se4e_foe_gepu)@WI(40)「マニマニのあくま」の せいで↓
;jpn: だいとかい フォーサイドは@KEY()↓
;jpn:◆ゲロゲロいじょうの↓
;jpn: ひどいことに なるはずさ。@WI(60)ゲプッ@KEY()↓
;jpn:◆くるしみに いくがいいさ!@SE(SE_se4e_foe_gepu)@WI(40)↓
;jpn: ゲボゲボゲボ@WI(10) ゲホゲボ@WI(15)↓
;jpn: ゲローーップ!@SE(SE_se4e_foe_gepu)@WI(40)
@KEY()↓
@CLOSEALL()
@WI(1)
@REMOVE_CHAR(PRSN_GPFT_GEPPU_6_A,ANIM_BLINK_SUICIDE)
@SETF(FLG_WIN_GEPPU)
@SETF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
@SETF(FLG_GPFT_MINIGEPPU_D_DISAPPEAR)
@SETF(FLG_GPFT_MINIGEPPU_E_DISAPPEAR)
@SETF(FLG_THRK_PEOPLE_APPEAR)
@SETF(FLG_THRK_BUIL_B_MAN_APPEAR);おまけ
@SETF(FLG_DOSEI_ONSEN_GERO);温泉のメッセージ切り替え
@SETF(FLG_PHOTO_ONSEN);撮り頃フラグ
@SETF(FLG_PHOTO_TENTO);撮り頃フラグ
;@SETF(FLG_PHOTO_BONE);撮り頃フラグ;黒ゴマと話した後に変更
@CLRF(FLG_THRK_ZOMBI_CAPTURED)
@CLRF(FLG_THRK_OZISAN_D_DISAPPEAR);テントの人出現
@CLRF(FLG_THRK_TUNNEL_CLOSE);ゲップ倒すまでスリークから出さない
@SET_COMEBACK_POS(TLPT_DOSEIDANI);死亡時にも温泉に出てもらう
;--------
@MUSISTART()
;--------
』
_GPFT_GEPPU_DEAD;
◆...No?...↓
  Gyork, Gyork, Gyork!@KEY()↓
◆I heard there’s a prophecy that he would defeat Master Giygas...@KEY()↓
◆Heeg Heeg Heeg↓
  You make me laugh so hard!@KEY()↓
;jpn:◆‥‥ちがうのか‥‥ゴゲゴゲゴゲ。@KEY()↓
;jpn:◆そいつが ギーグさまを↓
;jpn: たおすと↓
;jpn: よげんが あったらしいぞ。@KEY()↓
;jpn:◆ゲハゲハゲハゲハ↓
;jpn: わらわせるなぁ。@WI(15)↓
;jpn: こんな くそったれどもを‥‥@KEY()↓
;@SE(SE_se4e_foe_gepu)@WI(40)↓
◆If Master Giygas is scared of someone...@SE(SE_se4e_foe_gepu)@KEY()↓
◆he would have to be worse than the greatest evil...
@KEY()↓
;jpn:◆ギーグさまが すこしでも↓
;jpn: おそれているとしたら‥‥@KEY()@SE(SE_se4e_foe_gepu)@WI(40)↓
;jpn:◆よのなか おにも あくまも↓
;jpn: ないものか‥‥ゲヒヒヒヒヒ。@KEY()↓
;@SE(SE_se4e_foe_gepu)@WI(40)↓
◆I’ll take you down big time,@WI(15) so get ready for the worst fight of your life!
@KEY()↓
;jpn:◆おれさまが いまから↓
;jpn: さいあくのたたかいで↓
;jpn: おまえ@GOSUB(MSG_SUB_TATI)を しまつしてやる!@KEY()↓
;@SE(SE_se4e_foe_gepu)@WI(40)↓
@GOTO(_GPFT_GEPPU_MAIN);合流点へ


;@Habitat:グレープフルーツの滝/ミルキーウェル/3通路
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_MLKY_BOSS/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GPFT_MLKY_BOSS
MSG_GPFT_MLKY_BOSS;
@CHKFGOTO(FLG_WIN_MLKY_BOSS,MSG_SYS_HANASU_NG)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆You finally got here.@KEY()↓
◆This is the third ”Your Sanctuary” location.@WI(20)  But it’s mine now.@KEY()↓
◆Take it from me,@WI(30) if you dare...
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは 3ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし いまは↓
;jpn: わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_MLKY_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_GPFT_MILKY_1_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_MLKY_BOSS)
』
;-------------------------------------------------

MSG_GPFT_HAKAMORI;
@GOSUB(MSG_SHOP_GPFT_GRAVEKEEPER)
@!
;◆あんたたち おハカのしたを↓
; ぬけてきたのか?!@KEY()↓
;◆むてっぽうなことするねぇ。@WI(20)↓
; ‥‥ハラもへったことだろう。↓
;◆あ@WI(15) ちょうどいい。@WI(20)↓
; おじさん たべものをもってたよ。@KEY()↓

;取り引きのあとに
;◆ぜんめんてきに↓
; つかれを いやしたいなら@KEY()↓
;◆このさきに おもろいひとたちの↓
; むらがあるから↓
; そっちで やすめばいい。@KEY()↓
;◆おじさんは↓
; こまったひとたちを たすけるのが↓
; ほんとに すきなんだ。@KEY()↓
;◆‥‥おかねは とるけどね。@KEY()↓
;』
;-------------------------------------------------

MSG_THRK_BOSS_GRAVE;墓場のボス
@Q_HAVE(PC_ALL,GDS_FOOD_HAEMITSU)
@TRUE_GOTO(_THRK_BOSS_GRAVE_HAVE)
;ハエミツなし
◆Gyork Gyork!@KEY()↓
◆Hey you, commoner!@WI(20)  You there wandering around without any ”Fly Honey”...@KEY()↓
◆I am the mortal enemy of your kind.
@KEY()
;jpn:◆グケッ グケッ。@KEY()↓
;jpn:◆「はえみつ」も もたずに↓
;jpn: このあたりを うろついているとは↓
;jpn: ‥‥ふつうのやつ!@KEY()↓
;jpn:◆おれと おまえは↓
;jpn: つまり てきどうし!@KEY()
;戦闘に
』

_THRK_BOSS_GRAVE_HAVE;ハエミツあり
◆Gyork!  Gyork!@KEY()↓
◆Since you had ”Fly Honey,” I considered you a friend.@KEY()↓
◆But actually, you’re just a commoner!@WI(20)  I am the mortal enemy of your kind.
@KEY()
;jpn:◆グケッ グケッ。@KEY()↓
;jpn:◆「はえみつ」を もっているから↓
;jpn: なかまかとおもったら↓
;jpn: どうやら ふつうのやつ!@KEY()↓
;jpn:◆そんな ふつうのやつは↓
;jpn: おれの てきだ!@KEY()
;戦闘に
』

MSG_THRK_BOSS_GRAVE_DIE;戦闘後
@OPEN(1)
@Q_HAVE(PC_ALL,GDS_FOOD_HAEMITSU)
@TRUE_GOTO(_THRK_BOSS_GRAVE_DIE_HAVE)
;ハエミツなし
◆You have defeated me...@KEY()↓
◆Allow me to eat some Fly Honey for the last time...@KEY()↓
◆Master Belch hates people like you.@KEY()↓
◆...You see, those who don’t have ”Fly Honey” are our mortal enemies...
@KEY()
;jpn:◆おれを たおすんだったら‥‥@KEY()↓
;jpn:◆せめて@WI(30) しぬまえに↓
;jpn: 「はえみつ」を なめさせて↓
;jpn: ほしかったなぁ。@KEY()↓
;jpn:◆ゲップーさまは おまえみたいな↓
;jpn: やつが だいきらいなんだ。@KEY()↓
;jpn:◆‥‥つまり@WI(30)↓
;jpn: 「はえみつ」を↓
;jpn: もっていないような「てき」がな。@KEY()
@CLOSEALL()
』
_THRK_BOSS_GRAVE_DIE_HAVE;ハエミツあり
◆I wanted to get your Fly Honey and gulp it down.@KEY()↓
◆Master Belch and I love Fly Honey.@WI(20)↓
  Gyorg Gyorg!...
@KEY()
;jpn:◆せめて@WI(15) おまえの もっている↓
;jpn: 「はえみつ」を なめてから↓
;jpn: まけたかったなぁ。@KEY()↓
;jpn:◆おれとか ゲップーさまは↓
;jpn: 「はえみつ」が↓
;jpn: だーいすきなんだ音@KEY()↓
;jpn:◆グケッ@WI(10) グケー!@KEY()
@CLOSEALL()
』
;-------------------------------------------------

