;-----------------------------------------------------

;@Habitat:ドコドコ砂漠／ドラッグストア／ドラッグストア
;@Person:道具売り
;@Figure:サラリーマンD
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SHOP
MSG_DSRT_SHOP;@MiuraAppended
@GOSUB(MSG_SHOP_DSRT_DRUG)
』


;@Habitat:ドコドコ砂漠／ドラッグストア／ドラッグストア
;@Person:宿係
;@Figure:ジミな男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_MOTEL
MSG_DSRT_MOTEL;＠ポーラだったらマアム→松
◆Sir, we also have motel facilities.
;jpn:◆うちは やどやも↓
;jpn: やってるんですけどねぇ@WI(20)↓
;jpn: おきゃくさん。@KEY()
@GOSUB(MSG_GLOBAL_MYHOME)
』


;@Habitat:ドコドコ砂漠／ドラッグストア／ドラッグストア
;@Person:CD
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

；----------------------------------------
;@Habitat:ドコドコ砂漠／モッチーの家／モッチーの家
;@Person:宿泊係
;@Figure:しげちゃん
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_HOTEL
MSG_DSRT_HOTEL;砂漠のホテル機能の人
◆Thank you!@KEY()↓
◆It’s a small house, but please stay the night.
@KEY()

;jpn:◆おせわに なってます!@WI(10)↓
;jpn: とまってってください。@WI(20)↓
;jpn: ちっこい いえだけどさ。@KEY()
;夜にする
@GOSUB(MSG_SUB_SYUKUHAKU)
@GOSUB(MSG_SUB_SE_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_YADOYA_DSRT_SHIGE)
@CHKFGOTO(FLG_DSRT_DIA_RESERVE,_DSRT_HOTEL_SHIGE_DIA);ダイヤもらってなかったら
』
_DSRT_HOTEL_SHIGE_DIA;
@COLD_PLAYER(PC_ALL)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DSRT_HOTEL_SHIGE_ITEMFULL)
@OPEN(1)
◆Here, I’ll give you this now...for sure.
@KEY()↓
;jpn:◆では あらためて↓
;jpn: ‥‥これ たしかに わたします。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DSRT_HOTEL_SHIGE_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_DIAMOND)
@SETF(FLG_DSRT_ITEM_DIA)
@CLRF(FLG_DSRT_DIA_RESERVE);		ダイア後からもらえるフラグ
;@CLRF(FLG_FOUR_SHIGE)
@GOSUB(MSG_SUB_GETGOODS_S)@KEYNP()
@CLOSEALL()
@FRESH_PLAYER(PC_ALL)
』
_DSRT_HOTEL_SHIGE_ITEMFULL;
@OPEN(1)
◆Come on!  You haven’t got room again!@KEY()↓
◆Please take care of it right away.
@KEYNP()

;jpn:◆あれっ?! またまた↓
;jpn: にもつがいっぱいですね。@WI(20)↓
;jpn: なんとかしてくださいな。@KEYNP()
@CLOSEALL()
@FRESH_PLAYER(PC_ALL)
』
;----------------------------------------

;@Habitat:ドコドコ砂漠／フィールド／西の交通渋滞
;@Person:渋滞被害者A
;@Figure:OLC
;@AppearanceKey:FLG_DSRT_CLEAR/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_HIGHWAY_A
MSG_DSRT_HIGHWAY_A;
◆This traffic jam is taking forever.@KEY()↓
◆...Man, do I need to go...
@KEYNP()
;jpn:◆このじゅうたいは↓
;jpn: えいえんに つづきそうだわ。↓
;jpn: ‥‥ああ おしっこしたい。@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／西の交通渋滞
;@Person:渋滞被害者B
;@Figure:青年
;@AppearanceKey:FLG_DSRT_CLEAR/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_HIGHWAY_B
MSG_DSRT_HIGHWAY_B;
◆I heard that a little ways ahead a herd of buffalo is running across the road.@KEY()↓
◆I’m can’t move an inch!
@KEYNP()
;jpn:◆このさきのほうで↓
;jpn: バッファローのたいぐんが↓
;jpn: どうろを おうだんしてるらしい。@KEY()↓
;jpn:◆これじゃ すすめないよなぁ。@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／西の交通渋滞
;@Person:渋滞被害者C
;@Figure:リゾート男
;@AppearanceKey:FLG_DSRT_CLEAR/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_HIGHWAY_C
MSG_DSRT_HIGHWAY_C;
◆I feel sorry for the guys behind  me, but I’m so bent,@KEY()↓
◆I’m leaving my car here and walking instead!
@KEYNP()
;jpn:◆おいら うしろのやつらにゃ↓
;jpn: わるいけど↓
;jpn: クルマほっぽりだして@KEY()↓
;jpn:◆あるいてっちゃおうかって↓
;jpn: おもってるわけよ。↓
;jpn: イライラするぜー!@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／西の交通渋滞
;@Person:渋滞被害者D
;@Figure:ツッパリ
;@AppearanceKey:FLG_DSRT_CLEAR/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_HIGHWAY_D
MSG_DSRT_HIGHWAY_D;
◆I was going to see my girlfriend in Fourside...@KEY()↓
◆At this pace I’ll be a １００ years old by the time I get there!
@KEYNP()
;jpn:◆フォーサイドの かのじょに↓
;jpn: あいたくて はしってたのに↓
;jpn: このままじゃ‥‥@KEY()↓
;jpn:◆おれも かのじょも↓
;jpn: １００さいに なっちまうよォ!@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／ドラッグストア前
;@Person:電話
;@Figure:電話ボックス
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

;@Habitat:ドコドコ砂漠／フィールド／砂漠の西
;@Person:日光浴好きの男
;@Figure:寝ている男
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SUNTANMAN
MSG_DSRT_SUNTANMAN;
◆We sleep in the desert, so we’re often mistaken for corpses.@KEY()↓
◆But a corpse doesn’t usually wear a bathing suit, right?@KEY()↓
◆Hey, stop staring at my tan lines...Go away.
@KEYNP()
;jpn:◆おれたち さばくでねてるんで↓
;jpn: よく したいと↓
;jpn: まちがわれるんだよね。@KEY()↓
;jpn:◆でも したいって↓
;jpn: みずぎで ねてないだろ。@KEY()↓
;jpn:◆‥‥いつまでも こんなとこで↓
;jpn: ジロジロみてるなよ。↓
;jpn: あっち いけよ。@KEYNP()
;◆あっちのほうに なにか↓
; あなみたいなものが↓
; あるらしいから いってみれば?@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／砂漠の西
;@Person:日光浴好きの女
;@Figure:寝ている女
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SUNTANGAL
MSG_DSRT_SUNTANGAL;
◆Annoying kids...)↓
  What a group of brats!...@KEY()↓
◆Scat you little monsters!
@KEYNP()
;DAN:"Sh Sh" means you want someone to go away.  
	
;jpn:◆るさいわねー‥‥↓
;jpn: こどもがゾロゾロ‥‥↓
;jpn: しっ しっ!@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／砂漠の西ハイウェイの脇
;@Person:コンタクトの立て札
;@Figure:立札
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_DSRT_CHECK_CONTACTLENS
;@Message:0
MSG_DSRT_CHECK_CONTACTLENS;＃
◆(I lost a pair of contact lenses here in the Dusty Dunes Desert.@KEY()↓
◆They were a momento from my grandma, and very important to me.@KEY()↓
◆If you find them,  bring them to me and I’ll give you a reward.@KEY()↓
◆I’m Penetella Giovanni.@KEY()↓
◆Find me at the Fourside Bakery, second floor.)
;jpn:◆(このドコドコさばくで↓
;jpn: コンタクトレンズを↓
;jpn: おとしました。@KEY()↓
;jpn:◆おばあさんの かたみで↓
;jpn: とても たいせつにしていたもの↓
;jpn: なので@KEY()↓
;jpn:◆みつけて とどけてくださったら↓
;jpn: おれいを します。@KEY()↓
;jpn:◆フォーサイド パンやの２かい↓
;jpn: ペテネラ・ジョバンニ)
@CHKFGOTO(FLG_FOUR_PETENERA,_DSRT_CONTACTLENS_LATER)
@KEYNP()
』
_DSRT_CONTACTLENS_LATER;上に続けて
@KEY()↓
◆(Thank you, I found them.@KEY()↓
◆Thanks again for all your help.)
@KEYNP()
;jpn:◆(おかげさまで みつかりました。@WI(30)
;jpn: ごきょうりょく↓
;jpn: ありがとうございました)@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／モッチーの家の前
;@Person:ショージ・モッチー
;@Figure:ショージ・モッチー
;@AppearanceKey:FLG_DSRT_SYOZI_DISAPPEAR/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SYOZI_START
MSG_DSRT_SYOZI_START;
MSG_DSRT_SYOZI;
@CHKFGOTO(FLG_DSRT_DIA_RESERVE,_DSRT_SYOZI_DIA);ダイヤチュージモチ時
@CHKFGOTO(FLG_DSRT_ITEM_DIA,_DSRT_SYOZI_DIA)
@CHKFGOTO(FLG_WIN_DSRT_BOSS,_DSRT_SYOZI_2)
@CHKFGOTO(FLG_DSRT_SYOZI_1,_DSRT_SYOZI_LATER)
◆This hole’s great!@KEY()↓
◆Good hole, good hole, good hole...@KEY()↓
◆First, someone asked me to dig for buried gold.@KEY()↓
◆I began to feel like I was obligated to find it.@KEY()↓
◆Man, am I starving.@KEY()↓
◆Do you have any food you can spare?↓
;jpn:◆このあなは すげぇよ。@WI(20)↓
;jpn: いいあなだ。@KEY()↓
;jpn:◆もともと ひとにたのまれて↓
;jpn: ここで まいぞうきんを↓
;jpn: ほりはじめたんだけど‥‥@KEY()↓
;jpn:◆とちゅうから イジになってさ。@WI(20)↓
;jpn: なんとか みつけたいんだいね。@WI(30)↓
;jpn: はら へったなー。@KEY()↓
;jpn:◆なんか くいものを↓
;jpn: わけてくんないかい?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DSRT_SYOZI_YES,_DSRT_SYOZI_NO)

_DSRT_SYOZI_NO;
◆The humanitarian thing is to help people out when they’re hungry.@KEY()↓
◆Although I hate it, @DSP_GOODS(GDS_FOOD_PIZZA) would work for me...
;jpn:◆おたがいに はらへってるときに↓
;jpn: くいものを わけあうってのが↓
;jpn: ひとのみち じゃないのかねぇ。@KEY()↓
;jpn:◆おれ だいっきらいなんだけど↓
;jpn: ピザでも いいや。@WI(20)↓
;jpn: たのむよ。
@GOTO(_DSRT_SYOZI_END)

_DSRT_SYOZI_YES;
◆Seems like you have a lot of stuff.@KEY()↓
◆What are you gonna give me?

;jpn:◆いろいろもってる みてぇだけど↓
;jpn: どれを くれるんだい?
@KEY()
@DSP_PL()
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_DSRT_SYOZI_NO)		;キャンセル?
@SAVE_REG()				;主レ=PLAYER_ID:副レ=GOODSの位置を保存
@GET_PLAYER_GOODS(0,0)			;主レ=PLAYER_ID:副レ=GOODS_ID
@GOODS_TYPE_P(TYPE_EAT)			;グッズタイプチェック
@FALSE_GOTO(_DSRT_SYOZI_NOTFOOD)	;食べ物?
@LOAD_REG()				;主レ=PLAYER_ID:副レ=GOODSの位置
@GOODSOUT_PLAYER(0,0)			;グッズ削除。

_DSRT_SYOZI_SELECT_FOOD;
@SE(SE_se76_my_give)
◆Thank you.@KEY()↓
◆If I find the gold, I’ll give it to you.

;jpn:◆ありがとね。↓
;jpn: きんを めっけたら↓
;jpn: ぜんぶ あんたにやるからさ。
@KEYNP()
@SETF(FLG_DSRT_SYOZI_1)
@SETF(FLG_DSRT_SYOZI_DISAPPEAR)
@SETF(FLG_DSRT_SYOZI_DUNGEON_APPEAR)
@CHKFGOTO(FLG_FOUR_MISSFAKE,_DSRT_SYOZI_SWITCH)
@!
_DSRT_SYOZI_SWITCH;
@SETF(FLG_DSRT_SWITCH_BEFORE)
@!

_DSRT_SYOZI_NOTFOOD;
◆Come on! I can’t eat this!
;DAN:He has country side accent.

;jpn:◆こりゃあ くえねぇーべ。@KEY()↓
@!


_DSRT_SYOZI_LATER;
◆I’m still hard at work digging and digging.@KEY()↓
◆Hey, wait a second.

;jpn:◆いまも ガンガンほってるかんね。↓
;jpn: もう ちっと まっててくんない。
@GOTO(_DSRT_SYOZI_END)

_DSRT_SYOZI_2;@MiuraAppended
◆You’ve gotten rid of the monster?!@KEY()↓
◆Good job.@KEY()↓
◆Ok, from here on, just let me dig...@KEY()↓
◆You’ll see, I’ll find the buried gold!@KEY()↓
◆Before I start digging I’m going to set a careful plan of action...
@KEYNP()
;jpn:◆ばけもんを↓
;jpn: のしちまったって?!@WI(20)↓
;jpn: ごくろうさんだったねぇ。@KEY()↓
;jpn:◆よし!@WI(30) このさきは↓
;jpn: おれに まかしてくれ。@KEY()↓
;jpn:◆バーンと まいぞうきんを↓
;jpn: ほりあてて やるからさ!@KEY()↓
;jpn:◆じゃ おれ↓
;jpn: しごとのだんどりを きめてから↓
;jpn: はじめるからね。@KEYNP()
@SETF(FLG_DSRT_YUMBO_SHIGE_APPEAR)
;@GOTO(MSG_EVT_67_SYOZI);ユンボモチのイベントヤメ
@SETF(FLG_DSRT_SYOZI_DISAPPEAR);モッチー姿を消す
』

_DSRT_SYOZI_DIA;
◆If we could just find a diamond even...@KEY()↓
◆It’s a shame that a digger like me can’t find buried gold.@KEY()↓
◆I’ll try even harder.
;jpn:◆ダイヤしか でなかったんじゃ↓
;jpn: まいぞうきんほりとしちゃ↓
;jpn: あかっぱじ だかんね。@KEY()↓
;jpn:◆がんばってみますよ もっと。

_DSRT_SYOZI_END;
@KEYNP()
@!


;@Habitat:ドコドコ砂漠／フィールド／埋蔵金発掘現場
;@Person:見物人A
;@Figure:OLG
;@AppearanceKey:FLG_DSRT_SWITCH/on
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_A
MSG_DSRT_A;
@CHKFGOTO(FLG_DSRT_ITEM_DIA,MSG_DSRT_A_LATER)
◆I’ve been watching them dig for a while...@KEY()↓
◆I wonder what they’ll find.
@KEYNP()
;jpn:◆この あなほりを↓
;jpn: ずうっと みてるんだけど‥‥↓
;jpn: なんか でるのかしらねぇ。@KEYNP()
』

MSG_DSRT_A_LATER;
◆They only found a diamond...well, you take what you get...
@KEYNP()
;jpn:◆ダイヤがでてもねぇ‥‥。↓
;jpn: しょうがないんだよねぇ‥‥。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／埋蔵金発掘現場
;@Person:見物人B
;@Figure:少女A
;@AppearanceKey:FLG_DSRT_SWITCH/on
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_B
MSG_DSRT_B;
@CHKFGOTO(FLG_DSRT_ITEM_DIA,MSG_DSRT_A_LATER)
◆If they have a live broadcast, I can watch the dig while lying on the floor.
@KEYNP()
;jpn:◆テレビちゅうけいでも↓
;jpn: してくれたら ねころんで↓
;jpn: みてられるのにね。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／埋蔵金発掘現場
;@Person:見物人C
;@Figure:ツッパリ
;@AppearanceKey:FLG_DSRT_SWITCH/on
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_C
MSG_DSRT_C;
@CHKFGOTO(FLG_DSRT_ITEM_DIA,MSG_DSRT_A_LATER)
◆I think he should dig somewhere else.
@KEYNP()
;jpn:◆おれは もっとちがうところを↓
;jpn: ほるべきだと おもうんだよね。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／埋蔵金発掘現場
;@Person:見物人D
;@Figure:サラリーマンC
;@AppearanceKey:FLG_DSRT_SWITCH/on
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_D
MSG_DSRT_D;
@CHKFGOTO(FLG_DSRT_ITEM_DIA,MSG_DSRT_A_LATER)
◆I have lots of work to do, but I can’t seem to move.@KEY()↓
◆I’m so curious about the dig.@KEY()↓
◆I can’t help it.
@KEYNP()
;jpn:◆しごとが たまってるんだけど↓
;jpn: ここが きがかりで↓
;jpn: うごけないんだよ。@KEY()↓
;jpn:◆こまったもんだ。@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／ハイウェイ中央の脇
;@Person:スロットマシン
;@Figure:スロットマシン
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:
MSG_DSRT_SLOTMACHINE;
@GOSUB(MSG_DSRT_SLOTMAIN)			;←これを追加すべし
』

MSG_DSRT_SLOTMAIN;
@GET_ORDER_PLAYER(1)				;mainReg <- 先頭のplayer id
@GET_PLAYER_DIR(0,2,PRSN_DEST_FIELD_3B)		;スロットマシンへの向きcheck
@XCHG()
@SAVE_REG()
@EQ(1)					;main.reg == 5 then main.reg = 1
@TRUE_GOTO(_SLOTMACHINE_FRONT)
@LOAD_REG()
@EQ(2)
@TRUE_GOTO(_SLOTMACHINE_FRONT)
@LOAD_REG()
@EQ(8)
@TRUE_GOTO(_SLOTMACHINE_FRONT)
@GOTO(_SLOTMACHINE_NOT_FRONT)
_SLOTMACHINE_FRONT
;@GET_ORDER_PLAYER(1)
;@SET_REG(0)
◆(I’m a broken slot machine.@KEY()↓
◆But, the Sanchez Brothers and their friend are a very cheerful trio...@KEY()↓
◆they will make you happy.)@KEY()↓
;jpn:◆(ぼくは スロットマシンだ。↓
;jpn: ただし こわれている。@KEY()↓
;jpn:◆でもね‥‥ぼくのうしろにいる↓
;jpn: パンチョ ピンチョきょうだいと↓
;jpn: そのともだち‥‥@KEY()↓
;jpn:◆ようきな ３にんぐみが@KEY()↓
;jpn:◆きみ@GOSUB(MSG_SUB_TATI)を ハッピーにして↓
;jpn: くれるはずさ)@KEY()↓
;２回め以降
◆(Would you like to insert a buck?)↓
;jpn:◆(１ドル いれてみますか?)@KEY()↓
;はいいいえ
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_SLOT_START,_SLOT_CANCEL)
@GOTO(_SLOT_CANCEL)

_SLOT_START
@Q_MONEY(1)
@TRUE_GOTO(_SLOT_NOMONEY)
@WI(1)
@MONEYOUT(1)
@WINR_MONEY()
@GOSUB(MSG_SLOTBROS_ROTATE)
@!

_SLOT_CANCEL
◆(Okay...)
@KEYNP()
;jpn:◆(そうですか‥‥)@KEYNP()
@!
_SLOT_NOMONEY
◆(You have no money).
@KEYNP()
;jpn:◆(おかねを↓
;jpn: もっていませんでしたね)@KEYNP()
@!

;◆さばくの かざりだと↓
; おもってくれて かまわない。@KEY()↓
;◆よくぞ ここまで きてくれたね)@KEYNP()

_SLOTMACHINE_NOT_FRONT
◆(I’m a slot machine.@KEY()↓
◆Can you talk to me from the front side?)
@KEYNP()
;jpn:◆(ぼくは スロットマシンだ@KEY()↓
;jpn: わるいけど まえから↓
;jpn: はなしかけてくれないか)@KEYNP()
』
;◆しょうめんにきて↓
; きみのかおを ぼくに↓
; みせてくれないか)@KEYNP()
;@!

;-----------------------------------------------------slotbros 
MSG_SLOTBROS_ROTATE;
@CLOSEALL()					;message windowのclose
@WI(2)
@REMOVE_CHAR(PRSN_DEST_FIELD_L,ANIM_SLOTBROS_ROTATE_L)
@WI(2)
@REMOVE_CHAR(PRSN_DEST_FIELD_M,ANIM_SLOTBROS_ROTATE_M)
@WI(2)
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_ROTATE_N)
@WI(120)
@WI(120)

;-------------兄の停止と分岐
@REMOVE_CHAR(PRSN_DEST_FIELD_L,ANIM_SLOTBROS_STOP_L)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_ANI_1x)	;if(port0){
						;	goto ANI_1x;
						;}
_SLOTBROS_ANI_0x				;_ANI_0x
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_OTOTO_01)	;if(port1){
						;	goto _OTOTO_01;
@GOTO(_SLOTBROS_OTOTO_00)			;} else {
						;	goto _OTOTO_00;
						;}
_SLOTBROS_ANI_1x				;_ANI_1x
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_OTOTO_11)	;if(port1){
						;	goto _OTOTO_11;
@GOTO(_SLOTBROS_OTOTO_10)			;} else {
						;	goto _OTOTO_10;
						;}

;-------------弟の停止と分岐
_SLOTBROS_OTOTO_00				;_OTOTO_00
@REMOVE_CHAR(PRSN_DEST_FIELD_M,ANIM_SLOTBROS_STOP_M)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_HAZURE)	;if(port0){
						;	goto _HAZURE;
						;}
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_HAZURE)	;if(port1){
						;	goto _HAZURE;
						;}
@GOTO(_SLOTBROS_TOMO_00)			;goto _TOMO_00;

_SLOTBROS_OTOTO_01				;_OTOTO_01
@REMOVE_CHAR(PRSN_DEST_FIELD_M,ANIM_SLOTBROS_STOP_M)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_HAZURE)	;if(port0){
						;	goto _HAZURE;
						;}
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_TOMO_01)	;if(port1){
						;	goto _TOMO_01
						;}
@GOTO(_SLOTBROS_HAZURE)				;goto _HAZURE;

_SLOTBROS_OTOTO_10				;_OTOTO_10
@REMOVE_CHAR(PRSN_DEST_FIELD_M,ANIM_SLOTBROS_STOP_M)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_HAZURE)	;if(port1){
						;	goto _HAZURE;
						;}
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_TOMO_10)	;if(port0){
						;	goto _TOMO_10
						;}
@GOTO(_SLOTBROS_HAZURE)				;goto _HAZURE;

_SLOTBROS_OTOTO_11				;_OTOTO_11
@REMOVE_CHAR(PRSN_DEST_FIELD_M,ANIM_SLOTBROS_STOP_M)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_OTOTO_1x)	;if(port0){
						;	goto _OTOTO_1x;
						;}
@GOTO(_SLOTBROS_HAZURE)				;goto _HAZURE;
_SLOTBROS_OTOTO_1x				;_OTOTO_1x
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_TOMO_11)	;if(port1){
						;	goto _TOMO11;
						;}
@GOTO(_SLOTBROS_HAZURE)				;goto _HAZURE;

;-------------友の停止と分岐
_SLOTBROS_TOMO_00				;_TOMO_00
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_STOP_N_REACH)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_HAZURE_2)	;if(port0){
						;	goto _HAZURE_2;
						;}
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_HAZURE_2)	;if(port1){
						;	goto _HAZURE_2;
						;}
@GOTO(_SLOTBROS_ATARI_00)			;goto _ATARI_00;

_SLOTBROS_TOMO_01				;_TOMO_01
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_STOP_N_REACH)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_HAZURE_2)	;if(port0){
						;	goto _HAZURE_2;
						;}
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_ATARI_01)	;if(port1){
						;	goto _ATARI_01
						;}
@GOTO(_SLOTBROS_HAZURE_2)			;goto _HAZURE_2;

_SLOTBROS_TOMO_10				;_TOMO_10
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_STOP_N_REACH)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_HAZURE_2)	;if(port1){
						;	goto _HAZURE_2;
						;}
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_ATARI_10)	;if(port0){
						;	goto _ATARI_10;
						;}
@GOTO(_SLOTBROS_HAZURE_2)			;goto _HAZURE_2;

_SLOTBROS_TOMO_11				;_TOMO_11
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_STOP_N_REACH)
@WAITSYS()
@CHKFGOTO(FLG_ANIM_PORT_0,_SLOTBROS_TOMO_1x)	;if(port0){
						;	goto _TOMO_1x;
						;}
@GOTO(_SLOTBROS_HAZURE_2)			;goto _HAZURE_2;
_SLOTBROS_TOMO_1x				;_TOMO_1x
@CHKFGOTO(FLG_ANIM_PORT_1,_SLOTBROS_ATARI_11)	;if(port1){
						;	goto _ATARI_11;
						;}
@GOTO(_SLOTBROS_HAZURE_2)			;goto _HAZURE_2;

;-------------ゾロ目処理
_SLOTBROS_ATARI_00					;黄△	2等
@WI(120)
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_PRESENT)	;友、前に出る
@WAITSYS()
@COLD_CHAR(PRSN_DEST_FIELD_N)				;added
@OPEN(1)						;message win open
◆Amigo, you won a very big jackpot!@KEY()↓
◆Here’s a big prize for you, amigo!
@KEY()↓
;jpn:◆いちだいじでござるぜアミーゴ!↓
;jpn: すごい おおあたりでござるぜ↓
;jpn: セニョールセニョリータ!@KEY()↓
;jpn:◆かほうものの アミーゴに↓
;jpn: ビッグな みつぎものでござるぜ!@KEY()↓
;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SLOTBROS_ATARI_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_HIYOKO)	;このあたりは後でまっつんルーチンに差し替え
◆@GOSUB(MSG_ESUB_DSP_PARTY) won a @DSP_GOODS(GDS_TOOL_HIYOKO) as a prize.
@KEYNP()
;jpn:◆@DSP_LCNAME()は↓
;jpn: けいひんとして↓
;jpn: @DSP_GOODS(GDS_TOOL_HIYOKO)を もらった@KEYNP()↓
@SE(SE_se74_my_get)
@CLOSEALL()
@FRESH_CHAR(PRSN_DEST_FIELD_N)		;友、所定の位置に戻る
;@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_RETURN)	;友、所定の位置に戻る
@WAITSYS()
@GOTO(_SLOTBROS_EXIT)

_SLOTBROS_ATARI_01					;青<<	3等
@WI(120)
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_PRESENT)	;友、前に出る
@WAITSYS()
@COLD_CHAR(PRSN_DEST_FIELD_N)
@OPEN(1)						;message win open
;以下5linesが糸井さんoriginal(1,2,4等は2line目を少し変えました/上野)
◆Amigo, you won!@KEY()↓
◆A very big winning, I think!@KEY()↓
◆Here’s a very nice prize for the important amigo!
@KEY()↓
;jpn:◆いちだいじでござるぜアミーゴ!↓
;jpn: おおあたりでござるぜ↓
;jpn: セニョールセニョリータ!@KEY()↓
;jpn:◆かほうものの アミーゴに↓
;jpn: ビッグな みつぎものでござるぜ!@KEY()↓
;◆オーケー アミーゴ!↓
; すごい おおあたりだぜ↓
; セニョールセニョリータ!@KEY()↓
;◆ハッピーな あんたに↓
; これをプレゼントフォーユー@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SLOTBROS_ATARI_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_FOOD_SKIP_SAND)	;このあたりは後でまっつんルーチンに差し替え
◆@GOSUB(MSG_ESUB_DSP_PARTY) won a @DSP_GOODS(GDS_FOOD_SKIP_SAND) as a prize.
@KEYNP()

;jpn:◆@DSP_LCNAME()は↓
;jpn: けいひんとして↓
;jpn: @DSP_GOODS(GDS_FOOD_SKIP_SAND)を もらった@KEYNP()
@SE(SE_se74_my_get)
@CLOSEALL()
@FRESH_CHAR(PRSN_DEST_FIELD_N)
;@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_RETURN)	;友、所定の位置に戻る
@WAITSYS()
@GOTO(_SLOTBROS_EXIT)

_SLOTBROS_ATARI_10					;赤7	1等
@WI(120)
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_PRESENT)	;友、前に出る
@WAITSYS()
@COLD_CHAR(PRSN_DEST_FIELD_N)
@OPEN(1)						;message win open
◆Amigo, you won!@KEY()↓
◆A very big winning, and you hit it!@KEY()↓
◆Here’s the prize for the important amigo!
@KEY()↓
;jpn:◆いちだいじでござるぜアミーゴ!↓
;jpn: あらしのような↓
;jpn: おおあたりでござるぜ@KEY()↓
;jpn:◆かほうものの アミーゴに↓
;jpn: ビッグな みつぎものでござるぜ!@KEY()↓
;◆オーケー アミーゴ!↓
; ものすごい おおあたりだぜ↓
; セニョールセニョリータ!@KEY()↓
;◆ラッキーナイスな あんたに↓
; これをプレゼントフォーユー@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SLOTBROS_ATARI_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_FOOD_PSYCHO_CARAMEL)	;このあたりは後でまっつんルーチンに差し替え
◆@GOSUB(MSG_ESUB_DSP_PARTY) won a @DSP_GOODS(GDS_FOOD_PSYCHO_CARAMEL) as a prize.
@KEYNP()

;jpn:◆@DSP_LCNAME()は↓
;jpn: けいひんとして↓
;jpn: @DSP_GOODS(GDS_FOOD_PSYCHO_CARAMEL)を もらった@KEYNP()
@SE(SE_se74_my_get)
@CLOSEALL()
@FRESH_CHAR(PRSN_DEST_FIELD_N)
;@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_RETURN)	;友、所定の位置に戻る
@WAITSYS()
@GOTO(_SLOTBROS_EXIT)

_SLOTBROS_ATARI_11					;青>>	4等
@WI(120)
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_PRESENT)	;友、前に出る
@WAITSYS()
@COLD_CHAR(PRSN_DEST_FIELD_N)
@OPEN(1)						;message win open
◆Amigo, you won!@KEY()↓
◆A very big winning, my friend!@KEY()↓
◆Here’s the big prize for you!
@KEY()↓
;jpn:◆いちだいじでござるぜアミーゴ!↓
;jpn: おおあたりでござるぜ@KEY()↓
;jpn:◆かほうものの アミーゴに↓
;jpn: ビッグな みつぎものでござるぜ!@KEY()↓
;◆オーケー アミーゴ!↓
; ひるいなき おおあたりだ↓
; セニョールセニョリータ!@KEY()↓
;◆ハッピーナイスな あんたに↓
; これをプレゼントフォーユー@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SLOTBROS_ATARI_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_FOOD_JUICE_ORANGE)	;このあたりは後でまっつんルーチンに差し替え
◆@GOSUB(MSG_ESUB_DSP_PARTY) won a @DSP_GOODS(GDS_FOOD_JUICE_ORANGE) as a prize.
@KEYNP()
;jpn:◆@DSP_LCNAME()は↓
;jpn: けいひんとして↓
;jpn: @DSP_GOODS(GDS_FOOD_JUICE_ORANGE)を もらった。@KEYNP()
@SE(SE_se74_my_get)
@CLOSEALL()
@FRESH_CHAR(PRSN_DEST_FIELD_N)
;@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_RETURN)	;友、所定の位置に戻る
@WAITSYS()
@GOTO(_SLOTBROS_EXIT)

_SLOTBROS_ATARI_GOODSFULL;
←
◆That’s what I thought, but amigo, you have no more room.@KEY()↓
◆I’m sorry, but the deal’s off.@KEY()↓
◆Your pay off took the day off, amigo.
@KEYNP()
;jpn:◆と おもったが↓
;jpn: アミーゴは どうやら もちものが↓
;jpn: いっぱいのようでござるな。@KEY()↓
;jpn:◆すまぬが↓
;jpn: このはなしは なかったことに↓
;jpn: してくださらんか セニョール@KEY()↓
;jpn:◆かたじけナイチンゲール!!@KEYNP()
@CLOSEALL()
@FRESH_CHAR(PRSN_DEST_FIELD_N)
;@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_RETURN)	;友、所定の位置に戻る
@WAITSYS()
@GOTO(_SLOTBROS_EXIT)

;-------------ハズレ処理 (弟の時点でハズレ)
_SLOTBROS_HAZURE
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_SLOTBROS_STOP_N)	;友停止
@WAITSYS()
;-------------ハズレ処理2(友の時点でハズレ)
_SLOTBROS_HAZURE_2
;-------------SLOTBROS後始末
_SLOTBROS_EXIT
@WI(2)
@REMOVE_CHAR(PRSN_DEST_FIELD_L,ANIM_MAPOBJSTILL)
@WI(2)
@REMOVE_CHAR(PRSN_DEST_FIELD_M,ANIM_MAPOBJSTILL)
@WI(2)
@REMOVE_CHAR(PRSN_DEST_FIELD_N,ANIM_MAPOBJSTILL)
@!

;@Habitat:ドコドコ砂漠／フィールド／ハイウェイ中央の脇
;@Person:スロットBros.兄
;@Figure:スロットブラザース
;@AppearanceKey:0
;@ActionScript:◆スロット兄動き
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SLOTBROS_A
MSG_DSRT_SLOTBROS_A;@MiuraAppended
◆I’m big brother Pancho.
@KEYNP()
;jpn:◆あにのパンチョでーす。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／ハイウェイ中央の脇
;@Person:スロットBros.弟
;@Figure:スロットブラザース
;@AppearanceKey:0
;@ActionScript:◆スロット弟動き
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SLOTBROS_B
MSG_DSRT_SLOTBROS_B;@MiuraAppended
◆I’m kid brother Pincho.
@KEYNP()
;jpn:◆おとうとのピンチョでーす。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／ハイウェイ中央の脇
;@Person:スロットBros.友
;@Figure:スロットブラザース
;@AppearanceKey:0
;@ActionScript:◆スロット友だち動き
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_SLOTBROS_C
MSG_DSRT_SLOTBROS_C;@MiuraAppended
◆I’m Tomas Jefferson.
@KEYNP()
;jpn:◆ともだちの@WI(30)↓
;jpn: おおしおへいはちろうです。@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／砂漠中央付近
;@Person:うまのほね
;@Figure:骨
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_HORSEBONE
MSG_DSRT_HORSEBONE;
◆(...I’m just a pile of bleached bones. I can’t talk.)
@KEYNP()
;jpn:◆(‥‥おれは たんなる↓
;jpn: うまのほね だから↓
;jpn: しゃべらないよ)@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／砂漠中央付近
;@Person:うしのほね
;@Figure:骨
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_COWBONE
MSG_DSRT_COWBONE;
◆(Even though I’m just a pile of bones,@KEY()↓
◆I can talk and I’m lonely out here in the desert.)
@KEYNP()
;jpn:◆(うしのほね とはいえ↓
;jpn: さばくに ずっといるのは↓
;jpn: さみしいものだね)@KEYNP()
』

;@Habitat:ドコドコ砂漠／フィールド／砂漠中央付近
;@Person:くろゴマ
;@Figure:黒ゴマ
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_BLACKSESAME
MSG_DSRT_BLACKSESAME;
◆(Why would you feel like talking to a tiny black sesame like me.)@KEY()↓
◆(I wanna apologize to the white sesame that I hurt before.@KEY()↓
◆If I could just see her.)
;jpn:◆(よく こんなにちいさな↓
;jpn: くろゴマに はなしかけるきに↓
;jpn: なったものですね)@KEY()↓
;jpn:◆(むかし つめたくしたしろゴマに↓
;jpn: もしも あえたら あやまりたい)
@CHKFGOTO(FLG_DSRT_WHITESESAME,_DSRT_BLACKSESAME_1)
@KEYNP()
@CLOSEALL()
@SETF(FLG_DSRT_BLACKSESAME)
@CHKFGOTO(FLG_PHOTO_13,MSG_END)
@WI(60)
@GOSUB(MSG_GLOBAL_PHOTO_13);撮影
』

_DSRT_BLACKSESAME_1;
@KEY()↓
◆(What?@KEY()↓
◆The white sesame still...loves me?!@KEY()↓
◆Weep, weep...)
@KEYNP()
;jpn:◆(えっ@WI(20) しろゴマが‥‥まだ↓
;jpn: おれを すきだと?!↓
;jpn: ホロリ‥‥)@KEYNP()
@CLOSEALL()
@SETF(FLG_DSRT_BLACKSESAME)
@CHKFGOTO(FLG_PHOTO_13,MSG_END)
@WI(60)
@GOSUB(MSG_GLOBAL_PHOTO_13);撮影
』

;@Habitat:ドコドコ砂漠／フィールド／砂漠中央付近
;@Person:しろゴマ
;@Figure:白ゴマ
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_WHITESESAME
MSG_DSRT_WHITESESAME;
◆(I heard that the black sesame I used to love is somewhere in this desert.@KEY()↓
◆If you see him, please tell him that I still love him.)
;jpn:◆(むかし すきだったくろゴマが↓
;jpn: このさばくの どこかにいるって↓
;jpn: きいたんですが@KEY()↓
;jpn:◆もし あったら↓
;jpn: しろゴマは いまもすきよって↓
;jpn: つたえてね。)
@CHKFGOTO(FLG_DSRT_BLACKSESAME,_DSRT_WHITESESAME_1)
@SETF(FLG_DSRT_WHITESESAME)
@KEYNP()
』

_DSRT_WHITESESAME_1;
@KEY()↓
◆(Really?@KEY()↓
◆You’ve seen him already?@KEY()↓
◆Was he okay?@KEY()↓
◆...Hmmm, I see.)
@KEYNP()
;jpn:◆(えっ もう あった?!@WI(30)↓
;jpn: げんきでしたか@WI(30)↓
;jpn: ‥‥そうですか。)@KEYNP()
@SETF(FLG_DSRT_WHITESESAME)
;御褒美?
』

;@Habitat:ドコドコ砂漠／フィールド／砂漠中央付近
;@Person:コンタクトレンズ
;@Figure:光
;@AppearanceKey:0
;@ActionScript:◆その場でアニメーション
;@GoodsMessage:0
;@CheckMessage:MSG_DSRT_CONTACTLENS
;@Message:0
MSG_DSRT_CONTACTLENS;@MiuraAppended
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0) spotted something shiny.@KEY()↓
◆It was a set of contact lenses!
@KEY()↓
;jpn:◆@DSP_NAME(0)は ひかるものを↓
;jpn: チェックした。@KEY()↓
;jpn:◆コンタクトレンズをみつけた。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DSRT_CONTACTLENS_ITEMFULL)
@GOODSIN_PLAYER(PC_ALL,GDS_TOOL_CONTACT_LENS)
@HIDE_CHAR(PRSN_DEST_FIELD_4B,OBJFX_HIDE_NONE)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_ITEM_CONTACTLENS)
@KEYNP()
』

_DSRT_CONTACTLENS_ITEMFULL;
◆You have no more room.
@KEYNP()

;jpn:◆にもつが いっぱいで もてない。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／砂漠中央オアシス
;@Person:デザートモンキー
;@Figure:さる
;@AppearanceKey:0
;@ActionScript:◆せわしなくサル動き
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_MONKEY_A
MSG_DSRT_MONKEY_A;
;砂漠のサル
◆As sea monkeys live in the sea...desert monkeys live in the dessert.@KEY()↓
◆I mean desert, not dessert!@KEY()↓
◆I am happy that there are animals in the desert, aren’t you?
@KEYNP()
;jpn:◆うみに シーモンキーが↓
;jpn: いるように‥‥さばくには↓
;jpn: デザートモンキーがいるわけだ。@KEY()↓
;jpn:◆デザートっていっても↓
;jpn: しょくごのおかしじゃないぞ。↓
;jpn: 「さばく」って いみだ。@KEY()↓
;jpn:◆さばくで いきものにあうと↓
;jpn: ちょいと ほっとするよな。↓
;jpn: おたがいに な。@KEYNP()
』


;@Habitat:ドコドコ砂漠／フィールド／砂漠中央オアシス
;@Person:武器専門男
;@Figure:武器男
;@AppearanceKey:0
;@ActionScript:◆きょろきょろ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_WEAPON
MSG_DSRT_WEAPON;
@GOSUB(MSG_SHOP_DSRT_WEAPON)
』


;▼▲▼▲▼▲▼▲ ドコドコ砂漠 ▼▲▼▲▼▲▼▲

;^^^^^^^^ドコドコ砂漠：サルダンジョン^^^^^^^^

;@Habitat:ドコドコ砂漠／サルダンジョン／どこか
;@Person:タライ・ジャブ
;@Figure:タライジャブ
;@AppearanceKey:0
;@ActionScript:止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_TARAIJAB
MSG_DSRT_TARAIJAB;チベット僧(タライ・ジャブ)
;神秘的な僧。宗教的直感(?)によって、NESたちと
;世界のうんめいを(バクゼンと)知っている。
;チベットの人々というのは、みんなこんなふうなんじゃないか
;と思う私たちは、軽薄ですよね。
@CHKFGOTO(FLG_WIN_GIEGU,_DSRT_TARAIJAB_LATER)
@CHKFGOTO(FLG_DSRT_INFO_TLPT,_DSRT_TARAIJAB_AFTER);サル出て行った
@CHKFGOTO(FLG_ITEM_TOFU,_DSRT_TARAIJAB_MAIN)
@BGMSTART(0,BGM_home0);エデン序曲
◆The truth of space and time moves through the universe like a wave...@KEY()↓
◆Truth speaks through space and matter and makes itself known to human beings.@KEY()↓
◆I was waiting for you,@WI(15) and you came.@WI(20)  This was destined to happen.@KEY()↓
◆In truth, all is pre−determined...@KEY()↓
;jpn:◆うちゅうの しんりは↓
;jpn: つぶのように なみのように↓
;jpn: うちゅうを かけめぐり@KEY()↓
;jpn:◆ひと という うちゅうに↓
;jpn: かたりかけているものじゃ。@KEY()↓
;jpn
:◆あなたがたが ここにくること@WI(20)↓
;jpn: わたしが ここで まつこと‥‥@WI(30)↓
;jpn: すべて さだめられた しんり。@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_ALLHEAL_ONE)
@SE(SE_se25_b_healing)
@WI(20)
 @DSP_STS(STS_PC_NAME_PAULA)↓
@SET_LOOPREG(PC_PAULA)
@GOSUB(MSG_SUB_ALLHEAL_ONE)
@WI(20)
 @DSP_STS(STS_PC_NAME_JEFF)
@SET_LOOPREG(PC_JEFF)
@GOSUB(MSG_SUB_ALLHEAL_ONE)
@SE(SE_se25_b_healing)
@WI(20)
  and @DSP_STS(STS_PC_NAME_POO)@WI(30),@KEY()↓
◆when these four powers gather,@KEY()↓
◆twisted space will bring back peace to the world.@KEY()↓
◆Do you understand?↓
  It doesn’t matter.↓
  Proceed as you wish.@KEY()↓
◆Open the treasure box and take what is inside with you.@KEY()↓
;jpn: そして@DSP_STS(STS_PC_NAME_POO)@WI(30)↓
;jpn: ４つのちからが であうとき@KEY()↓
;jpn:◆ねじれようとしている↓
;jpn: うちゅうは‥‥やすらかな↓
;jpn: こきゅうを とりもどす。@KEY()↓
;jpn:◆わかるかね。@WI(30)↓
;jpn: わからんでも よい。@KEY()↓
;jpn:◆あなたがたの すきなように↓
;jpn: あゆんでゆけば それでよい。@KEY()↓
;jpn:◆たからばこを あけて↓
;jpn: じゆうに たからを↓
;jpn: もっていきなさい。@KEY()↓
@WI(60)↓
◆Did you come in search of this?@KEY()↓
◆...Someone left it behind in this hole.
;jpn:◆もしかすると↓
;jpn: これを さがしに きたのかな。@KEY()↓
;jpn:◆‥‥うっかりものが↓
;jpn: あなに おとしていきよったが。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DSRT_TARAIJAB_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_ICHIGO_TOFU)
@SETF(FLG_ITEM_TOFU)
@GOSUB(MSG_SUB_GETGOODS_S)
@KEY()↓
;↓
_DSRT_TARAIJAB_MAIN;
@OPEN(1)
◆The adventure that lies ahead won’t be easy.@KEY()↓
◆I’ll give you a special skill to help you move through space as you wish.@KEY()↓
◆Learn the skill from the monkey over there...@KEY()↓
◆would you like to learn this special power?↓
<Yes>
<No>
;jpn:◆ここから さきのたびも↓
;jpn: なみたいていの ものでは↓
;jpn: なかろう。@KEY()↓
;jpn:◆くうかんを じゆうに↓
;jpn: いどうする ちからを↓
;jpn: さずけてあげよう。@KEY()↓
;jpn:◆そこの サルに↓
;jpn: ならっていきなさい。@KEY()↓
;jpn:◆それとも そんなちからは↓
;jpn: いらないか?↓
;jpn:  <いる>  <いらない>
@DSP_ITEM(2)
@SELGOTO(_DSRT_TARAIJAB_MAIN_YES,_DSRT_TARAIJAB_MAIN_NO)
_DSRT_TARAIJAB_MAIN_NO;いらない
◆Ha ha ha.@KEY()↓
◆That’s one way.@KEY()↓
◆Be sure that you do not talk to the monkey, and go.
@KEYNP()
;jpn:◆ハッハッハ。@WI(20)↓
;jpn: それも ひとつの こたえだ。@KEY()↓
;jpn:◆あえて サルに はなしかけずに↓
;jpn: そのままいきなさい。@KEYNP()
@SETF( FLG_TEMP_1 )	;テレポート情報聞いた
@CLOSEALL()
;------------
@BGM_EFFECT(3)
@WI(20)
@MUSISTART()
;------------
』
_DSRT_TARAIJAB_MAIN_YES;
◆Ha ha ha.@KEY()↓
◆That’s wonderful!@KEY()↓
◆Speak to the monkey over there.
@KEYNP()
;jpn:◆ハッハッハ。@WI(20)↓
;jpn: それは そうじゃろう!@KEY()↓
;jpn:◆だったら そこにいる↓
;jpn: サルに はなしかけてごらん。@KEYNP()
@SETF( FLG_TEMP_1 )	;テレポート情報聞いた
@CLOSEALL()
;------------
@BGM_EFFECT(3)
@WI(20)
@MUSISTART()
;------------
』
_DSRT_TARAIJAB_GOODSFULL;
◆You cannot carry anything else.@KEY()↓
◆Why don’t you get rid of something you don’t need.@KEY()↓
◆You will need this, the Gourmet Yogurt Machine.
@KEYNP()
;jpn:◆にもつが いっぱいか。@WI(20)↓
;jpn: なにか いらないものを↓
;jpn: しまつして@KEY()↓
;jpn:◆この‥‥↓
; 「グルメとうふマシン」とやらを↓
;jpn: 「ぐるめとうふマシン」とやらを↓
;jpn: もっていきなさい。@KEYNP()
;------------
@BGM_EFFECT(3)
@WI(20)
@MUSISTART()
;------------
』

_DSRT_TARAIJAB_AFTER;＄
◆The truth of space and time moves through the universe like a wave...@KEY()↓
◆Truth speaks through space and matter and makes itself known to human beings.@KEY()↓
◆I was waiting for you,@WI(15) and you came.@WI(20)  This was destined to happen.@KEY()↓
◆In truth, all is pre−determined...@KEY()↓
@KEYNP()
;jpn:◆うちゅうの しんりは↓
;jpn: つぶのように なみのように↓
;jpn: うちゅうを かけめぐり@KEY()↓
;jpn:◆ひと という うちゅうに↓
;jpn: かたりかけているものじゃ。@KEY()↓
;jpn:◆あなたがたが ここにくること@WI(20)↓
;jpn: わたしが ここで まつこと‥‥@WI(30)↓
;jpn: すべて さだめられた しんり。@KEYNP()
』

_DSRT_TARAIJAB_LATER;＆
◆You’ve been exceedingly patient.@KEY()↓
◆You’ve overcome many hardships.@KEY()↓
◆I praise all of you for your courage.
@KEYNP()
;jpn:◆よくたえた。@KEY()↓
;jpn:◆よくのりこえた。@KEY()↓
;jpn:◆あなががたの ゆうきを↓
;jpn: たたえます。@KEYNP()
』

;▼▲▼▲▼▲▼▲ ドコドコ砂漠 ▼▲▼▲▼▲▼▲

;^^^^^^^^ドコドコ砂漠：モッチーダンジョン^^^^^^^^

;@Habitat:ドコドコ砂漠／モッチーダンジョン／入口付近
;@Person:ショージ・モッチー
;@Figure:ショージ・モッチー
;@AppearanceKey:FLG_DSRT_SYOZI_DUNGEON_APPEAR/on
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_DSRT_SYOZI_DUNGEON
MSG_DSRT_SYOZI_DUNGEON;
◆I didn’t have a problem digging until this...I found a maze.@KEY()↓
◆Lots of monsters appeared, so I couldn’t proceed.@KEY()↓
◆There’s ５ big moles...!@KEY()↓
◆If I beat the monsters, I can continue on.@KEY()↓
◆I think I have a bleeding ulcer from worrying too much.@KEY()↓
◆I’m helpless to really do anything.
@KEYNP()
;jpn:◆ここんとこまでは ラクショーで↓
;jpn: あなを ほってきてさ↓
;jpn: めいろを めっけたんだけどね。@KEY()↓
;jpn:◆ばーけもんが うーんとでてきて↓
;jpn: さきに すすめなく↓
;jpn: なっちまったんさね。@KEY()↓
;jpn:◆でっけー モグラが↓
;jpn: ‥‥どうやら ５ひきもいる!@KEY()↓
;jpn:◆ばけものさえ のしちまえば↓
;jpn: もっと さきまで↓
;jpn: すすめるんだいね。@KEY()↓
;jpn:◆おらぁ いが いてぇよ。↓
;jpn: なやんじまってさ。↓
;jpn: フー まいったいねぇ。@KEYNP()
』

;@Habitat:ドコドコ砂漠／モッチーダンジョン／1大迷路
;@Person:巨大モグラA
;@Figure:モグラ
;@AppearanceKey:FLG_WIN_DSRT_BOSS_A/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_DSRT_BOSS_A

MSG_DSRT_DSRT_BOSS_A;
@CHKFGOTO(FLG_WIN_DSRT_BOSS_A,MSG_SYS_HANASU_NG)
@GOSUB(_SUB_DSRT_BOSS_MESSAGE)
@GOSUB(MSG_BATTLE_DSRT_BOSS_A)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@GOSUB(_SUB_DSRT_BOSS_SETF)
@WI(1)
@REMOVE_CHAR(PRSN_DEST_MOCHY_1_B,ANIM_BLINK_SUICIDE)
@SETF(FLG_WIN_DSRT_BOSS_A)
@GOSUB(_SUB_DSRT_CHK_WIN_ALLBOSS)
』

;@Habitat:ドコドコ砂漠／モッチーダンジョン／1大迷路
;@Person:巨大モグラB
;@Figure:モグラ
;@AppearanceKey:FLG_WIN_DSRT_BOSS_B/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_DSRT_BOSS_B
MSG_DSRT_DSRT_BOSS_B;
@CHKFGOTO(FLG_WIN_DSRT_BOSS_B,MSG_SYS_HANASU_NG)
@GOSUB(_SUB_DSRT_BOSS_MESSAGE)
@GOSUB(MSG_BATTLE_DSRT_BOSS_B)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@GOSUB(_SUB_DSRT_BOSS_SETF)
@WI(1)
@REMOVE_CHAR(PRSN_DEST_MOCHY_1_C,ANIM_BLINK_SUICIDE)
@SETF(FLG_WIN_DSRT_BOSS_B)
@GOSUB(_SUB_DSRT_CHK_WIN_ALLBOSS)
』

;@Habitat:ドコドコ砂漠／モッチーダンジョン／1大迷路
;@Person:巨大モグラC
;@Figure:モグラ
;@AppearanceKey:FLG_WIN_DSRT_BOSS_C/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_DSRT_BOSS_C
MSG_DSRT_DSRT_BOSS_C;
@CHKFGOTO(FLG_WIN_DSRT_BOSS_C,MSG_SYS_HANASU_NG)
@GOSUB(_SUB_DSRT_BOSS_MESSAGE)
@GOSUB(MSG_BATTLE_DSRT_BOSS_C)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@GOSUB(_SUB_DSRT_BOSS_SETF)
@WI(1)
@REMOVE_CHAR(PRSN_DEST_MOCHY_1_D,ANIM_BLINK_SUICIDE)
@SETF(FLG_WIN_DSRT_BOSS_C)
@GOSUB(_SUB_DSRT_CHK_WIN_ALLBOSS)
』

;@Habitat:ドコドコ砂漠／モッチーダンジョン／2小迷路
;@Person:巨大モグラD
;@Figure:モグラ
;@AppearanceKey:FLG_WIN_DSRT_BOSS_D/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_DSRT_BOSS_D
MSG_DSRT_DSRT_BOSS_D;
@CHKFGOTO(FLG_WIN_DSRT_BOSS_D,MSG_SYS_HANASU_NG)
@GOSUB(_SUB_DSRT_BOSS_MESSAGE)
@GOSUB(MSG_BATTLE_DSRT_BOSS_D)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@GOSUB(_SUB_DSRT_BOSS_SETF)
@WI(1)
@REMOVE_CHAR(PRSN_DEST_MOCHY_2_A,ANIM_BLINK_SUICIDE)
@SETF(FLG_WIN_DSRT_BOSS_D)
@GOSUB(_SUB_DSRT_CHK_WIN_ALLBOSS)
』

;@Habitat:ドコドコ砂漠／モッチーダンジョン／3中迷路
;@Person:巨大モグラE
;@Figure:モグラ
;@AppearanceKey:FLG_WIN_DSRT_BOSS_E/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DSRT_DSRT_BOSS_E
MSG_DSRT_DSRT_BOSS_E;
@CHKFGOTO(FLG_WIN_DSRT_BOSS_E,MSG_SYS_HANASU_NG)
@GOSUB(_SUB_DSRT_BOSS_MESSAGE)
@GOSUB(MSG_BATTLE_DSRT_BOSS_E)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@GOSUB(_SUB_DSRT_BOSS_SETF)
@WI(1)
@REMOVE_CHAR(PRSN_DEST_MOCHY_3_A,ANIM_BLINK_SUICIDE)
@SETF(FLG_WIN_DSRT_BOSS_E)
@GOSUB(_SUB_DSRT_CHK_WIN_ALLBOSS)
』

_SUB_DSRT_BOSS_MESSAGE;
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
@CHKFGOTO(FLG_DSRT_BOSS_4,_DSRT_BOSS_MESS_5)
@CHKFGOTO(FLG_DSRT_BOSS_3,_DSRT_BOSS_MESS_4)
@CHKFGOTO(FLG_DSRT_BOSS_2,_DSRT_BOSS_MESS_3)
@CHKFGOTO(FLG_DSRT_BOSS_1,_DSRT_BOSS_MESS_2)
_DSRT_BOSS_MESS_1;
@OPEN(1)
◆I’m one of the masters of this hole.@KEY()↓
◆There are five masters in all.@WI(20)  We are all moles, of course.@KEY()↓
◆I believe I’m the third strongest amongst us.@KEY()↓
◆Take your best shot!
;jpn:◆おれは↓
;jpn: このあなの↓
;jpn: ぬしだ。@KEY()↓
;jpn:◆このあなには↓
;jpn: ５にんの↓
;jpn: ぬしがいる。@KEY()↓
;jpn:◆５にんといっても↓
;jpn: もぐらだから@KEY()↓
;jpn:◆せいかくには↓
;jpn: ５ひきだ。@KEY()↓
;jpn:◆おれがおもうには↓
;jpn: おれは そのうちで↓
;jpn: ３ばんめに つよい。@KEY()↓
;jpn:◆どこからでも↓
;jpn: かかってこい!
@KEY()
@CLOSEALL()
@!
_DSRT_BOSS_MESS_2;
@OPEN(1)
◆I’m really the third strongest master.@KEY()↓
◆I’ll destroy you now!@KEY()
;jpn:◆おれが ほんとうに↓
;jpn: ３ばんめに つよい↓
;jpn: このあなのぬしだ。@KEY()↓
;jpn:◆しょうぶしてやる!@KEY()
@CLOSEALL()
@!
_DSRT_BOSS_MESS_3;
@OPEN(1)
◆My strength falls between the second and fourth strongest masters.@KEY()↓
◆Do you wanna test me?@KEY()↓
;jpn:◆おれは↓
;jpn: ２ばんめにつよい↓
;jpn: あなのぬしより よわいが@KEY()↓
;jpn:◆４ばんめのやつより
;jpn: つよい。@KEY()↓
;jpn:◆おれの うでを↓
;jpn: ためしてみるか?@KEY()↓
;jpn:◆こい!@KEY()
@CLOSEALL()
@!
_DSRT_BOSS_MESS_4;
@OPEN(1)
◆I’m truly the third strongest master of this hole.@KEY()↓
◆I’ll demonstrate the power of being third to you!
@KEY()
;jpn:◆おれが↓
;jpn: しょうしんしょうめいの@KEY()↓
;jpn:◆ナンバースリーの↓
;jpn: このあなのぬしだ。@KEY()↓
;jpn:◆ほんものの↓
;jpn: ちゅうくらいの つよさを↓
;jpn: みせてやる!@KEY()
@CLOSEALL()
@!
_DSRT_BOSS_MESS_5;
@OPEN(1)
◆Ha ha ha.@KEY()↓
◆You’ve fought the strongest master of this hole,@KEY()↓
◆the second strongest master of this hole,@KEY()↓
◆the fourth strongest master of this hole,@KEY()↓
◆and the weakest master of this hole!@KEY()↓
◆I’m truly the third strongest master of this hole.@KEY()↓
◆Now you see the true advantage of being third!
@KEY()
;jpn:◆ふっふっふ。@KEY()↓
;jpn:◆おまえは いままでに↓
;jpn: １ばんつよい↓
;jpn: このあなのぬしと@KEY()↓
;jpn:◆２ばんめに つよい↓
;jpn: このあなのぬしと@KEY()↓
;jpn:◆４ばんめにつよい↓
;jpn: このあなのぬしと@KEY()↓
;jpn:◆１ばんよわい↓
;jpn: このあなのぬしと↓
;jpn: たたかったはずだ!@KEY()↓
;jpn:◆おれが!@KEY()↓
;jpn:◆おれが!@KEY()↓
;jpn:◆しんの↓
;jpn: ３ばんめにつよい↓
;jpn: このあなのぬしなのだ!@KEY()↓
;jpn:◆いくぞ!@KEY()
@CLOSEALL()
@!

_SUB_DSRT_CHK_WIN_ALLBOSS;
@CHKF(FLG_WIN_DSRT_BOSS_A)@FALSE_GOTO(_CHK_WIN_ALLBOSS_END)
@CHKF(FLG_WIN_DSRT_BOSS_B)@FALSE_GOTO(_CHK_WIN_ALLBOSS_END)
@CHKF(FLG_WIN_DSRT_BOSS_C)@FALSE_GOTO(_CHK_WIN_ALLBOSS_END)
@CHKF(FLG_WIN_DSRT_BOSS_D)@FALSE_GOTO(_CHK_WIN_ALLBOSS_END)
@CHKF(FLG_WIN_DSRT_BOSS_E)@FALSE_GOTO(_CHK_WIN_ALLBOSS_END)
@SETF(FLG_DSRT_DUNGEON_OK)
@SETF(FLG_WIN_DSRT_BOSS);モッチーのセリフ替え
@GOSUB(MSG_SUB_BGM_CHANGE_2)
@CLRF(FLG_DSRT_SYOZI_DUNGEON_APPEAR)
@CLRF(FLG_DSRT_SYOZI_DISAPPEAR)
@SETF(FLG_PHOTO_EXCAVATION);撮り頃フラグ
_CHK_WIN_ALLBOSS_END;
@!
_SUB_DSRT_BOSS_SETF;
@CHKFGOTO(FLG_DSRT_BOSS_4,_DSRT_BOSS_SETF_5)
@CHKFGOTO(FLG_DSRT_BOSS_3,_DSRT_BOSS_SETF_4)
@CHKFGOTO(FLG_DSRT_BOSS_2,_DSRT_BOSS_SETF_3)
@CHKFGOTO(FLG_DSRT_BOSS_1,_DSRT_BOSS_SETF_2)
_DSRT_BOSS_SETF_1;
@SETF(FLG_DSRT_BOSS_1)
@!
_DSRT_BOSS_SETF_2;
@SETF(FLG_DSRT_BOSS_2)
@!
_DSRT_BOSS_SETF_3;
@SETF(FLG_DSRT_BOSS_3)
@!
_DSRT_BOSS_SETF_4;
@SETF(FLG_DSRT_BOSS_4)
@!
_DSRT_BOSS_SETF_5;
@!

;▼部屋１(右のさる)▼▼▼▼▼▼▼▼(スキップサンド)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_A;
@CHKFGOTO(FLG_SARUDUNGEON_A_OK,_SARUD_A_AFTER)
◆Ukippkyako Ukikiki?@KEY()↓
◆(Do you have↓
  a @DSP_GOODS(GDS_FOOD_SKIP_SAND)?)@KEY()↓
◆Ukii Ukieki...@KEY()↓
◆(I’ll move away if yo give me one.)@KEY()↓
◆Ukiki?@KEY()↓
◆(Can you give me one?)↓
;jpn:◆ウキップキャコ ウキキッキ?↓
;jpn:(スキップサンド もってるか?)@KEY()↓
;jpn:◆ウキー ウキキ‥‥↓
;jpn:(ひとつ くれたら↓
;jpn: どいてやるけど‥‥)@KEY()↓
;jpn:◆ウキ〜?↓
;jpn:(くれるか?)↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_A_YES,_SARUD_A_NO)
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「スキップサンド」以外を選ぶと〕
_SARUD_A_NO;
◆Uki, Ukyakikya@KEY()↓
◆(I won’t  move.)
@KEYNP()
;jpn:◆ウキ ウキャキキャ↓
;jpn:(おれ どかない)@KEYNP()
』
_SARUD_A_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_A_NO)
@SAVE_REG()
@GOSUB(_SARUD_Q_SKIP)
@FALSE_GOTO(_SARUD_A_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「スキップサンド」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Ukippu Kyako!@KEY()↓
◆(A @DSP_GOODS(GDS_FOOD_SKIP_SAND)!)
@KEYNP()
;jpn:◆ウキップキャコ!↓
;jpn:(スキップサンド!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_2_B,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_2_D,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_A_OK)
』
;D〔移動後に話すと〕
_SARUD_A_AFTER;
◆Ukki.@KEY()↓
◆(Lucky.)
@KEYNP()
;jpn:◆ウッキー↓
;jpn:(ラッキー)
@KEYNP()
』
;▼部屋１(左のさる)▼▼▼▼▼▼▼▼(えんそくランチ)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_B;
@CHKFGOTO(FLG_SARUDUNGEON_B_OK,_SARUD_B_AFTER)
◆Kikiki Kiki!@KEY()↓
◆(I wanna eat a @DSP_GOODS(GDS_FOOD_LUNCH)!)@KEY()↓
◆Kikiki Kiki@KEY()↓
◆(If you grant my wish, I might open the entrance.)@KEY()↓
◆Kikiki Kiki?@KEY()↓
◆(Will you give me a @DSP_GOODS(GDS_FOOD_LUNCH)?)↓
;jpn:◆キッキッキッ キキッ!↓
;jpn:(えんそくランチ たべたい!)@KEY()↓
;jpn:◆キッキッキッ キキッ↓
;jpn:(のぞみを かなえてくれたら↓
;jpn: いりぐち あけてあげようかな)@KEY()↓
;jpn:◆キッキッキッ キキッ?↓
;jpn:(えんそくランチ くれる?)↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_B_YES,_SARUD_B_NO)
_SARUD_B_NO;
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「クッキー」以外を選ぶと〕
◆Kikiki Kiki!@KEY()↓
◆(I wanna eat a @DSP_GOODS(GDS_FOOD_LUNCH)!)
@KEYNP()
;jpn:◆キッキッキッ キキッ!↓
;jpn:(えんそくランチ たべたい!)@KEYNP()
』
_SARUD_B_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_B_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_FOOD_LUNCH)
@FALSE_GOTO(_SARUD_B_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「えんそくランチ」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Kikie!@KEY()↓
◆(Great!)
@KEYNP()
;jpn:◆キキー!↓
;jpn:(やったー!)
;@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_2_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_2_C,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_B_OK)
』
;D〔移動後に話すと〕
_SARUD_B_AFTER;
◆Kikki@KEY()↓
◆(Hee he he)
@KEYNP()
;jpn:◆キッキ↓
;jpn:(えへへ)
;@KEYNP()
』
;▼部屋２(右のさる)▼▼▼▼▼▼▼▼(ぬれタオル)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_C;
@CHKFGOTO(FLG_SARUDUNGEON_C_OK,_SARUD_C_AFTER)
◆Uki Ukikie@KEY()↓
◆(Doesn’t it feel hot in here?  My fur’s all sweaty!)@KEY()↓
◆Ukie Kikukie@KEY()↓
◆(Maybe you don’t usually keep a @DSP_GOODS(GDS_TOOL_WET_TOWEL), but )@KEY()↓
◆Ukke Ukiki Ukkikie?@KEY()↓
◆(if you have one, will you share it with me?)↓
;jpn:◆ウキー ウキキー↓
;jpn:(なんか むしますよねえ)@KEY()↓
;jpn:◆ウキキー ウキー↓
;jpn:(ぬれタオルなんて ふつう↓
;jpn: もってないとおもいますけども)@KEY()↓
;jpn:◆ウキー ウキキ ウキキー?↓
;jpn:(もし もってたらば↓
;jpn: ゆずってもらえませんかあ?)@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_C_YES,_SARUD_C_NO)
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ぬれタオル」以外を選ぶと〕
_SARUD_C_NO;松(メッセージなし)
◆Ukie Ukie Ukikie
	(Any way, it is humid in here.)

;jpn:◆ウキー ウキー ウキキー↓
;jpn:(いやはや それにしても↓
;jpn: ここは むしますよねえ)
@KEYNP()
』
_SARUD_C_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_C_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_WET_TOWEL)
@FALSE_GOTO(_SARUD_C_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ぬれタオル」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Ukokkie?  Ukike?@KEY()↓
◆(Do you have one?@KEY()↓
◆Thank you!)
@KEYNP()
;jpn:◆ウキキー? ウキキー!↓
;jpn:(もってたんですかあ?↓
;jpn: ありがとうございますう!)
;@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_4_B,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_4_D,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_C_OK)
』
;D〔移動後に話すと〕
_SARUD_C_AFTER;
◆Ukri Ukrikie@KEY()↓
◆(It’s humid here.)
;jpn:◆ウキー ウキキー↓
;jpn:(とにかく ここは↓
;jpn: むしますよねえ)
@KEYNP()
』
;▼部屋２(左のさる)▼▼▼▼▼▼▼▼(ピザ・ピザ(Lサイズ))
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_D;
@CHKFGOTO(FLG_SARUDUNGEON_D_OK,_SARUD_D_AFTER)
◆Ukkkin Uki Uki Ukkin@KEY()↓
◆(Oooooooo..., I’m Monkonna.@KEY()↓
◆I wanna eat a tasty @DSP_GOODS(GDS_FOOD_PIZZA).)↓
◆Ukkyou kikinkyou@KEY()↓
  (If you have some, will you give it to me?)
;◆Ukkkin Uki Uki Ukkin
;	(Uffun I’m Sarudonna.
;  I wanna eat tasty pizza.)
;DAN:As you know, saru is monkey. So, 
;Sarudonna is a combined words of Saru and 
;Madonna.
;◆Ukkin Uun?
;	(If you have one, can you give me?)
;jpn:◆ウッキン ウキウキウッキン↓
;jpn:(うっふん わたし サルドンナ。↓
;jpn: おいしいピザ たべたいわん)@KEY()↓
;jpn:◆ウッキン ウ〜ン?↓
;jpn:(もってたら ちょうだ〜い?)↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_D_YES,_SARUD_D_NO)
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ピザ・ピザ(Lサイズ)」以外を選ぶと〕
_SARUD_D_NO;
◆Uki Ukiekkiki!@KEY()↓
◆(You useless monkey hater!)
;jpn:◆ウキ ウキキキキ!↓
;jpn:(この さるでなし!)
@KEYNP()
』
_SARUD_D_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_D_NO)
@SAVE_REG()
@GOSUB(_SARUD_Q_PIZZA)
@FALSE_GOTO(_SARUD_D_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ピザ・ピザ(Lサイズ)」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Ukkin Ukkikeen@KEY()↓
◆(Hah, Monkonna’s happy.)
;jpn:◆ウッキ〜ン ウッキッキ〜ン↓
;jpn:(いっや〜ん↓
;jpn: サルドンナ うれし〜ん)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_4_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_4_C,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_D_OK)
』
;D〔移動後に話すと〕
_SARUD_D_AFTER;
◆Ukkien@KEY()↓
◆(Oooooooo...)
;jpn:◆ウッキ〜ン↓
;jpn:(うっふ〜ん)
@KEYNP()
』
;▼部屋３(右のさる)▼▼▼▼▼▼▼▼(おとなのドリンク)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_E;
@CHKFGOTO(FLG_SARUDUNGEON_E_OK,_SARUD_E_AFTER)
◆Ukyakki KyaKye@KEY()↓
◆(I’d like to have an @DSP_GOODS(GDS_FOOD_DRINK_ADULT).)@KEY()↓
◆Kya Kya?@KEY()↓
◆(Can you give me one?)↓
;jpn:◆キャッキャッ キャキャッ↓
;jpn:(のんでみたいな↓
;jpn: おとなのドリンク)@KEY()↓
;jpn:◆キャッキャッ?↓
;jpn:(ぼくに ちょうだい?)↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_E_YES,_SARUD_E_NO)
_SARUD_E_NO;
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「おとなのドリンク」以外を選ぶと〕
◆KyaKya Kyokyokyo?@KEY()↓
◆(’Cause I’m still a kid?)
;jpn:◆キャキャッ キョキョキョ?↓
;jpn:(ぼくが こどもだから?)
@KEYNP()
』
_SARUD_E_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_E_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_FOOD_DRINK_ADULT)
@FALSE_GOTO(_SARUD_E_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「おとなのドリンク」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Gulp, gulp...Bliekki!@KEY()↓
◆(Gulp, gulp...Bliekki!)
;jpn:◆ぐびぐび@WI(20)‥‥キョケー!@WI(20)↓
;jpn:(ぐびぐび@WI(20)‥‥キョケー!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_C_B,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_C_D,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_E_OK)
』
;D〔移動後に話すと〕
_SARUD_E_AFTER;
◆Kya Kya@KEY()↓
◆(Kya Kya)
;jpn:◆キャッキャッ↓
;jpn:(きゃっきゃっ)
@KEYNP()
』
;▼部屋３(左のさる)▼▼▼▼▼▼▼▼(ピザ・ピザ(Lサイズ))
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_F;
@CHKFGOTO(FLG_SARUDUNGEON_F_OK,_SARUD_F_AFTER)
◆If you have a @DSP_GOODS(GDS_FOOD_PIZZA), please give me one.@KEY()↓
◆...Ukiki Ukkike@KEY()↓
◆(...Woops, I spoke to you in the human’s language.)@KEY()↓
◆Ukiki Ukkike@KEY()↓
◆(If you have a @DSP_GOODS(GDS_FOOD_PIZZA), please give me one.)↓
;jpn:◆ピザもってたら ちょうだい。@KEY()↓
;jpn:◆‥‥ウキッキ ウキウキ キキ↓
;jpn:(‥‥しまった にんげんの↓
;jpn: ことばで しゃべっちゃった)@KEY()↓
;jpn:◆ウキキ ウッキッキー↓
;jpn:(ピザもってたら ちょうだい)↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_F_YES,_SARUD_F_NO)
_SARUD_F_NO;
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ピザ・ピザ(Lサイズ)」以外を選ぶと〕
◆Kye...@KEY()↓
◆(Darn...)
;jpn:◆キェッ‥‥↓
;jpn:(ちぇっ‥‥)
@KEYNP()
』
_SARUD_F_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_F_NO)
@SAVE_REG()
@GOSUB(_SARUD_Q_PIZZA)
@FALSE_GOTO(_SARUD_F_NO)
_SARUD_F_YES_B;
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ピザ・ピザ(Lサイズ)」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Ukki Ukikii!@KEY()↓
◆(Great, pizza time!)
;jpn:◆ウッキ ウキッキー!↓
;jpn:(やったぞ ピザだ!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_C_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_C_C,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_F_OK)
』
;D〔移動後に話すと〕
_SARUD_F_AFTER;
◆Thank you.@KEY()↓
◆...Kie ukkya@KEY()↓
◆(...crap, I used the human’s language again.)
;jpn:◆どうも。@KEY()↓
;jpn:◆‥‥ウキッキ ウキウキ キキ↓
;jpn:(‥‥しまった にんげんの↓
;jpn: ことばで しゃべっちゃった)
@KEYNP()
』
;▼部屋５(右のさる)▼▼▼▼▼▼▼▼(ハンバーガー・ダブルバーガー)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_G;
@CHKFGOTO(FLG_SARUDUNGEON_G_OK,_SARUD_G_AFTER)
◆Unkikie!  Uukiuki!@KEY()↓
◆(I love hamburgers!)@KEY()↓
◆Ukie Unkikie...@KEY()↓
◆(The monkey next to me loves hamburgers too...)@KEY()↓
◆Uuu.  Unkikkie Uki?@KEY()↓
◆(If you have a @DSP_GOODS(GDS_FOOD_HAMBURGER), will you please give it to me?)↓
;jpn:◆ウンキッキー ウーキウキ!↓
;jpn:(ハンバーガー だーいすき!)@KEY()↓
;jpn:◆ウキー ウンキッキー‥‥↓
;jpn:(となりの おさるも↓
;jpn: ハンバーガー すきみたい‥‥)@KEY()↓
;jpn:◆ウー ウンキッキー ウキ?↓
;jpn:(ねえ ハンバーガーもってたら↓
;jpn: ぼくだけに ちょうだい?)@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_G_YES,_SARUD_G_NO)
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ハンバーガー・ダブルバーガー」以外を選ぶと〕
_SARUD_G_NO;
◆...@KEY()↓
◆(...)
;jpn:◆‥‥‥‥↓
;jpn:(‥‥‥‥)
@KEYNP()
』
_SARUD_G_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_G_NO)
@SAVE_REG()
@GOSUB(_SARUD_Q_HAMBERGER)
@FALSE_GOTO(_SARUD_G_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ハンバーガー・ダブルバーガー」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Unkikie!@KEY()↓
◆(@DSP_GOODS(GDS_FOOD_HAMBURGER)!)
;jpn:◆ウンキッキー!↓
;jpn:(ハンバーガー!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_8_B,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_8_D,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_G_OK)
』
;D〔移動後に話すと〕
_SARUD_G_AFTER;
◆Uki Unkinki Ukinkie@KEY()↓
◆(Truth is, the monkey next to me is my twin brother.)
;jpn:◆ウキ ウッキンキ ウキンキー↓
;jpn:(じつは となりのおさるとは↓
;jpn: ふたごのかんけいなんだ)
@KEYNP()
』
;▼部屋５(左のさる)▼▼▼▼▼▼▼▼(ハンバーガー・ダブルバーガー)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_H;
@CHKFGOTO(FLG_SARUDUNGEON_H_OK,_SARUD_H_AFTER)
◆Unkikkie Uuki Uki!@KEY()↓
◆(I love hamburgers!)@KEY()↓
◆Ukie Unkikie...@KEY()↓
◆(The monkey next to me loves hamburgers too...)@KEY()↓
◆Uuu.  Unkikkie Uki?@KEY()↓
◆(If you have a @DSP_GOODS(GDS_FOOD_HAMBURGER), will you please give it to me?)↓
;jpn:◆ウンキッキー ウーキウキ!↓
;jpn:(ハンバーガー だーいすき!)@KEY()↓
;jpn:◆ウキー ウンキッキー‥‥↓
;jpn:(となりの おさるも↓
;jpn: ハンバーガー すきみたい‥‥)@KEY()↓
;jpn:◆ウー ウンキッキー ウキ?↓
;jpn:(ねえ ハンバーガーもってたら↓
;jpn: ぼくだけに ちょうだい?)@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_H_YES,_SARUD_H_NO)
_SARUD_H_NO;
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ハンバーガー・ダブルバーガー」以外を選ぶと〕
◆.....@KEY()↓
◆(.....)

;jpn:◆‥‥‥‥↓
;jpn:(‥‥‥‥)
@KEYNP()
』
_SARUD_H_YES
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_H_NO)
@SAVE_REG()
@GOSUB(_SARUD_Q_HAMBERGER)
@FALSE_GOTO(_SARUD_H_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ハンバーガー・ダブルバーガー」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Unkikkie!@KEY()↓
◆(@DSP_GOODS(GDS_FOOD_HAMBURGER)!)

;jpn:◆ウンキッキー!↓
;jpn:(ハンバーガー!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_8_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_8_C,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_H_OK)
』
;D〔移動後に話すと〕
_SARUD_H_AFTER;
◆Uki Ukkinki Ukinkie@KEY()↓
◆(The monkey next to me is my twin brother.)

;jpn:◆ウキ ウッキンキ ウキンキー↓
;jpn:(じつは となりのおさるとは↓
;jpn: ふたごのかんけいなんだ)
@KEYNP()
』
;▼部屋６(右のさる)▼▼▼▼▼▼▼▼(キングバナナ)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_I;
@CHKFGOTO(FLG_SARUDUNGEON_I_OK,_SARUD_I_AFTER)
◆Ukie Ukikikie@KEY()↓
◆(I am Man K. Man.)@KEY()↓
◆Ukie Ukikikie@KEY()↓
◆(To me the most interesting thing is the @DSP_GOODS(GDS_TOOL_DRY_MEAT_SPECIAL).)@KEY()↓
◆Ukie Ukikikie@KEY()↓
◆(What?@KEY()↓
◆Are you giving me a present?)↓
;jpn:◆ウキー ウキキキー↓
;jpn:(ぼく やまださるおです)@KEY()↓
;jpn:◆ウキー ウキキキー↓
;jpn:(いま いちばんきょうみあるのは↓
;jpn: やっぱり キングバナナです)@KEY()↓
;jpn:◆ウキー ウキキキー↓
;jpn:(え? もしかして ぼくに↓
;jpn: プレゼントしてくれるとか?)@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_I_YES,_SARUD_I_NO)
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「キングバナナ」以外を選ぶと〕
_SARUD_I_NO;
◆Uki...@KEY()↓
◆(Tight wad...)

;jpn:◆ウキ‥‥↓
;jpn:(けち‥‥)
@KEYNP()
』
_SARUD_I_YES
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_I_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_DRY_MEAT_SPECIAL)
@FALSE_GOTO(_SARUD_I_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「キングバナナ」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Ukie!@KEY()↓
◆(Oh, I’ve died and gone to monkey heaven!)
;jpn:◆ウキー!↓
;jpn:(やりー!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_I_B,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_I_D,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_I_OK)
』
;D〔移動後に話すと〕
_SARUD_I_AFTER;
◆Ukki Ukikie@KEY()↓
◆(I am Man K. Man.)

;jpn:◆ウキー ウキキキー↓
;jpn:(ぼく やまださるおです)
@KEYNP()
』
;▼部屋６(左のさる)▼▼▼▼▼▼▼▼(ハンバーガー・ダブルバーガー)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_J;
@CHKFGOTO(FLG_SARUDUNGEON_J_OK,_SARUD_J_AFTER)
◆Uikkie Uiki Uki@KEY()↓
◆(Let’s get to the point.@KEY()↓
◆Give me a @DSP_GOODS(GDS_FOOD_HAMBURGER).)↓
;jpn:◆ウィッキー ウィキウィキ↓
;jpn:(けつろんから さきにいうと↓
;jpn: ハンバーガーください)@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_J_YES,_SARUD_J_NO)
_SARUD_J_NO;
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ハンバーガー・ダブルバーガー」以外を選ぶと〕
◆Uiki Uikki@KEY()↓
◆(Ok, shove off then.)
;jpn:◆ウィキ ウィッキ↓
;jpn:(じゃ いいです)
@KEYNP()
』
_SARUD_J_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_J_NO)
@SAVE_REG()
@GOSUB(_SARUD_Q_HAMBERGER)
@FALSE_GOTO(_SARUD_J_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ハンバーガー・ダブルバーガー」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Uikki Uiki Uiki Uiki@KEY()↓
◆(I’m very grateful to you.)
;jpn:◆ウィキウィキ ウィキウィキ↓
;jpn:(かんしゃのきもちで↓
;jpn: いっぱいです)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_I_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_I_C,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_J_OK)
』
;D〔移動後に話すと〕
_SARUD_J_AFTER;
◆Uiki@KEY()↓
◆(Please take care.)
;jpn:◆ウィキ↓
;jpn:(よろしくどうぞ)
@KEYNP()
』
;▼部屋７(右のさる)▼▼▼▼▼▼▼▼(うみたてたまご)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_K;
@CHKFGOTO(FLG_SARUDUNGEON_K_OK,_SARUD_K_AFTER)
◆Meow Meow fss fss fssss?@KEY()↓
◆(What strange chattering for a monkey.)@KEY()↓
◆Coo Coo pepepe.@KEY()↓
◆(If I eat a @DSP_GOODS(GDS_FOOD_EGG_RAW), I recover some health.)@KEY()↓
◆Croak croak breeeeeep?@KEY()↓
◆(If you have one, can I have one?)↓
;jpn:◆ニャーニャー ホケキョ?↓
;jpn:(さるのくせに へんな↓
;jpn: なきごえでしょ?)@KEY()↓
;jpn:◆クルルー ポッポッポー↓
;jpn:(うみたてたまご のめば↓
;jpn: なおるんだけどな)@KEY()↓
;jpn:◆ホーシーツクツク?↓
;jpn:(もってるなら くれませんか?)↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_K_YES,_SARUD_K_NO)
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、または「
;うみたてたまご」以外を選ぶと〕
_SARUD_K_NO;
◆Bow wow ruff ruff bark!@KEY()↓
◆(Fine, I’ll just be a weird monkey.)
;jpn:◆パオーン チューチュー↓
;jpn:(いいんだ へんなさるで)
@KEYNP()
@!
_SARUD_K_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_K_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_FOOD_EGG_RAW)
@FALSE_GOTO(_SARUD_K_NO)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「うみたてたまご」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Gulp, gulp...Ukiki!@KEY()↓
◆(Gulp, gulp...See!)
;DAN:Gokkun is sound of drinking.

;jpn:◆ごっくん‥‥ウキキッ!↓
;jpn:(ごっくん‥‥ほらねっ!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_E_B,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_E_D,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_K_OK)
@!
;D〔移動後に話すと〕
_SARUD_K_AFTER;
◆Ukiki!@KEY()↓
◆(Monkey’s true chattering!)

;jpn:◆ウキキッ!↓
;jpn:(さるほんらいの なきごえ!)
@KEYNP()
』
;▼部屋７(左のさる)▼▼▼▼▼▼▼▼(ものさし)
;A〔入口ふさいでる状態のさるに話すと〕
MSG_SARUDUNGEON_L;
@CHKFGOTO(FLG_SARUDUNGEON_L_OK,_SARUD_L_AFTER)
◆Kiki kikkeki!@KEY()↓
◆(Oh, I wanna measure something!)@KEY()↓
◆Kiki kiku eki!@KEY()↓
◆(But I don’t have a @DSP_GOODS(GDS_TOOL_MONOSASHI)...)@KEY()↓
◆Kuki keikuki?@KEY()↓
◆(Do you have one I may borrow?)↓
;jpn:◆キキ キキキキキ!↓
;jpn:(ああ なにか↓
;jpn: はかりたいわ!)@KEY()↓
;jpn:◆キキ キキキキキ‥‥↓
;jpn:(でも ものさし↓
;jpn: もってないの‥‥)@KEY()↓
;jpn:◆キキ キキキキキ?↓
;jpn:(あなた もってたら↓
;jpn: わたしに ちょうだい?)@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SARUD_L_YES,_SARUD_L_NO)
_SARUD_L_NO;
;C〔「いいえ」を選ぶか、「はい」でウインドウ開いた後にキャンセル、
;または「ものさし」以外を選ぶと〕
◆Kiki Kikurek ki!@KEY()↓
◆(No measuring!)
;jpn:◆キキ キキキキキ!↓
;jpn:(ああ はかられたわ!)
@KEYNP()
』
_SARUD_L_YES;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SARUD_L_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_MONOSASHI)
@FALSE_GOTO(_SARUD_L_NO)
_SARUD_L_YES_2;
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
;B〔「はい」で開いたウインドウ内の「ものさし」を選ぶと〕
@SE(SE_se76_my_give)
@WI(10)
◆Kikki ekruiki!@KEY()↓
◆(Finally, I can measure my own tail!)
;jpn:◆キッキ キキキキキキキ!↓
;jpn:(これで じぶんのしっぽが↓
;jpn: はかれるわ!)
@KEYNP()
@CLOSEALL()
@HIDE_CHAR(PRSN_DEST_MONKEY_E_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_DEST_MONKEY_E_C,ANIM_PEOPLEWALK1_LIVE,OBJFX_SHOW_NONE)
@SETF(FLG_SARUDUNGEON_L_OK)
』
;D〔移動後に話すと〕
_SARUD_L_AFTER;
◆Kikoke Ukike!@KEY()↓
◆(I can measure his tail too!)
;jpn:◆キキキキキキキ!↓
;jpn:(かれのしっぽも↓
;jpn: はかれるわ!)
@KEYNP()
』

_SARUD_Q_HAMBERGER;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SET_REG(0)
@EQ(GDS_FOOD_HAMBURGER)
@TRUE_GOTO(_Q_HAMBERGER_END)
@XCHG()
@EQ(GDS_FOOD_HAMBURGER_DOUBLE)
_Q_HAMBERGER_END;
@!

_SARUD_Q_PIZZA;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SET_REG(0)
@EQ(GDS_FOOD_PIZZA)
@TRUE_GOTO(_Q_PIZZA_END)
@XCHG()
@EQ(GDS_FOOD_PIZZA_LARGE)
_Q_PIZZA_END;
@!

_SARUD_Q_SKIP;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SET_REG(0)
@EQ(GDS_FOOD_SKIP_SAND)
@TRUE_GOTO(_Q_SKIP_END)
@XCHG()
@EQ(GDS_FOOD_SKIP_SAND_SP)
_Q_SKIP_END;
@!

;▼部屋８(差し替え)▼▼▼▼▼▼▼▼
;〔初めてはなすと〕
MSG_SARUDUNGEON_M;
@CHKFGOTO(FLG_SARUDUNGEON_M_OK,_SARUD_M_AFTER)
◆Kyakyako Kyakie@KEY()↓
◆(Somewhere amongst all these rooms...)@KEY()↓
◆Ukkiki Kyako Kyakki@KEY()↓
◆(you should be able to obtain Dragonite.)@KEY()↓
◆Ukyakki Kikiyakoke?@KEY()↓
◆(Do you think Dragonite is really made from dragons?)@KEY()↓
◆KyokeKyoke Ukyokie@KEY()↓
◆(By the way, I’ll give you a @DSP_GOODS(GDS_FOOD_EGG_RAW).)@KEY()↓
◆Ukyakyokyo Kiekyo@KEY()↓
◆(If you run out, just come back and I’ll give you as many eggs as you want.)@KEY()↓
;jpn:◆キャキャコ キャキー↓
;jpn:(たくさんあるへやの↓
;jpn: どこかで‥‥)@KEY()↓
;jpn:◆ウッキッキ キャコキャッキ↓
;jpn:(ドラゴンパウダーが↓
;jpn: てにはいるらしいんだ)@KEY()↓
;jpn:◆ウキャッキ キキャコケ?↓
;jpn:(ドラゴンパウダーって↓
;jpn: ドラゴンパの ウダーかな?)@KEY()↓
;jpn:◆キョケキョケ ウキョキー↓
;jpn:(それはそうと↓
;jpn: うみたてたまご あげます)@KEY()↓
;jpn:◆ウキャキョキョ キーキョ↓
;jpn:(なくなったら またくれば↓
;jpn: なんどでも あげちゃうよ)@KEY()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SARUD_M_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_FOOD_EGG_RAW)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_SARUDUNGEON_M_OK)
@KEYNP()
』
_SARUD_M_GOODSFULL;
@KEY()↓
◆Kyokyukyo kyakie@KEY()↓
◆(You have too much stuff!)
;jpn:◆キョキュキョ キャキー↓
;jpn:(もちものが いっぱいだよ!)
@KEYNP()
@!
_SARUD_M_AFTER;
;〔２回目以降〕
◆Ukyako kyakki?@KEY()↓
◆(Did you find a @DSP_GOODS(GDS_EQUIP_PENDANT_HONOO)?)@KEY()↓
◆Ukyakki Kokekyakya?@KEY()↓
◆(Oh no, you don’t have to answer.)@KEY()↓
◆KyokeKyoke Ukyokie@KEY()↓
◆(Here’s another @DSP_GOODS(GDS_FOOD_EGG_RAW)...)@KEY()↓
;jpn:◆ウッキコ キャッキ?↓
;jpn:(ほのおのペンダントは↓
;jpn: もう みつけた?)@KEY()↓
;jpn:◆ウキャッキ コケキキャ?↓
;jpn:(あ こたえなくてもいいよ)@KEY()↓
;jpn:◆キョケキョケ ウキョキー↓
;jpn:(それはそうと うみたてたまご↓
;jpn: もうひとつ あげます)@KEY()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SARUD_M_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_FOOD_EGG_RAW)
@GOSUB(MSG_SUB_GETGOODS)
@KEYNP()
』
;▼部屋１１(差し替え)▼▼▼▼▼▼▼▼(キングバナナくれる)
;〔初めてはなすと〕
MSG_SARUDUNGEON_N;
@CHKFGOTO(FLG_SARUDUNGEON_N_OK,_SARUD_N_AFTER)
◆Kyuie@KEY()↓
◆(One of my friends can use the teleport.)@KEY()↓
◆Kyu?  Kyikki?@KEY()↓
◆(What?@KEY()↓
◆You’ve never heard of it?)@KEY()↓
◆Kyukyu Kyui@KEY()↓
◆(Then, I’ll give you @DSP_GOODS(GDS_TOOL_DRY_MEAT_SPECIAL).)@KEY()↓
;jpn:◆キュイー↓
;jpn:(わたしたちの なかまのひとりは↓
;jpn: テレポートが つかえるのよ)@KEY()↓
;jpn:◆キュ? キュイッキ?↓
;jpn:(え? そんなこと↓
;jpn: きいてないよって?)@KEY()↓
;jpn:◆キュッキュ キュイー↓
;jpn:(それなら ほら↓
;jpn: キングバナナ あげるわ)@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SARUD_N_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_DRY_MEAT_SPECIAL)
◆Kyu Ukyukui?@KEY()↓
◆(That didn’t make sense, did it?@KEY()↓
◆But, anyway, I’m attractive, don’t you think?)@KEY()
;jpn:◆キュー ウキュキュイ?↓
;jpn:(わたしって しりめつれつで↓
;jpn: なんかみりょくてきでしょ?)@KEY()
@GOSUB(MSG_SUB_GETGOODS_S)
@SETF(FLG_SARUDUNGEON_N_OK)
@KEYNP()
』
_SARUD_N_GOODSFULL;
◆Kiee Kiee@KEY()↓
◆(You can’t carry any more items.@KEY()↓
◆You’ve got too much stuff.)
;jpn:◆キ キー
;jpn:(もちものがいっぱいで↓
;jpn: それいじょう もてないわね)
@KEYNP()
@!
_SARUD_N_AFTER;
;〔２回目以降〕
◆Kyu Kyuii@KEY()↓
◆(We’re born in the desert.)@KEY()↓
◆Kyu?  Kyuikki?@KEY()↓
◆(What?@KEY()↓
◆You didn’t know that?)@KEY()↓
◆Kyukyu Kyui kyukyu@KEY()↓
◆(You guys must be hard workers.)@KEY()↓
◆Kyu ukyukyoi?@KEY()↓
◆(I’m not making sense, am I?@KEY()↓
◆But I am attractive, don’t you think?)
;jpn:◆キュキューイ↓
;jpn:(わたしたちは↓
;jpn: さばくうまれなのよ)@KEY()↓
;jpn:◆キュ? キュイッキ?↓
;jpn:(え? そんなこと↓
;jpn: きいてないよって?)@KEY()↓
;jpn:◆キュッキュ キュイキュキュ↓
;jpn:(じゃあ あなたたちは↓
;jpn: きっと がんばりやさんね)@KEY()↓
;jpn:◆キュー ウキュキュイ?↓
;jpn:(わたしって しりめつれつで↓
;jpn: なんかみりょくてきでしょ?)
@KEYNP()
』

;▼部屋１３▼▼▼▼▼▼▼▼

;〔初めてはなすと〕
MSG_SARUDUNGEON_O;
◆Ukikki Rukikki@KEY()↓
◆(I love Talah Rama the most.)@KEY()↓
◆Waakikki Hoikikki@KEY()↓
◆(He’s a friend of the monkeys.@KEY()↓
◆Hoikikki).@KEY()↓
◆...Uki Ukiukiukya@KEY()↓
◆(...Here’s a song I made up for Talah Rama!)
;jpn:◆ウーキッキ ルーキッキ↓
;jpn:(タライ・ジャブさま↓
;jpn:  いちばん すきすき)@KEY()↓
;jpn:◆ワーキッキ ホイキッキ↓
;jpn:(おさるの みかただ↓
;jpn: ほいキッキ)@KEY()↓
;jpn:◆‥‥ウキ ウキウキウキャ!↓
;jpn:(‥‥これ ぼくがつくった↓
;jpn: タライ・ジャブさまのうた!)
@KEYNP()
』
;@CHKFGOTO(FLG_SARUDUNGEON_O_OK,_SARUD_O_AFTER)
;◆ウー‥‥↓
;(このおくに‥‥)@KEY()↓
;◆ウー ウー‥‥↓
;(しるさるぞ しる↓
; いだいなるおかた‥‥)@KEY()↓
;◆キャキャイ・キャキュ‥‥↓
;(そのなも↓
; タライ・ジャブさまが‥‥)@KEY()↓
;◆ウキョッ!↓
;(いるよっ!)
;@KEYNP()
;@SETF(FLG_SARUDUNGEON_O_OK)
;』
;
;〔２回目以降〕
;_SARUD_O_AFTER;
;◆ウー‥‥↓
;(どうやら そなたたち‥‥)@KEY()↓
;◆ウー ウー‥‥↓
;(いだいなるおかた↓
; タライ・ジャブさまに‥‥)@KEY()↓
;◆ウキョ ウキョ ウキョッ!↓
;(きにいられたみたいねっ!)
;@KEYNP()
;』



;▼部屋１４▼▼▼▼▼▼▼▼

MSG_SARUDUNGEON_P;
@CHKFGOTO(FLG_MASTER_TLPT,_SARUDUNGEON_P_LATER);同じセリフ
@CHKFGOTO(FLG_ITEM_TOFU,_SARUDUNGEON_P_AFTER)
◆Kyakyakyaa Kya@KEY()↓
◆(I’ve been waiting for you.)
;jpn:◆キャキャキャーキャ↓
;jpn:(おまちしてました)
@KEYNP()
』

_SARUDUNGEON_P_AFTER;テレポートを教えるサル
◆Kyakyekyai kya@KEY()↓
◆(I’ll teach you teleportation.)@KEY()↓
◆Kyakyakya@KEY()↓
◆(Let’s go outside.)
;jpn:◆キャキャキャーキャ↓
;jpn:(テレポーテーションを↓
;jpn: おしえます)@KEY()↓
;jpn:◆キャキャキャ↓
;(さあ ひろいところに↓;＄
;jpn:(さあ ちじょうに↓
;jpn: でましょう)
@KEYNP()
@CLOSEALL()
@REMOVE_CHAR( PRSN_DEST_MONKEY_M_A, ANIM_LEAVE_SARUSENSEI )
@WAITSYS()
@SETF(FLG_DSRT_INFO_TLPT)	;テレポート情報を聞いた
@SETF(FLG_DSRT_TSARU_DISAPPEAR)
@SETF(FLG_DSRT_TSARU_A_APPEAR);サルセンセイA表示
』
_SARUDUNGEON_P_LATER;＄テレポート修得後のサル先生
◆Kyakya kyekyi?@KEY()↓
◆(So...how ’ve you been?)
;jpn:◆キャキャキャーキャ?↓
;jpn:(おげんきでしたか?)
@KEYNP()
』

MSG_EVT_LEAD_SARUSENSEI;
◆Hikikki.@KEY()↓
◆(Follow me, like this way.)
;jpn:◆ホイキッキ↓
;jpn:(こっちだ)@KEYNP
@CLOSEALL()
@REMOVE_CHAR( PRSN_DEST_FIELD_S, ANIM_LEAD_SARUSENSEI )
』

MSG_EVT_READY_SARUSENSEI;
;誘導してきたサル先生Aを、サル先生Bと交換
@HIDE_CHAR( PRSN_DEST_FIELD_S,OBJFX_HIDE_NONE)
@MOVE_CHAR( PRSN_DEST_FIELD_T, ANIM_MAPOBJSTILL, OBJFX_SHOW_NONE )
@RESF( FLG_DSRT_TSARU_A_APPEAR)
@SETF( FLG_DSRT_TSARU_B_APPEAR);サル先生B表示
@WI(1)	;PRSN_DEST_FIELD_サル先生B の登録待ち(念のため)
@GET_CHAR_DIR( PRSN_DEST_FIELD_T, 1, PC_ALL )
@SET_CHAR_DIR( PRSN_DEST_FIELD_T, 0 )	;サル先生Bをネスの方に向かせる
』

MSG_EVT_LESSON_TELEPORT;
@CHKFGOTO(FLG_MASTER_TLPT,_EVT_LESSON_TELEPORT_BYE)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_DSRT_SARUSENSEI_DEAD);ネス死んでたらダメ
@CHKFGOTO( FLG_TEMP_1, MSG_EVT_SARUSENSEI_TRYAGAIN )	;再トライ用
_EVT_SARUSENSEI_TRYAGAIN_YES;
◆Kyakya Kyokyo@KEY()↓
◆(Ok, I’ll do a teacher’s demonstration.)@KEY()↓
◆Kyakyakya Kyakkya@KEY()↓
◆(If you can learn this, you can go anywhere you’ve been previously.)@KEY()↓
◆Kyakkyaki kiki@KEY()↓
◆(You can go there instantly.)@KEY()↓
◆Kyakki Kyaki@KEY()↓
◆(This skill can’t be used in a room or underground, though.)@KEY()
;jpn:◆キャッキャッ キョキョ↓
;jpn:(じゃあ せんせいが まず↓
;jpn: みほんをみせよう)@KEY()↓
;jpn:◆キャキャキャ キャッキャ↓
;jpn:(これが できるようになると↓
;jpn: いちど いったところなら)@KEY()↓
;jpn:◆キャキャキ キキ↓
;jpn:(あっ というまに↓
;jpn: いけるようになります)@KEY()↓
;jpn:◆キャッキ キャキ↓
;jpn:(ちかや へやのなかでは↓
;jpn: このちからは つかえません)@KEY()↓;＄
@CLOSEALL()
;お手本見せるアニメ
@REMOVE_CHAR( PRSN_DEST_FIELD_T, ANIM_TELEPORT_SARUSENSEI )
@WAITSYS()
@COLD_CHAR( PRSN_DEST_FIELD_T )
@BGMSTART( 0, BGM_telep )	;テレポートBGM始め
@FRESH_CHAR( PRSN_DEST_FIELD_T )
@WAITSYS()
@COLD_CHAR( PRSN_DEST_FIELD_T )
@MUSISTART()			;テレポートBGM終わり
@FRESH_CHAR( PRSN_DEST_FIELD_T )
@WAITSYS()
@REMOVE_CHAR( PRSN_DEST_FIELD_T, ANIM_MAPOBJSTILL )
@GET_CHAR_DIR( PRSN_DEST_FIELD_T, 1, PC_ALL )	;組
@SET_CHAR_DIR( PRSN_DEST_FIELD_T, 0 )		;み
@WI( 30 )
@OPEN(1)
◆Ukkie@KEY()↓
◆(I went to Fourside and returned.)@KEY()↓
◆Kyaakyakkya@KEY()↓
◆(I showed you the basic, straight course,@KEY()↓
◆but you can also build up enough speed while turning, if you have enough room.)@KEY()↓
◆Ukkikie@KEY()↓
◆(Ok!@WI(15)↓
  Why don’t you try it, young man!)
@KEYNP()
;jpn:◆ウッキー↓
;jpn:(フォーサイドのまちにいって↓
;jpn: すぐに もどってきました)@KEY()↓;＄
;jpn:◆キャーキャッキャ↓
;jpn:(せんせいは きほんてきな↓
;jpn: まっすぐコースで やったけれど@KEY()↓
;jpn:◆きょりさえあれば↓
;jpn: まがっても できるからね)@KEY()↓
;jpn:◆ウッキッキー↓
;jpn:(さあ!@WI(15) やってみなさい。↓
;jpn: わかものよ!)@KEYNP
@CLOSEALL()
@SETF( FLG_TEMP_1 )	;再トライ用
;この後ネスの強制テレポート開始
』

MSG_EVT_SARUSENSEI_TRYAGAIN;
@OPEN(1)
◆Kyakyakyakya@KEY()↓
◆(Try again by believing in the monkey teacher.)↓
<Yes>
<No>
;jpn:◆キャーキャキャキャ↓
;jpn:(もういちどトライしてみようよ。↓
;jpn: サルのせんせいを しんじて)@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO( _EVT_SARUSENSEI_TRYAGAIN_YES, _EVT_SARUSENSEI_TRYAGAIN_NO )

_EVT_SARUSENSEI_TRYAGAIN_NO;
◆Kyakyakya@KEY()↓
◆(You don’t like the monkey teacher?...)
@KEYNP()
;jpn:◆キャッキャキャ↓
;jpn:(やっぱり↓
;jpn: サルのせんせいじゃ いやか‥‥)@KEYNP()
@CLOSEALL()
』
_DSRT_SARUSENSEI_DEAD;
◆uKI?@KEY()↓
◆(What happened to the boy with the red cap?@KEY()↓
◆I was only going to teach him something.)@KEY()↓
◆Kyakyo@KEY()↓
◆(He’s not here...)
;jpn:◆ウキ?↓
;jpn:(あれ? ともだちの↓
;jpn: あかいぼうしのコに‥‥だけ)@KEY()↓
;jpn:◆キャッキョ↓
;jpn:(おしえようと おもったんだけど↓
;jpn: ‥‥いないのか)
@KEYNP()
』

MSG_EVT_MASTER_TLPT;
@OPEN(1)
◆@DSP_NAME(PC_NESS) learned how to use PSI Teleportation.
@KEYNP()
;jpn:◆(@DSP_STS(STS_PC_NAME_NES)は↓
;jpn: PSIテレポーテーションαが↓
;jpn: つかえるようになった)@KEYNP
@CLOSEALL()
@ADD_PSI( PC_NESS, 1 )
@SETF( FLG_MASTER_TLPT )
;サル先生Bをネスのいる方に向かせる
@GET_CHAR_DIR( PRSN_DEST_FIELD_T, 1, PC_ALL )	;植物
@SET_CHAR_DIR( PRSN_DEST_FIELD_T, 0 )		;物語
@SHOW_MANPU_CHAR( PRSN_DEST_FIELD_T, MANPU_BIKKURI )
@WI(60)
@HIDE_MANPU_CHAR( PRSN_DEST_FIELD_T )
;サル先生Bを、ネスに近寄るアニメと交換
@REMOVE_CHAR( PRSN_DEST_FIELD_T, ANIM_APPROACH_CONT_SCRIPT )
@WAITSYS()
@OPEN(1)
◆Kyaho!@KEY()↓
◆(Great!↓
  Okay, the teacher is going home now.)
@KEYNP()
;jpn:◆キャッホー!
;jpn:(すごいぞ!@KEY()↓
;jpn:◆それじゃ せんせいは↓
;jpn: かえるから)@KEYNP
@CLOSEALL()
;サル先生Bをジャブ穴に帰す
@REMOVE_CHAR( PRSN_DEST_FIELD_T, ANIM_RETURN_SARUSENSEI )
@RESF( FLG_TEMP_1 )
@RESF( FLG_DSRT_TSARU_B_APPEAR )	;サル先生Bを表示しないように
@RESF( FLG_DSRT_TSARU_DISAPPEAR )	;タライジャブの部屋にサルを表示する
』
_EVT_LESSON_TELEPORT_BYE;去るサル先生
◆Kyai Kyai@KEY()↓
◆(Bye bye.)
@KEYNP()
;jpn:◆キャイキャイ↓
;jpn:(バイバイ@WI(20) ね)@KEYNP()
』
;-------------------------------------------------


;▼入口近くにいるさる(地上)▼▼▼▼▼▼▼▼

MSG_DSRT_MONKEY_SARUDUNGEON;
◆Kukkukukku@KEY()↓
◆(Welcome!)@KEY()↓
◆Kikikiykki@KEY()↓
◆(Our paradise exists beneath that hole.)@KEY()↓
◆Kuykku kikki...@KEY()↓
◆(Talah Rama is great and kind...)@KEY()↓
◆Kikki Kuykku@KEY()↓
◆(and he knows everything, Talah Rama does...)@KEY()↓
◆Kikku Kuekki@KEY()↓
◆(He made us the underground rooms...)
@KEYNP()
;jpn:◆クッククック↓
;jpn:(ようこそ ここへ)@KEY()↓
;jpn:◆キッキキッキ↓
;jpn:(そこの あなのしたは↓
;jpn: ぼくらの らくえん)@KEY()↓
;jpn:◆クックキッキ‥‥↓
;jpn:(いだいで やさしい↓
;jpn: タライ・ジャブさまが‥‥)@KEY()↓
;jpn:◆キッキクック‥‥↓
;jpn:(なんでも しっている↓
;jpn: タライ・ジャブさまが‥‥)@KEY()↓
;jpn:◆キッククッキ↓
;jpn:(ぼくらのために つくって↓
;jpn: くれた ちかしつなのです)@KEYNP()
』



;▲以上です▲▲▲▲▲▲▲▲▲▲▲▲▲
;-------------------------------------------------

;以下増補

MSG_DSRT_MONKEY_TJAB;
;断食のタライジャブ脇のサル
◆Kyakkyekyaekya Kyikkya@KEY()↓
◆(Talah Rama is now fasting and@KEY()↓
◆Kyakkyakyekyakya@KEY()↓
◆practicing silent meditaion,@KEY()↓
◆he is also abstaining from anything that would make him sick or smelly too.)@KEY()↓
◆Kyapi Kyapi@KEY()↓
◆(Please don’t bother him.)
@KEYNP()
;jpn:◆キャッキャキャ キャッキャッ↓
;jpn:(タライ・ジャブさまは↓
;jpn: ただいま だんじきと)@KEY()↓
;jpn:◆キャキャキャキャキャ↓
;jpn:(むごんのぎょうと↓
;jpn: きんしゅ きんえんを)@KEY()↓
;jpn:◆キャピキャピ↓
;jpn:(なさっておられる。↓
;jpn: じゃまを なさいませんように)@KEYNP()
』

MSG_DSRT_TJAB;
;タライジャブは無言
◆.....

;jpn:◆‥‥‥。
@KEYNP()
』
;-------------------------------------------------

MSG_DSRT_CHECK_SYOZI;
◆(Dusty Dunes Headquarters for finding buried gold.)
@KEYNP()
;jpn:◆(ドコドコさばく↓
;jpn: まいぞうきん はっくつほんぶ)@KEYNP()
』
;-------------------------------------------------

MSG_CHECK_DESERT_SIGN;＄
◆(East to Fourside.)
@KEYNP()
;jpn:◆(ひがし↓
;jpn:  フォーサイドほうめん)@KEYNP()
』
;-------------------------------------------------
