;@Habitat:フォーサイド/恐竜博物館/受付
;@Person:キャサリン
;@Figure:OLG
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MUSEUM_RECEPTION
MSG_FOUR_MUSEUM_RECEPTION;
@CHKFGOTO(FLG_GLOBAL_MUSEUM_PAID,_FOUR_MUSEUM_RECEPTION_PAID)
◆The Dinosaur Museum doesn’t have any real dinosaurs...@KEY()↓
◆They’re all replicas.@KEY()↓
◆I’m sure everyone knows that.@KEY()↓
;jpn:◆きょうりゅうはくぶつかんは↓
;jpn: ほんものの きょうりゅうが‥‥@KEY()↓
;jpn:◆いるわけではなくて↓
;jpn: すべて レプリカです。↓
;jpn: あたりまえのことですけどね。@KEY()↓
;◆それでもいいなら↓
; にゅうじょうりょう 5ドルです。↓
; よろしいですか?@KEY()↓
◆If you still want to go see the dinosaurs,@KEY()↓
◆pay 5 dollars a piece for the entrance fee.@KEY()↓
◆Is that okay?↓
;jpn:◆それでもいいなら↓
;jpn: にゅうじょうりょう↓
;jpn: ひとり 5ドルです。@KEY()↓;人数分の料金を請求する為に変更
;jpn:◆よろしいですか?@KEY()↓
@WINR_MONEY()
<Yes>
<No>
;jpn:	<はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_MUSEUM_RECEPTION_YES,_FOUR_MUSEUM_RECEPTION_NO)

_FOUR_MUSEUM_RECEPTION_NO;
@MUL_ACTIVE_PLAYER(5)
@XCHG()
◆Maybe you think @DSP_NUM(0) dollars is too much.@KEY()↓
◆Or are you just not interested in dinosaurs.@KEY()↓
◆You’re strange, kid!
@KEYNP()
;jpn:◆@DSP_NUM(0)ドルが おしいのかしら。↓
;◆5ドルが おしいのかしら。↓
;jpn: きょうりゅうに きょうみが↓
;jpn: ないのかしら? かわったひと!@KEYNP()
』

_FOUR_MUSEUM_RECEPTION_YES;
@MUL_ACTIVE_PLAYER(5)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_FOUR_MUSEUM_RECEPTION_NOMONEY)
@SE(SE_se76_my_give)
@WI(1)
@MONEYOUT(0)
@WINR_MONEY()
◆Please enter.@KEY()↓
◆You’ll find an academic researcher inside.
@KEYNP()
;jpn:◆じゃ どうぞ。↓
;jpn: なかに がくじゅつけんきゅういん↓
;jpn: が おります。@KEY()
@SETF(FLG_GLOBAL_MUSEUM_PAID)
@CHKFGOTO(FLG_WIN_GIEGU,MSG_END)	;別れのHRECTを保つ為
@RES_HIT_RECT(1)
』

_FOUR_MUSEUM_RECEPTION_NOMONEY;
@MUL_ACTIVE_PLAYER(5)
@XCHG()
◆You don’t even have↓
   @DSP_NUM(0) dollars!@KEY()↓
◆You don’t deserve to go in the museum.
@KEYNP()
;jpn:◆たった@DSP_NUM(0)ドルも↓
;◆たった5ドルも↓
;jpn: もっていないなんて@KEY()↓
;jpn:◆あなたが はくぶつかんいり↓
;jpn: するべきじゃないかしら。@KEYNP()
』
_FOUR_MUSEUM_RECEPTION_PAID;
◆The Dinosaur Museum doesn’t have real dinosaurs...@KEY()↓
◆They all are replicas.@KEY()↓
◆But I guess everyone knows that.
@KEYNP()
;jpn:◆きょうりゅうはくぶつかんは↓
;jpn: ほんものの きょうりゅうが‥‥@KEY()↓
;jpn:◆いるわけではなくて↓
;jpn: すべて レプリカです。@WI(20)↓
;jpn: あたりまえのことですけどね。@KEYNP()
』


;@Habitat:フォーサイド/恐竜博物館/展示室
;@Person:部屋への扉を塞ぐコモリターさん
;@Figure:コモリター
;@AppearanceKey:FLG_FOUR_KOMORITA_APPEAR/off
;@ActionScript:◆東を向いて止まったまま
;@GoodsMessage:MSG_FOUR_KOMORITA_RECEIVE
;@CheckMessage:0
;@Message:MSG_FOUR_MUSEUM_KOMORITA
MSG_FOUR_MUSEUM_KOMORITA;
;恐竜博物館学術研究員(コモリター)
@CHKFGOTO(FLG_TEMP_1,MSG_FOUR_KOMORITA_RECEIVE_LATER)
@CHKFGOTO(FLG_TLPT_SUMS,_FOUR_MUSEUM_KOMORITA_AFTER)
◆I’m so happy there are some visitors today.@WI(15)  These days, few people come here.@KEY()↓
◆...I’m Mr. Spoon, the academic researcher.@KEY()↓
;jpn:◆ひさしぶりに きゃくがきて↓
;jpn: うれしいなあ。@KEY()↓
;jpn:◆‥‥わたし とうはくぶつかんの↓
;jpn: けんきゅういんの↓
;jpn: ライスボウル といいます。@KEY()↓
@WI(60)↓
◆I wonder if there are any famous stars here today?@KEY()↓
;jpn:◆たまにはアイドルタレントとか@KEY()↓
;jpn: こないものかなぁ。@KEY()↓
@WI(60)↓
◆Dinosaurs...@KEY()↓
◆Huge, aren’t they?  Well, that’s all I’ve gotten out of my research!@KEY()↓
◆You wanna hear more?@KEY()↓
◆(Whispering) To tell you the truth...@KEY()↓
◆I heard that dinosaurs were found near the lower side of Scaraba,@KEY()↓
◆and there were lots of them.@KEY()↓
◆There are unconfirmed reports@KEY()↓
◆that the dinosaurs ate some of the natives there.@KEY()↓
◆If you go, please try to find the dinosaurs and bring back photographs.
@KEY()↓
;jpn:◆きょうりゅう‥‥おっきいでしょ。@WI(15)↓
;jpn: きょうりゅうは おおきい。@KEY()↓
;jpn:◆いじょうで かいせつを おわる。↓
;jpn: わかりましたね。@WI(20)↓
;jpn: まだなんか ききたいんですか。@KEY()↓
;jpn:◆ボソボソ じつはですね‥‥@WI(20)↓
;jpn: たいこのむかしに↓
;jpn: ぜつめつしたはずの@KEY()↓
;jpn:◆きょうりゅうが↓
;jpn: スカラビちかくの おくちで↓
;jpn: はっけんされたという@KEY()↓
;jpn:◆ほうこくが あるんですよね。@WI(20)↓
;jpn: それも‥‥かずおおく いる と。@WI(15)↓
;jpn: げんちのひとが くわれちゃった@KEY()↓
;jpn:◆という みかくにんじょうほうも↓
;jpn: あります。@WI(15)↓
;jpn: もし あちらに たびをするなら@KEY()↓
;jpn:◆ぜひとも はっけんして↓
;jpn: しゃしんでも とってきて↓
;jpn: ください。@KEY()↓
@GOTO(MSG_FOUR_KOMORITA_RECEIVE_LATER)
』

_FOUR_MUSEUM_KOMORITA_AFTER;
◆You want to know about something ”extraordinary”?@KEY()↓
◆...@KEY()↓
◆Hmmmm...@KEY()↓
;jpn:◆きみ@GOSUB(MSG_SUB_TATI)↓
;jpn: 「とんでもないもの」について↓
;jpn: しりたいっていうの?@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆‥‥‥‥‥‥。@KEY()↓
@WI(60)↓
◆...You know, there’s a new singer named Venus at the Topolla Theater.@KEY()↓
◆Could you bring me her autograph on an eraser?
◆Then, I’ll show you something ”extraordinary.”@KEY()↓
◆...Oh, if you can get her autograph on anything, don’t worry about the eraser...@KEY()↓
◆I don’t care if the autograph is written on toilet paper...
@KEYNP()
;jpn:◆‥‥あの トポロげきじょうに↓
;jpn: ビーナスって しんじんかしゅが↓
;jpn: でてるでしょ。@KEY()↓
;jpn:◆あのひとの サインいりけしごむ↓
;jpn: もらってきてくれませんか。@KEY()↓
;jpn:◆「とんでもないもの」を↓
;jpn: みせてあげるから。@KEY()↓
;jpn:◆‥‥あ。@WI(15)サインいりなら↓
;jpn: けしごむじゃなくても いいです。↓
;jpn: サインいりちりがみでも。@KEYNP()
@SETF(FLG_FOUR_KOMORITA)
@CLRF(FLG_SUMS_MUSEUM_PHONE_RING)	;電話止む
;@SETF(FLG_PHOTO_DINO_MUSEUM);撮り頃フラグ;マグネットヒル後に変更
』

MSG_FOUR_KOMORITA_RECEIVE_LATER;
◆Please come back again to study,@KEY()↓
◆’cause I don’t like being alone...
@KEYNP()
;jpn:◆またぜひ↓
;jpn: べんきょうに きてくださいね。@WI(15)↓
;jpn: サミシイから‥‥わたしが。@KEYNP()
』

MSG_FOUR_KOMORITA_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_BANANA_SIGNED)
@TRUE_GOTO(_FOUR_KOMORITA_RECEIVE_BANANA)
@GOTO(MSG_SYS_GOODS_USE_NG)

_FOUR_KOMORITA_RECEIVE_BANANA;
@SE(SE_se76_my_give)
◆You got it!@KEY()↓
◆That banana peel has an authentic ”Venus” autograph?@KEY()↓
◆Yep, there’s no doubt about it!@KEY()↓
◆Now for my promise.@KEY()↓
◆I’ll tell you about something ”extraordinary.”@KEY()↓
◆In the next room, there is a light shining from far, far below the manhole.@KEY()↓
◆There, I found a huge, monster rat!@KEY()↓
◆I’m not trying to pull your leg...@KEY()↓
◆I’ll let you go there and check it out for yourself.
@KEYNP()
;jpn:◆やった! これは まちがいなく↓
;jpn: サインいりバナナのかわ!@WI(20)↓
;jpn: じゃ やくそくどおり‥‥@KEY()↓
;jpn:◆「とんでもないもの」を↓
;jpn: みせましょう。@KEY()↓
;jpn:◆となりのへやの↓
;jpn: マンホールの おくのおくに@KEY()↓
;jpn:◆まぶしいひかりが みえましてね‥↓
;jpn: そのむこうに とてつもなく‥‥@KEY()↓
;jpn:◆でかいネズミの ばけものを↓
;jpn: はっけんしたんですよ‥わたしが。@KEY()↓
;jpn:◆‥‥じまんしてるんじゃあ↓
;jpn: ないんですよ。@WI(15)でも@KEY()↓
;jpn:◆わたしが きょかするから↓
;jpn: みてきていいですよ。@KEYNP()
@SE(SE_se10_present_open)
@CLOSEALL()
@GOODSOUT(PC_ALL,GDS_TOOL_BANANA_SIGNED)
@HIDE_CHAR(PRSN_FRSD_MUSEUM_EXHI_A,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_FRSD_MUSEUM_EXHI_B,ANIM_MUSEUM_KOMORITA,OBJFX_SHOW_NONE)
@WAITSYS();ココ
@SETF(FLG_FOUR_KOMORITA_APPEAR)
@SETF(FLG_TEMP_1)
』

;@Habitat:フォーサイド/恐竜博物館/展示室
;@Person:コモリターさん
;@Figure:コモリター
;@AppearanceKey:FLG_FOUR_KOMORITA_APPEAR/on
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MUSEUM_KOMORITA_B
MSG_FOUR_MUSEUM_KOMORITA_B;
@CHKFGOTO(FLG_TLPT_DKFD,_FOUR_MUSEUM_KOMORITA_B_LATER)
@GOTO(MSG_FOUR_KOMORITA_RECEIVE_LATER)

_FOUR_MUSEUM_KOMORITA_B_LATER;
◆As I thought, dinosaurs did actually exist in history.@KEY()↓
◆Yes, I have sure−fire proof.@KEY()↓
◆I’ve seen them in so many movies, they must have been real!
@KEYNP()
;jpn:◆やっぱり きょうりゅうは↓
;jpn: じつざいしたんですね。@KEY()↓
;jpn:◆うーん そうか。@KEY()↓
;jpn:◆りろんてきには↓
;jpn: わかっていたが‥‥。@WI(20)↓
;jpn: えいがにも よくでてきてたし。@KEYNP()
』


;@Habitat:フォーサイド/恐竜博物館/展示室
;@Person:客A
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MUSEUM_A
MSG_FOUR_MUSEUM_A;
◆...I wonder how many animals go extinct before human beings discover them.@KEY()↓
◆I wanna see a live dinosaur sometime in my life.
@KEYNP()
;jpn:◆‥‥ちきゅうのれきしのなかで↓
;jpn: われわれじんるいに↓
;jpn: であうことなく@KEY()↓
;jpn:◆ほろんでいった せいぶつは↓
;jpn: どれくらい いたものだろうか。↓
;jpn: ‥‥うーむ。@KEY()↓
;jpn:◆いきた きょうりゅうを↓
;jpn: いちど みてみたいものだ。@KEYNP()
』

;@Habitat:フォーサイド/恐竜博物館/展示室
;@Person:客B
;@Figure:少女C
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MUSEUM_B
MSG_FOUR_MUSEUM_B;
◆Huge!...@KEY()↓
◆Not you, I’m talking about the dinosaur bones.
@KEYNP()
;jpn:◆でかい!@WI(60)↓
;jpn: あなたのことじゃなく↓
;jpn: きょうりゅうのほねが ね。@KEYNP()
』

;@Habitat:フォーサイド/恐竜博物館/展示室
;@Person:客C
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MUSEUM_C
MSG_FOUR_MUSEUM_C;
◆This museum should sell dinosaur t−shirts.
@KEYNP()
;jpn:◆こういう はくぶつかんって↓
;jpn: きょうりゅうの ティーシャツを↓
;jpn: うればいいと おもうんだよな。@KEYNP()
』

;----------------------------------------
;@Habitat:フォーサイド/病院/受付
;@Person:受付係
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_HOSPITAL_USHER
MSG_FOUR_HOSPITAL_USHER;@MiuraAppended
;◆どなたに ごめんかいですか?@KEY()
@GOSUB(MSG_NURSE_FOUR)
;@GOSUB(MSG_SHOP_FOUR_HOSPITAL)
』

;@Habitat:フォーサイド/病院/診察室
;@Person:お医者さん
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_HOSPITAL_DOCTOR
MSG_FOUR_HOSPITAL_DOCTOR;@MiuraAppended
;◆みてもらいたいのは↓
; だれだね?@KEY()
@GOSUB(MSG_DOCTOR_FOUR)
』

;@Habitat:フォーサイド/病院/診察室
;@Person:助手
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_HOSP_GIRL
MSG_FOUR_HOSP_GIRL;
◆One person requested a ”shampoo and cut.”@KEY()↓
◆They must have thought that a ”bad hair day” could be treated at the hospital.@KEY()↓
◆Either that or they wanted their medical insurance to cover their grooming.
@KEYNP()
;jpn:◆このまえ びよういんと↓
;jpn: まちがえて シャンプーとカットを↓
;jpn: たのんできたひとが いたわ。@KEY()↓
;jpn:◆ひらがなで しゃべってるから↓
;jpn: たまに そういうことも↓
;jpn: あるのよね。@KEYNP()
』

;----------------------------------------

MSG_FOUR_DEPT_TOYSYOP;フォーサイドデパートのおもちゃや
@GOTO(MSG_SHOP_FOUR_TOYSHOP)
』

MSG_FOUR_DEPT_SPORT;フォーサイドデパートのスポーツグッズ屋
@GOTO(MSG_SHOP_FOUR_SPORT)
』

MSG_FOUR_DEPT_HUMBURGER;フォーサイドデパートのハンバーガーショップ
@GOTO(MSG_SHOP_FOUR_HAMBURGER)
』

;@Habitat:フォーサイド/デパート/1階.返品コーナー
;@Person:キャッシュディスペンサ
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;@Habitat:フォーサイド/デパート/1階.返品コーナー
;@Person:公衆電話
;@Figure:電話ボックス
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

;@Habitat:フォーサイド/デパート/1階.返品コーナー
;@Person:返品係
;@Figure:OLF
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_HENPIN
MSG_FOUR_DEPT_HENPIN;@MiuraAppended
@GOSUB(MSG_DP_HENPIN)
』

;@Habitat:フォーサイド/デパート/1階.返品コーナー
;@Person:チケット係
;@Figure:OLF
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_TICKETPIA
MSG_FOUR_DEPT_TICKETPIA;
◆Would you like to buy tickets for the Topolla Theater?@KEY()↓
<Yes>
<No>
;jpn:◆トポロげきじょうの↓
;jpn: チケットをおもとめですか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_DEPART_TICKETPIA_YES,_FOUR_DEPART_TICKETPIA_NO)

_FOUR_DEPART_TICKETPIA_NO;
◆Oh, I see.@KEY()↓
◆You’re not a customer.
@KEYNP()
;jpn:◆なーんだ。↓
;jpn: おきゃくさまじゃ なかったのね。@KEYNP()
』

_FOUR_DEPART_TICKETPIA_YES;
◆Orchestra seats and balcony seats are sold out.@KEY()↓
◆Now, there’s ”standing room only” left.@KEY()↓
◆It’s $30 per person.@KEY()↓
◆Is that okay with you?↓
;DAN:I said standing seat, I mean standing and no seat.

;jpn:◆Sせき ABせきは うりきれで↓
;jpn: 30ドルの たちみせきしか↓
;jpn: のこっていません。@KEY()↓
;jpn:◆よろしいですか?↓
@WINR_MONEY()
<Yes>
<No>
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_DEPART_TICKETPIA_BUY,_FOUR_DEPART_TICKETPIA_NO)
@GOTO(_FOUR_DEPART_TICKETPIA_NO)

_FOUR_DEPART_TICKETPIA_BUY;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_FOUR_DEPART_TICKETPIA_ITEMFULL)
@SAVE_REG()
@Q_MONEY(30)
@TRUE_GOTO(_FOUR_DEPART_TICKETPIA_NOMONEY)
@SE(SE_se76_my_give)
@WI(1)
@MONEYOUT(30)
@WINR_MONEY()
◆Thanks a lot.@KEY()↓
◆Enjoy the show.
@KEYNP()
;jpn:◆ありがとうございました。@WI(15)↓
;jpn: たのしんでください。@KEYNP()
@SE(SE_se74_my_get)
@LOAD_REG()
@GOODSIN_PLAYER(0,GDS_TOOL_THEATER_TICKET)
』

_FOUR_DEPART_TICKETPIA_NOMONEY;
◆I’ve never heard of anyone who doesn’t even have $30!@KEY()↓
◆Ho ho ho ho ho ho ho ho ho.@KEY()↓
◆Oh, excuse me for my laughing in your face.
@KEYNP()
;jpn:◆30ドルも↓
;jpn: もってないひとなんて↓
;jpn: いまどき ほんとにいるのね!@KEY()↓
;jpn:◆ホーホほホホホほほーホホほホホホ↓
;jpn: ほほほホホほホホほーほホほほホホ@KEY()↓
;jpn:◆ぁ しつれい。@KEYNP()
』

_FOUR_DEPART_TICKETPIA_ITEMFULL;
@SE(SE_se05_undo)
◆Sorry, but you can’t carry all of these...
@KEYNP()

;jpn:◆しつれいですが↓
;jpn: もちきれない ごようすですね‥‥@KEYNP()
』


;@Habitat:フォーサイド/デパート/2階.ドラッグストア
;@Person:店員A
;@Figure:OLF
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_DRUG1
MSG_FOUR_DEPT_DRUG1;
@GOSUB(MSG_SHOP_FOUR_DRUG1)
』

;@Habitat:フォーサイド/デパート/2階.ドラッグストア
;@Person:店員B
;@Figure:サラリーマンD
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_DRUG2
MSG_FOUR_DEPT_DRUG2;
@GOSUB(MSG_SHOP_FOUR_DRUG2)
』

;@Habitat:フォーサイド/デパート/2階.ドラッグストア
;@Person:客A
;@Figure:用心棒
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_A
MSG_FOUR_DEPT_A;
@CHKFGOTO(FLG_FOUR_DEPT_MSGCHG,_FOUR_DEPT_A_TMP)
◆Everything’s so expensive...@KEY()↓
◆Should I return to my hometown?
@KEYNP()
;jpn:◆ぶっか‥‥たかいっすよね。↓
;jpn: おれ いなか かえろうかなぁ。@KEYNP()
』
_FOUR_DEPT_A_TMP;
◆What did you do during the power outage?@KEY()↓
◆I was sitting here ’cause I was scared.
@KEYNP()
;jpn:◆ていでんの あいだ↓
;jpn: なにしてました?@KEY()↓
;jpn:◆おれ こわくて↓
;jpn: ずっとここに↓
;jpn: しゃがんでましたよ。@KEYNP()
』

;@Habitat:フォーサイド/デパート/2階.食料品店
;@Person:食料店員
;@Figure:ウェートレスB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_FOOD
MSG_FOUR_DEPT_FOOD;@MiuraAppended
@GOSUB(MSG_SHOP_FOUR_FOOD)
』

;@Habitat:フォーサイド/デパート/3階.食料品売り場
;@Person:ふりかけ店員
;@Figure:ウェートレスB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_FURIKAKE
MSG_FOUR_DEPT_FURIKAKE;@MiuraAppended
@GOSUB(MSG_SHOP_FOUR_FURIKAKE)
』

;@Habitat:フォーサイド/デパート/3階.食料品売り場
;@Person:客B
;@Figure:おばさんA
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_B
MSG_FOUR_DEPT_B;
@CHKFGOTO(FLG_FOUR_DEPT_MSGCHG,_FOUR_DEPT_B_TMP)
◆mumble, mumble, mumble...man, I’m so busy.@KEY()↓
◆Don’t bother me, kid.
@KEYNP()
;jpn:◆あくせく↓
;jpn: あくせく いそがしいんだから@KEY()↓
;jpn:◆はなしかけないでね。@KEYNP()
』
_FOUR_DEPT_B_TMP;
◆I want to get out of here,@KEY()↓
◆because they suddenly shut down the store and the power goes out.@KEY()↓
◆There are lots of strange things happening in this department store.
@KEYNP()
;jpn:◆はやく かえろう。@WI(20)↓
;jpn: きゅうに へいてんしてみたり↓
;jpn: ていでんになったり‥‥@KEY()↓
;jpn:◆この デパート↓
;jpn: へんなこと ばっかりなんだもん。@KEYNP()
』


;@Habitat:フォーサイド/デパート/4階.ゲームセンター
;@Person:客C
;@Figure:少女D
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_C
MSG_FOUR_DEPT_C;
@CHKFGOTO(FLG_FOUR_DEPT_MSGCHG,_FOUR_DEPT_C_TMP)
◆Oh, so you’re skipping school too, right?
@KEYNP()
;jpn:◆あんたも↓
;jpn: がっこう さぼってるのね。@KEYNP()
』
_FOUR_DEPT_C_TMP;
◆I heard a sound like ”gwaaargh!” and it was loud.@KEY()↓
◆I wonder if someone was fighting.
@KEYNP()
;jpn:◆そっちの へやで クケクケいう↓
;jpn: こえが きこえたり↓
;jpn: ドタバタさわがしかったけど‥‥@KEY()↓
;jpn:◆けんかでも あったのかしら?@KEYNP()
』
;@Habitat:フォーサイド/デパート/4階.ゲームセンター
;@Person:客D
;@Figure:ヘルメット
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_D
MSG_FOUR_DEPT_D;
@CHKFGOTO(FLG_FOUR_DEPT_MSGCHG,_FOUR_DEPT_D_TMP)
◆When I grow up, I wanna work for APE as a programmer...@KEY()↓
◆Do you have any connections with those guys?↓
<Yes>
<No>
;DAN:Of course, you don't need to use APE.

;jpn:◆おれ おとなになったら@KEY()↓
;jpn:◆エイプに しゅうしょくして↓
;jpn: プログラマーやろうと↓
;jpn: おもってるんだけど‥‥。@KEY()↓
;jpn:◆おまえ コネない?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_DEPT_D_YES,_FOUR_DEPT_D_NO)

_FOUR_DEPT_D_NO;
_FOUR_DEPT_D_YES;
◆Oh, you didn’t have to answer.@KEY()↓
◆It was dumb of me to ask you that question.
@KEYNP()
;jpn:◆あ こたえなくていいよ。↓
;jpn: おまえなんかに きいた↓
;jpn: おれが バカだった。@KEYNP()
』
_FOUR_DEPT_D_TMP;
◆The power supply to the game was cut off.@KEY()↓
◆I wasted my money.
@KEYNP()
;jpn:◆ゲームの でんげんも↓
;jpn: きれちゃってたから↓
;jpn: コインを そんしちゃったよ。@KEYNP()
』

;@Habitat:フォーサイド/デパート/4階.ゲームセンター
;@Person:客E
;@Figure:マスク
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_E
MSG_FOUR_DEPT_E;
@CHKFGOTO(FLG_FOUR_DEPT_MSGCHG,_FOUR_DEPT_E_TMP)
◆I wanna save up some money and go to Summers or somewhere else to relax.
@KEYNP()
;jpn:◆かねためて サマーズとかに↓
;jpn: りょこうにいってさ↓
;jpn: のんびりしたいなぁ。@KEYNP()
』
_FOUR_DEPT_E_TMP;
◆Certainly, it’s very dangerous living in the city.
@KEYNP()
;jpn:◆まったく とかいは↓
;jpn: ぶっそうだよな。@KEYNP()
』

;@Habitat:フォーサイド/デパート/4階.事務室
;@Person:暗闇デパートのモンスター
;@Figure:HH教信者
;@AppearanceKey:FLG_FOUR_DEPT_BOSS_APPEAR/on
;@ActionScript:◆正面向いてそのまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_DEPT_BOSS
MSG_FOUR_DEPT_BOSS;
@CHKFGOTO(FLG_FOUR_DEPT_OK,MSG_SYS_HANASU_NG)
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
;◆Kuke Kuke Kukku
;jpn:◆クケッ クケッ クック@KEY()↓
;@WI(60)↓
;jpn:◆よく ここまでたどりついたな。
; @DSP_STS(STS_PC_NAME_NES)。@KEY()↓
;@KEY()↓
◆Gwaaagh, Gwarrrgh!.@KEY()↓
◆You finally made it.@KEY()↓
◆This department store is gonna be your grave!@KEY()↓
◆Gwaaagh.@KEY()↓
◆You will be gone, and you’ll be burning in...@KEY()↓
◆Well, you’ll go to heaven!@KEY()
;jpn:◆このデパートが おまえたちの↓
;jpn: はかばになるんだ! クケッ@KEY()↓
;jpn:◆しんで じごくへ‥‥いや↓
;jpn: てんごくへ いけ!@KEY()↓
@GOSUB(MSG_BATTLE_DEPT_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@BGMSTOP(0)
@OPEN(1)
◆...Even though you could beat me...@KEY()↓
◆Master Giygas will avenge me...@KEY()↓
;jpn:◆‥‥おれを たおしても‥‥クッ↓
;jpn: ギーグさまの‥‥@KEY()↓
@WI(60)↓
◆At this moment, @DSP_NAME(PC_PAULA) should be...Monotoli...@KEY()↓
◆Gwaaaaarrrrgh!!
@KEY()
;jpn:◆いまごろ @DSP_STS(STS_PC_NAME_PAULA)は↓
;jpn: モノトリーの‥‥ククッ@KEY()
@CLOSEALL()
@WI(60)
@SETF(FLG_FOUR_DEPT_OK)
@SETF(FLG_FOUR_DEPT_MSGCHG)
@CLRF(FLG_FOUR_DEPT_BOSS_APPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_FRSD_DEPT_MANAGER_A,ANIM_BLINK_SUICIDE)
@SETF(FLG_PHOTO_DEPT);撮り頃フラグ
@FUNC(5)			;毒死禁止
』

;----------------------------------------
;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人A
;@Figure:おじさんA
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_A
MSG_FOUR_A;
@CHKFGOTO(FLG_WIN_GIEGU,_FOUR_A_END)
@CHKFGOTO(FLG_FOUR_OK,_FOUR_A_LATER)
◆The city of Fourside has developed quite a bit@KEY()↓
◆since Mr. Geldegarde Monotoli hit the big time.@KEY()↓
◆It’s been good for the city.
@KEYNP()
;jpn:◆このフォーサイドのまちも↓
;jpn: モノモッチ・モノトリーさんが↓
;jpn: かつやくしはじめてから@KEY()↓
;jpn:◆ずいぶん はってんしたよね。↓
;jpn: わたしは よかったと おもうよ。@KEYNP()
』

_FOUR_A_LATER;#
◆That Mr. Monotoli has lost quite a bit of his resources...
@KEYNP()
;jpn:◆あの モノトリーさんは↓
;jpn: すっかり おちぶれたらしいねぇ。@KEYNP()
』
_FOUR_A_END;&
◆In the future, you will build cities and even create a country...@KEY()↓
◆...I’m counting on you.
@KEYNP()
;jpn:◆いずれ きみたちが↓
;jpn: まちや くにを↓
;jpn: つくっていくことに なるんだ。@KEY()↓
;jpn:◆‥‥たのむよ。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人B
;@Figure:OLA
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_B
MSG_FOUR_B;
@CHKFGOTO(FLG_WIN_GIEGU,_FOUR_B_END)
@CHKFGOTO(FLG_FOUR_OK,_FOUR_B_LATER)
◆I’ve heard some bad rumors about Mr. Montoli.@KEY()↓
◆I heard he made a deal with a pure evil entity in exchange for power...@KEY()↓
◆you know...stuff like that.
@KEYNP()
;jpn:◆モノトリーさんに かんしては↓
;jpn: わるいうわさも↓
;jpn: ずいぶん きくのよね。@KEY()↓
;jpn:◆あくまと とりひきして↓
;jpn: いまのけんりょくを↓
;jpn: ゆずりうけたとか‥‥ね。@KEYNP()
』

_FOUR_B_LATER;#
◆Just as I thought, Monotoli has a portion of Evil’s power.
@KEYNP()
;jpn:◆やっぱりモノトリーって↓
;jpn: あくまに ちからを↓
;jpn: かりてたらしいわねぇ。@KEYNP()
』
_FOUR_B_END;&
◆My grandpa told me that everyone has at least one outstanding skill.@KEY()↓
◆When I look at you, I know he’s right.
@KEYNP()
;jpn:◆どんなこどもにも↓
;jpn: なんか とりえがあるって↓
;jpn: おじいちゃんが いってたけど@KEY()↓
;jpn:◆きみたちを みてると↓
;jpn: ほんとに そうだとおもうわね。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人C
;@Figure:トランペッター
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_C
MSG_FOUR_C;
@CHKFGOTO(FLG_FOUR_OK,_FOUR_C_LATER)
◆In the old days, Mr. Monotoli was just a regular,@KEY()↓
◆unattractive real estate agent.@KEY()↓
◆Now he has the power to control the police force.@KEY()↓
◆I don’t think the city of Fourside is better than before.
@KEYNP()
;jpn:◆むかしは モノトリーさんは↓
;jpn: ふうさいのあがらない↓
;jpn: ただの ふどうさんやだったんだ。@KEY()↓
;jpn:◆いまじゃ けいさつまで↓
;jpn: じゆうに うごかせるっていうぜ。@KEY()↓
;jpn:◆おれは フォーサイドのまちが↓
;jpn: よくなったなんて↓
;jpn: とても おもえないな。@KEYNP()
』

_FOUR_C_LATER;
◆You’re very young,@KEY()↓
◆but you brought something very precious back to the people in this town.@KEY()↓
◆Thank you.
@KEYNP()
;jpn:◆あんたは ちいさいけど↓
;jpn: このまちのひとびとに↓
;jpn: たいせつなものを@KEY()↓
;jpn:◆とりもどしてくれた。↓
;jpn: ありがとうよ。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人D
;@Figure:サラリーマンC
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_D
MSG_FOUR_D;
@CHKFGOTO(FLG_FOUR_OK,_FOUR_D_LATER)
◆The Runaway Five from Twoson seem very popular.@KEY()↓
◆I heard that the Topolla Theater is always full.
@KEYNP()
;jpn:◆ツーソンから やってきた↓
;jpn: トンズラブラザーズってバンドは↓
;jpn: だいにんきだな。@KEY()↓
;jpn:◆トポロげきじょうは↓
;jpn: いつも まんいんらしいよ。@KEYNP()
』

_FOUR_D_LATER;
◆I heard you’re friends of the Runaway Five.@KEY()↓
◆I’m jealous.
@KEYNP()
;jpn:◆きみは トンズラブラザーズと↓
;jpn: しりあいだったらしいね。↓
;jpn: うらやましいなぁ。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人E
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_E
MSG_FOUR_E;
@CHKFGOTO(FLG_FOUR_OK,_FOUR_E_LATER)
◆Speaking of the Topolla Theater, there’s a new singer called Venus.@KEY()↓
◆She’s better than the Runaway Five.@KEY()↓
◆I’m totally bonkers about her...
@KEYNP()
;jpn:◆トポロげきじょうといえば↓
;jpn: トンズラ・バンドより@KEY()↓
;jpn:◆ビーナスって しんじんが↓
;jpn: さいこうだね。@KEY()↓
;jpn:◆ぼく‥‥めろめろなんだ。@KEYNP()
』

_FOUR_E_LATER;
◆Venus...@KEY()↓
◆She’s become even more beautiful.
@KEYNP()
;jpn:◆ビーナス‥‥↓
;jpn: さいきん またまた↓
;jpn: きれいになったね。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人F
;@Figure:ツッパリ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_F
MSG_FOUR_F;
;(酒場の近く)
@CHKFGOTO(FLG_WIN_GIEGU,_FOUR_F_END)
@CHKFGOTO(FLG_FOUR_OK,_FOUR_F_LATER)
◆I don’t get it.@KEY()↓
◆I heard that a guy who looks like Monotoli has been hanging out at Jackie’s Cafe.@KEY()↓
◆You know, the totally unpopular place.@KEY()↓
◆I heard he quietly goes in and out.
@KEYNP()
;jpn:◆どうしてなんだろう?↓
;jpn: あの おおがねもちの↓
;jpn: モノトリーに よくにたおとこが@KEY()↓
;jpn:◆うらぶれた ボルヘスのさかばに↓
;jpn: でいりしてるらしいんだ。↓
;jpn: こそこそと さ。@KEYNP()
』

_FOUR_F_LATER;#
◆Jackie’s Cafe was where the deal with the evil entity took place.@KEY()↓
◆I can’t believe it...can you?
@KEYNP()
;jpn:◆あのボルヘスのさかばが↓
;jpn: あくまとの とりひきばしょだった↓
;jpn: なんて‥‥ねぇ。@KEYNP()
』
_FOUR_F_END;&
◆You boys are young, but you did a great job here and out there.
@KEYNP()
;jpn:◆きみたち ちっちゃいけど↓
;jpn: いろいろ↓
;jpn: だいかつやくだったんだねぇ。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:街の人G(酔っ払い)
;@Figure:おじさんB
;@AppearanceKey:0
;@ActionScript:◆千鳥足
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_G
MSG_FOUR_G;
@CHKFGOTO(FLG_FOUR_OK,_FOUR_G_LATER)
◆No one know anything.@KEY()↓
◆Grrrr.@KEY()↓
◆Monotoli’s toadies stole everything from me, including my house and land.@KEY()↓
◆Weep, weep...@KEY()↓
◆They are evil incarnate.@KEY()↓
◆Lawyers, policemen, everyone that follows Monotoli!@KEY()↓
◆They’re all his toadies!@KEY()↓
◆No matter how you fight him, you can’t win!@KEY()↓
◆Yeah, yeah, I’m okay...just leave me here to cry into my cappucino!@KEY()↓
◆Nosy!
@KEYNP()
;jpn:◆みんな なんにもしらねぇんだ!↓
;jpn: ヒック@WI(15)↓
;jpn: おれはモノトリーのてしたに@KEY()↓
;jpn:◆とちや いえを ぜーんぶ↓
;jpn: だましとられたんだぞ。 ウィー。↓
;jpn: あいつらは アクマだ。@KEY()↓
;jpn:◆べんごしも けいさつも↓
;jpn: みんな モノトリーの てしただ!↓
;jpn: どうあがいても かてやしねぇ!@KEY()↓
;jpn:◆おれは よっぱらっちゃ↓
;jpn:       ヒック@WI(15)↓
;jpn: いねえよ! バーローイ!@KEYNP()
』

_FOUR_G_LATER;
◆Hic!@KEY()↓
◆I’m fine.@KEY()↓
◆Hic!@KEY()↓
◆I’m not drinking the... hic!@KEY()↓
◆I hate these hiccups...@KEY()↓
◆Yes, they’re... hic!@KEY()↓
◆Another cappucino here!@KEY()↓
◆Hic!
@KEYNP()
;jpn:◆ヒック@WI(15) おれは よっぱらって↓
;jpn: ヒック@WI(15) なんか ヒック ないよ。↓
;jpn: これは しゃっくりだ。@KEY()↓
;jpn:◆ほんと ヒック@WI(15) だよ。↓
;jpn: おれの めを みろ!↓
;jpn: ヒック。@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:警官1
;@Figure:警官
;@AppearanceKey:0
;@ActionScript:◆尾行
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_COP_1
MSG_FOUR_COP_1;
@CHKFGOTO(FLG_WIN_GIEGU,_FOUR_COP_1_END)
@CHKFGOTO(FLG_FOUR_OK,_FOUR_COP_1_LATER)
◆Protect Mr. Monotoli first.@KEY()↓
◆The safety of the citizens of this city comes second.@KEY()↓
◆Heh heh heh.@KEY()↓
◆That’s our job, you know.@KEY()↓
◆Heh heh.
@KEYNP()
;jpn:◆しみんの あんぜんよりも↓
;jpn: モノトリーさまの あんぜんを↓
;jpn: まもるのが@KEY()↓
;jpn:◆へっへっへ↓
;jpn: おれたちの にんむだよ。@WI(15)↓
;jpn: ここは そういうまちさ。へっへ。@KEYNP()
』

_FOUR_COP_1_LATER;#
◆It was stupid of me to let Monotoli do whatever he wanted.@KEY()↓
◆We’ll do our best to create a safe environment in which people can live safely.
@KEYNP()
;jpn:◆モノトリーごときに↓
;jpn: すきかってなことを させてた↓
;jpn: われわれが バカだった。@KEY()↓
;jpn:◆しみんの みんなが↓
;jpn: あんぜんに いきられるように↓
;jpn: おれたちは がんばるよ。@KEYNP()
』
_FOUR_COP_1_END;&
◆You’re getting in better shape every time I see you.@KEY()↓
◆Don’t you wanna be a police officer?
@KEYNP()
;jpn:◆きみ ますます↓
;jpn: いいからだになったな。@KEY()↓
;jpn:◆けいさつかんに ならないか?@KEYNP()
』


;@Habitat:フォーサイド/フィールド/街の至る所
;@Person:警官2
;@Figure:警官
;@AppearanceKey:0
;@ActionScript:◆正面向いてそのまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_COP_2
MSG_FOUR_COP_2;
@CHKFGOTO(FLG_WIN_GIEGU,_FOUR_COP_2_END)
@CHKFGOTO(FLG_FOUR_OK,_FOUR_COP_2_LATER)
◆You boys are sneaking around, looking for Mr. Monotoli, aren’t you?@KEY()↓
◆If I catch you boys doing anything, I’ll arrest you−−no questions asked!@KEY()↓
◆Be prepared!@KEY()↓
;jpn:◆おまえら モノトリーさまのことを↓
;jpn: ききまわってるらしいな。@KEY()↓
;jpn:◆なんかあったら↓
;jpn: しょっぴいてやるからな!↓
;jpn: かくごしておけよ。@KEY()↓
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Got it, @DSP_NAME(0)...@KEY()↓
◆Ha ha ha.@KEY()↓
◆I’ve already checked out your name...
@KEYNP()
;jpn:◆わかったか@WI(10) @DSP_NAME(0)さんよ‥‥。@KEY()↓
;jpn:◆ふふふ おまえのなまえくらい↓
;jpn: とっくに しらべてあるさ。@KEYNP()
』

_FOUR_COP_2_LATER;#
◆Oh, that rude comment was a slip of the tongue.@KEY()↓
◆Now I feel like Monotoli should eat my shorts.@KEY()↓
;jpn:◆おっと いつぞやは↓
;jpn: くちがすべって↓
;jpn: しつれいなこと いいましたが‥‥@KEY()↓
;jpn:◆いまは モノトリーなんて↓
@GET_ORDER_PLAYER(1)
@SET_REG(0)
;jpn: くそくらえですよ @DSP_NAME(0)さま。@KEYNP()
;男女区別
◆@DSP_NAME(0), @XCHG()@GOSUB(MSG_ESUB_SIR_MAAM).
@KEYNP()
』
_FOUR_COP_2_END;&
◆I misjudged you guys.@KEY()↓
◆I thought you were little snot−nosed punks.@KEY()↓
◆...I know better now.
@KEYNP()
;jpn:◆じぶんは あなたがたのことを↓
;jpn: ちゃらちゃらした↓
;jpn: パッパラパーなガキどもだと@KEY()↓
;jpn:◆ごかいしとりましたが@WI(30)↓
;jpn: ‥‥みなおしましたです。@KEYNP()
』

;@Habitat:フォーサイド/フィールド/モノトリービル付近
;@Person:おつかいのメイド
;@Figure:ウェートレスB
;@AppearanceKey:FLG_FOUR_MAID_APPEAR/on
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MAID
MSG_FOUR_MAID;
;モノトリービルの近く
;@CHKFGOTO(FLG_FOUR_MAID_THANKS,_FOUR_MAID_THANKS_2)
◆I kept asking around for Trout−flavored yogurt, but...
@KEYNP()

;jpn:◆あちこちの ひとに↓
;jpn: 「いちごとうふ」のことを↓
;jpn: たずねてまわったんだけど‥‥
@Q_HAVE(PC_ALL,GDS_TOOL_ICHIGO_TOFU)
@TRUE_GOTO(_FOUR_MAID_THANKS)
;@KEYNP()
』

_FOUR_MAID_THANKS;
@KEY()↓
◆What?@KEY()↓
◆You have a ”@DSP_GOODS(GDS_TOOL_ICHIGO_TOFU)”?@KEY()↓
◆May I have it?@KEY()↓
;jpn:◆えっ 「ぐるめとうふマシン」を↓
;jpn: もってるの?!@WI(15)↓
;jpn: ゆずってくださるの!@KEY()↓
@SE(SE_se76_my_give)
@WI(10)
◆(Before you could answer, she took the ”@DSP_GOODS(GDS_TOOL_ICHIGO_TOFU).”)@KEY()↓
◆Now I can make Trout−flavored yogurt for my guests.@KEY()↓
◆...You are so kind, I’ll make some for you.@KEY()↓
◆My room’s on the 48th floor.@KEY()↓
◆Don’t forget to drop by!
@KEYNP()
;jpn:◆(「ぐるめとうふマシン」を↓;←(仮)追加 
;jpn: ごういんに もっていかれた)@KEY()↓;←(仮)追加
;jpn:◆これで おきゃくさまに↓
;jpn: 「いちごとうふ」を↓
;jpn: つくってさしあげられるわ!@KEY()↓
;jpn:◆‥‥なんてしんせつなひと↓
;jpn: あなたにも ごちそうするわね。@KEY()↓
;jpn:◆わたしのへやは 48かいよ。↓
;jpn: きっと きてね!@KEY()↓
@CLOSEALL()
@GOODSOUT( PC_ALL, GDS_TOOL_ICHIGO_TOFU )
@SETF( FLG_FOUR_MAID_THANKS )
@REMOVE_CHAR( PRSN_FRSD_FIELD_J, ANIM_MAID_INTO_BUILDING )
@WAITSYS()
;振り向いてセリフ
@COLD_CHAR( PRSN_FRSD_FIELD_J )
@GET_CHAR_DIR( PRSN_FRSD_FIELD_J, 1, PC_ALL )
@SET_CHAR_DIR( PRSN_FRSD_FIELD_J, 0 )
@WI( 20 )
@OPEN( 1 )
◆My room’s on the 48th floor.@KEY()↓
◆Don’t forget to drop by!
@KEYNP()
;jpn:◆わたしのへやは 48かいよ。↓
;jpn: きっと きてね!@KEY()↓
@CLOSEALL()
@FRESH_CHAR( PRSN_FRSD_FIELD_J )
@CLRF(FLG_FOUR_MAID_APPEAR)
』

;◆モノトリーさまの かわいがってる↓
; ポーキーさまが↓
; いちごとうふが たべたいって‥‥@KEY()↓
;◆どこに うってるのかも↓
; わかんないし‥‥。↓
; あなた しってる?@KEY()↓
;◆そうよねー しらないわよねー。@KEYNP()
』

;_FOUR_MAID_THANKS;
;◆えっ 「ぐるめとうふマシン」を
; もってるの?!↓
; ゆずってくださるの!@KEY()↓
;@SE(SE_se76_my_give)
;@WI(10)
;◆これで おきゃくさまに↓
; 「いちごとうふ」を↓
; つくってさしあげられるわ!@KEY()↓
;◆‥‥なんてしんせつなひと↓
; あなたにも ごちそうするわね。@KEY()↓
;@GOODSOUT(PC_ALL,GDS_TOOL_ICHIGO_TOFU)
;@SETF(FLG_FOUR_MAID_THANKS)
;
;_FOUR_MAID_THANKS_2;
;◆わたしのへやは 48かいよ。↓
; きっと きてね!@KEYNP()
;@CLRF(FLG_FOUR_MAID_APPEAR)
;』

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:やられトンチキ
;@Figure:倒れているトンチキ
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_TONCHIKI
MSG_FOUR_TONCHIKI;
;@SET_LOOPREG(PC_NESS)
;@TRUE_GOTO(_FOUR_TONCHIKI_NESS_DEAD)
◆...@KEY()↓
◆*Wheeze, wheeze*...@KEY()↓
◆... ...@KEY()↓
◆Aren’t you @DSP_NAME(PC_NESS)...?@KEY()↓
◆...I can’t see too well...@KEY()↓
◆Everything’s blurry...@KEY()↓
◆You are @DSP_NAME(PC_NESS), arent’ you?@KEY()↓
◆It’s me, we met in Twoson...@KEY()↓
◆Everdred from Burglin Park.@KEY()↓
◆You must remember.@KEY()↓
◆I’m the best thief around.@KEY()↓
◆That... Carpainter in Happy Happy Village was hiding something...@KEY()↓
◆*wheeze, wheeze*... strange.@KEY()↓
◆I stole it, and thought about selling it in the big city...@KEY()↓
◆An old, city−wise man called it Mani Mani.@KEY()↓
◆It’s a strange−colored, doll−looking thing.@KEY()↓
◆...Ohh... *wheeze*, I’m in pain.@KEY()↓
◆...and@KEY()↓
◆...@KEY()↓
◆Monotoli tricked me and stole it... from me!@KEY()↓
◆He tricked a thief!@KEY()↓
◆He wanted me out of the way because I know his secret...@KEY()↓
◆He gets his evil power from that statue!@KEY()↓
◆...Listen!@KEY()↓
◆I’ll tell you only once.@KEY()↓
◆At the cafe, check... behind... the counter...@KEY()↓
◆...*Gasp*...@KEY()↓
;jpn:◆‥‥‥@KEY()↓
;jpn:◆ゼイ ゼイ@KEY()↓
;jpn:◆‥‥‥‥‥‥‥‥‥@DSP_STS(STS_PC_NAME_NES)↓
;jpn: @DSP_STS(STS_PC_NAME_NES)‥‥@WI(30)だろ?@KEY()↓
;jpn:◆‥‥めのまえが@WI(10) ぼ@WI(10) ぼやけて↓
;jpn: よく みえないけど‥‥↓
;jpn: おまえ @DSP_STS(STS_PC_NAME_NES)‥‥@WI(30)だよな?@KEY()↓
;jpn:◆お@WI(10) おれだよ ツーソンの‥‥@KEY()↓
;jpn:◆ヌスットひろばの トンチキだよ。↓
;jpn: おぼえてるな。@WI(20)↓
;jpn: せかいいちのドロボーだよ。@KEY()↓
;jpn:◆あの‥‥@WI(20)ハッピーハッピーむらの↓
;jpn: カーペインターが@WI(20)↓
;jpn: おかしなものを‥‥ゼーゼー@KEY()↓
;jpn:◆かくしもってたんだ。@WI(30)↓
;jpn: そいつを おれが ぬすんできて↓
;jpn: このまちで うろうとおもった‥。@KEY()↓
;jpn:◆ものしりのじいさんが↓
;jpn: 「マニマニのあくま」と↓
;jpn: よんでた。@KEY()↓
;jpn:◆ふきつな いろをした↓
;jpn: にんぎょうだった。@WI(30)↓
;jpn: ‥‥う@WI(20) ‥‥う@WI(20) くるしいぜ。@KEY()↓
;jpn:◆‥‥で@WI(20)↓
;jpn: ‥‥‥@KEY()↓
;jpn:◆モノトリーのやろうに↓
;jpn: だまされて‥‥@WI(20)とられちまった。@WI(30)↓
;jpn: ドロボーのおれを@KEY()↓
;jpn:◆だましやがって@WI(20)↓
;jpn: しかも このヒミツをしっている↓
;jpn: おれを‥‥@KEY()↓
;jpn:◆つけねらって↓
;jpn: けそうと しやがったんだ。@KEY()↓
;jpn:◆やつは あの にんぎょうから↓
;jpn: あくまのパワーを うけてるんだ。@KEY()↓
;jpn:◆‥‥いいか?@KEY()↓
;jpn:◆いちどしか いわないから↓
;jpn: よくきけ。@KEY()↓
;jpn:◆さかばの‥‥@WI(20)↓
;jpn: カウンターのなかをしらべるんだ。↓
;jpn: ‥‥ウッ‥‥@KEY()↓
@CHKFGOTO(FLG_TEMP_8,_FOUR_TONCHIKI_Q2)
@SETF(FLG_TEMP_8)
◆I said I’d tell you only once...@KEY()↓
◆But if you insist, I’ll tell you once more...@KEY()↓
◆...*gasp, gasp*@KEY()↓
◆Do do do you wanna hear it again?↓
<Yes>
<No>
;jpn:◆さっき いちどしか↓
;jpn: いわないと いったものの‥‥@KEY()↓
;jpn:◆どうしてもと いうなら↓
;jpn: もういっかい いうが‥‥@KEY()↓
;jpn:◆‥‥ウッ@WI(20)↓
;jpn: き@WI(15) き@WI(15) ききたいか?@WI(20)↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(MSG_FOUR_TONCHIKI,_FOUR_TONCHIKI_NO)
@GOTO(_FOUR_TONCHIKI_NO)

_FOUR_TONCHIKI_Q2;
◆I’ve told you twice already...@KEY()↓
◆But if you wanna hear one more time...@KEY()↓
◆I’ll tell you once more...@KEY()↓
◆D...D...do...you wanna hear it again?↓
<Yes>
<No>
;jpn:◆さっきから にかいも↓
;jpn: いったけど‥‥@KEY()↓
;jpn:◆どうしてもと いうなら↓
;jpn: もういっかい いうが‥‥@KEY()↓
;jpn:◆く@WI(15) く@WI(15) くるしい! ゲホゲホ。↓
;jpn: ‥‥き@WI(15) き@WI(15) ききたいか?@WI(20)↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_TONCHIKI_YES2,_FOUR_TONCHIKI_NO)
@GOTO(_FOUR_TONCHIKI_NO)

_FOUR_TONCHIKI_YES2;
◆I’m not such a kind man.@KEY()↓
◆I’m slipping away...@KEY()↓

;jpn:◆おれも そんなに↓
;jpn: おひとよしじゃねぇ。@KEY()↓
;jpn:◆ほんとに しにそうなんだ。@KEY()↓

_FOUR_TONCHIKI_NO;
◆...Before I go, here’s my last haiku poem:@KEY()↓
◆When on your way out@KEY()↓
◆Be sure that you say goodbye@KEY()↓
◆then lock the door tight.@KEY()↓
◆This is my final request...@KEY()↓
◆Don’t follow me.@KEY()↓
◆I must be on my way...@KEY()↓
◆Whoa....@KEY()↓
◆So...long!
@KEYNP()
;jpn:◆‥‥では しぬまえに いっく。@WI(30)↓
;jpn: 「おでかけは@WI(20) ひとこえかけて↓
;jpn:  かぎかけて     トンチキ」@KEY()↓
;jpn:◆おれの さいごのたのみだ。↓
;jpn: あとを おうんじゃねぇよ。@WI(20)↓
;jpn: ドロボーのいぢ‥‥@WI(10)が@WI(10)あ@WI(10)る。@KEY()↓
;jpn:◆(ヨロヨロ)↓
;jpn: あ・@WI(20)ば・@WI(20)よ!@KEY()
@SETF(FLG_FOUR_TONCHIKI)
@CLRF(FLG_FOUR_TONCHIKI_APPEAR)
@GOSUB(MSG_EVT_72_TONCHIKI)
』

;_FOUR_TONCHIKI_NESS_DEAD;
;◆(ネスが↓
; きぜつかダイヤのときの↓
; メッセージです)
;@KEYNP()
;@!

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:人集りA
;@Figure:アーティスト
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_CROWD_A
MSG_FOUR_CROWD_A;
@CHKFGOTO(FLG_FOUR_TONCHIKI,_FOUR_CROWD_A_TMP)
◆There’s a person lying on the ground.@KEY()↓
◆I wonder if he’s...he’s...
@KEYNP()
;jpn:◆ひとが たおれているんだけど↓
;jpn: しんでるのかなぁ。@KEYNP()
』
_FOUR_CROWD_A_TMP;
◆He’s not dead...@KEY()↓
◆I thought he may have passed on.
@KEYNP()
;jpn:◆しんでるわけじゃ↓
;jpn: なかったんだなぁ。@KEY()↓
;jpn:◆‥‥でも しにそうだったな。@KEYNP()
』

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:人集りB
;@Figure:OLG
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_CROWD_B
MSG_FOUR_CROWD_B;
@CHKFGOTO(FLG_FOUR_TONCHIKI,_FOUR_CROWD_B_TMP)
◆Oooo...I don’t like seeing a corpse around here.
@KEYNP()
;jpn:◆やぁねぇ こんなところで↓
;jpn: しんでるなんて。@KEYNP()
』
_FOUR_CROWD_B_TMP;
◆He should really go to the hospital like other sick people do.
@KEYNP()
;jpn:◆ちゃんと びょういんに↓
;jpn: いけばいいのにねぇ。@KEYNP()
』

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:人集りC
;@Figure:ゴロツキ
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_CROWD_C
MSG_FOUR_CROWD_C;
@CHKFGOTO(FLG_FOUR_TONCHIKI,_FOUR_CROWD_C_TMP)
◆He’s breathing...@KEY()↓
◆Has he just been drinking?
@KEYNP()
;jpn:◆いきは してるみたいだけど↓
;jpn: ただの よっぱらいかなぁ。@KEYNP()
』
_FOUR_CROWD_C_TMP;
◆Do you know him?@KEY()↓
◆You must be a dangerous kid!@KEY()↓
◆I’ll bet you’re on your way to Jackie’s Cafe right now!
@KEYNP()
;jpn:◆きみ@GOSUB(MSG_SUB_TATI)↓
;jpn: あのおとこの↓
;jpn: しりあいなの?@KEY()↓
;jpn:◆ぶっそうな コドモだなぁ。@KEY()↓
;jpn:◆ボルヘスのさかばに↓
;jpn: いくのかい?@KEYNP()
』

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:人集りD(道を塞ぐ)
;@Figure:ボロ
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_CROWD_D
MSG_FOUR_CROWD_D;
@CHKFGOTO(FLG_FOUR_TONCHIKI,_FOUR_CROWD_D_TMP)
@CHKFGOTO(FLG_TEMP_1,_FOUR_CROWD_D_YES_TEMP)
◆Don’t cut in front of me!@KEY()↓
◆If you give me somethin’, I’ll let you have my spot.@KEY()↓
◆Will you give me somethin’?↓
<Yes>
<No>
;jpn:◆ちゃんと じゅんばんにならべよ。↓
;jpn: なんかくれたら↓
;jpn: ばしょを ゆずってやるけどよ。@KEY()↓
;jpn:◆くれるか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_CROWD_D_YES,_FOUR_CROWD_D_NO)
_FOUR_CROWD_D_NO;
←
◆Then stay right there where you’re too short to see a thing!
@KEYNP()
;jpn:◆じゃ なんにもみえないまま↓
;jpn: ずっと そこに たってろよ。@KEYNP()
』
_FOUR_CROWD_D_YES;
◆So, what do I get?
;jpn:◆なにをくれるんだ。@WKEY(30)
@GOSUB(MSG_SEL_GOODS)
@WI(60)↓
@FALSE_GOTO(_FOUR_CROWD_D_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@FALSE_GOTO(_FOUR_CROWD_D_UNABLE)
;◆@DSP_GOODS(0)?
◆Are you sure?↓
<Yes>
<No>
;jpn:◆@DSP_GOODS(0)か。↓
;jpn: ほんとうにくれるのか?↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_CROWD_D_YES,_CROWD_D_NO)
_CROWD_D_NO;
◆If you don’t want to give me somethin’,@KEY()↓
◆don’t say you’re gonna give me somethin’...@KEY()↓
;jpn:◆‥‥くれないなら↓
;jpn: くれるなんて いうなよ。@KEY()↓
@GOTO(_FOUR_CROWD_D_YES)

_CROWD_D_YES;
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@SE(SE_se76_my_give)
@WI(1)
◆All right, take my place.
@KEYNP()
;jpn:◆よっしゃ。↓
;jpn: じゃ はいっていいよ。@KEYNP()
@SETF(FLG_TEMP_1)
@GOSUB(MSG_EVT_72_BORO)
』

_FOUR_CROWD_D_YES_TEMP;
◆All right, take my place.
@KEYNP()
;jpn:◆よっしゃ。↓
;jpn: じゃ はいっていいよ。@KEYNP()
』

_FOUR_CROWD_D_UNABLE;
◆Give me somethin’ that makes me really happy!@KEY()↓
◆And do it in a nice way!
@KEYNP()
;jpn:◆もっと おれの↓
;jpn: よろこぶものを くれよ!@WI(20)↓
;jpn: おもいやりを もってさ。@KEYNP()
』

_FOUR_CROWD_D_TMP;
◆Don’t you feel better since you had the chance to talk with your friend?@KEY()↓
◆I helped you find him.
@KEYNP()
;DAN: I remember this scene, but I have no 
;jpn:◆おれの おかげで↓
;jpn: しりあいと はなせて↓
;jpn: よかったな。@KEYNP()
』

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:人集りE
;@Figure:おばさんA
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_CROWD_E
MSG_FOUR_CROWD_E;
@CHKFGOTO(FLG_FOUR_TONCHIKI,_FOUR_CROWD_E_TMP)
◆Oh, no no no.@KEY()↓
◆I don’t want to go like that.@KEY()↓
◆I’m glad it wasn’t me.
@KEYNP()
;jpn:◆おお いやだ いやだ。↓
;jpn: あんなめに あいたくないね。↓
;jpn: じぶんじゃなくて よかったよ。@KEYNP()
』
_FOUR_CROWD_E_TMP;
◆Is that man going to...to...?
@KEYNP()
;jpn:◆あの おとこ↓
;jpn: しんじゃうのかしらね。@KEYNP()
』

;@Habitat:フォーサイド/フィールド/ボルヘス酒場付近
;@Person:人集りF
;@Figure:おばさんB
;@AppearanceKey:FLG_FOUR_TONCHIKI_APPEAR/on
;@ActionScript:◆演出コンテ#10.6
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_CROWD_F
MSG_FOUR_CROWD_F;
@CHKFGOTO(FLG_FOUR_TONCHIKI,_FOUR_CROWD_F_TMP)
◆He doesn’t look like a nice man.
@KEYNP()
;jpn:◆あんまり にんそうのいいひとじゃ↓
;jpn: ないわねぇ。@KEYNP()
』
_FOUR_CROWD_F_TMP;
◆He stared right at me...@KEY()↓
◆Ooo...it was scary!
@KEYNP()
;jpn:◆わたしを‥‥↓
;jpn: にらみつけていったわ。@KEY()↓
;jpn:◆‥‥こわかったぁ。@KEYNP()
』

;◆あんた@GOSUB(MSG_SUB_TATI)も↓
; きをつけるんだよ。@KEYNP()
;』


;@Habitat:フォーサイド/フィールド/
;@Person:武器専門男
;@Figure:武器男
;@AppearanceKey:0
;@ActionScript:◆きょろきょろ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_WEAPON
MSG_FOUR_WEAPON;@MiuraAppended
@GOSUB(MSG_SHOP_FOUR_WEAPON)
』

;@Habitat:フォーサイド/フィールド/
;@Person:ジャンク屋
;@Figure:パンク青年
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_JUNK
MSG_FOUR_JUNK;@MiuraAppended
;◆ガラクタだけど↓
; ほしいかい?@KEY()
@GOSUB(MSG_SHOP_FOUR_JUNK)
』


;--------------------------------------------------

;@Habitat:フォーサイド/マグネットヒル/7下水道
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_MGNT_BOSS/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_FOUR_MGNT_BOSS
MSG_FOUR_MGNT_BOSS;
@CHKFGOTO(FLG_WIN_MGNT_BOSS,MSG_SYS_HANASU_NG)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆You finally got here.@KEY()↓
◆This is the fifth ”Your Sanctuary” location.@WI(20)  But it’s mine now.@KEY()↓
◆Take it from me,@WI(30) if you dare...
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは 5ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし いまは↓
;jpn: わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_MGNT_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_FRSD_MAGNET_7_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_MGNT_BOSS)
』
;------------------------------------------------

;以下増補

MSG_FOUR_INFORMER_A;
;フォーサイドの埋蔵金情報の人
@CHKFGOTO(FLG_DSRT_ITEM_DIA,_FOUR_INFORMER_A_LATER)
◆What happened to those guys digging for the buried gold?@KEY()↓
◆If they found the gold,it would be worth a huge amount of money.@KEY()↓
◆They’d be able to pay off a million dollar debt very easily.@KEY()↓
◆If I were them, I’d go to Japan and live it up!
@KEYNP()
;jpn:◆さばくの↓
;jpn: まいぞうきん はっくつは↓
;jpn: どうなったんだろう。@KEY()↓
;jpn:◆もし みつかったら↓
;jpn: たいへんな きんがくだろ。@KEY()↓
;jpn:◆なんびゃくまんおくドルの↓
;jpn: しゃっきんだって↓
;jpn: かえせちゃうよなぁ。@KEY()↓
;jpn:◆オレだったら↓
;jpn: ニッポンへ いって@KEY()↓
;jpn:◆トーキョーの「かつまん」の↓
;jpn: ヒレカツていしょくを↓
;jpn: 3かいくらい くっちゃうね。@KEYNP()
』
_FOUR_INFORMER_A_LATER;
◆I heard they couldn’t find the buried gold.@KEY()↓
◆Those guys worked really hard, but all they got was a diamond!
@KEYNP()
;jpn:◆まいぞうきん‥‥↓
;jpn: でなかったらしいね。@KEY()↓
;jpn:◆せっかく あれだけ↓
;jpn: くろうしたのに↓
;jpn: ダーイヤモンドじゃあねー!@KEYNP()
』
;-------------------------------------------------

MSG_FOUR_INFORMER_B;
◆I wonder why the department store’s closed.
@KEYNP()
;jpn:◆どうして デパートが↓
;jpn: へいてんしてるのかなぁ。@KEYNP()
』

MSG_FOUR_INFORMER_C;
◆When Monotoli became the owner,@KEY()↓
◆this department store began having strange happenings.
@KEYNP()
;jpn:◆モノトリーが オーナーになって↓
;jpn: このデパートは↓
;jpn: ヘンなことが おおくなったねぇ。@KEYNP()
』

MSG_FOUR_INFORMER_D;
◆I heard the department store finally re−opened.@KEY()↓
◆Hope they have a boffo sale.
@KEYNP()
;jpn:◆へいてんしていた デパートが↓
;jpn: やっと あいたらしいね。@WI(20)↓
;jpn: バーゲンでも やらないかな。@KEYNP()
』
;-------------------------------------

MSG_FOUR_INFORMER_E;032_Cマグネットボスを倒したら消える
◆Behind this wall, things seem very strange.@KEY()↓
◆I feel like this isn’t my place...@KEY()↓
◆Maybe it’s your place.
@KEYNP()
;jpn:◆どうも このへいのなかは↓
;jpn: あやしいなぁ。@KEY()↓
;jpn:◆‥‥なんか おれのばしょじゃ↓
;jpn: ないような きがするんだけど‥‥@KEY()↓
;jpn:◆あんがい おまえのばしょ↓
;jpn: だったりして。@KEYNP()
』

MSG_FOUR_INFORMER_F;マグネットボスを倒したら消える
◆The boy stuck to the wall...may be a Peeping Tom.
@KEYNP()
;jpn:◆そこの へいに↓
;jpn: はりついてるヤツ‥‥@KEY()↓
;jpn:◆のぞきオトコかもしれないわね。@KEYNP()
』
;-------------------------------------------------

MSG_FOUR_BRGS_WARE_RAT;024_H
@CHKFGOTO(FLG_FOUR_OK,_FOUR_BRGS_WARE_RAT_LATER)
◆(You were wandering around the warehouse with a vacant, far away look in your eyes.@KEY()↓
◆Were you day dreaming?)
@KEYNP()
;jpn:◆(おまえ↓
;jpn: とおくをみているような↓
;jpn: うつろなめをして@KEY()↓
;jpn:◆そうこのなかを↓
;jpn: あるきまわってたぞ。@KEY()↓
;jpn:◆ゆめでも みてたのか?)@KEYNP()
』
_FOUR_BRGS_WARE_RAT_LATER;
◆I’m lucky I’m a rat.@WI(20)  We have such easy lives...
@KEYNP()
;jpn:◆(ネズミは きらくでいいや)@KEYNP()
』
;-------------------------------------------------

MSG_FOUR_MONOTOLY_END;&最終戦闘後のモノトリー(エレベーターボーイ)
◆Oh, @DSP_STS(STS_PC_NAME_NES)@KEY()↓

;jpn:◆おお @DSP_STS(STS_PC_NAME_NES)くん@KEY()↓
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_FOUR_MONOTOLY_END_MAIN)
;
◆@DSP_STS(STS_PC_NAME_PAULA)@KEY()↓

;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)ちゃん@KEY()↓
;
_FOUR_MONOTOLY_END_MAIN;
◆I’m Geldegarde Monotoli.@KEY()↓
◆Don’t you remember me?@KEY()↓
◆I returned this building to Mr. Enrich Flavor.@KEY()↓
◆Now I’m working as an elevator man.@KEY()↓
◆I’m very happy, and it’s good to be alive.@KEY()↓
◆I heard of your many successes.@KEY()↓
◆Wonderful.
@KEYNP()
;jpn:◆モノトリーだよ。@WI(20)↓
;jpn: わすれたかな?@KEY()↓
;jpn:◆このビルも もとのもちぬしの↓
;jpn: エンリッチ・フレーバーさんに↓
;jpn: かえして@KEY()↓
;jpn:◆わたしは↓
;jpn: エレベーターマンとして↓
;jpn: しゅうしょくしたのさ。@KEY()↓
;jpn:◆いまは まいにちが↓
;jpn: いきいきしてるよ。@KEY()↓
;jpn:◆きみたちの かつやくは↓
;jpn: うわさできいている。@KEY()↓
;jpn:◆すばらしい。@WI(30)↓
;jpn: こころから↓
;jpn: すばらしいとおもうよ。@KEYNP()
』

;-------------------------------------------------

MSG_FOUR_BORGES_AMBRAMI;&ポーキーの父アンブラミ
◆Wheeee!@KEY()↓
◆Hic!@KEY()↓
◆@DSP_NAME(PC_NESS).@KEY()↓
◆Pokey left me, his own dad, and just disappeared.@KEY()↓
◆If you see him, tell him that he should take better care of his father.@KEY()↓
◆Don’t tell my wife in Onett that I’ve been spending my timehere.@KEY()↓
◆Hic!@KEY()↓
◆Wheeeee!
@KEYNP()
;jpn:◆ウィー@WI(10) ヒック!↓@WI(30)
;jpn: @DSP_STS(STS_PC_NAME_NES)じゃないか。@KEY()↓
;jpn:◆ポーキーのやつ ちちおやの↓
;jpn: おれを おきざりにして↓
;jpn: きえちまったよ。@KEY()↓
;jpn:◆もし ポーキーのバカにあったら↓
;jpn: もっと おとうさんを↓
;jpn: たいせつにしろって いってくれ。@KEY()↓
;jpn:◆‥‥おれが ここで↓
;jpn: のんだくれてるなんて@KEY()↓
;jpn:◆オネットの にょうぼにゃ↓
;jpn: ぜったいに ないしょだぞ。@WI(20)↓
;jpn: ヒック!@WI(15) ウィーーー@KEYNP()
』
;-------------------------------------------------

;トポロ劇場受付の客
;ステージ後に現れ消える?
MSG_FOUR_THEATER_VISITOR_A;$
◆I heard Venus made an appearance at the Runaway Five show.@KEY()↓
◆I missed her ’cause I went to the bathroom.@KEY()↓
◆I’ll hate bathrooms for the rest of my life.
@KEYNP()
;jpn:◆トンズラたちのステージに↓
;jpn: ビーナスちゃんが↓
;jpn: とうじょうしたらしいな。@KEY()↓
;jpn:◆おれ トイレいってて↓
;jpn: みられなかったんだ。@KEY()↓
;jpn:◆‥‥トイレを うらむぜ。@KEYNP()
』

MSG_FOUR_THEATER_VISITOR_B;$
◆Oh, I can’t see the Runaway Five here anymore...?@KEY()↓
◆I should dump this sorry excuse of a man and become a Runaway Five groupie.
@KEYNP()
;jpn:◆ああ もうトンズラたちには↓
;jpn: あえないのかしら‥‥@KEY()↓
;jpn:◆わたしも こんなおとこから↓
;jpn: とんずらして@KEY()↓
;jpn:◆トンズラブラザーズのおっかけに↓
;jpn: なっちゃおうかしら‥‥。@KEYNP()
』
;-------------------------------------------------

MSG_FOUR_FIELD_KOZIKI;$
◆I’m very punctual about time and careful with money.@KEY()↓
◆I don’t look like it, though.
@KEYNP()
;jpn:◆こうみえても ぼくは↓
;jpn: じかんとか おかねとかに↓
;jpn: きちんと してるんだぜ。@KEYNP()
』
;-------------------------------------------------
