;-----------------------------------------------------

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客A
;@Figure:ジミな男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:DMSG_SUMS_CLUB_A
MSG_SUMS_CLUB_A;
◆Didactically speaking, seminal evidence seems to explicate the fact that@KEY()↓
◆your repudiation of entropy supports my theory of space−time synthesis.@KEY()↓
◆Of this, I am irrefutably confident.
;jpn:◆つまり いまのせかいでは↓
;jpn: エントロピーの ぞうだいっていう↓
;jpn: ながれに あらがうことは@KEY()↓
;jpn:◆ぼうちょうする うちゅうを↓
;jpn: ひていしつづける いしが↓
;jpn: ひょうめいされているってこと‥‥
@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客B♀
;@Figure:OLC
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_B
MSG_SUMS_CLUB_B;
◆Mmmmm.@KEY()↓
◆I think it’s a very complicated issue.@KEY()↓
;jpn:◆うーん。↓
;jpn: わたしが かんがえるに↓
;jpn: それは むつかしいもんだいね。@KEY()↓
@WI(60)↓
◆......Oh, sorry!@KEY()↓
◆I was sleeping...
@KEYNP()
;jpn:◆‥@WI(30)‥@WI(30)あ@WI(15) ごめんなさい。@WI(20)↓
;jpn: ねむってたわ。@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客C
;@Figure:青年
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_C
MSG_SUMS_CLUB_C;
◆You guys can’t envision the final collapse of capitalism?@KEY()↓
◆Incredible!
@KEYNP()
;jpn:◆えっ きみたちって↓
;jpn: しほんしゅぎの↓
;jpn: さいしゅうイメージを@KEY()↓
;jpn:◆そうぞうすることさえも↓
;jpn: しないで↓
;jpn: いきてるわけ?!@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客D
;@Figure:おじさんD
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_D
MSG_SUMS_CLUB_D;
@CHKFGOTO(FLG_SUMS_STOIC_WIFE_DISAPPEAR,_SUMS_CLUB_B_LATER)
◆You know, I really want to eat some Magic cake.@KEY()↓
◆It’s a mysterious work of art...@KEY()↓
◆I can’t get that cake off my mind.@KEY()↓
◆There’s only one woman who can make Magic cake...@KEY()↓
◆She’s hanging out in this club.@KEY()↓
◆Yeah, she’s over there at the entrance...@KEY()↓
◆Anyway, the absolute irony and study of self−identification is...@KEY()↓
◆Blah, blah, blah...@KEY()↓
◆I don’t know what to do!
@KEYNP()
;jpn:◆ボクはねぇ@WI(20) キミ↓
;jpn: あの げんそうてきで かんびな↓
;jpn: げいじゅつひんともいえるところの@KEY()↓
;jpn:◆マジックケーキ‥‥を@WI(20)↓
;jpn: もういちど しょくしてみたいと@KEY()↓
;jpn:◆こころから↓
;jpn: ねがってやまないんだよ。@KEY()↓
;jpn:◆しかし‥‥@KEY()↓
;jpn:◆マジックケーキをつくる↓
;jpn: せかいで ゆいいつともいえる↓
;jpn: じょせいがね‥‥@KEY()↓
;jpn:◆このクラブに いりびたりで@WI(30)↓
;jpn: つくろうと しないんだよ。@KEY()↓
;jpn:◆あの いりぐちのところに↓
;jpn: いるんだが‥‥@KEY()↓
;jpn:◆この ぜったいむじゅんてき↓
;jpn: じこどういつせいというか↓
;jpn: ‥‥クドクド‥‥@KEY()↓
;jpn:◆こまっちゃうんだよね ボク。@KEYNP()
@CHKFGOTO(FLG_PU,MSG_END)
@SETF(FLG_SUMS_MASSAGE_APPEAR);この人と女房のセリフ替え用。夕焼けはヤメ
;@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させなくする
』
_SUMS_CLUB_B_LATER;
◆The woman who sells magic cake@KEY()↓
◆seems to have been removed from the members list.
@KEYNP()
;jpn:◆マジックケーキうりの カノジョ↓
;jpn: どうやら ボクらの メンバーから↓
;jpn: はずれたようだね。@KEYNP()
』
;◆カリヨンビーチにはねぇ キミ↓
; なかなかおもしろい↓
; マッサージをしてくれる@KEY()↓
;◆ジルって じょせいが いてね‥‥@KEY()↓
;◆いいゆめを みせてくれるらしい。↓
; いいゆめ‥‥だよ‥‥キミ。↓
; すてきじゃないか‥‥ねぇ。@KEYNP()
;@CHKFGOTO(FLG_PU,MSG_END)
;@SETF(FLG_SUMS_MASSAGE_APPEAR)
;@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させなくする
;』


;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:オーナー(アーシー)
;@Figure:モヒカン
;@AppearanceKey:0
;@ActionScript:◆
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_OWNER
MSG_SUMS_CLUB_OWNER;
◆You don’t understand what the hey everyone is talking about, do you?@KEY()↓
◆I don’t either, but I try to be patient with the customers.@KEY()↓
◆They pay high prices just for a glass of water@KEY()↓
◆and the chance to have serious, intellectual discussions.@KEY()↓
◆Actually, it’s an easy business.@KEY()↓
◆You want a drink?@KEY()↓
◆We only serve water, though...
@KEYNP()
;jpn:◆きゃくたちが なにいってるのか↓
;jpn: わかんないだろ。@WI(20)↓
;jpn: がまんしてるんだ おれも。@KEY()↓
;jpn:◆たかいかねはらって↓
;jpn: みずだけのんで ペチャクチャと↓
;jpn: こむずかしいこと しゃべってさ。@KEY()↓
;jpn:◆でも いいしょうばいだよ。@WI(20)↓
;jpn: あんたも なにか?@WI(10)↓
;jpn: メニューは みずだけだけど‥‥。@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:ウェイトレス(ジョシー)
;@Figure:ウェートレスB
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_WAITRESS
MSG_SUMS_CLUB_WAITRESS;
;クラブストイックは、
;表の看板に
;「水あります」と記されている
◆The show?@KEY()↓
◆It’s already started.@KEY()↓
◆Everyone stares at the stone on stage and philosophizes.@KEY()↓
◆...Doesn’t it sound stupid?
;jpn:◆ショー?@WI(20) もうはじまってるわよ。↓
;jpn: ステージのいしを みつめて↓
;jpn: いろいろてつがくするのよ。@KEY()↓
;jpn:◆‥‥バカらしいでしょ。
@CHKFGOTO(FLG_PU,_SUMS_CLUB_WAITRESS_PU)
@KEYNP()
』

_SUMS_CLUB_WAITRESS_PU;
@KEY()↓
◆If you just want water, go to the drug store.@KEY()↓
◆It’s a lot cheaper there.
@KEYNP()
;jpn:◆みずだけ ほんとに ほしいなら↓
;jpn: ドラッグストアで↓
;jpn: やすく うってるわよ。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／トトの住宅A／トトの住宅A
;@Person:住人
;@Figure:スペイン人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_HOUSE_A
MSG_TOTO_HOUSE_A;
◆Across the sea, there’s a town called Scaraba.@KEY()↓
◆It’s a mysterious town.@KEY()↓
◆It’s my dream town.
@KEYNP()
;jpn:◆うみのかなたには↓
;jpn: スカラビという まちがある。@WI(20)↓
;jpn: しんぴのまち。あこがれのまち。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／トトの住宅C／トトの住宅C
;@Person:街の人B
;@Figure:スペイン人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_B
MSG_TOTO_B;
◆I’m a grave robber.@KEY()↓
◆I was scared of the pyramid in Scaraba...@KEY()↓
◆so, I didn’t go in...@KEY()↓
◆but I tell people that I saw mummy−type monsters with my very own eyes!
@KEYNP()
;jpn:◆わたしは はかドロボーなんだわ。@WI(20)↓
;jpn: スカラビのピラミッドは↓
;jpn: あんまりこわくて‥‥@KEY()↓
;jpn:◆はいれなかったんだわ。↓
;jpn: だけどね ミイラのばけもんとか↓
;jpn: このめでみたのは じまんでしょ。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／トトの住宅D／トトの住宅D
;@Person:住人
;@Figure:レゲエ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_D
MSG_TOTO_D;＃
@CHKFGOTO(FLG_SUMS_STOIC_WIFE_DISAPPEAR,_TOTO_D_LATER)
◆Do you know the Stoic Club, in Summers?@KEY()↓
◆You need to call a secret number for a reservation if you want to get in.@KEY()↓
◆What?@KEY()↓
◆Yeah, I’ll give you the secret number.@KEY()↓
◆I warn you though, it’s a strange place...
@KEYNP()
;jpn:◆サマーズのまちの↓
;jpn: ストイッククラブってあるだろ。@WI(20)↓
;jpn: あそこって@KEY()↓
;jpn:◆ひみつの でんわで↓
;jpn: よやくしないと はいれないんだ。@WI(20)↓
;jpn: え おれ?@KEY()↓
;jpn:◆おれは しってるよ。↓
;jpn: でんわばんごうくらい↓
;jpn: おしえてやるさ。@KEY()↓
;jpn:◆へんなみせだけどな。@KEYNP()
@SE(SE_se74_my_get)
@SETF(FLG_SYS_PHONE_STOIC)
@FUNC(5)			;毒死配達禁止
』
_TOTO_D_LATER;＆
◆I think this is a nice town.@KEY()↓
◆Come back when you grow up!
@KEYNP()
;jpn:◆おれは このまちが すきだなぁ@WI(30)↓
;jpn: おとなになったら また↓
;jpn: このまちに こいよ な。@KEYNP()
』

;----------------------------------------
;@Habitat:サマーズ／トトの住宅G／トトの住宅G
;@Person:住人
;@Figure:トランペッター
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_HOUSE_G
MSG_TOTO_HOUSE_G;
◆If you come closer, I’ll play the trumpet!@KEY()↓
◆.....@KEY()↓
◆Uhhh, I don’t know how to play yet.
@KEYNP()
;jpn:◆ちかよると ふくぞ!@WI(20)↓
;jpn: ‥‥‥↓
;jpn: まだ ふけないんだけどさ。@KEYNP()
』

;@Habitat:サマーズ／トトの住宅G／トトの住宅G
;@Person:ペット
;@Figure:チリドッグ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_HOUSE_GDOG
MSG_TOTO_HOUSE_GDOG;
◆Bow...@KEY()↓
◆...now brown cow?
@KEYNP()
;jpn:◆ウーーー‥‥@KEY()↓
;jpn:◆マンボ!@KEYNP()
』
;◆ハズレ!@WI(20)↓
; (このイヌは しゃべらない)@KEYNP()
;』

;----------------------------------------
;@Habitat:サマーズ／雑貨屋／雑貨屋
;@Person:店員
;@Figure:若い船乗り
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_GROCER
MSG_SUMS_GROCER;
@GOSUB(MSG_SHOP_SUMS_GROCER)
』

；----------------------------------------
;@Habitat:サマーズ／ドラッグストア／ドラッグストア
;@Person:店員
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_DRUGSTORE
MSG_SUMS_DRUGSTORE;@MiuraAppended
@GOSUB(MSG_SHOP_SUMS_DRUG)
』

;@Habitat:サマーズ／ドラッグストア／ドラッグストア
;@Person:客A
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SOUVENIR_A
MSG_SUMS_SOUVENIR_A;
;サマーズのお土産屋客A
◆There’s a big monster living in the sea between here and Scaraba.@KEY()↓
◆I’ve seen a picture of it.
@KEYNP()
;jpn:◆スカラビにわたる うみには↓
;jpn: どえらいバケモノが いるのよね。@WI(15)↓
;jpn: しゃしんでみたことあるのよね。@KEYNP()
』

;@Habitat:サマーズ／ドラッグストア／ドラッグストア
;@Person:客B
;@Figure:アーティスト
;@AppearanceKey:0
;@ActionScript:◆足踏み＆方向転換
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SOUVENIR_B
MSG_SUMS_SOUVENIR_B;
;サマーズのお土産屋客B
@CHKFGOTO(FLG_PU,_SUMS_SOUVENIR_B_TMP)
_SUMS_SOUVENIR_B_MAIN;
◆How annoying!@KEY()↓
◆Why are you are wandering around?@KEY()↓
◆Summers is a posh resort, made for adults.
@KEYNP()
;jpn:◆なんだか こどもが↓
;jpn: うろうろしてて↓
;jpn: じゃまねぇ。@KEY()↓
;jpn:◆サマーズは おとなのための↓
;jpn: こうきゅうリゾートち なのに。@KEYNP()
』
_SUMS_SOUVENIR_B_TMP;
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_SOUVENIR_B_MAIN);プーと別れていたら
@SET_LOOPREG(PC_POO)			;プーのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SUMS_SOUVENIR_B_MAIN)
◆That Kung Fu−like hairstyle!@KEY()↓
◆You look so cool!@KEY()↓
◆I may fall in love with you.@KEY()↓
◆Do you think I’m too forward?
@KEYNP()
;jpn:◆そちらの べんぱつのかた↓
;jpn: なんだか すっごくステキ!@KEY()↓
;jpn:◆すきに なっちゃいそう。@WI(20)↓
;jpn: わたしったら↓
;jpn: いけない おんなかしら。@KEYNP()
』
;◆ちかごろ かたがこって‥‥。↓
; うでのいいマッサージしが↓
; いたんだけど みつからなくて。@KEYNP()
;』

；----------------------------------------
;@Habitat:サマーズ／ホテル／廊下ロビー
;@Person:客A
;@Figure:ジミな男
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_A
MSG_SUMS_HOTEL_A;
◆Don’t get too excited about this town.@KEY()↓
◆It’s a tourist trap.@KEY()↓
◆Everyone seems to be nice, but they’re just doing it for the money.@KEY()↓
◆I know from experience.
@KEYNP()
;jpn:◆このまちで うかれていては↓
;jpn: いけません。↓
;jpn: ここは かんこうち なんです。@KEY()↓
;jpn:◆みんな しんせつぶってるけど↓
;jpn: しょうばいで しんせつに↓
;jpn: してるんですよ。 きっと。@KEYNP()
』

;@Habitat:サマーズ／ホテル／廊下ロビー
;@Person:客B
;@Figure:OLC
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_B
MSG_SUMS_HOTEL_B;
◆Excuse me.
;jpn:◆エクスキューズ ミー。
@KEYNP()
』

;@Habitat:サマーズ／ホテル／廊下ロビー
;@Person:客C
;@Figure:おばさんB
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_C
MSG_SUMS_HOTEL_C;＃
@CHKFGOTO(FLG_ITEM_HIEROGLYPH,_SUMS_HOTEL_C_END)
◆I heard the security guard in the Scaraba Cultural Museum isn’t very nice.@KEY()↓
◆But he can be helpful.
@KEYNP()
;jpn:◆「スカラビぶんかはくぶつかん」↓
;jpn: にいる ガードマンって‥‥@KEY()↓
;jpn:◆あんまり たちが↓
;jpn: よくないって はなしだけど@WI(20)↓
;jpn: りようできるおとこ らしいわ。@KEYNP()
』
_SUMS_HOTEL_C_END;＆
◆Forget about the adventure,@KEY()↓
◆Come back again!
@KEYNP()
;jpn:◆いつかまた↓
;jpn: ぼうけんなんか わすれて↓
;jpn: あそびにきてね。@KEYNP()
』


;◆ビーチにいた マッサージさん↓
; すっごく じょうずだったわ。↓
; ゆめごこちよ。@KEYNP()
』


;■サマーズホテル西の部屋■■■■■■■■■■■■■■■■■■■■■■■■■
;added 0717 toda -> ueno
MSG_SUMS_HOTEL_D
◆I can’t believe you pronounce Hotel as ”Hotel.”@KEY()↓
◆In this country, Hotel is pronounced ”otel.”@KEY()↓
◆...What?@KEY()↓
◆So then in your country, is otter pronounced as ”Hotter”?@KEY()↓
◆’Ow should I know these things?.
@KEYNP()
;jpn:◆ホテルを ホテルと↓
;jpn: はつおんしてるようじゃ↓
;jpn: おさとが しれるね。@KEY()↓
;jpn:◆このくにでは↓
;jpn: ホテルは オテルなのさ。@KEY()↓
;jpn:◆‥‥え?↓
;jpn: じゃ ホタルはオタルかって?@KEY()↓
;jpn:◆そんなことは↓
;jpn: シラーヌ・ド・ゾンゼーヌ。@KEYNP()
』



;@Habitat:サマーズ／ホテル／受付
;@Person:フロントマン
;@Figure:おじさんB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_DESK
MSG_SUMS_HOTEL_DESK;@MiuraAppended
;◆サマーズホテルにようこそ。@KEY()↓
@GOSUB(MSG_GLOBAL_HOTEL)
』

;@Habitat:サマーズ／ホテル／受付
;@Person:ボーイ
;@Figure:ホテルボーイ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTELPORTER
MSG_SUMS_HOTELPORTER;
;jpn:◆いつも どうも ポーキ‥‥@WI(20)↓
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Thank you again, Poke...@KEY()↓
◆Uhhh, Mr. @DSP_NAME(0).
@KEYNP()
;＠ポーラだったら変える「Miss」
;jpn: いえ @WI(20)@DSP_NAME(0)さま。@KEYNP()
』

;@Habitat:サマーズ／ホテル／キャッシュディスペンサ
;@Person:キャッシュディスペンサ
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

；----------------------------------------
;@Habitat:サマーズ／レストラン／レストラン
;@Person:店員
;@Figure:コック
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_DINER
MSG_SUMS_DINER;
;
@GOSUB(MSG_SHOP_SUMS_DINER)
;
;処理後
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:ウェートレス
;@Figure:ウェートレスB
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_WAITRESS
MSG_SUMS_RESTAURANT_WAITRESS;
◆@DSP_STS(STS_PARTY_FAVORITE_FOODS)?@KEY()↓
◆Please...we do not have such trash on our menu.
@KEYNP()
;◆@DSP_STS(STS_PARTY_FAVORITE_FOODS)?@WI(20)↓
;jpn: うちのメニューには ないわ。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客A
;@Figure:おじさんB
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_A
MSG_SUMS_RESTAURANT_A;
◆Hey, talking to people at another table in a restaurant is like...@KEY()↓
◆breaking into their room and checking their drawers for valuables.@KEY()↓
◆Yeah, other people on important adventures do such things,@KEY()↓
◆but you have to admit that it’s bizarre!
@KEYNP()
;jpn:◆きみ レストランの↓
;jpn: べつのテーブルのきゃくに↓
;jpn: やたらに はなしかけることは‥‥@KEY()↓
;jpn:◆こんやくしゃの へやに はいって↓
;jpn: ものもいわずに↓
;jpn: タンスのひきだしを しらべて‥‥@KEY()↓
;jpn:◆ちいさなメダルを さがすような↓
;jpn: いじょうな こういだよ。@WI(20)↓
;jpn: ま‥‥@KEY()↓
;jpn:◆じじょうがあるなら↓
;jpn: しかたがないけど ね。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客B
;@Figure:おばさんA
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_B
MSG_SUMS_RESTAURANT_B;
◆I like the atmosphere in this restaurant.@KEY()↓
◆They have good food, too.
@KEYNP()
;jpn:◆このみせって↓
;jpn: ふんいきもいいけど↓
;jpn: おりょうりが すばらしいわ。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客C
;@Figure:おじさんD
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_C
MSG_SUMS_RESTAURANT_C;
◆I’ll have the Braised Boa Over Minced Baby Leeks...@KEY()↓
◆Oh, you’re not the waiter.
@KEYNP()
;jpn:◆チャバネヘビの↓
;jpn: おにがらやきを くれ。↓
;jpn: おっと みせのひとじゃないのか。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客D
;@Figure:おばあさん
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_D
MSG_SUMS_RESTAURANT_D;
◆I have fake teeth,@KEY()↓
◆so I like soft foods.@KEY()↓
◆Not like rocks or stones.@KEY()↓
◆They’re too hard.
@KEYNP()
;jpn:◆わたしは いればなので↓
;jpn: やわらかいものが すきなの。@WI(20)↓
;jpn: いわとか いしは かたくって。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／博物館／受付
;@Person:受付嬢(オードリー)
;@Figure:OLG
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_AUDREY
MSG_SUMS_MUSEUM_AUDREY;
@CHKFGOTO(FLG_GLOBAL_MUSEUM_PAID,_SUMS_MUSEUM_PAID)
◆Right now, part of the Scaraba Cultural Museum is being remodeling.@KEY()↓
◆Do you still want to enter?↓
<Yes>
<No>
;jpn:◆いま↓
;jpn: 「スカラビぶんかはくぶつかん」は↓
;jpn: いちぶ かいそうちゅうですが@KEY()↓
;jpn:◆それでも いいですか?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_MUSEUM_AUDREY_YES,_SUMS_MUSEUM_AUDREY_NO)

_SUMS_MUSEUM_AUDREY_NO;
◆Since the Hieroglyph display is closed, people haven’t wanted to visit.
@KEYNP()
;jpn:◆ヒエログリフが みられないので↓
;jpn: おきゃくさまが ほとんど↓
;jpn: はいらないんですよ。@KEYNP()
』

_SUMS_MUSEUM_AUDREY_YES;
◆Three dollars per person.@KEY()↓
◆Study hard.↓
;jpn:◆では おひとり３ドルです。↓
;jpn: しっかり べんきょうしてね。↓
@WINR_MONEY()
<Yes>
<No>
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_MUSEUM_AUDREY_YESYES,_SUMS_MUSEUM_AUDREY_NO)
@GOTO(_SUMS_MUSEUM_AUDREY_NO)

_SUMS_MUSEUM_AUDREY_YESYES;
@MUL_ACTIVE_PLAYER(3)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_SUMS_MUSEUM_AUDREY_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(0)
@WINR_MONEY()
@SETF(FLG_GLOBAL_MUSEUM_PAID)
@CHKFGOTO(FLG_WIN_GIEGU,MSG_END)	;別れのHRECTを保つ為
@RES_HIT_RECT(1)			;お金を払ったら包囲網を解く
』

_SUMS_MUSEUM_AUDREY_NOMONEY;
◆You don’t have any money, right?@KEY()↓
◆Okay, since you kids look like you would study hard, you may enter,@KEY()↓
◆free of charge!@KEY()↓
◆Oh wait...I can’t do that!@KEY()↓
◆Good bye.
@KEYNP()
;jpn:◆おかねがないんですね?@KEY()↓
;jpn:◆それじゃあ↓
;jpn: べんきょうねっしんな↓
;jpn: こども@GOSUB(MSG_SUB_TATI)だから@KEY()↓
;jpn:◆ただ!@KEY()↓
;jpn:◆むりょう!@KEY()↓
;jpn:◆に するわけにいかないのよ。↓
;jpn: さよなら。@KEYNP()
』
_SUMS_MUSEUM_PAID;
◆Since the Hieroglyph display is closed, people haven’t wanted to visit.
@KEYNP()
;jpn:◆ヒエログリフが みられないので↓
;jpn: おきゃくさまが ほとんど↓
;jpn: はいらないんですよ。@KEYNP()
』

;@Habitat:サマーズ／博物館／展示室大
;@Person:係員(オマール)
;@Figure:スカラビ男C
;@AppearanceKey:0
;@ActionScript:◆西を向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_OMAR
MSG_SUMS_MUSEUM_OMAR;
◆This room is being remodeled, so I can’t show it to you...@KEY()↓
;jpn:◆このへやは かいそうちゅうで↓
;jpn: みせるわけには いかないが‥‥@KEY()↓
@CHKFGOTO(FLG_PU,MSG_SUMS_MUSEUM_OMAR_PU)
_SUMS_MUSEUM_OMAR_PU_DEAD;
◆I can’t...well, I usually don’t...@KEY()↓
◆show this room...@KEY()↓
◆Once you hit adulthood, you’ll understand.@KEY()↓
◆I do, however, like jewelry.@KEY()↓
◆Perhaps a little, shall we say, ”under the table deal” would be in order...
@KEYNP()
;jpn:◆いかないが‥‥いや↓
;jpn: なんでもない。↓
;jpn: ふつうは みせない‥‥と。@KEY()↓
;jpn:◆ま おとななら↓
;jpn: わかってもらえるんだろうが@KEY()↓
;jpn:◆わたしは ほうせきに↓
;jpn: きょうみが あってねぇ。@KEY()↓
;jpn:◆うーむ そでのしたのほうが↓
;jpn: なんか スースーするなぁ。↓
;jpn: コホン@KEYNP()
』
MSG_SUMS_MUSEUM_OMAR_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_TINY_RUBY)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
@SET_LOOPREG(PC_POO)			;プーのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(MSG_SYS_GOODS_USE_NG)
@GOTO(MSG_SUMS_MUSEUM_OMAR_PU)
』

MSG_SUMS_MUSEUM_OMAR_PU;
@SET_LOOPREG(PC_POO)			;プーのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SUMS_MUSEUM_OMAR_PU_DEAD)
◆Oh, the samurai kid is here.@KEY()↓
◆Will he be giving me that gem?↓
;＠プーだけだったら「you」
<Yes>
<No>
;jpn:◆おっと そっちのべんぱつのひと↓
;jpn: その ほうせきを わたしに?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_MUSEUM_OMAR_PU_YES,_SUMS_MUSEUM_OMAR_PU_NO)

_SUMS_MUSEUM_OMAR_PU_NO;
@SE(SE_se76_my_give)
◆Excuse me?@KEY()↓
◆So, what he just handed me is not a gem.@KEY()↓
;＠プーだけだったら「you」
◆Hah ha ha.@KEY()↓
◆I’m going to really enjoy the ”cookie” that I just got.@KEY()↓
◆Let’s pretend this conversation never took place...@KEY()↓
◆While I’m pretending, you go on in...
@KEY()
;jpn:◆えっ ほうせきじゃないけど‥‥@KEY()↓
;jpn:◆エッヘッヘ↓
;jpn: わたしの そでのしたに↓
;jpn: おもりを つけろって ですか。@KEY()↓
;◆えっ それでハナをかむ?↓
; ハナをかんだら そのカミクズは↓
; わたしに くれると?! おお!@KEY()↓
;jpn:◆わたし‥‥みてみぬふりを↓
;jpn: しますから そのすきに↓
;jpn: はいっていいです。へっへっへ。@KEY()
@GOTO(MSG_EVT_SUMS_OMAR)
』

_SUMS_MUSEUM_OMAR_PU_YES;
@SE(SE_se76_my_give)
◆You’re such a good student.@KEY()↓
◆I’m impressed by your passion for learning.@KEY()↓
◆Come in.
@KEY()
;jpn:◆よほどべんきょうねっしんなかた。↓
;jpn: そのきもちに うたれました。↓
;jpn: どうぞ おはいりください。@KEY()
@GOTO(MSG_EVT_SUMS_OMAR)
』

MSG_EVT_SUMS_OMAR;
@SET_CHAR_DIR(PRSN_SUMS_HIERO_PASS_A,DIR_M_UP)
@WI(30)
@SE(SE_se08_door_in)
@HIDE_CHAR(PRSN_SUMS_HIERO_PASS_A,OBJFX_HIDE_NONE)
@GOODSOUT(PC_ALL,GDS_TOOL_TINY_RUBY)
@SETF(FLG_SUMS_OMAR_B_APPEAR)
』

MSG_SUMS_OMAR_B;
@CHKFGOTO(FLG_TEMP_9,MSG_SUMS_OMAR_B_TEMP)
◆Excellent!@KEY()↓
◆Do you feel like you’re really experiencing this great historical period?@KEY()↓
◆The experience is more valuable than a small gem...@KEY()↓
◆Ha ha ha!@KEY()↓
◆The other day, a rich kid came to Summers by helicopter...@KEY()↓
◆He also took a picture of the Hieroglyphs.@KEY()↓
◆I got lots of money from him.@KEY()↓
◆Heh heh heh.
@KEYNP()
;jpn:◆すばらしい!@KEY()↓
;jpn:◆いだいなる れきしを↓
;jpn: かんじるでしょう?@KEY()↓
;jpn:◆この ちいさな↓
;jpn: ほうせき いじょうの↓
;jpn: かちのある‥‥@KEY()↓
;jpn:◆ワッハッハ!@KEY()↓
;jpn:◆こないだも ヘリコプターで↓
;jpn: サマーズにやってきた↓
;jpn: ふごうの しょうねんがね‥‥@KEY()↓
;jpn:◆ヒエログリフを↓
;jpn: しゃしんにとって↓
;jpn: いきましたよ。@KEY()↓
;jpn:◆あんときゃ げんきんを↓
;jpn: たっぷり もらったっけなぁ↓
;jpn: ヘッヘッヘ。@KEYNP()
』

MSG_SUMS_OMAR_B_TEMP;
◆Here’s a picture of the hieroglyphs, just for you.@KEY()↓
◆It’s a reward for studying so hard.@KEY()↓
;jpn:◆べんきょうねっしんな かたに↓
;jpn: 「ヒエログリフのうつし」を↓
;jpn: とくべつに さしあげましょう。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SUMS_OMAR_B_ITEMFULL_TEMP)
@GOODSIN_PLAYER(0,GDS_TOOL_HIEROGLYPH_COPY)
@GOSUB(MSG_SUB_GETGOODS)@KEY()↓
◆Use it in your Human Civilization class.@KEY()↓
◆Ha ha ha!
@KEYNP()
;jpn:◆じんるいの ぶんかのために↓
;jpn: やくだててください。@KEY()↓
;jpn:◆ワッハッハ!@KEYNP()
@SETF(FLG_ITEM_HIEROGLYPH)
@CLRF(FLG_TEMP_9)
@CHKFGOTO(FLG_FOUR_KOMORITA,MSG_END)	;ライスボウルの話しを聞いてなければ
@SETF(FLG_SUMS_MUSEUM_PHONE_RING)	;電話鳴る
』
_SUMS_OMAR_B_ITEMFULL_TEMP;
@SE(SE_se05_undo)
◆Oh, you can’t carry it ’cause you have too much stuff.@KEY()↓
◆It’s a pity.@KEY()↓
◆You’re such a hard worker.@KEY()↓
◆Ha ha ha!
@KEYNP()
;jpn:◆おお にもつが
;jpn: いっぱいで もてない!@KEY()↓
;jpn:◆べんきょうねっしんなかたなのに↓
;jpn: もてないとは ざんねんですな。@KEY()↓
;jpn:◆ワッハッハ!@KEYNP()
@SETF(FLG_TEMP_9)
』

MSG_SUMS_OMAR_B_EVT;
;オマールに漫符出す
@SET_CHAR_DIR( PRSN_SUMS_HIERO_EXHI2_A, DIR_M_LEFT )
@SHOW_MANPU_CHAR( PRSN_SUMS_HIERO_EXHI2_A, MANPU_BIKKURI )
@WI( 60 )
@HIDE_MANPU_CHAR( PRSN_SUMS_HIERO_EXHI2_A )
;パーティに近寄るオマール
@REMOVE_CHAR( PRSN_SUMS_HIERO_EXHI2_A, ANIM_OMAR_GIVE_HIEROGRIPH )
@WAITSYS()
@COLD_CHAR( PRSN_SUMS_HIERO_EXHI2_A )	;「去るオマール」凍結
@OPEN(1)
◆Wait one second.@KEY()↓
◆Here’s a picture of the hieroglyphs just for you.@KEY()↓
◆It’s a reward for studying so hard.@KEY()↓
;jpn:◆ちょっと おまちを。@KEY()↓
;jpn:◆べんきょうねっしんな かたに↓
;jpn: 「ヒエログリフのうつし」を↓
;jpn: とくべつに さしあげましょう。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SUMS_OMAR_B_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_HIEROGLYPH_COPY)
@GOSUB(MSG_SUB_GETGOODS)@KEY()↓
◆Use it in your Human Civilization class.@KEY()↓
◆Ha ha ha!
@KEYNP()
;jpn:◆じんるいの ぶんかのために↓
;jpn: やくだててください。@KEY()↓
;jpn:◆ワッハッハ!@KEYNP()
@CLOSEALL()
@FRESH_CHAR( PRSN_SUMS_HIERO_EXHI2_A )	;「去るオマール」
@WAITSYS()
@SETF(FLG_ITEM_HIEROGLYPH)
@CHKFGOTO(FLG_FOUR_KOMORITA,MSG_END)	;ライスボウルの話しを聞いてなければ
@SETF(FLG_SUMS_MUSEUM_PHONE_RING)	;電話鳴る
』
_SUMS_OMAR_B_ITEMFULL;
@SE(SE_se05_undo)
◆Oh, you can’t carry it ’cause you have too much stuff.@KEY()↓
◆It’s a pity.@KEY()↓
◆You’re such a hard worker.@KEY()↓
◆Ha ha ha!
@KEYNP()
;jpn:◆おお にもつが
;jpn: いっぱいで もてない!@KEY()↓
;jpn:◆べんきょうねっしんなかたなのに↓
;jpn: もてないとは ざんねんですな。@KEY()↓
;jpn:◆ワッハッハ!@KEYNP()
@CLOSEALL()
@FRESH_CHAR( PRSN_SUMS_HIERO_EXHI2_A )	;「去るオマール」
@WAITSYS()
@SETF(FLG_TEMP_9)
』


;@Habitat:サマーズ／博物館／展示室大
;@Person:学芸員
;@Figure:サラリーマンD
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_KOMORITA
MSG_SUMS_MUSEUM_KOMORITA;＃
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_MUSEUM_KOMORITA_END)
@CHKFGOTO(FLG_FOUR_KOMORITA_APPEAR,_SUMS_MUSEUM_KOMORITA_LATER)
◆What?  Mr. Spoon is calling from the Fourside museum?@KEY()↓
◆He’s just bragging about something...@KEY()↓
◆Let him say what he wants!@KEY()↓
◆I wonder what he wants to tell me?@KEY()↓
◆I dare him to try and upstage me...@KEY()↓
◆Oh, sorry...I was just talking to myself...＊cough＊
@KEYNP()
;jpn:◆「フォーサイド↓
;jpn: しぜんはくぶつかん」の↓
;jpn: ライスボウルくんが@KEY()↓
;jpn:◆なにか じまんそうなでんわを↓
;jpn: かけてきてるらしいんだが‥‥@KEY()↓
;jpn:◆‥‥なんなんだろう?@WI(20)↓
;jpn: あー しりたい!@WI(15)↓
;jpn: あー くやしい!@KEY()↓
;jpn:◆‥‥あ いまのは ひとりごとさ。@WI(20)↓
;jpn: きに しないで くれたまえね。@WI(15)↓
;jpn: コホン。@KEYNP()
@SE(SE_se72);あやしい音
@KEYNP()
』
_SUMS_MUSEUM_KOMORITA_LATER;
◆It must be something teeny weeny that Mr. Spoon has found.@KEY()↓
◆I don’t need to know the specifics.
@KEYNP()
;jpn:◆ライスボウルくんの↓
;jpn: はっけんなんて@WI(20)↓
;jpn: どうせ たいしたことなかったろ?@KEY()↓
;jpn:◆ぼくは あんまり↓
;jpn: しりたくないな。@KEYNP()
』
_SUMS_MUSEUM_KOMORITA_END;＆
◆You have a good reputaiton.@KEY()↓
◆Wouldn’t you like to focus your hard working energy@KEY()↓
◆in the exciting field of archaeology?
@KEYNP()
;jpn:◆きみの いいうわさは↓
;jpn: いろいろ きいてるよ。@KEY()↓
;jpn:◆その こんじょうを↓
;jpn: これから こうこがくの↓
;jpn: けんきゅうに いかさないか?@KEYNP()
』


;@Habitat:サマーズ／博物館／展示室大
;@Person:客
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_A
MSG_SUMS_MUSEUM_A;＃
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_MUSEUM_A_END)
◆I saw a chubby kid about your age here.@KEY()↓
◆He looked like he was awfully wealthy.  He was being extravagant!
@KEYNP()
;jpn:◆ちょうど おまえらと↓
;jpn: おないどしくらいの デブが↓
;jpn: さっきまで いたぜ。@KEY()↓
;jpn:◆やたらに かねまわりの↓
;jpn: よさそうな ガキだった。@KEYNP()
』
_SUMS_MUSEUM_A_END;＆
◆It’s nice seeing you in such good shape.@KEY()↓
◆I wonder what porky Pokey’s doing.@KEY()↓
◆Yeah, that’s the boy I met before.
@KEYNP()
;jpn:◆きみは げんきそうでよかったけど@WI(20)↓
;jpn: まえに あった あの↓
;jpn: ポーキーとかいう デブは@KEY()↓
;jpn:◆どうしてるだろうなぁ。@KEYNP()
』
;----------------------------------------
;@Habitat:サマーズ／病院／受付
;@Person:受付嬢
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOSPITAL_USHER
MSG_SUMS_HOSPITAL_USHER;@MiuraAppended
;◆どなたに ごめんかいですか?@KEY()
@GOSUB(MSG_NURSE_SUMS)
;@GOSUB(MSG_SHOP_SUMS_HOSPITAL)
』

;@Habitat:サマーズ／病院／診察室
;@Person:医者
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOSPITAL_DOCTOR
MSG_SUMS_HOSPITAL_DOCTOR;@MiuraAppended
;◆みてもらいたいのは↓
; だれだね?@KEY()
@GOSUB(MSG_DOCTOR_SUMS)
』

;@Habitat:サマーズ／病院／診察室
;@Person:付き添い
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOSP_GIRL
MSG_SUMS_HOSP_GIRL;
◆My cousin is a nurse in Twoson.@KEY()↓
◆She’s not good at administering shots.@KEY()↓
◆The one she gave me was painful.
@KEYNP()
;jpn:◆わたしのいとこが ツーソンで↓
;jpn: かんごふをしてるんだけど↓
;jpn: ちゅうしゃがへたで いたいのよ。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の男A
;@Figure:海パンB
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_A
MSG_SUMS_SWIMSUITMAN_A;
◆Wake up in the morning, fall in love.@KEY()↓
◆Eat lunch, fall in love...@KEY()↓
◆And at night, fall in love again...@KEY()↓
◆That’s my dream life.
@KEYNP()
;jpn:◆あさおきて こいをして↓
;jpn: ランチをたべて こいをして‥‥↓
;jpn: よるになったら こいをして‥‥。@KEY()↓
;jpn:◆そういうじんせいが↓
;jpn: ぼくの のぞみ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の女A
;@Figure:ビキニA
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITGAL_A
MSG_SUMS_SWIMSUITGAL_A;
◆The guy next to me is really bugging me.@KEY()↓
◆He keeps following me around.
@KEYNP()
;jpn:◆となりのおとこ↓
;jpn: うるさくて しかたないのよ。↓
;jpn: しつこく ついてくるの。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の男B
;@Figure:海パンA
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_B
MSG_SUMS_SWIMSUITMAN_B;
◆I wonder why such serious looking kids@KEY()↓
◆as you would come to this resort town...@KEY()↓
◆You guys are spoiling the atmosphere...
@KEYNP()
;jpn:◆きみたちみたいな↓
;jpn: せっぱつまった かおつきの↓
;jpn: ひとびとが‥‥@KEY()↓
;jpn:◆どうして こんなリゾートちに↓
;jpn: きているんだろうねぇ。↓
;jpn: ふんいき こわしちゃうなぁ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:水着の男C(元サーファー)
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_C
MSG_SUMS_SWIMSUITMAN_C;
◆I’m actually a surfer.@KEY()↓
◆But you can’t surf at this Summer’s beach.@KEY()↓
◆Should I become a porter so that I can get tips from all the old folks?
@KEYNP()
;jpn:◆おれは もともとサーファーだけど↓
;jpn: このサマーズのビーチじゃ↓
;jpn: なみのりは むりだね。@KEY()↓
;jpn:◆ジーさん バーさんから↓
;jpn: チップをもらって↓
;jpn: にもつはこびでも やるか。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の男D
;@Figure:海パンB
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_D
MSG_SUMS_SWIMSUITMAN_D;
◆Are you from EagleLand?@KEY()↓
◆If you like adventure, this isn’t your kind of place.@KEY()↓
◆You should travel across the sea to Scaraba from Toto, the port town.
@KEYNP()
;jpn:◆イーグルランドから きたのかい。↓
;jpn: ぼうけんずきなら↓
;jpn: このまちは あわないとおもうよ。@KEY()↓
;jpn:◆トトっていう みなとまちから↓
;jpn: ふねで スカラビに↓
;jpn: わたるんだな。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の女B
;@Figure:ビキニB
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITGAL_B
MSG_SUMS_SWIMSUITGAL_B;
@CHKFGOTO(FLG_PU,_SUMS_SWIMSUITGAL_B_TMP)
_SUMS_SWIMSUITGAL_B_MAIN;
◆Don’t talk to me.@KEY()↓
◆My mind is a complete blank.
@KEYNP()
;jpn:◆はなしかけるの やめてよね@WI(15)↓
;jpn: あたし なーんにも↓
;jpn: かんがえてないんだから。@KEYNP()
』
_SUMS_SWIMSUITGAL_B_TMP;
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_SWIMSUITGAL_B_MAIN);プーと別れていたら
@SET_LOOPREG(PC_POO)			;プーのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SUMS_SWIMSUITGAL_B_MAIN)
◆Asian boy, you’re so cool...@KEY()↓
◆Don’t look at me like that...
@KEYNP()
;jpn:◆あら オリエンタルで↓
;jpn: クールで すてきな おとこ‥‥@KEY()↓
;jpn:◆そんなめで みつめないで‥‥@WI(20)↓
;jpn: すてきすぎるー音@KEYNP()
』


;@Habitat:サマーズ／フィールド／ビーチ
;@Person:オイルマッサージ
;@Figure:マッサージ師
;@AppearanceKey:FLG_SUMS_MASSAGE_APPEAR/on
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_OILMASSAGE
MSG_SUMS_OILMASSAGE;
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_WIFE_END)
@CHKFGOTO(FLG_PU,MSG_SUMS_WIFE);ランマに行ってたらマジックタルト売りに
@FUNC(5)			;配達禁止
◆I don’t know who told you.@KEY()↓
◆You came from far off just to eat my Magic cake?...@KEY()↓
◆I thought making cakes would be the best career for me.@KEY()↓
◆Dig in!@KEY()↓
◆I used all leftover materials.@KEY()↓
◆This is a very special Magic cake!
@KEY()
;jpn:◆だれにきいたか しらないけれど@KEY()↓
;jpn:◆とおいくにから わざわざ↓
;jpn: わたしの マジックケーキを↓
;jpn: たべにきてくれたなんて‥‥@KEY()↓
;jpn:◆やっぱり わたし ケーキづくりが↓
;jpn: いちばん じぶんに あってる。@WI(30)↓
;jpn: そう おもったの。@KEY()↓
;jpn:◆さあ たくさんたべて!@KEY()↓
;jpn:◆さいごの ざいりょうを↓
;jpn: ぜんぶつかった スペシャルな↓
;jpn: マジックケーキよ!@KEY()↓
@CLOSEALL()
@CLRF(FLG_SUMS_MASSAGE_APPEAR)
@GOTO(MSG_EVT_78_GIL)
』
_SUMS_WIFE_END;
◆I can’t make anymore Magic cakes.@KEY()↓
◆If you want to try something tastier...@KEY()↓
◆I have a ”@DSP_GOODS(GDS_FOOD_MAGIC_TORTE).”@KEY()↓
◆Try it.@KEY()↓
@KEYNP()
;jpn:◆マジックケーキは↓
;jpn: もうつくれないけど↓
;jpn: おいしさなら それいじょうの‥‥@KEY()↓
;jpn:◆「マジックタルト」を↓
;jpn: うってるのよ。@KEY()↓
;jpn:◆あじみ してね。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SUMS_WIFE_GOODSFULL)
@GOODSIN_PLAYER(PC_ALL,GDS_FOOD_MAGIC_TORTE)
@SE(SE_se74_my_get)
◆...I could make one extra good today.
;jpn:◆‥‥きょうは また↓
;jpn: おいしくできたのよ。
@KEYNP()
@!
_SUMS_WIFE_GOODSFULL;
◆You seem to have too much stuff to carry.@KEY()↓
◆Come back after you get rid of something.
@KEYNP()
;jpn:◆もちものが いっぱいよ↓
;jpn: にもつを へらしてから↓
;jpn: またきてね。@KEYNP()
@!

;オイルマッサージの女(マーサ)
;◆とろけるような ゆめごこち。@WI(20)↓
; オイルマッサージは いかが。@KEY()↓
;◆ためしてみる?↓
;  <はい>  <いいえ>
;@DSP_ITEM(2)
;@SELGOTO(_SUMS_OILMASSAGE_YES,_SUMS_OILMASSAGE_NO)
;_SUMS_OILMASSAGE_NO;
;◆じゃ また こんどね。バーイ。@KEYNP()
;』
;_SUMS_OILMASSAGE_YES;
;◆じゃ こっちのひかげでね。@KEY()
;@CLOSEALL()
;@CLRF(FLG_SUMS_MASSAGE_APPEAR)
;@GOTO(MSG_EVT_78_GIL)
;』


;@Habitat:サマーズ／フィールド／ビーチ(スカイウォーカーそば)
;@Person:リゾート客A
;@Figure:リゾート女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESORT_A
MSG_SUMS_RESORT_A;
◆You look so serious...@KEY()↓
◆You’re in Summers, a dream paradise.@KEY()↓
◆Relax, and have some fun.
@KEYNP()
;jpn:◆きみ@GOSUB(MSG_SUB_TATI) ずいぶん↓
;jpn: きんちょうしたかお してるね。@KEY()↓
;jpn:◆ここは サマーズ。@WI(20)↓
;jpn: ゆめのパラダイスだよ。@KEY()↓
;jpn:◆もっと リゾートっぽく↓
;jpn: らくに しなさいよ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:リゾート客B
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESORT_B
MSG_SUMS_RESORT_B;
◆The sky’s blue and the sun is high.@KEY()↓
◆The prices here are so high, it’ll make your face turn blue!@KEY()↓
◆That’s Summers!
@KEYNP()
;jpn:◆そらは あおくて たかいし↓
;jpn: ぶっかも あおくなるほど↓
;jpn: たかい! サマーズって まちは。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:街の人１
;@Figure:Tシャツ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_1
MSG_SUMS_1;
◆If you’re bored, go check out the ”Scaraba Cultural Museum.”@KEY()↓
◆It may be helpful to you.@KEY()↓
◆They have a hieroglyph from a pyramid.
@KEYNP()
;jpn:◆たいくつしてるなら↓
;jpn: 「スカラビぶんかはくぶつかん」↓
;jpn: にでも いったら どうだい。@KEY()↓
;jpn:◆ためになるよ。↓
;jpn: ピラミッドのヒエログリフとかが↓
;jpn: あるらしいしさ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:街の人２
;@Figure:アーティスト
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_2
MSG_SUMS_2;
◆Another nice day.@KEY()↓
◆Summers always has sunny days.
@KEYNP()
;jpn:◆きょうも いいてんきね。@KEY()↓
;jpn:◆サマーズの かいがんって↓
;jpn: いつも いいおてんきなのよ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:アイス売り
;@Figure:スロットブラザース
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_ICELOLLY
MSG_SUMS_ICELOLLY;
;◆Want a popsicle?
;jpn:◆アイスキャンディーは↓;
;jpn: いかがっすか?@KEY()↓
@GOSUB(MSG_SUMS_ICE)
』


;@Habitat:サマーズ／フィールド／街の至るところ
;@Person:九官鳥
;@Figure:九官鳥
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_BIRD
MSG_SUMS_BIRD;
;この九官鳥は、サマーズのまちのあちこちを
;適当にとびまわっています。そして、サマーズの人々の
;セリフをアトランダムにしゃべるのです。
◆(It’s a Myna bird!)@KEY()↓
;jpn:◆キューカンチョーッ!@KEY()↓
@RAND(5)
@ONGOTO(MSG_SUMS_SWIMSUITGAL_A,MSG_SUMS_SWIMSUITGAL_B,MSG_SUMS_SWIMSUITMAN_D,MSG_SUMS_1,MSG_TOTO_A)
@GOTO(MSG_SUMS_SWIMSUITMAN_A)
』


;@Habitat:サマーズ／フィールド／トトの街の辺り
;@Person:街の人A
;@Figure:若い船乗り
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_A
MSG_TOTO_A;＃
@CHKFGOTO(FLG_TLPT_SKRB,_TOTO_A_LATER)
◆To go to Scaraba, you need to cross the sea.@KEY()↓
◆However a monster named Kraken lives in the open sea.@KEY()↓
◆He attacks ships that pass through.@KEY()↓
◆Are you scared?
@KEYNP()
;jpn:◆スカラビには うみをわたらねば↓
;jpn: ならないんだわな。@KEY()↓
;jpn:◆とはいえ↓
;jpn: あれたうみには↓
;jpn: クラーケンたらいう バケモンが@KEY()↓
;jpn:◆げんきに ふねを↓
;jpn: おそってくれるんだわー。@KEY()↓
;jpn:◆こわいっしょ?@KEYNP()
』
_TOTO_A_LATER;
◆I’m a mighty sailor man@KEY()↓
◆A mountain man I’m not@KEY()↓
◆The open sea is home for me@KEY()↓
◆And mountains aren’t worth snot@KEY()↓
◆...I’m writing a song for sailors.
@KEYNP()
;jpn:◆音うみの おとこはよー@WI(20)↓
;jpn: やまの おとことはよー@WI(20)↓
;jpn: ちょと@WI(15) ちがうよー音@KEY()↓
;jpn:◆‥‥いま うみのおとこのうたを↓
;jpn: つくってるところなんだ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／トトの街の辺り
;@Person:街の人C
;@Figure:スペイン人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_C
MSG_TOTO_C;
◆Dinosaurs existed!@KEY()↓
◆I saw one!@KEY()↓
◆It had been out of the underground when it dried out.@KEY()↓
◆Of course, it was dead!@KEY()↓
◆Believe what I’m saying!
@KEYNP()
;jpn:◆きょうりゅうは いる!↓
;jpn: おれは みたんだってば!@KEY()↓
;jpn:◆じめんのしたから↓
;jpn: はいあがってきて↓
;jpn: ひからびて しんでたんだわ!@KEY()↓
;jpn:◆おれの いうことを↓
;jpn: しんじてくでーっ!@KEYNP()
』

;@Habitat:サマーズ／フィールド／トトの波止場
;@Person:船乗りA
;@Figure:若い船乗り
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_SAILOR_A
MSG_TOTO_SAILOR_A;
@CHKFGOTO(FLG_TLPT_SKRB,_TOTO_SAILOR_LATER)
@CHKFGOTO(FLG_PU,_TOTO_SAILOR_AFTER)
@CHKFGOTO(FLG_TEMP_9,_TOTO_SAILOR_TMP)
_TOTO_SAILOR_A_START;
◆Would you like a boat ride?↓
<Yes>
<No>
;jpn:◆ふねに のりたいのかい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TOTO_SAILOR_A_YES,_TOTO_SAILOR_A_NO)
_TOTO_SAILOR_A_NO;
◆Ok, I understand.
;jpn:◆そうか そんなら いいんだ。
@CHKF(FLG_TEMP_9)@FALSE_GOTO(_TOTO_SAILOR_A_YES_A)
@KEYNP()
』
_TOTO_SAILOR_A_YES_A;
@KEY()↓
_TOTO_SAILOR_A_YES;
◆I don’t feel like sending a ship out.@KEY()↓
◆I’m worried about my wife...@KEY()↓
◆I’m not afraid of the Kraken!@KEY()↓
◆.....@KEY()↓
;jpn:◆ふねをだす きに↓
;jpn: なれねぇんだよ。@KEY()↓
;jpn:◆にょうぼの ことで↓
;jpn: なやんでてね‥‥。@KEY()↓
;jpn:◆クラーケンが↓
;jpn: こわいわけじゃねぇんだ。@KEY()↓
@WI(60)↓
◆My wife’s totally ignoring her Magic cake business.@KEY()↓
◆These days she spends her time hanging out in a strange club.@KEY()↓
◆We no longer have any mutual interests to discuss.@KEY()↓
◆Is our relationship over?@KEY()↓
◆...＊Sigh＊
@KEYNP()
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆にょうぼが↓
;jpn: 「マジックケーキ」うりの↓
;jpn: しょうばい そっちのけで@KEY()↓
;jpn:◆おかしな みせに↓
;jpn: いりびたっててよう。@KEY()↓
;jpn:◆はなしが ぜんぜん↓
;jpn: あわなくなっちまったんだ。@KEY()↓
;jpn:◆おれたち もう おしまいかなぁ。↓
;jpn: ‥‥フー。@KEYNP()
@SETF(FLG_TEMP_9)
』
_TOTO_SAILOR_TMP;
◆Do you wanna hear the same story again?↓
<Yes>
<No>
;jpn:◆なんども おんなじはなしを↓
;jpn: きくんだな?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TOTO_SAILOR_A_YES,_TOTO_SAILOR_A_NO)
@GOTO(_TOTO_SAILOR_A_NO)

_TOTO_SAILOR_AFTER;
@CHKFGOTO(FLG_TOTO_SAILOR_MSGCHG,_TOTO_SAILOR_AFTER_MAIN)
◆Thank you!@KEY()↓
◆You made my wife wake up.@KEY()↓
◆She quit talking about all that serious crap...@KEY()↓
◆Yeah!@KEY()↓
◆Let’s work hard!@KEY()↓
;jpn:◆あんたたちの おかげで↓
;jpn: にょうぼが↓
;jpn: めを さましてくれた。@KEY()↓
;jpn:◆ぜんっぜん ムツカシイことも↓
;jpn: いわなくなったし‥‥。@KEY()↓
;jpn:◆さぁ!@WI(15) おれも はりきるぞ!@KEY()↓
@SETF(FLG_TOTO_SAILOR_MSGCHG)
;
_TOTO_SAILOR_AFTER_MAIN;２度目以降
◆If you’re courageous, get on this boat.@KEY()↓
◆You’ll probably see the Kraken and experience getting seasick!@KEY()↓
◆After all, it could only cost you your life, and you got that for free!@KEY()↓
◆Luck will determine the outcome of this voyage.@KEY()↓
◆So, do you want to sail the seas to Scaraba?@KEY()↓
;jpn:◆ゆうきのあるやつなら↓
;jpn: ふねに のんなよ。@KEY()↓
;jpn:◆クラーケンも みられるし↓
;jpn: ふなよいも けいけんできるぜ。@KEY()↓
;jpn:◆どうせ ただでもらった いのち。↓
;jpn: ひろうも おとすも うんしだい。↓
;jpn: スカラビに わたるかね?@KEY()↓
_TOTO_SAILOR_LATER_MAIN;;
◆Twenty bucks per person is fine with me.↓
;jpn:◆ひとり ２０ドルで いいぜ。↓
@WINR_MONEY()
<Yes>
<No>

;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_TOTO_SAILOR_A_AFTER_YES,_TOTO_SAILOR_A_AFTER_NO)

_TOTO_SAILOR_A_AFTER_NO;
◆I understand.@KEY()↓
◆Stay here and shiver in fear for your future!@KEY()↓
◆Ha ha ha ha ha ha!
@KEYNP()
;jpn:◆そうか むりもないな。↓
;jpn: そのへんで ぶるぶるふるえてな。@WI(20)↓
;jpn: ハハハハハ!@KEYNP()
』

_TOTO_SAILOR_A_AFTER_YES;
@MUL_ACTIVE_PLAYER(20)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_TOTO_SAILOR_A_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(0)
@WINR_MONEY()
◆Ready!@KEY()↓
◆We’re reckless, baby!@KEY()↓
◆Bon Voyage!
@KEYNP()
;jpn:◆ようし!↓
;jpn: いのちしらずたちよ!↓
;jpn: ヨーソロー!@KEY()
@CLOSEALL()
@GOTO(MSG_EVT_85_ONBOARD)
』

_TOTO_SAILOR_A_NOMONEY;
◆What?@KEY()↓
◆You have no money?!@KEY()↓
◆Come back after you make some money.
@KEYNP()
;jpn:◆えっ かねがない?!↓
;jpn: どっかで かせいで またおいで。@KEYNP()
』
_TOTO_SAILOR_LATER;
◆Compared to the olden days, this boat ride is like being on a luxury liner.@KEY()↓
◆Do you want another ride?@KEY()↓
◆I’ll give you a ride if you want, since you destroyed the Kraken.@KEY()↓
;jpn:◆むかしにくらべりゃ↓
;jpn: この ふねのたびも↓
;jpn: まるで ゆうらんせんさ。@KEY()↓
;jpn:◆おまえたちが クラーケンを↓
;jpn: たいじしてくれたから‥‥@WI(30)↓
;jpn: また のるかい?@KEY()↓
@GOTO(_TOTO_SAILOR_LATER_MAIN)

MSG_CAT_1;ネコ
◆Fsst Fsst.
@KEYNP()
;DAN: Just ask me.
;jpn:◆ゴロゴロ@KEYNP()
』
MSG_CAT_2;やなぎのネコ
◆Meow.
@KEYNP()
;jpn:◆ニャア@KEYNP()
』
;-------------------------------------------------

MSG_SUMS_STOIC_WIFE;マジックケーキ売り(ストイック)
◆I’ve finally awakened the inner me, the true self.@KEY()↓
◆The patrons of this club are able to stare into their own soul hard@KEY()↓
◆enough to burn a hole in their psyche.@KEY()↓
◆I’m now comfortable enough to stare at the real me, the true self,@KEY()↓
◆and burn the impression into my super−ego.@KEY()↓
◆I want to be in this comfort zone at any time, all the time or at no time.@KEY()↓
◆My id is telling me...
;jpn:◆わたし やっと このごろ↓
;jpn: じいしきに めざめたと↓
;jpn: いっていいとおもうの。@KEY()↓
;jpn:◆このクラブの ひとたちって@KEY()↓
;jpn:◆じこの そんざいを↓
;jpn: あなが あくほど↓
;jpn: みつめていて‥‥@KEY()↓
;jpn:◆わたし あながあきそうに↓
;jpn: ここちいい じこよ。@KEY()↓
;jpn:◆しろくじちゅうも↓
;jpn: ごろくじちゅうも@KEY()↓
;jpn:◆このみせに↓
;jpn: そんざいしていたいわ。
@CHKFGOTO(FLG_SUMS_MASSAGE_APPEAR,_SUMS_STOIC_WIFE_TMP)
@KEYNP()
』
_SUMS_STOIC_WIFE_TMP;
@KEY()↓
◆What?  What?@WI(15)  Magic Cake?@KEY()↓
◆You came all this way just to eat my Magic Cake?↓
<Yes>
<No>
;jpn:◆えっ@WI(20) マジックケーキですって?↓
;jpn: わたしの マジックケーキを↓
;jpn: たべたくて わざわざ ここまで?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_STOIC_WIFE_YES,_SUMS_STOIC_WIFE_NO)
_SUMS_STOIC_WIFE_NO;
◆Okay then, don’t get in my way while I search for the little girl within me...
@KEYNP()
;jpn:◆そう‥‥じゃ わたしの↓
;jpn: なんかいのだいぼうけんというか↓
;jpn: むつかしばなしというか‥‥の@KEY()↓
;jpn:◆じゃまな きんしを しないで。@KEYNP()
』
_SUMS_STOIC_WIFE_YES;
◆I see...okay...@KEY()↓
◆Why don’t you stop by a little cart out on the beach later?
@KEYNP()
;jpn:◆‥‥そ@WI(15) そう。↓
@WI(60)↓
;jpn: ‥‥‥。@KEY()↓
;jpn:◆じゃ あとで ビーチの↓
;jpn: ワゴンまで いらっしゃい。@KEY()
@CLOSEALL()
;ケーキ妻を階段に消えるアニメと交換
@REMOVE_CHAR( PRSN_SUMS_STOIC_G, ANIM_GO_OUT_CAKEWIFE )
@WAITSYS()	;ケーキ妻が階段に消えるのをじっと待つ
@SETF(FLG_SUMS_STOIC_WIFE_DISAPPEAR)
』
;-------------------------------------------------

;更に追加分

MSG_SUMS_SWIMSUITMAN_E;
◆Only a tanning pro like me is able to get an actual suntan on the palms of his hands!
@KEYNP()
;jpn:◆(おれみたいな ひやけのプロは@WI(20)↓
;jpn: こうして てのひらもやくもんだ)@KEYNP()
』
MSG_SUMS_SWIMSUITGAL_C;
◆I’m just trying to take a nap in the shade.  Don’t bother me!
@KEYNP()
;jpn:◆(ひかげで ひるねしてるの。@WI(20)↓
;jpn: じゃましないでね)@KEYNP()
』
;-------------------------------------------------

MSG_SUMS_RESTAURANT_E;
◆Pooooweeeet!@WI(60)↓
  Oooo...sorry...@KEY()↓
◆Y’know, I can’t quite describe it...@KEY()↓
◆Drinking glass after glass of ice coffee is...well...@KEY()↓
◆Buuuurp!@WI(90)↓
  Oooo...’scuse me...
@KEYNP()
;jpn:◆プハーーーーッ!@WI(90)↓
;jpn: いや しっけいしっけい。@KEY()↓
;jpn:◆なんちゅうか この↓
;jpn: ひるまのビールっちゅうのは↓
;jpn: じつに なんちゅうか‥‥@KEY()↓
;jpn:◆ゲフーッ!@WI(90)↓
;jpn: いや しっけいしっけい。@KEYNP()
』
;-------------------------------------------------

;それに輪をかけて追加分
;0717

MSG_TOTO_WELCOME
◆(East of here is the port town of Toto)@KEY()↓
◆...No, no...↓
  I’m not a billboard...
@KEYNP()

;jpn:◆(ここから ひがしは↓
;jpn: みなとのあるまち「トト」)↓
@KEY()↓
;jpn:◆@WI(10)‥‥わ @WI(20)わしは↓
;jpn: かんばんじゃ ないぞ。@KEYNP()
』


;《ストイッククラブの近く》
MSG_READ_SUMMERS_SIGN3
◆(Have a fantastic vacation!@KEY()↓
◆At least until you run out of money.↓
      Hotel Du Summers)
@KEYNP()
;jpn:◆(よいバカンスを!@WI(20)↓
;jpn: あなたの おかねのつづくかぎり)↓
;jpn:     「オテル・ド・サマーズ」@KEYNP()
』


;《病院の近く》
MSG_READ_SUMMERS_SIGN5
◆There is graffiti on the board...The handwriting is hard to read...@KEY()↓
◆(@DSP_NAME(PC_NESS) can eat my shorts!@WI(20)↓
  For a neighbor, he’s a loser!)
@KEYNP()
;jpn:◆かんばんには へたなもじで↓
;jpn: らくがきが されていた。@KEY()↓
;jpn:◆(ボンジュール @DSP_STS(STS_PC_NAME_NES)!@WI(20)↓
;jpn: おまえが これをよんでるころ↓
;jpn: おれは もう へっへっへ!)@KEYNP()
』
;-------------------------------------------------
