;-------------------------------
;@Habitat:ランマ／宮殿／玉座の間
;@Person:老師・イースーチー
;@Figure:師匠
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_MASTER
MSG_RAMA_MASTER;
@CHKFGOTO(FLG_WIN_GIEGU,_RAMA_MASTER_END)
@CHKFGOTO(FLG_PU,_RAMA_MASTER_PU)
@CHKFGOTO(FLG_RAMA_OK,_RAMA_MASTER_OK)
@CHKFGOTO(FLG_TEMP_9,_RAMA_MASTER_1)
◆I won’t say anything.@KEY()↓
◆Go to ”Mu,” the place of emptiness again.
@KEYNP()
;jpn:◆なにも もうしあげませぬ。↓
;jpn: もういちど ムのばしょへ↓
;jpn: おいきくだされ。@KEYNP()
@GOSUB(MSG_EVT_79_MU_SET_HRECT_A);修行再セット
』
_RAMA_MASTER_1;
◆Go quickly!
@KEYNP()
;jpn:◆さぁ はやく!@KEYNP()
』

_RAMA_MASTER_OK;修行後のセリフとして
◆I am proud.@KEY()↓
◆You have completed your Mu training.@KEY()↓
◆There is nothing more to teach you from the holy writings.
@KEYNP()
;jpn:◆「ムのしゅぎょう」に↓
;jpn: よくぞ たえてくれました。@KEY()↓
;jpn:◆これで このイースーチーめが↓
;jpn: あなたに おおしえすることは↓
;jpn: なにも なくなりました。@KEYNP()
@CLOSE()
@GOSUB( MSG_SUB_BGM_FADEOUT_LONG )
@BGMSTART(0,BGM_home0);エデン序曲
@WI(60)
@OPEN( 1 )
◆Prince @DSP_NAME(PC_POO),@KEY()↓
◆I shall relay a message to you from Eternity.@KEY()↓
◆The evil entity that controls all wickedness is preparing for@KEY()↓
◆the greatest struggle of all time...@KEY()↓
◆The only ones who can challenge the entity are three boys and one girl.@KEY()↓
◆One named @DSP_NAME(PC_NESS) is the leader of the four.@KEY()↓
◆One of the boys is you, Prince @DSP_NAME(PC_POO).@KEY()↓
◆Now that you’ve completed your training, search out @DSP_NAME(PC_NESS) at once.@KEY()↓
◆For all beings, for the earth herself...@KEY()↓
◆I pray for growth in the might of the four.@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさま@KEY()↓
;jpn:◆えらばれしランマのおうじの↓
;jpn: あなたに↓
;jpn: てんのおつげを つたえまする。@KEY()↓
;jpn:◆すべてのじゃあくなるものを↓
;jpn: うごかし しはいするカミが@KEY()↓
;jpn:◆れきしじょう さいだいの↓
;jpn: たたかいを いどんでおりまする。@KEY()↓
;jpn:◆これを うけてたてるものは↓
;jpn: たった４にんの しょうねんたち。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)というものが↓
;jpn: その かしらになりまする。@KEY()↓
;jpn:◆４にんのうちの ひとりが↓
;jpn: @DSP_STS(STS_PC_NAME_POO)おうじ‥‥あなたです。@KEY()↓
;jpn:◆さいごの しれんに うちかった↓
;jpn: いま!@KEY()↓
;jpn:◆すぐに @DSP_STS(STS_PC_NAME_NES)どののもとへ↓
;jpn: とんでくだされ!@KEY()↓
;jpn:◆おおくの ひとびとのために↓
;jpn: このよの へいわのために‥‥@KEY()↓
;jpn:◆おおきなちからに↓
;jpn: なってくだされませい!@KEYNP()
@CLOSEALL()
@WI(1)
@OPEN(14)
@EXP_UP_POINT(PC_POO,6000)	;経験値アップ!
@FKEY()				;必要?
@CLOSEALL()
@GOTO(MSG_EVT_80_ADD_PU_SUMS)	;S_EVENTへ
』
;
;◆あらゆる しゅぎょうをつんだ↓
; あなたですが@KEY()↓
;◆さいごのしれんに うちかったら↓
; @DSP_STS(STS_PC_NAME_NES)のいるところへ↓
; かけつけることになりましょう。@KEY()↓
;◆‥‥のこされたときは わずか。@KEY()↓
;◆すぐに しれんのちに↓
; おもむいてくだされ。@KEY()↓
;◆アンニャやまの「ムのばしょ」へ↓
; すぐに いって↓
; しれんを うけてくださりませ。@KEYNP()
』
_RAMA_MASTER_PU;
◆Your future battle will be considerably more dangerous than you expect.@KEY()↓
◆Don’t be careless...
@KEY()
;jpn:◆あなたがたの これからの↓
;jpn: たたかいには@KEY()↓
;jpn:◆ますます ふきつなかげが↓
;jpn: いろこくさしています。@KEY()↓
;jpn:◆くれぐれも↓
;jpn: ゆだんめされぬように‥‥。@KEY()
@CLOSEALL()			;ワープ前にウィンドウ閉じる
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@WARP(WARP_RAMA_147)
』
_RAMA_MASTER_END;＆
◆As I thought, the prophecy foretold of our only chance for success.@KEY()↓
◆Please enjoy the life ahead of you as a regular boy.
@KEYNP()
;jpn:◆やはり よげんは↓
;jpn: もっとも よいかたちで↓
;jpn: じょうじゅしました。@KEY()↓
;jpn:◆あとは おもいきり↓
;jpn: ふつうのしょうねんとしての↓
;jpn: ひびを おたのしみくだされ。@KEYNP()
』


;@Habitat:ランマ／宮殿／玉座の間
;@Person:仕え人A
;@Figure:ランマ男B
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_A
MSG_RAMA_A;
@CHKFGOTO(FLG_WIN_GIEGU,_RAMA_A_END)
@CHKFGOTO(FLG_PU,_RAMA_A_LATER)
◆Use the treasures of Dalaam as you wish.@KEY()↓
◆Go in peace.
@KEYNP()
;jpn:◆ランマのくにの たからは↓
;jpn: あなたさまが ごじゆうに↓
;jpn: おつかいください。@KEY()↓
;jpn:◆おげんきで。@KEYNP()
』
_RAMA_A_LATER;
◆Didn’t you meet up with many monsters along the way?@KEY()↓
◆Recently, several bad incidents occurred in this peaceful country...
@KEYNP()
;jpn:◆みちみち バケモノに↓
;jpn: あわれませんでしたか?@KEY()↓
;jpn:◆このごろは どうも↓
;jpn: この へいわなくに にも↓
;jpn: よからぬ ことが‥‥@KEYNP()
』
_RAMA_A_END;＆
◆We understand that you’ve experienced hardship in the past.@KEY()↓
◆No one could fight the evil entity, except you.@KEY()↓
◆We are proud.@KEY()↓
◆We are happy.
@KEYNP()
;jpn:◆わたくしたちは あなたがたの↓
;jpn: いままでの くなんのふかさを↓
;jpn: ぞんじあげております。@KEY()↓
;jpn:◆だれひとりとして↓
;jpn: あなたがたのかわりに↓
;jpn: たたかうことなど@KEY()↓
;jpn:◆できなかったでありましょう。@WI(30)↓
;jpn: おみごとでございました。@WI(30)↓
;jpn: うれしゅうございます。@KEYNP()
』


;@Habitat:ランマ／宮殿／玉座の間
;@Person:電話行者
;@Figure:電話行者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_PHONEMASTER
MSG_RAMA_PHONEMASTER;
;ネスパパにかかるセーブ電話。
@CHKFGOTO(FLG_PU,MSG_GLOBAL_TELEPHONE_RAMA)
@GOTO(MSG_PAPA)
』

;@Habitat:ランマ／宮殿／玉座の間
;@Person:プーの準備品箱
;@Figure:東洋風プレゼント箱
;@AppearanceKey:0
;@ActionScript:◆プレゼント箱
;@GoodsMessage:0
;@CheckMessage:MSG_BOX_RAMA_1
;@Message:0
;MSG_BOX_RAMA_1;@MiuraAdapted
@CHKFGOTO(FLG_BOX_RAMA_1,MSG_BOX_EMPTY)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0) opened the present.@KEY()↓
◆Inside was the @DSP_GOODS(GDS_FOOD_LUNCH_KING).
@KEYNP()
;jpn:◆@DSP_NAME(0)は↓
;jpn: プレゼントのはこを あけた。@KEY()↓
;jpn:◆おうじゃのべんとうが あった。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(MSG_BOX_ITEMFULL)
@SE(SE_se74_my_get)
@GOODSIN(PC_ALL,GDS_FOOD_LUNCH_KING)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0) got it.
;jpn:◆@DSP_NAME(0)は↓
;jpn: おうじゃのべんとうを↓
;jpn: てにいれた。
@KEYNP()
@SETF(FLG_BOX_RAMA_1)
』

;@Habitat:ランマ／宮殿／廊下
;@Person:仕え人B
;@Figure:ランマ女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_B
MSG_RAMA_B;＆
@CHKFGOTO(FLG_WIN_GIEGU,_RAMA_B_END)
@SET_LOOPREG(1)
_RAMA_B_Q_LOOP;
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_RAMA_B_POO_NO)
@GET_ORDER_PLAYER(0)
@EQ(PC_POO)
@TRUE_GOTO(_RAMA_B_2)
@INC()
@GOTO(_RAMA_B_Q_LOOP)
_RAMA_B_2;
@SET_LOOPREG(PC_POO)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_RAMA_B_POO_NO)
◆Prince @DSP_NAME(PC_POO).@KEY()↓
◆You’re my favorite.@KEY()↓
◆(blush) tee hee hee.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさま。↓
;jpn: きょうも ス・@WI(20)テ・@WI(20)キ@WI(20) です。↓
;jpn: ポッ@KEYNP()
』

_RAMA_B_POO_NO;ネスと共に
◆Since you left for a foreign country,@KEY()↓
◆the girls of Dalaam have had to endure their loneliness without you.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさまが↓
;jpn: がいこくに いかれてから↓
;jpn: ランマの おんなのコたちは@KEY()↓
;jpn:◆さみしさを かみころして↓
;jpn: いきておりますわ。@KEYNP()
』
_RAMA_B_END;＆
◆Prince @DSP_NAME(PC_POO) has returned, so everyone is extremely happy.@KEY()↓
◆Please stay and relax.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじも↓
;jpn: もどってこられたし↓
;jpn: みんな おおよろこび。@KEY()↓
;jpn:◆ゆっくりしてってね。@@KEYNP()
』

;----------------------------------------
;@Habitat:ランマ／住人の家A／住人の家A
;@Person:住人A
;@Figure:ランマ男A
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_HOUSE_A
MSG_RAMA_HOUSE_A;
;(プレゼントボックスを置く)
◆Please come in.@KEY()↓
◆Look around the house as much as you want.
@KEYNP()
;jpn:◆これは これは。↓
;jpn: いくらでも いえのなかを↓
;jpn: ごらんください。@KEYNP()
』

;@Habitat:ランマ／住人の家A／住人の家A
;@Person:プレゼント箱
;@Figure:東洋風プレゼント箱
;@AppearanceKey:0
;@ActionScript:◆プレゼント箱
;@GoodsMessage:0
;@CheckMessage:MSG_BOX_RAMA_2
;@Message:0
;MSG_BOX_RAMA_2;@MiuraAdapted
@CHKFGOTO(FLG_BOX_RAMA_2,MSG_BOX_EMPTY)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0) opened the present.@KEY()↓
◆Inside was a @DSP_GOODS(GDS_TOOL_ANGEL_SEED).@KEY()↓
;jpn:◆@DSP_NAME(0)は↓
;jpn: プレゼントのはこを あけた。@KEY()↓
;jpn:◆エンジェルシードが あった。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(MSG_BOX_ITEMFULL)
@SE(SE_se74_my_get)
@GOODSIN(PC_ALL,GDS_TOOL_ANGEL_SEED)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0) got it.
;jpn:◆@DSP_NAME(0)は↓
;jpn: エンジェルシードを↓
;jpn: てにいれた。
@KEYNP()
@SETF(FLG_BOX_RAMA_2)
』

;@Habitat:ランマ／住人の家B／住人の家B
;@Person:住人B
;@Figure:ランマ女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_HOUSE_B
MSG_RAMA_HOUSE_B;
@CHKFGOTO(FLG_PU,_RAMA_HOUSE_B_LATER)
◆I just roasted some garlic and ate it,@KEY()↓
◆so the room still stinks.
@KEYNP()
;jpn:◆いま にんにくやいてたべてたから↓
;jpn: へやのなかが くさいんです。@KEYNP()
』
_RAMA_HOUSE_B_LATER;
◆I didn’t eat any garlic today, so the room doesn’t stink.
@KEYNP()
;jpn:◆きょうは にんにくを↓
;jpn:	たべなかったから↓
;jpn: へやのなかが くさくない。@KEYNP()
』

;@Habitat:ランマ／住人の家C／住人の家C
;@Person:住人C
;@Figure:ランマ男B
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_HOUSE_C
MSG_RAMA_HOUSE_C;
;@SE(SE_se72);不明
@CHKFGOTO(FLG_WIN_GIEGU,_RAMA_HOUSE_C_END)
@SET_LOOPREG(PC_POO)			;プーのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_RAMA_HOUSE_C_TMP)
◆You know that you do do everything well, right?@KEY()↓
◆Do do?  Ooops.@KEY()↓
◆Say, Prince @DSP_NAME(PC_POO), are you still popular with the girls?@KEY()↓
<Yes>
<No>
;jpn:◆ほっぺたに ちからが↓
;jpn: とまってました。↓
;jpn: おっとちがった。 カ でしたね。@KEY()↓
;jpn:◆どうです?@WI(15) @DSP_STS(STS_PC_NAME_POO)おうじ↓
;jpn: このごろも もててますか?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_RAMA_HOUSE_C_YES,_RAMA_HOUSE_C_NO)
_RAMA_HOUSE_C_NO;
◆You’ve been acting very serious lately.@KEYNP()
;jpn:◆さいきん なんか↓
;jpn: きびしすぎるかんじだもんなぁ。@KEYNP()
』
_RAMA_HOUSE_C_YES;
◆I heard you’re living a more serious lifestyle these days.
@KEYNP()
;jpn:◆と いっても↓
;jpn: すっごくまじめに やってるって↓
;jpn: うわさですよ。@KEYNP()
』
_RAMA_HOUSE_C_TMP;
◆We have difficulty communicating with foreigners.
@KEYNP()
;jpn:◆わたしたち↓
;jpn: がいこくの かたには↓
;jpn: うまく はなしができないんです。@KEYNP()
』
_RAMA_HOUSE_C_END;＆
◆Hello.@KEY()↓
◆Congratulations.@KEY()↓
◆Thank you...@KEY()↓
◆...Oh, my foreign language skills worked!
@KEYNP()
;jpn:◆こんにちは。@WI(20)おめでとう。@WI(20)↓
;jpn: ありがとう‥‥@KEY()↓
;jpn:◆‥‥あらま ぼくったら↓
;jpn: がいこくごが つうじたみたい。@KEYNP()
』

;----------------------------------------
;@Habitat:ランマ／フィールド／フィールドの適当なところ
;@Person:外のランマ人A
;@Figure:ロープマジック男
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_FIELD_A
MSG_RAMA_FIELD_A;
◆.....@KEY()↓
◆preeet!...@KEY()↓
◆pooooot!...
@KEYNP()
;jpn:◆‥‥‥。↓
;jpn: ‥‥‥    @WI(60)プッ‥‥‥↓
;jpn: ‥‥‥@WI(20)プピー‥‥。@KEYNP()
』

;@Habitat:ランマ／フィールド／フィールドの適当なところ
;@Person:外のランマ人B
;@Figure:ランマ男A
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_FIELD_B
MSG_RAMA_FIELD_B;
@CHKFGOTO(FLG_WIN_GIEGU,_RAMA_FIELD_B_END)
@CHKFGOTO(FLG_PU,_RAMA_FIELD_B_LATER)
◆What is immortality.....?@KEY()↓
◆Is it everlasting life?@KEY()↓
◆Mmmmm Mmmmm.
@KEYNP()
;jpn:◆ふめつ‥‥とは なにか?↓
;jpn: そんざいの たえられないかるさ。↓
;jpn: うーむ うーむ。@KEYNP()
』
_RAMA_FIELD_B_LATER;＃
◆What’s the difference between ”existing” and ”exiting”@KEY()↓
◆.....Nothing?@KEY()↓
◆Mmmmm Mmmmm
@KEYNP()
;jpn:◆「そんざい」と「ぞんざい」の↓
;jpn: おおきな ちがいは‥‥@KEY()↓
;jpn:◆‥‥ないのではないか?↓
;jpn: うーむ うーむ。@KEYNP()
』
_RAMA_FIELD_B_END;＆
◆I’m a little embarrassed to say it, but I’ll tell you anyway...@KEY()↓
◆I thought ”Philosophy” was the study of stones.@KEY()↓
◆I now realize it’s about studying all night...@KEY()↓
◆...What?@KEY()↓
◆It’s not?
@KEYNP()
;jpn:◆‥‥いまさら↓
;jpn: はずかしいんだけどね@WI(30)↓
;jpn: ぼくは‥‥@KEY()↓
;jpn:◆「てつがく」って@WI(20) てつのことを↓
;jpn: けんきゅうするのかと↓
;jpn: おもっていたんだよ。@KEY()↓
;jpn:◆てつやで↓
;jpn: べんきょうすること↓
;jpn: だったんだねぇ‥‥。@KEY()@WI(30)↓
;jpn:◆‥‥えっ ちがうの?@KEYNP()
』

;@Habitat:ランマ／フィールド／フィールドの適当なところ
;@Person:外のランマ人C
;@Figure:ランマ女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_FIELD_C
MSG_RAMA_FIELD_C;
@CHKFGOTO(FLG_PU,_RAMA_FIELD_C_LATER)
◆I heard that Prince @DSP_NAME(PC_POO) is deeply into ”Moo Training.”@KEY()↓
◆...I want to help him, if I can.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさま↓
;jpn: さいきん 「メのしゅぎょう」に↓
;jpn: こってらっしゃるって ホント?@KEY()↓
;jpn:◆わたし うまれつき↓
;jpn: メは いいほうなの。@WI(20)↓
;jpn: ‥‥おしえてあげたいわ。@KEYNP()
;◆うちのくにが オリンピックに↓
; さんかするようになったら↓
; どんなユニホームに なるかしら。@KEYNP()
』
_RAMA_FIELD_C_LATER;
◆I wonder if Prince @DSP_NAME(PC_POO) succeeded in ”Moo Training”?@KEY()↓
◆I wanted him to come by and show me his best barnyard impression.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさまの↓
;jpn: 「メのしゅぎょう」は↓
;jpn: うまくいったのかしら。@KEY()↓
;jpn:◆よくなった メで↓
;jpn: わたしを みつめてほしかった。@KEYNP()
』

;@Habitat:ランマ／フィールド／無の場所
;@Person:無の場所の立て札
;@Figure:立て札
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_RAMA_CHECK_MU
;@Message:0
MSG_RAMA_CHECK_MU;
◆(This is Mu, the place of nothingness.@KEY()↓
◆People who train here must first clear everything from their mind.@KEY()↓
◆If you can make your mind blank and learn the true meaning of ”Mu,”@KEY()↓
◆you’ll pass through.  Mu is Mu...)
@KEYNP()
;jpn:◆(これは ムのばしょ。↓
;jpn: ここにて しれんをうけるものは↓
;jpn: すべてを ムにし@KEY()↓
;jpn:◆いっさいを クウにし↓
;jpn: ムのなんたるかを しるときに↓
;jpn: このばしょを ぬけるものなり。@KEY()↓
;jpn:◆ムとはム)@KEYNP()
;@GOSUB(MSG_DEBUG_EVENT_79)
』

;@Habitat:ランマ／フィールド／ピンククラウド入り口
;@Person:ピンククラウド番人
;@Figure:ランマ男B
;@AppearanceKey:FLG_PU/off
;@ActionScript:◆正面向いてとまったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_GUARD
MSG_RAMA_GUARD;
;鉄のタコ近くの人
@CHKFGOTO(FLG_RAMA_RABBIT_DISAPPEAR,_RAMA_GUARD_LATER)
◆Black rabbits...they’re blocking your path to the cave.@KEY()↓
◆If you think about them, you should feel kind of empty.@KEY()↓
◆...But I can’t seem to get them off of my mind.
@KEYNP()
;jpn:◆どうくつの いりぐちをふさぐ↓
;jpn: くろウサギ‥‥@KEY()↓
;jpn:◆それについて↓
;jpn: ふかく かんがえるのは↓
;jpn: とても むなしい。@KEY()↓
;jpn:◆‥‥しかし↓
;jpn: なんだか きになるなぁ。@KEYNP()
』
_RAMA_GUARD_LATER;ウサギバリアを消した後
◆If it’s safe, I want to be inside.
@KEYNP()
;jpn:◆もし あんぜんなら↓
;jpn: わたしも なかに はいって↓
;jpn: みたかった。@KEYNP()
』

;@Habitat:ランマ／ピンククラウド／大部屋
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_PINK_BOSS/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_RAMA_PINK_BOSS
MSG_RAMA_PINK_BOSS;
@CHKFGOTO(FLG_WIN_PINK_BOSS,MSG_SYS_HANASU_NG)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆You finally got here.@KEY()↓
◆This is the sixth ”Your Sanctuary” location.@WI(20)  But it’s mine now.@KEY()↓
◆Take it from me,@WI(30) if you dare...
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは ６ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし いまは↓
;jpn: わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_PINK_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_RAMA_PINK_4_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_PINK_BOSS)
』
;------------------------------------------------

;以下増補

MSG_RAMA_GIRL_A;ランマ娘
@CHKFGOTO(FLG_PU,_RAMA_GIRL_A_LATER)
◆Prince @DSP_NAME(PC_POO) is always in training these days...@KEY()↓
◆He won’t play with me at all.@KEY()↓
◆I feel so lonely.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさまったら↓
;jpn: ちかごろは しゅぎょうばかり↓
;jpn: なさっていて‥‥@KEY()↓
;jpn:◆ちっとも↓
;jpn: あそんでくださらないのね。@KEY()↓
;jpn:◆わたし さみしい。@KEYNP()
』
_RAMA_GIRL_A_LATER;
◆Prince @DSP_NAME(PC_POO) has good relationships with foreigners.@KEY()↓
◆...What an international person!
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさま↓
;jpn: がいこくの かたと↓
;jpn: おつきあいなさってて@KEY()↓
;jpn:◆‥‥こくさいてき!@KEYNP()
』

MSG_RAMA_GIRL_B;
@CHKFGOTO(FLG_WIN_GIEGU,_RAMA_GIRL_B_END)
@CHKFGOTO(FLG_PU,_RAMA_GIRL_B_LATER)
_RAMA_GIRL_B_MAIN;
◆Oh, Prince @DSP_NAME(PC_POO).@KEY()↓
◆Do you have time to play with me?↓
<Yes>
<No>
;jpn:◆あら @DSP_STS(STS_PC_NAME_POO)おうじさま@KEY()↓
;jpn:◆ひさしぶりに わたしと↓
;jpn: いちゃいちゃ↓
;jpn: してくれるんですか?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_RAMA_GIRL_B_YES,_RAMA_GIRL_B_NO)
_RAMA_GIRL_B_NO;
◆Hah, I knew it.@KEY()↓
◆”Training” changed you!@KEY()↓
◆I’m jealous of your ”training”!
@KEYNP()
;jpn:◆やっぱり↓
;jpn: 「しゅぎょう」のせいね!@KEY()↓
;jpn:◆わたし 「しゅぎょう」が↓
;jpn: にくい!@KEYNP()
』
_RAMA_GIRL_B_YES;
◆Happy me!@KEY()↓
◆(patty cake, patty cake...)
@KEYNP()
;jpn:◆うれしい!@WI(20)↓
;jpn: (いちゃいちゃ)@KEYNP()
』
_RAMA_GIRL_B_LATER;その後
◆There are so many monsters around recently, we can’t relax and have fun.@KEY()↓
◆(weep)
@KEYNP()
』
_RAMA_GIRL_B_END;＆
◆Prince @DSP_NAME(PC_POO) is so cool, but you’re also young and tough.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさまも↓
;jpn: ステキだけど @DSP_STS(STS_PC_NAME_NES)さまも↓
;jpn: ‥‥さわやかで ステキ。@KEYNP()
』

MSG_RAMA_GIRL_C;松(後半メッセージなし)
@CHKFGOTO(FLG_PU,_RAMA_GIRL_C_LATER)
◆Prince @DSP_NAME(PC_POO)...(blush).@KEY()↓
◆He is such a hunk.
;＠プーがいたら「You are」
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさまって↓
;jpn: ‥‥ポ@KEY()↓
;jpn:◆このごろ とても↓
;jpn: ストイックで↓
;jpn: すてきなかんじですー。
@KEYNP()
』
_RAMA_GIRL_C_LATER;その後
◆I’m waiting for Prince @DSP_NAME(PC_POO) to see me and say ”I love you.”
;jpn:◆@DSP_STS(STS_PC_NAME_POO)おうじさまが いつか↓
;jpn: わたしのところに@KEY()↓
;jpn:◆「すきだよ」とか↓
;jpn: いいにきてくれるのを↓
;jpn: まってるんですー。
@KEYNP()
』

MSG_RAMA_OLDMAN_258;リャン・ウー・パー
◆You have nice eyes.@KEY()↓
◆...You must be Prince @DSP_NAME(PC_POO).@KEY()↓
◆Long ago, I completed Mu Training.@KEY()↓
◆I want to show you a higher level of intelligence...@KEY()↓
◆However, I’m still realizing and learning this high level...@KEY()↓
◆I’ll see you again.@KEY()↓
◆So long!
@KEYNP()
;jpn:◆なかなか よい めをしておる。↓
;jpn: ‥‥@DSP_STS(STS_PC_NAME_POO)おうじだな。@KEY()↓
;jpn:◆わしも いちどは↓
;jpn: 「ムのしゅぎょう」を↓
;jpn: なしとげたもの。@KEY()↓
;jpn:◆さらに こうどな ちえを↓
;jpn: おまえに つたえたいが‥‥@KEY()↓
;jpn:◆まだ わしとて↓
;jpn: しゅぎょうちゅうなのじゃ。@KEY()↓
;jpn:◆いずれ また あおう。↓
;jpn: さらば!@KEYNP()
;竜巻を成して消える
@SE( SE_se28_b_offence_up )
@SETF(FLG_RAMA_258_DISAPPEAR)
』
;-------------------------------------------------

MSG_RAMA_PU;
◆You’re here!@KEY()↓
◆We have little, but stay and rest for a while.@KEY()↓
;jpn:◆もう きてくれたのか!@KEY()↓
;jpn:◆ここは なにもない ところだけど↓
;jpn: ゆっくりしてってくれ。@KEY()
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)↓
◆But I’m impressed!  You did so well for one who hasn’t had much training.
@KEYNP()
;jpn:◆しかし↓
;jpn: しゅぎょうも つんでない↓
;jpn: おまえが あれほどやるとはなぁ。@KEYNP()
』
;-------------------------------------------------

MSG_RAMA_RABBIT;ウサギチェック
◆(As strange as this may sound, there are statues of rabbits blocking your way.)@KEYNP()
;jpn:◆(テコでも どかない↓
;jpn: ウサギぞうが ゆくてを↓
;jpn: ふさいでいる)@KEYNP()
』

;
;「ウサギごのみニンジン」をつかう

MSG_RAMA_RABBIT_RECEIVE;
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_CARROT)
@FALSE_GOTO(_RABBIT_RECEIVE_NG)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_TUKATTA)
@SE(SE_se76_my_give)
@LOAD_GLOBAL_REG()
@GOODSOUT_PLAYER(0,0)
←
◆(How strange!@KEY()↓
◆The rabbits and carrots disappeared all at once!)
@KEYNP()	
;jpn:◆(あら ふしぎ!@WI(20)↓
;jpn: ウサギとニンジンは↓
;jpn: いちどに きえてしまった!)@KEYNP()
@SE(SE_se21_b_foe_down)
@HIDE_CHAR(PRSN_RAMA_FIELD_I,OBJFX_HIDE_HSTRIPE)
@HIDE_CHAR(PRSN_RAMA_FIELD_J,OBJFX_HIDE_HSTRIPE)
@HIDE_CHAR(PRSN_RAMA_FIELD_K,OBJFX_HIDE_HSTRIPE)
@SETF(FLG_RAMA_RABBIT_DISAPPEAR)
@!

_RABBIT_RECEIVE_NG;
←
◆That won’t move the rabbits.
@KEYNP()
;jpn:◆そういうものでは↓
;jpn: ウサギは うごかせない。
;@KEYNP()
@!

;-------------------------------------------------

MSG_RAMA_CHECK_SHOP;ランマショップのカンバン
◆Dalaama Restaurant.@KEY()↓
◆(We accept ＄ dollars.)
@KEYNP()
;jpn:◆ランマりょうりの みせ↓
;jpn: (＄ドルも つかえます)@KEYNP()
』
;-------------------------------------------------
