;-------------------------------------------------

;@Habitat:スカラビ/ドラッグストア/ドラッグストア
;@Person:店員
;@Figure:スカラビ男C
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_DRUG
MSG_SKRB_DRUG;@MiuraAppended
@GOSUB(MSG_SHOP_SKRB_DRUG)
』

;----------------------------------------
;@Habitat:スカラビ/ホテル/ホテル
;@Person:フロント
;@Figure:スカラビ男A
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOTEL
;MSG_SKRB_HOTEL;
;◆「グレート・サザーン・ホテル」へ↓
; ようこそ!@KEY()↓
;@GOSUB(MSG_GLOBAL_HOTEL)
;』

;@Habitat:スカラビ/ホテル/ホテル
;@Person:キャッシュディスペンサ
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;@Habitat:スカラビ/ホテル/ホテル
;@Person:武器専門男
;@Figure:武器男
;@AppearanceKey:0
;@ActionScript:◆きょろきょろ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_WEAPON
MSG_SKRB_WEAPON;@MiuraAppended
@GOSUB(MSG_SHOP_SKRB_WEAPON)
』

;----------------------------------------
;@Habitat:スカラビ/住人の家B/住人の家B
;@Person:住人
;@Figure:スカラビ女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOUSE_B
MSG_SKRB_HOUSE_B;
◆No, I don’t want any mummy bandages!@KEY()↓
◆No soliciting allowed please!
@KEYNP()
;jpn:◆ミイラのほうたいなんか↓
;jpn: いらないよ!↓
;jpn: おしうりおことわり!@KEYNP()
』

;@Habitat:スカラビ/住人の家C/住人の家C
;@Person:住人
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOUSE_C
MSG_SKRB_HOUSE_C;
◆I’ve never seen you around here.@KEY()↓
◆What do you want?@KEY()↓
◆I do not have anything you would want.
@KEYNP()
;jpn:◆このへんじゃ みかけないかおだ。↓
;jpn: なにかようかな。↓
;jpn: わしのほうからは ようはないよ。@KEYNP()
』

;----------------------------------------
;@Habitat:スカラビ/病院/受付
;@Person:受付嬢
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOSPITAL_USHER
MSG_SKRB_HOSPITAL_USHER;@MiuraAppended
;◆どなたに ごめんかいですか?@KEY()
@GOSUB(MSG_NURSE_SKRB)
;@GOSUB(MSG_SHOP_SKRB_HOSPITAL)
』

;@Habitat:スカラビ/病院/病院
;@Person:医者
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOSPITAL_DOCTOR
MSG_SKRB_HOSPITAL_DOCTOR;@MiuraAppended
;◆みてもらいたいのは↓
; だれだね?@KEY()
@GOSUB(MSG_DOCTOR_SKRB)
』

;----------------------------------------
;@Habitat:スカラビ/フィールド/港の付近
;@Person:港の人
;@Figure:スカラビ男C
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HARBOR
MSG_SKRB_HARBOR;
◆Did you come from Toto by ship?@KEY()↓
◆There’s a scary monster in the sea...@KEY()↓
◆...Did you beat him?@KEY()↓
◆Or did you escape?@KEY()↓
◆Either way, you are fantastic!
@KEYNP()
;jpn:◆あんたがた トトから ふねで?!↓
;jpn: うみには おそろしいばけものが↓
;jpn: いたっていうのに‥‥@KEY()↓
;jpn:◆‥‥やっつけたのか。↓
;jpn: うまく にげられたのか?↓
;jpn: どっちにしても たいしたものだ。@KEYNP()
』

;@Habitat:スカラビ/フィールド/蛇屋付近
;@Person:蛇屋の人集りA
;@Figure:スカラビ男A
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_A
MSG_SKRB_SNAKESHOP_A;
◆Snakes are so unpleasant, but so cute...@KEY()↓
◆Oh, I don’t know what I may be saying.
@KEYNP()
;jpn:◆へびは きもちわるいけど↓
;jpn: けっこう かわいい‥けど↓
;jpn: ああ@KEY()↓
;jpn:◆おれ なにいってるのか↓
;jpn: わかんないや。@KEYNP()
』

;@Habitat:スカラビ/フィールド/蛇屋付近
;@Person:蛇屋の人集りB
;@Figure:スカラビ男C
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_B
MSG_SKRB_SNAKESHOP_B;
◆Should I keep a snake at home?@KEY()↓
◆Perhaps I should ”asp” an expert.
@KEYNP()
;jpn:◆へび かおうかなぁ↓
;jpn: うちでかうには↓
;jpn: ちょっと ヘビーかな。@KEYNP()
』

;@Habitat:スカラビ/フィールド/蛇屋付近
;@Person:蛇屋の人集りC
;@Figure:スカラビ女
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_C
MSG_SKRB_SNAKESHOP_C;
◆Poisonous snakes cost more.@KEY()↓
◆Why would a fine young man like you need one?
;@ポーラだったら「lady」
@KEYNP()
;jpn:◆どくへびのほうが↓
;jpn: ねだんが たかいのねぇ↓
;jpn: なんにつかうのかしら。@KEYNP()
』

;@Habitat:スカラビ/フィールド/蛇屋付近
;@Person:へび袋売り
;@Figure:スカラビ男B
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_D
MSG_SKRB_SNAKESHOP_D;
◆The @DSP_GOODS(GDS_TOOL_SNAKE_BAG) can hold live snakes!@WI(20)  There are snakes in the sack!@KEY()↓
◆Please, it is a very useful item!@KEY()↓
◆Shall you buy one?  I am humbly offering it to you...↓
<Yes>
<No>
;jpn:◆へびのはいった へびぶくろ。↓
;jpn: ふくろのなかには へびがいる。↓
;jpn: やくにたつよ。 かうか?@KEY()↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_SNAKESHOP_D_YES,_SKRB_SNAKESHOP_D_NO)

_SKRB_SNAKESHOP_D_NO;
◆You are afraid of snakes, are you not?@KEY()↓
◆Heh heh heh.
@KEYNP()
;jpn:◆へびが こわいんだろ↓
;jpn: へっへっへ。@KEYNP()
』

_SKRB_SNAKESHOP_D_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SKRB_SNAKESHOP_D_ITEMFULL)
◆That is 290 dollars, kind @XCHG()@GOSUB(MSG_ESUB_SIR_MAAM).↓
@WINR_MONEY()
<Yes>
<No>
;jpn:◆290ドルだ。↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_SNAKESHOP_D_BUY,_SKRB_SNAKESHOP_D_NO)
@GOTO(_SKRB_SNAKESHOP_D_NO)

_SKRB_SNAKESHOP_D_BUY;
@Q_MONEY(290)
@TRUE_GOTO(_SKRB_SNAKESHOP_D_NOMONEY)
@Q_GOODSFULL(PC_ALL)
@GOODSIN_PLAYER(0,GDS_TOOL_SNAKE_BAG)
@SE(SE_se76_my_give)
@MONEYOUT(98)
@WINR_MONEY()
@SE(SE_se78_my_open_rock)
◆I’ll give you a discount as the sack has a hole in it.@KEY()↓
◆(Snake sack dealer marked the price down to 98 dollars from 290 dollars.)
@KEYNP()
;jpn:◆あなが あいてるから↓
;jpn: やすくしておいたよ。@KEY()↓
;jpn:◆(ヘビぶくろうりは↓
;jpn: 290ドルを↓
;jpn: 98ドルにしてくれた)
@KEYNP()
』

_SKRB_SNAKESHOP_D_NOMONEY;
◆Without any money, I cannot sell to you..
@KEYNP()
;jpn:◆かねがなくちゃあ↓
;jpn: かえねえな。@KEYNP()
』

_SKRB_SNAKESHOP_D_ITEMFULL;
◆Since you have too many items, I humbly keep this important @DSP_GOODS(GDS_TOOL_SNAKE_BAG).
@KEYNP()
;jpn:◆ガラクタばっかり↓
;jpn: かかえこんでるから@KEY()↓
;jpn:◆たいせつな へびぶくろが↓
;jpn: もてねえようだぜ。@KEYNP()
』



;@Habitat:スカラビ/フィールド/蛇屋
;@Person:へび屋(パンチョ)
;@Figure:へび屋のパンチョ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_PANCHO
MSG_SKRB_SNAKESHOP_PANCHO;
;◆ハイ レッドスネーク・カモン!↓
; キッス オブ ファイア。↓
; わきげのエサ‥‥はくしゅー!@KEY()
@GOSUB(MSG_SHOP_SKRB_SNAKE)
』

;@Habitat:スカラビ/フィールド/バザールの場
;@Person:バザールの男(ゴザールさん)
;@Figure:スカラビ男C
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_GOZAR
MSG_SKRB_GOZAR;
;◆めずらしいもの いろいろあるよ。↓
; あったら べんり↓
; なければ たいへん!@KEY()↓
;◆メニューみて きめなはれ。@KEY()
@GOSUB(MSG_SHOP_SKRB_BAZAR)
』

;@Habitat:スカラビ/フィールド/バザールの場
;@Person:バザールのヤジ馬A
;@Figure:スカラビ男A
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_BAZAR_A
MSG_SKRB_BAZAR_A;$β
◆I bought a ”@DSP_GOODS(GDS_TOOL_NOSE_PIG).”@KEY()↓
◆This will help out a large amount@KEY()↓
◆while I am humbly searching for the Magic truffle in the Deep Darkness.@KEY()↓
◆You too can learn how to use a @DSP_GOODS(GDS_TOOL_NOSE_PIG) with the ”Use” command under ”Goods.”@KEY()↓
◆So please rest easy.
@KEYNP()
;jpn:◆ぼく「ブタのはな」を↓
;jpn: かったんだよ。@KEY()↓
;jpn:◆まきょうに はえている↓
;jpn: マジックトリフを↓
;jpn: みつけるのには これはべんりさ。@KEY()↓
;jpn:◆「ブタのはな」の つかいかたは↓
;jpn: 「せつめい」で↓
;jpn: わかるらしいから@KEY()↓
;jpn:◆あんしんだね。@KEYNP()
;◆なんのことだか↓
; ぼく わかんないや。@KEYNP()
』
;◆ぼく「ぶたのはな」を↓
; かったんだよ。@KEY()↓
;◆マジックトリフを↓
; みつけるのには これはべんりさ。@KEYNP()
;』

;@Habitat:スカラビ/フィールド/バザールの場
;@Person:占師
;@Figure:ロープマジック男
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_FORTUNETELLER
MSG_SKRB_FORTUNETELLER;#
@CHKFGOTO(FLG_WIN_GIEGU,_SKRB_FORTUNETELLER_END)
◆Oh, you have the mark of bad luck on your face...@KEY()↓
◆No...Don’t worry...@KEY()↓
◆If you want to know, I’ll humbly tell you.@KEY()↓
◆”You shall come back here...@KEY()↓
◆After you have encountered a dangerous situation.”@KEY()↓
◆However, I may be wrong, and if so...a thousand pardons.
@KEYNP()
;jpn:◆おっ@WI(20) あんたのかおには↓
;jpn: ふきつな かげが‥‥@WI(60)↓
;jpn: いや‥‥き@WI(15) きにせんでもいい‥‥@KEY()↓
;jpn:◆どうしても ききたいなら いう。@WI(30)↓
;jpn: あんたは ひどいめにあって↓
;jpn: ここに もどってくる‥‥。@KEY()↓
;jpn:◆しかし そんなことは↓
;jpn: ぜーんぜん ないかも しれない。@KEYNP()
』
_SKRB_FORTUNETELLER_END;&
◆Oh!@KEY()↓
◆You have the mark of bad luck on your face...@KEY()↓
◆Yet, I could be wrong, as you didn’t wash your face lately.
@KEYNP()
;jpn:◆あらま!@WI(20) あんたのかおには↓
;jpn: ふけつなかげが‥‥@WI(60)↓
;jpn: たぶん よごれてるだけだろうが。@KEYNP()
』

;@Habitat:スカラビ/フィールド/街のなか
;@Person:いい夢情報の人
;@Figure:スカラビ女
;@AppearanceKey:FLG_PU/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_C
MSG_SKRB_C;
◆In the pyramid there’s hidden treasure.@KEY()↓
◆My husband was looking for it.@KEY()↓
◆Before he found it...he slipped on a banana peel.@KEY()↓
◆...So he gave up the search.
@KEYNP()
;jpn:◆ピラミッドのなかには↓
;jpn: まだ たからものが↓
;jpn: かくされているそうよ。@KEY()↓
;jpn:◆わたしの おっとは↓
;jpn: それをねらっていたんだけど↓
;jpn: こころざしなかばで‥‥@KEY()↓
;jpn:◆‥‥バナナのかわですべって@KEY()↓
;jpn:◆‥‥めげたの。@KEYNP()
』


;プーを仲間にしないでスカラビに来たときのみ出現。
;◆「グレート・サザーン・ホテル」に↓
; とまると いいゆめが↓
; みられるんですって。@KEY()↓
;◆わたしは じもとのにんげんだから↓
; なかなかチャンスがないのよ。@KEYNP()
;』

;@Habitat:スカラビ/フィールド/街のなか
;@Person:町の人A
;@Figure:スカラビ男C
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_A
MSG_SKRB_A;
◆The Tenda tribe used to live here.@KEY()↓
◆They went to the back of the Deep Darkness as they were too innocent.@KEY()↓
◆I wonder if they are still alive.
@KEYNP()
;jpn:◆むかし グミぞくって ひとびとが↓
;jpn: いたらしいんだけど↓
;jpn: あんまり ひとのいいやつらなんで@KEY()↓
;jpn:◆まきょうの おくへ↓
;jpn: おいやられちゃったんだよ。↓
;jpn: まだ いるんだろうかねぇ。@KEYNP()
』

;@Habitat:スカラビ/フィールド/街を出たところ
;@Person:町の人B
;@Figure:スカラビ男A
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_B
MSG_SKRB_B;
◆If you’re going to the Pyramid, prepare well,@KEY()↓
◆and be ready for whatever may occur.
@KEYNP()
;jpn:◆ピラミッドに いくんだったら↓
;jpn: かなり かくごして いきなよ。@KEYNP()
』

;@Habitat:スカラビ/フィールド/スフィンクス付近
;@Person:水売り
;@Figure:スカラビ男B
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_WATERSHOP
MSG_SKRB_WATERSHOP;
@GOSUB(MSG_SKRB_WATER)
』
;◆のどの かわいたたびびとに↓
; みずを うってあげましょう。↓
; たかいよ 100ドル。@KEY()
;』

;@Habitat:スカラビ/フィールド/ピラミッド出口
;@Person:幻の老人
;@Figure:幻の老人
;@AppearanceKey:FLG_PU_0/off
;@ActionScript:◆プレイヤーが接近したら竜巻から登場
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_OLDMAN
MSG_SKRB_OLDMAN;
;ピラミッドで「たかのめ」をとって帰ると、こんなふうな
;ものがいる。はなしかけると
;1500才くらいの老人があらわれる。
@OPEN(1)
◆Well done.@KEY()↓
◆You have made it!@KEY()
;jpn:◆よくぞ ここまで↓
;jpn: たどりついた!@KEY()
@CLOSEALL()
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@OPEN(1)
◆We finally meet, Prince @DSP_STS(STS_PC_NAME_POO).
@KEY()
;jpn:◆とうとう あえたのう。↓
;jpn: @DSP_STS(STS_PC_NAME_POO)おうじ。@KEY()
@CLOSEALL()
』
MSG_SKRB_OLDMAN_0;
@OPEN(1)
◆The stars foretold that I would meet you here...@KEY()↓
◆So, now it’s the time to show you the way of the Starstorm...@KEY()↓
;jpn:◆ほしのいちが↓
;jpn: おまえに であうことを↓
;jpn: つたえておったが‥‥やはり。@KEY()↓
;jpn:◆いまこそ↓
;jpn: 「ほしを おとす ほうほう」を↓
;jpn: でんじゅするとき。@KEY()↓
;@CHKFGOTO(FLG_POWR_PINK,_SKRB_OLDMAN_JEFF)
;◆しかしじゃ。そのまえに↓
; ランマのくにに@KEY()↓
;◆まだ ゆかねばならぬばしょが↓
; あろう? ピンクのくものうえ‥。@KEY()
;@CHKFGOTO(FLG_POWR_RAIN,_SKRB_OLDMAN_GO)
;◆@DSP_STS(STS_PC_NAME_JEFF)!↓
; あめのふる なぞのばしょを↓
; おぼえておろう?@KEY()↓
;◆そこに ゆくことが↓
; いま ひつようなのじゃ。@KEY()↓
;◆そこにゆき そしてもういちど↓
; ここに もどってくるのじゃ!↓
; カーーッツ!@KEY()
;@CLOSEALL()
;@WI(1)
;@WARP(WARP_SKRB_FORTUNETELLER)
;@ADD_PARTY(PC_POO)
;』
;_SKRB_OLDMAN_JEFF;
;@CHKFGOTO(FLG_POWR_RAIN,_SKRB_OLDMAN_OK)
;◆しかしじゃ。そのまえに@KEY()↓
;◆@DSP_STS(STS_PC_NAME_JEFF)!↓
; あめのふる なぞのばしょを↓
; おぼえておろう?@KEY()↓
;◆そこに ゆくことが↓
; いま ひつようなのじゃ。@KEY()
;◆そこにゆき そしてもういちど↓
; ここに もどってくるのじゃ!↓
; カーーッツ!@KEY()
;@CLOSEALL()
;@WI(1)
;@WARP(WARP_SKRB_FORTUNETELLER)
;@ADD_PARTY(PC_POO)
;』
;
;_SKRB_OLDMAN_OK;
◆For a while, you must live far away from your friends and live with me.@KEY()↓
◆Do you understand?@KEY()↓
◆...There’s only one answer.@KEY()↓
◆I must stop you here even if you don’t want to.@KEY()↓
◆Stay for a while, do you understand?!
;jpn:◆しばらくは なかまとはなれて↓
;jpn: わしと ともに↓
;jpn: くらさねばならぬが@KEY()↓
;jpn:◆よいな?@KEY()↓
;jpn:◆‥‥へんじは ひとつ。↓
;jpn: むりにでも ひきとめねばならぬ。↓
;jpn: しばし ここに とどまるのだ。@KEY()↓
;jpn:◆よいな!!
;ビカビカっとフラッシュ
@KEY()
@CLOSEALL()
@WI(30)
@GOTO(MSG_EVT_88_MABOROSHI_PU)

MSG_SKRB_OLDMAN_OK_1;
@OPEN(1)
◆It depends on @DSP_NAME(PC_POO)’s efforts.  That will determine the reuniting of the group.@KEY()↓
◆Be faithful, and wait until the time comes!
@KEYNP()
;◆Depending on @DSP_STS(STS_PC_NAME_POO)’s efforts,
;  you can go back to your friends.
;◆Believe yourself and wait until the time comes!
;@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)の どりょくしだいでは↓
;jpn: はやく おまえたちのもとに↓
;jpn: もどることが できる。@KEY()↓
;jpn:◆しんじて そのときを まて!@KEY()
@CLOSEALL()
』

;_SKRB_OLDMAN_GO;
;◆そこにゆき そしてもういちど↓
; ここに もどってくるのじゃ!↓
; カーーッツ!@KEY()
;@CLOSEALL()
;@WI(1)
;@WARP(WARP_SKRB_FORTUNETELLER)
;@ADD_PARTY(PC_POO)
;』


;@Habitat:スカラビ/フィールド/街のなか
;@Person:ロープの上の男ププカ
;@Figure:ロープマジック男
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_PUPUKA
MSG_SKRB_PUPUKA;
@CHKFGOTO(FLG_ITEM_KEY_PUPUKA,_SKRB_PUPUKA_AFTER)
◆I’m doing this as a hobby.@KEY()↓
◆Isn’t it cool?@KEY()↓
◆I recently made a friend.@KEY()↓
◆He used to be a Dungeon Maker.@KEY()↓
◆And now he’s a ”Dungeon Man.”@KEY()↓
◆Would you like to meet him?↓
<Yes>
<No>
;jpn:◆わたしは しゅみで↓
;jpn: こういうことを やっているんだ。↓
;jpn: カッコイイだろ。@KEY()↓
;jpn:◆さいきん ともだちができてね。↓
;jpn: ダンジョンづくりのしょくにんで↓
;jpn: とうとう‥‥フッフッフ@KEY()↓
;jpn:◆「ダンジョンおとこ」に↓
;jpn: なってしまったやつさ。@KEY()↓
;jpn:◆あってみたいかい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_PUPUKA_YES,_SKRB_PUPUKA_NO)

_SKRB_PUPUKA_NO;
◆I understand, he is a very strange fellow.
@KEYNP()
;jpn:◆そうかぁ‥‥↓
;jpn: かわりものだからなぁ あいつ。↓
;jpn: しょうがないな。@KEYNP()
』

_SKRB_PUPUKA_YES;
;@Q_GOODSFULL(PC_ALL)
;@FALSE_GOTO(_SKRB_PUPUKA_ITEMFULL)
◆All righty then, I’ll give you the key so that you can enter him.@KEY()↓
◆Oh no...I don’t have it!@KEY()↓
◆I must have lost it somewhere.@KEY()↓
◆I’m sorry, I don’t worry about small things.
@KEYNP()
;jpn:◆そうか。それじゃ↓
;jpn: かれのへやの カギをあげよう。↓
;jpn:◆あ‥‥@WI(15)ない!@WI(20)↓
;jpn: あらら どっかで↓
;jpn: おとしちゃったかな。@KEY()↓
;jpn:◆ごめん ごめん。↓
;jpn: ちいさいことには わたしは↓
;jpn: こだわらないんだよ。@KEYNP()
』

; よろしく つたえてくれ。@KEY()
;@SE(SE_se74_my_get)
;@GOODSIN(PC_ALL,GDS_TOOL_KEY_DUNGEONMAN)
;@SETF(FLG_ITEM_KEY_PUPUKA)
;』
;
;_SKRB_PUPUKA_ITEMFULL;
;◆こりゃこまった。↓
; あんたら にもつがおおすぎて↓
; カギがわたせんぞ。@KEYNP()
;』
;
_SKRB_PUPUKA_AFTER;
◆I stayed here the whole time you were gone.@KEY()↓
◆But now I don’t know why I did.@KEYNP()
;jpn:◆みえはって ずっと↓
;jpn: こんなところに いるけど‥‥@KEY()↓
;jpn:◆なんか むなしいなぁ。@KEYNP()
』
;◆わたしは しゅみで↓
; こういうことを やっているんだ。↓
; カッコイイだろ。@KEY()↓
;◆うーん@WI(30)↓
; ‥‥カッコイイ。@KEYNP()
;』


;@Habitat:スカラビ/フィールド/ピラミッド出口付近
;@Person:ヤリを持った男
;@Figure:ヤリ男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_YARIMAN
MSG_SKRB_YARIMAN;
@CHKFGOTO(FLG_ITEM_KEY_PUPUKA,_SKRB_YARIMAN_AFTER)
;ヤリ男
◆I am not sure if it was the ”Dungeon Man,” but...@KEY()↓
◆there is a strange looking tower to the northwest.@KEY()↓
◆...This key I picked up a little while ago shall maybe open the tower.@KEY()↓
◆You may have it, I do not need it.
;jpn:◆「ダンジョンおとこ」かどうかは↓
;jpn: しらねぇけど‥‥↓
;jpn: おかしなとうなら@KEY()↓
;jpn:◆ほくせいの ほうがくに↓
;jpn: たってるぜ。@KEY()↓
;jpn:◆‥‥もしかすると↓
;jpn: さっきひろったカギは@KEY()↓
;jpn:◆あのとうの いりぐちのカギ↓
;jpn: かもしれねぇな。@KEY()↓
;jpn:◆おれは いらんから↓
;jpn: おまえさんに やるよ。
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SKRB_YARIMAN_GOODSFULL)
@KEY()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_DUNGEONMAN)
@SAVE_GLOBAL_REG()
@GOSUB(MSG_SUB_GETGOODS_S)
@SETF(FLG_ITEM_KEY_PUPUKA)
@KEYNP()
@CLOSEALL()
;タカのめをプーが持ってったら電話
@CHKF(FLG_SKRB_PU_TAKANOME)@FALSE_GOTO(MSG_END)
@WI(60)
@GOSUB(MSG_GLOBAL_PHONE_TRACY_LOSTITEM)
』
_SKRB_YARIMAN_AFTER;グッズプレゼント後
◆I’m not sure if it was the ”Dungeon Man”...@KEY()↓
◆There’s a strange looking tower to the northwest.
@KEYNP()
;jpn:◆「ダンジョンおとこ」かどうかは↓
;jpn: しらねぇけど‥‥↓
;jpn: おかしなとうなら@KEY()↓
;jpn:◆ほくせいの ほうがくに↓
;jpn: たってるぜ。@KEYNP()
』

_SKRB_YARIMAN_GOODSFULL;
@KEY()↓
◆...But it seems that you have too many things.
@KEYNP()
;jpn:◆‥‥って いっても↓
;jpn: もちものが いっぱいか。@KEYNP()
』

;@Habitat:スカラビ/フィールド/砂漠南部
;@Person:ダンジョン男
;@Figure:ダンジョン男
;@AppearanceKey:FLG_SKRB_BRICKROAD_DISAPPEAR/off
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:0
MSG_SKRB_FIELD_DUNGEONMAN;
@CHKFGOTO(FLG_SKRB_DUNGEONMAN_OPEN,_SKRB_DMAN_2)
◆(Looks like you could enter, but it’s locked.)
@KEYNP()
;jpn:◆(なかに はいれるらしいが↓
;jpn: カギが かかっている)@KEYNP()
』

_SKRB_DMAN_2;チェックしたら即ワープ
;◆いりぐちがあります。↓
; なかに はいりますか?↓
;<はい>
;<いいえ>
;@DSP_ITEM(2)
;@SELGOTO(_DMAN_2_YES,_DMAN_2_NO)
;_DMAN_2_NO;
;◆なかにはいるのをやめました。
;@KEYNP()
;@!
;_DMAN_2_YES;
;◆なかにはいります。
;@KEYNP()
@CLOSEALL()
@WI(1)
@WARP(WARP_SKRB_DMAN_BODY)
@GOSUB(MSG_SAVE_MOUSE)
@!


MSG_SKRB_FIELD_DUNGEONMAN_RECEIVE;
@SAVE_REG()
@CHKFGOTO(FLG_SKRB_DUNGEONMAN_OPEN,_SKRB_DMAN_ALREADY)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_DUNGEONMAN)
@FALSE_GOTO(_SKRB_DMAN_KEY_NG)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_TUKATTA)
←
◆(The key worked to open the door.@KEY()↓
◆You may enter.)
@KEYNP()
;jpn:◆(カギがあいて↓
;jpn: なかにはいれるようになった)
@KEYNP()
@SETF(FLG_SKRB_DUNGEONMAN_OPEN)
@SE(SE_se77_my_open_locker)
@CLOSEALL()
@WARP(WARP_SKRB_DMAN_BODY)
@GOSUB(MSG_SAVE_MOUSE)
@!

_SKRB_DMAN_KEY_NG;
◆(The key doesn’t fit!)
;jpn:◆(カギが あわない!)
@KEYNP()
@!

_SKRB_DMAN_ALREADY;
◆(The door’s already opened.)
;jpn:◆(すでに とびらはあいている)
@KEYNP()
@!

;@Habitat:スカラビ/フィールド/最南部
;@Person:潜水艦情報の人
;@Figure:ヤリ男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_YARIMAN_2
MSG_SKRB_YARIMAN_2;
@CHKFGOTO(FLG_TLPT_MAKY,_SKRB_YARIMAN_2_LATER)
◆A scary place called Deep Darkness is on the other side of the river.@KEY()↓
◆The monsters are very strong and you can lose your health@KEY()↓
◆just by wandering in the swamp.@KEY()↓
◆Do you want to cross the river, even though you know it’s a stupid idea?@KEY()↓
<Yes>
<No>
;jpn:◆この かわの むこうは↓
;jpn: 「まきょう」とよばれる↓
;jpn: おそろしいところだ。@KEY()↓
;jpn:◆かいぶつは つよいし↓
;jpn: どくのぬまは あるくだけで↓
;jpn: たいりょくがへるぞ。@KEY()↓
;jpn:◆かわを わたりたいのか?↓
;jpn: ばかを しょうちで。↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_YARIMAN_2_YES,_SKRB_YARIMAN_2_NO)

_SKRB_YARIMAN_2_NO;
◆It was stupid of me to ask.@KEY()↓
◆Let’s together watch the sunset over Deep Darkness from here.
@KEYNP()
;jpn:◆きいてみた おれがばかだった。@KEY()↓
;jpn:◆いっしょに↓
;jpn: 「まきょう」にしずむ↓
;jpn: ゆうひでも みよう。@KEYNP()
』
_SKRB_YARIMAN_2_YES;#
◆The swamp is bottomless.@KEY()↓
◆Even if you’re swimming, you’ll be dragged in.@KEY()↓
◆It is a different story if you have a submarine.
@KEYNP()
;jpn:◆ぬまはそこなし。@WI(20)↓
;jpn: およいでいっても↓
;jpn: ひきずりこまれちまうぜ。@KEY()↓
;jpn:◆サブマリンでもあれば↓
;jpn: はなしはべつだが。@KEYNP()
@SETF(FLG_SKRB_YARIMAN)
@SETF(FLG_DSRT_KANBAN_44_MOVE);カンバン移動サブマリンコースオープン
』
_SKRB_YARIMAN_2_LATER;&
◆You returned from exploring the Deep Darkness?@KEY()↓
◆I cannot believe you made it back alive.
@KEYNP()
;jpn:◆あの おそろしい「まきょう」を↓
;jpn: たんけんしてきたんだってね。@KEY()↓
;jpn:◆いきてかえったなんて↓
;jpn: しんじられん。@KEYNP()
』

;▼▲▼▲▼▲▼▲ スカラビ ▼▲▼▲▼▲▼▲

;^^^^^^^^ダンジョン男内部:4階^^^^^^^^

;@Habitat:スカラビ/ダンジョン男内部/洞窟4F最北部
;@Person:ブリックの顔
;@Figure:ダンジョン職人の顔
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_SKRB_BRICKROAD
MSG_SKRB_BRICKROAD;
;ダンジョンの中のカクレ部屋にいる。入口はあいているが
;部屋はしまっているからカギがないとダメですよね。
@CHKFGOTO(FLG_TLPT_MAKY,_SKRB_BRICKROAD_MAIN)
@CHKFGOTO(FLG_SKRB_YARIMAN,_SKRB_BRICKROAD_MAKYO_2)
_SKRB_BRICKROAD_MAIN;
◆Welcome!
@KEY()
;jpn:◆ウーェルカム!@KEY()
@CLOSEALL()
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@OPEN(1)
@CHKFGOTO(FLG_TLPT_MAKY,MSG_SKRB_DUNGEONMAN_END)
◆Long time, no see.@KEY()↓
◆Mr. @DSP_NAME(PC_JEFF), we met in Winters a long time ago.@KEY()↓
◆I’m Brick Road.@KEY()↓
◆Dr. Andonuts finally made me Dungeon Man.@KEY()↓
◆If you want, I’ll come with you guys for a while.@KEY()↓
◆The ”Return Hole” is over there.
◆Jump in that hole and then walk out.
@KEYNP()
;jpn:◆ひさしぶりでやんす。@WI(20)↓
;jpn: @DSP_STS(STS_PC_NAME_JEFF)さん ずっとまえに↓
;jpn: ウィンターズで あいやした@KEY()↓
;jpn:◆ブリックロードで ござんす。@KEY()↓
;jpn:◆アンドーナッツはかせの おかげで↓
;jpn: ついに ダンジョンおとこに↓
;jpn: なれたんでやす。@KEY()↓
;jpn:◆あんたがたさえ よかったら↓
;jpn: しばらく いっしょに↓
;jpn: ついていきやす。@KEY()↓
;jpn:◆そこにある「おかえりあな」↓
;jpn: ‥‥という あなから↓
;jpn: したに おっこちて@KEY()↓
;jpn:◆そとにでて あるいてみて↓
;jpn: おくんなさい。@KEYNP()
;◆はいってきた とびらをでて↓
; あるいてみて おくんなさい。@KEYNP()
@SETF(FLG_BRICKROAD)
@SETF(FLG_SKRB_YARIMAN_B_APPEAR)
@SET_HIT_RECT(1,HRECT_SKRB_DM_HAMARI,MSG_EVT_90_DM_HAMARI)
@SETF(FLG_PHOTO_DUNGEONMAN);撮り頃フラグ
』
_SKRB_BRICKROAD_MAKYO_2;
◆There’s an old submarine at the back of the dungeon.@KEY()↓
◆It can be used to cross the river.@KEY()↓
◆There’s a ”Goodbye Exit”...over there.@KEY()↓
◆It will take you to the submarine.@KEY()↓
◆Don’t make a mistake on which exit you take.@KEY()↓
◆You need to take the ”Goodbye Exit!”@KEY()↓
◆Hope to see you again!
@KEYNP()
;jpn:◆このダンジョンの おくに↓
;jpn: くたびれたサブマリンが↓
;jpn: ありやす。@KEY()↓
;jpn:◆そいつで むこうぎしに↓
;jpn: わたってくだせえやし。@KEY()↓
;jpn:◆このおくにある「さらばあな」@KEY()↓;$追加
;jpn:◆‥‥という なまえのあなが↓
;jpn: サブマリンのばしょへ↓
;jpn: つうじているでやんす。@KEY()↓
;jpn:◆くれぐれも おちるあなを↓
;jpn: まちがえないでおくんなさい。@WI(20)↓
;jpn: 「さらばあな」でやんすよ。@KEY()↓
;jpn:◆えんが あったら↓
;jpn: また あいやしょう!@KEYNP()
』
MSG_SKRB_DUNGEONMAN_END;&動けなくなったままのダンジョン男
◆I don’t know how, but my homemade dungeon helped you out.@KEY()↓
◆I’m glad.
@KEYNP()
;jpn:◆どんなふうにか しらないけれど@WI(20)↓
;jpn: わしの てづくりダンジョンが↓
;jpn: やくにたって うれしいでやんす。@KEYNP()
@CLOSEALL()
』
;-------------------------------------------------


;@Habitat:スカラビ/ダンジョン男内部/洞窟4F南東
;@Person:看板44
;@Figure:立札
;@AppearanceKey:FLG_SKRB_YARIMAN/off
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_SKRB_BRICKROAD
MSG_BRICK_SIGN_44;
;2回目の帰路(潜水艦の場所へ)
;1回目クリア前は看板で通路を封じ、クリア後は看板を消す
@CHKFGOTO(FLG_TLPT_MAKY,_BRICK_SIGN_44_LATER)
◆”Goodbye Exit”@KEY()↓
◆Some day, you should enter with courage.@KEY()↓
◆...Brick Road.
@KEYNP()
;jpn:◆「さらばあな」↓
;jpn: いずれ ゆうきをだして↓
;jpn: とびこむべし。‥ブリック・ロード@KEYNP()
』
_BRICK_SIGN_44_LATER;後に
◆This path is closed.@KEY()↓
◆...Brick Road.
@KEYNP()
;jpn:◆こちらの コースはへいさした。↓
↓
;jpn:        ‥ブリック・ロード@KEYNP()
』


;回復ベンチ
MSG_SKRB_DMAN_BENCH_1A;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_2)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

MSG_SKRB_DMAN_BENCH_1B;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_1)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

MSG_SKRB_DMAN_BENCH_2;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_3)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

MSG_SKRB_DMAN_BENCH_3;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_4)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!
_DMAN_BENCH_MES;
◆”Good Night Bench.”@KEY()↓
◆May you relax and recover your health and spirits.
@KEYNP()
;jpn:◆「おやすみベンチ」↓
;jpn: つかれが すっかりとれ@KEY()↓
;jpn:◆きりょく たいりょくが↓
;jpn: かいふくします。
@KEYNP()
@!

_DMAN_BENCH_MES_2;
;@COLD_PLAYER(PC_ALL)
@OPEN(1)
◆@GOSUB(MSG_ESUB_DSP_PARTY)’s health is restored.
;jpn:◆@DSP_LCNAME()は↓
;jpn: すっかり げんきになった。
@KEYNP()
@CLOSEALL()
;@FRESH_PLAYER(PC_ALL)
@!


;^^^^^^^^ダンジョン男内部:1階^^^^^^^^

;@Habitat:スカラビ/ダンジョン男内部/洞窟中2階最北部
;@Person:壊れたサブマリン
;@Figure:潜水艦
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_SKRB_BRICK_SUBMARINE
MSG_SKRB_BRICK_SUBMARINE;
;潜水艦をチェックしたときのメッセージ
@SET_LOOPREG(PC_JEFF)			;ジェフのIDを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SKRB_BRICK_SUBMARINE_DEAD)
◆(@DSP_NAME(PC_JEFF) checked the broken submarine.)@KEY()↓
◆Yes!@KEY()↓
◆It can still work.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_JEFF)は↓
;jpn: こわれたサブマリンを↓
;jpn: チェックした。@KEY()↓
;jpn:◆よし!↓
;jpn: これは まだうごくぞ。@KEY()
@CLOSEALL()
@GOTO(MSG_EVT_92_SUBMARINE)

_SKRB_BRICK_SUBMARINE_DEAD;
◆(No one can repair the submarine except @DSP_NAME(PC_JEFF).)
@KEYNP()
;jpn:◆(@DSP_STS(STS_PC_NAME_JEFF) いがいのものには↓
;jpn: サブマリンの↓
;jpn: しゅうりは できない)@KEYNP()
』
;------------------------------------------------------------------

;この後増補

MSG_SKRB_INFO_POKEY;
◆Oh, be careful where you walk.@KEY()↓
◆It’s filthy.@KEY()↓
◆A chubby kid did his business out here somewhere...
@KEYNP()
;jpn:◆あ そのへんあるくと↓
;jpn: バッチイよ。@KEY()↓
;jpn:◆がいこくから きたとかいう↓
;jpn: ふとった ガキが↓
;jpn: ノグソしてったから。@KEYNP()
』
MSG_SKRB_UNKO_POKEY;チェックすると
◆(Pokey’s stink still hangs in the air...)
@KEYNP()
;jpn:◆(ポーキーがいた↓
;jpn: なごりがある‥‥)@KEYNP()
』

MSG_SKRB_INFO_HIERO;
◆You need to be able to read hieroglyphs to solve the mystery of the Pyramid.@KEY()↓
◆...I couldn’t solve it, although I read it.@KEY()↓
◆Didn’t you read the hieroglyphs at the museum in Summers?@KEY()↓
<Yes>
<No>
;jpn:◆ヒエログリフをよんで↓
;jpn: りかいしないと↓
;jpn: ピラミッドのなぞは とけない。@KEYNP()
;jpn:◆‥‥おれは よんでも↓
;jpn: とけなかったんだけど@KEY()↓
;jpn:◆きみ@GOSUB(MSG_SUB_TATI)↓
;jpn: サマーズのはくぶつかんで↓
;jpn: よんできたんだろ?@KEY()↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_INFO_HIERO_YES,_SKRB_INFO_HIERO_NO)
_SKRB_INFO_HIERO_NO;
◆Well, that means that you must go back, read it and then come back here.
@KEYNP()
;jpn:◆そりゃあ サマーズに↓
;jpn: ひきかえしてでも↓
;jpn: しっかり よんでこなきゃ。@KEYNP()
』
_SKRB_INFO_HIERO_YES;
◆Then, you should be able to solve the mystery someday.
@KEYNP()
;jpn:◆じゃあ いずれ↓
;jpn: なぞは とけるだろうよ。@KEYNP()
』
;-------------------------------------------------

MSG_SKRB_CHECK_SHOP;スカラビショップのカンバン
◆Hassan’s Shop@KEY()↓
◆($ dollars acceptable.)
@KEYNP()
;jpn:◆ハッサンさんの みせ↓
;jpn: ($ドルも つかえるよ)@KEYNP()
』
;-------------------------------------------------

MSG_BRICK_SIGN_FACE;
◆That face is mine.@KEY()↓
◆(Feel free to talk to it.)@KEY()↓
◆...Brick Road.
@KEYNP()
;jpn:◆そこのかおは わたしのである。↓
;jpn: (きがるに はなしかけてみよう)↓
;jpn:        ‥ブリック・ロード@KEYNP()
』
;-------------------------------------------------
