;----------------------------------

;@Habitat:地底大陸／ファイアースプリングス／1大広間
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_FIRE_BOSS/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DKFD_FIRE_BOSS
MSG_DKFD_FIRE_BOSS;marcus
@CHKFGOTO(FLG_WIN_FIRE_BOSS,MSG_SYS_HANASU_NG)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆You finally got here.@KEY()↓
◆This is the eighth ”Your Sanctuary” location.@WI(20)  But it’s mine now.@KEY()↓
◆Take it from me,@WI(30) if you dare...
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは ８ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし いまは↓
;jpn: わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_FIRE_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_CHKA_FIRE_1_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_FIRE_BOSS)
』

;-----------------------------------

;@Habitat:最低国／フィールド／どこか
;@Person:さらわれた土星さん
;@Figure:土星さん
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DKFD_DOSEI
MSG_DKFD_DOSEI;marcus
@FONTBAKA()
;◆あっち スペーストンネルの↓
; ぬすまれた が こわれて ある。@KEYNP()
◆Kidnapped.  I was.  Boing!@KEY()↓
◆Kidnapper.  Bad guy.@KEY()↓
◆Bad guy gone.  Zoom!@KEY()↓
◆Where?↓
  To the past.@KEY()↓
◆Ding, ding!

;jpn:◆さらわれたよ↓
;jpn: ぼく。@KEY()↓
;jpn:◆さらったよ↓
;jpn: わるいやつ。@KEY()↓
;jpn:◆いっちゃったよ↓
;jpn: わるいやつ。@KEY()↓
;jpn:◆どこへ?@WI(30)↓
;jpn: むかしへ。@KEY()↓
;jpn:◆ぷー。
@KEYNP()
@FONTSTD()
』

;@Habitat:最低国／フィールド／どこか
;@Person:壊れたスペーストンネル
;@Figure:壊れたスカイウォーカー
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_DKFD_SKYWALKER
;@Message:0
MSG_DKFD_SKYWALKER;marcus@MiuraAdapted
@CHKFGOTO(FLG_BOX_DKFD_1,MSG_BOX_EMPTY)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0) checked the broken Phase Distorter.@KEY()↓
◆There was a @DSP_GOODS(GDS_TOOL_LIFE_HORN).@KEY()↓
;jpn:◆@DSP_NAME(0)は↓
;jpn: こわれた スペーストンネルを↓
;jpn: しらべた。@KEY()↓
;jpn:◆いのちのつのぶえが あった。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(MSG_BOX_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_LIFE_HORN)
@GOSUB(MSG_SUB_GETGOODS)
@SETF(FLG_BOX_DKFD_1)
@KEYNP()
』

;@Habitat:最低国／フィールド／どこか
;@Person:幻の老人
;@Figure:幻の老人
;@AppearanceKey:0
;@ActionScript:◆竜巻から出現
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_DKFD_OLDMAN
MSG_DKFD_OLDMAN;@MiuraAppended
;PKスターストームΩを教える老人
;----------
@SE(SE_se63_teleport_appear)
;----------
@MOVE_GOM_CHAR(GOM_MABOROSHI,ANIM_SAITEI_MABOROSHI_IN,OBJFX_SHOW_NONE);幻登場
@WAITSYS()
@HIDE_GOM_CHAR(GOM_MABOROSHI,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_MAGICANTO_OLDMAN,ANIM_MAPOBJSTILL,OBJFX_SHOW_NONE);老人登場
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_LEFT)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_UP)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_RIGHT)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_DOWN)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_LEFT)
@WI(1)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_UP)
@WI(2)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_RIGHT)
@WI(3)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_DOWN)
@WI(4)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_LEFT)
@WI(5)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_UP)
@WI(6)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_RIGHT)
@WI(7)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_DOWN)
@WI(8)
@SET_GOM_CHAR_DIR(GOM_MAGICANTO_OLDMAN,DIR_M_LEFT)
@OPEN(1)
◆Greetings!@WI(20)  So, you are finally here!
;jpn:◆よーくぞ ここまで↓
;jpn: たどりつかれた!
@KEY()
@CLOSEALL()
@GOSUB(MSG_SUB_ALLHEAL_POWR)    ;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@OPEN(1)
◆Excellent!  You are truly excellent!@KEY()↓
◆There is only a little time left!@WI(15)  I’ll give you the last power.@KEY()↓
◆I must go now...@KEY()
;jpn:◆りっぱ りっぱ!↓
;jpn: ごりっぱな しょうねんたち!@KEY()↓
;jpn:◆のこされた ときは↓
;jpn: わずか!@KEY()↓
;jpn:◆さいごの ちからを↓
;jpn: さずけましょう!@KEY()↓
;jpn:◆では わたしは↓
;jpn: いそいでいるので‥‥@KEY()
@CLOSEALL()
@ADD_PSI(PC_POO,3)
@HIDE_GOM_CHAR(GOM_MAGICANTO_OLDMAN,OBJFX_HIDE_NONE)
;----------
@SE(SE_se63_teleport_appear)
;----------
@MOVE_GOM_CHAR(GOM_MABOROSHI,ANIM_SAITEI_MABOROSHI_OUT,OBJFX_SHOW_NONE)
@WAITSYS()
@ADD_PSI(PC_POO,3)
@OPEN(1)
◆(@DSP_STS(STS_PC_NAME_POO) became conscious of PSI Starstorm Ω!)
;jpn:◆(@DSP_STS(STS_PC_NAME_POO)は↓;
;jpn: PKスターストームΩを↓
;jpn: みにつけた!)
@SE(SE_se67_elevator_stop)
@KEYNP()
@CLOSEALL()
』
;-------------------------------------------------

;この後増補

;地底大陸のグミ族
MSG_DKFD_GUMI_A;グミドリアンを持っていたら寄ってくる人
@CHKFGOTO(FLG_INFO_POWR,_DKFD_GUMI_A_END)
;@CHKFGOTO(FLG_DKFD_GUMI_BOSS,_DKFD_GUMI_A_AFTER)
;◆おまえら けっこう すっげえ↓
; いいにおいするじゃん!@WI(15)クンクン@KEY()↓
;◆あっ オレ? おれもグミぞくよ。@KEYNP()
;』
;_DKFD_GUMI_A_AFTER;marcus＃
◆Even though I listened to the talkative Mystery Rock’s story,@KEY()↓
◆I don’t understand what he’s talking about.
;jpn:◆しんぴのいわの はなしを↓
;jpn: きいても オレには↓
;jpn: なにいってるのか@KEY()↓
;jpn:◆じぇーんじぇん↓
;jpn: わかりましぇーん。
@KEYNP()
』
_DKFD_GUMI_A_END;marcus＆
◆The rock suddenly stopped talking.@KEY()↓
◆In other words...@KEY()↓
◆it’s not saying anything.
;jpn:◆いつのまにやら いわが↓
;jpn: しゃべらなくなった。@KEY()↓
;jpn:◆つまり なにも‥‥@KEY()↓
;jpn:◆いわない。
@KEYNP()
』

MSG_DKFD_GUMI_A_RECEIVE;marcusこの人物の前でグミドリアンを使うと
;みんな集まれー
◆...You have a nice item.@KEY()↓
◆Since I came to the Lost Underworld, I haven’t seen or smelled @DSP_GOODS(GDS_TOOL_KEY_GUMIDORIAN).
;＠地名確認
;jpn:◆‥‥いいもん もってるなぁ。↓
;jpn: したの せかいに おちてきてから@KEY()↓
;jpn:◆グミドリアンなんて↓
;jpn: おめに かかれなかったもんなぁ
@KEYNP()
』

MSG_DKFD_GUMI_BOSS;marcus
@CHKFGOTO(FLG_INFO_POWR,_DKFD_GUMI_BOSS_END)
@CHKFGOTO(FLG_DKFD_GUMI_BOSS,_DKFD_GUMI_BOSS_AFTER)
◆What are you doing in the dinosaur’s cage?@KEY()↓
◆I’ll open the door for you, and you get out of the cage quick.@KEY()↓
◆That’s an order from the boss.@WI(15)  ...By the way, thanks for the @DSP_GOODS(GDS_TOOL_KEY_GUMIDORIAN).
;jpn:◆きょうりゅうの オリのなかで↓
;jpn: なにやってるんだ?!@KEY()↓
;jpn:◆いりぐちを あけてやるから↓
;jpn: はやく こっちに でてこい。@KEY()↓
;jpn:◆ボスの オレが ゆるすから。@WI(30)↓
;jpn: ‥‥グミドリアン ありがとよ。
@KEY()↓
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆(@DSP_NAME(0)’s @DSP_GOODS(GDS_TOOL_KEY_GUMIDORIAN) was taken.)@KEY()↓
◆(That nasty smell left you at the same time!)
;jpn:◆(@DSP_NAME(0)は↓
;jpn: 「グミドリアン」を↓
;jpn: とられてしまった)@KEY()↓
;jpn:◆(もう くさく なくなった)
@KEYNP()
;門開く(恐竜が入れない大きさなら空きっぱなし)
@SETF(FLG_DKFD_GUMI_BOSS)
』
_DKFD_GUMI_BOSS_AFTER;marcus＃ボスのセリフその後
◆Why don’t you see the talkative mystery rock.@KEY()↓
◆That rock really jabbers away!!

;jpn:◆しんぴのいわを おがんでいけよ。↓
;jpn: いわもまた よくしゃべるぜ。
@KEYNP()
』
_DKFD_GUMI_BOSS_END;marcus＆
◆A rock that doesn’t talk is no fun at all.

;jpn:◆しゃべらないいわって‥‥@WI(30)↓
;jpn: おもしろくもなんともないな。
@KEYNP()
』


;その他
MSG_DKFD_GUMI_C;marcus＃
@CHKFGOTO(FLG_WIN_GIEGU,_DKFD_GUMI_C_END)
◆We are the same Tenda as those above ground.@KEY()↓
◆...We seem different?@KEY()↓
◆Yeah,@WI(15) you know, the Tenda up there are shy and don’t like to talk.

;jpn:◆オレたちは うえのやつらと↓
;jpn: おんなじ グミぞくなんだ。@KEY()↓
;jpn:◆‥‥ちがうって?@KEY()↓
;jpn:◆だからぁ うえのやつらは↓
;jpn: むくちなんだよ。
@KEYNP()
』
_DKFD_GUMI_C_END;marcus＆
◆It may be my imagination, but I think I hear the sound of other Tenda talking up above.@KEY()↓
◆I wonder...have they overcome their shyness?
;jpn:◆きのせいか うえのほうから↓
;jpn: はなしごえが きこえるときが↓
;jpn: あるんだ。@KEY()↓
;jpn:◆あいつら‥‥@WI(30)↓
;jpn: もしかしたら おしゃべりに↓
;jpn: なったのかなぁ。
@KEYNP()
』

MSG_DKFD_GUMI_D;marcus＃
@CHKFGOTO(FLG_WIN_GIEGU,_DKFD_GUMI_D_END)
◆Didn’t you think that the Tenda up above have some particularly beautiful women?@KEY()↓
◆They’re still shy, though.
;jpn:◆うえのグミぞくにゃ↓
;jpn: びじんが おおかっただろ?@KEY()↓
;jpn: ‥‥むくち だけどな。
@KEYNP()
』
_DKFD_GUMI_D_END;marcus＆
◆Tenda women up above ground are pretty, but the men seem kind of run down.
 ;jpn:◆うえのグミぞくにゃ↓
;jpn: たしかに びじんがおおいけど@WI(20)↓
;jpn: おとこは さえないよな。
@KEYNP()
』

MSG_DKFD_GUMI_E;marcus
@CHKFGOTO(FLG_DKFD_GUMI_E_READED,_DKFD_GUMI_E_B)
@SETF(FLG_DKFD_GUMI_E_READED)
;◆きょうりゅうの オリのなかに↓
; おんせんが ふきでるんだ。@KEY()↓
;◆じしんの たびに↓
; ドピューン! とな。@KEY()↓
;◆あおい おんせんは↓
; たいりょくかいふくに きく。@KEY()↓
;◆あかい おんせんは↓
; しびれやら どくやらを↓
; とってくれるんだ。@KEYNP()
;
◆You’re strange, but you smell good.  So I’ll tell you a secret.@KEY()↓
◆Did you feel the earthquake a little while ago?@KEY()↓
◆...You know, we have earthquakes all the time here.@KEY()↓
◆After an earthquake, the hot springs will erupt.@KEY()↓
◆The blue springs are great for recovering health.@KEY()↓
◆The Red springs are perfect for healing paralysis or drawing out poison.
;jpn:◆おまえ へんなやつだけど↓
;jpn: なんか いいにおいだから↓
;jpn: いいこと おしえてやる。@KEY()↓
;jpn:◆さっき じしん あったろ?↓
;jpn: @WI(30)‥‥っていうか ここでは↓
;jpn: じしんは しょっちゅうある。@KEY()↓
;jpn:◆じしんのあと じめんのあなから↓
;jpn: おんせんが ふきでるんだ。@KEY()↓
;jpn:◆あおい おんせんは↓
;jpn: たいりょくかいふくに きく。@KEY()↓
;jpn:◆あかい おんせんは↓
;jpn: しびれやら どくやらを↓
;jpn: とってくれるみたいよ。
@KEYNP()
』

_DKFD_GUMI_E_B;marcus
◆Hey! Strange fellow.@KEY()↓
◆After an earthquake, the hot springs erupt out of the ground.@KEY()↓
◆Have you ever noticed that?@KEY()↓
◆The blue springs are great for recovering health.@KEY()↓
◆The red springs are perfect for healing paralysis or drawing out poison.
;jpn:◆やあ! へんなやつ。@KEY()↓
;jpn:◆じしんのあと じめんのあなから↓
;jpn: おんせんが ふきでるんだけど@KEY()↓
;jpn:◆もう みたことあるかな。@KEY()↓
;jpn:◆あおい おんせんは↓
;jpn: たいりょくかいふくに きく。@KEY()↓
;jpn:◆あかい おんせんは↓
;jpn: しびれやら どくやらを↓
;jpn: とってくれるみたいよ。
@KEYNP()
』


MSG_DKFD_GUMI_F;marcus＃
@CHKFGOTO(FLG_WIN_GIEGU,_DKFD_GUMI_F_END)
◆Tenda who like to talk came to the Lost Underworld@KEY()↓
◆because we couldn’t stand the quiet up above.@KEY()↓
◆So, we established a separate tribe.@KEY()↓
◆I hope we can be friendly again some day.@KEY()↓
◆...Yeah, it was a lot easier to live up above.

;jpn:◆わしら おしゃべりな グミぞくは↓
;jpn: うえの やつらの むくちに↓
;jpn: たえられなくて したにおりてきて@KEY()↓
;jpn:◆べつのくにを つくってしまったが↓
;jpn: いずれは なかよく↓
;jpn: なりたいもんだ。@KEY()↓
;jpn:◆‥‥うえの ほうが↓
;jpn: すみやすかったよ。
@KEYNP()
』
_DKFD_GUMI_F_END;marcus＆
◆You guys helped the upper tribe and the lower tribe gain unity again.@KEY()↓
◆Soon, we’ll be one village again!  Thank you.
;jpn:◆きみたちの おかげで↓
;jpn: ちかいうちに↓
;jpn: うえのむらと したのむらが@KEY()↓
;jpn:◆ひとつのむらに↓
;jpn: まとまりそうじゃ。@WI(30)↓
;jpn: ありがとう。
@KEYNP()
』

MSG_DKFD_GUMI_G;
◆We made a cage for dinosaurs and locked them up...@KEY()↓
◆That’s what my brother tells me.@KEY()↓
◆But I don’t believe it...  He’s just spewing out of his cake hole.
;jpn:◆きょうりゅうの オリをつくって↓
;jpn: とじこめた‥‥@WI(15)と↓
;jpn: アニキはいうけど@KEY()↓
;jpn:◆それって つよがりだと↓
;jpn: おもうなぁ。
@KEYNP()
』

MSG_DKFD_GUMI_H;＃間欠泉で遊ぶコドモ
@CHKFGOTO(FLG_WIN_GIEGU,_DKFD_GUMI_H_END)
◆A chubby, obnoxious kid from some foreign country said something heartrending...@KEY()↓
◆So, I’m healing my wounds in the hot springs.
;jpn:◆どっかの クニからきた↓
;jpn: いけすかないデブに@KEY()↓
;jpn:◆こころが はりさけそうなこと↓
;jpn: いわれちゃって‥‥@KEY()↓
;jpn:◆おんせんで そのキズを↓
;jpn: いやしてるんだ。
@KEYNP()
』
_DKFD_GUMI_H_END;marcus＆
◆Hot springs rock!
;jpn:◆おんせんって いいよなぁ。
@KEYNP()
』

MSG_DKFD_GUMI_I;
@GOSUB(MSG_SUB_DKFD_EGO)
@!
;キャッシュディスペンサー機能のグミ
;外国留学経験者?
;ディ・スペンサー氏とは別人
;◆がいこくの かたですね?@KEY()↓
;◆ボクは あるけいざいたいこくに↓
; りゅうがく けいけんのある↓
; はなしのわかる グミです。@KEY()↓
;◆なまえは エーゴ・ステッキです。@KEY()↓
;◆おやくにたてることが あったら↓
; いつでも いってください。@KEY()↓
;_DKFD_GUMI_I_MAIN;１
;◆おかねを↓
; ごようだて しましょうか?@KEY()↓
;＜＞＜＞
;◆わたしは↓
; きをわるくしたりなんかしません。@WI(20)↓
; また いつでも どうぞ。@KEYNP()
;』
;◆あつかいきんがくと どうがくの↓
; てすうりょうを いただきますが↓
; よろしいですね?@KEY()↓
;;＜＞＜＞
;◆まだ ほんとうに このせかいで↓
; こまっては いないようですね。@KEYNP()
;』
;◆＜アズケル＞＜ヒキダス＞
;
;◆おたがいに とてもいい↓
; チャンスでしたね。@WI(20)↓
; また よろしく おねがいします。@KEYNP()
;』
;◆ハーイ! エーゴです。@KEY()↓
;１に続く

;MSG_DKFD_GUMI_J;物売り地底グミ
;◆ともだちの エーゴに↓
; たのまれて↓
; おみせやさんゴッコをしてるだよ。@KEY()↓
;◆いらっしゃいませ。@KEY()↓


;以下ショップ
;◆あんたから もらった↓
; えはがき みてぇなもの↓
; (おさつのことらしい)は↓
;◆エーゴに わたしとくだよ。@KEY()↓
;◆じゃーな。@WI(20)↓
; また あそぼうぜ。@KEYNP()
;』

;お金が足りないと
;◆えはがきみてぇなの↓
;(おさつのことらしい)が↓
; たりねぇと↓
;◆エーゴに おこられちまうだよ。@KEYNP()
;』
;◆にもつが いっぺぇで↓
; わたせねぇだよ。@KEYNP()
;』

MSG_DKFD_GUMI_K;避難所Aのグミ
;電話鳥について?
◆The bird right there says strange words like ”Hello?” and ”click beep beep beep.”
;jpn:◆そこにいるトリは↓
;jpn: 「もしもし」とか↓
;jpn: 「ガチャン ツーツーツー」とか@KEY()↓
;jpn:◆へんなことを いうのだ。
@KEYNP()
』

MSG_DKFD_GUMI_L;＃避難所Bのグミ
@CHKFGOTO(FLG_WIN_GIEGU,_DKFD_GUMI_L_END)
◆Here, the dinosaurs don’t come and attack me.  So, I can relax.@KEY()↓
◆...Except now I can’t get out.
;jpn:◆ここにいると きょうりゅうが↓
;jpn: おそってこられなくて↓
;jpn: あんしんなんだけど@KEY()↓
;jpn:◆‥‥でられなく↓
;jpn: なっちゃったんだよぉ。
@KEYNP()
』
_DKFD_GUMI_L_END;marcus＆
◆Without dinosaurs, this place seems like it is missing something big.
;jpn:◆きょうりゅうがいないと↓
;jpn: ここのけしきって↓
;jpn: なんか さみしいな。
@KEYNP()
』

MSG_DKFD_BIRD_PHONE;marcus仮設定
;電話鳥のあいさつ
◆Ring, ring, rrriiing!!
;DAN:This is sound of telephone ringing but the bird is saying instead of real telephone.  The bird is like a phone bird.
;jpn:◆チュルッ チュルッチュ ルー
@KEY()↓
@GOSUB(MSG_TEL)
』
;◆ああ おもいだすぜ↓;
; グミドリアンの あの↓
; あじ‥‥かおり!@KEY()↓
;◆きょうりゅうの オリの↓
; (洞窟の方角)のほうに↓
; どうくつが あいてて@KEY()↓
;◆ほのかに グミドリアンの↓
; かおりがしたが あんがい↓
; あんなところに あったのかなぁ。@KEYNP()
;』

;グミの扉で「グミドリアン」をつかう。

MSG_DKFD_GUMI_DOOR_RECEIVE;
;@GOSUB(MSG_SUB_GOODS_PRE)
;@EQ(GDS_TOOL_KEY_GUMIDORIAN)
;@FALSE_GOTO(_GUMI_DOOR_RECEIVE_NG)
;@LOAD_REG()
;@GOSUB(MSG_SUB_GOODS_TUKATTA)
;@SE(SE_se76_my_give)
;@LOAD_GLOBAL_REG()
;@GOODSOUT_PLAYER(0,0)
;←
;◆(グミぞくは とびらを↓
; あけてくれた)
;@KEYNP()
;@SE(SE_se4a_foe_explosion)
;@HIDE_CHAR(PRSN_CHKA_FIELD_3B,OBJFX_HIDE_HSTRIPE)
;@SETF(FLG_DKFD_DOOR_DISAPPEAR)
;@!
;_GUMI_DOOR_RECEIVE_NG;
;◆(そういうものでは↓
; グミぞくは よろこばない)
;@KEYNP()
@!

;---------------------------------

MSG_READ_DKFD_GUMI_1;marcus看板
◆(Don’t feed the dinosaurs in the cage!↓
  The Boss)

;jpn:◆(オリのなかの きょうりゅうに↓
;jpn: エサを やるな!↓
;jpn:             ボス )
@KEYNP()
』

MSG_READ_DKFD_GUMI_2;
◆(Don’t talk to the rock if you have nothing to say.@WI(20)  The Boss)
;jpn:◆(ようも ないのに↓
;jpn: いわに はなしかけるな!↓
;jpn:             ボス )
@KEYNP()
』

MSG_READ_DKFD_GUMI_3;
◆(In case of danger, evacuate here!↓
  The Boss)

;jpn:◆(あぶないときには ここに↓
;jpn: ひなんしよう!↓
;jpn:             ボス )
@KEYNP()
』

;----------------------------------------------
