;---------------------------------------

;@Habitat:マジカント／ショップ／ショップ
;@Person:マジb道具屋
;@Figure:マジカントの人
;@AppearanceKey:0
;@ActionScript:◆正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_B
MSG_MGKT_B;
@GOSUB(MSG_SHOP_MGKT_FREE)
』

;----------------------------------------
;@Habitat:マジカント／フライングマンの家／フライングマンの家
;@Person:フライングマン１
;@Figure:フライングマン
;@AppearanceKey:FLG_FLYINGMAN_1/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_FLYINGMAN_1
MSG_MGKT_FLYINGMAN_1;
@GOSUB(_SUB_Q_FLYINGMAN)
@TRUE_GOTO(MSG_MGKT_FLYINGMAN_ALREADY)
@GOSUB(MSG_SUB_FLYINGMAN_ADD)
@GOSUB(MSG_ADD_FLYINGMAN1)
@SETF(FLG_BGM_FLYINGMAN)
@SETF(FLG_FLYINGMAN_1)
@!

MSG_MGKT_FLYINGMAN_2;
@GOSUB(_SUB_Q_FLYINGMAN)
@TRUE_GOTO(MSG_MGKT_FLYINGMAN_ALREADY)
@GOSUB(MSG_SUB_FLYINGMAN_ADD)
@GOSUB(MSG_ADD_FLYINGMAN2)
@SETF(FLG_BGM_FLYINGMAN)
@SETF(FLG_FLYINGMAN_2)
@!

MSG_MGKT_FLYINGMAN_3;
@GOSUB(_SUB_Q_FLYINGMAN)
@TRUE_GOTO(MSG_MGKT_FLYINGMAN_ALREADY)
@GOSUB(MSG_SUB_FLYINGMAN_ADD)
@GOSUB(MSG_ADD_FLYINGMAN3)
@SETF(FLG_BGM_FLYINGMAN)
@SETF(FLG_FLYINGMAN_3)
@!

MSG_MGKT_FLYINGMAN_4;
@GOSUB(_SUB_Q_FLYINGMAN)
@TRUE_GOTO(MSG_MGKT_FLYINGMAN_ALREADY)
@GOSUB(MSG_SUB_FLYINGMAN_ADD)
@GOSUB(MSG_ADD_FLYINGMAN4)
@SETF(FLG_BGM_FLYINGMAN)
@SETF(FLG_FLYINGMAN_4)
@!

MSG_MGKT_FLYINGMAN_5;
@GOSUB(_SUB_Q_FLYINGMAN)
@TRUE_GOTO(MSG_MGKT_FLYINGMAN_ALREADY)
@GOSUB(MSG_SUB_FLYINGMAN_ADD)
@GOSUB(MSG_ADD_FLYINGMAN5)
@SETF(FLG_BGM_FLYINGMAN)
@SETF(FLG_FLYINGMAN_5)
@!

MSG_SUB_FLYINGMAN_ADD;
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_D,_MGKT_FLYINGMAN_5)
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_C,_MGKT_FLYINGMAN_4)
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_B,_MGKT_FLYINGMAN_3)
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_A,_MGKT_FLYINGMAN_2)
◆I am your courage.@KEY()↓
◆I follow you here in Magicant.@KEY()↓
◆...My name?@KEY()↓
◆Let’s say Flying Man.
@KEY()
;jpn:◆わたしは あなたの ゆうき。@WI(20)↓
;jpn: あなたについて ゆきます。@WI(30)↓
;jpn: ‥‥‥なまえ?@KEY()↓
;jpn:◆フライングマンとでも↓
;jpn: いっておきましょうか。@KEY()
』

_MGKT_FLYINGMAN_2;フライングマン２
◆I’ll be your courage.@KEY()↓
◆I’ll remain unless you lose your courage.@KEY()↓
◆Call me Flying Man ２.
@KEY()
;jpn:◆わたしは あなたの ゆうき。@WI(20)↓
;jpn: あなたが ゆうきを↓
;jpn: うしなわぬかぎり@KEY()↓
;jpn:◆わたしは うまれます。@KEY()↓
;jpn:◆フライングマン２ とでも↓
;jpn: よんでください。@KEY()
』

_MGKT_FLYINGMAN_3;フライングマン３
◆I’m Flying Man ３.@KEY()↓
◆Your courage hasn’t died yet.@KEY()↓
◆Let’s go!@KEY()
;jpn:◆フライングマン３ です。@WI(20)↓
;jpn: あなたのゆうきは↓
;jpn: まだまだ かれていない。@KEY()↓
;jpn:◆いきましょう!@KEY()
』

_MGKT_FLYINGMAN_4;帰ってきたフライングマン
◆I’m also your courage.@KEY()↓
◆Call me Return of the Flying Man!@KEY()↓
◆...How’s that?@KEY()↓
◆However...don’t treat us like trash.@KEY()
;jpn:◆わたしも あなたの ゆうき。@WI(20)↓
;jpn: もしも なを よぶなら↓
;jpn: かえってきたフライングマン!@KEY()↓
;jpn:◆‥‥とでも よんでください。@WI(30)↓
;jpn: ただ‥‥@WI(15)あんまり わたしたちを↓
;jpn: そまつに あつかわないように。@KEY()
』

_MGKT_FLYINGMAN_5;さいごのフライングマン
◆Of course, we’re your courage.@KEY()↓
◆But I warned you not to treat us like trash!@KEY()↓
◆Didn’t you get it?!@KEY()↓
◆This isn’t courage, it’s desperation.@KEY()↓
◆If yo don’t understand ”courage,” look it up in the dictionary.@KEY()↓
◆Okay?@KEY()↓
◆My name’s The Final Flying Man.@KEY()
;jpn:◆むろん わたしたちは↓
;jpn: あなたの ゆうき ですが↓
;jpn: そまつに しないようにと@KEY()↓
;jpn:◆ちゅうこくしたでしょう?!@WI(20)↓
;jpn: これでは ゆうきではなく↓
;jpn: 「ばんゆう」です。@KEY()↓
;jpn:◆「ばんゆう」のいみが↓
;jpn: わからなかったら↓
;jpn: じしょを ひいてください。@KEY()↓
;jpn:◆いいですね。@KEY()↓
;jpn:◆わたしのなは@WI(15)↓
;jpn: さいごのフライングマン。@KEY()
』

MSG_MGKT_FLYINGMAN_ALREADY;
◆Did you want to talk to me?@KEY()↓
◆I’m sorry, there’s really not much to say...
@KEYNP()

;jpn:◆わたしと なにか↓
;jpn: はなしが したかったのですね。@KEY()↓
;jpn:◆わたしは あいにく↓
;jpn: わだいが すくないもので‥‥@WI(20)↓
;jpn: もうしわけ ありません。@KEYNP()
』



_SUB_Q_FLYINGMAN;
@GET_ORDER_PLAYER(2)
@SAVE_REG()
@EQ(PC_FLYINGMAN1)
@TRUE_GOTO(_Q_FLY_END)
@LOAD_REG()
@EQ(PC_FLYINGMAN2)
@TRUE_GOTO(_Q_FLY_END)
@LOAD_REG()
@EQ(PC_FLYINGMAN3)
@TRUE_GOTO(_Q_FLY_END)
@LOAD_REG()
@EQ(PC_FLYINGMAN4)
@TRUE_GOTO(_Q_FLY_END)
@LOAD_REG()
@EQ(PC_FLYINGMAN5)
_Q_FLY_END;
@!

;@Habitat:マジカント／ショップ／ショップ
;@Person:ペンダント売り
;@Figure:ミンチ
;@AppearanceKey:0
;@ActionScript:◆正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_PENDANT
MSG_MGKT_PENDANT;
;◆Hey, @DSP_STS(STS_PC_NAME_NES)!
;  What do you want?

;jpn:◆やあ @DSP_STS(STS_PC_NAME_NES)くん!↓
;jpn: ほしいものは なんだね?@KEY()
;@GOSUB(MSG_SHOP_MGKT_PENDANT)
』


;@Habitat:マジカント／フライングマンの家／フライングマンの家
;@Person:フライングマン２
;@Figure:フライングマン
;@AppearanceKey:FLG_FLYINGMAN_2/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_FLYINGMAN_2

;@Habitat:マジカント／フライングマンの家／フライングマンの家
;@Person:フライングマン３
;@Figure:フライングマン
;@AppearanceKey:FLG_FLYINGMAN_3/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_FLYINGMAN_3

;@Habitat:マジカント／フライングマンの家／フライングマンの家
;@Person:フライングマン４
;@Figure:フライングマン
;@AppearanceKey:FLG_FLYINGMAN_4/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_FLYINGMAN_4

;@Habitat:マジカント／フライングマンの家／フライングマンの家
;@Person:フライングマン５
;@Figure:フライングマン
;@AppearanceKey:FLG_FLYINGMAN_5/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_FLYINGMAN_5

；----------------------------------------
;@Habitat:マジカント／ホテル／ホテル
;@Person:マジc宿主
;@Figure:マジカントのトリ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_C
MSG_MGKT_C;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_MGKT_C_AFTER)
◆Please rest.@KEY()↓
◆The dream you’ll have here is a dream within a dream.@KEY()↓
◆Your heart knows things you aren’t aware of.@KEY()↓
◆Do you want to sleep?↓
<Yes>
<No>

;jpn:◆ゆっくり やすんでいっておくれ。↓
;jpn: ここでみるゆめは↓
;jpn: ゆめの また ゆめ。@KEY()↓
;jpn:◆じぶんのこころは↓
;jpn: じぶんでも しらないことを↓
;jpn: しってるんだよ。@KEY()↓
;jpn:◆ねむるかい?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MGKT_C_YES,_MGKT_C_NO)

_MGKT_C_NO;
◆Okay.@KEY()↓
◆If you walk outside, beware of the monsters.
@KEYNP()
;jpn:◆そうかい。@WI(20)↓
;jpn: そとをあるくなら ばけものに↓
;jpn: きをつけておくれ。@KEYNP()
』

_MGKT_C_YES;
;体力回復(暗転ワープあり、BGM２、夜鍋あり、セリフ替えなし)
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_YADOYA_MGKT)
@!

_MGKT_C_AFTER;
◆If you walk outside, beware of the monsters.
@KEYNP()

;jpn:◆そとをあるくなら ばけものに↓
;jpn: きをつけておくれ。@KEYNP()
@!


；----------------------------------------
;@Habitat:マジカント／マイホーム／部屋１
;@Person:マジeママ
;@Figure:ネスのママ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_E
MSG_MGKT_E;
◆Oh @DSP_NAME(PC_NESS), are you tired from traveling on your adventure?@KEY()↓
<Yes>
<No>
;jpn:◆まぁ @DSP_STS(STS_PC_NAME_NES)↓
;jpn: ぼうけんのたびに つかれたの?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_MGKT_E_YES,_MGKT_E_NO)

_MGKT_E_NO;
◆Yeah, that’s right.@KEY()↓
◆You can’t even think about being tired at a time like this.@KEY()↓
◆Be strong!
@KEY()
;jpn:◆そうね。つかれたなんて↓
;jpn: いってられないわね。@WI(20)↓
;jpn: しっかり!@WI(20) @DSP_STS(STS_PC_NAME_NES)。@KEY()
;体力回復(暗転ワープあり、BGM２、夜鍋あり、セリフ替えなし)
;@GOSUB(MSG_SUB_ALLHEAL_POWR)
;@GOSUB(MSG_GLOBAL_MYHOME)
;@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
;@WARP(WARP_MGKT_MAMA)
@SET_PALLETSET(31,7,60);ピンク
』

_MGKT_E_YES;
◆If you wish, you can stay here forever.@KEY()↓
◆I’ll make some @DSP_STS(STS_PARTY_FAVORITE_FOODS) for you.@KEY()

;jpn:◆それなら いつまでも↓
;jpn: ここにいていいのよ。@WI(20)↓
;jpn: @DSP_STS(STS_PARTY_FAVORITE_FOODS)も つくるわ。@KEY()
;体力回復(暗転ワープあり、BGM２、夜鍋あり、セリフ替えなし)
@GOSUB(MSG_SUB_ALLHEAL_POWR)
@GOSUB(MSG_GLOBAL_MYHOME)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@WARP(WARP_MGKT_MAMA)
@SET_PALLETSET(31,7,60);ピンク
』


;@Habitat:マジカント／マイホーム／部屋２
;@Person:マジf妹トレーシー
;@Figure:トレーシー
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_F
MSG_MGKT_F;
◆Brother @DSP_NAME(PC_NESS)!@KEY()↓
◆The ”Sea of Eden” is at the end of Magicant.@KEY()↓
◆Other people can’t get close to it.@KEY()↓
◆It’s a strange place.@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)おにいちゃん!@WI(20)↓
;jpn: マジカントの ずっとおくに↓
;jpn: 「エデンのうみ」があるわよ。@KEY()↓
;jpn:◆ほかのひとには ちかよれない↓
;jpn: ふしぎなばしょなのよ。@KEY()↓
@SET_PALLETSET(5,0,60);ノーマル
◆Is there anything I can do for you?
@KEY()↓
;jpn:◆わたしに↓
;jpn: してあげられることは ある?@KEY()↓
@GOTO(MSG_TRACY_GLOBAL_START);汎用のトレーシー呼び出し(三浦)


;@Habitat:マジカント／マイホーム／部屋２
;@Person:マジi
;@Figure:ネスの犬
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_I
MSG_MGKT_I;
◆Whimper...whine.@KEY()↓
◆(I lived in your house before you were born...@KEY()↓
◆@DSP_NAME(PC_NESS) used to be small and weak.)
@KEYNP()
;jpn:◆クン クーン。↓
;jpn: (ぼくは きみが↓
;jpn: うまれるまえから@KEY()↓
;jpn:◆きみの うちに いたんだよ。↓
;jpn: むかしは @DSP_STS(STS_PC_NAME_NES)って↓
;jpn: もっと よわむしだったんだ)@KEYNP()
』

；----------------------------------------
;@Habitat:マジカント／電話CDの部屋／電話CDの部屋
;@Person:鳥A
;@Figure:ヒヨコ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_BIRD_A
MSG_MGKT_BIRD_A;
◆Pi pi pi pi pi@KEY()↓
◆(I’m just a faint memory.@KEY()↓
◆You don’t usually remember me.@KEY()↓
◆But you’ve heard my song in the back of your mind.)
@KEYNP()
;jpn:◆ピピピピピ↓
;jpn: (わたしは あなたの↓
;jpn: おもいでの かたすみにいる@KEY()↓
;jpn:◆ふだんは おもいださないけど↓
;jpn: わたしのさえずりを↓
;jpn: いつも きいていたのよ)@KEYNP()
』

;@Habitat:マジカント／電話CDの部屋／電話CDの部屋
;@Person:キャッシュディスペンサ
;@Figure:CD
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;@Habitat:マジカント／電話CDの部屋／電話CDの部屋
;@Person:公衆電話
;@Figure:電話ボックス
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

；----------------------------------------
;@Habitat:マジカント／フィールド／初めて会う所
;@Person:マジa
;@Figure:マジカントの人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_A
MSG_MGKT_A;
◆This is the realm of Magicant, which your mind created.@KEY()↓
◆Why don’t you explore your mind.@KEY()↓
◆Take your time, @DSP_NAME(PC_NESS).
@KEYNP()
;jpn:◆ここは マジカントのくに。↓
;jpn: きみのこころが うみだしたくに。@KEY()↓
;jpn:◆ゆっくりと じぶんのこころを↓
;jpn: たんけんしてみなよ @DSP_STS(STS_PC_NAME_NES)。@KEYNP()
@SET_PALLETSET(31,5,60);黄色黒
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:マジd幼いネス
;@Figure:キャップ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_D
MSG_MGKT_D;
◆It’s me...@KEY()↓
◆I’m you when you were younger.@KEY()↓
◆Hey, let’s play ball.@KEY()↓
◆Do you prefer reading comics or playing games?@KEY()↓
◆What?@KEY()↓
◆You’re busy?...
@KEYNP()
;jpn:◆ぼく きみのちいさいころの‥‥↓
;jpn: ぼくだよ。↓
;jpn: ねぇ キャッチボールしようよ。@KEY()↓
;jpn:◆それとも まんがをよんだり↓
;jpn: ゲームをしたりするかい?↓
;jpn: えっ? いそがしいのかぁ‥‥。@KEYNP()
@SET_PALLETSET(31,3,60);オレンジ
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:マジg敵キャラ
;@Figure:ゾンビ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_G
MSG_MGKT_G;
◆You kicked my butt badly...@KEY()↓
◆I won’t forget!
@KEYNP()
;jpn:◆おまえには ずいぶん↓
;jpn: いためつけられたけど‥‥↓
;jpn: @WI(20)‥‥おぼえてるぜ!@KEYNP()
@SET_PALLETSET(31,2,60);こげ茶黒
』        

;@Habitat:マジカント／フィールド／適当なところ
;@Person:マジh敵キャラ
;@Figure:大ムッド
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_H
MSG_MGKT_H;
◆You destroyed my pride...@KEY()↓
◆AAaaaargh!
@KEYNP()
;jpn:◆おれのプライドは ズタズタだ。↓
;jpn: おまえに やられてからな‥‥。↓
;jpn: チェッ。@KEYNP()
@SET_PALLETSET(31,6,60);ピンク青
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:マジj敵キャラ
;@Figure:半魚人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_J
MSG_MGKT_J;
◆@DSP_NAME(PC_NESS)@KEY()↓
◆I still feel pain where you wounded me.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_NES)さん↓
;jpn: あんたに やられた キズが↓
;jpn: いまでも シクシクいたみますぜ。@KEYNP()
@SET_PALLETSET(31,6,60);ピンク青
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk1
;@Figure:ヘルメット
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_1
MSG_MGKT_K_1;
;幼稚園児の列
◆Waaaa, @DSP_NAME(PC_NESS), let’s play.
@KEYNP()
;jpn:◆ワイワイ↓
;jpn: @DSP_STS(STS_PC_NAME_NES)ちゃん あそぼう。@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk2
;@Figure:ハット
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_2
MSG_MGKT_K_2;
◆Gyaaa.@KEY()↓
◆Long time no see @DSP_NAME(PC_NESS)!
@KEYNP()
;jpn:◆ガヤガヤ↓
;jpn: ひさしぶりだね @DSP_STS(STS_PC_NAME_NES)!@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk3
;@Figure:ダンゴ
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_3
MSG_MGKT_K_3;0
◆La lalala.@KEY()↓
◆My name’s Nico...Let’s run and sing and dance!
@KEYNP()
;jpn:◆ランララン↓
;jpn: いっしょに うたを↓
;jpn: うたいましょ!@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk4
;@Figure:ピッキー
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_4
MSG_MGKT_K_4;
◆@DSP_NAME(PC_NESS)!@KEY()↓
◆Pokey took my snack!
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_NES)ちゃーん↓
;jpn: ポーキーにいちゃんに↓
;jpn: おかしを とられたよーん。@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk5
;@Figure:リボン
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_5
MSG_MGKT_K_5;
◆Fresh!
@KEYNP()
;jpn:◆エッチー!@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk6
;@Figure:さる
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_6
MSG_MGKT_K_6;
◆Kya Kya.
@KEYNP()
;jpn:◆キャッ キャ@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk7
;@Figure:インディー
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_7
MSG_MGKT_K_7;
◆Peace!@KEY()↓
◆We haven’t played together lately.
@KEYNP()
;jpn:◆ピース!↓
;jpn: さいきん いっしょに↓
;jpn: あそんでないな。@KEYNP()
;@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／団体幼児
;@Person:マジk8
;@Figure:マジカントの人
;@AppearanceKey:0
;@ActionScript:◆列になってうろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_K_8
MSG_MGKT_K_8;
◆I’d like you to take your time,@KEY()↓
◆’cause this country will disappear when you wake up.
@KEYNP()
;jpn:◆ゆっくりしてけと いいたいけれど↓
;jpn: このくには おまえが めざめたら↓
;jpn: きえちゃうんだよ。@KEYNP()
@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:マジlネス自身
;@Figure:ネス
;@AppearanceKey:0
;@ActionScript:◆その場でうろうろ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_L
MSG_MGKT_L;
@CHKFGOTO(FLG_MGKT_GETITEM_CAP,_MGKT_L_LATER)
◆Hey me!@KEY()↓
◆I found my cap that you lost.@KEY()↓
;jpn:◆やぁ ぼく!↓
;jpn: ぼくがむかしなくした↓
;jpn: あのぼうしが みつかったよ!@KEY()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_MGKT_L_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_EQUIP_CAP_NANAIRO)
@GOSUB(MSG_SUB_GETGOODS)@KEYNP()
@SETF(FLG_MGKT_GETITEM_CAP)
@SET_PALLETSET(31,3,60);オレンジ
』

_MGKT_L_ITEMFULL;
←
◆I’m so stupid!@KEY()↓
◆There’s lots of junk in my backpack at a time like this.@KEY()↓
◆Why don’t I get rid of something I don’t use.
@KEYNP()
;jpn:◆おまぬけな ぼく!↓
;jpn: こんな だいじなときに↓
;jpn: つまらないにもつが いっぱい!@KEY()↓
;jpn:◆なにか すてるか つかうか↓
;jpn: してこなきゃ↓
;jpn: だめだよ。@KEYNP()
@SET_PALLETSET(5,0,60);ノーマル
』

_MGKT_L_LATER;
◆Hey me!
@KEYNP()
;jpn:◆やぁ ぼく!@KEYNP()
@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:鳥B
;@Figure:ヒヨコ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_BIRD_B
MSG_MGKT_BIRD_B;
◆Chi chi chi chi chi@KEY()↓
◆(Onett was a quiet, small town, wasn’t it?)
@KEYNP()
;jpn:◆チチチチチ@WI(20)↓
;jpn: (オネットは↓
;jpn: おだやかな まちだったわね)@KEYNP()
@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:花々
;@Figure:マジカントの花
;@AppearanceKey:0
;@ActionScript:◆その場でアニメーション
;@GoodsMessage:0
;@CheckMessage:0
;@Message:SG_MGKT_FLOWER
MSG_MGKT_FLOWER;
;複数配置して賑やかにしたい
◆Look at the sun.@KEY()↓
◆Face the sun and smile...
@KEYNP()
;jpn:◆音おひさまに むかおう↓
;jpn: おひさまに かおを むけて↓
;jpn: 音えがおを つくろう 音@KEYNP()
@SET_PALLETSET(5,0,60);ノーマル
』

;@Habitat:マジカント／フィールド／フライング家の前
;@Person:フライング墓１
;@Figure:フライングマンの墓
;@AppearanceKey:FLG_SYS_FLYINGMAN_DEAD_A
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_MGKT_TOMB1
;@Message:0
MSG_MGKT_TOMB1;
◆@DSP_NAME(PC_NESS)’s courage is resting here.@KEY()↓
◆He fought well and died.
@KEYNP()
;jpn:◆ここに ねむるは↓
;jpn: @DSP_STS(STS_PC_NAME_NES)の ゆうき。↓
;jpn: よくたたかい きずつきたおれた。@KEYNP()
』

;@Habitat:マジカント／フィールド／フライング家の前
;@Person:フライング墓２
;@Figure:フライングマンの墓
;@AppearanceKey:FLG_SYS_FLYINGMAN_DEAD_B
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_MGKT_TOMB2
;@Message:0
MSG_MGKT_TOMB2;
◆Another one of @DSP_NAME(PC_NESS)’s courage is resting here.@KEY()↓
◆He damaged evil terribly, and finally died.
@KEYNP()

;jpn:◆ここに ねむるは↓
;jpn: さらなる @DSP_STS(STS_PC_NAME_NES)の ゆうき。@KEY()↓
;jpn:◆じゃあくなるものに↓
;jpn: おおきな だげきをあたえ↓
;jpn: ついに たおれた。@KEYNP()
』

;@Habitat:マジカント／フィールド／フライング家の前
;@Person:フライング墓３
;@Figure:フライングマンの墓
;@AppearanceKey:FLG_SYS_FLYINGMAN_DEAD_C
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_MGKT_TOMB3
;@Message:0
MSG_MGKT_TOMB3;
◆Here he rests...@KEY()↓
◆I didn’t have time to have his name chiseled into the tombstone.
@KEYNP()
;jpn:◆ここに ねむるは‥‥↓
;jpn: いそがしくて はかにもじを↓
;jpn: きざむひまもなかった。@KEYNP()
』

;@Habitat:マジカント／フィールド／フライング家の前
;@Person:フライング墓４
;@Figure:フライングマンの墓
;@AppearanceKey:FLG_SYS_FLYINGMAN_DEAD_D
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_MGKT_TOMB4
;@Message:0
MSG_MGKT_TOMB4;
◆Someone’s tombstone.
@KEYNP()
;jpn:◆だれかの はか。@KEYNP()
』

;@Habitat:マジカント／フィールド／フライング家の前
;@Person:フライング墓５
;@Figure:フライングマンの墓
;@AppearanceKey:FLG_SYS_FLYINGMAN_DEAD_E
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessageMSG_MGKT_TOMB5
;@Message:0
MSG_MGKT_TOMB5;
◆Tombstone.
@KEYNP()
;jpn:◆はか。@KEYNP()
@SETF(FLG_MGKT_TOMB6)
』

;@Habitat:マジカント／フィールド／フライング家の前
;@Person:ブンブーンの墓６
;@Figure:フライングマンの墓
;@AppearanceKey:FLG_MGKT_TOMB6
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:MSG_MGKT_TOMB6
;@Message:0
MSG_MGKT_TOMB6;
◆This is Buzz Buzz’s tombstone.@KEY()↓
◆He appeared earlier in the game and gave up the ghost@KEY()↓
◆before he achieved his goal.
@KEYNP()
;jpn:◆ゲームのはじめに とうじょうして↓
;jpn: こころざし なかばにして↓
;jpn: たおれた ブンブーンのはか。@KEYNP()
』


;@Habitat:マジカント／フィールド／適当なところ
;@Person:老人A
;@Figure:マジカントの老人
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_OLDMAN_A
MSG_MGKT_OLDMAN_A;
◆The Sea of Eden is filled with ultimate intelligence.@KEY()↓
◆You can’t go there unless you’re truly ready.@KEY()↓
◆It’s a place where you can touch the truth of the unverse.@KEY()↓
◆Going there may bring sorrow.
@KEYNP()
;jpn:◆「エデンのうみ」は↓
;jpn: きゅうきょくの「ちえ」が↓
;jpn: うずまいている ところ。@KEY()↓
;jpn:◆なみたいていのことでは↓
;jpn: そこへは ゆけぬ。@KEY()↓
;jpn:◆うちゅうの しんりに↓
;jpn: いっしゅんだけ↓
;jpn: ふれることが できる ばしょだ。@KEY()↓
;jpn:◆そこへ ゆくことが↓
;jpn: おまえのふこうに↓
;jpn: なるかも しれぬぞ。@KEYNP()
@SET_PALLETSET(31,5,60);黄色黒
』

;@Habitat:マジカント／フィールド／適当なところ
;@Person:老人B
;@Figure:マジカントの老人
;@AppearanceKey:0
;@ActionScript:◆
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_OLDMAN_B
MSG_MGKT_OLDMAN_B;
;老人Aよりも先に、この人に会うようにしてください。
;例えば、宿屋にうろうろしるとか。
◆@DSP_NAME(PC_NESS), you’ve stood on the eight power spots of the earth.@KEY()↓
◆From these conditions, you created Magicant, the realm of your mind.@KEY()↓
◆In Magicant, there’s beauty, kindness, sorrow, and hatred.@KEY()↓
◆Of course, there’s an evil and violent side of you.@KEY()↓
◆The Sea of Eden sits at the center of those feelings.@KEY()↓
◆It takes you to the truth about yourself.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_NES) おまえは↓
;jpn: ちきゅうの８つのパワースポット↓
;jpn: すべてに たった。@KEY()↓
;jpn:◆そのことが この こころのくに↓
;jpn: マジカントを うみだす↓
;jpn: じょうけんだったのじゃよ。@KEY()↓
;jpn:◆このマジカントには↓
;jpn: おまえのこころのなかにある↓
;jpn: うつくしさも やさしさも@KEY()↓
;jpn:◆かなしみも にくしみも@KEY()↓
;jpn:◆むろん じゃあくなものや↓
;jpn: きょうぼうなものも あるのだ。@KEY()↓
;jpn:◆そして そのちゅうしんに↓
;jpn: しんりにつながる‥‥@KEY()↓
;jpn:◆「エデンのうみ」が↓
;jpn: そんざいしているのだ。@KEYNP()
@SET_PALLETSET(31,6,60);雪
』

;@Habitat:マジカント／フィールド／エデンの塔
;@Person:黄金のオスカー像
;@Figure:黄金のオスカー
;@AppearanceKey:FLG_WIN_OSCAR/off
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MGKT_OSCAR
MSG_MGKT_OSCAR;@MiuraAppended
;「@DSP_STS(STS_PC_NAME_NES)の あくま」
;または「マジカントの あくま」
@CHKFGOTO(FLG_WIN_OSCAR,MSG_SYS_HANASU_NG)
◆(I’m the evil part of your brain.@KEY()↓
◆You can’t beat me.@KEY()↓
◆Because you are the one forced me into being...)
;jpn:◆(ワタシハ↓
;jpn: オマエノ ココロノナカノ↓
;jpn: ジャアク。@KEY()↓
;jpn:◆タオスコトハ デキマイ。@KEY()↓
;jpn:◆オマエガ ソダテタ↓
;jpn: ワタシナノダカラ‥‥)
@KEY()
@GOSUB(MSG_BATTLE_OSCAR)
@TRUE_GOTO(MSG_BATTLE_LOSE)

;@SETF(FLG_DSRT_SYOZI_DISAPPEAR)ヤメ。地底大陸に入った時にセット
;@ANIM(ANIM_DISAPPEAR)
@SETF(FLG_WIN_OSCAR)
@WI(1)
@REMOVE_CHAR(PRSN_MGCT_EDEN_4A,ANIM_BLINK_SUICIDE)
@WI( 40 )
;背景の明度が揺れ出し、徐々に暗くなる
;※ アニメとの絡みがあるので、簡単に変更しないこと!!
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_EVT_FLUCTUATE_MAGICANT, OBJFX_SHOW_NONE )
@WAITSYS()					;(Start)
@COLD_GOM_CHAR( GOM_HIT_CHR )
MSG_MGKT_WIN_OSCAR_THEVOICE;「声」
;オスカーとの戦闘後のメッセージ
@OPEN(1)
◆(@DSP_NAME(PC_NESS) heard a familiar voice at the center of the Sea of Eden.)@KEY()↓
;jpn:◆(@DSP_STS(STS_PC_NAME_NES)は↓
;jpn: エデンのうみの ちゅうしんで↓
;jpn: ききおぼえのあるこえを きいた)@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(1)
◆Giygas’ goal is to destroy you.@KEY()↓
;jpn:◆@WI(20)「ギーグの ねらいは↓
;jpn: きみを まっさつすることにある。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(2)
◆Listen carefully!@KEY()↓

;jpn:◆いいか。よく きけ!@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(3)
◆Everything in the universe could be destroyed at the hands of Giygas.@KEY()↓
;jpn:◆ぎんがけいうちゅう すべてが↓
;jpn: ギーグというやつの てに↓
;jpn: おちるかも しれないんだ。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(4)
◆But he and his followers are also in trouble.@KEY()↓

;jpn:◆でも やつらも こまっている。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(5)
◆The Apple of Enlightenment has foretold@KEY()↓
;jpn:◆ギーグのもっている↓
;jpn: よげんマシン「ちえのリンゴ」は@KEY()↓;「よげんマシン＝ちえのリンゴ」は
@GOSUB( MSG_FRESH_WSYS_COLD );			;(6)
◆that Giygas’ attempt will fail.@KEY()↓
;jpn:◆ギーグのたくらみが↓
;jpn: しっぱいにおわると つげたんだ。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(7)
◆It is because of the existance of a boy named @DSP_NAME(PC_NESS).@KEY()↓
;jpn:◆その りゆうが‥‥@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(8)
◆...That’s me!@KEY()↓
 
;jpn:◆@DSP_STS(STS_PC_NAME_NES)というなの じゃまな↓
;jpn: しょうねんの そんざいなんだ。@WI(30)↓
;jpn: ‥‥ぼくだ!@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(9)
◆Listen.@KEY()↓

;jpn:◆いいかい。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(10)
◆Free your mind and KNOW what you must do!@KEY()↓

;jpn:◆こころを とぎすませて↓
;jpn: いま きみが どうするべきかを↓
;jpn: 「わかる」んだ!@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(11)
◆Your destiny has already been decided.@KEY()↓

;jpn:◆すでに うんめいは きまってる。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(12)
◆You...I...where should we go?@KEY()↓


;jpn:◆きみは‥‥@WI(30) ぼくは‥‥@WI(20)↓
;jpn: どこに いけば いいのか?@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(13)
◆You know deep within the reaches of your mind.@KEY()↓

;jpn:◆こころのおくで わかってるんだ。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(14)
◆ ...S...Sat...@KEY()↓
◆...Saturn@KEY()↓
◆...@KEY()↓

;jpn:◆‥‥サ@WI(20)タ@WI(20)↓
;jpn: ‥‥サターン@WI(20)↓
;jpn: ‥‥‥@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(15)
◆Saturn Valley...yes...@KEY()↓

;jpn:◆サターンバレー‥‥@WI(20)そうだ。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(16)
◆Go to the valley where the Mr.Saturn live.@KEY()↓

;jpn:◆どせいさんたちのいた↓
;jpn: あのたにに むかうんだ。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(17)
◆...You’ll get something new there.@KEY()↓

;jpn:◆‥‥そこで あたらしいなにかが↓
;jpn: つかめる。@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(18)
◆Soon, Magicant will be no more.@KEY()↓
◆We must be quick!@KEY()

;jpn:◆もうすぐ このマジカントは↓
;jpn: ‥‥しょうめつする。@WI(20)↓
;jpn: いそがなければ!」@KEY()↓
@GOSUB( MSG_FRESH_WSYS_COLD );			;(19)
@CLOSE()
@WI(120)
@OPEN( 1 )
◆(@DSP_NAME(PC_NESS) really heard his own voice.@KEY()↓
◆Go to Saturn Valley!@KEY()↓
◆Go to Saturn Valley now!)
@KEYNP()

;jpn:◆(@DSP_STS(STS_PC_NAME_NES)は たしかに↓
;jpn: じぶんじしんのこえを きいた。@KEY()↓
;jpn:◆サターンバレーへ!@KEY()↓
;jpn:◆サターンバレーへ!)@KEYNP()
@CLOSE()
@BGM_EFFECT( 3 )	;BGMフェードアウト長め
;次で完全に真っ暗に
@GOSUB( MSG_FRESH_WSYS_COLD );			;(Final)
@WI( 60 )
@GOTO(MSG_SYS_MGKT_NES_POWER_UP);SYSTEM.MSG内の経験値獲得処理へ
』
;-------------------
MSG_FRESH_WSYS_COLD;
@FRESH_GOM_CHAR( GOM_HIT_CHR )
@WAITSYS()
@COLD_GOM_CHAR( GOM_HIT_CHR )
』
;-------------------------------------------------

MSG_CHECK_MGKT_CLOCK;
◆@DSP_NAME(PC_NESS)!@KEY()↓
◆Did you learn how to tell what time I’m indicating?
@KEYNP()

;◆@DSP_STS(STS_PC_NAME_NES)!↓
;jpn: ぼくが なんじなんぷんを↓
;jpn: しめしているか@KEY()↓
;jpn:◆よめるようになったかい?@KEYNP()
』

MSG_CHECK_MGKT_SNOWMAN_1;
◆We had fun one snowy day.@KEY()↓
◆I melted, but I am still real in your memory.
@KEYNP()
;jpn:◆ふゆのひに あそんだね。↓
;jpn: ぼくは とけて↓
;jpn: きえてしまったけれど@KEY()↓
;jpn:◆きみの おもいでのなかに↓
;jpn: まだ のこっているんだよ。@KEYNP()
』
MSG_CHECK_MGKT_SNOWMAN_2;
◆I know the name of the girl you used to like.
@KEYNP()

;jpn:◆ぼく きみが むかし↓
;jpn: すきだった おんなのコのなまえ↓
;jpn: しってるよ。@KEYNP()
』
MSG_CHECK_MGKT_SNOWMAN_3;
◆Thank you for remembering me.
@KEYNP()
;jpn:◆ぼくのことを↓
;jpn: おぼえててくれて↓
;jpn: ありがとう@KEYNP()
』
;-------------------------------------------------

MSG_MGKT_POKEY;マジカントのポーキー
◆@DSP_NAME(PC_NESS), you’re so lucky...@KEY()↓
◆I envy you.@KEY()↓
◆...@KEY()↓
◆I have no luck.@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)↓
;jpn: おまえは いいよな‥‥。@KEY()↓
;jpn:◆なんか おまえのこと↓
;jpn: うらやましいよ。@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆おれなんか ダメさ。↓
@WI(60)↓
◆But, @DSP_NAME(PC_NESS)...well, okay...@KEY()↓

;jpn:◆だけど @DSP_STS(STS_PC_NAME_NES)↓
@WI(60)↓
◆Let’s be friends forever, all right?
@KEYNP()
;jpn:◆‥‥ま@WI(30) いいよ。@KEY()↓
;jpn:◆いつまでも なかよく↓
;jpn: やっていこうぜ@WI(30) な。@KEYNP()
』

MSG_MGKT_TONCHIKI;マジカントのトンチキさん
◆@DSP_NAME(PC_NESS)!@KEY()↓
◆Maybe you don’t wanna hear this,@KEY()↓
◆but you remind me of myself when I was young.@KEY()↓
◆I can’t do anything more for you.@KEY()↓
◆Good luck, @DSP_NAME(PC_NESS)!
@KEYNP()
;◆@DSP_STS(STS_PC_NAME_NES)!@WI(20)↓
;jpn: おまえは‥‥↓
;jpn: いやがるかもしれないけれど@KEY()↓
;jpn:◆おまえって わかいときの↓
;jpn: オレににてたんだ。@KEY()↓
;jpn:◆オレは もう↓
;jpn: なにすることも できないけどさ。@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)@WI(20)↓
;jpn: がんばってくれ!@KEYNP()
@CLOSEALL()
@WI(1)
@SET_PALLETSET(31,4,60)
@HIDE_CHAR(PRSN_MGCT_FIELD_1C,OBJFX_HIDE_VSTRIPE);消える
;@WI(120)
@SETF(FLG_MGKT_TONCHIKI_DISAPPEAR)
』

;エデンへの土管
MSG_CHECK_MGKT_DOKAN;
@CLOSEALL()
;@SE(SE_se64_taco)
;@WI(120)
;@WI(30)
@WARP(WARP_MGKT_EDEN)
@!
MSG_CHECK_MGKT_DOKAN_B;
@CLOSEALL()
;@SE(SE_se64_taco)
;@WI(120)
;@WI(30)
@WARP(WARP_MGKT_DOKAN_MGKT)
@!
;------------------------------------------------
MSG_MGKT_SOUNDSTONE_BROKE;＄音の石消える(マジカント後)
@OPEN(1)
◆The @DSP_GOODS(GDS_TOOL_SOUND_STONE) that @DSP_NAME(PC_NESS) used to have is now gone.
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_NES)が もっていた↓
;jpn: おとのいしは きえてしまった。@KEYNP()
@CLOSEALL()
@GOODSOUT(PC_ALL,GDS_TOOL_SOUND_STONE)
』
;------------------------------------------------
