;/////////////////////////////////回復/////////////////////////////////

MSG_BTL_HPMAX_KAIFUKU;
←
◆@DSP_OBJECT()’s HP are↓
  maxed out!
;jpn: @DSP_OBJECT()のHPが↓
;jpn: まんタンになる!
@SE(SE_se24_b_lifeup)
@KEY()
@!

MSG_BTL_HP_KAIFUKU;
←
◆@DSP_OBJECT() recovered↓
  @DSP_CNUM() HP!
;jpn: @DSP_OBJECT()のHPが↓
;jpn: @DSP_CNUM()かいふくする!
@SE(SE_se24_b_lifeup)
@KEY()
@!

MSG_BTL_PP_KAIFUKU;
←
◆@DSP_OBJECT() recovered↓
  @DSP_CNUM() PP!
;jpn: @DSP_OBJECT()のPPが↓
;jpn: @DSP_CNUM()かいふくする!
@SE(SE_se24_b_lifeup)
@KEY()
@!

;///////////////////////////////チェック///////////////////////////////////

MSG_BTL_CHECK_OFFENSE;
←
◆@DSP_OBJECT()’s↓
  offense is @DSP_CNUM().
;jpn: @DSP_OBJECT()は↓
;jpn: オフェンスが@DSP_CNUM()!
@KEY()
@!

MSG_BTL_CHECK_DEFENSE;
←
  Defense is @DSP_CNUM()!
;jpn: ディフェンスが@DSP_CNUM()!
@KEY()
@!



MSG_BTL_CHECK_ANTI_FIRE;●(akm0616 w/itoi)
←
◆Vulnerable to PSI Fire!
;jpn: PKファイアーに よわい!
@KEY()
@!

MSG_BTL_CHECK_ANTI_FREEZE;●(akm0616 w/itoi)
←
◆Vulnerable to PSI Freeze!
;jpn: PKフリーズに よわい!
@KEY()
@!

MSG_BTL_CHECK_ANTI_FLASH;●(akm0616 w/itoi)
←
◆Vulnerable to PSI Flash!
;jpn: PKフラッシュに よわい!
@KEY()
@!

MSG_BTL_CHECK_ANTI_PARALYSIS;●(akm0616 w/itoi)
←
◆Vulnerable to Paralysis!
;jpn: パラライシスに よわい!
@KEY()
@!

MSG_BTL_CHECK_BRAIN_LEVEL_0;●(akm0616 w/itoi)
←
◆Open to Hypnosis!
;jpn: さいみんじゅつに よわい!
@KEY()
@!

MSG_BTL_CHECK_BRAIN_LEVEL_3;●(akm0616 w/itoi)
←
◆Susceptible to Brain Shock.
;jpn: ブレインショックに よわい!
@KEY()
@!

;//////////////////////////////特殊状態にかかる//////////////////////////////

MSG_BTL_METAMORPHOSE_OK;●(akm0616 w/itoi)
←
◆Yikes! @DSP_ACTOR() turned into↓
  @DSP_OBJECT()!
;jpn: なんと @DSP_ACTOR()は @DSP_OBJECT()に↓
;jpn: へんしんしてしまった!
@KEY()
@!

MSG_BTL_METAMORPHOSE_NG;●(akm0616 w/itoi)
←
◆@DSP_ACTOR() could not turn↓
  into @DSP_OBJECT()!
;jpn: @DSP_ACTOR()は @DSP_OBJECT()に↓
;jpn: へんしんできなかった‥‥。
@KEY()
@!

MSG_BTL_DAIYA_ON;
←
◆@DSP_OBJECT() was↓
  diamondized!
;jpn: @DSP_OBJECT()は↓
;jpn: ダイヤモンドじょうたいに なってしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_SHIBIRE_ON;
←
◆@DSP_OBJECT()’s body↓
  became numb!
;jpn: @DSP_OBJECT()のからだは↓
;jpn: しびれてしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_KIMOCHI_ON;
←
◆@DSP_OBJECT() felt↓
  somewhat nauseous...
;jpn: @DSP_OBJECT()は なんだか↓
;jpn: きもちわるくなってしまった‥‥。
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_MODOKU_ON;
←
◆@DSP_OBJECT() got↓
  poisoned!
;jpn: @DSP_OBJECT()は↓
;jpn: どくに おかされた!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_KAZE_ON;
←
◆@DSP_OBJECT() caught a cold!
;jpn: @DSP_OBJECT()は↓
;jpn: かぜを ひいてしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

_SUB_GOBJECT_1;
@GET_OBJECT(1)
@ONGOTO(_GOBJECT_11,_GOBJECT_12,_GOBJECT_13)
_GOBJECT_11;
(he)
@!
_GOBJECT_12;
(she)
@!
_GOBJECT_13;
(it)
@!
_SUB_GOBJECT_2;
@GET_OBJECT(2)
@ONGOTO(_GOBJECT_21,_GOBJECT_22,_GOBJECT_23)
_GOBJECT_21;
(1)
@!
_GOBJECT_22;
(2)
@!
_GOBJECT_23;
(3)
@!


MSG_BTL_KINOKO_ON;
←
◆@DSP_OBJECT() began to↓
  feel strange!
;jpn: @DSP_OBJECT()は↓
;jpn: ふしぎな きもちになった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_TORITSU_ON;
←
◆@DSP_OBJECT() was↓
  possessed by a mini−ghost!
;jpn: @DSP_OBJECT()は ミニミニユーレイに↓
;jpn: とりつかれてしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_NAMIDA_ON;
←
◆@DSP_OBJECT() could not↓
  stop crying!
;jpn: @DSP_OBJECT()は↓
;jpn: なみだが とまらなくなった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_SHIBARA_ON;
←
◆@DSP_OBJECT() suddenly↓
  could not move!
;jpn: @DSP_OBJECT()は↓
;jpn: うごけなく なってしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_KOORI_ON;
←
◆@DSP_OBJECT()’s body↓
  solidified!
;jpn: @DSP_OBJECT()のからだは↓
;jpn: かたまってしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_FUUIN_ON;
←
◆@DSP_OBJECT() was↓
  not able to concentrate!
;jpn: @DSP_OBJECT()は↓
;jpn: コンセントレーションが できなくなった!
@SE(SE_se53_foe_possess)
@KEY()↓
◆@DSP_OBJECT() was↓
  not able to use PSI!
;jpn: PSIが↓
;jpn: つかえなくなった!
@KEY()
@!

MSG_BTL_HEN_ON;
←
◆@DSP_OBJECT() felt↓
  a little strange...
;jpn: @DSP_OBJECT()は↓
;jpn: すこし ヘンになった‥‥。
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_NEMURI_ON;
←
◆@DSP_OBJECT() fell↓
  asleep!
;jpn: @DSP_OBJECT()は↓
;jpn: ねむってしまった!
@SE(SE_se53_foe_possess)
@KEY()
@!

MSG_BTL_KIZETU_ON;
←
◆@DSP_OBJECT() got hurt↓
  and collapsed...
;jpn: @DSP_OBJECT()は↓
;jpn: きずつき たおれた‥‥。
@SE(SE_se20_b_my_down)
@KEY()
@!

MSG_SYS_NPCDEAD_FLYINGMAN;
←
◆@DSP_OBJECT() got hurt↓
  and collapsed...
;jpn: @DSP_OBJECT()は↓
;jpn: きずつきたおれた‥‥。
@SE(SE_se20_b_my_down)
@CLRF(FLG_BGM_FLYINGMAN)
@KEY()↓
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_D,_FLYDEAD_E)
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_C,_FLYDEAD_D)
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_B,_FLYDEAD_C)
@CHKFGOTO(FLG_SYS_FLYINGMAN_DEAD_A,_FLYDEAD_B)
@SETF(FLG_SYS_FLYINGMAN_DEAD_A)
@GOSUB(_SUB_FLYDEAD_DEL)
』

_FLYDEAD_B;
@SETF(FLG_SYS_FLYINGMAN_DEAD_B)
@GOSUB(_SUB_FLYDEAD_DEL)
@!

_FLYDEAD_C;
@SETF(FLG_SYS_FLYINGMAN_DEAD_C)
@GOSUB(_SUB_FLYDEAD_DEL)
@!

_FLYDEAD_D;
@SETF(FLG_SYS_FLYINGMAN_DEAD_D)
@GOSUB(_SUB_FLYDEAD_DEL)
@!

_FLYDEAD_E;
@SETF(FLG_SYS_FLYINGMAN_DEAD_E)
@GOSUB(_SUB_FLYDEAD_DEL)
@!

_SUB_FLYDEAD_DEL;
@GET_ORDER_PLAYER(2)
@SAVE_REG()
@EQ(PC_FLYINGMAN1)
@FALSE_GOTO(_FDEAD_DEL_2)
@DEL_PARTY(PC_FLYINGMAN1)
@!
_FDEAD_DEL_2;
@LOAD_REG()
@EQ(PC_FLYINGMAN2)
@FALSE_GOTO(_FDEAD_DEL_3)
@DEL_PARTY(PC_FLYINGMAN2)
@!
_FDEAD_DEL_3;
@LOAD_REG()
@EQ(PC_FLYINGMAN3)
@FALSE_GOTO(_FDEAD_DEL_4)
@DEL_PARTY(PC_FLYINGMAN3)
@!
_FDEAD_DEL_4;
@LOAD_REG()
@EQ(PC_FLYINGMAN4)
@FALSE_GOTO(_FDEAD_DEL_5)
@DEL_PARTY(PC_FLYINGMAN4)
@!
_FDEAD_DEL_5;
@DEL_PARTY(PC_FLYINGMAN5)
@!

MSG_SYS_NPCDEAD_NUIGURUMI;
←
◆@DSP_OBJECT() became↓
  a pile of fluff...
;jpn: @DSP_OBJECT()は↓
;jpn: ボロボロに こわれてしまった‥‥。
@SE(SE_se20_b_my_down)
@KEY()↓
@GOODSOUT(PC_ALL,GDS_HAVE_NUIGURUMI)
』

MSG_SYS_NPCDEAD_NUIGURUMI_S;
←
◆@DSP_OBJECT() became↓
  a big pile of fluff...
;jpn: @DSP_OBJECT()は↓
;jpn: ﾎﾞﾛﾎﾞﾛに こわれてしまった‥‥。
@SE(SE_se20_b_my_down)
@KEY()↓
@GOODSOUT(PC_ALL,GDS_HAVE_NUIGURUMI_SUPER)
@!

;以下は、最後に@KEY()を付けてはいけない。三浦兄
;----------------------------------------------
MSG_BTL_KIZETU_ON_M;
←
◆@DSP_OBJECT() was↓
  defeated!
;jpn: @DSP_OBJECT()を↓
;jpn: たおした!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_UGOKANAKU;
←
◆@DSP_OBJECT() stopped↓
  moving!
;jpn: @DSP_OBJECT()は↓
;jpn: うごかなくなった!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_OTONASHIKU;
←
◆@DSP_OBJECT() became↓
  tame!
;jpn: @DSP_OBJECT()は↓
;jpn: おとなしくなった!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_KIESARU;
←
◆@DSP_OBJECT() disappeared!
;jpn: @DSP_OBJECT()は↓
;jpn: きえさった!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_KAKIKIERU;
←
◆The figure of @DSP_OBJECT()↓
  melted into thin air!
;jpn: @DSP_OBJECT()は↓
;jpn: かききえた!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_KUDAKERU;
←
◆@DSP_OBJECT() was↓
  broken into pieces!
;jpn: @DSP_OBJECT()は↓
;jpn: こなごなに くだけた!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_HAKAI;
←
◆@DSP_OBJECT() was↓
  destroyed!
;jpn: @DSP_OBJECT()を↓
;jpn: はかいした!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_PONKOTSU;
←
◆@DSP_OBJECT() was↓
  totally scrapped!
;jpn: @DSP_OBJECT()は↓
;jpn: ポンコツに なった!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_WARENI;
←
◆@DSP_OBJECT() turned back↓
  to normal!
;jpn: @DSP_OBJECT()は↓
;jpn: われに かえった!
@SE(SE_se21_b_foe_down)
@!

MSG_BTL_KIZETU_ON_TSUCHINI;
←
◆@DSP_OBJECT() returned to the↓
  dust of the earth!
;jpn: @DSP_OBJECT()は↓
;jpn: つちに かえった!
@SE(SE_se21_b_foe_down)
@!


;////////////////////////////特殊状態からの回復//////////////////////////

MSG_BTL_DAIYA_OFF;
←
◆@DSP_OBJECT()’s body↓
  returned to normal!
;jpn: @DSP_OBJECT()のからだは↓
;jpn: もとのすがたに もどった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_SHIBIRE_OFF;
←
◆@DSP_OBJECT()’s numbness↓
  is gone!
;jpn: @DSP_OBJECT()の↓
;jpn: からだのしびれが きえた!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_KIMOCHI_OFF;
←
◆@DSP_OBJECT() felt↓
  much better!
;jpn: @DSP_OBJECT()の きぶんは↓
;jpn: よくなった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_MODOKU_OFF;
←
◆The poison was removed↓
  from @DSP_OBJECT()’s body!
;jpn: @DSP_OBJECT()のからだから↓
;jpn: どくが きえた!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_KAZE_OFF;
←
◆@DSP_OBJECT() got over↓
  the cold!
;jpn: @DSP_OBJECT()の かぜが↓
;jpn: なおった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_NAMIDA_OFF;
←
◆@DSP_OBJECT() finally↓
  stopped crying...
;jpn: @DSP_OBJECT()の なみだは↓
;jpn: ようやく とまった‥‥。
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_SHIBARA_OFF;
←
◆@DSP_OBJECT()’s body↓
  again moved freely!
;jpn: @DSP_OBJECT()のからだは↓
;jpn: じゆうになった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_KOORI_STAT;
←
◆@DSP_OBJECT() was↓
  able to move!
;jpn: @DSP_ACTOR()は↓
;jpn: うごけるようになった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_HEN_OFF;
←
◆@DSP_OBJECT() went↓
  back to normal!
;jpn: @DSP_OBJECT()は↓
;jpn: もとにもどった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_NISSYA_OFF;
←
◆@DSP_OBJECT()’s sunstroke↓
  was cured!
;jpn: @DSP_OBJECT()の↓
;jpn: にっしゃびょうが なおった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_NEMURI_OFF;
←
◆@DSP_OBJECT() woke up!
;jpn: @DSP_OBJECT()は めをさました!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_FUUIN_OFF;
←
◆@DSP_OBJECT() was↓
  able to concentrate!
;jpn: @DSP_OBJECT()は↓
;jpn: コンセントレーションできるように なった!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_IKIKAERI;
←
◆@DSP_OBJECT() was revived!
;jpn: @DSP_OBJECT()は↓
;jpn: カムバックした!
@SE(SE_se25_b_healing)
@KEY()
@!

MSG_BTL_IKIKAERI_F;
←
◆It didn’t work...
;jpn: だめでした‥‥。
@KEY()
@!

;////////////////////////////////シールド/////////////////////////////////////
MSG_BTL_SHIELD_ON;
←
◆@DSP_OBJECT()’s body was↓
  protected by the light from the Shield!
;jpn: @DSP_OBJECT()のからだが↓
;jpn: ひかりのシールドに つつまれた!
@KEY()
@!

MSG_BTL_SHIELD_ADD;
←
◆The light from @DSP_OBJECT()’s↓
  Shield became brighter!
;jpn: @DSP_OBJECT()の シールドの↓
;jpn: ひかりが つよくなった!
@KEY()
@!

MSG_BTL_POWER_ON;
←
◆@DSP_OBJECT()’s body was↓
  protected by the Counter−attack Shield!
;jpn: @DSP_OBJECT()のからだが↓
;jpn: はんげきのシールドに つつまれた!
@KEY()
@!

MSG_BTL_POWER_ADD;
←
◆@DSP_OBJECT()’s Counter−↓
  attack Shield became stronger!
;jpn: @DSP_OBJECT()の↓
;jpn: はんげきのシールドの つよさが ました!
@KEY()
@!

MSG_BTL_PSYCO_ON;
←
◆@DSP_OBJECT()’s body was↓
  protected by the Psychic Shield!
;jpn: @DSP_OBJECT()のからだが↓
;jpn: サイコシールドに つつまれた!
@KEY()
@!

MSG_BTL_PSYCO_ADD;
←
◆@DSP_OBJECT()’s↓
  Psychic Shield became stronger!
;jpn: @DSP_OBJECT()の サイコシールドの↓
;jpn: つよさが ました!
@KEY()
@!

MSG_BTL_PSYPOWER_ON;
←
◆@DSP_OBJECT()’s body was↓
  protected by the Counter−attack@KEY()↓
◆Psychic Shield!
;jpn: @DSP_OBJECT()のからだが↓
;jpn: はんげきのサイコシールドに つつまれた!
@KEY()
@!

MSG_BTL_PSYPOWER_ADD;
←
◆@DSP_OBJECT()’s Counter−↓
  attack Psychic Shield@KEY()↓
◆became stronger!
;jpn: @DSP_OBJECT()の↓
;jpn: はんげきのサイコシールドの
;@KEY()
;↓
;;jpn: つよさが ました!
@KEY()
@!

MSG_BTL_SHIELD_OFF;
←
◆@DSP_OBJECT()’s Shield↓
  disappeared!
;jpn: @DSP_OBJECT()のシールドは↓
;jpn: きえて なくなった!
@KEY()
@!

MSG_BTL_POWER_TURN;
←
◆The Counter−attack Shield↓
  deflected the attack!
;jpn: はんげきのシールドが↓
;jpn: こうげきを はねかえした!
@SE(SE_se5d)
@WI(30)
@KEY()
@!

MSG_BTL_PSYPOWER_TURN;
←
◆The Counter−attack Shield↓
;jpn: はんげきのサイコシールドが↓
@GET_CITEM()
@XCHG()
  deflected @DSP_PSI(0)!
;jpn: @DSP_PSI(0)を はねかえした!
@SE(SE_se5d)
@KEY()
@!

MSG_BTL_PSYCO_TURN;
←
◆@DSP_OBJECT()’s↓
  Psychic Shield made@KEY()↓
;jpn: @DSP_OBJECT()の サイコシールドが↓
@GET_CITEM()
@XCHG()
  @DSP_PSI(0) disappear!
;jpn: @DSP_PSI(0)を かきけした!
;@SE((しゅんん))
@KEY()
@!

MSG_BTL_NEUTRALIZE_RESULT;
;@SE(SE_)
←
◆The effects of PSI on↓
  @DSP_OBJECT() is gone!
;jpn: @DSP_OBJECT()に かかっていた↓
;jpn: PSIのこうりょくが きえた!
@SE(SE_se29_b_defense_down)
@KEY()
@!

MSG_BTL_NEUTRALIZE_METAMORPH;
←
◆@DSP_STS(STS_PC_NAME_POO) returned↓
  to his original form!
;jpn: @DSP_STS(STS_PC_NAME_POO)は↓
;jpn: もとのすがたに もどった!
@KEY()
@!

MSG_BTL_FRANKLIN_TURN;
←
◆The Franklin Badge deflected↓
  the lightning!
;jpn: フランクリンバッジが↓
;jpn: いなずまを はねかえした!
@SE(SE_se5d)
@KEY()
@!

