;///////////////////////モンスターの特殊攻撃(2/3)////////////////////////

MSG_BTL_PPDOWN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() made↓
  something spin around!
;jpn: @DSP_ACTOR()は↓
;jpn: なにかを ぐるぐるとまわした!
@KEY()
@!

MSG_BTL_OKORU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() lost↓
  his temper!
;jpn: @DSP_ACTOR()は↓
;jpn: つい かっとなってしまった!
@KEY()
@!

MSG_BTL_KITANAI_KOTOBA;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() said↓
  something nasty!
;jpn: @DSP_ACTOR()は↓
;jpn: きたないことばを なげつけた!
@SE(SE_se54_foe_word)
@KEY()
@WI(1)
@!

MSG_BTL_SUIBUN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() used a↓
  vacuum attack!
;jpn: @DSP_ACTOR()の↓
;jpn: すいこみ
;jpn:こうげきだ!
@KEY()
@!

MSG_BTL_ENERGY;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() replenished a↓
  fuel supply!
;jpn: @DSP_ACTOR()は↓
;jpn: エネルギーを ちゅうにゅうした!
@SE(SE_se59_foe_enrgy)
@KEY()
@WI(1)
@!

MSG_BTL_DOKU_KAMITUKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() took a bite↓
  using its poisonous fangs!
;jpn: @DSP_ACTOR()は↓
;jpn: どくのきばで かみついた!
@KEY()
@!

MSG_BTL_YORO_MISSILE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() fired↓
  a missile, making itself dizzy.
;jpn: @DSP_ACTOR()は よろけながら↓
;jpn: ミサイルを はっしゃした!
@SE(SE_se46_b_rocket)
@KEY()
@WI(1)
@!

MSG_BTL_MULTI_ATTACK;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() started a↓
  continuous attack!
;jpn: @DSP_ACTOR()の↓
;jpn: れんぞくこうげき!
@KEY()
@!

MSG_BTL_MIGAMAE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is↓
  on guard.
;jpn: @DSP_ACTOR()は↓
;jpn: みがまえている!
@KEY()
@!

MSG_BTL_FIREBALL;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() spewed out↓
  a flaming fireball!
;jpn: @DSP_ACTOR()は↓
;jpn: まっかな ほのおを ふきだした!
@SE(SE_se4b_foe_burning)
@KEY()
@WI(1)
@!

MSG_BTL_GEKITOTU;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() rushed in,↓
  and intertwined with you!
;jpn: @DSP_ACTOR()は↓
;jpn: からみあいながら つっこんできた!
@KEY()
@!

MSG_BTL_KARATE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() attacked↓
  with a crushing chop!
;jpn: @DSP_ACTOR()は↓
;jpn: はりてチョップを くりだした!
@KEY()
@!

MSG_BTL_TOMOE;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() grappled and used↓
  his submission hold!
;jpn: @DSP_ACTOR()は↓
;jpn: サブミッションを かけてきた!
@KEY()
@!

MSG_BTL_BOUSOU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() revved and accelerated!↓
;jpn: @DSP_ACTOR()は↓
;jpn: ぼうそうした!
@KEY()
@!

MSG_BTL_KNIFE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() brandished↓
  a knife!
;jpn: @DSP_ACTOR()は↓
;jpn: ナイフを ふりまわした!
@KEY()
@!

MSG_BTL_TOSSIN;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() tore↓
  into you!
;jpn: @DSP_ACTOR()が↓
;jpn: とっしんしてきた!
@KEY()
@!

MSG_BTL_KAMITUKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() used a↓
  biting attack!
;jpn: @DSP_ACTOR()の↓
;jpn: かみつきこうげきだ!
@KEY()
@!

MSG_BTL_HIKKAKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() clawed↓
  with @GOSUB(MSG_ESUB_HIS_HER_GACT) sharp nails!
;jpn: @DSP_ACTOR()は↓
;jpn: するどいつめで ひっかいた!
@KEY()
@!

MSG_BTL_SIPPO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() swung↓
  @GOSUB(MSG_ESUB_HIS_HER_GACT) tail very hard!
;jpn: @DSP_ACTOR()は↓
;jpn: しっぽを つよく ふりまわした!
@KEY()
@!

MSG_BTL_NOSHIKAKARI;
;metamorph
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() growled↓
  and lunged forward!
;jpn: @DSP_ACTOR()は↓
;jpn: のしかかりこうげきだ!
; のしかかってきた!
@KEY()
@!

MSG_BTL_KAMIBUKURO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() wielded↓
  a shopping bag!
;jpn: @DSP_ACTOR()は↓
;jpn: かいものぶくろを ふりまわした!
@KEY()
@!

MSG_BTL_KONBOU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() swung↓
  a club!
;jpn: @DSP_ACTOR()は↓
;jpn: こんぼうを ふりまわした!
@KEY()
@!

MSG_BTL_TATUMAKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() generated↓
  a tornado!
;jpn: @DSP_ACTOR()は↓
;jpn: たつまきを おこした!
@SE(SE_se5a_foe_tatumaki)
@KEY()
@!

MSG_BTL_WATER;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() sprayed a gigantic blast of water!↓
;jpn: @DSP_ACTOR()の↓
;jpn: はげしい ほうすいこうげきだ!
@KEY()
@!

MSG_BTL_FUTEKI_SMILE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() flashed↓
  a menacing smile!
;jpn: @DSP_ACTOR()は↓
;jpn: ぞっとするような わらいをうかべた!
@KEY()
@!

MSG_BTL_LOUD_SMILE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() started↓
  laughing hysterically!
;jpn: @DSP_ACTOR()は↓
;jpn: おおごえで わらいだした!
@KEY()
@!

MSG_BTL_NIJIRIYORU;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() edged↓
  closer!
;jpn: @DSP_ACTOR()は↓
;jpn: にじりよってきた!
@KEY()
@!

MSG_BTL_TUBUYAKI1;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() muttered↓
@MESSAGE_SOUND(2)
  ”1...”
@MESSAGE_SOUND(1)
;;jpn: @DSP_ACTOR()は↓
;@MESSAGE_SOUND(2)
;;jpn: 「1‥‥」
;@MESSAGE_SOUND(1)
;;jpn:とつぶやいた。
@KEY()
@!

MSG_BTL_TUBUYAKI2;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() murmured↓
@MESSAGE_SOUND(2)
  ”2...”
@MESSAGE_SOUND(1)
;;jpn: @DSP_ACTOR()は↓
;@MESSAGE_SOUND(2)
;;jpn: 「2‥‥」
;@MESSAGE_SOUND(1)
;;jpn:とつぶやいた。
@KEY()
@!

MSG_BTL_TUBUYAKI3;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() whispered↓
@MESSAGE_SOUND(2)
  ”3...”
@MESSAGE_SOUND(1)
;;jpn: @DSP_ACTOR()は↓
;@MESSAGE_SOUND(2)
;;jpn: 「3‥‥」
;@MESSAGE_SOUND(1)
;;jpn:とつぶやいた。
@KEY()
@!

MSG_BTL_KOROBU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() fell down!
;jpn: @DSP_ACTOR()は↓
;jpn: ころんだ!
@SE(SE_se22_b_hit_miss)
@KEY()
@!

MSG_BTL_BOOTTO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is being↓
  absentminded.
;jpn: @DSP_ACTOR()は↓
;jpn: ぼーっとしている。
@KEY()
@!

MSG_BTL_JYOUKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() generated↓
  a burst of steam!
;jpn: @DSP_ACTOR()は↓
;jpn: はげしく じょうきを はいた!
@KEY()
@!

MSG_BTL_YOROYORO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is↓
  wobbly.
;jpn: @DSP_ACTOR()は↓
;jpn: よろよろしている。
@KEY()
@!

MSG_BTL_FURAFURA;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is↓
  reeling.
;jpn: @DSP_ACTOR()は↓
;jpn: ふらふらしている。
@KEY()
@!

MSG_BTL_NITANITA;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() has↓
  a big grin on @GOSUB(MSG_ESUB_HIS_HER_GACT) face.
;jpn: @DSP_ACTOR()は↓
;jpn: にたにた わらっている!
@KEY()
@!

MSG_BTL_KOKYUU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is taking deep breaths for the next assault.↓
;jpn: @DSP_ACTOR()は ふたりの↓
;jpn: こきゅうを ととのえている。
@KEY()
@!

MSG_BTL_AISATU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() sends↓
  a greeting!
;jpn: @DSP_ACTOR()は↓
;jpn: あいさつを した!
@KEY()
@!

MSG_BTL_UNARI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is↓
  making a loud, piercing howl.
;jpn: @DSP_ACTOR()は↓
;jpn: ひくいうなりごえを あげている。
@KEY()
@!

MSG_BTL_KACHIKACHI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is↓
  saying ”tick−tock.”
;jpn: @DSP_ACTOR()は↓
;jpn: コチコチいっている。
@KEY()
@!

MSG_BTL_MABUSII_HIKARI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() emitted↓
  a glorious light!
;jpn: @DSP_ACTOR()は↓
;jpn: まばゆいひかりを はなった!
@KEY()
@!

MSG_BTL_BIRIBIRI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() used an↓
  electrical shock attack!
;jpn: @DSP_ACTOR()の↓
;jpn: でんきショックこうげきだ!
@KEY()
@!

MSG_BTL_KAFUN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() scattered↓
  its pollen around!
;jpn: @DSP_ACTOR()は↓
;jpn: かふんを まきちらした!
@SE(SE_se52_foe_spore)
@KEY()
@WI(1)
@!

MSG_BTL_COLD_HAND;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() reached out↓
  with its icy hand.
;jpn: @DSP_ACTOR()は↓
;jpn: つめたいてを のばしてきた!
@KEY()
@!

MSG_BTL_POISON_BREATH;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() played↓
  a flute with @GOSUB(MSG_ESUB_HIS_HER_GACT) poisonous breath!
;jpn: @DSP_ACTOR()は↓
;jpn: どくのいきで ふえをふいた!
@KEY()
@!

MSG_BTL_HAIKI_GAS;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() spewed↓
  exhaust fumes!
;jpn: @DSP_ACTOR()は↓
;jpn: はいきガスを まきちらした!
@KEY()
@!

MSG_BTL_LAUGH_HEN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() started↓
  laughing maniacally!
;jpn: @DSP_ACTOR()は↓
;jpn: くるったように おおわらいした!
@KEY()
@!

MSG_BTL_FUE;
←
@SE(SE_se19_b_foe_hitsign)
◆The @DSP_ACTOR() breathed↓
  in through @GOSUB(MSG_ESUB_HIS_HER_GACT) flute!
;jpn: @DSP_ACTOR()は↓
;jpn: ふえを すった!
@KEY()
@!

MSG_BTL_JUMP_TO_FACE;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() leaped↓
  forward and spread its wings!
;jpn: @DSP_ACTOR()は↓
;jpn: はねをひろげて とびかかってきた!
@KEY()
@!

MSG_BTL_CHOU_ONPA;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() became↓
  friendly and affectionate!@KEY()↓
◆You backed off.↓
  still!
;jpn: @DSP_ACTOR()は↓
;jpn: あいそよく なついてきた!↓
;jpn: @DSP_LCNAME()は たちすくんだ!
@KEY()
@!

