;///////////////////////モンスターの特殊攻撃(3/3)////////////////////////

MSG_BTL_JIHIBIKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() made a↓
  loud rumble!
;jpn: @DSP_ACTOR()は↓
;jpn: ものすごい じひびきを たてた!
@KEY()
@!

MSG_BTL_OSAETSUKE;
←
;metamorph prohibited
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() gave you↓
  a great big hug.
;jpn: @DSP_ACTOR()は↓
;jpn: ひしと だきついてきた!
@KEY()
@!

MSG_BTL_CURSE_WORD;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() let loose with↓
  a hacking cough.
;jpn: @DSP_ACTOR()は↓
;jpn: わるいせきをした!
@KEY()
@!

MSG_BTL_JIMI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() used↓
  (his/her/its) misery attack!
;jpn: @DSP_ACTOR()は↓
;jpn: しみったれた こうげきを した!
@KEY()
@!

MSG_BTL_PENKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() utilized a↓
  paint attack!
;jpn: @DSP_ACTOR()の↓
;jpn: ペンキこうげきだ!
@KEY()
@!

MSG_BTL_NAGURI_KAKARI;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() came out↓
  swinging!
;jpn: @DSP_ACTOR()は↓
;jpn: なぐりかかってきた!
;@SE(SE_se1e_b_foe_damage1)
@KEY()
@!

MSG_BTL_CLAW;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() scratched↓
  with its claws!
;jpn: @DSP_ACTOR()は↓
;jpn: ツメで ひっかいた!
@KEY()
@!

MSG_BTL_KUCHIBASHI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() pecked↓
  at your eyes!
;jpn: @DSP_ACTOR()は↓
;jpn: くちばしで つついた!
@KEY()
@!

MSG_BTL_TSUNO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() rammed and trampled you!↓
;jpn: @DSP_ACTOR()の↓
;jpn: つのこうげきだ!
@KEY()
@!

MSG_BTL_PUNCH;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() threw↓
  a punch!
;jpn: @DSP_ACTOR()は↓
;jpn: パンチを くりだした!
@KEY()
@!

MSG_BTL_PUMPKIN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() spit↓
  its pumpkin seeds!
;jpn: @DSP_ACTOR()は↓
;jpn: かぼちゃのたねを ぶつけた!
@KEY()
@!

MSG_BTL_BEAM;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() fired↓
  a beam!
;jpn: @DSP_ACTOR()は↓
;jpn: ビームを はっしゃした!
@SE(SE_se4d_foe_elewave)
@KEY()
@WI(1)
;追加
@!

MSG_BTL_YARI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() jabbed↓
  with a spear!
;jpn: @DSP_ACTOR()は↓
;jpn: やりで つついた!
@KEY()
@!

MSG_BTL_FUMITSUKE;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() stomped↓
  with (his/her/its) huge foot!
;jpn: @DSP_ACTOR()は↓
;jpn: きょだいな あしで ふみつけてきた!
@KEY()
@!

MSG_BTL_FURAFUUPU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() swung↓
  his hula hoop.
;jpn: @DSP_ACTOR()は↓
;jpn: フラフープを ふりまわした!
@SE(SE_se1a_b_my_hit)
@KEY()
@!

MSG_BTL_TAIATARI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() charged↓
  forward!
;jpn: @DSP_ACTOR()は↓
;jpn: たいあたりを ぶちかました!
@KEY()
@!

MSG_BTL_SKATEBOARD;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() shredded↓
  fiercely on a skateboard!
;jpn: @DSP_ACTOR()は↓
;jpn: スケボーにのって とっしんしてきた!
@KEY()
@!

MSG_BTL_KAMITSUKI_DIAMOND;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() bit you↓
  hard!
;jpn: @DSP_ACTOR()は↓
;jpn: かみついた!
@KEY()
@!

MSG_BTL_KUDAMAKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() grumbled↓
  about today’s youth!
;jpn: @DSP_ACTOR()は↓
;jpn: くだを まいた!
@SE(SE_se54_foe_word)
@KEY()
@!

MSG_BTL_SEKKYOU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() started↓
  lecturing you!
;jpn: @DSP_ACTOR()は↓
;jpn: せっきょうを はじめた!
@SE(SE_se54_foe_word)
@KEY()
@!

MSG_BTL_SHIKARITSUKE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() scoweled↓
  sharply!
;jpn: @DSP_ACTOR()は↓
;jpn: ガミガミと しかりつけた!
@SE(SE_se54_foe_word)
@KEY()
@!

MSG_BTL_BAD_SMELL;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() vented↓
  a terrible odor!
;jpn: @DSP_ACTOR()は↓
;jpn: ひどいにおいを まきちらした!
@KEY()
@!

MSG_BTL_LOUD_VOICE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() shouted↓
  in a loud voice!
;jpn: @DSP_ACTOR()は↓
;jpn: おおきなこえを はりあげた!
@KEY()
@!

MSG_BTL_OTAKEBI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() shrieked a warcry!
;jpn: @DSP_ACTOR()は↓
;jpn: おたけびを あげた!
@KEY()
@!

MSG_BTL_FAKE_DEAD;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() knitted↓
  its brow!
;jpn: @DSP_ACTOR()は↓
;jpn: みけんに しわを よせた!
@KEY()
@!

MSG_BTL_YUDAN;
@RAND(3)
@ONGOTO(MSG_BTL_YUDAN_2,MSG_BTL_YUDAN_3,MSG_BTL_YUDAN_4)
@GOTO(MSG_BTL_YUDAN_1)

MSG_BTL_YUDAN_1;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() lost↓
  a gear and some bolts!
;jpn: @DSP_ACTOR()は↓
;jpn: はぐるまを おとした!
@KEY()
@!

MSG_BTL_YUDAN_2;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() re-applied↓
  a bandage!
;jpn: @DSP_ACTOR()は↓
;jpn: ばんそうこうを はりなおした!
@KEY()
@!

MSG_BTL_YUDAN_3;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() cleaned↓
  the area!
;jpn: @DSP_ACTOR()は↓
;jpn: あたりを そうじした!
@KEY()
@!

MSG_BTL_YUDAN_4;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() wanted to go↓
  and get a battery!
;jpn: @DSP_ACTOR()は↓
;jpn: でんちを かいに いこうとした!
@KEY()
@!

MSG_BTL_YUDAN_LIFEUP;＄
←
◆@DSP_ACTOR() ate a↓
  bologne sandwich!
;jpn: @DSP_ACTOR()は↓
;jpn: てまきずしを たべた!
@SE(SE_se44_b_eat)
@KEY()↓
@GOSUB(MSG_BTL_HPMAX_KAIFUKU)
@!


MSG_BTL_NEBIE_BEAM;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() shot a beam↓
  that causes night-time stuffiness!
;jpn: @DSP_ACTOR()は↓
;jpn: ねびえビームを はっしゃした!
@KEY()
@!

MSG_BTL_NEUTRALIZE_SPARKLE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() emitted↓
  a pale green light!
;jpn: @DSP_ACTOR()は↓
;jpn: あおじろい ひかりを はなった!
@KEY()
@!


MSG_BTL_MAKITSUKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() coiled around↓
  you and attacked!
;jpn: @DSP_ACTOR()の↓
;jpn: まきつきこうげきだ!
@KEY()
@!

MSG_BTL_TO_DIAMOND_DOG;
←
◆All of a sudden,@KEY()↓
◆@DSP_ACTOR() gave off↓
  a rainbow of colors!
;jpn: とつぜん!@KEY()↓
;jpn: @DSP_ACTOR()は↓
;jpn: まばゆいひかりを はなった!@KEY()
@SE(SE_se41_b_pk_starstorm2)
@BTLFX(BFX_PSI_FLASH_M,BFX_NULL)
@WI(30)

@SE(SE_se41_b_pk_starstorm2)
@BTLFX(BFX_PSI_FLASH_M,BFX_NULL)
@WI(30)

@SE(SE_se41_b_pk_starstorm2)
@BTLFX(BFX_PSI_FLASH_M,BFX_NULL)
@WI(30)
@!

MSG_BTL_WARP_NEAR;
MSG_BTL_DFSHOWER;
MSG_BTL_2GUTS;
MSG_BTL_HIRU_A;
MSG_BTL_HIRU_B;
MSG_BTL_HIRU_C;
MSG_BTL_HIRU_D;
MSG_BTL_UNPOISON;
MSG_BTL_DFSPRAY;
MSG_BTL_NEUTRALIZER;
MSG_BTL_LIFEUP_C;		<-- これを追加して下さい。
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the↓
  @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()
@!

MSG_BTL_ANTIPSI;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the↓
  @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
;@SE(SE_se45_b_mecha)
@WI(30)
@SE(SE_se36_b_pk_fire3)
@WI(30)
@BTLFX(BFX_NULL,BFX_ANTI_PSI_MACHINE)
@WI(60)
@KEY()
@!

MSG_BTL_HPSUCK;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the↓
  @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
;@SE(SE_se45_b_mecha)
@WI(30)
@SE(SE_se3b_b_pk_freeze4)
@BTLFX(BFX_NULL,BFX_SUCK_MACHINE)
@WI(60)
@KEY()
@!

MSG_BTL_HPSUCKSP;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the↓
  @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
;@SE(SE_se45_b_mecha)
@WI(30)
@SE(SE_se3b_b_pk_freeze4)
@BTLFX(BFX_NULL,BFX_SUCK_MACHINE_SUPER)
@WI(60)
@KEY()
@!

MSG_BTL_SHIELDKILL;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the↓
  @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
;@SE(SE_se45_b_mecha)
@WI(30)
@SE(SE_se63_teleport_appear)
@BTLFX(BFX_NULL,BFX_SHIELD_KILLER)
@WI(60)
;@SE(SE_se5a_foe_tatumaki)
@KEY()
@!

MSG_BTL_BAD_SMELL_GAS;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() discharged↓
  a very stinky gas!
;jpn: @DSP_ACTOR()は↓
;jpn: とてもくさいガスを まきちらした!
@!

MSG_BTL_LIGHTNING;●(akm0616 w/itoi)
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
;@OPEN(14)	←三浦兄による修正
@CLS()
◆You cannot grasp the true form↓
  of @DSP_ACTOR()’s attack!
;jpn: @DSP_ACTOR()からのこうげきの↓
;jpn: しょうたいが つかめない!
@BTLFX(BFX_SHAKE_WINDOW,BFX_NULL)
@BTLFX(BFX_GG_UNKNOWN,BFX_NULL)
@SE(SE_se51_foe_haku)
@WI(40)
@SE(SE_se51_foe_haku)
@!

MSG_BTL_LIGHTNING_B;＠
@GOSUB(MSG_BTL_GYIYYIG_TALK_A)
@CLS()
◆You cannot grasp the true form↓
  of @DSP_ACTOR()’s attack!
;jpn: @DSP_ACTOR()からのこうげきの↓
;jpn: しょうたいが つかめない!
@BTLFX(BFX_SHAKE_WINDOW,BFX_NULL)
@BTLFX(BFX_GG_UNKNOWN,BFX_NULL)
@SE(SE_se51_foe_haku)
@WI(40)
@SE(SE_se51_foe_haku)
@!

MSG_BTL_LIGHTNING_C
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
@CLS()
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
@CLS()
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
@CLS()
◆You cannot grasp the true form↓
  of @DSP_ACTOR()’s attack!
;jpn: @DSP_ACTOR()からのこうげきの↓
;jpn: しょうたいが つかめない!
@BTLFX(BFX_SHAKE_WINDOW,BFX_NULL)
@BTLFX(BFX_GG_UNKNOWN,BFX_NULL)
@SE(SE_se51_foe_haku)
@WI(40)
@SE(SE_se51_foe_haku)
@!

MSG_BTL_GYIYYIG_3
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
@CLS()
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
@CLS()
@GOSUB(MSG_BTL_GYIYYIG);＠ギーグの声ランダムで
@WI(40)
@CLS()
@!

