;///////////////////////モンスターの特殊攻撃(1/3)////////////////////////

;#仲間を呼ぶ
MSG_BTL_NAKAMA0;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() called↓
  for help!
;jpn: @DSP_ACTOR()は↓
;jpn: おうえんを よんだ!
@SE(SE_se48_foe_friend_call)
@KEY()
;@WI(1)
@!

;#種を巻く
MSG_BTL_TANEMAKI0;
@SE(SE_se19_b_foe_hitsign)
←
◆@DSP_ACTOR() sowed↓
  some seeds around itself!
;jpn: @DSP_ACTOR()は じぶんのまわりに↓
;jpn: たねを まいた!
@SE(SE_se48_foe_friend_call)
@KEY()
;@WI(1)
@!

;#爆発する
MSG_BTL_EXPLOSION;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() exploded↓
  into bits!
;jpn: @DSP_ACTOR()は↓
;jpn: だいばくはつを おこした!
@SE(SE_se5b)
@KEY()
@WI(30)
@!

MSG_BTL_BURN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() burst↓
  into flames!
;jpn: @DSP_ACTOR()は↓
;jpn: はげしく もえあがった!
@SE(SE_se4b_foe_burning)
@KEY()
@WI(30)
@!

MSG_BTL_GOODS;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は どさくさにまぎれて↓
@GET_CITEM()
@FALSE_GOTO(_BTL_GOODS_FAILED)
@XCHG()
 stole a @DSP_GOODS(0)@KEY()↓↓
◆in the confusion of the battle!
;jpn: @DSP_GOODS(0)を ぬすんだ!
@KEY()
@!

_BTL_GOODS_FAILED;
 tried to↓
  steal something, but failed!
;jpn: なにか ぬすもうとしたが↓
;jpn: しっぱいした!
@KEY()
@!

MSG_BTL_TIMESTOP;
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() froze↓
  you in time!
;jpn: @DSP_ACTOR()は↓
;jpn: @DSP_LCNAME()の じかんをとめた!
@BGMSTART(0,BGM_non)
@KEY()
@WI(1)
@!

MSG_BTL_MANAZASHI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() glared↓
  with its eerie eyes!
;jpn: @DSP_ACTOR()は↓
;jpn: ぶきみなめで にらみつけた!
@KEY()
@WI(1)
@!

MSG_BTL_KAIDENPA;
@SE(SE_se19_b_foe_hitsign)
←
◆@DSP_ACTOR() generated↓
  a mysterious electric field!
;jpn: @DSP_ACTOR()は↓
;jpn: かいでんぱを とばした!
@SE(SE_se4d_foe_elewave)
@KEY()
@WI(1)
@!

MSG_BTL_YORO_KAIDENPA;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() stumbled, but fired a ↓
  strange beam.
;jpn: @DSP_ACTOR()は よろけながら↓
;jpn: かいこうせんを はっしゃした!
@SE(SE_se4d_foe_elewave)
@KEY()
@WI(1)
@!

MSG_BTL_GEPPU_IKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() burped↓
  and blew his nauseating breath at you!
;jpn: @DSP_ACTOR()は↓
;jpn: とんでもなくくさい いきをはきかけた!
@SE(SE_se4e_foe_gepu)
@KEY()
@WI(1)
@!

MSG_BTL_DOKUBARI;
;metamorph
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() stung↓
  with its poison stinger!
;jpn: @DSP_ACTOR()は↓
;jpn: どくばりを つきさした!
; どくばりを つきさしてきた!
@KEY()
@WI(1)
@!

MSG_BTL_DEATH_KISS;
;metamorph
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() gave↓
  the kiss of death!
;jpn: @DSP_ACTOR()は↓
;jpn: しのくちずけを した!
; しのくちずけを してきた!
@KEY()
@WI(1)
@!

MSG_BTL_TUMETAI_IKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() exhaled↓
  @GOSUB(MSG_ESUB_HIS_HER_GACT) arctic−cold breath!
;jpn: @DSP_ACTOR()は↓
;jpn: ひえびえとする いきを はきかけた!
@SE(SE_se51_foe_haku)
@KEY()
@WI(1)
@!

MSG_BTL_HOUSHI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() scattered↓
  some spores!
;jpn: @DSP_ACTOR()は↓
;jpn: ほうしを ばらまいた!
@SE(SE_se52_foe_spore)
@KEY()
@WI(1)
@!

MSG_BTL_TORITUKI;tried toでよかった。(三浦)
;metamorph prohibited
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() tried to possess you↓
  in a frightening manner.
;jpn: @DSP_ACTOR()は↓
;jpn: いやらしく とりついてきた!
@SE(SE_se60_monster_appear)
@KEY()
@WI(1)
@!

MSG_BTL_YOI_KAORI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() sprinkled↓
  around some wonderful−smelling powder.
;(,it makes you feel entranced!)
;jpn: @DSP_ACTOR()は↓
;jpn: ウットリするかおりの こなを ふりまいた!
@SE(SE_se52_foe_spore)
@KEY()
@WI(1)
@!

MSG_BTL_KABI_HOUSI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() scattered↓
  some mold spores!
;jpn: @DSP_ACTOR()は↓
;jpn: カビの ほうしを まきちらした!
@SE(SE_se52_foe_spore)
@KEY()
@WI(1)
@!

MSG_BTL_SHIBARI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() employed a↓
  binding attack!
;jpn: @DSP_ACTOR()の↓
;jpn: しばりこうげきだ!
@KEY()
@WI(1)
@!

MSG_BTL_NENEKI;
;metamorph
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() spit out
  a sticky mucus!
;jpn: @DSP_ACTOR()は↓
;jpn: ねんえきを はきかけた!
; ねんえきを はきかけてきた!
@SE(SE_se51_foe_haku)
@KEY()
@WI(1)
@!

MSG_BTL_HAEMITU;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() spewed↓
  ”Fly Honey” out of his mouth!
;jpn: @DSP_ACTOR()は くちから↓
;jpn: はえみつを ふきだした!
@SE(SE_se51_foe_haku)
@KEY()
@WI(1)
@!

;MSG_BTL_G_HAEMITU;用途不明削除(三浦)
;◆(It’s $dummy. The label is G HAEMITU.)
;;jpn:◆($ダミーです。↓
;;jpn:  ラベルは↓
;  G HAEMITU)
;@KEY()
;@!

MSG_BTL_OSHIRI_ITO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() shot↓
  spider silk out of its body!
;jpn: @DSP_ACTOR()は↓
;jpn: おしりから いとを はきだした!
@KEY()
@!

MSG_BTL_KOWAI_KOTOBA;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() said something really↓
  scary!
;jpn: @DSP_ACTOR()は↓
;jpn: こわいことばを なげつけた!
@SE(SE_se54_foe_word)
@KEY()
@WI(1)
@!

MSG_BTL_AYASHI_KOTO;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() did↓
  something very mysterious!
;jpn: @DSP_ACTOR()は↓
;jpn: なにやら あやしいことをした!
@SE(SE_se55_foe_ayashii)
@KEY()
@WI(1)
@!

MSG_BTL_FUUIN;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() disrupted↓
  your senses!
;jpn: @DSP_ACTOR()は↓
;jpn: いしきを かきみだした!
@KEY()
@!

MSG_BTL_TACHIBA_THINK;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() is↓
  sizing up the situation!
;jpn: @DSP_ACTOR()は↓
;jpn: たちばを かんがえている!
@KEY()
@!

MSG_BTL_KOGEPPU_IKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() exhaled↓
  a blast of stinky breath!
;jpn: @DSP_ACTOR()は↓
;jpn: くさいいきを はきかけた!
@SE(SE_se5c)
@KEY()
@WI(1)
@!

MSG_BTL_TYPHOON;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() summoned↓
  a storm!
;jpn: @DSP_ACTOR()は↓
;jpn: あらしを よびよせた!
@SE(SE_se56_foe_typhoon)
@KEY()
@WI(1)
@!

MSG_BTL_COFFEE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() spilled↓
  some scalding hot espresso!
;jpn: @DSP_ACTOR()は↓
;jpn: あついコーヒーを こぼした!
@KEY()
@!

MSG_BTL_MUSIC;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() played↓
  a haunting melody!
;jpn: @DSP_ACTOR()は↓
;jpn: ふしぎなきょくを えんそうした!
;@SE(SE_se57_foe_ferformance)
;コントロールコードによってBGMをおかしくする。未設定?(三浦)
@KEY()
@WI(1)
@!

MSG_BTL_SYOUKA_EKI;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() dispensed an↓
  extinguishing blast!
;jpn: @DSP_ACTOR()は↓
;jpn: しょうかえきを ふきだした!
@SE(SE_se58_foe_fire_water)
@KEY()
@WI(1)
@!

MSG_BTL_KAMINARI;γ
;metamorph
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() used a↓
  Crashing Boom Bang attack!
;jpn: @DSP_ACTOR()の↓
;jpn: バチバチこうげきだ!
@KEY()
@!

MSG_BTL_FIRE;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() shot out↓
  a spray of fire!
;jpn: @DSP_ACTOR()は↓
;jpn: あたりを ひのうみにした!
@SE(SE_se4b_foe_burning)
@KEY()
@WI(1)
@!

MSG_BTL_FIRE_BREATH;
←
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR() breathed↓
  fire!
;jpn: @DSP_ACTOR()は↓
;jpn: ひを ふいた!
@SE(SE_se4b_foe_burning)
@KEY()
@WI(1)
@!

