
;PSI説明
;=======

;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;制限事項は以下のように記述してあります。(三浦兄95.03.17)
;___must be fit in 1 line___
;___must be fit in 2 line___
;___must be fit in 4 line___
;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


; 1PK(ひっさつ)α
;akm
MSG_EXPL_PSI_HISSATSU_ALFA;marcus
@GOSUB(_PSI_HISSATSU)
;akm◆Psychokinesis wave by mind consentration

;akm  Each enemy took about 50 points of damage. 

 each enemy about 50 points of damage.

;jpn: てきぜんいんに↓
;jpn: やく50ポイントずつ ダメージをあたえる。
@!

; 2PK(ひっさつ)β
;akm
MSG_EXPL_PSI_HISSATSU_BETA;marcus
@GOSUB(_PSI_HISSATSU)
;akm Each enemy took about about 180 points of damage.

 each enemy about 180 points of damage.

;jpn:  てきぜんいんに↓
;jpn: やく180ポイントずつ ダメージをあたえる。
@!

; 3PK(ひっさつ)γ
;akm
MSG_EXPL_PSI_HISSATSU_GAMMA;marcus
@GOSUB(_PSI_HISSATSU)
;akm  Each enemy took about 50 points of damage.

 each enemy about 320 points of damage.

;jpn: てきぜんいんに↓
;jpn: やく320ポイントずつ ダメージをあたえる。
@!

; 4PK(ひっさつ)Ω
;akm
MSG_EXPL_PSI_HISSATSU_OMEGA;marcus
@GOSUB(_PSI_HISSATSU)
;akm  Each enemy took about 640 points of damage.

 each enemy about 640 points of damage.

;jpn: てきぜんいんに↓
;jpn: やく640ポイントずつ ダメージをあたえる。
@!

; 5PKファイアーα
;akm
MSG_EXPL_PSI_FIRE_ALFA;marcus 
@GOSUB(_PSI_FIRE)
;akm  Each target took about 80 points of damage.

 about 80 points of damage each.

;jpn: それぞれ やく80ポイントのダメージを あたえる。
@!

; 6PKファイアーβ
;akm
MSG_EXPL_PSI_FIRE_BETA;marcus 
@GOSUB(_PSI_FIRE)
;akm  Gave each target about 80 points of damage.

 about 160 points of damage each.

;jpn: それぞれ やく160ポイントのダメージを あたえる。
@!

; 7PKファイアーγ
;akm
MSG_EXPL_PSI_FIRE_GAMMA;marcus
@GOSUB(_PSI_FIRE)
;akm  Gave each target about 240 points of damage.

 about 240 points of damage each.

;jpn: それぞれ やく240ポイントのダメージを あたえる。
@!

; 8PKファイアーΩ
;akm
MSG_EXPL_PSI_FIRE_OMEGA;marcus
@GOSUB(_PSI_FIRE)
;akm  Gave each target about 320 points of damage.

 about 320 points of damage each.

;jpn: それぞれ やく320ポイントのダメージを あたえる。
@!

; 9PKフリーズα
;akm!
MSG_EXPL_PSI_FREEZ_ALFA; marcus
@GOSUB(_PSI_FREEZ)
;akm  Inflicted about 180 points of damage.↓

 inflicting about 180 points of damage.↓

;jpn: やく180ポイントのダメージを あたえる。↓
@GOSUB(_PSI_FREEZ_2)←
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!

;10 PKフリーズβ
;akm!
MSG_EXPL_PSI_FREEZ_BETA;marcus 
@GOSUB(_PSI_FREEZ)
;akm  Inflicted about 360 points of damage.↓

 inflicting about 360 points of damage.↓

;jpn: やく360ポイントのダメージを あたえる。↓
@GOSUB(_PSI_FREEZ_2)←
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!

;11 PKフリーズγ
;akm!
MSG_EXPL_PSI_FREEZ_GAMMA;marcus
@GOSUB(_PSI_FREEZ)
;akm  Inflicted about 540 points of damage.↓

 inflicting about 540 points of damage.↓

;jpn: やく540ポイントのダメージを あたえる。↓
@GOSUB(_PSI_FREEZ_2)←
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!
 
;12 PKフリーズΩ
;akm!
MSG_EXPL_PSI_FREEZ_OMEGA;marcus
@GOSUB(_PSI_FREEZ)
;akm  Inflicted about 720 points of damage.↓

 inflicting about 720 points of damage.↓

;jpn: やく720ポイントのダメージを あたえる。↓
@GOSUB(_PSI_FREEZ_2)↓
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!

;13 PKサンダーα
;akm!
MSG_EXPL_PSI_THUNDER_ALFA;marcus
◆The enemy is thunder struck for about 120 points of damage.↓

;jpn:◆ダメージ やく120ポイントの↓
;jpn: かみなりを おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;14 PKサンダーβ
;akm!
MSG_EXPL_PSI_THUNDER_BETA;marcus
;akm◆Thunder struck for about 120 points of damage.↓

◆The enemy is thunder struck for about 120 points of damage two separate times.↓

;jpn:◆ダメージ やく120ポイントの↓
;jpn: かみなりを 2はつ おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;15 PKサンダーγ
;akm!
MSG_EXPL_PSI_THUNDER_GAMMA;marcus
;akm◆The enemy is thunder struck for about 200 points of damage.↓

◆The enemy is thunder struck for about 200 points of damage three separate times.↓

;jpn:◆ダメージ やく200ポイントの↓
;jpn: かみなりを 3ぱつ おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;16 PKサンダーΩ
;akm!
MSG_EXPL_PSI_THUNDER_OMEGA;
;akm◆Thunder struck for about 200 points of damage.↓

◆The enemy is thunder struck for about 200 points of damage four separate times.↓

;jpn:◆ダメージ やく200ポイントの↓
;jpn: かみなりを 4ぱつ おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;PKフラッシュ
;--------------------------------------------------------------
;アルファ                7/8 涙止まらず                  1/8 変
;ベータ  1/8 気絶        5/8 涙止まらず  1/8 しびれ      1/8 変
;ガンマ  2/8 気絶        4/8 涙止まらず  1/8 しびれ      1/8 変
;オメガ  3/8 気絶        3/8 涙止まらず  1/8 しびれ      1/8 変

;17 PKフラッシュα
;akm!
MSG_EXPL_PSI_FLASH_ALFA;marcus
@GOSUB(_PSI_FLUSH_1)
@GOSUB(_PSI_FLUSH_2)
;akm◆In certain circumstances, it makes an object ”unusual.”

, in some circumstances, feel strange.

;jpn:◆「へん」にすることも まれに ある。
@!

;18 PKフラッシュβ
;akm!
MSG_EXPL_PSI_FLASH_BETA;marcus
@GOSUB(_PSI_FLUSH_1)
@GOSUB(_PSI_FLUSH_2)
;akm◆Otherwise, it makes an object ”unusual,” ”numbed” or destroys it with a single strike.

, and in some circumstances, can make the enemy feel strange, become numb, or even be destroyed.

;jpn:◆そのほかにも 「へん」にしたり 「しびれ」させたり↓
;jpn: いちげきで たおすことも ある。
@!

;19 PKフラッシュγ
;akm!
MSG_EXPL_PSI_FLASH_GAMMA;marcus
@GOSUB(_PSI_FLUSH_1)
@GOSUB(_PSI_FLUSH_2)
;akm◆Often, it will destroy an object with a single strike. 

.↓
◆Often, it will destroy an enemy in a single strike.

;jpn:◆いちげきで たおすことも かなりある。
@!

;20 PKフラッシュΩ
;akm!
MSG_EXPL_PSI_FLASH_OMEGA;marcus
◆It generates glorious rays that have a high probability of destroying all the enemies on the scene in a single strike.

;jpn:◆はげしいひかりを はなち↓
;jpn: てきぜんいんを かなりの かくりつで↓
;jpn: いちげきで たおすことが できる。
@!

;21 PKスターストームα
;akm
MSG_EXPL_PSI_STARSTOM_ALFA; marcus
@GOSUB(_PSI_STARSTORM_1)←
;akm◆It deals about 360 points of damage to each enemy.

◆It deals about 360 points of damage to each enemy.

;jpn:◆てきぜんいんに↓
;jpn: やく360ポイントずつ ダメージをあたえる。
@!

;22 PKスターストームΩ
;akm
MSG_EXPL_PSI_STARSTORM_OMEGA;marcus
@GOSUB(_PSI_STARSTORM_1)←
;akm◆Deals about 720 points of damage to each enemy.

◆It deals about 720 points of damage to each enemy.

;jpn:◆てきぜんいんに↓
;jpn: やく720ポイントずつ ダメージをあたえる。
@!

;23 ライフアップα
;akm
MSG_EXPL_PSI_LIFEUP_ALFA;
;akm◆Restores 100 HP for a friend.

◆Restores 100 HP to one person.

;jpn:◆なかまひとりのHPを↓
;jpn: やく100ポイント かいふくする。
@!

;24 ライフアップβ
;akm
MSG_EXPL_PSI_LIFEUP_BETA;marcus
◆Restores 300 HP to one person.

;jpn:◆なかまひとりのHPを↓
;jpn: やく300ポイント かいふくする。
@!

;25 ライフアップγ
;akm
MSG_EXPL_PSI_LIFEUP_GAMMA;marcus
◆Completely restores the HP of one person.

;jpn:◆なかまひとりのHPを↓
;jpn: かんぜんに かいふくする。
@!

;26 ライフアップΩ
;akm
MSG_EXPL_PSI_LIFEUP_OMEGA;marcus
◆Restores 400 HP to everyone.

;jpn:◆なかまぜんいんのHPを↓
;jpn: やく400ずつ かいふくする。
@!

;27 ヒーリングα
;akm
MSG_EXPL_PSI_HEALING_ALFA;marcus
◆Cures a cold, sunstroke or sleep conditions.

;jpn:◆なかまの「かぜ」「にっしゃびょう」↓
;jpn: 「ねむり」じょうたいを かいふくする。
@!

;28 ヒーリングβ
;akm
MSG_EXPL_PSI_HEALING_BETA;marcus
◆In addition to the effects of Healing α, this cures poisonings, nausea, feeling strange and uncontrollable crying.

;jpn:◆ヒーリングαのこうかにくわえ↓
;jpn: 「どく」「きもちわるい」「へん」↓
;jpn: 「なみだがとまらない」じょうたいを かいふくする。
@!

;29 ヒーリングγ
;akm
MSG_EXPL_PSI_HEALING_GAMMA;marcus
◆In addition to the effects of Healing β, this cures being diamondized and paralysis.↓
◆It also revives a friend who has become unconscious, though HP is not maxed out.

;jpn:◆ヒーリングβのこうかにくわえ↓
;jpn: 「ダイヤ」「しびれ」じょうたいを かいふくする。↓
;jpn:◆「きぜつ」しているなかまを カムバックさせる↓
;jpn: こともあるが そのときHPは まんタンに ならない。
@!

;30 ヒーリングΩ
;akm
MSG_EXPL_PSI_HEALING_OMEGA;marcus
◆In addition to the effects of Healing γ, this revives a friend who has become unconscious, and it completely maxes out that person’s HP when revived.

;jpn:◆ヒーリングγのこうかにくわえ↓
;jpn: 「きぜつ」しているなかまを かくじつに↓
;jpn: HPまんタンで カムバックさせる。
@!

;31 シールドα
;akm
MSG_EXPL_PSI_SHIELD_ALFA;marcus
◆Protect one person with the shield of light.↓
◆It reduces the damage caused by an enemy’s attack by 50%.↓
;akm◆However, the effect will be lost if another shield is put on over it.↓

◆Using a different shield will cancel these effects.
 
;jpn:◆なかまひとりに「ひかりのシールド」をかける。↓
;jpn:◆てきからうける だげきこうげきのダメージが↓
;jpn: はんぶんになる。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆なかまひとりに「シールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE)
;@!

;33 シールドΣ
;akm
MSG_EXPL_PSI_SHIELD_SIGMA;marcus
◆Protect everyone with the shield of light.↓
◆It reduces the damage caused by an enemy’s attack by 50%.↓
;akm◆However, the effect will be lost if another shield is put on over it.

◆Using a different shield will cancel these effects.


;jpn:◆みかたぜんいんに「ひかりのシールド」をかける。↓
;jpn:◆てきからうける だげきこうげきのダメージが↓
;jpn: はんぶんになる。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆みかたぜんいんに「シールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE)
;@!

;32 シールドβ
;akm
MSG_EXPL_PSI_SHIELD_BETA;marcus
◆Protects one person with a power shield.↓

◆Cuts damage in half and some of the blocked damage is dealt back to the enemy.↓

◆Using a different shield will cancel these effects.

;jpn:◆なかまひとりに「はんげきのシールド」をかける。↓
;jpn:◆だげきこうげきのダメージが↓
;jpn: はんぶんになり のこりを はねかえす。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆なかまひとりに「パワーシールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE_REPEL)
;@!

;34 シールドΩ
;akm
MSG_EXPL_PSI_SHIELD_OMEGA;marcus
◆Protects everyone with a power shield.↓

;akm◆It reduces the damage caused by the enemy’s attack by 50% and returns the rest to attacker.↓

◆Cuts damage in half and some of the blocked damage is dealt back to the enemy.↓

;akm◆However, the effect will be lost if another shield is put on over it.

◆Using a different shield will cancel these effects.


;jpn:◆みかたぜんいんに「はんげきのシールド」をかける。↓
;jpn:◆だげきこうげきのダメージが↓
;jpn: はんぶんになり のこりを はねかえす。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆みかたぜんいんに「パワーシールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE_REPEL)
;@!

;35 サイコシールドα
;akm
MSG_EXPL_PSI_P_SHIELD_ALFA;marcus
◆Protects one person with a psychic shield.↓
◆It blocks an enemy’s PSI attack.↓

;akm◆However, the effect will be lost if another shield is put on over it.

◆Using a different shield will cancel these effects.

;jpn:◆みかたひとりに「サイコシールド」をかける。↓
;jpn:◆てきからうける PSIこうげきを↓
;jpn: むこうにする。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆みかたひとりに「サイコシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_HALVE)
;@!

;36 サイコシールドΣ
;akm
MSG_EXPL_PSI_P_SHIELD_SIGMA;marcus
◆Protects everyone with a psychic shield.↓

◆It blocks an enemy’s PSI attack.↓

;akm◆However, the effect will be lost if another shield is put on over it.

◆Using a different shield will cancel these effects.

;jpn:◆みかたぜんいんに「サイコシールド」をかける。↓
;jpn:◆てきからうける PSIこうげきを↓
;jpn: むこうにする。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆みかたぜんいんに「サイコシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_HALVE)
;@!

;37 サイコシールドβ
;akm
MSG_EXPL_PSI_P_SHIELD_BETA;marcus
◆Protects one person with a psychic power shield.↓
◆It reflects an enemy’s PSI attack back at the attacker.↓
◆Using a different shield will cancel these effects.

;akm◆However, the effect will be lost if another shield is put on over it.

;jpn:◆みかたひとりに「はんげきのサイコシールド」をかける。↓
;jpn:◆てきからうける PSIこうげきを↓
;jpn: そのままはねかえす。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆みかたひとりに「サイパワーシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_REPEL)
;@!

;38 サイコシールドΩ
;akm
MSG_EXPL_PSI_P_SHIELD_OMEGA;marcus
◆Protects everyone with a psychic power shield.↓
◆It reflects an enemy’s PSI attack back at the attacker.↓
◆Using a different shield will cancel these effects.


;akm◆However, the effect will be lost if another shield is put on over it.

;jpn:◆みかたぜんいんに「はんげきのサイコシールド」をかける。↓
;jpn:◆てきからうける PSIこうげきを↓
;jpn: そのままはねかえす。↓
;jpn:◆べつのシールドをかけると うちけされてしまう。
@!
;◆みかたぜんいんに「サイパワーシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_REPEL)
;@!

;39 オフェンスアップα
;akm
MSG_EXPL_PSI_OFFENSE_UP_ALFA;marcus
◆Increase one person’s Offense for the duration of the current battle.↓

;jpn:◆みかたひとりの こうげきりょくを↓
;jpn: せんとうじにかぎって アップする。↓
@GOSUB(_PSI_USE_PILE)
@!

;40 オフェンスアップΩ
;akm
MSG_EXPL_PSI_OFFENSE_UP_OMEGA;marcus
◆Increase everyone’s Offense for the duration of the current battle.↓

;jpn:◆みかたぜんいんの こうげきりょくを↓
;jpn: せんとうじにかぎって アップする。↓
@GOSUB(_PSI_USE_PILE)
@!

;41 ディフェンスダウンα
;akm
MSG_EXPL_PSI_DEFENSE_DOWN_ALFA;marcus
◆Decreases the Defense of one enemy for the duration of the current battle.↓

;jpn:◆てきひとりの しゅびりょくを↓
;jpn: せんとうじにかぎって ダウンさせる。↓
@GOSUB(_PSI_USE_PILE)
@!

;42 ディフェンスダウンΩ
;akm
MSG_EXPL_PSI_DEFENSE_DOWN_OMEGA;
◆Decreases the Defense of all enemies for the duration of the current battle.↓

;jpn:◆てきぜんいんの しゅびりょくを↓
;jpn: せんとうじにかぎって ダウンさせる。↓
@GOSUB(_PSI_USE_PILE)
@!

;43 さいみんじゅつα
;akm
MSG_EXPL_PSI_SAIMIN_ALFA;marcus
◆Puts one enemy to sleep.↓
 
;jpn:◆てきひとりを ねむらせる。↓
@GOSUB(_PSI_SAIMIN_SUPPLEMENT)
@!

;44 さいみんじゅつΩ
;akm
MSG_EXPL_PSI_SAIMIN_OMEGA;
◆Puts all of the enemies to sleep.↓

;jpn:◆てきぜんいんを ねむらせる。↓
@GOSUB(_PSI_SAIMIN_SUPPLEMENT)
@!

;45 サイマグネットα
;akm
MSG_EXPL_PSI_P_MAGNET_ALFA;marcus
;akm◆One of the enemy’s PP

◆Grabs 2−8 points of PP from one enemy and adds it to your own.

;jpn:◆てきひとりの PPを↓
;akm@GOSUB(_PSI_PSI_MAGNET_BASIC)
@!

;46 サイマグネットΩ
;akm
MSG_EXPL_PSI_P_MAGNET_OMEGA;marcus
;akm◆Each enemy’s PP 

◆Grabs 2−8 points of PP from each enemy and adds it to your own.

;jpn:◆てきぜんいんの PPを↓
;jpn: それぞれ@GOSUB(_PSI_PSI_MAGNET_BASIC)
@!

;47 パラライシスα
;akm
MSG_EXPL_PSI_PARALYSIS_ALFA;marcus
◆Forces one enemy into
;jpn:◆てきひとりを↓
@GOSUB(_PSI_PARALYSIS_BASIC)
@!

;48 パラライシスΩ
;akm
MSG_EXPL_PSI_PARALYSIS_OMEGA;marcus
◆Forces all enemies into
;jpn:◆てきぜんいんを↓
@GOSUB(_PSI_PARALYSIS_BASIC)
@!

;49 ブレインショックα
;akm
MSG_EXPL_PSI_BRAIN_SHOCK_ALFA;marcus
◆Makes one enemy feels strange.

;jpn:◆てきひとりを
;@GOSUB(_PSI_BRAIN_SHOCK_BASIC)
@!

;50 ブレインショックΩ
;akm
MSG_EXPL_PSI_BRAIN_SHOCK_OMEGA;marcus
◆Makes all of the enemies feel strange.

;jpn:◆てきぜんいんを
;@GOSUB(_PSI_BRAIN_SHOCK_BASIC)
@!

;51 テレポートα
;akm
MSG_EXPL_PSI_TELEPORT_ALFA;marcus
@GOSUB(_PSI_TELEPORT_BASIC)←
◆You need a good running approach for this to work.

;jpn:◆ながいじょそうが ひつようだ。
@!

;52 テレポートβ
;akm
MSG_EXPL_PSI_TELEPORT_BETA;
@GOSUB(_PSI_TELEPORT_BASIC)←
◆You don’t need a running approach to use this.↓
◆It is also called the ”Tornado Teleport.”

;jpn:◆ながいじょそうは いらない。↓
;jpn:◆「たつまきテレポート」ともいう。
@!


