;akimiura

;グッズ説明
;==========

;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;制限事項は以下のように記述してあります。(三浦兄95.03.17)
;___must be fit in 1 line___
;___meaning not match___
;___checking by mr. marcus necessary___
;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

;1フランクリンバッチ
;akm
MSG_EXPL_GDS_FRANKLIN_BADGE;marcus
←
◆By keeping it as one of your items,@KEY()↓
◆it deflects a lightning attack back at the attacker.

;jpn:◆グッズとして↓
;jpn: もっているだけで@KEY()↓
;jpn:◆かみなりこうげきを↓
;jpn: はねかえす。
@KEYNP()
@!

;2ぬいぐるみ
;akm
MSG_EXPL_GDS_NUIGURUMI;
←
◆@GOSUB(_GDS_NUIGURUMI)
@KEYNP()
@!

;3つよいぬいぐるみ
;akm
MSG_EXPL_GDS_NUIGURUMI_SUPER;
←
;◆Very 
@GOSUB(_GDS_NUIGURUMI)

;jpn:◆とても@GOSUB(_GDS_NUIGURUMI)
@KEYNP()
@!

;4こわれたきかい
;akm
MSG_EXPL_GDS_BROKEN_GADGET;marcus
←
◆There’s no way of knowing its original use.@KEY()↓
◆It’s just some kind of broken gadget.@KEY()↓

;jpn:◆もとはなんだか↓
;jpn: わからないが↓
;jpn: こわれたきかいだ。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;5こわれたメカ
;akm
MSG_EXPL_GDS_BROKEN_MECHANISM;
←
◆There’s no way of knowing its original use.@KEY()↓
◆It’s just some kind of broken mechanism.@KEY()↓

;jpn:◆もとはなんだか↓
;jpn: わからないが↓
;jpn: こわれたメカだ。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;6こわれたエアガン
;akm
MSG_EXPL_GDS_BROKEN_AIRGUN;
←
◆A broken air gun.@KEY()↓

;jpn:◆こわれている↓
;jpn: エアガン。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;7こわれたスプレー
;akm
MSG_EXPL_GDS_BROKEN_SPRAY;
←
◆A broken spray can.@KEY()↓

;jpn:◆こわれている↓
;jpn: スプレーかん。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;8こわれたレーザー
;akm
MSG_EXPL_GDS_BROKEN_LASER;
←
◆A broken laser gun.@KEY()↓

;jpn:◆こわれている↓
;jpn: レーザーほう。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;9こわれたアイロン
;akm
MSG_EXPL_GDS_BROKEN_GARAKUTA;marcus
←
◆A contraption that looks like an iron.@KEY()↓

;jpn:◆アイロンのような かたちをした↓
;jpn: きかい。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;10 こわれたすいどうかん
;akm
MSG_EXPL_GDS_BROKEN_KINZOKUBO;marcus
←
◆It looks like a busted water pipe.@KEY()↓

;jpn:◆こわれている↓
;jpn: すいどうかんのような メカ。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;11 こわれたビームほう
;akm
MSG_EXPL_GDS_BROKEN_BEAM;
←
◆A broken beam cannon.@KEY()↓

;jpn:◆こわれている↓
;jpn: ビームほう。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;12 こわれたつつ
;akm
MSG_EXPL_GDS_BROKEN_TSUTSU;marcus
←
◆A broken tube−shaped item.@KEY()↓

;jpn:◆こわれている↓
;jpn: つつがたの メカ。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;13 こわれたバズーカ
;akm
MSG_EXPL_GDS_BROKEN_BAZOOKA;
←
◆A broken bazooka.@KEY()↓

;jpn:◆こわれている↓
;jpn: バズーカほう。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;14 こわれたラッパ
;akm
MSG_EXPL_GDS_BROKEN_RAPPA;
←
◆A broken apparatus that is shaped like a trumpet.@KEY()↓

;jpn:◆ラッパのような かたちの↓
;jpn: こわれている きかい。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;15 こわれたハーモニカ
;akm
MSG_EXPL_GDS_BROKEN_TESUKZ;
←
◆A broken device that looks like a harmonica.@KEY()↓

;jpn:◆ハーモニカのように みえる↓
;jpn: こわれた きかい。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;16こわれたパラボラ
;akm
MSG_EXPL_GDS_BROKEN_PARABPLA;marcus
←
◆A piece of broken equipment that looks like a satellite dish.@KEY()↓

;jpn:◆パラボラアンテナに にた↓
;jpn: こわれた きかい。@KEY()↓
@GOSUB(_GDS_JEFF_REPAIR)
@KEYNP()
@!

;17 ボロのバット
;akm
MSG_EXPL_GDS_BAT_BOR;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;18 ふつうのバット
;akm
MSG_EXPL_GDS_BAT_FUTSU;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;19 いいバット
;akm
MSG_EXPL_GDS_BAT_YOI;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;20 とてもいいバット
;akm
MSG_EXPL_GDS_BAT_TOTEMO;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;21 ミスターのバット
;akm
MSG_EXPL_GDS_BAT_MISTER;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;22 ゴージャスなバット
;akm
MSG_EXPL_GDS_BAT_KOUKYU;marcus
←
@GOSUB(_GDS_NESS_WEAPON)
@KEY()↓
◆This item looks like it could have had cork put into the core!

;jpn:◆キラリ↓
;jpn: かざりもついてる。
@KEYNP()
@!

;23 さいこうのバット
;akm
MSG_EXPL_GDS_BAT_SAIKO;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;24 マジカントバット
;akm
MSG_EXPL_GDS_BAT_MAGICANT;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;25 でんせつのバット
;akm
MSG_EXPL_GDS_BAT_DENSETSU;
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;26 ガッツのバット
;akm
MSG_EXPL_GDS_BAT_GUTS;marcus
←
@GOSUB(_GDS_NESS_WEAPON)
@KEY()
↓
◆When equipped, it increases your guts.

;jpn:◆そうびすると↓
;jpn: ガッツが あがる。
@KEYNP()
@!

;27 かたにちからバット
;akm
MSG_EXPL_GDS_BAT_KARBURI;marcus
←
@GOSUB(_GDS_NESS_WEAPON)
@KEY()
↓
◆You can’t help but swing this bat with all your might.@KEY()↓
◆There’s a good chance that you may just whiff.

;jpn:◆ちからいっぱい ふりまわさずには↓
;jpn: いられない。@KEY()↓
;jpn:◆からぶりに きをつけよう。
@KEYNP()
@!

;28 フライパン
;akm
MSG_EXPL_GDS_FLYPAN;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;29 あつめのフライパン
;akm
MSG_EXPL_GDS_FLYPAN_ATSUME;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;30 いいフライパン
;akm
MSG_EXPL_GDS_FLYPAN_YOI;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;31 シェフのフライパン
;akm
MSG_EXPL_GDS_FLYPAN_CHEF;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;32 すてきなフライパン
;akm
MSG_EXPL_GDS_FLYPAN_SUTEKI;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;33 ふしぎなフライパン
;akm
MSG_EXPL_GDS_FLYPAN_FUSHIG;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;34 てんしのフライパン
;akm
MSG_EXPL_GDS_FLYPAN_TENSHI;
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;35 おうじゃのつるぎ
;akm
MSG_EXPL_GDS_SWORD_KING;
←
@GOSUB(_GDS_POO_WEAPON)
@KEY()↓
◆It increases your offense.

;jpn:◆こうげきりょくアップだ。
@KEYNP()
@!

;36バンバンガン
;akm
MSG_EXPL_GDS_GUN_BANBAN;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;37ショックガン
;akm
MSG_EXPL_GDS_GUN_SHOCK;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;38エアガン
;akm
MSG_EXPL_GDS_GUN_AIR;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;39スーパーエアガン
;akm
MSG_EXPL_GDS_GUN_AIR_SUPER;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;40アストロマシンガン
;akm
MSG_EXPL_GDS_GUN_DESTROYER;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;41レーザービーム
;akm
MSG_EXPL_GDS_BEAM_LASER;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;42ハイパービーム
;akm
MSG_EXPL_GDS_BEAM_HYPER;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;43クラッシュビーム
;akm
MSG_EXPL_GDS_BEAM_CRASH;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;44にじいろビーム
;akm
MSG_EXPL_GDS_BEAM_NIJIIRO;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;45デスビーム
;akm
MSG_EXPL_GDS_BEAM_DEATH;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;46さいあくビーム
;akm
MSG_EXPL_GDS_BEAM_SAIAKU;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;47ムーンビーム
;akm
MSG_EXPL_GDS_BEAM_MOON;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;48ガイアビーム
;akm
MSG_EXPL_GDS_BEAM_GAIA;
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;49ヨーヨー
;akm
MSG_EXPL_GDS_EQUIP_YOYO;marcus
←
◆A so−so weapon.

;jpn:◆ちょっといいぶき。
@KEYNP()
@!

;50スリングショット
;akm
MSG_EXPL_GDS_EQUIP_SLING;marcus
←
◆A decent little weapon.

;jpn:◆まあまあいいぶき。
@KEYNP()
@!

;51スーパースリング
;akm
MSG_EXPL_GDS_EQUIP_SLING_SUPER;marcus
←
◆A pretty powerful weapon.

;jpn:◆わりといい ぶき。
@KEYNP()
@!

;52すっごいヨーヨー
;akm
MSG_EXPL_GDS_EQUIP_YOYO_SUPER;marcus
←
◆A tough, strong weapon!

;jpn:◆けっこういいぶき。
@KEYNP()
@!

;53コンバットヨーヨー
;akm
MSG_EXPL_GDS_EQUIP_KILLER;marcus
←
◆This one rocks, for sure.

;jpn:◆なるほどいいぶき。
@KEYNP()
@!

;54 たびのおまもり
;akm
MSG_EXPL_GDS_AMULET_ABI;
←
@GOSUB(_GDS_AMULET)
@KEYNP()
@!

;55 おおきなおまもり
;akm
MSG_EXPL_GDS_AMULET_OOKINA;marcus
←
@GOSUB(_GDS_AMULET)@KEY()↓
◆Also, it adds a bit of speed.

;jpn:◆スピードも↓
;jpn: ちょっとだけ あがる。
@KEYNP()
@!

;56 かがやくおまもり
;akm
MSG_EXPL_GDS_AMULET_KAGAYAKU;marcus
←
@GOSUB(_GDS_AMULET)@KEY()↓
◆It also increases your speed.

;jpn:◆スピードも↓
;jpn: あがる。	
@KEYNP()
@!

;57 うさぎのおまもり
;akm
MSG_EXPL_GDS_AMULET_USAGI;marcus
←
@GOSUB(_GDS_AMULET)@KEY()↓
◆It increases your speed in a big way.

;jpn:◆スピードも↓
;jpn: おおきく あがる。
@KEYNP()
@!

;58 ほのおのペンダント
;akm
MSG_EXPL_GDS_PENDANT_HONOO;marcus
←
@GOSUB(_GDS_EQUIP_BODY)
◆It protects you from fire attacks.

;jpn:◆ファイアーこうげきから↓
;jpn: みをまもる。
@KEYNP()
@!

;59 しずくのペンダント
;akm
MSG_EXPL_GDS_PENDANT_SHIZUKU;marcus
←
@GOSUB(_GDS_EQUIP_BODY)
◆It protects you from freeze attacks.

;jpn:◆フリーズこうげきから↓
;jpn: みをまもる。
@KEYNP()
@!

;60 やみのペンダント
;akm
MSG_EXPL_GDS_PENDANT_YAMI;marcus
←
@GOSUB(_GDS_EQUIP_BODY)
◆It absorbs the light of a flash attack.

;jpn:◆フラッシュこうげきの↓
;jpn: ひかりを↓
;jpn: きゅうしゅうしてしまう。
@KEYNP()
@!

;61 うみのペンダント
;akm
MSG_EXPL_GDS_PENDANT_UMI;marcus
←
@GOSUB(_GDS_EQUIP_BODY)
◆It protects you from fire, freeze and flash attacks.

;jpn:◆ファイアー↓
;jpn: フリーズ@KEY()↓
;jpn:◆そして フラッシュこうげきから↓
;jpn: みをまもる。
@KEYNP()
@!

;62 ほしのペンダント
;akm
MSG_EXPL_GDS_PENDANT_HOSHI;marcus
←
@GOSUB(_GDS_EQUIP_BODY)
◆It protects you from fire, freeze, flash and paralysis attacks.

;jpn:◆ファイアー↓
;jpn: フリーズ↓
;jpn: フラッシュ@KEY()↓
;jpn:◆そして パラライシスこうげきから↓
;jpn: かんぜんに みをまもる。
@KEYNP()
@!

;63 おうじゃのマント
;akm
MSG_EXPL_GDS_CLOAK_KING;marcus
←
◆@DSP_NAME(PC_POO)’s body equipment.@KEY()↓
◆It increases his Defense.

;jpn:◆@DSP_NAME(PC_POO)の↓
;jpn: ボディそうび。@KEY()↓
;jpn:◆しゅびりょくアップだ。
@KEYNP()
@!

;64 やすもののうでわ
;akm
MSG_EXPL_GDS_BRACELET_YASUMONO;
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;65 どうのうでわ
;akm
MSG_EXPL_GDS_BRACELET_COPPER;
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;66 ぎんのうでわ
;akm
MSG_EXPL_GDS_BRACELET_SILVER;
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;67 きんのうでわ
;akm
MSG_EXPL_GDS_BRACELET_GOLD;
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;68 プラチナのうでわ
;akm
MSG_EXPL_GDS_BRACELET_PLATINUM;
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;69 ダイヤのうでわ
;akm
MSG_EXPL_GDS_BRACELET_DIAMOND;
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;70 ようせいのうでわ
;akm
MSG_EXPL_GDS_BRACELET_YOUSEI;
←
@GOSUB(_GDS_EQUIP_ARM)@KEY()↓
@GOSUB(_GDS_EQUIP_ARM_B)
@KEYNP()
@!

;71 てんしのうでわ
;akm
MSG_EXPL_GDS_BRACELET_ENSHI;
←
@GOSUB(_GDS_EQUIP_ARM)@KEY()↓
@GOSUB(_GDS_EQUIP_ARM_B)
@KEYNP()
@!

;72 めがみのうでわ
;akm
MSG_EXPL_GDS_BLACELET_MEGAMI;
←
@GOSUB(_GDS_EQUIP_ARM)@KEY()↓
@GOSUB(_GDS_EQUIP_ARM_B)
@KEYNP()
@!

;73 おうじゃのうでわ
;akm
MSG_EXPL_GDS_BRACERET_KING;marcus
←
◆To be equipped on @DSP_NAME(PC_POO)’s arm.@KEY()↓

;jpn:◆@DSP_NAME(PC_POO)の↓
;jpn: うでそうび。@KEY()↓

◆Helps protect from being hypnotized, and Luck goes up.

◆Of course, Defense also goes up.

;jpn:◆しゅびりょくアップだ。
@KEYNP()
@!

;74 やきゅうぼう
;akm
MSG_EXPL_GDS_CAP_YAKYU;marcus
←
@GOSUB(_GDS_EQUIP_MISC)@KEY()↓
◆It has the logo of your favorite baseball team.

;jpn:◆おきにいりの↓
;jpn: きゅうだんの↓
;jpn: マークがはいってる。
@KEYNP()
@!

;75 ホームズキャップ
;akm
MSG_EXPL_GDS_CAP_HOLMS;marcus
←
@GOSUB(_GDS_EQUIP_MISC)@KEY()↓
◆It makes you feel like the great detective, Sherlock Holmes, when equipped.
;jpn:◆かぶると めいたんてい↓
;jpn: シャーロックホームズの↓
;jpn: きぶんだ。
@KEYNP()
@!

;76 ミスターのぼうし
;akm
MSG_EXPL_GDS_CAP_MISTER;marcus
←
@GOSUB(_GDS_EQUIP_MISC)@KEY()↓
◆It is said to have been given to your friend by a famous player at the ballpark.

;jpn:◆あこがれの せんしゅに↓
;jpn: やきゅうじょうで↓
;jpn: もらったものだという。
@KEYNP()
@!

;77 ぼうしヘルメット
;akm
MSG_EXPL_GDS_CAP_NANIRO;marcus
←
@GOSUB(_GDS_EQUIP_MISC)↓
◆Should be worn when searching for buried treasure,@KEY()↓
◆or while you are at the construction site.

;jpn:◆まいぞうきんさがし や↓
;jpn: こうじげんば などに。
@KEYNP()
@!

;78 リボン
;akm
MSG_EXPL_GDS_RIBBON;
←
@GOSUB(_GDS_PAULA_EQUIP_MISC)
@KEYNP()
@!

;79 まっかなリボン
;akm
MSG_EXPL_GDS_RIBBON_RED;
←
@GOSUB(_GDS_PAULA_EQUIP_MISC)
@KEYNP()
@!

;80 めがみのリボン
;akm
MSG_EXPL_GDS_RIBBON_MEGAMI;
←
@GOSUB(_GDS_PAULA_EQUIP_MISC)
@KEYNP()
@!

;81 やすらぎのコイン
;akm
MSG_EXPL_GDS_RIBBON_YASURAGI;
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;82 まもりのコイン
;akm
MSG_EXPL_GDS_COIN_MAORI;
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;83 まよけのコイン
;akm
MSG_EXPL_GDS_COIN_MAYOKE;
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;84 まふうじのコイン
;akm
MSG_EXPL_GDS_COIN_MAFUJI;
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;85 かがやきのコイン
;akm
MSG_EXPL_GDS_COIN_KAGAYAKI;
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;86 おみやげのコイン
;akm
MSG_EXPL_GDS_COIN_CHISAN;
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;87 おうじゃのバンダナ
;akm
MSG_EXPL_GDS_BANDANNA_KING;marcus
←
@GOSUB(_GDS_POO_EQUIP_MISC)@KEY()↓
◆It increases his Defense.

;jpn:◆しゅびりょくアップだ。
@KEYNP()
@!

;88 クッキー
;akm
MSG_EXPL_GDS_COOKIE;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
６
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;89 ポテトフライ
;akm
MSG_EXPL_GDS_POTATO_FRIED;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
２４
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;90 ハンバーガー
;akm
MSG_EXPL_GDS_HAMBURGER;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
５０
@GOSUB(_GDS_HP_RECOVER)
@KEY()↓
◆１００％ beef.

;jpn:◆ビーフ１００パーセント。
@KEYNP()
@!

;91 ゆでたまご
;akm
MSG_EXPL_GDS_EGG_BOILD;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
４０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;92 うみたてたまご
;akm
MSG_EXPL_GDS_EGG_RAW;marcus
←
@GOSUB(_GDS_EAT_HP_RECOVER)
８０
@GOSUB(_GDS_HP_RECOVER)
@KEY()↓
◆So fresh, it’s still warm!

;jpn:◆うみたてのホヤホヤ。
@KEYNP()
@!

;93 えんそくランチ
;akm
MSG_EXPL_GDS_LUNCH;marcus
←
@GOSUB(_GDS_EAT_HP_RECOVER)
８０
@GOSUB(_GDS_HP_RECOVER)
@KEY()↓
◆There’s even a slice of your favorite cake!

;jpn:◆たこウインナーも↓
;jpn: はいってる。
@KEYNP()
@!

;94 サマーズふうパスタ
;akm
MSG_EXPL_GDS_PASTA_SUMMERS;marcus
←
◆This is a pasta dish which legend holds was a favorite of King Summers the Third@KEY()↓
◆in the １６th century. Back then, there were many great chefs, confident of their@KEY()↓
◆culinary skills, always going to and from Summer’s Palace.@KEY()↓
◆Once day, King Summers wife, Anna Summers, said,@KEY()↓
◆”Oh what I wouldn’t give for some really delicious pasta!” 
... ... ...@KEY()↓
◆...Well, let’s just leave it at that. The story is too long to go through completely...@KEY()↓
◆but it really is a beautiful, touching tale...

;jpn:◆１６せいきの サマーズおう↓
;jpn: サマーズ３せいが↓
;jpn: このんだといわれているパスタだ。@KEY()↓
;jpn:◆とうじのサマーズきゅうでんには↓
;jpn: うでにおぼえのある↓
;jpn: りょうりにんが@KEY()↓
;jpn:◆たすう でいりしていた。↓
;jpn:◆ある なつのひのこと↓
;jpn: サマーズおうの きさき@KEY()↓
;jpn:◆アンナ・サマーズが↓
;jpn: 「ああ おいしいパスタが↓
;jpn: たべたい!」と‥‥。@KEY()↓
;jpn:◆‥‥‥‥‥‥‥‥‥。@KEY()↓
;jpn:◆‥‥‥‥‥せつめいが↓
;jpn: ながくなりそうなので↓
;jpn: けつろんをいおう。
@KEY()
↓
@GOSUB(_GDS_EAT_HP_RECOVER)
１１０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;95 ピザ
;akm
MSG_EXPL_GDS_PIZZA;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
１２０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;96 シェフのおすすめ
;akm
MSG_EXPL_GDS_VOUCHED_CHEF;marcus
←
◆This is today’s special. It is highly recommended by our chef,@KEY()↓
◆who trained at a five−star restaurant in Paris.@KEY()↓

;jpn:◆パリの５つぼし レストランで↓
;jpn: しゅぎょうした↓
;jpn: サマーズレストランの@KEY()↓
;jpn:◆シェフがすすめる↓
;jpn: ひがわり りょうり。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
２００
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;97 ピザ(Lサイズ)
;akm
MSG_EXPL_GDS_PIZZA_LARGE;
←
◆Since it’s a really big pizza, everyone can recover about ２４０ HP when eaten.

;jpn:◆Lサイズなので↓
;jpn: たべると ぜんいんのたいりょくが@KEY()↓
;jpn:◆それぞれ↓
;jpn: やく２４０
;@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;98 サイコキャラメル
;akm
MSG_EXPL_GDS_PSYCHO_CARAMEL;
←
◆Increases PP by ２０.

;jpn:◆たべると↓
;jpn: PPが↓
;jpn: やく２０
;@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;99 マジックトリフ
;akm
MSG_EXPL_GDS_MAGIC_TRUFFLE;marcus
←
◆A dream−like delicacy↓
  that is said to grow at the base of trees@KEY()↓
◆in wet, muddy places.@KEY()↓
◆It restores about ８０ PP.

;jpn:◆じめじめ どろどろした ばしょの↓
;jpn: きの ねもとにある といわれる↓
;jpn: まぼろしの ちんみ。@KEY()↓
;jpn:◆たべると↓
;jpn: PPが↓
;jpn: やく８０
;@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;100おうじゃのべんとう(さとりのべんとう)
;akm
MSG_EXPL_GDS_LUNCH_KING;marcus
←
@GOSUB(_GDS_EAT_HP_RECOVER)
５０ PP.

;jpn:◆PPが↓
;jpn: やく５０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;101ふしぎなキャンディ
;akm
MSG_EXPL_GDS_MYSTIC_ANDY;marcus
←
◆When you eat this, it will increase either Speed, Guts, Vitality, IQ or Luck.

;jpn:◆たべると スピード ガッツ↓
;jpn: バイタリティ IQ ラックの↓
;jpn: どれかが あがる。
@KEYNP()
@!

;102サンドイッチ(クロワッサン)
;akm
MSG_EXPL_GDS_BREAD_UGLY;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
６０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;103パン(バターロール)
;akm
MSG_EXPL_GDS_BREAD;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
３０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;104フーセンガム
;akm
MSG_EXPL_GDS_BUBBLE_GUM;marcus
←
◆This is the Balloon Monkey’s favorite.@KEY()↓
◆It will not help you recover, but@KEY()↓
◆You’ll also never run out, ’cause it’s a super jumbo pack!

;jpn:◆バルーンモンキーの↓
;jpn: だいこうぶつ。@KEY()↓
;jpn:◆たべても
;jpn: たいりょくは↓
;jpn: かいふくしない。@KEY()↓
;jpn:◆たくさん はいっているので↓
;jpn: なんまい たべても↓
;jpn: なくならない。
@KEYNP()
@!

;105はえみつ
;akm
MSG_EXPL_GDS_HAEMITSU;marcus
←
◆Geppu’s most favorite food in the whole world.@KEY()↓
◆However... it smells REALLY, really nasty! We’re talkin’ major stinkage here!

;jpn:◆ゲップーの↓
;jpn: だいこうぶつ。@KEY()↓
;jpn:◆ちょっと‥‥↓
;jpn: く くさい‥‥。
@KEYNP()
@!

;106オレンジジュース
;akm
MSG_EXPL_GDS_JUICE_ORANGE;
←
@GOSUB(_GDS_DRINK_HP_RECOVER)
６
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;107ロイヤルアイスティー
;akm
MSG_EXPL_GDS_ICE_TEA;marcus
←
◆The highest quality tea, produced by tea expert Mr. Y. Todaar,@KEY()↓
◆who carefully selects only hand−picked tea leaves.@KEY()↓
◆Long ago, only aristocrats at a king’s court were allowed to drink this tea.
;akm◆Ordinary folks never had it...


;jpn:◆こうちゃ かんていにんの↓
;jpn: トダールさんが@KEY()↓
;jpn:◆てづみリーフを げんせんして↓
;jpn: つくった↓
;jpn: さいこうきゅうの こうちゃ。@KEY()↓
;jpn:◆かつては↓
;jpn: きゅうていの きぞくしか↓
;jpn: のむことができなかった。@KEY()↓
;jpn:◆いっぱんしみんでも
@KEY()
↓
@GOSUB(_GDS_DRINK_HP_RECOVER)
６０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;108おとなのドリンク
;akm
MSG_EXPL_GDS_DRINK_ADULT;marcus
←
◆For building a stronger, healthier body.@KEY()↓
◆It gives you a blast of nourishment when you are fatigued.

;jpn:◆じようきょうそう↓
;jpn: にくたいひろうじの↓
;jpn: えいようほきゅうに。
@KEY()
↓
@GOSUB(_GDS_DRINK_HP_RECOVER)
８０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;109クラーケンのスープ
;akm
MSG_EXPL_GDS_SOUP_KRAKEN;marcus
←
◆Soup made from the fin of the sea monster known as Kraken.@KEY()↓
◆This beast lives in the ocean off the shore of Summers.

;jpn:◆サマーズのうみにすむ↓
;jpn: かいぶつクラーケンの↓
;jpn: ヒレのスープ。
@KEY()
↓
◆Very expensive, but a sizable power boost is guaranteed.

;jpn:◆とてもこうかだが↓
;jpn: そのぶんの たいりょくUPは↓
;jpn: まちがいなし。
@KEYNP()
@!

;110みず
;akm
MSG_EXPL_GDS_WATER;marcus
←
◆When you drink it, your PP slightly increases.

;jpn:◆のむと↓
;jpn: PPが↓
;jpn: わずかに
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;111かぜぐすり
;akm
MSG_EXPL_GDS_COLD_PILL;marcus
←
◆This is the most effective thing to take when you catch a cold.

;jpn:◆かぜを ひいたら↓
;jpn: このくすり。
@KEYNP()
@!

;112けっせい
;akm
MSG_EXPL_GDS_SERUM;marcus
←
◆This is the best thing to take when you get poisoned.

;jpn:◆どくに↓
;jpn: おかされたら↓
;jpn: これ。
@KEYNP()
@!

;113IQカプセル
;akm
MSG_EXPL_GDS_CAPSULE_IQ;marcus
←
◆It increases your IQ when taken.

;jpn:◆のむと↓
;jpn: IQがあがる。
@KEYNP()
@!

;114ガッツカプセル
;akm
MSG_EXPL_GDS_CAPSULE_GUTS;marcus
←
◆It increases your Guts when taken.

;jpn:◆のむと↓
;jpn: ガッツがあがる。
@KEYNP()
@!

;115スピードカプセル
;akm
MSG_EXPL_GDS_CAPSULE_SPEED;marcus
←
◆It increases your Speed when taken.

;jpn:◆のむと↓
;jpn: スピードがあがる。
@KEYNP()
@!

;116バイタルカプセル
;akm
MSG_EXPL_GDS_CAPSULE_VITAL;marcus
←
◆It increases your Vitality when taken.

;jpn:◆のむと↓
;jpn: バイタリティがあがる。
@KEYNP()
@!

;117ラックカプセル
;akm
MSG_EXPL_GDS_CAPSULE_LUCK;marcus
←
◆It increases your Luck when taken.

;jpn:◆のむと↓
;jpn: ラックがあがる。
@KEYNP()
@!

;118ケチャップ
;akm
MSG_EXPL_GDS_KETCHUP;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;119マスタード(こなざとう)
;akm
MSG_EXPL_GDS_MUSTARD;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;120ウスターソース
;akm
MSG_EXPL_GDS_SOURCE;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;121しょうゆ(コンデンスミルク)
;akm
MSG_EXPL_GDS_SOY;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;122しちみ(あおのり)
;akm
MSG_EXPL_GDS_SHICHIMI;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;123タバスコ
;akm
MSG_EXPL_GDS_TABASCO;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;124ごましお
;akm
MSG_EXPL_GDS_GOMASHIO;
←
@GOSUB(_GDS_TOPPING_HP_RECOVER)
@KEYNP()
@!

;125バックステージパス
;akm
MSG_EXPL_GDS_BACKSTAGE_PASS;marcus
←
◆It allows you go back stage at the Chaos Theater.@KEY()↓
◆Of course, you can also watch the show using the pass.

;jpn:◆カオスげきじょうの↓
;jpn: がくやに はいれる↓
;jpn: きょかしょう。@KEY()↓
;jpn:◆もちろん ステージも↓
;jpn: みほうだい。
@KEYNP()
@!

;126おうじゃのふりかけ(まんだらふりかけ)
;akm
MSG_EXPL_GDS_TOPPING_KING;marcus
←
◆Use by sprinkling it over food.@KEY()↓
◆It tastes good with any kind of food, thereby@KEY()↓
◆increasing the recovery power of the food.

;jpn:◆たべものに↓
;jpn: かけてつかう。@KEY()↓
;jpn:◆どんな たべものにも↓
;jpn: よくあう。@KEY()↓
;jpn:◆かいふくりょく アップだ。
@KEYNP()
@!

;127ぬれタオル
;akm
MSG_EXPL_GDS_WET_TOWEL;marcus
←
◆It’s great for those times that you get sunstroke.

;jpn:◆にっしゃびょうに↓
;jpn: かかったら↓
;jpn: これ。
@KEYNP()
@!

;128エンジェルシード(すっきりハーブ)
;akm
MSG_EXPL_GDS_ANGEL_SEED;marcus
←
◆It helps when you have been poisoned, or you are feeling nauseous.@KEY()↓
◆It also has other uses...@KEY()↓

;akm◆Also has other useage.@KEY()↓
 
;jpn:◆どくに おかされたり↓
;jpn: きもちがわるくなったら↓
;jpn: これ。@KEY()↓
;jpn:◆そのほかにも↓
@GOSUB(_GDS_HEAL_B)
@GOSUB(_GDS_HEAL_C1)
@KEYNP()
@!

;129うらカンポー
;akm
MSG_EXPL_GDS_DIAMOND_CRASHER;marcus
←
;◆ダイヤモンドになってしまったり↓
; しびれてしまったら↓
; これ。@KEY()↓
◆May revive a friend who is unconscious.@KEY()↓

;jpn:◆きぜつした なかまを↓
;jpn: カムバックさせることが ある。@KEY()↓
@GOSUB(_GDS_HEAL_A)
@GOSUB(_GDS_HEAL_B)
@GOSUB(_GDS_HEAL_C1)
;akm@KEY()↓
@GOSUB(_GDS_HEAL_D)
@KEYNP()
@!

;130いのちのつのぶえ
;akm
MSG_EXPL_GDS_LIFE_HORN;marcus
←
◆Revives a friend who is unconscious.@KEY()↓

;jpn:◆きぜつした なかまを↓
;jpn: カムバックさせる。@KEY()↓
@GOSUB(_GDS_HEAL_A)
@GOSUB(_GDS_HEAL_B)
@GOSUB(_GDS_HEAL_C2)
;@KEY()↓
@GOSUB(_GDS_HEAL_D)
@KEYNP()
@!

;131アンチPSIマシン
;akm
MSG_EXPL_GDS_ANTI_PSI;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Contains the enemy’s PSI during a battle.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: てきのPSIを ふうじこめる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;132シールドキラー
;akm
MSG_EXPL_GDS_SHIELD_KILLER;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Breaks through the enemy’s shield during a battle.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: てきのシールドを きりさく。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;133バズーカほう
;akm
MSG_EXPL_GDS_BAZOOKA;marcus
←
@GOSUB(_GDS_FOR_JEFF)
@GOSUB(_GDS_DAMAGE)
@KEY()↓
◆Because of its explosive power,@KEY()↓
◆it may effect others besides the target creature.@KEY()↓

;jpn:◆ばくはつりょくが あるので↓
;jpn: ねらったてき いがいにも↓
;jpn: こうかが ある。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;134スーパーバズーカ
;akm
MSG_EXPL_GDS__BAZOOKA_SUPER;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Really dishes out a lot of damage to the enemy during a battle.

;jpn:◆せんとうじ↓
;jpn: てきに おおきなダメージを↓
;jpn: あたえる。
@KEY()↓
◆Because of its explosive power,@KEY()↓
◆it may effect others besides the target creature.@KEY()↓

;jpn:◆ばくはつりょくが あるので↓
;jpn: ねらったてき いがいにも↓
;jpn: こうかが ある。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;135チューチューマシン
;akm
MSG_EXPL_GDS_SUCK;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Sucks up some HP from the target creature.@KEY()↓
◆The more HP an enemy has, the more you get.@KEY()↓

;jpn:◆ねらったてきの↓
;jpn: たいりょくを すいとる。@KEY()↓
;jpn:◆てきのたいりょくが↓
;jpn: おおきいほど↓
;jpn: たくさん すいとることができる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;136スーパーチューチュー
;akm
MSG_EXPL_GDS_SUCK_SUPER;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Sucks up some HP from all the enemies.@KEY()↓
◆The more HP the enemies have, the more you get.@KEY()↓

;jpn:◆てきぜんいんから↓
;jpn: たいりょくをすいとる。@KEY()↓
;jpn:◆てきのたいりょくが↓
;jpn: おおきいほど↓
;jpn: たくさん すいとることができる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;137スーパースプレー
;akm
MSG_EXPL_GDS_SPRAY_SUPER;marcus
←
◆Deals ２００ points of damage to any bug when used during combat.@KEY()↓

;jpn:◆せんとうじ ムシたちに↓
;jpn: それぞれ やく２００ポイントの↓
;jpn: ダメージをあたえる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;138ねばねばマシン
;akm
MSG_EXPL_GDS_NEBANEBA_MACHINE;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Sprays a sticky substance that stops the enemy from moving.@KEY()↓

;jpn:◆せんとうじ なかから↓
;jpn: ねばーっ としたものが↓
;jpn: とびだして@KEY()↓
;jpn:◆てきのうごきをとめる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;139ぐるめとうふマシン
;akm
MSG_EXPL_GDS_TOOL_ICHIGO_TOFU;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Invented by Apple Kid.@KEY()↓
;akm◆During the battle, not quite sure what it is, but gives enemy some damage.

◆If used during combat, some damage will be dealt to the enemy,@KEY()↓
◆though it’s not understood why this happens... it’s just yogurt after all...@KEY()↓

;jpn:◆アップルキッドの はつめいひん。@KEY()↓
;jpn:◆せんとうじ‥‥↓
;jpn: よくわからないが↓
;jpn: てきにダメージを あたえる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;140ものさし
;akm
MSG_EXPL_GDS_MONSASHI;marcus
←
◆You can even use this during battle!@KEY()↓

;jpn:◆せんとうじに↓
;jpn: つかうことすら できる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;141へびぶくろ
;akm
MSG_EXPL_GDS_SNAKE_BAG;marcus
←
◆During battle, a snake pops out of the bag and bites the enemy.@KEY()↓
◆There are thousands of small snakes living in the bag,@KEY()↓
◆so you should be able to use it over and over again.@KEY()↓
◆It can possibly poison the enemy, too.

;jpn:◆せんとうじ なかから↓
;jpn: へびが とびだして↓
;jpn: てきに かみつく。@KEY()↓
;jpn:◆ふくろには ちいさな へびが↓
;jpn: むすうに いるので↓
;jpn: なんどでも つかえる。@KEY()↓
;jpn:◆てきに↓
;jpn: どくを あたえることも ある。
@KEYNP()
@!

;142ミイラのほうたい
;akm
MSG_EXPL_GDS_BANDAGE_MUMMY;
←
◆If used as a whip during battle, the enemy will take some damage@KEY()↓
◆and stop moving for a while.

;jpn:◆せんとうじ↓
;jpn: むちのように つかうと↓
;jpn: てきにダメージを あたえ@KEY()↓
;jpn:◆すこしのあいだ↓
;jpn: うごきを とめることができる。
@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;143ぶんどき
;akm
MSG_EXPL_GDS_BUNDOKI;marcus
←
◆You can even use this during battle!@KEY()↓

;jpn:◆せんとうじに↓
;jpn: つかうことさえ できる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;144ペンシルロケット
;akm
MSG_EXPL_GDS_PENCIL_ROCKET;
←
@GOSUB(_GDS_FOR_JEFF)
@GOSUB(_GDS_DAMAGE)
@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;145ペンシルロケット５
akm
MSG_EXPL_GDS_PENCIL_ROCKET5;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆Fires a fast, powerful bottle rocket.@KEY()↓
 
;jpn:◆ペンシルロケットを↓
;jpn: いちどに５はつ はっしゃする。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;146ペンシルロケット２０
;akm
MSG_EXPL_GDS_PENCIL_ROCKET20;
←
@GOSUB(_GDS_FOR_JEFF)
◆Possibly the strongest weapon around, it does a lot of damage due to its massive warhead.@KEY()↓
 
;jpn:◆ペンシルロケットを↓
;jpn: いちどに２０ぱつ はっしゃする。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;147ボム
;akm
MSG_EXPL_GDS_BOMB;
←
@GOSUB(_GDS_DAMAGE)
@KEY()↓
◆Because of its explosive power,@KEY()↓
◆it may effect others besides the target creature. @KEY()↓

;jpn:◆ばくはつりょくが あるので↓
;jpn: ねらったてき いがいにも↓
;jpn: こうかが ある。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;148スーパーボム
;akm
MSG_EXPL_GDS_BOMB_SUPER;marcus
←
◆Able to dish out some heavy−duty destruction in combat.  @KEY()↓
◆Because of its explosive power,@KEY()↓
◆it may effect others besides the target creature.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: てきに おおきなダメージを↓
;jpn: あたえる。@KEY()↓
;jpn:◆ばくはつりょくが あるので↓
;jpn: ねらったてき いがいにも↓
;jpn: こうかが ある。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;149さっちゅうスプレー
;akm
MSG_EXPL_GDS_SPRAY;marcus
←
◆Deals １００ points of damage to any bug when used during combat.@KEY()↓
;◆Deals about １００ points of damage to a bug when used during combat.@KEY()↓

;jpn:◆せんとうじ ムシたちに↓
;jpn: それぞれ やく１００ポイントの↓
;jpn: ダメージをあたえる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;150さびのもと
;akm
MSG_EXPL_GDS_ORIGIN_RUST;marcus
←
◆Quickly rusts metallic enemies when used during battle.@KEY()↓
◆The enemy will take about ２００ points of damage.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: きんぞくのてきを さびさせて@KEY()↓
;jpn:◆それぞれ やく２００ポイントの↓
;jpn: ダメージをあたえる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;151さびのもとスーパー
;akm
MSG_EXPL_GDS_ORIGIN_RUST_SUPER;marcus
←
◆Causes almost instantaneous rusting when used on metallic enemies during battle.@KEY()↓
◆The enemy takes about ４００ points of damage.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: きんぞくのてきを さびさせて@KEY()↓
;jpn:◆それぞれ やく４００ポイントの↓
;jpn: ダメージをあたえる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;152ペテネラのくつした
;akm
MSG_EXPL_GDS_SOCKS_STINK;marcus
←
◆When used during battle, the enemy gets so nauseous from the ripe odor,@KEY()↓
◆they cannot fight.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: てきはそのくささに たじろぎ↓
;jpn: かたまってしまう。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;153くわがたむし
;akm
MSG_EXPL_GDS_KUWAGT;marcus
←
◆By throwing this at the enemy during battle,@KEY()↓
◆the enemy is shocked and stops moving.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: なげつけると てきがおどろき↓
;jpn: うごきがとまる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;154ハブラシ
;akm
MSG_EXPL_GDS_TOOTHBRUSH;marcus
←
◆Can be used during battle.@KEY()↓
 
;jpn:◆せんとうじに↓
;jpn: つかうことが できる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;155ハンドバックのベルト
;akm
MSG_EXPL_GDS_BELT_HANDBAG;marcus
←
◆When used as a whip during battle,@KEY()↓
◆the enemy takes enough damage to stop moving for a short time.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: むちのように つかうと↓
;jpn: てきにダメージを あたえ@KEY()↓
;jpn:◆すこしのあいだ↓
;jpn: うごきを とめることができる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;156ファラオののろい
;akm
MSG_EXPL_GDS_CURSE_PHARAOH;marcus
←
◆An ectoplasmic ooze is disgorged out of the dreadful box,@KEY()↓
◆and the enemy may be poisoned.@KEY()↓

;jpn:◆おどろおどろしい↓
;jpn: もんようが えがかれた↓
;jpn: はこの なかから@KEY()↓
;jpn:◆エクトプラズムのようなものが↓
;jpn: とびだし@KEY()↓
;jpn:◆てきに↓
;jpn: どくを あたえることも ある。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;157ディフェンスシャワー
;akm
MSG_EXPL_GDS__SHOWER_DEFNCE;marcus
←
◆Increases the Defense of all the friends.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: みかたぜんいんの↓
;jpn: しゅびりょくが あがる。@KEY()↓
@GOSUB(_PSI_USE_PILE)
@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;158ママのてがみ
;akm
MSG_EXPL_GDS_LETTER_MAMA
←
◆A letter from Mama to @DSP_NAME(PC_NESS).

;jpn:◆ママが↓
;jpn: @DSP_NAME(PC_NESS)にあてた てがみ。
@KEYNP()
@!

;159インスタントガッツ
;akm
MSG_EXPL_GDS_DOUBLE_GUTS;marcus
←
◆Doubles your guts during battle.@KEY()↓
◆However, after a battle, your guts return to normal. @KEY()↓

;jpn:◆せんとうじ↓
;jpn: ガッツが ２ばいになる。@KEY()↓
;jpn:◆ただし せんとうが おわると↓
;jpn: もとにもどる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;160ドラゴンパウダー
;akm
MSG_EXPL_GDS_DRAGON_POWDER;marcus
←
◆If you sprinkle the powder on one of your friends during battle, @KEY()↓
◆that friend turns into a dragon and attacks all enemies.@KEY()↓

;jpn:◆せんとうじ↓
;jpn: みかたに ふりかけると↓
;jpn: ドラゴンに へんしんして@KEY()↓
;jpn:◆てきぜんいんに↓
;jpn: ダメージを あたえる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;161ディフェンススプレー
;akm
MSG_EXPL_GDS_SPRAY_DEFNCE;marcus
←
◆Increase one of the friends Defense during battle.

;jpn:◆せんとうじ↓
;jpn: みかたひとりの↓
;jpn: しゅびりょくが あがる。
@KEY()
↓
@GOSUB(_PSI_USE_PILE)
@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;162 ブタのはな
;akm
MSG_EXPL_GDS_NOSE_PIG;marcus
←
◆If you wear this on your nose, you can find and root out magic truffles.@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)@KEY()↓
◆...let me explain a bit about magic truffles.@KEY()↓
◆They are a kind of mushroom that grow in damp places, like at the base of big trees.@KEY()↓
◆They are almost always buried, @KEY()↓
◆so they cannot be seen.@KEY()↓
◆If you find one and eat it, it is said to greatly recover a person’s PP!@KEY()↓
◆You can see more info about the wondrous Magic Truffle after you have obtained one.

;jpn:◆はなに はりつけると↓
;jpn: マジックトリフの においを↓
;jpn: かぎわけることができる。@KEY()↓

;jpn:◆‥‥ついでだから↓
;jpn: マジックトリフのせつめいを↓
;jpn: ざっと しておこう。@KEY()↓
;jpn:◆マジックトリフとは↓
;jpn: じめじめしたばしょの@KEY()↓
;jpn:◆たいぼくの ねもとなどに↓
;jpn: はえている↓
;jpn: キノコのいっしゅ。@KEY()↓
;jpn:◆はえているといっても↓
;jpn: じめんのなかに↓
;jpn: うもれていることがほとんどで@KEY()↓
;jpn:◆めで みてさがすのは↓
;jpn: とてもムリらしい。@KEY()↓
;jpn:◆たべると サイコパワーが↓
;jpn: どーん! とかいふくする@KEY()↓
;jpn:◆らしい。@KEY()↓
;jpn:◆くわしくはマジックトリフの↓
;jpn: せつめいをごらんください。
@KEYNP()
@!

;163どうぐやのかんばん
;akm
MSG_EXPL_GDS_SIGNBOARD_PAWNSHOP;marcus
←
◆It invites people to come and buy your unnecessary goods.@KEY()↓

;jpn:◆つかうと↓
;jpn: いらないグッズを かいに↓
;jpn: おきゃくさんが やってくる。@KEY()↓
@GOSUB(_GDS_USE_MANY_TIMES)
@KEYNP()
@!

;164むくちをなおすほん
MSG_EXPL_GDS_BOOK_CHAT;marcus
←
◆As the title says, it helps one overcome shyness.

;jpn:◆そのなのとおり↓
;jpn: むくちをなおすほんだ。
@KEYNP()
@!

;165えはがき
;akm
MSG_EXPL_GDS_POSTCARD;marcus
←
◆Not really horrible, but the scene on the front doesn’t make you want to go there.  

;jpn:◆あたりさわりのない↓
;jpn: しかし↓
;jpn: かんじのわるい@KEY()↓
;jpn:◆ふうけいが↓
;jpn: えがかれている。
@KEYNP()
@!

;166キングバナナ
;akm
MSG_EXPL_GDS_DRY_MEAT_SPECIAL;marcus
←
◆A king−sized banana.↓
  Not edible.

;jpn:◆キングサイズの バナナ。↓
;jpn: しょくように てきさない。
@KEYNP()
@!

;167トニーのてがみ
;akm
MSG_EXPL_GDS_LETTER_TONY
←
◆A letter from Tony to @DSP_NAME(PC_JEFF).

;jpn:◆トニーが↓
;jpn: @DSP_NAME(PC_JEFF)にあてた てがみ。
@KEYNP()
@!

;168ヒヨコ
;akm
MSG_EXPL_GDS_HIYOK;marcus
←
◆A chick that just hatched.

;jpn:◆うまれたばかりの↓
;jpn: ヒヨコです。
@KEYNP()
@!

;169にわとり
;akm
MSG_EXPL_GDS_NIWATORI;marcus
←
◆A real, live chicken.@KEY()↓
◆Don’t eat it, please.

;jpn:◆にわとり。↓
;jpn:◆たべないでくださいね。
@KEYNP()
@!

;170たびごやのカギ
;akm
MSG_EXPL_GDS_KEY_TABIGOYA;marcus
←
◆A key to the traveling entertainer’s shack.

;jpn:◆たびげいにんの↓
;jpn: こやのカギ。
@KEYNP()
@!

;171ろうやのカギ
;akm
MSG_EXPL_GDS_KEY_PRISON;marcus
←
◆A key to a holding cell made specially for @DSP_NAME(PC_PAULA).

;jpn:◆@DSP_NAME(PC_PAULA)が つかまっている↓
;jpn: ろうやのカギ。
@KEYNP()
@!

;172ちょっとカギマシン
;akm
MSG_EXPL_GDS_CHOTTO;marcus
←
◆The ”Machine that Opens Doors, especially when you have a slightly bad key” machine.

;jpn:◆「ちょっとしたカギなら↓
;jpn: いがいとカンタンに↓
;jpn: あけられる」マシン。
@KEYNP()
@!

;173メイドのカギ
;akm
MSG_EXPL_GDS_MONTLY;marcus
←
◆A key given to you by a maid who works at the Monotoli building.

;jpn:◆モノトリービルの↓
;jpn: メイドさんがくれたカギ。
@KEYNP()
@!

;174ゾンビホイホイ
;akm
MSG_EXPL_GDS_ZOMBIE_HOIHOI;marcus
←
◆Apple Kid’s invention.@KEY()↓
◆Lay this out in the tent, and the next day, a lot of zombies may be stuck to it.

;jpn:◆アップルキッドの はつめいひん。@KEY()↓
;jpn:◆テントにしかけて↓
;jpn: ひとばん たてば↓
;jpn: ゾンビが あつまってくる。
@KEYNP()
@!

;175たかのめ
;akm
MSG_EXPL_GDS_EAGLE_EYE;marcus
←
◆What a miracle! Now you can see in the dark!

;jpn:◆くらやみのなかでも↓
;jpn: あらふしぎ↓
;jpn: めが みえるようになる。
@KEYNP()
@!

;176じてんしゃ
;akm
MSG_EXPL_GDS_BICYCLE;marcus
←
◆Riding this makes you feel like whistling!@KEY()↓
◆You can even ring the bell by pressing the R button.

;jpn:◆こぐと↓
;jpn: おもわず↓
;jpn: くちぶえが ふきたくなる。@KEY()↓
;jpn:◆Rボタンを おすと↓
;jpn: ベルがなる。
@KEYNP()
@!

;177キャッシュカード
;akm
MSG_EXPL_GDS_CASHCARD;marcus
←
;akm◆Don’t forget this when you leave!

◆You know, you shouldn’t leave home without...@KEY()↓
◆It even works overseas!

;jpn:◆でかけるときは わすれずに。↓
;jpn: かいがいでも つかえます。
@KEYNP()
@!

;178チケット
;akm
MSG_EXPL_GDS_THEATER_TICKET;marcus
←
◆It says, ”Section B, seat ３D.”

;jpn:◆「Sせき ３ばん」と↓
;jpn: かいてある。
@KEYNP()
@!

;179ようちえんじのてがみ
;akm
MSG_EXPL_GDS_LETTER_CHILD;marcus
←
◆A letter from the pre−school kids to @DSP_NAME(PC_PAULA).

;jpn:◆ポーラスターようちえんの↓
;jpn: おともだちが↓
;jpn: @DSP_NAME(PC_PAULA)にあてた てがみ。
@KEYNP()
@!

;180さつたば
;akm
MSG_EXPL_GDS_SATSUTABA;marcus
←
◆A bundle of brand new, crisp bills.

;jpn:◆てが きれそうな↓
;jpn: しんぴんの↓
;jpn: おさつのたばだ。
@KEYNP()
@!

;181じゅしんでんわ
;akm
MSG_EXPL_GDS_PHONE_RECIVER;marcus
←
◆Apple kid’s invention.@KEY()↓
◆Now, you can receive important calls.

;jpn:◆アップルキッドの はつめいひん。@KEY()↓
;jpn:◆だれかから↓
;jpn: だいじな でんわが↓
;jpn: かかってくるかもしれない。
@KEYNP()
@!

;182ダイヤモンド
;akm
MSG_EXPL_GDS_DIAMOND;marcus
←
◆A big, beautiful, and expensive−looking gem.
 
;jpn:◆おおきくて↓
;jpn: うつくしくて↓
;jpn: こうかそうな ほうせき。
@KEYNP()
@!

;183サインいりバナナ
;akm
MSG_EXPL_GDS_BANN_SIGNED;
←
◆A banana skin with Venus’s autograph.

;jpn:◆ビーナスのサインが↓
;jpn: はいっている↓
;jpn: バナナのかわ。
@KEYNP()
@!

;184タコけしマシン
;akm
MSG_EXPL_GDS_KEY_TAKOKESHI;marcus
←
◆Apple Kid’s invention.@KEY()↓
◆It makes something blocking your way@KEY()↓
◆that looks like an pencil disappear in just a second.
;jpn:◆アップルキッドの はつめいひん。@KEY()↓
;jpn:◆めのまえの↓
;jpn: タコの かたちを↓
;jpn: したものを@KEY()↓
;jpn:◆あっというまに↓
;jpn: けしてしまうマシン。
@KEYNP()
@!

;185ヒエログリフのうつし
;akm
MSG_EXPL_GDS_HIEROGLYPH_COPY;marcus
←
◆A copy of a hieroglyph.@KEY()↓
◆Something important is recorded in the ancient characters.

;jpn:◆ヒエログリフの うつし。↓
;jpn:◆こだいのもじで↓
;jpn: なにやら かいてある。
@KEYNP()
@!

;186メテオタイト
;akm
MSG_EXPL_GDS_PRECIOUS_METAL_B;marcus
←
◆It can be sold for a very high price.@KEY()↓
◆Nothing happens if you use it.@KEY()↓
◆A good explanation is kind of tough...

;jpn:◆こうかなねだんで↓
;jpn: かいとって もらえそう。@KEY()↓
;jpn:◆つかっても↓
;jpn: なにも おこらない。@KEY()↓
;jpn:◆なかなか せつめいしにくい↓
;jpn: ぶっしつ。
@KEYNP()
@!

;187コンタクトレンズ
;akm
MSG_EXPL_GDS_CONTACT_LENS;marcus
←
◆It must belong to someone.

;jpn:◆だれかの おとしものらしい。
@KEYNP()
@!

;188ハンドエイド
;akm
MSG_EXPL_GDS_HAND_AID;marcus
←
◆A hand−made Band Aid.@KEY()↓
◆It heals your wounded body.@KEY()↓

;jpn:◆ハンドメイドの バンドエイド↓
;jpn: りゃくして「ハンドエイド」。@KEY()↓
;jpn:◆つかうと↓
;jpn: からだじゅうの きずが↓
;jpn: かんぜんに なおる。@KEY()↓
@GOSUB(_GDS_USE_ONCE)
@KEYNP()
@!

;189いちごどうふ
;akm
MSG_EXPL_GDS_ICHIGO_TOFU;
←
◆A fashionable treat for snobby, haute cuisine people in some big cities.@KEY()↓

;jpn:◆だいとかいで にんきの↓
;jpn: ファッショナブルな↓
;jpn: デザート。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
３０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;190バナナ
;akm
MSG_EXPL_GDS_BANN;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
２５
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;191カロリーブロック
;akm
MSG_EXPL_GDS_CALORIE_BLOCK;
←
@GOSUB(_GDS_EAT_HP_RECOVER)
６０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;192ププカのカギ(とうのかぎ)
;akm
MSG_EXPL_GDS_KEY_DUNGEONMAN;
←
◆An old key.

;jpn:◆ふるぼけたカギ。
@KEYNP()
@!

;193ぶっしつXYZ
;akm
MSG_EXPL_GDS_OBJECT_XYZ;marcus
←
◆It looks like a plain old rock,@KEY()↓
◆but for someone who knows about it, it is actually a very precious, unusual element.

;jpn:◆いっけん↓
;jpn: ただの いしのようだが‥‥。@KEY()↓
;jpn:◆みるひとがみれば↓
;jpn: すごく とくしゅな↓
;jpn: ぶっしつだ。
@KEYNP()
@!

;194だいちのペンダント
;akm
MSG_EXPL_GDS_PENDANT_DAICHI;marcus
←
@GOSUB(_GDS_EQUIP_BODY)
◆It protects you from fire, freeze, and flash attacks.

;jpn:◆ファイアー↓
;jpn: フリーズ@KEY()↓
;jpn:◆そして フラッシュこうげきから↓
;jpn: みをまもる。
@KEYNP()
@!

;195ちゅうわマシン
;akm
MSG_EXPL_GDS_NEUTRALIZER;marcus
←
@GOSUB(_GDS_FOR_JEFF)
◆This item resets the abilities of all creatures (friend or enemy)@KEY()↓
◆to their normal levels.@KEY()↓
◆Any changes that had taken place due to PSI and such is neutralized.@KEY()↓
◆It also neutralizes all shields (friend or enemy) that were in effect.@KEY()↓
◆(Remember, the abilities@KEY()↓
◆that I am talking about are Offense, Defense, Guts, etc.)

;jpn:◆せんとうじに へんかしている↓
;jpn: パラメーターを@KEY()↓
;jpn:◆てきみかたをとわず↓
;jpn: すべて もとにもどす。@KEY()↓
;jpn:◆かかっているシールドを↓
;jpn: てきみかたをとわず↓
;jpn: かいじょする こうかもある。@KEY()↓
;jpn:◆(パラメーターとは↓
;jpn: オフェンスや↓
;jpn: ディフェンスや@KEY()↓
;jpn:◆ガッツなどを あらわす↓
;jpn: すうちのことです)
@KEYNP()
@!

;196おとのいし
;akm
MSG_EXPL_GDS_SOUND_STONE;marcus
←
◆If you touch this to your forehead and concentrate on your thoughts,@KEY()↓

◆Your Sanctuary melodies can be heard.

;jpn:◆ひたいにあて↓
;jpn: いしきを しゅうちゅうすると@KEY()↓
;jpn:◆おぼえた メロディが↓
;jpn: きこえてくる。
@KEYNP()
@!

;197あなぬけネズミ
;akm
MSG_EXPL_GDS_ESCAPE_MOUSE;marcus
←
◆If you use this in a dungeon or some such place,@KEY()↓
◆the mouse brings you back to the place where you entered.@KEY()↓
◆It’s a very smart mouse.

;jpn:◆ダンジョンのなかでつかうと↓
;jpn: はいってきたばしょまで↓
;jpn: つれもどしてくれる@KEY()↓
;jpn:◆かしこいネズミ。
@KEYNP()
@!

;198アイスキャンディ(ひしょちのジェラード)
;akm
MSG_EXPL_GDS_ICE_CANDY;marcus
←
◆Ice cream that is all the rage among fashionable, young women.@KEY()↓

;jpn:◆オシャレな おねーさんなどに↓
;jpn: にんきがある↓
;jpn: アイスクリーム。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
３０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;199へび
;akm
MSG_EXPL_GDS_SNAKE;marcus
←
◆When used during battle, it bites the enemy and disappears.@KEY()↓
◆It may also poison the enemy.

;jpn:◆せんとうじに つかうと↓
;jpn: てきに かみついて↓
;jpn: どこかへ いってしまう。@KEY()↓
;jpn:◆てきに↓
;jpn: どくを あたえることも ある。
@KEYNP()
@!

;200どくへび
;akm
MSG_EXPL_GDS_SNAKE_POISON;marcus
←
◆When used during battle, it bites the enemy and disappears.@KEY()↓
◆It always poisons the enemy.

;jpn:◆せんとうじに つかうと↓
;jpn: てきに かみついて↓
;jpn: どこかへ いってしまう。@KEY()↓
;jpn:◆てきに かくじつに↓
;jpn: どくを あたえる。
@KEYNP()
@!

;201さとりのいし
;akm
MSG_EXPL_GDS_FUUIN_STONE;marcus
←
◆A miraculous stone that enables you to ”concentrate”@KEY()↓
◆without using your own brain.@KEY()↓
◆This is accomplished just by your keeping this item.@KEY()↓
◆This is great because if you can’t concentrate, you can’t use PSI.

;jpn:◆もっているだけで↓
;jpn: コンセントレーションを↓
;jpn: みだされなくなる@KEY()↓
;jpn:◆ふしぎな いし。@KEY()↓
;jpn:◆コンセントレーションできないと↓
;jpn: PSIは つかえない。
;@KEY()
;◆(コンセントレーションとは↓
; しゅうちゅうりょくのことです)
@KEYNP()
@!

;202まちのちず
;akm
MSG_EXPL_GDS_TOWN_MAP;marcus
←
◆A handy town map.
 It can be used in Onett, as well as other towns.@KEY()↓
◆You can view the map quickly, simply by pressing the X button.

;jpn:◆べんりなタウンマップ。↓
;jpn: オネットをはじめ↓
;jpn: いろいろな まちで つかえる。@KEY()↓
;jpn:◆Xボタンをおせば↓
;jpn: すぐに みることができる。
@KEYNP()
@!

;203ビデオドラッグ
;akm
MSG_EXPL_GDS_VIDEO_DRUG;marcus
←
◆What the hey is this?

;jpn:◆なんなんだ これは?
@KEYNP()
@!

;204グレオレマシーン
;akm
MSG_EXPL_GDS_GREORE_MACHINE;marcus
←
◆Orange Kid’s invention.@KEY()↓
◆The full name is the ”Super Orange Machine.”

;jpn:◆オレンジキッドの はつめいひん。@KEY()↓
;jpn:◆せいしきめいしょうは↓
;jpn: 「グレートオレンジマシーン」。
@KEYNP()
@!

;205ロッカーのカギ
;akm
MSG_EXPL_GDS_KEY_LOCKER;marcus
←
◆A key to a regular locker.

;jpn:◆ふつうの↓
;jpn: ロッカーのカギ。
@KEYNP()
@!

;206たいしたことないもの
;akm
MSG_EXPL_GDS_NOT_SO_GOOD;marcus
←
◆It doesn’t look like it would do much of anything, but...

;jpn:◆ほんとに↓
;jpn: たいしたことの なさそうな↓
;jpn: ものだが‥‥。
@KEYNP()
@!

;207マジックタルト
;akm
MSG_EXPL_GDS_MAGIC_TORTE;marcus
←
◆Recovers about ２０ PP.

;jpn:◆たべると↓
;jpn: PPが↓
;jpn: やく２０
;@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;208ちいさなルビー
;akm
MSG_EXPL_GDS_TINY_RUBY;marcus
←
◆An old treasure from Dalaam.

;jpn:◆ランマのくにに↓
;jpn: ふるくから ある↓
;jpn: たからもの。
@KEYNP()
@!

;209サルのきもち
;akm
MSG_EXPL_GDS_MONKY_MIND;marcus
←
◆A gift from a monkey.@KEY()↓
◆It can be used during battle.

;jpn:◆サルからの おくりもの。↓
;jpn:◆せんとうで↓
;jpn: つかうことが できる。
@KEYNP()
@!

;210こけしけしマシン
;akm
MSG_EXPL_GDS_KEY_KOKESHIKESHI;
←
◆Apple kid’s invention.@KEY()↓
◆It erases something that looks like a eraser@KEY()↓
◆that also might be blocking your way.
;jpn:◆アップルキッドの はつめいひん。@KEY()↓
;jpn:◆めのまえの↓
;jpn: こけしの かたちを↓
;jpn: したものを@KEY()↓
;jpn:◆あっというまに↓
;jpn: けしてしまうマシン。
@KEYNP()
@!

;211グミドリアン
;akm
MSG_EXPL_GDS_KEY_GUMIDORIAN;marcus
←
◆A very strong−smelling dish.@KEY()↓
◆Those who like it go nuts for it...

;jpn:◆ひじょうにつよい においの↓
;jpn: くだもの。↓
;jpn:◆すきなひとには たまらない。
@KEYNP()
@!

;212ゴヂラのバット
;akm
MSG_EXPL_GDS_BAT_GODZILLA
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;213ゴージャスなバット
;akm
MSG_EXPL_GDS_BAT_KOUKYU_E;marcus
←
@GOSUB(_GDS_NESS_WEAPON)
@KEY()↓
◆Wow! Look at the pine tar! It’s almost all the way to the end!

;jpn:◆キラリ↓
;jpn: かざりもついてる。
@KEYNP()
@!

;214きゅうきょくバット
;akm
MSG_EXPL_GDS_BAT_MAMMOTH
←
@GOSUB(_GDS_NESS_WEAPON)
@KEYNP()
@!

;215ダブルビーム
;akm
MSG_EXPL_GDS_BEAM_STRONG
←
@GOSUB(_GDS_JEFF_WEAPON)
@KEYNP()
@!

;216ブラチナのうでわ
;akm
MSG_EXPL_GDS_BRACELET_PLATINUM_E
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;217ダイヤのうでわ
;akm
MSG_EXPL_GDS_BRACELET_DIAMOND_E
←
@GOSUB(_GDS_EQUIP_ARM)
@KEYNP()
@!

;218まもりのリボン
;akm
MSG_EXPL_GDS_RIBBON_MAMORI
←
@GOSUB(_GDS_PAULA_EQUIP_MISC)
@KEY()↓			;added 0716

◆When equipped, Luck is increased.
;@GOSUB(_GDS_EQUIP_LUCK_UP)	;added 0716
@KEYNP()
@!

;219まふうじのリボン
;akm
MSG_EXPL_GDS_RIBBON_MAFUJI
←
@GOSUB(_GDS_PAULA_EQUIP_MISC)
@KEY()↓			;added 0716

◆When equipped, Luck is increased.
;@GOSUB(_GDS_EQUIP_LUCK_UP)	;added 0716
@KEYNP()
@!

;220どせいさんのリボン
;akm
MSG_EXPL_GDS_RIBBON_DOSEI;marcus
←
@GOSUB(_GDS_PAULA_EQUIP_MISC)
@KEY()↓			;added 0716

◆When equipped, Luck is increased.
;@GOSUB(_GDS_EQUIP_LUCK_UP)	;added 0716
@KEY()↓
◆Same as the one that Mr. Saturn wears on his head.@KEYNP()↓

;jpn:◆どせいさんの↓
;jpn: あたまのうえに みえるものと↓
;jpn: おなじ。@KEYNP()
@!

;221しずけさのコイン
;akm
MSG_EXPL_GDS_COIN_MIZUUMI
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;222まよけのコイン
;akm
MSG_EXPL_GDS_COIN_MAYOKE_E
←
@GOSUB(_GDS_COIN)
@KEYNP()
@!

;223カップめん
;akm
MSG_EXPL_GDS_CUP_RAMEN;marcus
←
◆You know what this is...@KEY()↓

;jpn:◆ごぞんじのとおりのもの。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
４０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;224スキップサンド
;akm
MSG_EXPL_GDS_SKIP_SAND;marcus
←
◆Gives you a spring in your step for about １０ seconds.@KEY()↓
◆It also helps you recover your power a bit.

;jpn:◆たべると↓
;jpn: １０びょうほど↓
;jpn: あしどりが かるくなる。@KEY()↓
;jpn:◆たいりょくも↓
;jpn: すこし かいふくする。
@KEYNP()
@!

;225ダブルスキップサンド
;akm
MSG_EXPL_GDS_SKIP_SAND_SP;marcus
←
◆Gives you a spring in your step for about ２０ seconds.@KEY()↓
◆It also helps you recover your power a bit.

;jpn:◆たべると↓
;jpn: ２０びょうほど↓
;jpn: あしどりが かるくなる。@KEY()↓
;jpn:◆たいりょくも↓
;jpn: すこし かいふくする。
@KEYNP()
@!

;226ラッキーサンドa
;akm
MSG_EXPL_GDS_FOOD_LUCKY_SAND_A;marcus
←
◆It helps you recover your power...@KEY()↓
◆How much and what you exactly recover depends on your luck!

;jpn:◆たべると↓
;jpn: たいりょくなどが↓
;jpn: かいふくする。@KEY()↓
;jpn:◆なにが どのくらい↓
;jpn: かいふくするか は↓
;jpn: うんしだい。
;０５０１γ
@KEYNP()
@!

;227ラッキーサンドb
;akm
MSG_EXPL_GDS_FOOD_LUCKY_SAND_B;
←
◆It helps you recover your power...@KEY()↓
◆How much and what you exactly recover depends on your luck!

;jpn:◆たべると↓
;jpn: たいりょくなどが↓
;jpn: かいふくする。@KEY()↓
;jpn:◆なにが どのくらい↓
;jpn: かいふくするか は↓
;jpn: うんしだい。
;０５０２γ
@KEYNP()
@!

;228ラッキーサンドc
;akm
MSG_EXPL_GDS_FOOD_LUCKY_SAND_C;
←
◆It helps you recover your power...@KEY()↓
◆How much and what you exactly recover depends on your luck!

;jpn:◆たべると↓
;jpn: たいりょくなどが↓
;jpn: かいふくする。@KEY()↓
;jpn:◆なにが どのくらい↓
;jpn: かいふくするか は↓
;jpn: うんしだい。
;０５０３γ
@KEYNP()
@!

;229ラッキーサンドd
;akm
MSG_EXPL_GDS_FOOD_LUCKY_SAND_D;
←
◆It helps you recover your power...@KEY()↓
◆How much and what you exactly recover depends on your luck!

;jpn:◆たべると↓
;jpn: たいりょくなどが↓
;jpn: かいふくする。@KEY()↓
;jpn:◆なにが どのくらい↓
;jpn: かいふくするか は↓
;jpn: うんしだい。
;０５０４γ
@KEYNP()
@!

;230ラッキーサンドe
;akm
MSG_EXPL_GDS_FOOD_LUCKY_SAND_E;
←
◆It helps you recover your power...@KEY()↓
◆How much and what you exactly recover depends on your luck!

;jpn:◆たべると↓
;jpn: たいりょくなどが↓
;jpn: かいふくする。@KEY()↓
;jpn:◆なにが どのくらい↓
;jpn: かいふくするか は↓
;jpn: うんしだい。
;０５０５γ
@KEYNP()
@!

;231ラッキーサンドf
;akm
MSG_EXPL_GDS_FOOD_LUCKY_SAND_F;
←
◆It helps you recover your power...@KEY()↓
◆How much and what you exactly recover depends on your luck!

;jpn:◆たべると↓
;jpn: たいりょくなどが↓
;jpn: かいふくする。@KEY()↓
;jpn:◆なにが どのくらい↓
;jpn: かいふくするか は↓
;jpn: うんしだい。
;０５０６γ
@KEYNP()
@!

;232コーヒー
;akm
MSG_EXPL_GDS_COFFEE;marcus
←
@GOSUB(_GDS_DRINK_HP_RECOVER)
１２
@GOSUB(_GDS_HP_RECOVER)
@KEY()↓
◆I guess it tastes good to adults.

;jpn:◆おとなの あじ。
@KEYNP()
@!

;233ダブルバーガー
;akm
MSG_EXPL_GDS_HAMBURGER_DOUBLE
←
@GOSUB(_GDS_EAT_HP_RECOVER)
９０
@GOSUB(_GDS_HP_RECOVER)
@KEY()↓
◆１００％ beef.

;jpn:◆ビーフ１００パーセント。
@KEYNP()
@!

;234アーモンドもなか
;akm
MSG_EXPL_GDS_CANDY_SOUR;marcus
←
◆It’s one of Mr Saturn’s favorite foods.@KEY()↓
◆It tastes pretty yummy.@KEY()↓

;jpn:◆どせいさんの だいこうぶつ。↓
;jpn:◆わりと おいしかったです。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
１００
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;235ブタようかん
;akm
MSG_EXPL_GDS_CANDY_BITTER;marcus
←
◆It’s one of Mr. Saturn’s favorite foods.@KEY()↓
◆It tastes all right.@KEY()↓

;jpn:◆どせいさんの だいこうぶつ。↓
;jpn:◆けっこう おいしかったです。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
３００
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;236やぎバターがゆ
;akm
MSG_EXPL_GDS_OKAYU;
←
◆An everyday dish in Dalaam.@KEY()↓

;jpn:◆ランマの いっぱんてきな↓
;jpn: しょくじ。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
２００
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;237まめのコロッケ
;akm
MSG_EXPL_GDS_BEANS_CROQUETTE;marcus
←
◆A croquette made with mashed chick peas, then breaded and deep fried.@KEY()↓
◆Gen−san in Scaraba loves to cook this.@KEY()↓
◆Salt improves it and the olive oil gives it a wonderful↓
;改行しました(三浦兄)
  flavor.@KEY()↓

;jpn:◆スカラビげんさんの↓
;jpn: ひよこまめを すりつぶし↓
;jpn: コロモをつけて あげたコロッケ。@KEY()↓
;jpn:◆しおあじが きいていて‥‥@KEY()↓
;jpn:◆ふるいアブラが また↓
;jpn: いいあじを だしている。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
４０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;238モロヘイヤスープ
;akm
MSG_EXPL_GDS_MOLOKHEIYA_SOUP;marcus
←
◆Molokheiya is a summer vegetable from Scaraba.@KEY()↓
◆It’s high in nutrients, and it has a light flavor that Scarabans love.@KEY()↓

;jpn:◆モロヘイヤは↓
;jpn: スカラビめいさんの↓
;jpn: なつやさい。@KEY()↓
;jpn:◆たかい えいようと↓
;jpn: あっさりあじが@KEY()↓
;jpn:◆スカラビのひとびとに↓
;jpn: このまれている。@KEY()↓
@GOSUB(_GDS_DRINK_HP_RECOVER)
８０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;239そまつなパン
;akm
MSG_EXPL_GDS_GUMI_BREAD;marcus
←
◆I don’t have a lot to say about this.@KEY()↓
◆I guess there are some people who think it’s good.@KEY()↓

;jpn:◆あまり せつめいしたくない。@KEY()↓
;jpn:◆うまいという ひともいる。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
８０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;240コンガリくしやき
;akm
MSG_EXPL_GDS_MUTTON_ON_SKEWERS;marcus
←
◆Broiled lamb’s liver, etc. all served on a skewer.@KEY()↓
◆Sometimes meat other than lamb is included.....@KEY()↓
◆that’s what someone told me...@KEY()↓

;jpn:◆ヒツジのレバーなどを↓
;jpn: てつのくしに さして↓
;jpn: コンガリやいたもの。@KEY()↓
;jpn:◆たまに ヒツジいがいの↓
;jpn: にくが まざっている@KEY()↓
;jpn:◆‥‥という ウワサもある。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
１２０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;241そぼくなヨーグルト
;akm
MSG_EXPL_GDS_GUMI_YOGURT;
←
◆Tastes okay in some respects.@KEY()↓

;jpn:◆あるいみで おいしい。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
１６０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;242ほしにく
;akm
MSG_EXPL_GDS_DRY_MEAT;
←
◆Recipe for making jerky.@KEY()↓
◆Obtain some type of meat, slice it into pieces about a half of an inch thick.@KEY()↓
◆Hang the pieces on a laundry line or something like it@KEY()↓
◆and leave out in the sun for maybe ６ months...@KEY()↓
◆Well, that’s what my recipe says.@KEY()↓

;jpn:◆ほしにくの つくりかた。@KEY()↓
;jpn:◆そのへんにある にくを↓
;jpn: １ミリのうすさに きる。@KEY()↓
;jpn:◆そこらへんにある↓
;jpn: ものほしざおに かけ@KEY()↓
;jpn:◆はんとしかん↓
;jpn: おひさまに あてる。@KEY()↓
;jpn:◆らしい。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
１５０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;243マンモスバーガー
;akm
MSG_EXPL_GDS_HAMBURGER_MAMMOTH
←
@GOSUB(_GDS_EAT_HP_RECOVER)
２００
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;244スパイシーほしにく
;akm
MSG_EXPL_GDS_DRY_MEAT_GREAT
←
◆Recipe for making spicy↓
;改行しました(三浦兄)
  jerky.@KEY()↓
◆Obtain some type of meat,@KEY()↓
◆slice it into pieces about a half of an inch thick.@KEY()↓
◆Season the pieces as much as possible,@KEY()↓
◆hang the pieces on a laundry line or something like it@KEY()↓
◆and leave out in the sun for maybe ８ months...@KEY()↓
◆Well, that’s what my recipe says...@KEY()↓

;jpn:◆スパイシーほしにくの↓
;jpn: つくりかた。@KEY()↓
;jpn:◆そのへんにある にくを↓
;jpn: １ミリのうすさに きる。@KEY()↓
;jpn:◆いやになるほど↓
;jpn: カライあじつけを する。@KEY()↓
;jpn:◆そこらへんにある↓
;jpn: ものほしざおに かけ@KEY()↓
;jpn:◆はんとしかん↓
;jpn: おひさまに あてる。@KEY()↓
;jpn:◆らしい。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
２５０
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;245ゼイタクほしにく
;akm
MSG_EXPL_GDS_DRY_MEAT_SP;marcus
←
◆A gourmet version of jerky that is considered a delicacy.@KEY()↓
◆It is created by a skillful artisan@KEY()↓
◆who has been making jerky for over ６０ years.@KEY()↓
◆Jerky fans consider this the caviar of all jerkys.@KEY()↓
◆I understand that they don’t dry gourmet jerky on a laundry line...@KEY()↓

;jpn:◆ほしにく ひとすじ ６０ねんの↓
;jpn: しょくにんさんが つくった↓
;jpn: ゼイタクな いっぴん。@KEY()↓
;jpn:◆ほしにくずき には↓
;jpn: たまらない。@KEY()↓
;jpn:◆ほすときに ものほしざおは↓
;jpn: つかわない@KEY()↓
;jpn:◆らしい。@KEY()↓
@GOSUB(_GDS_EAT_HP_RECOVER)
３００
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;246たかいみず
;akm
MSG_EXPL_GDS_WATER_HI;marcus
←
◆Very expensive water,@KEY()↓
◆but almost the same as the water you drink in town.@KEY()↓
◆It recovers PP a little bit.

;jpn:◆すごくねだんが たかいみず。@KEY()↓
;jpn:◆まちでのむ みずと↓
;jpn: ほとんど かわりはない。@KEY()↓
;jpn:◆のむと↓
;jpn: PPが↓
;jpn: わずかに
;@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;247マジックプリン
;akm
MSG_EXPL_GDS_MAGIC_PUDDING;marcus
←
◆Recovers about ４０ PP.

;jpn:◆たべると↓
;jpn: PPが↓
;jpn: やく４０
;@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;248たのしいフライパン
;akm
MSG_EXPL_GDS_FLYPAN_OOKINA
←
@GOSUB(_GDS_PAULA_WEAPON)
@KEYNP()
@!

;249どせいさんのコイン
;akm
MSG_EXPL_GDS_COIN_DOSEI;marcus
←
@GOSUB(_GDS_COIN)
@KEY()↓
◆It’s not money even though it’s called a coin.

;jpn:◆コインといっても↓
;jpn: おかねでは ないらしい。
@KEYNP()
@!

;250メテオニウム
;akm
MSG_EXPL_GDS_PRECIOUS_METAL
←
◆It can be sold for a very high price.@KEY()↓
◆Nothing happens if you use it.@KEY()↓
◆A good explanation is kind of tough...

;jpn:◆こうかなねだんで↓
;jpn: かいとって もらえそう。@KEY()↓
;jpn:◆つかっても↓
;jpn: なにも おこらない。@KEY()↓
;jpn:◆なかなか せつめいしにくい↓
;jpn: ぶっしつ。
@KEYNP()
@!

;251アイスキャンデー
;akm
MSG_EXPL_GDS_ICE_CANDY_E
←
@GOSUB(_GDS_EAT_HP_RECOVER)
１８
@GOSUB(_GDS_HP_RECOVER)
@KEYNP()
@!

;252いのちのうどん
;akm
MSG_EXPL_GDS_LIFE_HORN_E
@GOTO(MSG_EXPL_GDS_LIFE_HORN)		;同じ効用
;←
;◆きぜつした なかまを↓
; カムバックさせる。@KEY()↓
;@GOSUB(_GDS_HEAL_A)
;@GOSUB(_GDS_HEAL_B)
;@GOSUB(_GDS_HEAL_C2)
;@KEYNP()
;@!

;253うさぎごのみニンジン
;akm
MSG_EXPL_GDS_KEY_CARROT;marcus
←
◆A special type of bunny’s favorite carrot.

;jpn:◆うさぎさんのすきな↓
;jpn: ニンジン。
@KEYNP()
@!

;=====================================================================
;		サブルーチン群 / 人間optimized by noe 
;=====================================================================

;::::::::::::::::::::::::::::::::
;::::::::::::: PSI ::::::::::::::
;::::::::::::::::::::::::::::::::

;★ひっさつ
;akm
_PSI_HISSATSU;marcus
◆A deadly PSI attack which only @DSP_NAME(PC_NESS) can use.↓
◆It’s a psychokinetic wave generated by concentration that deals

;jpn:◆@DSP_NAME(PC_NESS)だけがつかいこなせる ひっさつPK。↓
;jpn:◆せいしんしゅうちゅうによる ねんどうは が
@!

;★ファイアー
;akm
_PSI_FIRE;marcus
;akm◆Fire bursts from the fingers and a row of enemies take 

◆Fire bursts from the fingers and a row of enemies take

;jpn:◆ゆびさきから ほのおがとびだし↓
;jpn: いちれつにならんだ てき ぜんいんに
@!

;★フリーズ
;akm
_PSI_FREEZ;marcus
;akm◆Causes very cold wind around the enemy and

◆Causes a very cold wind to swirl around one enemy,

;jpn:◆てきのまわりに つめたいかぜをまきおこし
@!

_PSI_FREEZ_2;
◆May freeze the enemy completely.

;jpn:◆てきをこおりづけにして かたまらせることもある。
@!

;★サンダー
;akm
_PSI_THUNDER;marcus
◆You may miss when there are few enemies.↓

;akm◆You may miss the target if there are not enough number of enemies.

◆Eliminates a psychic or psychic power shield.

;jpn:◆てきのかずがすくないと はずれてしまう。↓
;jpn:◆サイコシールドや はんげきのサイコシールドをきりさく。
@!

;★フラッシュ
;akm
;PKフラッシュ
;--------------------------------------------------------------
;アルファ                7/8 涙止まらず                  1/8 変
;ベータ  1/8 気絶        5/8 涙止まらず  1/8 しびれ      1/8 変
;ガンマ  2/8 気絶        4/8 涙止まらず  1/8 しびれ      1/8 変
;オメガ  3/8 気絶        3/8 涙止まらず  1/8 しびれ      1/8 変

_PSI_FLUSH_1;marcus
◆It generates a strong flash and can make the enemy

;akm◆Generates strong flash and makes all the enemy at the scene

;jpn:◆はげしいひかりを はなち てきぜんいんを
@!

_PSI_FLUSH_2
 start crying uncontrollably

;jpn: 「なみだがとまらない」じょうたいにする。
@!

;★スターストーム
;akm
_PSI_STARSTORM_1;marcus
◆The method of ”shaking off the stars” which @DSP_NAME(PC_POO) learned in his training.

;jpn:◆@DSP_NAME(PC_POO)が しゅぎょうによりおぼえた↓
;jpn: 「ほしを おとす ほうほう」。
@!

;★シールド
;akm
_PSI_SHIELD_HALVE;marcus
◆Decreases by one half the amount of damage caused by an enemy’s hit.

;jpn:◆てきからうける だげきこうげきのダメージが↓
;jpn: はんぶんになる。
@!

_PSI_SHIELD_HALVE_REPEL;marcus
◆Decreases by one half the damage caused by an enemy’s hit.  The damage that was blocked is then dealt back to the enemy.

;jpn:◆だげきこうげきのダメージが↓
;jpn: はんぶんになり のこりを はねかえす。
@!

;★サイコシールド
;akm
_PSI_PSI_SHIELD_HALVE;marcus
◆It can block an enemy’s PSI attack.

;jpn:◆てきからうける PSIこうげきを↓
;jpn: むこうにする。
@!

_PSI_PSI_SHIELD_REPEL;marcus
◆It reflects an enemy’s PSI attack back to the attacker.

;jpn:◆てきからうける PSIこうげきを↓
;jpn: そのままはねかえす。
@!

;★さいみんじゅつ
;akm
_PSI_SAIMIN_SUPPLEMENT
;◆てきの ちのうが↓
; たかいほど かかりにくい。
@!

;★サイマグネット
;akm
_PSI_PSI_MAGNET_BASIC;marcus
;akm  Grabs ２−８ points from the enemy and adds it to your own.

;jpn: ２〜８ポイント うばいとり↓
;jpn: じぶんのものにする。
@!

;★パラライシス
;akm
_PSI_PARALYSIS_BASIC;marcus
;akm  Makes the object ”numbed” condition.

 ”numbed” condition.

;jpn: 「しびれ」じょうたいにする。
@!

;★ブレインショック
;akm
_PSI_BRAIN_SHOCK_BASIC;marcus
;akm  Makes the object ”unususl” condition.

 Makes the target feel strange.

;jpn: 「へん」じょうたいにする。↓
;◆てきの ちのうしすうが↓
; たかいほど かかりやすい。
@!

;★テレポート
;akm
_PSI_TELEPORT_BASIC;marcus
◆Allows you to immediately return to a place where you have already been.

;jpn:◆いままでに いったことがあるばしょへ↓
;jpn: しゅんかんに いどうできる。
@!


;★グローバル
;akm
_PSI_USE_PILE;marcus
◆It is most effective if you use this power multiple times to ”layer” the effect.

;jpn:◆かさねて つかうと こうかてき。
;１２３４５６７８９０１２３４５６７８９
@!

_PSI_NOT_EFFECTIVE_ON_SOME;marcus
◆It may not be so effective against some enemies.

;jpn:◆あまり こうかのない てきもいる。
@!

;::::::::::::::::::::::::::::::::
;:::::::::::: GOODS :::::::::::::
;::::::::::::::::::::::::::::::::

;★ぬいぐるみ
;akm
_GDS_NUIGURUMI
A cute teddy bear!

;jpn:かわいい↓
;jpn: クマの↓
;jpn: ぬいぐるみだ。
@!

;★こわれた××全般
;akm
_GDS_JEFF_REPAIR;marcus
◆That genius @DSP_NAME(PC_JEFF) should be able to fix it sometime.

;jpn:◆てんさい@DSP_NAME(PC_JEFF)が↓
;jpn: いつかかならず↓
;jpn: なおしてくれる。
@!

;★××がそうびできるぶき
;akm
_GDS_NESS_WEAPON
◆@DSP_NAME(PC_NESS)

;jpn:◆@DSP_NAME(PC_NESS)が↓
@GOTO(_GDS_WEAPON)

_GDS_PAULA_WEAPON
◆@DSP_NAME(PC_PAULA)

;jpn:◆@DSP_NAME(PC_PAULA)が↓
@GOTO(_GDS_WEAPON)

_GDS_JEFF_WEAPON
◆@DSP_NAME(PC_JEFF)

;jpn:◆@DSP_NAME(PC_JEFF)が↓
@GOTO(_GDS_WEAPON)

_GDS_POO_WEAPON
◆@DSP_NAME(PC_POO)

;jpn:◆@DSP_NAME(PC_POO)が↓
@GOTO(_GDS_WEAPON)

_GDS_WEAPON
 can equip this weapon.

;jpn: そうびできる↓
;jpn: ぶき。
@!

;★おまもり
;akm
_GDS_AMULET;marcus
@GOSUB(_GDS_EQUIP_BODY)
◆It protects you from paralysis attacks.

;jpn:◆パラライシスこうげきから↓
;jpn: みをまもる。
@!

;★ボディそうび
;akm
_GDS_EQUIP_BODY;marcus
;◆ボディに みにつけるもの。
;次のように変えました/上野
◆Must be equipped on your body.

;jpn:◆ボディに そうびするもの。
@KEY()↓
@!

;★うでそうび
;akm
_GDS_EQUIP_ARM;marcus
◆Must be equipped on your arm.@KEY()↓
◆It increases your Defense.

;jpn:◆うでに つけるもの。↓
;jpn:◆ぼうぎょりょく アップ。
@!

_GDS_EQUIP_ARM_B;marcus
◆Helps keep you from being hypnotized, and it also increases your Luck.

;jpn:◆さいみんじゅつに↓
;jpn: かかりにくくなって↓
;jpn: ラックも あがる。
@!

;★そのたそうび
;akm
_GDS_EQUIP_MISC;
◆Must be equipped as ”other.”

;jpn:◆いわゆる そのたそうび。
@!

;★コイン
;akm
_GDS_COIN
@GOSUB(_GDS_EQUIP_MISC)@KEY()↓
◆Increases your Defense and Luck.

;jpn:◆みにつけると↓
;jpn: ぼうぎょりょくが あがり↓
;jpn: ラックも あがる。
@!

;★××のそのたそうび
;akm
_GDS_PAULA_EQUIP_MISC;marcus
◆Miscellaneous equipment that can only be used by @DSP_NAME(PC_PAULA).

;jpn:◆@DSP_NAME(PC_PAULA)せんようの↓
;jpn: そのたそうび。
@!

_GDS_POO_EQUIP_MISC
◆Miscellaneous equipment that can only be used by @DSP_NAME(PC_POO).

;jpn:◆@DSP_NAME(PC_POO)せんようの↓
;jpn: そのたそうび。
@!

;★たいりょくがかいふくする
;akm
_GDS_EAT_HP_RECOVER;marcus
◆When eaten, you recover about

;jpn:◆たべると↓
;jpn: たいりょくが↓
;jpn: やく
@!

_GDS_DRINK_HP_RECOVER;marcus
◆If you drink this, you recover about 
;jpn:◆のむと↓
;jpn: たいりょくが↓
;jpn: やく
@!

_GDS_HP_RECOVER

 HP.
;jpn: かいふくする。
@!

_GDS_HEAL_A;
◆In addition, it also works well on poison, nausea,@KEY()↓
;jpn:◆そのほかにも↓
;jpn: どく きもちわるい@KEY()↓
@!

_GDS_HEAL_B;marcus
◆colds, sunstroke, falling asleep, uncontrollable crying, and feeling strange.

;jpn:◆かぜ にっしゃびょう いねむり↓
;jpn: なみだがとまらない へん@KEY()↓
@!

_GDS_HEAL_C1;marcus
;akmworks well on

;jpn:◆に よくききます。
@!

_GDS_HEAL_C2
;akmcures

;jpn:◆も なおります。
@!

_GDS_HEAL_D;marcus
◆This is effective when you have paralysis, or you have been diamondized.

;jpn:◆ダイヤモンドになってしまったり↓
;jpn: しびれたときも↓
;jpn: これ。
@!

_GDS_TOPPING_HP_RECOVER;marcus
◆To use, sprinkle over food.@KEY()↓
◆A good combination increases the strength of your recovery.

;jpn:◆たべものに↓
;jpn: かけてつかう。@KEY()↓
;jpn:◆おいしい くみあわせで↓
;jpn: かいふくりょく アップ。
@!

;★何度でもつかえる
;akm
_GDS_USE_MANY_TIMES
◆Can be used many times.

;jpn:◆なんどでも つかえる。
@!

;★一度使うとなくなる
;akm
_GDS_USE_ONCE;marcus
◆Gone after one use.
 
;jpn:◆いちどつかうと なくなる。
@!

;★××のグッズ
;akm
_GDS_FOR_JEFF;marcus
◆Items for @DSP_NAME(PC_JEFF).@KEY()↓

;jpn:◆@DSP_NAME(PC_JEFF)のグッズ。@KEY()↓
@!

;★敵にダメージを与える
;akm
_GDS_DAMAGE;marcus
◆Damages an enemy when used during battle.

;jpn:◆せんとうじ↓
;jpn: てきにダメージを あたえる。
@!

_GDS_EQUIP_LUCK_UP;marcus
◆When equipped, it increases your Luck.
;jpn:◆みにつけると↓
;jpn: ラックも あがる。
@!

;1 2 3 4 5 6 7 8 91011121314151617
;1 2 3 4 5 6 7 8 910111213141516171819202122232425262728
