;/////////////////////////マップ専用グッズ(３／３)////////////////////////

;寄宿舎のロッカー
MSG_WINS_LOCKER;
◆This one is locked.
;jpn:◆ロッカーには↓
;jpn: カギが かかっている。
@KEYNP()
@!

MSG_WINS_LOCKER_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@Q_HAVE(PC_ALL,GDS_EQUIP_GUN_BANBAN)
@TRUE_GOTO(_WINS_LOCKER_EMPTY)
@SET_LOOPREG(GDS_EQUIP_GUN_BANBAN)
@GOSUB(_SUB_WINS_LOCKER_PART3)
@!

MSG_WINS_LOCKER_B_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@Q_HAVE(PC_ALL,GDS_EQUIP_CAP_HOLMES)
@TRUE_GOTO(_WINS_LOCKER_EMPTY)
@SET_LOOPREG(GDS_EQUIP_CAP_HOLMES)
@GOSUB(_SUB_WINS_LOCKER_PART3)
@!

MSG_WINS_LOCKER_C_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@Q_HAVE(PC_ALL,GDS_HAVE_BROKEN_AIRGUN)
@TRUE_GOTO(_WINS_LOCKER_EMPTY)
@SET_LOOPREG(GDS_HAVE_BROKEN_AIRGUN)
@GOSUB(_SUB_WINS_LOCKER_PART3)
@!

MSG_WINS_LOCKER_D_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@Q_HAVE(PC_ALL,GDS_HAVE_BROKEN_SPRAY)
@TRUE_GOTO(_WINS_LOCKER_EMPTY)
@SET_LOOPREG(GDS_HAVE_BROKEN_SPRAY)
@GOSUB(_SUB_WINS_LOCKER_PART3)
@!

MSG_WINS_LOCKER_E_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@GOSUB(_WINS_LOCKER_EMPTY)
@!

MSG_WINS_LOCKER_F_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@GOSUB(_WINS_LOCKER_EMPTY)
@!

MSG_WINS_LOCKER_G_RECEIVE;
@GOSUB(_SUB_WINS_LOCKER_PART1)
@TRUE_GOTO(_WINS_LOCKER_LOCKER)
@GOSUB(_SUB_WINS_LOCKER_PART1B)
@FALSE_GOTO(_WINS_LOCKER_RECEIVE_NG)
@GOSUB(_SUB_WINS_LOCKER_PART2)
@GOSUB(_WINS_LOCKER_EMPTY)
@!

_SUB_WINS_LOCKER_PART1;
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_LOCKER)
@!

_SUB_WINS_LOCKER_PART1B;
@LOAD_REG()
@XCHG()
@EQ(GDS_TOOL_KEY_CHOTTO)
@!

_SUB_WINS_LOCKER_PART2;
@LOAD_REG()
@XCHG()
◆@DSP_NAME(0) opened the locker using the @DSP_GOODS(GDS_TOOL_KEY_CHOTTO).
;jpn:◆@DSP_NAME(0)は↓
;jpn: 「ちょっとカギマシン」をつかって↓
;jpn: ロッカーを あけた。
@SE(SE_se77_my_open_locker)
@KEY()
←
@!
_SUB_WINS_LOCKER_PART3;●(akm0616 w/itoi)
@SET_REG(1)
◆There was a @DSP_GOODS(0) in the locker.
;jpn:◆ロッカーのなかには↓
;jpn: @DSP_GOODS(0)が↓
;jpn: はいっていた。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_WINS_LOCKER_GOODSFULL)
@SAVE_REG()
@GOODSIN_PLAYER(0,0)
@LOAD_REG()
@XCHG()
◆@DSP_NAME(0)
;jpn:◆@DSP_NAME(0)は↓
@XCHG()
 got↓
  the @DSP_GOODS(0).
;＠it?三浦
;jpn: @DSP_GOODS(0)を↓
;jpn: てにいれた。
@KEYNP()
@SE(SE_se74_my_get)
@WI(1)
@!

_WINS_LOCKER_LOCKER;
@LOAD_REG()
←
◆(The key is bent and doesn’t fit into the key hole!)
;jpn:◆(カギが まがっていて↓
;jpn: カギあなに はいらない!)
@KEYNP()
@SETF(FLG_WINS_LOCKER_FAILED)
@!

_WINS_LOCKER_EMPTY;
◆(Unfortunately, there is nothing in this locker.)
;jpn:◆(ざんねんながら↓
;jpn: このロッカーには↓
;jpn: なにもなかった)
@KEYNP()
@!

_WINS_LOCKER_GOODSFULL;
◆However, you already have too many things to carry.
;jpn:◆しかし もちものが↓
;jpn: いっぱいだった。
@KEY()↓
@GET_ORDER_PLAYER(1)
@XCHG()
◆@DSP_NAME(0)
;jpn:◆@DSP_NAME(0)は↓
@XCHG()
 left the @DSP_GOODS(0) in the locker.
;＠it?
;jpn: @DSP_GOODS(0)を↓
;jpn: ロッカーにもどした。
@KEYNP()
@!

;墓場の牢屋
MSG_THRK_PRISON;
@CHKFGOTO(FLG_THRK_PRISON_OPEN,MSG_END)
@GOSUB(_SUB_DOOR_LOCKED_MES)
@CHKFGOTO(FLG_JEFF,MSG_END);ジェフ仲間にしてたら祈らない
@CLOSEALL()
@WI(1)
@GOSUB(MSG_EVT_PAULA_TELEPATHY_PRISON);ジェフに祈りをS_EVENT
』

MSG_THRK_PRISON_RECEIVE;
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_KEY_CHOTTO)
@FALSE_GOTO(_THRK_PRISON_RECEIVE_NG)
@GOSUB(_SUB_DOOR_OPEN_MES)
@HIDE_CHAR(PRSN_THRK_JAIL_2_C,OBJFX_HIDE_NONE)
@SETF(FLG_THRK_PRISON_OPEN)
@!

_SUB_DOOR_LOCKED_MES;
@OPEN(1)
◆The door is locked.
;jpn:◆とびらには カギが↓
;jpn: かかっている。
@KEYNP()
@CLOSEALL()
@!

_SUB_DOOR_OPEN_MES;
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0)
;jpn:◆@DSP_NAME(0)は↓
@XCHG()
 used↓
  the @DSP_GOODS(0).
;jpn: @DSP_GOODS(0)を つかった。
@KEY()↓
◆The door opened.
;jpn:◆とびらが ひらいた。
@KEYNP()
@SE(SE_se77_my_open_locker)
@!

_ONET_TABIGOYA_RECEIVE_NG;
_WINS_LOCKER_RECEIVE_NG;
_THRK_PRISON_RECEIVE_NG;
◆It wasn’t the right key.
;jpn:◆カギが あわなかった。
@KEYNP()
@!

MSG_BTL_GREORE_MACHINE;
←
◆The Suporma sang the song ”Ode to Orange Kid.”@KEY()↓
◆As soon as it finished, the machine broke down.
;jpn:◆オレンジキッドを↓
;jpn: たたえるうたが きこえた。@KEY()↓
;jpn:◆うたうだけ うたうと↓
;jpn: マシーンはこわれてしまった。
@KEYNP()
@!

MSG_BTL_NOT_SO_GOOD;
←
◆By using the Insignificant Present, you had a very fruitful experience@KEY()↓
◆that cannot be understood by someone who does not use something insignificant.
;jpn:◆たいしたことないものを↓
;jpn: つかうことで‥‥@KEY()↓
;jpn:◆たいしたことないものを↓
;jpn: つかわないひとには えられない↓
;jpn: ゆういぎな けいけんをした。
@KEYNP()
@!


MSG_BTL_MONKEY_MIND;●(akm0616 w/itoi)
←
 @DSP_ACTOR() used the Monkey Love.
;jpn: @DSP_ACTOR()は↓
;jpn: サルのきもちを つかった!
@KEY()
↓
 All of a sudden, a monkey came along,
;jpn: とつぜん↓
;jpn: サルがやってきて↓
@KEY()
↓
 and pinned the enemy down with its tiny monkey body.
;jpn: ちいさいくせに↓
;jpn: てきを はがいじめにした!
@KEY()
@!


MSG_BTL_GUMIDORIAN;
;グミドリアン「つかう(たべる)」
←
◆It smelled so unbelievably bad that you could not eat it.
;jpn:◆このよのものとは↓
;jpn: おもえないくらい くさくて↓
;jpn: たべられなかった。
@KEYNP()
』


;手紙

MSG_BTL_LETTER_MAMA;
;プレゼントの中の手紙
;ママ
←
◆(Dear @DSP_STS(STS_PC_NAME_NES),↓
 How are you?@KEY()↓
◆Since you left home on your journey, things have changed around here.@KEY()↓
◆For example, I don’t have as much laundry.@KEY()↓
◆Also, we don’t seem to eat @DSP_STS(STS_PARTY_FAVORITE_FOODS) as much as we used to.@KEY()↓
◆I heard that you defeated some universal evil character−−what was it,@KEY()↓
◆Googi, or something like that?@KEY()↓
◆Well, that sounds really great!↓
  I want to hear all the details, so hurry home, okay?@KEY()↓
◆Tracy, @DSP_STS(STS_PARTY_DOG_NAME) and I are waiting for you.↓
                Love,↓
                Mama)
;jpn:◆(@DSP_STS(STS_PC_NAME_NES) げんき?@WI(20)↓
;jpn: あなたが↓
;jpn: ぼうけんの たびにでてから@KEY()↓
;jpn:◆いろいろ わがやにも↓
;jpn: へんかが ありました。@KEY()↓
;jpn:◆ひとつは↓
;jpn: あなたの せんたくものが↓
;jpn: へったこと。@KEY()↓
;jpn:◆もうひとつは あなたがいないので↓
;jpn: @DSP_STS(STS_PARTY_FAVORITE_FOODS)を たべるかいすうが↓
;jpn: へったことです。@KEY()↓
;jpn:◆ところで グーギとかいう↓
;jpn: あくの とりしまりを↓
;jpn: たいじしたんですってね。@KEY()↓
;jpn:◆すごいわ。@WI(30)↓
;jpn: ママも はなしを ききたいから↓
;jpn: はやく かえってきてね。@KEY()↓
;jpn:◆トレーシーと@DSP_STS(STS_PARTY_DOG_NAME)と↓
;jpn: まっています。↓
;jpn:           ママより)
@KEYNP()
』


MSG_BTL_LETTER_TONY;
;トニー
←
◆(Dear @DSP_STS(STS_PC_NAME_JEFF),↓
  Everything’s really going great here.@KEY()↓
◆I wish I could have gone with you on your adventure, even just part of the way,@KEY()↓
◆but instead I’m sitting here, waiting for you in Winters.@KEY()↓
◆I want to see you again as soon as possible.  I can’t wait to see your cheerful face.@KEY()↓
◆I bet your glasses are dirty... If you come back, I’ll clean them for you!@KEY()↓
◆Like I said, I’m waiting for you.↓
                Yours truly,↓
                Tony @KEY()↓
↓
◆P.S.  Don’t show this letter to anyone!)
;jpn:◆(しんあいなる @DSP_STS(STS_PC_NAME_JEFF)↓
;jpn: ぼくは げんきです。@KEY()↓
;jpn:◆ぼくも きみの ぼうけんのたびの↓
;jpn: てつだいが ちょっとでも↓
;jpn: できたらいいと おもったけど@KEY()↓
;jpn:◆けっきょく ぼくは‥‥@KEY()↓
;jpn:◆きみを ウィンターズで↓
;jpn: まっていることしか↓
;jpn: できませんでした。@KEY()↓
;jpn:◆はやく あいたいよ。@WI(20)↓
;jpn: きみの げんきなかおを↓
;jpn: いっこくも はやく みたい。@KEY()↓
;jpn:◆きみの めがねのくもりを↓
;jpn: ふいてあげたい。@KEY()↓
;jpn:◆まってるよ。@WI(30)↓
;jpn: しんあいなる @DSP_STS(STS_PC_NAME_JEFF)へ。@KEY()↓
;jpn:          トニーより@KEY()@WI(60)↓↓
;jpn:◆PS このてがみは↓
;jpn: ほかのひとには みせないでね)
@KEYNP()
』


MSG_BTL_LETTER_CHILD;
;幼稚園児
←
◆(Dear @DSP_STS(STS_PC_NAME_PAULA),↓
  How are you doing?↓
  I’m fine.@KEY()↓
◆I fine too!@KEY()↓
◆So are me!@KEY()↓
◆Me also!@KEY()↓
◆Me okay.@KEY()↓
◆Please come and play with us again at the Polestar Pre−school.@KEY()↓
◆Oh yeah, one more thing, bring us some presents...if you have any.@KEY()↓
◆               Sincerely,↓
                Your friends at the↓
                Polestar Pre−school)
;jpn:◆(@DSP_STS(STS_PC_NAME_PAULA) おねえちゃん。@WI(20)↓
;jpn: おげんきですか?↓
;jpn: わたしは げんきです。@KEY()↓
;jpn:◆ぼくも げんきです。@KEY()↓
;jpn:◆ぼくも げんきです。@KEY()↓
;jpn:◆おいらも げんきです。@KEY()↓
;jpn:◆あたいも げんきです。@KEY()↓
;jpn:◆また ポーラスターようちえんで↓
;jpn: いっぱい あそんでください。@KEY()↓
;jpn:◆おみやげ‥‥もしあったら↓
;jpn: もってきてね。@KEY()↓
;jpn:◆ ポーラスターようちえんの↓
;jpn:          みんなより)
@KEYNP()
』

MSG_BTL_DRY_MEAT_SPECIAL;●(akm0616 w/itoi)
←
◆You would probably regret it if you ate this now...
;jpn:◆たべてしまうと↓
;jpn: あとで こまるような↓
;jpn: きがする‥‥たぶん。
@KEY()
@!

;受信電話

MSG_BTL_PHONE_RECEIVER;
←
◆This phone  only receives calls.  You cannot make outgoing calls from it.
;jpn:◆このでんわは↓
;jpn: じゅしんせんようなので↓
;jpn: こちらからは かけられません。
@KEY()
@!

