;//////////////////////////グッズ系の行動時メッセージ/////////////////

MSG_BTL_HP4;
MSG_BTL_HP50G;
MSG_BTL_HP200G;
MSG_BTL_LIFEUP_A;
MSG_BTL_LIFEUP_B;
MSG_BTL_LIFEUP_Y;
MSG_BTL_PP20G;
MSG_BTL_PP80G;
MSG_BTL_BENTO;
MSG_BTL_CANDY;
MSG_BTL_MAZUI_PAN;
MSG_BTL_UMAI_PAN;
MSG_BTL_G_WATER;
MSG_BTL_IQ4;
MSG_BTL_GUTS4;
MSG_BTL_SPEED4;
MSG_BTL_VITA4;
MSG_BTL_LUCK4;
MSG_BTL_EAT_ONE;＠＄

@GET_CITEM()
@XCHG()
@GET_GOODS_EAT(0)
@EQ(2)
@TRUE_GOTO(_BTL_DRINK)
@GET_SPICE(0)
@TRUE_GOTO(_BTL_SPICE)
@Q_SELF()
@TRUE_GOTO(_BTL_EAT_SELF)
←
◆@DSP_ACTOR() took↓
  the @DSP_GOODS(0) out and@KEY()↓
◆@DSP_OBJECT() ate it.
;jpn:◆@DSP_ACTOR()は↓
;jpn: @DSP_GOODS(0)を とりだし@KEY()↓
;jpn:◆@DSP_OBJECT()に たべさせた。
@SE(SE_se44_b_eat)
@KEY()
@!

_BTL_EAT_SELF;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 ate↓
  the @DSP_GOODS(0).
;jpn: @DSP_GOODS(0)を たべた。
@SE(SE_se44_b_eat)
@KEY()
@WI(1)
@!

_BTL_SPICE;＠＄
@XCHG()
@SAVE_REG()
@Q_SELF()
@TRUE_GOTO(_BTL_SPICE_SELF)
←
@SAVE_REG()
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 took↓
  the @DSP_GOODS(0),@KEY()↓
;jpn: @DSP_GOODS(0)を とりだし@KEY()↓
@LOAD_REG()
  put it on↓
  @DSP_GOODS(0) and@KEY()↓
  @DSP_OBJECT() ate it.
;jpn:◆@DSP_GOODS(0)を かけて↓
;jpn: @DSP_OBJECT()に たべさせた。
@SE(SE_se44_b_eat)
@WI(1)
@KEY()
@!

_BTL_SPICE_SELF;＠＄
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 took↓
  the @DSP_GOODS(0)@KEY()↓
;jpn: @DSP_GOODS(0)を とりだし@KEY()↓
@LOAD_REG()
◆and ate it over↓
  the @DSP_GOODS(0).
;jpn:◆@DSP_GOODS(0)を↓
;jpn: かけて たべた。
@SE(SE_se44_b_eat)
@WI(1)
@KEY()
@!

_BTL_DRINK;＠＄
@Q_SELF()
@TRUE_GOTO(_BTL_DRINK_SELF)
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 took↓
  the @DSP_GOODS(0)@KEY()↓
  and @DSP_OBJECT() drank it.
;jpn: @DSP_GOODS(0)を とりだして@KEY()↓
;jpn:◆@DSP_OBJECT()に のませた。
@SE(SE_se44_b_eat)
@WI(1)
@KEY()
@!

_BTL_DRINK_SELF;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 drank↓
  the @DSP_GOODS(0).
;jpn: @DSP_GOODS(0)を のんだ。
@SE(SE_se44_b_eat)
@WI(1)
@KEY()
@!

MSG_BTL_EAT_ALL;
←
◆@GOSUB(MSG_ESUB_DSP_PARTY)
;jpn:◆@DSP_LCNAME()は みんなで↓
@GET_CITEM()
@XCHG()
 ate↓
  the @DSP_GOODS(0) together.
;jpn: @DSP_GOODS(0)を たべた。
@SE(SE_se44_b_eat)
@WI(1)
@KEY()
@!

MSG_BTL_EAT_SPICE_ATARI;
@Q_SELF()
@FALSE_GOTO(_ATARI_END)
←
◆It was pretty good.
;jpn:◆けっこう おいしかった。
@KEY()
_ATARI_END;
@!

MSG_BTL_EAT_SPICE_HAZURE;
@Q_SELF()
@FALSE_GOTO(_HAZURE_END)
←
◆It didn’t taste very good.
;jpn:◆あんまり おいしくなかった。
@KEY()
_HAZURE_END;
@!

MSG_BTL_DRAGON;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は じぶんに↓
@GET_CITEM()
@XCHG()
 sprinkled↓
  the @DSP_GOODS(0) over @GOSUB(MSG_ESUB_HIS_HER_GACT) head.
;jpn: @DSP_GOODS(0)を ふりかけた!
@KEY()↓
◆Yoicks!! @DSP_ACTOR() turned↓
  into a gigantic, fire−breathing dragon!
;jpn: なんと @DSP_ACTOR()は きょだいなドラゴンに↓
;jpn: へんしんして ほのおを はきだした!
@KEY()
@!

MSG_BTL_SPRAY;
MSG_BTL_SPRAY_SP;
MSG_BTL_RUST;
MSG_BTL_RUST_SP;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 sprayed a blast of↓
  @DSP_GOODS(0) out!
;jpn: @DSP_GOODS(0)を ふんしゃした!
@SE(SE_se47_b_spray)
@KEY()
@!

MSG_BTL_PHARAOH;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used↓
  the @DSP_GOODS(0)!
;jpn:@DSP_GOODS(0)を つかった!
@KEY()↓
◆Suddenly, something unknown burst from the box.
;jpn: はこから わけのわからぬものが↓
;jpn: とんででた!
@KEY()
@!


MSG_BTL_NEBANEBA;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()↓
◆Then, something sticky↓
  stuck to the enemy!
;jpn: ねばねばしたものが↓
;jpn: てきに くっついた!
@KEY()
@!
;#####
MSG_BTL_TOFU;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()↓
◆Suddenly, some Trout Yogurt↓
  was produced!
;jpn: なかから いちごとうふが↓
;jpn: とびだした!
@KEY()
@!

MSG_BTL_ROCKET;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 fired↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を はっしゃした!
@SE(SE_se46_b_rocket)
@KEY()
@!

MSG_BTL_ROCKET5;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 fired↓
  the @DSP_GOODS(0)!
;◆@DSP_ACTOR() fired↓
;  the five pencil rockets!
;jpn: @DSP_ACTOR()は↓
;jpn: ペンシルロケットを ５はつ はっしゃした!
@SE(SE_se46_b_rocket)
@WI(8)
@SE(SE_se46_b_rocket)
@WI(8)
@SE(SE_se46_b_rocket)
@WI(8)
@SE(SE_se46_b_rocket)
@WI(8)
@SE(SE_se46_b_rocket)
@WI(8)
@KEY()
@!

MSG_BTL_ROCKET20;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 fired↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を はっしゃした!
;◆@DSP_ACTOR() fired↓
;  the twenty pencil rockets!
;jpn: @DSP_ACTOR()は↓
;jpn: ペンシルロケットを ２０ぱつ はっしゃした!
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@SE(SE_se46_b_rocket)
@WI(4)
@KEY()
@!

MSG_BTL_BAZOOKA
MSG_BTL_BAZOOKA_SP
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 fired↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を はっしゃした!
@SE(SE_se46_b_rocket)
@KEY()
@!

MSG_BTL_BOMB;
MSG_BTL_BOMBSP;
MSG_BTL_KUWAGATA;
MSG_BTL_SOCKS;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 threw↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を なげつけた!
@SE(SE_se46_b_rocket)
;@SE(SE_se1a_b_my_hit)
@KEY()
@!

MSG_BTL_SNAKEBAG;
@GET_CITEM()
@XCHG()
←
◆@DSP_ACTOR() took a snake↓
  out of the @DSP_GOODS(0)@KEY()↓
  and threw it!
;jpn: @DSP_ACTOR()は @DSP_GOODS(0)から↓
;jpn: へびをとりだして なげつけた!
@KEY()
@!

MSG_BTL_HABURASHI;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used @DSP_GOODS(0) and @GOSUB(MSG_ESUB_HIS_HER_GACT) teeth↓
  were white and breath was fresh!
;@Its teeth were bright and fresh!
;jpn: @DSP_GOODS(0)で はをみがいた!↓
;jpn: すばらしく はが ひかった!
@KEY()
↓
◆The brightness of↓
  @DSP_ACTOR()’s teeth@KEY()↓
  made the enemy scared!
;jpn: @DSP_ACTOR()の はのひかりに↓
;jpn: てきは ひるんだ!
@KEY()
@!

MSG_BTL_HOUTAI;
MSG_BTL_BELT;
←
@GET_CITEM()
@XCHG()
◆@DSP_ACTOR() lashed out↓
  with the @DSP_GOODS(0)!
;jpn: @DSP_ACTOR()は↓
;jpn: @DSP_GOODS(0)で ぶった!
@KEY()
@!

MSG_BTL_GUM;
←
@GET_ORDER_PLAYER(2)
@EQ(PC_BALLOONMONKEY)
@FALSE_GOTO(_GUM_NG)
@GOSUB(MSG_EVT_46_51_BALLOON)
@!

_GUM_NG;S_EVENT中に
@GOTO(MSG_EVT_BALLOON_NG)
』

MSG_BTL_SNAKE;
MSG_BTL_SNAKE_POISON;
←
◆@DSP_ACTOR()
;jpn: @DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 threw↓
  the @DSP_GOODS(0)!
;jpn:@DSP_GOODS(0)を なげつけた!
@KEY()↓
◆The @DSP_GOODS(0) is↓
  biting!
;jpn:@DSP_GOODS(0)の かみつきこうげきだ!
@KEY()↓
@!


