;/////////////////////////マップ専用グッズ(１／３)////////////////////////

MSG_BTL_PIGNOSE;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 put↓
  the @DSP_GOODS(0) on @GOSUB(MSG_ESUB_HIS_HER_GACT) nose!
;jpn: @DSP_GOODS(0)を はなにつけた!
@SE(SE_se73_my_fitout)
@KEY()↓
◆@DSP_ACTOR() searched for↓
  the smell of the magic mushroom.
;jpn:◆@DSP_ACTOR()は↓
;jpn: マジックトリフの↓
;jpn: においを さぐった。
@KEY()↓
@SEARCH_TRUFFLE()
@FALSE_GOTO(MSG_SYS_PIGNOSE_NG)
@SAVE_REG()
@EQ(1)
@TRUE_GOTO(MSG_SYS_PIGNOSE_THISSCRN)
@LOAD_REG()
@EQ(10)
@TRUE_GOTO(MSG_SYS_PIGNOSE_FIND)
MSG_SYS_PIGNOSE_NEAR;
@LOAD_REG()
←
◆(It must be a little further @ONGOSUB(MSG_BTL_NULL,_PNOSE2,_PNOSE3,_PNOSE4,_PNOSE5,_PNOSE6,_PNOSE7,_PNOSE8,_PNOSE9).)
;jpn:◆(もっと↓
; @ONGOSUB(MSG_BTL_NULL,_PNOSE2,_PNOSE3,_PNOSE4,_PNOSE5,_PNOSE6,_PNOSE7,_PNOSE8,_PNOSE9)
;jpn:に あるようだ)
@KEYNP()
@!

MSG_SYS_PIGNOSE_FIND;●(akm0616 w/itoi)γ
←
◆(It must be right here!)
;jpn:◆(ズバリ!@WI(30)↓
;jpn: ここに ありそうだ)
;◆ジャン!@WI(30)↓
; マジックトリフを さぐりあてた!
@KEYNP()
@!
;@KEY()↓
;@Q_GOODSFULL(PC_ALL)
;@FALSE_GOTO(_PIGNOSE_GOODSFULL)
;@GOODSIN_PLAYER(0,GDS_FOOD_MAGIC_TRUFFLE)
;@SE(SE_se74_my_get)
;@XCHG()
;◆@DSP_NAME(0)は↓
; マジックトリフを てにいれた!
;@KEYNP()
;@!

;_PIGNOSE_GOODSFULL;
;◆しかし これいじょう↓
; ものを もてない。
;@KEYNP()
;@!

MSG_SYS_PIGNOSE_THISSCRN;
←
◆(It is around here somewhere, but you can’t pinpoint the exact location.)
;jpn: ばしょが とくていできない)
@KEYNP()
@!

MSG_SYS_PIGNOSE_NG;
←
◆(The Truffle doesn’t seem to be around here.)
;jpn:◆(このあたりには↓
;jpn: マジックトリフは なさそうだ)
@KEYNP()
@!

_PNOSE2;
up
;jpn:うえ
@!

_PNOSE3;
up and right
;jpn:みぎうえ
@!

_PNOSE4;
right
;jpn:みぎ
@!

_PNOSE5;
down and right
;jpn:みぎした
@!

_PNOSE6;
down
;jpn:した
@!

_PNOSE7;
down and left
;jpn:ひだりした
@!

_PNOSE8;
left
;jpn:ひだり
@!

_PNOSE9;
up and left
;jpn:ひだりうえ
@!

MSG_SYS_MAGIC_BUTTERFLY;
←
◆Thanks to the Magic Butterfly, you were able to totally relax.
;jpn:◆マジックバタフライのおかげで↓
;jpn: @DSP_LCNAME()は↓
;jpn: とても リラックスできた。
@KEYNP()
@CLOSEALL()
@!

MSG_BTL_KANBAN;
@CHKFGOTO(FLG_MYHOME_TO_BE,_BTL_KANBAN_END);ピッキー中は使えない。
@CHKFGOTO(FLG_WIN_GIEGU,_BTL_KANBAN_END);最終戦闘後は使えない。
@CHKFGOTO(FLG_STEP_PAST,MSG_SYS_GOODS_USE_NG_HERE);過去では使えない
@GOSUB(MSG_SUB_Q_NOW_DELIVERY)
@TRUE_GOTO(_BTL_KANBAN_ALREADY)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER,_BTL_KANBAN_ALREADY)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER_B,_BTL_KANBAN_ALREADY)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER_C,_BTL_KANBAN_ALREADY)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER_D,_BTL_KANBAN_ALREADY)
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()↓
◆A customer is heading this way.
;jpn:◆いま おきゃくさんは↓
;jpn: こちらに むかっている。
@KEYNP()
@CLOSEALL()
@RAND(3)
@ONGOTO(_KANBAN_1,_KANBAN_2,_KANBAN_3)
@DELIVERY(DELIVERY_CUSTOMER_A)
@SETF(FLG_DELIVERY_CUSTOMER)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!
_BTL_KANBAN_ALREADY;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used↓
  the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()↓
◆Wait!  Someone is already heading this way.  Wait for them to get here first.
;jpn:◆ウェイト!@WI(20)↓
;jpn: さきに よんでるひとを↓
;jpn: まってください。
@KEYNP()
』
_BTL_KANBAN_END;
◆For a long time, this ”For Sale” sign has been useful...@KEY()↓
◆Now, it is old, its message made unreadable by the passage of time.@KEY()↓
◆It has now lost its effectiveness.@KEY()↓
◆Thank you, sign.↓
 Good bye, sign.
;jpn:◆ながいあいだ ずいぶん↓
;jpn: べんりに つかえた↓
;jpn: かんばんだったが‥‥@KEY()↓
;jpn:◆ぼろぼろになり↓
;jpn: もじも よめなくなって↓
;jpn: そのこうかは うしなわれた。@KEY()↓
;jpn:◆ありがとう@WI(15) カンバン!@WI(20)↓
;jpn: さようなら@WI(15) カンバン!
@KEYNP()
』

_KANBAN_1;
@DELIVERY(DELIVERY_CUSTOMER_B)
@SETF(FLG_DELIVERY_CUSTOMER_B)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!
_KANBAN_2;
@DELIVERY(DELIVERY_CUSTOMER_C)
@SETF(FLG_DELIVERY_CUSTOMER_C)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!
_KANBAN_3;
@DELIVERY(DELIVERY_CUSTOMER_D)
@SETF(FLG_DELIVERY_CUSTOMER_D)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!

MSG_BTL_BOOK_MUKUCHI;
←
◆This book should be required reading for any quiet, shy person.
;jpn:◆これは↓
;jpn: むくちなひとが よむほんだ。
@KEY()
@!

MSG_BTL_POSTCARD;
←
◆You felt sad and empty.
;jpn:◆なんだか むなしかった。
@KEY()
@!

MSG_BTL_PANKUZU;＠消す?(三浦)
←
◆(If you get this message, it means that something is wrong.)
;jpn:◆(このメッセージが↓
;jpn: でるということは↓
;jpn: なにかが おかしい↓
;jpn: ということです)
@KEY()
@!

MSG_BTL_MANTRA;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 opened↓
  the @DSP_GOODS(0).
;jpn: @DSP_GOODS(0)を ひらいた!
@KEY()↓
◆The enemy may not notice that you are present.
;jpn:◆けはいが きえて↓
;jpn: てきに きづかれなくなった↓
@KEY()
@!


MSG_BTL_CASHCARD;
←
◆To use this, go to a cash machine and insert the card.
;jpn:◆キャッシュディスペンサーにいれて↓
;jpn: つかいます。
@KEY()
@!


MSG_USE_ZOMBIE_HOIHOI;
←
◆This is a kind of trap used to capture zombies.
;jpn:◆ゾンビをあつめる↓
;jpn: ワナの いっしゅです。
@KEY()
@!

MSG_USE_EAGLE_EYE;
←
◆It might be useful in a dark place.
;jpn:◆くらいところで↓
;jpn: やくにたつはずです。
@KEY()
@!

;#ゾンビホイホイをしかける場所でグッズを「つかう」

MSG_BTL_ZOMBIE_HOIHOI;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 placed the @DSP_GOODS(0) on the floor.
;jpn: @DSP_GOODS(0)を ↓
;jpn: ゆかに しかけた。
@SE(SE_se73_my_fitout)
@WI(1)
@KEY()
↓
@SETF(FLG_PUT_ZOMBI_HOIHOI)
@GOODSOUT(PC_ALL,GDS_TOOL_ZOMBI_HOIHOI)
@!


;#「たかのめ」を使う場所でグッズを「つかう」

MSG_BTL_EAGLE_EYE;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった。
@SE(SE_se5f_tasy_appear)
@WI(1)
@KEYNP()
@CLOSEALL()
@GOODSOUT(PC_ALL,GDS_TOOL_EAGLE_EYE)
@SETF(FLG_MAKYO_USE_TAKANOME)
@HIDE_CHAR(PRSN_MKYO_FIELD_I,OBJFX_HIDE_NONE)
;@HIDE_CHAR(PRSN_MKYO_FIELD_J,OBJFX_HIDE_NONE)
;@HIDE_CHAR(PRSN_MKYO_FIELD_K,OBJFX_HIDE_NONE)
;@HIDE_CHAR(PRSN_MKYO_FIELD_L,OBJFX_HIDE_NONE)
;@HIDE_CHAR(PRSN_MKYO_FIELD_M,OBJFX_HIDE_NONE)
;@HIDE_CHAR(PRSN_MKYO_FIELD_N,OBJFX_HIDE_NONE)
@GOSUB(MSG_EVT_94_TAKANOME))
@SETF(FLG_PHOTO_MAKYOU);撮り頃フラグ
@!



;こけし消しマシン(ストーンヘンジ)
MSG_WINS_STONE_KOKESHI;
◆(For some reason,@KEY()↓
  something that looks like a very large bronze eraser is in the way.)
;jpn:◆(なぜか こけしのようなものが↓
;jpn: みちを ふさいでいる)
@KEYNP()
@!

MSG_WINS_STONE_KOKESHI_RECEIVE;
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_KOKESHIKESHI)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG_HERE)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_TUKATTA)
←
◆(For some reason, the bronze eraser statue disappeared in an instant!)
;jpn:◆なぜか こけしは↓
;jpn: いっしゅんのうちに↓
;jpn: きえさった!
@KEYNP()
@CLOSEALL()
@WI(1)
@SE(SE_se21_b_foe_down)
@HIDE_CHAR(PRSN_WINS_STONE_2_3A,OBJFX_HIDE_DOTS)
;@WI(120)
@SETF(FLG_WINS_STONE_TACO_DISAPPEAR)
』


;自転車
MSG_BTL_BICYCLE;
←
@GET_ORDER_PLAYER(2)
@TRUE_GOTO(_BICYCLE_NG)
@GET_ORDER_PLAYER(1)
@Q_SPECIAL(0,2,2)
@TRUE_GOTO(_BICYCLE_KINOKO)
◆@DSP_ACTOR() rode a bicycle.
;jpn:◆@DSP_ACTOR()は↓
;jpn: じてんしゃに のった。
@RIDE_CYCLE()
@!
_BICYCLE_NG;
@GOSUB(MSG_SYS_BICYCLE_TOO_MANY)
@!

_BICYCLE_KINOKO;
◆If you are not feeling well, you should not ride a bicycle.
;jpn:◆けんこうに じしんのないときには↓
;jpn: じてんしゃに↓
;jpn: のってはいけません。
@KEYNP()
@!


MSG_BTL_MONOSASHI;＠「he」(三浦)
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()↓
◆Now, he can figure out the length of things easily.
;jpn:◆これでまた もののながさが↓
;jpn: よくわかった。
@KEY()
@!

;ものさし
MSG_BTL_BUNDOKI;
←
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
 used the @DSP_GOODS(0)!
;jpn: @DSP_GOODS(0)を つかった!
@KEY()↓
◆Now, he can fairly easily figure out the angle of various things.
;jpn:◆いろいろなものの かくどが↓
;jpn: だいたい わかった。
@KEY()
@!

;ひよこ
MSG_BTL_HIYOKO;
←
@SE(SE_se65_ape)
◆Seeing chicks makes you happy.
;jpn:◆ひよこをみて↓
;jpn: こころが なごんだ。
@SE(SE_se65_ape)
@KEY()
@!

;にわとり
MSG_BTL_NIWATORI;
←
@SE(SE_se68_bodyguard)
@WI(10)
@SE(SE_se68_bodyguard)
◆A chicken ran away as fast as it could.
;jpn:◆にわとりは↓
;jpn: ぜんそくりょくで にげだした。
@KEY()
@!

;テレポートボックス
MSG_BTL_TLPTBOX_OK;
←
 The Teleport Box started to groan.
;jpn: テレポートボックスが↓
;jpn: うなりはじめた!
@SE(SE_se63_teleport_appear)
@KEY()
↓
@BTLFX(BFX_SHAKE_QUAKE_SIDE,BFX_NULL)
 The Teleport Box shattered into pieces with a loud explosion.
;jpn: テレポートボックスは↓
;jpn: おとをたてて くだけちった!
@SE(SE_se63_teleport_appear)
@BTLFX(BFX_TELEPORT_BOX,BFX_NULL)
@KEYNP()
@!

MSG_BTL_TLPTBOX_NG;
←
 The Teleport Box began to groan.
;jpn: テレポートボックスが↓
;jpn: うなりはじめた!
@SE(SE_se63_teleport_appear)
@KEY()
↓
@BTLFX(BFX_SHAKE_QUAKE_SIDE,BFX_NULL)
 The Teleport Box didn’t work quite right...
;jpn: テレポートボックスは↓
;jpn: うまく うごかなかった。
@SE(SE_se05_undo)
@KEYNP()
@!

MSG_BTL_TLPTBOX_CANT;
←
 The Teleport Box can’t be used here.
;jpn: テレポートボックスは↓
;jpn: ここでは つかえない。
; しかし テレポートボックスは↓
; うごかなかった!
@KEYNP()
@!

;音の石
MSG_BTL_SOUND_STONE;
←
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_ACTOR()
;jpn:◆@DSP_ACTOR()は↓
@XCHG()
 touched the @DSP_GOODS(0) to his forehead and gathered his thoughts.
;jpn: @DSP_GOODS(0)を ひたいにあてて↓
;jpn: いしきを しゅうちゅうさせた。
@KEY()
@FUNC(9)				;ここでサウンド確認画面へ
@!

