;
;	ホテルでの新聞スクリプト
;
_SUB_PAPER_CHKF;
@CHKFGOTO(FLG_WIN_GIEGU,_PCHKF_29)
@CHKFGOTO(FLG_POWR_ALL,_PCHKF_28)
@CHKFGOTO(FLG_GUMI_CAVEOPEN,_PCHKF_27)
@CHKFGOTO(FLG_TLPT_MAKY,_PCHKF_26)
@CHKFGOTO(FLG_ITEM_TAKANOME,_PCHKF_25)
@CHKFGOTO(FLG_SPHINX_OK,_PCHKF_24)
@CHKFGOTO(FLG_TLPT_SKRB,_PCHKF_23)
@CHKFGOTO(FLG_PU,_PCHKF_22)
@CHKFGOTO(FLG_FOUR_OK,_PCHKF_21)
@CHKFGOTO(FLG_WIN_MANIMANI,_PCHKF_20)
@CHKFGOTO(FLG_FOUR_DEPT_OK,_PCHKF_19)
@CHKFGOTO(FLG_FOUR_DEPT_BOSS_APPEAR,_PCHKF_18)
@CHKFGOTO(FLG_TLPT_FOUR,_PCHKF_17)
@CHKFGOTO(FLG_WIN_GEPPU,_PCHKF_16)
@CHKFGOTO(FLG_WIN_MATENT,_PCHKF_15)
@CHKFGOTO(FLG_WINS_START,_PCHKF_14)
@CHKFGOTO(FLG_THRK_BIKINIZOMBI_APPEAR,_PCHKF_13)
@CHKFGOTO(FLG_TLPT_THRK,_PCHKF_12)
@CHKFGOTO(FLG_TWSN_ITEM_TONCHIKI,_PCHKF_11)
@CHKFGOTO(FLG_POLA_GRFD,_PCHKF_10)
@CHKFGOTO(FLG_WIN_CARPAINTER,_PCHKF_09)
@CHKFGOTO(FLG_ITEM_FRANKLINBADGE,_PCHKF_08)
@CHKFGOTO(FLG_TWSN_PAUL_UPSET,_PCHKF_07)
@CHKFGOTO(FLG_ONET_GATEOPEN,_PCHKF_06)
@CHKFGOTO(FLG_POWR_GIAN,_PCHKF_05)
@CHKFGOTO(FLG_KEY_TABIGOYA,_PCHKF_04)
@CHKFGOTO(FLG_WIN_FRANK,_PCHKF_03)
@CHKFGOTO(FLG_ONET_GUARDSHARK_DISAPPEAR,_PCHKF_02)
_PCHKF_01;
@SET_LOOPREG(1)
@!
_PCHKF_02;
@SET_LOOPREG(2)
@!
_PCHKF_03;
@SET_LOOPREG(3)
@!
_PCHKF_04;
@SET_LOOPREG(4)
@!
_PCHKF_05;
@SET_LOOPREG(5)
@!
_PCHKF_06;
@SET_LOOPREG(6)
@!
_PCHKF_07;
@SET_LOOPREG(7)
@!
_PCHKF_08;
@SET_LOOPREG(8)
@!
_PCHKF_09;
@SET_LOOPREG(9)
@!
_PCHKF_10;
@SET_LOOPREG(10)
@!
_PCHKF_11;
@SET_LOOPREG(11)
@!
_PCHKF_12;
@SET_LOOPREG(12)
@!
_PCHKF_13;
@SET_LOOPREG(13)
@!
_PCHKF_14;
@SET_LOOPREG(14)
@!
_PCHKF_15;
@SET_LOOPREG(15)
@!
_PCHKF_16;
@SET_LOOPREG(16)
@!
_PCHKF_17;
@SET_LOOPREG(17)
@!
_PCHKF_18;
@SET_LOOPREG(18)
@!
_PCHKF_19;
@SET_LOOPREG(19)
@!
_PCHKF_20;
@SET_LOOPREG(20)
@!
_PCHKF_21;
@SET_LOOPREG(21)
@!
_PCHKF_22;
@SET_LOOPREG(22)
@!
_PCHKF_23;
@SET_LOOPREG(23)
@!
_PCHKF_24;
@SET_LOOPREG(24)
@!
_PCHKF_25;
@SET_LOOPREG(25)
@!
_PCHKF_26;
@SET_LOOPREG(26)
@!
_PCHKF_27;
@SET_LOOPREG(27)
@!
_PCHKF_28;
@SET_LOOPREG(28)
@!
_PCHKF_29;
@SET_LOOPREG(29)
@!

MSG_HOTEL_ONET_PAPERBOY;
@GOSUB(_SUB_PAPER_CHKF)
@SET_REG(1)
@XCHG()
@ONGOSUB(_PAPER_ONET_01,_PAPER_ONET_02,_PAPER_ONET_03,_PAPER_ONET_04,_PAPER_ONET_05,_PAPER_ONET_06,_PAPER_ONET_07,_PAPER_ONET_08,_PAPER_ONET_09,_PAPER_ONET_10,_PAPER_ONET_11,_PAPER_ONET_12,_PAPER_ONET_13,_PAPER_ONET_14,_PAPER_ONET_15,_PAPER_ONET_16,_PAPER_ONET_17,_PAPER_ONET_18,_PAPER_ONET_19,_PAPER_ONET_20,_PAPER_ONET_21,_PAPER_ONET_22,_PAPER_ONET_23,_PAPER_ONET_24,_PAPER_ONET_25,_PAPER_ONET_26,_PAPER_ONET_27,_PAPER_ONET_28,_PAPER_ONET_29)
@!

_PAPER_ONET_PARTS_1;marcus
◆Good morning!↓
  Here’s your free copy of the morning newspaper!
;jpn:◆おはようございます。↓
;jpn: モーニングしんぶんサービスです。
@KEY()↓
@!

_PAPER_ONET_PARTS_2;marcus
◆Here’s today’s headlines in the Onett Times...
;jpn:◆けさの オネットタイムスには↓
;jpn: こんなきじが のっています‥‥
@KEY()↓
@!

_PAPER_ONET_PARTS_3;marcus
◆There’s an advertisement in today’s Onett Times that looks interesting.
;jpn:◆けさの オネットタイムスには↓
;jpn: こんなこうこくが↓
;jpn: のっています‥‥
@KEY()↓
@!

_PAPER_ONET_01;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Mysterious meteorite north of Onett still burning brightly”
;jpn:◆「オネットほくぶにおちた↓
;jpn: なぞのいんせきは いまもなお↓
;jpn: あかあかともえつづけている」
@KEYNP()
@!

_PAPER_ONET_02;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Road to Twoson still closed”
;jpn:◆「ツーソンにつづく どうろ↓
;jpn: いぜん つうこうどめのまま」
@KEYNP()
@!

_PAPER_ONET_03;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Complaints about Sharks gang suddenly melt into thin air”
;jpn:◆「シャークだんにかんする↓
;jpn: オネットしみんの くじょう↓
;jpn: とつぜん ゼロになる」
@KEYNP()
@!

_PAPER_ONET_04;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Mayor of Onett teaches Sharks a lesson, brings peace to Onett”
;jpn:◆「オネットしちょう みずから↓
;jpn: シャークだんを こらしめ↓
;jpn: まちに へいわを とりもどす」
@KEYNP()
@!

_PAPER_ONET_05;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Tamer of the Sharks actually a boy in a red cap!”
;jpn:◆「シャークだんを こらしめたのは↓
;jpn: あかいぼうしをかぶった↓
;jpn: ひとりの しょうねんだった!」
@KEYNP()
@!

_PAPER_ONET_06;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Many citizens of Onett suffer due to crooked real estate agents”
;jpn:◆「オネットしみんの あいだに↓     
;jpn: インチッキーふどうさんによる↓
;jpn: サギのひがい ぞくしゅつ!」
@KEYNP()
@!

_PAPER_ONET_07;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Girl named @DSP_STS(STS_PC_NAME_PAULA) listed as missing in neighboring town of Twoson”
;jpn:◆「となりまち ツーソンで↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)というなまえの↓
;jpn: しょうじょが ゆくえふめい」
@KEYNP()
@!

_PAPER_ONET_08;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
◆Yes...the Onett Times...Uhhh...@KEY()↓
◆Well, @WI(10) I made a mistake and brought you a newspaper called OnettStar on accident.@KEY()↓
  Let me read you the headline anyway...@KEY()↓
◆”So called Mr. Leader Guy running for mayor of Onett”@KEY()↓
◆Well,@WI(10) that’s OnettStar for you.
;jpn:◆けさの オネットタイムスには‥‥@KEY()↓
;jpn:◆あ@WI(10) まちがえて オネスポって↓
;jpn: しんぶん もってきちゃいました。↓
;jpn: いちおう よんでみますね‥‥@KEY()↓
;jpn:◆「いわゆるチョーさん↓
;jpn: オネットしちょうに りっこうほ」@KEY()↓
;jpn:◆ま@WI(10) なんというか↓
;jpn: オネスポですからねぇ。
@KEYNP()
@!

_PAPER_ONET_09;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_3)
◆”Isn’t it about time for a fantastic vacation to the dream resort of Summers?@KEY()↓
◆Someday, we’ll see you there...”
;jpn:◆「ゆめの ビーチリゾート↓
;jpn: サマーズで バカンスはいかが?↓
;jpn: あなたも いつか きっと‥‥」
@KEYNP()
@!

_PAPER_ONET_10;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Twoson kidnap victim @DSP_STS(STS_PC_NAME_PAULA) rescued by local Onett hero  @DSP_NAME(PC_NESS)”
;jpn:◆「となりまちの ゆうかいじけん。↓
;jpn: @DSP_STS(STS_PC_NAME_PAULA)ちゃんを たすけたのは↓
;jpn: わがまちの @DSP_STS(STS_PC_NAME_NES)くん!」
@KEYNP()
@!

_PAPER_ONET_11;marcus
_PAPER_ONET_12;marcus
_PAPER_ONET_13;marcus
_PAPER_ONET_14;marcus
_PAPER_ONET_15;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Situation in the town of Threed is dire”
;jpn:◆「スリークのまちは↓
;jpn: かなり とんでもないじたいに↓
;jpn: みまわれているもよう」
@KEYNP()
@!

_PAPER_ONET_16;marcus
_PAPER_ONET_17;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_3)
◆”Even our clerks get lost in the store!@KEY()↓
◆The world’s largest department store, the Fourside Grand”
;jpn:◆「てんいんも まいごになる!?↓
;jpn: せかいさいだいの デパート↓
;jpn: フォーサイド グランドストア」
@KEYNP()
@!

_PAPER_ONET_18;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Meteorite north of Onett still burning hot”
;jpn:◆「オネットほくぶの いんせきあと↓
;jpn: いぜん こうねつが さめず」
@KEYNP()
@!

_PAPER_ONET_19;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
◆.....@WI(10)Oh,@WI(10)there’s no issue today...sorry.
;jpn:◆‥‥@WI(10)あ@WI(10) きょうは しんぶんの↓
;jpn: きゅうかんびでしたよ。
@KEYNP()
@!

_PAPER_ONET_20;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”@DSP_STS(STS_PARTY_FAVORITE_FOODS) found to be major source of nutrition and energy”
;jpn:◆「@DSP_STS(STS_PARTY_FAVORITE_FOODS)には↓
;jpn: げんきのもとが たっぷりと↓
;jpn: ふくまれていることがわかった」
@KEYNP()
@!

_PAPER_ONET_21;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_3)
◆”Exotic atmosphere!↓
  Historical sites!@KEY()↓
◆Come to the glorious jewel named Scaraba!@KEY()↓
◆Scaraba Tourist Association”
;jpn:◆「いこくじょうちょ たっぷり!↓
;jpn: れきしのおもみが ちがいます!↓
;jpn: スカラビ かんこうきょうかい」
@KEYNP()
@!

_PAPER_ONET_22;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Onett Police chief still not through playing EarthBound!”
;jpn:◆「オネットけいさつしょちょう↓
;jpn: マザー2 まだ おわらず」
@KEYNP()
@!

_PAPER_ONET_23;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Prince @DSP_NAME(PC_POO) of Dalaam traveling incognito to Onett?”
;jpn:◆「ランマの @DSP_STS(STS_PC_NAME_POO)おうじ↓
;jpn: おしのびで オネットに!?」
@KEYNP()
@!

_PAPER_ONET_24;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_3)
◆”Even a seasoned world traveler enjoys staying here.@KEY()↓
◆Hotel Onett in lovely downtown Onett.@KEY()↓
◆...Hey, this is our ad!
;jpn:◆「せかいを たびした あなたにも↓
;jpn: きっと ごまんぞくいただけます↓
;jpn: ホテルオネット ホテルオネット」@KEY()↓
;jpn:◆‥‥@WI(10)あ@WI(30) うちの こうこくでした。
@KEYNP()
@!

_PAPER_ONET_25;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”International news:  Pyramid in Scaraba vandalized”
;jpn:◆「かいがいの ニュースより。↓
;jpn: スカラビの ピラミッド↓
;jpn: なにものかに あらされる!?」
@KEYNP()
@!

_PAPER_ONET_26;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Onett Library facing crisis@KEY()↓
◆Many book borrowers giving library books away or never returning them”
;jpn:◆「オネットとしょかん こまった。↓
;jpn: かりた ほんを またがししたり↓
;jpn: わすれたりするきゃく おおい」
@KEYNP()
@!

_PAPER_ONET_27;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Local survey shows most popular career among kids in Onett is adventurer”
;jpn:◆「オネットの こどもたちの↓
;jpn: あこがれの しょくぎょう。↓
;jpn: ナンバー1は ぼうけんか」
@KEYNP()
@!

_PAPER_ONET_28;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Meteorite landing in north Onett finally beginning to cool off”
;jpn:◆「オネットほくぶの いんせきあと↓
;jpn: ようやく こうねつが さめる」
@KEYNP()
@!

_PAPER_ONET_29;marcus
@GOSUB(_PAPER_ONET_PARTS_1)
@GOSUB(_PAPER_ONET_PARTS_2)
◆”Onett police chief finishes EarthBound, asks, ”Where is the sequel?”
;jpn:◆「オネットけいさつしょちょう↓
;jpn: マザー2 ついに おわらせる!↓
;jpn: そして ひとこと 3はまだか!」
@KEYNP()
@!

MSG_HOTEL_TWSN_PAPERBOY;marcus
@GOSUB(_SUB_PAPER_CHKF)
@SET_REG(1)
@XCHG()
@ONGOSUB(_PAPER_TWSN_01,_PAPER_TWSN_02,_PAPER_TWSN_03,_PAPER_TWSN_04,_PAPER_TWSN_05,_PAPER_TWSN_06,_PAPER_TWSN_07,_PAPER_TWSN_08,_PAPER_TWSN_09,_PAPER_TWSN_10,_PAPER_TWSN_11,_PAPER_TWSN_12,_PAPER_TWSN_13,_PAPER_TWSN_14,_PAPER_TWSN_15,_PAPER_TWSN_16,_PAPER_TWSN_17,_PAPER_TWSN_18,_PAPER_TWSN_19,_PAPER_TWSN_20,_PAPER_TWSN_21,_PAPER_TWSN_22,_PAPER_TWSN_23,_PAPER_TWSN_24,_PAPER_TWSN_25,_PAPER_TWSN_26,_PAPER_TWSN_27,_PAPER_TWSN_28,_PAPER_TWSN_29)
@!

_PAPER_TWSN_PART_1;marcus
◆How about reading the newspaper before you go?
;jpn:◆おでかけのまえに しんぶんでも↓
;jpn: いかがでしょうか。
@KEY()↓
@!

_PAPER_TWSN_PART_2;marcus
◆Here is this morning’s Twoson Tribune headline...
;jpn:◆けさの ツーソントゥデイは↓
;jpn: こんな ぐあいです‥‥
@KEY()↓
@!

_PAPER_TWSN_01;marcus
_PAPER_TWSN_02;marcus
_PAPER_TWSN_03;marcus
_PAPER_TWSN_04;marcus
_PAPER_TWSN_05;marcus
_PAPER_TWSN_06;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Ghosts found to inhabit tunnel to Threed”
;jpn:◆「スリークにつづくトンネルは↓
;jpn: あいかわらず ゴーストどもが!」
@KEYNP()
@!

_PAPER_TWSN_07;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”The brave local hero named @DSP_NAME(PC_NESS) who broke up the Sharks has left Onett.@KEY()↓
◆”Reports that the Mayor stopped the Sharks have been proven to be false”
;jpn:◆「となりまちの オネットの↓
;jpn: あくめいたかき シャークだんを↓
;jpn: たちなおらせた ゆうきある@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)しょうねんは いまは↓
;jpn: オネットには いないもよう」@KEY()↓
;jpn:◆わたしは オネットしちょうの↓
;jpn: おてがらだと ききましたけど↓
;jpn: どうも ちがうようですね。
@KEYNP()
@!

_PAPER_TWSN_08;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Missing girl still not found”
;jpn:◆「ゆくえふめいの しょうじょ↓
;jpn: いまだ てがかり つかめず」
@KEYNP()
@!

_PAPER_TWSN_09;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Regarding Mr. Carpainter↓
  Follower states Happy Happyism is wrong@KEY()↓
◆Follower claims temporary insanity...”
;jpn:◆「カーぺインターさんは かたる。↓
;jpn: ハッピーハッピーきょうは↓
;jpn: いまおもえば まちがいでした。@KEY()↓
;jpn:◆わたしは どうかしていたのです。↓
;jpn: おわびの ことばも ありません」
@KEYNP()
@!
_PAPER_TWSN_10;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”@DSP_NAME(PC_PAULA) found safe!↓
  Parents delighted to have her back”
;jpn:◆「@DSP_STS(STS_PC_NAME_PAULA)ちゃんは↓
;jpn: ぶじだった!↓
;jpn: ごりょうしんも おおよろこび」
@KEYNP()
@!

_PAPER_TWSN_11;marcus
_PAPER_TWSN_12;marcus
_PAPER_TWSN_13;marcus
_PAPER_TWSN_14;marcus
_PAPER_TWSN_15;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Ghosts continue to inhabit tunnel to Threed”
;jpn:◆「スリークにつづく トンネルには↓
;jpn: あいかわらず ばけものが!」
@KEYNP()
@!

_PAPER_TWSN_16;marcus
_PAPER_TWSN_17;marcus
@GOSUB(_PAPER_TWSN_PART_1)
◆This morning’s Twoson Tribune...@KEY()↓
◆...Ooops!  My mistake...I brought the TwosonStar newspaper instead...@KEY()↓
◆Well, let me read this anyway...@KEY()↓
◆”Tessie in Lake Tess is cousin of Nessie”@KEY()↓
◆...That’s about it.
;jpn:◆けさの ツーソントゥデイは‥‥@KEY()↓
;jpn:◆あ まちがえて ツゥースポって↓
;jpn: もってきちゃいました。↓
;jpn: とりあえず よんでみますと‥‥@KEY()↓
;jpn:◆「タスこの タッシーは↓
;jpn: ネッシーの いとこだった!」@KEY()↓
;jpn:◆‥‥なんなんでしょうね。
@KEYNP()
@!

_PAPER_TWSN_18;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Explosion heard recently caused by unknown craft crashing @KEY()↓
◆into the graveyard in Threed”
;jpn:◆「せんじつの ばくはつおんは↓
;jpn: スリークの きょうどうぼちに↓
;jpn: おちた へんなものが げんいん」
@KEYNP()
@!

_PAPER_TWSN_19;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Runaway Five present popular show at the Topolla Theater@KEY()↓
◆in downtown Fourside”
;jpn:◆「だいとかい フォーサイドの↓
;jpn: あの トポロげきじょうで↓
;jpn: われらがトンズラ だいにんき!」
@KEYNP()
@!

_PAPER_TWSN_20;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Everdred, Burglin Park crime boss, missing”
;jpn:◆「ヌスットひろばの ぬし↓
;jpn: トンチキさん しょうそくふめい」
@KEYNP()
@!

_PAPER_TWSN_21;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Runaway Five’s debut release sells out in minutes”
;jpn:◆「トンズラブラザーズの↓
;jpn: ねんがんの デビューレコード↓
;jpn: はつばいとどうじに うりきれ!」
@KEYNP()
@!

_PAPER_TWSN_22;marcus
@GOSUB(_PAPER_TWSN_PART_1)
◆...There was no morning edition today...
;jpn:◆‥‥@WI(10)あ@WI(10) きょうは しんぶんの↓
;jpn: きゅうかんびでしたっけ。
@KEYNP()
@!

_PAPER_TWSN_23;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Prince @DSP_NAME(PC_POO) of Dalaam secretly visiting Twoson?”
;jpn:◆「ランマの @DSP_STS(STS_PC_NAME_POO)おうじ↓
;jpn: おしのびで ツーソンに!?」
@KEYNP()
@!

_PAPER_TWSN_24;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Former Happy Happyism followers claim to have been naive”
;jpn:◆「あのころの わたしたちは↓
;jpn: まだまだ あおかった。@KEY()↓
;jpn:◆もと ハッピーハッピーきょうの↓
;jpn: しんじゃたち むかしをかたる」
@KEYNP()
@!

_PAPER_TWSN_25;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”You! With the controller in your hand! Have you been getting enough sleep lately?”
;jpn:◆「コントローラー てにしたあなた↓
;jpn: すいみんは たりてますか?」
@KEYNP()
@!

_PAPER_TWSN_26;marcus
@GOSUB(_PAPER_TWSN_PART_1)
◆There’s an interesting advertisement in today’s Twoson Tribune.@KEY()↓
◆”Are you shy?  Do you have trouble talking to people you don’t know?@KEY()↓
◆If so, the book ”Overcoming Shyness” is your self−help guide to becoming more outgoing.@KEY()↓
◆This title is now available at your local bookstore or library.”
;jpn:◆けさの ツーソントゥデイに↓
;jpn: こんな こうこくが@KEY()↓
;jpn:◆「むくちが いっぱつで なおる!↓
;jpn: そのなも むくちをなおすほん。↓
;jpn: としょかんにて かしだしちゅう」
@KEYNP()
@!

_PAPER_TWSN_27;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”In Twoson, Nintendo’s eight−bit system, the NES, makes a comeback!”

;jpn:◆「ツーソンの ひとびとのあいだで↓
;jpn: むかしのマザーが だいにんき!↓
;jpn: ニンテンドーも おおあわて!」
@KEYNP()
@!

_PAPER_TWSN_28;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Onett Times a better newspaper than we imagined here at the Twoson Tribune”
;jpn:◆「となりまちの しんぶん↓
;jpn: オネットタイムスも↓
;jpn: なかなか あなどれない」
@KEYNP()
@!

_PAPER_TWSN_29;marcus
@GOSUB(_PAPER_TWSN_PART_1)
@GOSUB(_PAPER_TWSN_PART_2)
◆”Monsters disappear!↓
 Animals calm down!↓
 The town is at peace!”
;jpn:◆「モンスターたち きえる!↓
;jpn: どうぶつたち おとなしくなる!↓
;jpn: ほんとの へいわ もどる!」
@KEYNP()
@!

MSG_HOTEL_THRK_PAPERBOY;
@GOSUB(_SUB_PAPER_CHKF)
@SET_REG(1)
@XCHG()
@ONGOSUB(_PAPER_THRK_01,_PAPER_THRK_02,_PAPER_THRK_03,_PAPER_THRK_04,_PAPER_THRK_05,_PAPER_THRK_06,_PAPER_THRK_07,_PAPER_THRK_08,_PAPER_THRK_09,_PAPER_THRK_10,_PAPER_THRK_11,_PAPER_THRK_12,_PAPER_THRK_13,_PAPER_THRK_14,_PAPER_THRK_15,_PAPER_THRK_16,_PAPER_THRK_17,_PAPER_THRK_18,_PAPER_THRK_19,_PAPER_THRK_20,_PAPER_THRK_21,_PAPER_THRK_22,_PAPER_THRK_23,_PAPER_THRK_24,_PAPER_THRK_25,_PAPER_THRK_26,_PAPER_THRK_27,_PAPER_THRK_28,_PAPER_THRK_29)
@!

_PAPER_THRK_PART_1;marcus
◆S...sir....?↓
;jpn:◆お おきゃくさま‥‥↓
@!
_PAPER_THRK_PART_2;marcus
◆The guest’s newspapers that were delivered to the hotel today are different than normal.@KEY()↓
◆The paper is called the Zombie Herald...@KEY()↓
◆I’m scared, but let me tell you what is in it...
;jpn:◆けさ ゾンビワールドという↓
;jpn: しんぶんが とどけられてまして↓
;jpn: こ こわいけど よんでみます‥‥
@KEY()↓
@!
_PAPER_THRK_PART_3;
◆Good Morning!!
;jpn:◆おっはようございます!
@KEY()↓
@!
_PAPER_THRK_PART_4;marcus
◆Here’s your copy of the Threed Journal.
;jpn:◆けさの スリークジャーナルを↓
;jpn: およみいたしましょう‥‥
@KEY()↓
@!

_PAPER_THRK_01;marcus
_PAPER_THRK_02;marcus
_PAPER_THRK_03;marcus
_PAPER_THRK_04;marcus
_PAPER_THRK_05;marcus
_PAPER_THRK_06;marcus
_PAPER_THRK_07;marcus
_PAPER_THRK_08;marcus
_PAPER_THRK_09;marcus
_PAPER_THRK_10;marcus
_PAPER_THRK_11;marcus
_PAPER_THRK_12;marcus
@GOSUB(_PAPER_THRK_PART_1)
  Are you going out?
;jpn: おでかけなさるんですか。
@KEY()↓
@GOSUB(_PAPER_THRK_PART_2)
◆”Destroy the humans!@KEY()↓
◆Hold the town for our glory, and for the glory of our master!”
;jpn:◆「にんげんどもに おそいかかれ!↓
;jpn: このまちを われらのものに↓
;jpn: われらが おやかたのために」
@KEYNP()
@!

_PAPER_THRK_13;marcus
@GOSUB(_PAPER_THRK_PART_1)
  The weather for today is dark and gloomy
;jpn: そとは いやなおてんきですよ。
@KEY()↓
@GOSUB(_PAPER_THRK_PART_2)
◆”Today’s weather: thick, gray clouds all day”↓
;jpn:◆「てんきよほう↓
;jpn: きょうも どんよりとした↓
;jpn: じつによい くもりぞらでしょう」
@KEYNP()
@!

_PAPER_THRK_14;marcus
@GOSUB(_PAPER_THRK_PART_1)
  Oh, you got up early today.
;jpn: おはやい おめざめですね。
@KEY()↓
@GOSUB(_PAPER_THRK_PART_2)
◆”Two human kids escape by somehow opening their cage”
;jpn:◆「にんげんのこども 2ひき↓
;jpn: オリのカギをあけて にげだす!」
@KEYNP()
@!

_PAPER_THRK_15;marcus
@GOSUB(_PAPER_THRK_PART_1)
  You’re working hard, even though you’re young.
;jpn: おわかいのに たいへんですね。
@KEY()↓
@GOSUB(_PAPER_THRK_PART_2)
◆”Boogey Tent falls!  Young human to blame!”
;jpn:◆「われわれのどうし ばけテントが↓
;jpn: なにものかに たおされる」
@KEYNP()
@!

_PAPER_THRK_16;marcus
@GOSUB(_PAPER_THRK_PART_3)
◆The pride of the Threed publishing community,@KEY()↓
◆the Threed Journal, is back with a vengeance!@KEY()↓
◆”Zombies vanquished!↓
  Tunnel now open!”
;jpn:◆このまちがほこる しんぶん↓
;jpn: スリークジャーナルが めでたく↓
;jpn: ふっかつ したんですよ!@KEY()↓
;jpn:◆「ツーソンから ゾンビきえる!↓
;jpn: トンネルも つうこうかのうに!」
@KEYNP()
@!

_PAPER_THRK_17;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Tessie exists, eyewitnesses report!@KEY()↓
◆But Tessie Watching Society member forgets to put film in his camera!”
;jpn:◆「タスこの タッシーは↓
;jpn: たーしかに いた!?@KEY()↓
;jpn:◆しかし タッシーそうさくたい↓
;jpn: カメラにフィルム いれわすれる」
@KEYNP()
@!

_PAPER_THRK_18;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Department store panic!@KEY()↓
◆Blackout hits popular department store in broad daylight”
;jpn:◆「だいとかい フォーサイドの↓
;jpn: にんきデパート なぞのていでん!↓
;jpn: まひるの だいパニック!」
@KEYNP()
@!

_PAPER_THRK_19;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Someone working to fix machine left in hole at the Threed graveyard”
;jpn:◆「きょうどうぼちの ちかしつに↓
;jpn: ほうちされた マシンを↓
;jpn: せっせと なおすひとたちがいた」
@KEYNP()
@!

_PAPER_THRK_20;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”@DSP_NAME(PC_NESS) and company save Threed@KEY()↓
◆confirms chief of Zombie Relief Corps”
;jpn:◆「@DSP_STS(STS_PC_NAME_NES)くんたちが↓
;jpn: このまちを すくってくれた。@KEY()↓
;jpn:◆もと ゾンビたいさくほんぶちょう↓
;jpn: しみじみと かたる」
@KEYNP()
@!

_PAPER_THRK_21;marcus松(シャレになっていない)
@GOSUB(_PAPER_THRK_PART_3)
◆This morning’s Threed Journal headlines read like this...@KEY()↓
◆Uhh, I made a mistake and brought the ThreedStar by accident...@KEY()↓
◆Well, let me read it to you anyway...@KEY()↓
◆”Zombie gives birth to hawk child”@KEY()↓
◆Heh, heh, heh...yeah, right...
;jpn:◆けさの スリークジャーナルを‥‥@KEY()↓
;jpn:◆あ まちがえて スリスポって↓
;jpn: しんぶん もってきちゃいました。↓
;jpn: ちょっと よんでみましょうか‥‥@KEY()↓
;jpn:◆「ゾンビが タカをうんだ!」@KEY()↓
;jpn:◆‥‥うむわけ ないですよね。
@KEYNP()
@!

_PAPER_THRK_22;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Supernatural powers do not exist@KEY()↓
◆Human beings cannot use teleportation states university professor”
;jpn:◆「だいがくの せんせい かたる。↓
;jpn: ちょうのうりょくは ありえない。↓
;jpn: テレポートなど できるわけない」
@KEYNP()
@!

_PAPER_THRK_23;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Prince @DSP_NAME(PC_POO) of Dalaam secretly visiting Threed?”
;jpn:◆「ランマの @DSP_STS(STS_PC_NAME_POO)おうじ↓
;jpn: おしのびで スリークに?!」
@KEYNP()
@!

_PAPER_THRK_24;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Zombie prison warden states inmates believe Our Nest is Best”
;jpn:◆「スリークみなみの オリのなかの↓
;jpn: ゾンビたちは かたる。↓
;jpn: なれれば けっこう いいくらし」
@KEYNP()
@!

_PAPER_THRK_25;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”Pyramid mysteriously opens in distant Scaraba.↓
◆Is this a good portent?”
;jpn:◆「はるか スカラビのくにの↓
;jpn: ピラミッドのとびら ひらく!↓
;jpn: こううんの きざしか?」
@KEYNP()
@!

_PAPER_THRK_26;marcus
@GOSUB(_PAPER_THRK_PART_3)
◆Here’s an interesting advertisement in today’s Threed Journal...@KEY()↓
◆”Morning newspapers brought to your room by a handsome, friendly bellboy.@KEY()↓
◆Threed Sunset Hotel”@KEY()↓
◆...Uhhh...hey!...this is our ad!
;jpn:◆けさの スリークジャーナルに↓
;jpn: こんな こうこくが のってます。@KEY()↓
;jpn:◆「げんきな しんぶんがかりが↓
;jpn: さわやかな あさを えんしゅつ。↓
;jpn: スリークサンセットホテル」@KEY()↓
; かいてきホテル スリークイン」@KEY()↓
;jpn:◆‥‥あ うちの こうこくでした。
@KEYNP()
@!

_PAPER_THRK_27;marcus
@GOSUB(_PAPER_THRK_PART_3)
◆Here’s today’s Threed Journal!...@KEY()↓
◆Uh...whoops...there is no edition today...
;jpn:◆けさの スリークジャーナルを@KEY()↓
;jpn:◆‥‥@WI(10)あ@WI(10) きょうは しんぶんの↓
;jpn: きゅうかんびでしたよ。
@KEYNP()
@!

_PAPER_THRK_28;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”The Twoson Tribune, the neighboring town’s newspaper, also woth reading”
;jpn:◆「となりのまちの しんぶん↓
;jpn: ツーソントゥデイも↓
;jpn: いがいと よみごたえ あり」
@KEYNP()
@!

_PAPER_THRK_29;marcus
@GOSUB(_PAPER_THRK_PART_3)
@GOSUB(_PAPER_THRK_PART_4)
◆”@DSP_NAME(PC_NESS) and friends made honorary citizens!”
;jpn:◆「@DSP_STS(STS_PC_NAME_NES)しょうねんと↓
;jpn: その なかまたちが↓
;jpn: スリークの めいよしみんに!」
@KEYNP()
@!

MSG_HOTEL_FOUR_PAPERBOY;
@GOSUB(_SUB_PAPER_CHKF)
@SET_REG(1)
@XCHG()
@ONGOSUB(_PAPER_FOUR_01,_PAPER_FOUR_02,_PAPER_FOUR_03,_PAPER_FOUR_04,_PAPER_FOUR_05,_PAPER_FOUR_06,_PAPER_FOUR_07,_PAPER_FOUR_08,_PAPER_FOUR_09,_PAPER_FOUR_10,_PAPER_FOUR_11,_PAPER_FOUR_12,_PAPER_FOUR_13,_PAPER_FOUR_14,_PAPER_FOUR_15,_PAPER_FOUR_16,_PAPER_FOUR_17,_PAPER_FOUR_18,_PAPER_FOUR_19,_PAPER_FOUR_20,_PAPER_FOUR_21,_PAPER_FOUR_22,_PAPER_FOUR_23,_PAPER_FOUR_24,_PAPER_FOUR_25,_PAPER_FOUR_26,_PAPER_FOUR_27,_PAPER_FOUR_28,_PAPER_FOUR_29)
@!

_PAPER_FOUR_PART_1;marcus
◆Good morning!@KEY()↓
◆This is a unique service, exclusive to our hotel only!@KEY()↓
◆I’m here to read you today’s headline.
@KEY()↓
;jpn:◆おはようございます。@KEY()↓
;jpn:◆とうホテルだけの↓
;jpn: しんぶん よみあげサービスです。@WI(10)↓
@!

_PAPER_FOUR_PART_2;marcus
◆On the front page of the Fourside Post...
;jpn: フォーサイドポスト だい1めん
@KEY()↓
@!

_PAPER_FOUR_01;Marcus
_PAPER_FOUR_02;
_PAPER_FOUR_03;
_PAPER_FOUR_04;
_PAPER_FOUR_05;
_PAPER_FOUR_06;
_PAPER_FOUR_07;
_PAPER_FOUR_08;
_PAPER_FOUR_09;
_PAPER_FOUR_10;
_PAPER_FOUR_11;
_PAPER_FOUR_12;
_PAPER_FOUR_13;
_PAPER_FOUR_14;
_PAPER_FOUR_15;
_PAPER_FOUR_16;
_PAPER_FOUR_17;
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Over 70% of Fourside citizens support Monotoli”
;jpn:◆「フォーサイドしみんによる↓
;jpn: モノトリーしの しじりつ↓
;jpn: 70パーセントを こえる!」
@KEYNP()
@!

_PAPER_FOUR_18;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Over 80% of Fourside citizens support Monotoli”
;jpn:◆「フォーサイドしみんによる↓
;jpn: モノトリーしの しじりつ↓
;jpn: 80パーセントを こえる!」
@KEYNP()
@!

_PAPER_FOUR_19;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Over 90% of Fourside citizens support Monotoli”@KEY()↓
◆Then on page 17, @KEY()↓
◆”Mysterious department store blackout caused by mouse”
;jpn:◆「フォーサイドしみんによる↓
;jpn: モノトリーしの しじりつ↓
;jpn: 90パーセントを こえる!」@KEY()↓
;jpn:◆フォーサイドポスト だい17めん@KEY()↓
;jpn:◆「デパートの なぞのていでん↓
;jpn: げんいんは ネズミのイタズラ」
@KEYNP()
@!

_PAPER_FOUR_20;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Over 50% of Fourside citizens now support Anti−Monotoli campaign”@KEY()↓
◆And on page 23 of the Fourside Post.@KEY()↓
◆”Lonely demise in the city.  Long−haired man with beard,@KEY()↓
◆sunglasses and aloha shirt found in street”
;jpn:◆「フォーサイドしみんによる↓
;jpn: モノトリーしの しじりつ↓
;jpn: 50パーセントを したまわる!」@KEY()↓
;jpn:◆フォーサイドポスト だい23めん@KEY()↓
;jpn:◆「とかいの こどくな し。↓
;jpn: サングラス ひげ ちょうはつ↓
;jpn: アロハシャツの だんせい」
@KEYNP()
@!

_PAPER_FOUR_21;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Famed Mr. Monotoli leaves Fourside.  States he is going on a trip”
;jpn:◆「あの モノトリーし↓
;jpn: たびにでると いいのこしたまま↓
;jpn: フォーサイドから すがたをけす」
@KEYNP()
@!

_PAPER_FOUR_22;marcus
@GOSUB(_PAPER_FOUR_PART_1)
◆The Fourside Post says...@KEY()↓
◆Yoicks! I made a mistake and brought a newspaper called FoursideStar.@KEY()↓
◆Let me read this anyway...@KEY()↓
◆”Lucky of the Runaway Five found to have been in state House of Representatives”@KEY()↓
◆...That’s got to be a lie...
;jpn: フォーサイドポストの‥‥@KEY()↓
;jpn:◆あ まちがえて フォースポって↓
;jpn: しんぶん もってきちゃいました。↓
;jpn: どうせだから よんでみます‥‥@KEY()↓
;jpn:◆「トンズラのラッキーは むかし↓
;jpn: がっきゅういいんだった!」↓@KEY()
;jpn:◆‥‥@WI(10)うそに きまってますよね。
@KEYNP()
@!

_PAPER_FOUR_23;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Prince @DSP_NAME(PC_POO) of Dalaam visiting Fourside in secret?”
;jpn:◆「ランマの @DSP_STS(STS_PC_NAME_POO)おうじ↓
;jpn: おしのびで フォーサイドに?!」
@KEYNP()
@!

_PAPER_FOUR_24;marcus
@GOSUB(_PAPER_FOUR_PART_1)
◆On page 25 of the Fourside Post...@KEY()↓
◆”Venus becomes toast of Fourside Autograph hunters creating problems for famed singer”
;jpn: フォーサイドポスト だい25めん@KEY()↓
;jpn:◆「いま フォーサイドで↓
;jpn: ビーナスにんき ふっとうちゅう!↓
;jpn: まいにちが サインぜめ」
@KEYNP()
@!

_PAPER_FOUR_25;marcus
@GOSUB(_PAPER_FOUR_PART_1)
◆On page 3 of the Fourside Post...@KEY()↓
◆”Criminal activity in Scaraba?@KEY()↓
◆Sacred treasure of pyramid, the @DSP_GOODS(GDS_TOOL_EAGLE_EYE) stolen”
;jpn: フォーサイドポスト だい3めん@KEY()↓
;jpn:◆「スカラビに せっとうだん?!↓
;jpn: ピラミッドの ひほう @DSP_GOODS(GDS_TOOL_EAGLE_EYE)が↓
;jpn: なにものかに もちさられる」
@KEYNP()
@!

_PAPER_FOUR_26;marcus
@GOSUB(_PAPER_FOUR_PART_1)
◆Here’s an advertisement in today’s Fourside Post.@KEY()↓
◆”Higher than everywhere else!↓
 (That’s height, not price)↓
 Monotoli Grand Hotel@KEY()↓
◆Hey!  That’s our hotel!
;jpn: フォーサイドポスト こうこくらん@KEY()↓
;jpn:◆「どこよりも たかい!↓
;jpn: (ねだんじゃなくて せのたかさ)↓
;jpn: モノトリーグランドホテル」@KEY()↓
; ホテル・ザ・フォーサイド」@KEY()↓
;jpn:◆‥‥このホテルのことですよ。
@KEYNP()
@!

_PAPER_FOUR_27;marcus
@GOSUB(_PAPER_FOUR_PART_1)
◆on page 13 of the Fourside Post...@KEY()↓
◆”Newspaper reading by bellboys is not exclusive to Fourside only@KEY()↓
◆Do not be taken in by bellboys just looking for a tip”@KEY()↓
◆...I’m so ashamed...
;jpn: フォーサイドポスト だい13めん@KEY()↓
;jpn:◆「しんぶん よみあげサービスは↓
;jpn: いまどき どこでも あたりまえ。↓
;jpn: だまされないよう ちゅうい」@KEY()↓
;jpn:◆‥‥おはずかしい。
@KEYNP()
@!

_PAPER_FOUR_28;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”The best newspaper of all the others@KEY()↓
◆Everyone reads the Fourside Post each morning”@KEY()↓
◆Is this the page one headline?
;jpn:◆「しんぶんのなかの しんぶん。↓
;jpn: フォーサイドポストを↓
;jpn: けさも みなさん よんでいる」@KEY()↓
;jpn:◆これが トップきじですか‥‥。
@KEYNP()
@!

_PAPER_FOUR_29;marcus
@GOSUB(_PAPER_FOUR_PART_1)
@GOSUB(_PAPER_FOUR_PART_2)
◆”Megalopolis Fourside to have another busy day”
;jpn:◆「だいとかい フォーサイドは↓
;jpn: きょうも いつもとかわらず↓
;jpn: あわただしく なるもよう」
@KEYNP()
@!

MSG_HOTEL_SUMS_PAPERBOY;
@GOSUB(_SUB_PAPER_CHKF)
@SET_REG(1)
@XCHG()
@ONGOSUB(_PAPER_SUMS_01,_PAPER_SUMS_02,_PAPER_SUMS_03,_PAPER_SUMS_04,_PAPER_SUMS_05,_PAPER_SUMS_06,_PAPER_SUMS_07,_PAPER_SUMS_08,_PAPER_SUMS_09,_PAPER_SUMS_10,_PAPER_SUMS_11,_PAPER_SUMS_12,_PAPER_SUMS_13,_PAPER_SUMS_14,_PAPER_SUMS_15,_PAPER_SUMS_16,_PAPER_SUMS_17,_PAPER_SUMS_18,_PAPER_SUMS_19,_PAPER_SUMS_20,_PAPER_SUMS_21,_PAPER_SUMS_22,_PAPER_SUMS_23,_PAPER_SUMS_24,_PAPER_SUMS_25,_PAPER_SUMS_26,_PAPER_SUMS_27,_PAPER_SUMS_28,_PAPER_SUMS_29)
@!
_PAPER_SUMS_PART_1;marcus
◆Ah, sir...↓
 Are you already on your way to the beach?
;jpn:◆これは これは おきゃくさま。↓
;jpn: もう ビーチへ おでかけですか。
@KEY()↓
@!
_PAPER_SUMS_PART_2;marcus
◆Here is this morning’s headlines from the Daily Summers...
;jpn:◆けさの デイリーサマーズの↓
;jpn: トップニュースはですね‥‥
@KEY()↓
@!

_PAPER_SUMS_01;marcus
_PAPER_SUMS_02;
_PAPER_SUMS_03;
_PAPER_SUMS_04;
_PAPER_SUMS_05;
_PAPER_SUMS_06;
_PAPER_SUMS_07;
_PAPER_SUMS_08;
_PAPER_SUMS_09;
_PAPER_SUMS_10;
_PAPER_SUMS_11;
_PAPER_SUMS_12;
_PAPER_SUMS_13;
_PAPER_SUMS_14;
_PAPER_SUMS_15;
_PAPER_SUMS_16;
_PAPER_SUMS_17;
_PAPER_SUMS_18;
_PAPER_SUMS_19;
_PAPER_SUMS_20;
_PAPER_SUMS_21;
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”People reported missing one after another in our sister city Winters”
;jpn:◆「しまいとし ウィンターズで↓
;jpn: ゆくえふめいしゃ ぞくしゅつ」
@KEYNP()
@!

_PAPER_SUMS_22;marcus
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”Yesterday the same as the day before yesterday@KEY()↓
◆Today to be the same as yesterday”
;jpn:◆「きのうは おとといと おなじ。↓
;jpn: きょうはきのうと おなじもよう」
@KEYNP()
@!

_PAPER_SUMS_23;marcus
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”Prince @DSP_NAME(PC_POO) of Dalaam visiting Summers secretly?”
;jpn:◆「ランマの @DSP_STS(STS_PC_NAME_POO)おうじ↓
;jpn: おしのびで サマーズに?!」
@KEYNP()
@!

_PAPER_SUMS_24;marcus
@GOSUB(_PAPER_SUMS_PART_1)
◆Today’s Daily Summers says...@KEY()↓
◆Ooo la la,@WI(10) I brought the wrong paper by mistake.  It is the Summer Inquirerer@KEY()↓
◆Listen to this headline...@KEY()↓
◆”Huge rat found living in sewer system”@KEY()↓
◆...I really do not think so...
;jpn:◆けさの デイリーサマーズ‥‥@KEY()↓
;jpn:◆あ@WI(10) まちがえて サマスポって↓
;jpn: しんぶん もってきちゃいました。↓
;jpn: この みだし すごいですよ‥‥@KEY()↓
;jpn:◆「フォーサイドの げすいどうに↓
;jpn: きょだいねずみがいた?!」↓
;jpn:◆‥‥いるわけないですよね。
@KEYNP()
@!

_PAPER_SUMS_25;marcus
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”Intruders in Scaraba Pyramid!@WI(10) Summers remains a peaceful paradise”
;jpn:◆「スカラビの ピラミッドに↓
;jpn: なにものかが しんにゅう?!↓
;jpn: ‥‥@WI(10)サマーズは へいわそのもの」
@KEYNP()
@!

_PAPER_SUMS_26;marcus
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”Breeze blew through the palm trees last night”@KEY()↓
◆...@WI(10) This is big news here.
;jpn:◆「さくばん かぜがふいて↓
;jpn: やしのきが けっこうゆれる!」@KEY()↓
;jpn:◆‥‥@WI(10)ここでは ビッグニュースです。
@KEYNP()
@!

_PAPER_SUMS_27;marcus
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”Kraken Fin makes a beautiful soup!@KEY()↓
◆New gourmet dish makes big waves at the beach”
;jpn:◆「ビーチに クラーケンのヒレが↓
;jpn: うちあげられ みんなでスープに。↓
;jpn: レストランでも しんメニューに」
@KEYNP()
@!

_PAPER_SUMS_28;marcus
@GOSUB(_PAPER_SUMS_PART_1)
◆There’s a great advertisement in this morning’s Daily Summers@KEY()↓
◆”Stop doing anything complicated.@KEY()↓
◆Forget about solving mysteries and completing stages!@KEY()↓
◆Welcome to the easy life in Summers!”
;jpn:◆けさの デイリーサマーズに↓
;jpn: すてきな こうこくがのってます。@KEY()↓
;jpn:◆「ややこしいこと やめましょう。↓
;jpn: ナゾとか クリアとか かんがえず↓
;jpn: サマーズで のんきライフ!」
@KEYNP()
@!

_PAPER_SUMS_29;Marcus
@GOSUB(_PAPER_SUMS_PART_1)
@GOSUB(_PAPER_SUMS_PART_2)
◆”Yesterday was the same as the day before yesterday@KEY()↓
◆Today will be the same as yesterday”
;jpn:◆「きのうは おとといと おなじ。↓
;jpn: きょうはきのうと おなじもよう」
@KEYNP()
@!

MSG_HOTEL_SKRB_PAPERBOY;
@GOSUB(_SUB_PAPER_CHKF)
@SET_REG(1)
@XCHG()
@ONGOSUB(_PAPER_SKRB_01,_PAPER_SKRB_02,_PAPER_SKRB_03,_PAPER_SKRB_04,_PAPER_SKRB_05,_PAPER_SKRB_06,_PAPER_SKRB_07,_PAPER_SKRB_08,_PAPER_SKRB_09,_PAPER_SKRB_10,_PAPER_SKRB_11,_PAPER_SKRB_12,_PAPER_SKRB_13,_PAPER_SKRB_14,_PAPER_SKRB_15,_PAPER_SKRB_16,_PAPER_SKRB_17,_PAPER_SKRB_18,_PAPER_SKRB_19,_PAPER_SKRB_20,_PAPER_SKRB_21,_PAPER_SKRB_22,_PAPER_SKRB_23,_PAPER_SKRB_24,_PAPER_SKRB_25,_PAPER_SKRB_26,_PAPER_SKRB_27,_PAPER_SKRB_28,_PAPER_SKRB_29)
@!

_PAPER_SKRB_PART_1;marcus
◆Good morning, good sir!@KEY()↓
◆Please allow me to read to you from the local newspaper,@KEY()↓
◆the Scaraba Papyrus...
;jpn:◆グッド モーニング サー!@KEY()↓
;jpn:◆このくにの ゆうめいなしんぶん↓
;jpn: スカラビパピルス およみします。
@KEY()↓
@!

_PAPER_SKRB_PART_2;marcus
◆...@WI(10)Well...there is some new here about...
;jpn: ‥‥@WI(10)というウワサ ながれる」
@KEYNP()
@!

_PAPER_SKRB_01;marcus
_PAPER_SKRB_02;
_PAPER_SKRB_03;
_PAPER_SKRB_04;
_PAPER_SKRB_05;
_PAPER_SKRB_06;
_PAPER_SKRB_07;
_PAPER_SKRB_08;
_PAPER_SKRB_09;
_PAPER_SKRB_10;
_PAPER_SKRB_11;
_PAPER_SKRB_12;
_PAPER_SKRB_13;
_PAPER_SKRB_14;
_PAPER_SKRB_15;
_PAPER_SKRB_16;
_PAPER_SKRB_17;
_PAPER_SKRB_18;
_PAPER_SKRB_19;
_PAPER_SKRB_20;
_PAPER_SKRB_21;
_PAPER_SKRB_22;
_PAPER_SKRB_23;
@GOSUB(_PAPER_SKRB_PART_1)
◆”Kraken, the evil sea monster, now gone forever!”@KEY()↓
;jpn:◆「いまわしき うみの かいぶつ↓
;jpn: クラーケンが すがたをけす!
@GOSUB(_PAPER_SKRB_PART_2)
@!

_PAPER_SKRB_24;marcus
@GOSUB(_PAPER_SKRB_PART_1)
◆”Activity at pyramid the first in 300 years”@KEY()↓
;jpn:◆「さばくの ピラミッド↓
;jpn: 300ねんぶりにトビラがひらいた
@GOSUB(_PAPER_SKRB_PART_2)
@!

_PAPER_SKRB_25;marcus
@GOSUB(_PAPER_SKRB_PART_1)
◆”@DSP_GOODS(GDS_TOOL_EAGLE_EYE) stolen from the pyramid in the desert!”@KEY()↓
;jpn:◆「さばくの ピラミッドから↓
;jpn: @DSP_GOODS(GDS_TOOL_EAGLE_EYE)が ぬすみだされる
@GOSUB(_PAPER_SKRB_PART_2)
@!

_PAPER_SKRB_26;marcus
@GOSUB(_PAPER_SKRB_PART_1)
◆”Mysterious moving tower sighted in desert!”@KEY()↓
;jpn:◆「さばくにたつ ふしぎなとうが↓
;jpn: ズルズルと うごきまわっていた!
@GOSUB(_PAPER_SKRB_PART_2)
@!

_PAPER_SKRB_27;marcus
@GOSUB(_PAPER_SKRB_PART_1)
◆”Miraculous foreign children overwhelm Kraken!”@KEY()↓
;jpn:◆「あのクラーケンを たおしたのは↓
;jpn: がいこくの こどもたちだった。
@GOSUB(_PAPER_SKRB_PART_2)
@!

_PAPER_SKRB_28;marcus
@GOSUB(_PAPER_SKRB_PART_1)
◆”Children who dash then disappear sighted, but only for an instant”@KEY()↓
;jpn:◆「とつぜん はしりだし パッと↓
;jpn: きえてしまう こどもたちがいる。
@GOSUB(_PAPER_SKRB_PART_2)
@!

_PAPER_SKRB_29;marcus
@GOSUB(_PAPER_SKRB_PART_1)
◆”Terrible sound recently heard@KEY()↓
◆Possibly the sound of evil being destroyed beyond our time and space”@KEY()↓
;jpn:◆「せんじつ じくうをこえて↓
;jpn: あくが ほろびる おとがした。
@GOSUB(_PAPER_SKRB_PART_2)
@!

MSG_HOTEL_MOON_PAPERBOY;marcus
◆Good morn...@WI(10)Uhhh...not morning.@WI(10)@KEY()↓
◆Here@WI(5) in Moonside, it’s always the middle of the night@KEY()↓
◆This is a headline from tonight’s Moonside Press...@KEY()↓
◆”Mani Mani is @WI(10) always Mani Mani @WI(10) at Mani Mani with all @WI(10) Mani Mani @WI(10) Mani”
;jpn:◆おはようございま‥‥@WI(10)せん。@WI(10)↓
;jpn: ここ@WI(5) ムーンサイドのまちは↓
;jpn: いつだって まよなかなんですよ。@KEY()↓
;jpn:◆こんやの ムーンサイドプレスに↓
;jpn: ほうら@WI(10) こんなニュースが@KEY()↓
;jpn:◆「マニマニは@WI(10) マニマニに@WI(10) いつも@WI(10)↓
;jpn: すべての@WI(10) マニマニの@WI(10) マニマニが@WI(10)↓
;jpn: マニ@WI(10) すべて@WI(10) ママ@WI(10) マニマニ」
@KEYNP()
@!

