;==============================================================================
;
;キャッシュディスペンサー
;

MSG_CD;
;
@SET_LOOPREG(0)
@SET_REG(1)
;
◆Welcome to the Automatic Teller Machine.@KEY()↓
◆Please select a transaction:↓

;@SAVE_WIN()
;@DSP_PL()
;@OPEN(37)
<Withdrawal>
<Deposit>
@DSP_ITEM(2)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@ONGOTO(_CD_HIKIDASHI,_CD_OAZUKE)
@SELGOTO(_CD_HIKIDASHI,_CD_OAZUKE)

;jpn:◆イラッシャイマセ↓
;jpn:<ヒキダス>
;jpn:<アズケル>
;@DSP_ITEM(2)
_CD_NO;
◆Thank you very much.

;jpn:◆アリガトウゴザイマシタ
_CD_END;
@KEYNP()
@!

_CD_OAZUKE;
;
@Q_BANK_MONEY(9999999)
@FALSE_GOTO(_CD_OA_FULL)
@GOSUB(_CD_INPUT_B)
@FALSE_GOTO(_CD_NO)
@SET_REG(0)
@Q_MONEY(0)
@TRUE_GOTO(_CD_OA_NOMONEY)
@MONEYOUT(0)
@DEPOSIT_MONEY_BANK(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(10)
◆Your account will be credited↓
  $@DSP_NUM(0).@KEY()↓
◆Thank you very much.

;◆$@DSP_NUM(0)↓
;jpn: オアズカリシマシタ@KEY()↓
;jpn:◆アリガトウゴザイマシタ
@GOTO(_CD_END)

_CD_OA_NOMONEY;				;所持金 < 入力した金額
◆Invalid instruction input.  Please try again.@KEY()↓

;jpn:◆ニュウリョク ミス!↓
;jpn: ニュウリョク↓
;jpn: シナオシテクダサイ@KEY()↓
@GOTO(_CD_OAZUKE)

_CD_OA_OVER;				;銀行預金限界越える(未使用)
◆You do not have that
  much money for a deposit.@KEY()↓

;jpn:◆ソンナニ アズカレマセン@KEY()↓
@GOTO(_CD_OAZUKE)

_CD_OA_FULL;				;銀行預金MAX
◆This machine cannot accept a deposit greater than↓
  $9,999,999.@KEY()↓
 
;◆$9999999↓
;jpn: ヲコエテハ↓
;jpn: アズカレナイキマリデス@KEY()↓
@GOTO(_CD_NO)

_CD_HIKIDASHI;
@Q_BANK_MONEY(1)
@TRUE_GOTO(_CD_HIKI_EMPTY)
@Q_MONEY(99999)
@FALSE_GOTO(_CD_HIKI_MAX)
@GOSUB(_CD_INPUT)
@FALSE_GOTO(_CD_NO)
@SET_REG(0)
@Q_BANK_MONEY(0)
@TRUE_GOTO(_CD_HIKI_NOMONEY)
@SAVE_REG()
@DRAW_MONEY_BANK(0)
@MONEYIN(0)
@Q_MONEY(100000)			;バグ?
@FALSE_GOTO(_CD_HIKI_OVER)		;機能していない(バグ?)
@WINR_MONEY()
@SE(SE_se74_my_get)
@WI(10)
◆Your account has been debited↓
  $@DSP_NUM(0).@KEY()↓
◆Please take your cash.

;jpn:◆$@DSP_NUM(0) ノ↓
;jpn: オヒキダシデスネ@KEY()↓
;jpn:◆アリガトウゴザイマシタ
@GOTO(_CD_END)

_CD_HIKI_NOMONEY;			;銀行預金 < 入力した金額
◆The requested amount is in excess of your account balance.@KEY()↓

;jpn:◆オアズカリキンガクヲ↓
;jpn: コエテイマス@KEY()↓
@GOTO(_CD_HIKIDASHI)

_CD_HIKI_OVER;				;所持金限界越える
@LOAD_REG()
@DEPOSIT_MONEY_BANK(0)
◆You are not allowed to carry more than↓
  $99,999.@KEY()↓

;◆$99999↓
;jpn: イジョウノモチアルキハ↓
;jpn: キンジラレテイマス@KEY()↓
@GOTO(_CD_HIKIDASHI)

_CD_HIKI_EMPTY;				;銀行預金$0
◆Your account is currently showing a zero balance.@KEY()↓

;jpn:◆ゲンザイ オアズカリキンハ↓
;jpn: アリマセン@KEY()↓
@GOTO(_CD_NO)

_CD_HIKI_MAX;				;所持金MAX
◆You are not allowed to carry more than↓
  $99,999.@KEY()↓

;◆$99999↓
;jpn: イジョウノモチアルキハ↓
;jpn: キンジラレテイマス@KEY()↓
@GOTO(_CD_NO)

_CD_INPUT;
@GOSUB(_CD_NOWMONEY)
◆Please enter the amount of your withdrawal.↓

;jpn:◆オヒキダシ キンガクハ?↓
_CD_INPUT_2;
@WINR_MONEY()
_CD_HOWMUCH;
@LOC(10,2)
&
@LOC(4,2)
$@INPUT(5)
@CLRLINE()
@!

_CD_INPUT_B;
@GOSUB(_CD_NOWMONEY)
◆Please enter the amount of your deposit.↓

;jpn:◆オアズケ キンガクハ?↓
@GOTO(_CD_INPUT_2)

_CD_NOWMONEY;
◆Your account currently shows a balance of↓
  $@DSP_STS(STS_PARTY_BANK_MONEY).@KEY()↓

;jpn:◆ゲンザイノ↓
;jpn: オアズカリキンガクハ↓
;jpn: $@DSP_STS(STS_PARTY_BANK_MONEY)デス@KEY()↓
@!

;
;電話
;

MSG_TEL;@Miura
@SEL_TEL_GOSUB()
@TRUE_GOTO(_TEL_END)
←
_TEL_END;
@!

MSG_TEL_2;
@SEL_TEL_GOSUB()
@TRUE_GOTO(_TEL_2END)
←
@MONEYIN(1)
@WINR_MONEY()
_TEL_2END;
@!

;
;スペーストンネル
;

MSG_SPACETNL;
◆INPUT YOUR COMMAND.↓
;@SAVE_WIN()
@DSP_PL()
;@OPEN(37)
@CHKFGOTO(FLG_STEP_PAST,_SPACE_01)
<Life−up>
<Communicate>

;jpn:◆こまんどヲ ニュウリョクセヨ↓
;jpn:<カイフク>
;jpn:<ツウシン>
@DSP_ITEM(2)

;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
_SPACE_02;
;@ONGOTO(MSG_SUB_SPACE_KAIHUKU,_SPACE_MUSEN)
@SELGOTO(MSG_SUB_SPACE_KAIHUKU,_SPACE_MUSEN)
@!

_SPACE_01;
<Repair>
<Communicate>

;jpn:<シュウリ>
;jpn:<ツウシン>
;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
@DSP_ITEM(2)
@GOTO(_SPACE_02)

_SPACE_MUSEN;
@GOSUB(MSG_PAPA)			;サブルーチン「電話(テレパパ?)」
					;に飛ぶ。
@!

;
;テレパパ
;

MSG_TEL_GAUS;
@CHKFGOTO(FLG_ITEM_GAUS,_GAUS_AFTER)
◆(Beep−beep−beep...)

;jpn:◆ツーツーツー↓
;jpn: ツーツーツー
@KEYNP()
@!
_GAUS_AFTER;
@SET_REG(1)
@SAVE_GLOBAL_REG()
◆Hello!  Hello!↓
  Maxwell Labs here.@KEY()↓
◆Oh, hello @DSP_STS(STS_PC_NAME_JEFF)!@KEY()↓
◆Would you like me to keep a record of your journey?↓

;jpn:◆はい はい↓
;jpn: ガウスの けんきゅうしつ。@KEY()↓
;jpn:◆なんだ @DSP_STS(STS_PC_NAME_JEFF)か。@KEY()↓
;jpn:◆ぼうけんのきろくを↓
;jpn: つけてほしいんだな?@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_GAUS_SAVE,_GAUS_BYE)
_GAUS_BYE;
◆You just wanted to hear my voice?↓
  Gwahahahahahahah!@KEY()↓

;jpn:◆おれのこえが↓
;jpn: ききたかったってか‥‥↓
;jpn: ガハハハハハ!@KEY()↓
_GAUS_HANGUP;
@GOTO(_PAPA_HANGUP)
@!

_GAUS_SAVE;
@LOAD_GLOBAL_REG()
@SET_COMEBACK_POS(0)
@CHKFGOTO(FLG_THRK_URBAN_ZOMBI_GONE,_GAUS_SAVE_B)	;CES用セーブ禁止
@SAVE_GAME()
_GAUS_SAVE_B;
◆All right, I have everything written down.@KEY()↓
◆Do you want to take a break now?↓
<Continue>
<End>
;jpn:◆よし つけたぞ。@KEY()↓
;jpn:◆もう やすむのか?↓
;jpn:<つづける>
;jpn:<おわる>
@DSP_ITEM(2)
@SELGOTO(_GAUS_GOON,_GAUS_END)
_GAUS_GOON;
◆You’ve become such a hard worker!@KEY()↓
◆I’ve got to get back to work myself!@KEY()↓
◆Go for it, bad boy!@KEY()↓
  
;jpn:◆おまえ ずいぶん↓
;jpn: がんばりやになったなぁ。@KEY()↓
;jpn:◆おれも もうすこし↓
;jpn: がんばってみるよ。@KEY()↓
;jpn:◆ファイト!@KEY()↓
@GOTO(_GAUS_HANGUP)

_GAUS_END;
◆I don’t know where you are planning on sleeping, but have a good rest!@KEY()↓
◆Go ahead and turn the power OFF, and have a good night.

;jpn:◆どこでねるのか しらないが↓
;jpn: ゆっくり からだを↓
;jpn: やすめろよ。@KEY()↓
;jpn:◆それじゃ でんげんを↓
;jpn: OFFにして おやすみ‥‥。
@DISKEY()
@KEYNP()
@!

MSG_PAPA;
@CHKFGOTO(FLG_PHONE_PAPA_FINAL,MSG_GLOBAL_PHONE_NG)
@CHKFGOTO(FLG_WIN_GIEGU,_PAPA_PHONE_END)
@SET_REG(1)
@SAVE_GLOBAL_REG()
←
@GET_ORDER_PLAYER(1)
@EQ(PC_NESS)
@TRUE_GOTO(_PAPA_NESS)
◆Hello?@KEY()↓
◆...Is that you, @DSP_STS(STS_PC_NAME_NES)@WI(10)?@KEY()↓
◆Why are you disguising your voice like that?@KEY()↓
◆Who are you pretending to be?@KEY()↓
◆Oh, well.  It’s not a big deal.@KEY()↓
◆I suppose you need to have a sense of humor↓ at a time like this.@KEY()↓
;◆Okay, even though I’m not sure who this is, but if you’re calling me@KEY()↓
;◆about keeping a record of your journey, I’ll gladly do it for you.@KEY()↓ 
;jpn:◆もしもし‥‥。@KEY()↓
;jpn:◆‥‥おいおい @DSP_STS(STS_PC_NAME_NES)@WI(10)↓
;jpn: そんなこえを だして↓
;jpn: いったい だれのモノマネだ?@KEY()↓
;jpn:◆‥‥ま そのままつづけなさい。@WI(15)↓
;jpn: こんなときこそ↓
;jpn: ユーモアは だいじだからな。@KEY()↓
;◆もしもし。@KEY()↓
;◆どなたかぞんじませんが↓
; ぼうけんのきろくでしたら↓
; わたしが つけておきましょう。@KEY()↓
@GOTO(_PAPA_BANK)
_PAPA_NESS;
◆@DSP_NAME(PC_NESS)?  It’s your dad.@KEY()↓
;jpn:◆あ パパだ。@KEY()↓
@CHKF(FLG_STEP_PAST)			;ロボ状態だったら
@ONGOSUB(_PAPA_ROBO)			;「風邪か?」メッセージ
_PAPA_BANK;
@Q_FIGHT_MONEY(1)
@FALSE_GOTO(_PAPA_LEVEL)
@XCHG()
◆I deposited $@DSP_NUM(0)↓
  into your bank account.@KEY()↓
◆Taking away what you’ve spent, you should now have@KEY()↓
◆$@DSP_STS(STS_PARTY_BANK_MONEY) in the bank.@KEY()↓

;jpn:◆おまえの ぎんこうこうざに↓
;jpn: @DSP_NUM(0)ドル↓
;jpn: ふりこんでおいたからね。@KEY()↓
;jpn:◆つかったぶんと さしひきで↓
;jpn: @DSP_STS(STS_PARTY_BANK_MONEY)ドル↓
;jpn: ぎんこうに はいっているはずだ。@KEY()↓
@Q_FIGHT_MONEY(2)
_PAPA_LEVEL;
@SET_LOOPREG(1)				;全プレーヤーの次のレベルまでの	loopR <- 1
◆Well, to get to next level,@KEY()

;jpn:◆えーと つぎのレベルまで‥‥
_PAPA_NEXT;				;経験値表示
@SET_REG(1)				;subR <- loopR
@Q_MEMBER(0)				;compare party(without npc) with subR
@TRUE_GOTO(_PAPA_SEL)			;全プレーヤーでループさせる。if party < subR goto _papa_sel
@GET_ORDER_PLAYER(0)			;mainR <- playerId[subR]
@FALSE_GOTO(_PAPA_SEL)			;if !mainR goto _papa_sel
@SET_REG(0)				;subR <- mainR
@GET_NEXTLEVEL(0)			;mainR <- nextLevel[subR] 
@FALSE_GOTO(_PAPA_LEVEL_MAX)		;if !nextLevel[subR] _papa_next_inc
					;この時点で、mainRには次のレベルに必要な経験値が
					;subRにはプレイヤーIDが入っている
;@XCHG()				;いらない!削除
←
◆@DSP_NAME(0)....

;jpn:◆@DSP_NAME(0)は 
@XCHG()					;xchg subR,mainR
@DSP_NUM(0).@KEY()
;jpn:@DSP_NUM(0)。@KEY()
_PAPA_NEXT_INC;
@INC()					;loopR++
@GOTO(_PAPA_NEXT)			;goto _papa_next

_PAPA_LEVEL_MAX;
←
◆@DSP_NAME(0)...↓
  has already reached (his/her) maximum level.@KEY()↓
◆That’s just fine, but...@KEY()↓

;jpn:◆@DSP_NAME(0)は‥‥
@KEY()↓
;jpn:◆もうすでに↓
;jpn: いきつくところまで↓
;jpn: いってしまったみたいだな。
@KEY()↓
;jpn:◆それは それで↓
;jpn: @WI(20)ま @WI(20)いいとして‥‥
;@KEY()↓
@GOTO(_PAPA_NEXT_INC)

_PAPA_SEL;
←
◆Anyway, what do you need from me?↓
;@SAVE_WIN()
;@DSP_PL()
;@OPEN(37)
<Record>
<Nothing, really>

;jpn:◆それはそうと なんのようだい?↓
;jpn:<きろくする>
;jpn:<とくにない>
@DSP_ITEM(2)
;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@ONGOTO(_PAPA_SAVE,_PAPA_CANCEL)
@SELGOTO(_PAPA_SAVE,_PAPA_CANCEL)

_PAPA_CANCEL;				;キャンセル
◆Good luck!@KEY()↓

;jpn:◆がんばれよ。@KEY()↓
@GOTO(_PAPA_HANGUP)

_PAPA_SAVE;				;記録する。
@LOAD_GLOBAL_REG()
@SET_COMEBACK_POS(0)
;@CHKFGOTO(FLG_THRK_URBAN_ZOMBI_GONE,_PAPA_SAVE_B)	;CES用セーブ禁止(解除)
@SAVE_GAME()
_PAPA_SAVE_B;
◆All done.@KEY()↓
◆Your dear old dad was also thinking about hitting the hay for the night.@KEY()↓
◆I have created a record of your adventure to this point.@KEY()↓
◆Good night, sleep tight.↓

;jpn:◆そうか。↓
;jpn: パパも もう きょうは↓
;jpn: やすもうと おもってたところだ。@KEY()↓
;jpn:◆ぼうけんのきろくは↓
;jpn: つけといたよ。@KEY()↓
;jpn:◆おやすみ‥‥↓
@GET_ORDER_PLAYER(1)			;先頭プレイヤーがネスじゃなければ
@EQ(PC_NESS)
@FALSE_GOTO(_PAPA_SEL_CONT)		;風邪直せ云々言わない
@CHKF(FLG_STEP_PAST)
@ONGOSUB(_PAPA_ROBO_2)			;ロボなら「風邪直せよ」。ホームシック直す。
_PAPA_SEL_CONT;
<Continue>
<End>

;jpn:<つづける>
;jpn:<おわる>
@DSP_ITEM(2)
@SELGOTO(_PAPA_GOON,_PAPA_END)

_PAPA_GOON;				;続ける。
◆@DSP_STS(STS_PC_NAME_NES), you like to work hard, just like your mother.@KEY()↓
◆But, I don’t think it’s good to work too hard.@KEY()↓

;jpn:◆@DSP_STS(STS_PC_NAME_NES)も ママににて↓
;jpn: がんばりやだなあ。@KEY()↓
;jpn:◆むりするなよ。@KEY()↓

_PAPA_HANGUP;
←
@SE(SE_se0b_tel_put)
◆(Click!  Beep−beep−beep...)

;jpn:◆ガチャン ツーツーツー
@KEYNP()
@!

_PAPA_END;				;ゲーム終了
◆We’re a great team, aren’t we?@KEY()↓
◆Well, you should turn the power OFF instead of just pressing RESET.@KEY()↓
◆All right?

;jpn:◆おたがい よくやったよな。@KEY()↓
;jpn:◆それじゃ リセットボタンを↓
;jpn: おさないで でんげんを OFFに↓
;jpn: しなさい。 わかったね。
@DISKEY()
@KEYNP()
@!

_PAPA_ROBO;
◆Who is this?!  @DSP_STS(STS_PC_NAME_NES)?!↓
  Do you have a cold or something?@KEY()↓
◆Your voice sounds kind of funny.@KEY()↓
◆Oh, well.  That’s OK.@KEY()↓

;jpn:◆あれ!? @DSP_STS(STS_PC_NAME_NES)!?↓
;jpn: カゼでもひいてるのか。↓
;jpn: こえが へんだぞ@KEY()↓
;jpn:◆ま いいか@KEY()↓
@!

;以下、ネスが先頭でない場合は呼ばれないようにした(上野)
_PAPA_ROBO_2;
◆I hope you get over your cold soon.
;jpn: はやくかぜをなおせよ。↓
@Q_SPECIAL(PC_NESS,6,2);ホームシック?
@TRUE_GOTO(_PAPA_ROBO_HOMESICK)
@!
_PAPA_ROBO_HOMESICK;
;以下、;は話の流れ上おかしくなるので削除(上野)
;@CLOSEALL()
;@WI(30)
;@OPEN(1)
;◆@DSP_STS(STS_PC_NAME_NES)は↓
; ホームシックを こくふくした。
@SET_SPECIAL(PC_NESS,6,1);ホームシック解除
@SE(SE_se25_b_healing)
;@KEY()↓
@!

_PAPA_PHONE_END;
◆Hi, it’s your dad!↓
  To get to the next level...@KEY()↓
◆Ha hah ha hah!↓
  I guess I don’t need to tell you this any more!@KEY()↓
◆... Next week will be your birthday, @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆I’m trying very hard to be home for that big day!@KEY()↓
◆I’ll be sure to get you a good present!@KEY()↓
◆I’ve been following your adventures closely,@KEY()↓
◆but I want to hear about them from you, in person.@KEY()↓
◆You sound a lot more... mature over the phone.@KEY()↓
◆...Well, I’ll see you at home, then.@KEY()↓
◆Bye!↓
  
;jpn:◆あ パパだ。↓
;jpn: つぎの レベルまで‥‥@KEY()↓
;jpn:◆ハハハハハ!@WI(20)↓
;jpn: もう そんなことをいう↓
;jpn: ひつようも ないな。@KEY()↓
;jpn:◆‥‥らいしゅうは たしか↓
;jpn: @DSP_STS(STS_PC_NAME_NES)の↓
;jpn: たんじょうび だったろう?@KEY()↓
;jpn:◆なんとか パパも↓
;jpn: それに まにあうように↓
;jpn: かえるから。@KEY()↓
;jpn:◆おみやげを たのしみに↓
;jpn: まっていておくれ。@KEY()↓
;jpn:◆いつも ぼうけんのきろくを↓
;jpn: つけていたけれど@KEY()↓
;jpn:◆おまえに ちょくせつ↓
;jpn: いろんなはなしを ききたいよ。@KEY()↓
;jpn:◆でんわのこえも ちょっと↓
;jpn: おとなっぽくなったけど‥‥@KEY()↓
;jpn:◆きっと↓
;jpn: おおきくなったんだろうなぁ。@KEY()↓
;jpn:◆‥‥じゃ こんどは↓
;jpn: いえで ゆっくりな。@KEY()↓
;jpn:◆バーイ!@WI(20)↓
@SE(SE_se0b_tel_put)
  (Click!↓
  Beep−beep−beep...)

;jpn: ガチャン ツーツーツー
@KEYNP()
@SETF(FLG_PHONE_PAPA_FINAL)
』

;
;エスカルゴ運送(電話)
;

MSG_UNSOU_TEL;
@CHKFGOTO(FLG_PHONE_ESCARGO_FINAL,MSG_GLOBAL_PHONE_NG);ツーツーツーのみ
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_1B);最終戦闘後
@CHKFGOTO(FLG_DELIVERY_UNSOU,_UNSOU_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_B,_UNSOU_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_TAKOKESHI,_UNSOU_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_TAKANOME,_UNSOU_NOW_DELIVERY)
@GOSUB(MSG_SUB_Q_NOW_DELIVERY)
@TRUE_GOTO(_UNSOU_NOW_DELIVERY)
;-----
;遺失物検査
@CHKFGOTO(FLG_GLOBAL_LOST_TAKOKESHI,MSG_UNSOU_TEL_TACO)
@CHKFGOTO(FLG_GLOBAL_LOST_TAKANOME,MSG_UNSOU_TEL_TAKA)
;-----
@GOSUB(_UNSOU_TEL_MES_1)
_UNSOU_TEL_SEL_MAIN;			;要件?
@GOSUB(_UNSOU_TEL_MES_2)
<Pick−up>
<Delivery>

;jpn:<おあずかり>
;jpn:<おとどけ>
@DSP_ITEM(2)
@SELGOTO(_UNSOU_TEL_LEAVE,_UNSOU_TEL_SEND)

_UNSOU_TEL_BYE;				;要件キャンセル
@GOSUB(_UNSOU_TEL_MES_3)
@GOSUB(_SUB_HANGUP_MES)
@!

_UNSOU_TEL_LEAVE;			;あずける選択
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_TEL_LEAVE_FULL)
_UNSOU_TEL_LEAVE_OK;
@GOSUB(_UNSOU_TEL_MES_4)
@SETF(FLG_DELIVERY_UNSOU_B)
@DELIVERY(DELIVERY_UNSOU_PICKUP)
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!

_UNSOU_TEL_LEAVE_FULL;			;預かれない。
@GOSUB(_UNSOU_TEL_MES_5)
@GOTO(_UNSOU_TEL_BYE)

_UNSOU_TEL_SEND;			;届ける選択。
@SET_LOOPREG(1)				
@GET_TRACY()
@FALSE_GOTO(_UNSOU_TEL_EMPTY)		;空?
@GOSUB(_UNSOU_TEL_MES_6)
_UNSOU_TEL_SEND_1;
@SAVE_WIN()
@SEL_TRACY_OUT()			;主レ=選択された預り所のグッズの位置
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
←
@FALSE_GOTO(_UNSOU_TEL_BYE)
@XCHG()
@SAVE_REG()				;副レ=選択された預り所のグッズの位置
@GET_TRACY_GOODS(0)
@XCHG()
◆@DSP_GOODS(0)?↓
  Do you have anything else?↓

;jpn:◆@DSP_GOODS(0)ですね。↓
@LOAD_REG()
@SET_TRANS_GOODS(255,0)
;jpn: ほかにまだありますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_TEL_SEND_2,_UNSOU_TEL_Q_OK)
@GOTO(_UNSOU_TEL_Q_OK)
_UNSOU_TEL_SEND_2;
@SET_LOOPREG(1)
@GET_TRACY()
@FALSE_GOTO(_UNSOU_TEL_EMPTY_2)
◆Select an item.@KEY()

;jpn:◆では グッズを↓
;jpn: せんたくしてください。@KEY()
@SAVE_WIN()
@SEL_TRACY_OUT()
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
←
@FALSE_GOTO(_UNSOU_TEL_Q_OK)
@XCHG()
@SAVE_REG()
@GET_TRACY_GOODS(0)
@XCHG()
◆@DSP_GOODS(0)?↓
 Do you have anything else?↓
 
;jpn:◆@DSP_GOODS(0)ですね。↓
@LOAD_REG()
@SET_TRANS_GOODS(255,0)
;jpn: ほかに ありますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_TEL_SEND_3,_UNSOU_TEL_Q_OK)
@GOTO(_UNSOU_TEL_Q_OK)
_UNSOU_TEL_SEND_3;
@SET_LOOPREG(1)
@GET_TRACY()
@FALSE_GOTO(_UNSOU_TEL_EMPTY_2)
◆Select an item.@KEY()

;jpn:◆では グッズを↓
;jpn: せんたくしてください。@KEY()
@SAVE_WIN()
@SEL_TRACY_OUT()
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
←
@FALSE_GOTO(_UNSOU_TEL_Q_OK)
@XCHG()
@SAVE_REG()
@GET_TRACY_GOODS(0)
@XCHG()
◆@DSP_GOODS(0)?@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@LOAD_REG()
@SET_TRANS_GOODS(255,0)

_UNSOU_TEL_Q_OK;			
◆Just to confirm, you’re expecting delivery of the@KEY()↓
 
;jpn:◆かくにんします。↓
;jpn: おとどけするのは@KEY()↓
@GET_TRANS_GOODS(1,0)
◆@DSP_GOODS(0)
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_TEL_Q_OK_2)
↓
  @DSP_GOODS(0)
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_TEL_Q_OK_2)
↓
  and @DSP_GOODS(0).
;jpn: あと @DSP_GOODS(0)
_UNSOU_TEL_Q_OK_2;
@KEY()
←
◆Is that correct?↓

;jpn:◆いじょうで よろしいでしょうか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_TEL_SEND_OK,_UNSOU_TEL_SEND_ONEMORE)
@GOTO(_UNSOU_TEL_SEND_ONEMORE)

_UNSOU_TEL_SEND_OK;			;届けにくる。(バッファに保存)
@GOSUB(_UNSOU_TEL_MES_7)
@SETF(FLG_DELIVERY_UNSOU)
@DELIVERY(DELIVERY_UNSOU_DELIVER)
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!

_UNSOU_TEL_EMPTY;				;預り所カラ(終了へ)
@GOSUB(_UNSOU_TEL_MES_8)
@GOTO(_UNSOU_TEL_BYE)

_UNSOU_TEL_EMPTY_2;				;預り所カラ(確認へ)
@GET_ORDER_PLAYER(1)
@XCHG()
◆We’re not storing any of @DSP_NAME(0)’s stuff right now.@KEY()↓
;jpn:◆げんざい @DSP_NAME(0)さまからは↓
;jpn: これいじょう おにもつを↓
;jpn: あずかっておりません。@KEY()↓
@GOTO(_UNSOU_TEL_Q_OK)

_UNSOU_TEL_SEND_ONEMORE;			;やり直し(バッファをクリア)
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
◆Well, please start over again.@KEY()↓

;jpn:◆では もういちど↓
;jpn: あらためて おねがいします。@KEY()↓
@GOTO(_UNSOU_TEL_SEND_1)

_UNSOU_NOW_DELIVERY;
@GOSUB(_UNSOU_TEL_MES_9)
@GOSUB(_SUB_HANGUP_MES)
@!

;

_UNSOU_TEL_MES_1;
◆Hello!  This is Escargo Express.@KEY()↓

;jpn:◆こんにちは↓
;jpn: エスカルゴうんそうでーす。@KEY()
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_UNSOU_TEL_MES_1_END)
←
◆Oh, is that you, @DSP_STS(STS_PC_NAME_NES)?↓
  Big Bro!@KEY()↓
◆It’s me, Tracy.@KEY()↓
◆I’m working part−time for Escargo Express.@KEY()↓

;jpn:◆あ@WI(10) @DSP_STS(STS_PC_NAME_NES)おにいちゃん?@KEY()↓
;jpn:◆わたしよ トレーシーよ。@KEY()↓
;jpn:◆エスカルゴうんそうで↓
;jpn: アルバイトしてるの。@KEY()
_UNSOU_TEL_MES_1_END;
@!
_UNSOU_TEL_MES_1B;最終戦闘後
◆Hello! This is Escargo Express.@KEY()↓
◆Tracy doesn’t work here any more.  Yeah, she used to work here, part−time.@KEY()↓
◆Hunh?  This is @DSP_STS(STS_PC_NAME_NES)?↓
  Tracy’s big brother?@KEY()↓
◆I’ve heard about the great work you’re doing.@KEY()↓
◆It’s an honor to talk to you, sir!@KEY()↓
◆Oh, you’re calling for a delivery?↓
  I’m very sorry.@KEY()↓
◆My wife is out on maternity leave, so I’m taking care of my other kid.@KEY()↓
◆I decided to take some time off from the delivery business.@KEY()↓
◆It’s right next to the fridge!  Put it into the microwave...  ...that’s it.@KEY()↓
◆...Sorry about that.@KEY()↓
◆I’m a little busy right now, as you heard.@KEY()↓
◆I really would like to hear some of your stories.@KEY()↓
◆Zoicks!  That was the dog’s food!@KEY()↓
◆*Crash!* Hey, hey!  Now look what you’ve done!@KEY()↓
◆...I’m sorry.↓
  I have to go.  Good bye.↓
;jpn:◆はい@WI(20) エスカルゴうんそうでーす!@WI(30)↓
;jpn: アルバイトのトレーシーちゃんなら↓
;jpn: もう やめましたよ。@KEY()↓
;jpn:◆えっ?@WI(15) あんた @DSP_STS(STS_PC_NAME_NES)とかって↓
;jpn: トレーシーのおにいさん?@KEY()↓
;jpn:◆なんだか たいそう↓
;jpn: ごりっぱな かつやくをした↓
;jpn: そうじゃないか。@KEY()↓
;jpn:◆わざわざ↓
;jpn: でんわもらっちゃうなんて↓
;jpn: こうえいだなぁ。@KEY()↓
;jpn:◆えっ はいたつですか?@WI(20)↓
;jpn: いやぁ@WI(15) ざんねんだなあ。@KEY()↓
;jpn:◆にょうぼが しゅっさんで↓
;jpn: さとがえりしましてね。@KEY()↓
;jpn:◆うえのコの めんどうを↓
;jpn: みなきゃならないんで@KEY()↓
;jpn:◆しばらく やすみを↓
;jpn: とることにしたんですよ。@KEY()↓
;jpn:◆そこの れいぞうこの↓
;jpn: よこに あるから!↓
;jpn: チンして‥‥@WI(15)そうそう。@KEY()↓
;jpn:◆‥‥あ@WI(15) しつれいしました。@WI(20)↓
;jpn: というふうに↓
;jpn: いそがしいんですよ。@KEY()↓
;jpn:◆また ゆっくり↓
;jpn: おはなしきかせてください。@KEY()↓
;jpn:◆そりゃ↓
;jpn: イヌのメシだってーの!@WI(20)↓
;jpn: (ガチャン)オラオラ!@KEY()↓
;jpn:◆‥‥じゃ すいません↓
;jpn: しつれいします。@WI(20)↓
@SE(SE_se0b_tel_put)
  (Click!)
;jpn: ガチャン ツーツーツー
@KEYNP()
@SETF(FLG_PHONE_ESCARGO_FINAL)
』
;◆あんただったら タダでいいよ。@KEY()
;@!

_UNSOU_TEL_MES_2;
←
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_2B)
◆What can I do for you?↓

;jpn:◆どんなごようけんでしょうか?↓
@!
_UNSOU_TEL_MES_2B;
◆What do you need?↓

;jpn:◆ごようけんは?↓
@!
_UNSOU_TEL_MES_3;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_3B)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_UNSOU_TEL_BYE_NESS_DEAD)
◆Come again.@KEY()

;jpn:◆また よろしくね。@KEY()
@!
_UNSOU_TEL_BYE_NESS_DEAD;
◆Please come again.@KEY()

;jpn:◆また よろしくおねがいします。@KEY()
@!
_UNSOU_TEL_MES_3B;
◆Well, come again.@KEY()

;jpn:◆じゃ@WI(15) また よろしく。@KEY()
@!

_UNSOU_TEL_MES_4;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_4B)
◆You want us to store something for you?@KEY()↓
◆We’ll send someone over immediately to pick it up.@KEY()

;jpn:◆おあずかりですね。↓
;jpn: かかりのものが すぐ↓
;jpn: そちらに まいりまーす。@KEY()
@!
_UNSOU_TEL_MES_4B;
◆Well, I’ll pick it up personally.↓
  Who am I?↓
  I’m the president!@KEY()
 
;jpn:◆じゃ@WI(20) しゃちょうのわたしが↓
;jpn: ちょくせつ とりにいきましょう!@KEY()
@!

_UNSOU_TEL_MES_5;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_5B)
◆I’m very sorry.↓
  Our storage lockers are all full right now.@KEY()↓

;jpn:◆もうしわけありません。↓
;jpn: ただいまロッカールームが↓
;jpn: いっぱいなんです。@KEY()↓
@!
_UNSOU_TEL_MES_5B;
◆I’m sorry.↓
  Our storage lockers are all full right now.@KEY()↓

;jpn:◆もうしわけありませんね。↓
;jpn: いまロッカールームが↓
;jpn: いっぱいなんですよ。@KEY()↓
@!

_UNSOU_TEL_MES_6;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_6B)
◆You would like us to deliver something?  We can deliver up to three things.@KEY()↓
◆Please select the goods you want.@KEY()
  
;jpn:◆おとどけですね↓
;jpn: 3つまで おとどけできます。@KEY()↓
;jpn:◆では グッズを↓
;jpn: せんたくしてください。@KEY()
@!
_UNSOU_TEL_MES_6B;
◆You would like us to deliver something?  We can deliver up to three things.@KEY()↓
◆Please select the goods you want.@KEY()

;jpn:◆おとどけですね↓
;jpn: 3つまで おとどけできますよ。@KEY()↓
;jpn:◆さっそく グッズを↓
;jpn: せんたくしてください。@KEY()
@!

_UNSOU_TEL_MES_7;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_7B)
◆We’ll send someone over right away!@KEY()
 
;jpn:◆かかりのものが↓
;jpn: すぐ うかがいます。@KEY()
@!
_UNSOU_TEL_MES_7B;
◆I’ll come and help you personally!@KEY()↓

;jpn:◆わたくし みずから↓
;jpn: うかがいます!@KEY()↓
@!

_UNSOU_TEL_MES_8;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_8B)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_UNSOU_TEL_EMPTY_NESS_DEAD)
◆Hey big brother @DSP_STS(STS_PC_NAME_NES),↓
  we don’t have any of your stuff in storage right now.@KEY()↓

;jpn:◆@DSP_STS(STS_PC_NAME_NES)おにいちゃん↓
;jpn: にもつなんか↓
;jpn: あずかってないわよ。@KEY()↓
@!
_UNSOU_TEL_EMPTY_NESS_DEAD;
@GET_ORDER_PLAYER(1)
@XCHG()
;@ポーラだったらマアム?
◆Sir, we do not have anything stored for a a someone@KEY()↓
◆by the name of @DSP_NAME(0).@KEY()↓

;jpn:◆げんざい @DSP_NAME(0)さまからは↓
;jpn: おにもつを↓
;jpn: あずかっておりませんが。@KEY()↓
@!
_UNSOU_TEL_MES_8B;
◆I don’t think we have anything of yours in storage.@KEY()↓

;jpn:◆どうも おたくのにもつは↓
;jpn: あずかってないようですねぇ。@KEY()↓
@!

_UNSOU_TEL_MES_9;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_9B)
◆Hello!↓
  This is Escargo Express.@KEY()↓
◆I’m very sorry, but all our delivery people are out, serving other customers.@KEY()↓
◆We can’t take any delivery orders right now.@KEY()↓
◆Please call back a little later.@KEY()

;jpn:◆こんにちは↓
;jpn: エスカルゴうんそうでーす。@KEY()↓
;jpn:◆もうしわけありませんが‥‥@KEY()↓
;jpn:◆ただいま はいたついんが↓
;jpn: ではらっておりますので↓
;jpn: うけつけられないんです。@KEY()↓
;jpn:◆また おかけなおしください。@KEY()
@!
_UNSOU_TEL_MES_9B;
◆Hello, you have reached Escargo Express.@KEY()↓
◆All of our staff members are currently out of the office.@KEY()↓
◆Please call again.↓
  This is a recording.@KEY()
 
;jpn:◆こちらは↓
;jpn: エスカルゴうんそうです。@KEY()↓
;jpn:◆このでんわは↓
;jpn: るすばんでんわです。@KEY()↓
;jpn:◆げんざい しゃいんぜんいん↓
;jpn: がいしゅつしておりますので↓
;jpn: あらためておかけなおしください。@KEY()
@!

;
;エスカルゴ運送_預かり
;

MSG_UNSOU_LEAVE;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@RESF(FLG_DELIVERY_UNSOU_B)
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL)
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_LEAVE_WINGIEGU)	;ギーグに勝った後
◆Hello, this is Escargo Express!@KEY()↓
◆Your delivery charge is $18.@KEY()↓
◆You can cover the bill, right?↓

;jpn:◆エスカルゴうんそうでーす!↓
;jpn: おあずかりりょうきんは↓
;jpn: 18ドルです。@KEY()↓
;jpn:◆おかね もってますよね?↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_UNSOU_LEAVE_MONEY_CHK,_UNSOU_LEAVE_NO)
_UNSOU_LEAVE_NO;
◆Oh, I see.↓
  Please try us again.

;jpn:◆そうですか。↓
;jpn: また よろしく。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_LEAVE_WINGIEGU;
◆Hi, I’m from Escargo Express.@KEY()↓
◆I’m here to pick up your stuff.@KEY()↓

;jpn:◆エスカルゴうんそうでーす!↓
;jpn: にもつをうけとりにきました。@KEY()↓
@GOTO(_UNSOU_LEAVE_SEL)

_UNSOU_LEAVE_MONEY_CHK;
@Q_MONEY(18)
@TRUE_GOTO(_UNSOU_LEAVE_NOMONEY)
_UNSOU_LEAVE_SEL;
◆What do you want me to take?@KEY()↓
◆I can take up to three things.@KEY()

;jpn:◆どれをおあずかりしましょう?↓
;jpn: 3つまでならOKですよ。@KEY()
@DSP_PL()
_UNSOU_LEAVE_SEL_1;
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_UNSOU_LEAVE_NO)	;キャンセル?
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_UNSOU_LEAVE_UNABLE_1)
@LOAD_REG()
@SET_TRANS_GOODS(0,0)
@GET_TRANS_GOODS(1,0)
◆@DSP_GOODS(0)?
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
←
  Will there be anything else?↓

;jpn:◆@DSP_GOODS(0)ですね。
;@Q_TRACY(PC_NESS,1)
;@CMP(2,0)
;@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
;←
;jpn: まだ ほかに ありますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_LEAVE_SEL_2,_UNSOU_LEAVE_Q_OK)
@GOTO(_UNSOU_LEAVE_Q_OK)
_UNSOU_LEAVE_SEL_2;
◆What do you want me to take?↓

;jpn:◆どれをおあずかりしましょう?↓
_UNSOU_LEAVE_SEL_2B;
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK)	;キャンセル?
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_UNSOU_LEAVE_UNABLE_2)
@LOAD_REG()
@SET_TRANS_GOODS(0,0)
@GET_TRANS_GOODS(2,0)
◆@DSP_GOODS(0)?↓
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
←
  Will there be anything else?↓

;jpn:◆@DSP_GOODS(0)ですね。
;@Q_TRACY(PC_NESS,1)
;@CMP(2,0)
;@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
;←
;jpn: まだ ほかに ありますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_LEAVE_SEL_3,_UNSOU_LEAVE_Q_OK)
@GOTO(_UNSOU_LEAVE_Q_OK)
_UNSOU_LEAVE_SEL_3;
◆Which one do you want me to take?↓

;jpn:◆どれをおあずかりしましょう?↓
_UNSOU_LEAVE_SEL_3B;
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK)	;キャンセル?
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_UNSOU_LEAVE_UNABLE_3)
@LOAD_REG()
@SET_TRANS_GOODS(0,0)
@GET_TRANS_GOODS(3,0)
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)ですね。
@KEY()↓
_UNSOU_LEAVE_Q_OK;
◆Let me just confirm your request.  You want me to take@KEY()↓
;◆@DSP_GOODS(0)
;  @DSP_GOODS(0)
;  and  @DSP_GOODS(0).
;◆Is this correct? 

;jpn:◆かくにんします↓
;jpn: おあずかりするのは@KEY()↓
@GET_TRANS_GOODS(1,0)
◆the @DSP_GOODS(0)
;◆@DSP_GOODS(0),
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK_2)
↓
  the @DSP_GOODS(0)
; @DSP_GOODS(0)
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK_2)
↓
;jpn: あと @DSP_GOODS(0)
  and the @DSP_GOODS(0).
_UNSOU_LEAVE_Q_OK_2;
@KEY()↓
◆Is this correct?↓

;jpn:◆いじょうで よろしいですか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_LEAVE_OK,_UNSOU_LEAVE_ONEMORE)
@GOTO(_UNSOU_LEAVE_ONEMORE)
_UNSOU_LEAVE_OK;
@MONEYOUT(18)
@CHKF(FLG_WIN_GIEGU)
@ONGOSUB(_UNSOU_OK_WINGIEGU)	;ギーグ倒した後
@WINR_MONEY()
@SE(SE_se76_my_give)
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
◆All right, certainly,↓
  thanks a lot!

;jpn:◆はい たしかに↓
;jpn: ありやと あんしたー。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_LEAVE_ONEMORE;
@GET_TRANS_GOODS(1,1)
@GOODSIN_PLAYER(0,0)
@GET_TRANS_GOODS(2,1)
@FALSE_GOTO(_UNSOU_LEAVE_ONEMORE_2)
@GOODSIN_PLAYER(0,0)
@GET_TRANS_GOODS(3,1)
@FALSE_GOTO(_UNSOU_LEAVE_ONEMORE_2)
@GOODSIN_PLAYER(0,0)
_UNSOU_LEAVE_ONEMORE_2;
◆Well, let’s start again, shall we?@KEY()

;jpn:◆では もういっぺん↓
;jpn: おねがいします。@KEY()
@GOTO(_UNSOU_LEAVE_SEL_1)

_UNSOU_LEAVE_UNABLE_1;
@GOSUB(_SUB_UNSOU_LEAVE_UNABLE_MES)
@GOTO(_UNSOU_LEAVE_SEL_1)

_UNSOU_LEAVE_UNABLE_2;
@GOSUB(_SUB_UNSOU_LEAVE_UNABLE_MES)
@GOTO(_UNSOU_LEAVE_SEL_2B)

_UNSOU_LEAVE_UNABLE_3;
@GOSUB(_SUB_UNSOU_LEAVE_UNABLE_MES)
@GOTO(_UNSOU_LEAVE_SEL_3B)

_UNSOU_LEAVE_GOODSFULL;
◆Excuse me.@KEY()↓
◆We checked your records and found@KEY()↓
◆that we are already storing too many of your items.@KEY()↓
◆We cannot accept any more goods from you at this time.@KEY()↓
◆Please contact us later when we may have space for your items.

;jpn:◆すいません。↓
;jpn: あずかりしょを しらべなおしたら↓
;jpn: いっぱいでした。@KEY()↓
;jpn:◆じゃ また よろしくー。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_LEAVE_GOODSFULL_2;
@KEY()↓
◆We’re sorry, we cannot carry more than three items.@KEY()↓
◆Please understand our policy.@KEY()↓
;jpn:◆あ もうこれいじょう↓
;jpn: あずかれないんで↓
;jpn: ここまでにしてください。@KEY()↓
@GOTO(_UNSOU_LEAVE_Q_OK)

_UNSOU_LEAVE_NOMONEY;
◆You don’t have enough money.@KEY()↓
◆Call us at another time.
;jpn:◆おかね たりないですね。↓
;jpn: また よろしく。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

;
;エスカルゴ運送_お届け
;

MSG_UNSOU_SEND;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@RESF(FLG_DELIVERY_UNSOU)
◆I’m from Escargo Express!!@KEY()↓
;jpn:◆エスカルゴうんそうでーっす!@KEY()↓
◆I’m here to deliver your@KEY()↓
@GET_TRANS_GOODS(1,0)
;  @DSP_GOODS(0),
;  @DSP_GOODS(0), 
;  and @DSP_GOODS(0).

◆@DSP_GOODS(0),
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_SEND_2)
;jpn:と↓
↓
  @DSP_GOODS(0),

; @DSP_GOODS(0)
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_SEND_2)
↓
;jpn: あと @DSP_GOODS(0)
  and @DSP_GOODS(0)
_UNSOU_SEND_2;
.@KEY()↓
;jpn:◆いじょうを↓
;jpn: おとどけに まいりましたー。@KEY()↓
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_SEND_GOODS_1)	;ギーグ倒した後
◆Your charge is $18.↓
  You can pay for this, right?@KEY()↓

;jpn:◆りょうきんは 18ドルです。↓
;jpn: おかね もってますよね?↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_UNSOU_SEND_YES,_UNSOU_SEND_NO_1)
_UNSOU_SEND_NO_1;			;キャンセル
◆Well, I need to take these things back then.@KEY()↓
◆Is that OK?↓

;jpn:◆じゃ にもつは↓
;jpn: もってかえりますけど@KEY()↓
;jpn:◆いいすか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_SEND_BYE,_UNSOU_SEND_NO_2)
_UNSOU_SEND_NO_2;
◆Hmmm, what should I do?@KEY()↓
◆You actually don’t have any money, right?↓

;jpn:◆こまったなー。@KEY()↓
;jpn:◆おかね ほんとは↓
;jpn: あるんでしょ?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_SEND_YES,_UNSOU_SEND_NO_1)
@GOTO(_UNSOU_SEND_NO_1)
_UNSOU_SEND_BYE;
◆Okay.↓
  Call us again later.

;jpn:◆そうですか。↓
;jpn: また よろしくー。
@KEYNP()
_UNSOU_SEND_END;
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_SEND_YES;
@Q_MONEY(18)
@TRUE_GOTO(_UNSOU_SEND_NOMONEY)
@GET_TRANS_GOODS(1,0)
_UNSOU_SEND_GOODS_1;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_UNSOU_SEND_GOODSFULL)
@GOODSIN_PLAYER(0,0)
@MONEYOUT(18)
_UNSOU_SEND_GOODS_2;
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_SEND_ALLOK)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_UNSOU_SEND_GOODSFULL_2)
@GOODSIN_PLAYER(0,0)
_UNSOU_SEND_GOODS_3;
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_SEND_ALLOK)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_UNSOU_SEND_GOODSFULL_3)
@GOODSIN_PLAYER(0,0)
_UNSOU_SEND_ALLOK;
@GOSUB(_SUB_UNSOU_SEND_OK_MES)
@GET_TRANS_GOODS(1,1)
@GET_TRANS_GOODS(2,1)
@GET_TRANS_GOODS(3,1)
@!

_UNSOU_SEND_GOODSFULL;			;グッズ欄いっぱい
◆Oh, you have too many things.↓
  Please call us again later.

;jpn:◆あれ にもつが↓
;jpn: いっぱいですね。↓
;jpn: じゃ また よろしくー。
@KEYNP()
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_SEND_GOODSFULL_2;		;グッズ欄いっぱい
◆I don’t think you can carry everything.@KEY()↓

;jpn:◆あれ ぜんぶは↓
;jpn: もてないみたいですね。@KEY()↓
@GET_TRANS_GOODS(1,1)
◆Well,  I’ll leave just↓
  the @DSP_GOODS(0).@KEY()↓

;jpn:◆じゃ @DSP_GOODS(0)だけ↓
;jpn: おわたししておきます。@KEY()↓
@GOSUB(_SUB_UNSOU_SEND_OK_MES)
@GET_TRANS_GOODS(2,1)
@TRACY_IN(0)
@GET_TRANS_GOODS(3,1)
@FALSE_GOTO(_SUB_UNSOU_GOODSFULL_2_END)
@TRACY_IN(0)
_SUB_UNSOU_GOODSFULL_2_END;
@!

_UNSOU_SEND_GOODSFULL_3;		;グッズ欄いっぱい
◆I don’t think you can carry everything.@KEY()↓

;jpn:◆あれ ぜんぶは↓
;jpn: もてないみたいですね。@KEY()↓
@GET_TRANS_GOODS(1,1)
◆Well, I’ll leave just↓
  the @DSP_GOODS(0)↓
  and
@GET_TRANS_GOODS(2,1)
 the @DSP_GOODS(0).@KEY()↓

;jpn:◆じゃ @DSP_GOODS(0)と↓
;@GET_TRANS_GOODS(2,1)
;jpn: @DSP_GOODS(0)だけ↓
;jpn: おわたししておきます。@KEY()↓
@GOSUB(_SUB_UNSOU_SEND_OK_MES)
@GET_TRANS_GOODS(3,1)
@TRACY_IN(0)
@!

_UNSOU_SEND_NOMONEY;			;お金足りない。
◆Ah, I see...You don’t have enough money.↓
  Call us again later.
@KEYNP()
;jpn:◆あれ? おかね たりないですね。↓
;jpn: じゃ また よろしく。
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

MSG_UNSOU_SEND_RETRY_OVER;
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
MSG_UNSOU_LEAVE_RETRY_OVER;
@CLRF(FLG_DELIVERY_UNSOU)
@CLRF(FLG_DELIVERY_UNSOU_B)
@GOSUB(MSG_SUB_ZYUSHIN_CALL)
@OPEN(1)
◆Hello!↓
  This is Escargo Express.↓
 (hee,ha,he,ha)@KEY()↓
◆I just (hee,ha,he,ha)couldn’t find your location...@KEY()↓
◆...You must be somewhere really strange.(hee,ha,he,ha)@KEY()↓
◆I’ve decided, honestly, that...I should give up.@KEY()↓
◆I’m outta here.(hee,ha,he,ha)@KEY()↓
◆Sometimes crap like this happens, you know?@KEY()
;jpn:◆もしもーし↓
;jpn: エスカルゴうんそうでーす。@WI(20)↓
;jpn: (ハアハア)@KEY()↓
;jpn:◆おたくさまが(ハアハア)↓
;jpn: おいでになるばしょが@WI(15)↓
;jpn: みつからなくて‥‥@KEY()↓
;jpn:◆‥‥きっと へんなところに↓
;jpn: いるんでしょうねぇ。@WI(20)↓
;jpn: (ハアハア)@KEY()↓
;jpn:◆わたし もう まごころこめて↓
;jpn: ‥‥あきらめましたから。@WI(20)↓
;jpn: かえります。(ハアハア)@KEY()↓
;jpn:◆こういうことも↓
;jpn: たまには あるんですねぇ。@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!

_SUB_HANGUP_MES;
←
@SE(SE_se0b_tel_put)
◆(Click!)

;jpn:◆ガチャン ツーツーツー。
@KEYNP()
@!

_SUB_UNSOU_SEND_OK_MES;
@CHKF(FLG_WIN_GIEGU)
@ONGOSUB(_UNSOU_OK_WINGIEGU)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆OK, here we are.↓
  Thank you!

;jpn:◆ハイ たしかに。↓
;jpn: ありやと やんしたー。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!
_UNSOU_OK_WINGIEGU;
@MONEYIN(18)
@!

_SUB_UNSOU_LEAVE_UNABLE_MES;
◆I think you should keep it.@KEY()↓
◆Do you have anything else you want me to take?@KEY()

;jpn:◆それは もっていたほうが↓
;jpn: いいと おもいますが。↓
;jpn: ほかに ありますか。@KEY()
@!

MSG_SUB_UNSOU_TRANS_RETURN_TRACY;
_SUB_UNSOU_TRANS_RETURN_TRACY;
@GET_TRANS_GOODS(1,1)
@TRACY_IN(0)
@GET_TRANS_GOODS(2,1)
@FALSE_GOTO(_TRANS_RETRA_END)
@TRACY_IN(0)
@GET_TRANS_GOODS(3,1)
@FALSE_GOTO(_TRANS_RETRA_END)
@TRACY_IN(0)
_TRANS_RETRA_END;
@!

;
;トレーシー
;

MSG_TRACY;
◆Oh, it’s my line now? Ooops!↓

;jpn:◆あ わたしの でばんね?↓
MSG_TRACY_GLOBAL_START;汎用のトレーシー呼び出し(三浦)
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_TRACY_YES,_TRACY_NO)
_TRACY_NO;
◆What the hey?↓
  Well, see you!
;jpn:◆なーんだ。@WI(15)↓
;jpn: じゃ またね!
@KEYNP()
』
MSG_TRACY_GLOBAL_START2;最終戦闘後
_TRACY_YES;
◆What do you want me to do?↓

;jpn:◆ごようは なーに?↓
_TRACY_SEL;
;@SAVE_WIN()
;@DSP_PL()
;@OPEN(37)
<store>
<check out>
;jpn:<あずける>
;jpn:<もちだす>
@DSP_ITEM(2)
;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@ONGOTO(MSG_TRACY_AZUKERU,_TRACY_MOTIDASU)
@SELGOTO(MSG_TRACY_AZUKERU,_TRACY_MOTIDASU)

_TRACY_END;
@CHKFGOTO(FLG_WIN_GIEGU,_TRACY_END_FINAL)
◆Well, take care and I’ll talk to you later!

;jpn:◆じゃ きをつけてね!
@KEYNP()
@!
_TRACY_END_FINAL;最終戦闘後
◆Well, take care and talk to you later!@KEY()↓
◆Oh, I said ”take care”!@KEY()↓
◆It just slipped out of my mouth,@KEY()↓
◆just like I was talking to you when you were gone...
;jpn:◆じゃ きをつけてね!@KEY()↓
;jpn:◆あら@WI(10) いままでのくせで↓
;jpn: きをつけてね‥‥@WI(15)なんて↓
;jpn: いっちゃった。
@KEYNP()
』

MSG_TRACY_AZUKERU;				;預ける
@GOSUB(MSG_SUB_Q_GOODSEMPTY)
@FALSE_GOTO(_TRACY_GDSEMP)
@Q_TRACY(PC_NESS,1)			;預り所チェック
@CMP(2,0)
@TRUE_GOTO(_TRACY_TRACYFULL)		;預り所いっぱい?
◆What do you want to store?@KEY()

;jpn:◆なにを あずける?@KEY()
@DSP_PL()
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_TRACY_OTHER)		;キャンセル?
_TRACY_AZUKERU_OK;
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_TRACY_AZU_UNABLE)
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@SE(SE_se76_my_give)
←
◆The @DSP_GOODS(0)?↓
  Don’t worry, I’ll keep it safe.@KEY()↓
 
;jpn:◆@DSP_GOODS(0)ね。↓
;jpn: だいじに しまっとくわ。@WI(15)@KEY()↓
@LOAD_REG()				;主レ=PLAYER_ID:副レ=GOODSの位置
@TRACY_IN_GOODS(0,0)			;預ける。

_TRACY_AZUKERU_NEXT;
←
◆Do you have anything else that you want me to store?↓
<yes>
<no>

;jpn:◆ほかに あずけるものは ある?↓
;jpn:<ある>
;jpn:<ない>
@DSP_ITEM(2)
@SELGOTO(MSG_TRACY_AZUKERU,_TRACY_OTHER)
@GOTO(_TRACY_OTHER)

_TRACY_TRACYFULL;			;預り所いっぱい
←
◆I’m sorry.↓
  My locker is full.@KEY()

;jpn:◆ごめんなさい。@WI(15)↓
;jpn: ロッカールームが↓
;jpn: いっぱいになっちゃったの。@KEY()
@GOTO(_TRACY_OTHER)

_TRACY_GDSEMP;
←
◆I don’t think you have anything to store.@KEY()

;jpn:◆あずけるものが ないみたい。@KEY()
@GOTO(_TRACY_OTHER)

_TRACY_AZU_UNABLE;
←
◆I think you should hang on to that.@KEY()↓
;jpn:◆それは もっていたほうが↓
;jpn: いいと おもうわ。@KEY()↓
@GOTO(_TRACY_AZUKERU_NEXT)

_TRACY_MOTIDASU;			;もちだす。
@SET_LOOPREG(1)				;空チェック
@GET_TRACY()
@FALSE_GOTO(_TRACY_EMPTY)		;空?
@Q_GOODSFULL(PC_ALL)			;全員のグッズ欄チェック。
@FALSE_GOTO(_TRACY_GOODSFULL)		;全員グッズ欄いっぱい?
←
◆What would you like↓
  returned?@KEY()

;jpn:◆なにを もっていくの?@KEY()
_TRACY_MOTIDASU_SEL;
;グッズ選択
@DSP_PL()
@SAVE_WIN()
;@SEL_TRACY_OUT()
_TRACY_MOTIDASU_SELB;
@SEL_TRACY_OUT()
←
@FALSE_GOTO(_TRACY_OTHER_PRE)
;プレーヤー選択
@XCHG()
@SAVE_REG()
@SAVE_WIN()
@GOSUB(MSG_SEL_GOODSIN_T)
@FALSE_GOTO(_TRACY_MOTIDASU_SEL_2)
;グッズ選択→プレーヤー選択した
@SAVE_GLOBAL_REG()
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@SE(SE_se74_my_get)
@TRACY_OUT_GOODS(0,0)
@GET_PLAYER_GOODS(0,0)
◆The @DSP_GOODS(0)?↓
  Take good care of it.@KEY()↓

;jpn:◆@DSP_GOODS(0)ね。@WI(15)↓
;jpn: だいじに してね。@WI(15)@KEY()↓
_TRACY_MOTIDASU_OTHER;
◆Is there anything else you want returned?↓
<yes>
<no>

;jpn:◆ほかに もっていくものは ある?↓
;jpn:<ある>
;jpn:<ない>
@DSP_ITEM(2)
@SELGOTO(_TRACY_MOTIDASU,_TRACY_OTHER)
@GOTO(_TRACY_OTHER)

_TRACY_MOTIDASU_SEL_2;
@XCHG()
@DSP_PL()
;@WIN_SEL_ITEMQ(13)
@GOTO(_TRACY_MOTIDASU_SELB)

_TRACY_EMPTY;
←
◆I’m not storing any of your stuff.@KEY()↓

;jpn:◆なにも あずかってないわよ。@KEY()↓
@GOTO(_TRACY_OTHER)			;キャンセル?

_TRACY_GOODSFULL;			;もちものいっぱい
←
◆I think you are already carrying too many things.@KEY()↓

;jpn:◆もちものが いっぱいみたいね。@KEY()↓
@GOTO(_TRACY_OTHER)

_TRACY_OTHER_PRE;
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
_TRACY_OTHER;				;他の用事ある?
←
◆Do you need anything else from me?↓

;jpn:◆ほかにも ようじはある?↓
@GOTO(_TRACY_SEL)

_TRACY_SELPLAYER_GOODSFULL;
←
◆I think @DSP_NAME(0) is carrying too many things.@KEY()

;jpn:◆@DSP_NAME(0)さんは↓
;jpn: もちものが いっぱいみたいよ。@KEY()
@!

;-------------------------------------------------
MSG_UNSOU_TEL_TACO;
◆Are you calling about the delivery of the ”Pencil Eraser”?↓
<yes>
<no>

;jpn:◆あ 「タコけしマシン」の↓
;jpn: おとどけね?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_UNSOU_TEL_TACO_YES,_UNSOU_TEL_TACO_NO)
_UNSOU_TEL_TACO_NO;
◆Oh, that’s not what you want?@KEY()↓

;jpn:◆あら ちがうの?@KEY()↓
@GOTO(_UNSOU_TEL_SEL_MAIN)

_UNSOU_TEL_TACO_YES;
◆We’ll send someone right away.@KEY()↓

;jpn:◆それでは かかりのものが↓
;jpn: すぐ うかがいまーす。@KEY()↓
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@DELIVERY(DELIVERY_UNSOU_TAKOKESHI)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
』

MSG_UNSOU_TEL_TAKA;
◆This is about the delivery of the ”Hawk Eye”?↓
<yes>
<no>

;jpn:◆あ 「タカのめ」の↓
;jpn: おとどけね?↓
;jpn:  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_UNSOU_TEL_TAKA_YES,_UNSOU_TEL_TAKA_NO)
_UNSOU_TEL_TAKA_NO;
◆Oh, that’s not what you want?@KEY()↓

;jpn:◆あら ちがうの?@KEY()↓
@GOTO(_UNSOU_TEL_SEL_MAIN)

_UNSOU_TEL_TAKA_YES;
◆We’ll send someone right away.@KEY()↓

;jpn:◆それでは かかりのものが↓
;jpn: すぐ うかがいまーす。@KEY()↓
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_DELIVERY_UNSOU_TAKANOME)
@DELIVERY(DELIVERY_UNSOU_TAKANOME)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
』
;-------------------------------------------------
;
;マッハピザ(電話)
;

MSG_TEL_PIZZA;
◆Hello! This is Mach Pizza!

;jpn:◆マッハピザでーす。
@CHKFGOTO(FLG_WIN_GIEGU,_PIZZA_PHONE_END)
@GOSUB(MSG_SUB_Q_NOW_DELIVERY)
@TRUE_GOTO(_PIZZA_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_PIZZA,_PIZZA_NOW_DELIVERY)

_TEL_PIZZA_ORDER
  What would you like to order?@KEY()↓
←
;jpn: ごちゅうもんは?@KEY()↓
@SAVE_WIN()
@OPEN(37)
<small>
<medium>
<large>

;jpn:<スモール>
;jpn:<ミディアム>
;jpn:<ラージ>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@ONGOTO(_TEL_PIZZA_SMALL,_TEL_PIZZA_MED,_TEL_PIZZA_LARGE)

_PIZZA_NO;				;キャンセル
◆Call again!@KEY()↓

;jpn:◆また↓
;jpn: おねがいしまーす。@KEY()↓
@GOTO(_TEL_PIZZA_END)

_TEL_PIZZA_MED;				;ミディアム(売り切れ)
◆Sorry, they are all sold out.↓

;jpn:◆すいません。↓
;jpn: いま うりきれなんです。↓
@GOTO(_TEL_PIZZA_ORDER)

_TEL_PIZZA_SMALL;			;スモール
◆You want one small pizza?↓

;jpn:◆スモールサイズひとつですね。↓
@GOTO(_TEL_PIZZA_BYE)

_TEL_PIZZA_LARGE;			;ラージ
◆You want one large pizza?↓

;jpn:◆ラージサイズひとつですね。↓
@SETF(FLG_PIZZA_SIZE)

_TEL_PIZZA_BYE;
@SET_REG(0)				;副レジ=GOODS_ID
  We’ll deliver it within 3 minutes.@KEY()↓

;jpn: 3ぷんいないに おとどけに↓
;jpn: あがりまーす。@KEY()↓
@SETF(FLG_DELIVERY_PIZZA)
@DELIVERY(DELIVERY_PIZZA)
@SETF(FLG_SYS_DISTLPT);テレポート禁止

_TEL_PIZZA_END;				;終了
@SE(SE_se0b_tel_put)
◆(Click!)

;jpn:◆ガチャン ツー ツー ツー
@KEYNP()
@!

_PIZZA_NOW_DELIVERY;
@KEY()↓
◆Our deliverlymen are not available right now.@KEY()↓
◆We can’t deliver any pizza for the time being.@KEY()↓

;jpn:◆ただいま じゅうぎょういんが↓
;jpn: ではらって おりますので↓
;jpn: はいたつが できないんですよ。@KEY()↓
@GOTO(_PIZZA_NO)

_PIZZA_PHONE_END;
@KEY()↓
◆Our delivery men got tired and quit.@KEY()↓
◆So, we decided to close the shop.@KEY()↓
◆Thank you for consistently using us for all of your pizza needs.@KEY()↓

;jpn:◆はいたつがかりが↓
;jpn: つかれちゃって↓
;jpn: やめちゃいましてね。@KEY()↓
;jpn:◆いっそ みせを↓
;jpn: たたむことに したんですよ。@KEY()↓
;jpn:◆ながいあいだ↓
;jpn: ありがとうございました。@WI(20)↓
@SE(SE_se0b_tel_put)
  (Click!)

;jpn: ガチャン ツーツーツー
@KEYNP()
』
;
;マッハピザ(届け屋)
;

MSG_PIZZA_SEND;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@RESF(FLG_DELIVERY_PIZZA)
◆Hello! Mach Pizza delivery!↓
  Here is your pizza pie, sir.@KEY()↓

;jpn:◆マッハピザでーす。↓
;jpn: ピザを とどけにきました。@KEY()↓

_PIZZA_CHK_GOODSFULL;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_PIZZA_GOODSFULL)
@SET_REG(0)
@SAVE_REG()				;副レジ=PLAYER_ID
@CHKFGOTO(FLG_PIZZA_SIZE,_PIZZA_LARGE)
@SET_LOOPREG(GDS_FOOD_PIZZA)
_PIZZA_MONEY;
@SET_REG(1)
@GOODS_TAKE_MONEY(0)			;主レジ=GOODSの値段:副レジ=GOODS_ID
@XCHG()
◆That’ll be $@DSP_NUM(0).↓
  You have the money,don’t you?↓

;jpn:◆@DSP_NUM(0)ドルです。↓
@SAVE_REG()
;jpn: おかね もってますよね?↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_PIZZA_MONEY_YES,_PIZZA_MONEY_NO)
_PIZZA_MONEY_NO;				;キャンセル
◆I see.↓
  Call us again.

;jpn:◆そうですか。↓
;jpn: じゃ また よろしくー。
_PIZZA_END;				;終了。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_PIZZA_LARGE;				;ラージサイズ時の処理
@CLRF(FLG_PIZZA_SIZE)			;フラグリセット
@SET_LOOPREG(GDS_FOOD_PIZZA_LARGE)
@GOTO(_PIZZA_MONEY)

_PIZZA_MONEY_YES;
_PIZZA_CHK;
@Q_MONEY(0)
@TRUE_GOTO(_PIZZA_NOMONEY)		;所持金足りる?
@LOAD_REG()
@XCHG()
@Q_GOODSFULL(PC_ALL)			;持ち物いっぱい?
@FALSE_GOTO(_PIZZA_GOODSFULL)
@GOODSIN_PLAYER(0,0)			;グッズ欄に
@LOAD_REG()
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Thank you very much.
 
;jpn:◆はい たしかに。↓
;jpn: ありやと やんしたー。
@GOTO(_PIZZA_END)

_PIZZA_GOODSFULL;			;持ち物いっぱい。
@CLRF(FLG_PIZZA_SIZE)			;フラグリセット
◆Oh, it looks like you can not carry any more.↓
  Call us again some other time.

;jpn:◆あれっ にもつが いっぱい↓
;jpn: みたいですね。↓
;jpn: じゃ また よろしくー。
@GOTO(_PIZZA_END)

_PIZZA_NOMONEY;				;所持金不足。
◆Oh? You are a little short of cash.  Well, call us again some other time.
  
;jpn:◆あれ? たりないですね。↓
;jpn: じゃ また よろしくー。
@GOTO(_PIZZA_END)

MSG_PIZZA_SEND_RETRY_OVER;
@CLRF(FLG_DELIVERY_PIZZA)
@CLRF(FLG_PIZZA_SIZE)
@GOSUB(MSG_SUB_ZYUSHIN_CALL)
@OPEN(1)
◆Hello!↓
  This is Mach Pizza.↓
 (hee,ha,he,ha)@KEY()↓
◆....You must be at somewhere really strange,(hee,ha,he,ha)...@KEY()↓
◆I couldn’t deliver the pizza.↓
  The pizza got really cold and hard, and my legs are tired...@KEY()↓
◆I am going to give up and go back.@KEY()↓
◆...I hope I can find the way home...↓
 (hee,ha,he,ha)@KEY()
;jpn:◆もしもーし!↓
;jpn: マッハピザでーす。(ハアハア)@KEY()↓
;jpn:◆どうやら おきゃくさまが↓
;jpn: とんでもない ところに↓
;jpn: いらっしゃるらしくて(ハアハア)@KEY()↓
;jpn:◆はいたつできませんでした。↓
;jpn: ピザは かちかちになっちゃうし↓
;jpn: あしは くたびれるし‥‥@KEY()↓
;jpn:◆こんかいは あきらめて↓
;jpn: かえらせていただきます。@KEY()↓
;jpn:◆‥‥か かえれるかなぁ。↓
;jpn: (ハアハア)@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!

;
;デパート_返品
;

MSG_DP_HENPIN;
←
◆Would you like to return something?↓

;jpn:◆ごへんぴんですか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DP_HENPIN_YES,_DP_HENPIN_NO1)

_DP_HENPIN_NO1;				;返品しない。
◆Oh, that’s good.@KEY()↓

;jpn:◆ああ よかった。@KEY()↓
_DP_HENPIN_NO2;
◆Please stop by again.

;jpn:◆これからも とうデパートを↓
;jpn: よろしくおひきたて↓
;jpn: くださいませね。@KEY()↓
;jpn:◆うっふん。
_DP_HENPIN_END;				;終了。
@KEYNP()
@!

_DP_HENPIN_YES;				;返品する。
◆What do you want to return?

;jpn:◆なにを へんぴん?
_DP_HENPIN_SEL;
@KEY()
@WINR_MONEY()
@GOSUB(MSG_SEL_GOODS)			;グッ選択
↓
@FALSE_GOTO(_DP_HENPIN_NO1)		;キャンセル?
@SAVE_REG()				;主レジ=PLAYER_ID・副レ=GOODSの位置
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)			;主レジ=GOODS_IDの金額
@FALSE_GOTO(_DP_HENPIN_UNABLE)
◆The @DSP_GOODS(0)?↓
  We can give you
  back @XCHG()$@DSP_NUM(0).@KEY()↓
◆Would you like to do that?↓

;jpn:◆@DSP_GOODS(0)ですね。↓		;グッズ名表示
;@XCHG()					;副レジ=GOODS_IDの金額
;jpn: @DSP_NUM(0)ドルで↓
;jpn: おひきとりしますが‥‥
;@KEY()↓				;売り値表示
;jpn:◆よろしゅうございますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DP_HENPIN_MONEY_YES,_DP_HENPIN_MONEY_NO)

_DP_HENPIN_MONEY_NO;			;売らない。
@GOTO(_DP_HENPIN_OTHER)

_DP_HENPIN_MONEY_YES;			;売る。
@MONEYIN(0)				;所持金に入金
@WINR_MONEY()
@SE(SE_se76_my_give)
@LOAD_REG()				;主レ=PLAYER_ID・副レ=GOODSの位置
@GOODSOUT_PLAYER(0,0)			;アイテム欄から削除。
◆Thank you very much.@KEY()↓

;jpn:◆ありがとうございます。@KEY()↓

_DP_HENPIN_OTHER;			;他に返品は?
◆Do you have anything else?↓

;jpn:◆ほかにも ございますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DP_HENPIN_YES,_DP_HENPIN_NO2)
@GOTO(_DP_HENPIN_NO2)

_DP_HENPIN_UNABLE;				;売ることができない。
◆We’re very sorry,but we don’t deal with that product.@KEY()↓

;jpn:◆おそれいります。↓
;jpn: とうてんでは↓
;jpn: あつかっておりません。@KEY()↓
@GOTO(_DP_HENPIN_OTHER)


;
;ハッピー村/フィールド/無人販売所
;

MSG_SHOP_HAPPY_AUTOSHOP;
◆(We trust you.Feel free to shop here.)@KEY()↓
◆What would you like to buy?@KEY()

;jpn:◆(あなたを しんようします。@WI(20)↓
;jpn: ごじゆうに おかいもの↓
;jpn: してください)@KEY()↓
;jpn:◆なにをかう?@KEY()
@WINR_MONEY()
@DSP_PL()
@SEL_SHOP_TAKE(SHOP_HAPPY_AUTOSHOP)
←
@FALSE_GOTO(_AUTO_NOTTAKE)
@XCHG()
_AUTO_X;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_AUTO_GOODSFULL)
@SAVE_REG()
◆How much do you want to pay?↓

;jpn:◆いくらしはらう?↓
@LOC(9,2)
&
@LOC(4,2)
$@INPUT(4)
@CLRLINE()
@XCHG()					;主レ=GOODS_ID:副レ=支払い額
@FALSE_GOTO(_AUTO_NOTTAKE)
@SAVE_REG()
@Q_MONEY(0)
@TRUE_GOTO(_AUTO_NOMONEY)
@LOAD_REG()
@XCHG()
@FALSE_GOTO(_AUTO_PAY0)
@XCHG()
@EQ(GDS_FOOD_BANANA)
@TRUE_GOTO(_AUTO_2)
_AUTO_1;
@CMP(12,1)
@FALSE_GOTO(_AUTO_FOUL)
@GOTO(_AUTO_PAY)
_AUTO_2;
@CMP(5,1)
@FALSE_GOTO(_AUTO_FOUL)
_AUTO_PAY;
@LOAD_REG()
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆@DSP_NAME(PC_NESS) paid $@DSP_NUM(0) at the self−service stand.

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn: むじんはんばいじょに↓
;jpn: @DSP_NUM(0)ドルしはらった。
@KEYNP()
_AUTO_GOODSIN;
@LOAD_REG()
@XCHG()
@GOODSIN_PLAYER(PC_NESS,0)
@SETF(FLG_HAPPY_AUTOSHOP)
_AUTO_CHK;
@!

_AUTO_FOUL;
@SETF(FLG_HAPPY_AUTOSHOP_FOUL)
@GOTO(_AUTO_PAY)


_AUTO_NOTTAKE;
◆@DSP_NAME(PC_NESS) decided not to buy anything.

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn: かうのをやめた。
@KEYNP()
@!

_AUTO_PAY0;
◆@DSP_NAME(PC_NESS) did not pay.

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn: おかねを はらわなかった。
@KEYNP()
@SETF(FLG_HAPPY_AUTOSHOP_FOUL)
@GOTO(_AUTO_GOODSIN)

_AUTO_GOODSFULL;
◆@DSP_NAME(PC_NESS) could not
  carry any more stuff.

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn: もちものがいっぱいだった。
@KEYNP()
@!

_AUTO_NOMONEY;
◆@DSP_NAME(PC_NESS) did not have
  that much money.

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn: そんなにおかねを↓
;jpn: もっていなかった。
@KEYNP()
@!


;
;アイス売り
;

MSG_SUMS_ICE;
@GOSUB(MSG_SHOP_SUMS_ICE)
@!

;
;水売り
;

MSG_SKRB_WATER;
@GOSUB(MSG_SHOP_SKRB_WATER)
@!

MSG_SUMS_WIFE;
MSG_SUMS_MAZICTORTE;
@GOSUB(MSG_SHOP_SUMS_WIFE)
@!

MSG_HAPPY_DRUGSTORE;
@GOSUB(MSG_SHOP_HAPPY_DRUGSTORE)
@!
MSG_SHOP_DOSEI_BAKA3;
@GOSUB(MSG_SHOP_SHOP_DOSEI_BAKA3)
@!
MSG_DSRT_SHOP2;
@GOSUB(MSG_SHOP_DSRT_SHOP2)
@!
MSG_TWSN_FURIKAKE;
@GOSUB(MSG_SHOP_SKRB_FURIKAKE)
@!
MSG_SKRB_FURIKAKE;
@GOSUB(MSG_SHOP_SKRB_FURIKAKE)
@!
MSG_SKRB_BAZAR_B;
@GOSUB(MSG_SHOP_SKRB_BAZAR_B)
@!
MSG_DSRT_BENTOU;
@GOSUB(MSG_SHOP_DSRT_BENTOU)
@!
MSG_RAMA_OKAYU;
@GOSUB(MSG_SHOP_RAMA_OKAYU)
@!
MSG_WINS_STONEHENGE_B;
@GOSUB(MSG_SHOP_WINS_STONEHENGE_B)
@!

MSG_HOTEL_MOON_SHOP;
@GOSUB(MSG_SHOP_HOTEL_MOON_SHOP)
@!

MSG_SUMS_MAGICCAKE_WAGON;
MSG_SUMS_HOTDOG_WAGON;
MSG_DSRT_BENTOU_WAGON;
@GOSUB(MSG_SYS_NOPROBLEM)
@!

;
;グミの物々交換
;


MSG_SUB_GUMI_BUTUBUTU;
@CHKFGOTO(FLG_GUMI_7_BOOK,_BUTUBUTU_AFTER)
◆I would like the @DSP_GOODS(GDS_TOOL_LIFE_HORN).@KEY()↓
◆If you give me↓
  the @DSP_GOODS(GDS_TOOL_LIFE_HORN),@KEY()↓
◆I’ll give you something in return.@KEY()↓
◆Look at my list.
; <poor qualitiy bread>
; <simple yogult>
; <poor qualitiy bread>
; <spicy jerkey>
; <dragon powder>
; <magical power sealing coin>
;  note: this is one of the defense goods.
; <the best bat>
 
;jpn:◆おれ↓
 @DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn: ほしい。@KEY()↓
◆@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn: くれれば@KEY()↓
;jpn:◆おれいに ものやる。@KEY()↓
;jpn:◆やるもの リスト
;jpn: みろ。@KEY()
@OPEN(7)
@CHKFGOTO(FLG_GUMI_1_BOOK,_BUTUBUTU_GOODS2)
<Plain roll>

;jpn:<そまつなパン>
_BUTUBUTU_GOODS2;
@CHKFGOTO(FLG_GUMI_2_BOOK,_BUTUBUTU_GOODS3)
<Plain yogurt>

;jpn:<そぼくなヨーグルト>
_BUTUBUTU_GOODS3;
@CHKFGOTO(FLG_GUMI_3_BOOK,_BUTUBUTU_GOODS4)
<Plain roll>

;jpn:<そまつなパン>
_BUTUBUTU_GOODS4;
@CHKFGOTO(FLG_GUMI_4_BOOK,_BUTUBUTU_GOODS5)
<spicy jerky>

;jpn:<スパイシーなほしにく>
_BUTUBUTU_GOODS5;
@CHKFGOTO(FLG_GUMI_5_BOOK,_BUTUBUTU_GOODS6)
<Dragon Powder>

;jpn:<ドラゴンパウダー>
_BUTUBUTU_GOODS6;
@CHKFGOTO(FLG_GUMI_6_BOOK,_BUTUBUTU_GOODS7)
<Talisman coin>

;jpn:<まふうじのコイン>
_BUTUBUTU_GOODS7;
<All−Star bat>

;jpn:<さいこうのバット>
@DSP_ITEML(1)
@KEYNP()
@CLOSE()
@SELECT_WIN(1)
←
◆Will you give me↓
  the @DSP_GOODS(GDS_TOOL_LIFE_HORN)?@KEY()

;◆@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn: くれるか?@KEY()
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_BUTUBUTU_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_LIFE_HORN)
@FALSE_GOTO(_BUTUBUTU_MISS)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@GOSUB(_SUB_BUTUBUTU_SELGOODS)
@SET_REG(1)
←
◆Okay.↓
  I give you the @DSP_GOODS(0).@KEY()↓
◆You happy.↓
  I happy.@KEY()
 
;jpn:◆よし。↓
;jpn: @DSP_GOODS(0)やる。@KEY()↓
;jpn:◆うれしい おまえ。↓
;jpn: うれしい おれ。@KEY()
←
@Q_GOODSFULL(PC_ALL)
@SAVE_REG()
@GOODSIN_PLAYER(0,0)
@GOSUB(MSG_SUB_GETGOODS)
@KEYNP()
@!
_BUTUBUTU_NO;
←
◆You not want? It Okay.↓
  Come again.

;jpn:◆いやなら いいんだ。↓
;jpn: またこい。
@KEYNP()
@!
_BUTUBUTU_MISS;
←
◆That not the one.
 
;jpn:◆それ ちがう。
@KEYNP()
@!
_BUTUBUTU_AFTER;
◆More @DSP_GOODS(GDS_TOOL_LIFE_HORN)?@KEY()↓
◆I satisfied.@KEY()↓
◆See ya!
 
;◆@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn: たまった。@KEY()↓
;jpn:◆まんぞくした おれ。@KEY()↓
;jpn:◆じゃあな。
@KEYNP()
@!

_SUB_BUTUBUTU_SELGOODS;
@CHKFGOTO(FLG_GUMI_6_BOOK,_BUTUBUTU_SELGOODS_7)
@CHKFGOTO(FLG_GUMI_5_BOOK,_BUTUBUTU_SELGOODS_6)
@CHKFGOTO(FLG_GUMI_4_BOOK,_BUTUBUTU_SELGOODS_5)
@CHKFGOTO(FLG_GUMI_3_BOOK,_BUTUBUTU_SELGOODS_4)
@CHKFGOTO(FLG_GUMI_2_BOOK,_BUTUBUTU_SELGOODS_3)
@CHKFGOTO(FLG_GUMI_1_BOOK,_BUTUBUTU_SELGOODS_2)
_BUTUBUTU_SELGOODS_1;
@SET_LOOPREG(GDS_FOOD_GUMI_BREAD)
@SETF(FLG_GUMI_1_BOOK)
@!
_BUTUBUTU_SELGOODS_2;
@SET_LOOPREG(GDS_FOOD_GUMI_YOGURT)
@SETF(FLG_GUMI_2_BOOK)
@!
_BUTUBUTU_SELGOODS_3;
@SET_LOOPREG(GDS_FOOD_GUMI_BREAD)
@SETF(FLG_GUMI_3_BOOK)
@!
_BUTUBUTU_SELGOODS_4;
@SET_LOOPREG(GDS_FOOD_DRY_MEAT_GREAT)
@SETF(FLG_GUMI_4_BOOK)
@!
_BUTUBUTU_SELGOODS_5;
@SET_LOOPREG(GDS_TOOL_DRAGON_POWDER)
@SETF(FLG_GUMI_5_BOOK)
@!
_BUTUBUTU_SELGOODS_6;
@SET_LOOPREG(GDS_EQUIP_COIN_MAFUJI)
@SETF(FLG_GUMI_6_BOOK)
@!
_BUTUBUTU_SELGOODS_7;
@SET_LOOPREG(GDS_EQUIP_BAT_SAIKO)
@SETF(FLG_GUMI_7_BOOK)
@!

;魔境のキャッシュディスペンサー男
MSG_SUB_MAKYO_CDMAN;
◆Shhhhh! Be quiet!↓
  I look very important, but I’m not really.......@KEY()↓
◆I’m a cash dispenser man.@KEY()↓
◆If you want to withdraw cash.....@KEY()↓
◆I’ll charge you a handling fee,@KEY()↓
◆which is the same amount as your withdrawal.@KEY()↓
◆So, do you want a withdrawal?↓
;jpn:◆しっ! しずかに!@WI(20)↓
;jpn: わたしは じゅうようそうだけど↓
;jpn: そうでもない‥‥@KEY()↓
;jpn:◆キャッシュディスペンサーおとこ↓
;jpn: ‥‥です。@KEY()↓
;jpn:◆‥‥ひきだすばあい↓
;jpn: あつかいきんがくと@KEY()↓
;jpn:◆どうがくの↓
;jpn: てすうりょうを↓
;jpn: いただきますが‥‥@KEY()↓
;jpn:◆ごりように なりますか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_CDMAN_YES,_CDMAN_NO)
_CDMAN_NO;
←
◆....I’ll be here, so...↓
  Come back any time.

;jpn:◆‥‥わたしは いつも↓
;jpn: ここにいますから‥‥@WI(15)↓
;jpn: いつでも どうぞ。
@KEYNP()
@!
_CDMAN_YES;
◆You have $@DSP_STS(STS_PARTY_BANK_MONEY) in your account now.↓
<Withdrawal>
<Deposit>

;jpn:◆いま ぎんこうよきんは↓
;jpn: @DSP_STS(STS_PARTY_BANK_MONEY)ドルです。↓
;jpn:<ひきだす>
;jpn:<あずける>
@DSP_ITEM(2)
@SELGOTO(_CDMAN_HIKI,_CDMAN_AZU)
@GOTO(_CDMAN_NO)
_CDMAN_AZU;
@Q_BANK_MONEY(9999999)
@FALSE_GOTO(_CDMAN_AZU_FULL)
@GOSUB(_CDMAN_AZU_INPUT)
@FALSE_GOTO(_CDMAN_NO)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_CDMAN_AZU_NOMONEY)
@MONEYOUT(0)
@DEPOSIT_MONEY_BANK(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(10)
◆I have registered your deposit↓
  of $@DSP_NUM(0).@KEY()↓

;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn: たしかにおあずかりしました。
;@KEY()↓
@GOTO(_CDMAN_THANKS)

_CDMAN_HIKI;
@Q_BANK_MONEY(1)
@TRUE_GOTO(_CDMAN_HIKI_EMPTY)
@Q_MONEY(99999)
@FALSE_GOTO(_CDMAN_HIKI_MAX)
@GOSUB(_CDMAN_HIKI_INPUT)
@FALSE_GOTO(_CDMAN_NO)
@XCHG()
@Q_BANK_MONEY(0)
@TRUE_GOTO(_CDMAN_HIKI_NOMONEY)
@DRAW_MONEY_BANK(0)
@Q_BANK_MONEY(0)
@TRUE_GOTO(_CDMAN_HIKI_NOMONEY_2)
◆Your cash withdrawal↓
  is $@DSP_NUM(0),@KEY()↓
◆and the handling charge↓
  is $@DSP_NUM(0).@KEY()↓
◆I will subtract this amount from your account.@KEY()↓
◆Is that okay with you?↓
;jpn:◆おわたしするぶんが↓
;jpn:  @DSP_NUM(0)ドル@KEY()↓
;jpn:◆てすうりょうが↓
;jpn:  @DSP_NUM(0)ドル@KEY()↓
;jpn:◆これだけ ひきだしますが↓
;jpn: よろしいですか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_CDMAN_HIKI_YES,_CDMAN_HIKI_NO)
_CDMAN_HIKI_NO;
@DEPOSIT_MONEY_BANK(0)
@GOTO(_CDMAN_NO)

_CDMAN_HIKI_YES;
@DRAW_MONEY_BANK(0)
@MONEYIN(0)
@WINR_MONEY()
@SE(SE_se74_my_get)
@WI(10)
◆Your withdrawal↓
  is $@DSP_NUM(0).@KEY()

;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn: たしかにおひきだししました。
;@KEY()↓
@GOTO(_CDMAN_THANKS)


_CDMAN_THANKS;
←
◆Okay...@KEY()↓
◆Please don’t bother yourself with me...you should continue your journey.

;jpn:◆じゃ‥‥↓
;jpn: わたしのことは わすれて↓
;jpn: たびを おつづけください。
@KEYNP()
@!

_CDMAN_AZU_FULL;
←
◆I don’t think you can deposit any more money.@KEY()↓

;jpn:◆これいじょうは↓
;jpn: おかねを あずけられない↓
;jpn: みたいですね。@KEY()↓
@GOTO(_CDMAN_NO)
_CDMAN_AZU_NOMONEY;
←
◆I don’t think you have that much money.@KEY()↓

;jpn:◆あなたは そんなに↓
;jpn: おかねを もっていない↓
;jpn: みたいですが‥‥@KEY()↓
@GOTO(_CDMAN_AZU)
_CDMAN_HIKI_EMPTY;
◆I don’t think you have any savings in the bank.@KEY()

;jpn:◆あなたは ぎんこうに↓
;jpn: よきんをして おられない↓
;jpn: みたいですが‥‥@KEY()
@GOTO(_CDMAN_NO)
_CDMAN_HIKI_MAX;
◆I don’t think you can withdraw any more money.@KEY()↓

;jpn:◆あなたは これいじょう↓
;jpn: おかねをひきだせない↓
;jpn: みたいですが‥‥@KEY()↓
@GOTO(_CDMAN_NO)
_CDMAN_HIKI_NOMONEY;
◆I don’t think you have that much money in your account.@KEY()↓

;jpn:◆あなたは そんなに↓
;jpn: ぎんこうに あずけておられない↓
;jpn: みたいですが‥‥@KEY()↓
@GOTO(_CDMAN_HIKI)
_CDMAN_HIKI_NOMONEY_2;
@DEPOSIT_MONEY_BANK(0)
◆I don’t think you have enough money for my handling fee.@KEY()↓

;jpn:◆わたしのぶんが↓
;jpn: たりないみたい↓
;jpn: なんですが‥‥@KEY()↓
@GOTO(_CDMAN_HIKI)


_CDMAN_AZU_INPUT;
←
◆How much will you deposit?↓

;jpn:◆いくらあずけますか?↓
@GOSUB(_CD_INPUT_2)
@!
_CDMAN_HIKI_INPUT;
←
◆How much do you want to withdraw?↓

;jpn:◆いくらひきだしますか?↓
@GOSUB(_CD_INPUT_2)
@!
  

;キャッシュディスペンサー機能の地底グミ
;外国留学経験者?
MSG_SUB_DKFD_EGO;
@CHKFGOTO(FLG_TEMP_1,_EGO_TMP)
@SETF(FLG_TEMP_1)
◆You’re a foreigner, aren’t you?@KEY()↓
◆I am a world−wise Tenda.@KEY()↓
◆I was an exchange student who traveled to a country@KEY()↓
◆that is known as an economic superpower.@KEY()↓
◆My name is Ay−go Stikke.@KEY()↓
◆Let me know if I can do anything for you.@KEY()↓

;jpn:◆がいこくの かたですね?@KEY()↓
;jpn:◆ボクは あるけいざいたいこくに↓
;jpn: りゅうがく けいけんのある↓
;jpn: はなしのわかる グミです。@KEY()↓
;jpn:◆なまえは エーゴ・ステッキです。@KEY()↓
;jpn:◆おやくにたてることが あったら↓
;jpn: いつでも いってください。@KEY()↓
_EGO_1;
◆Shall I loan you some money?↓

;jpn:◆おかねを↓
;jpn: ごようだて しましょうか?@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_EGO_YES_1,_EGO_NO_1)
_EGO_NO_1;
◆I don’t feel strange about it at all.↓
  Please ask me any time.

;jpn:◆わたしは↓
;jpn: きをわるくしたりなんかしません。@WI(20)↓
;jpn: また いつでも どうぞ。
@KEYNP()
@!
_EGO_YES_1;
◆If you want to withdraw.....@KEY()↓
◆I will charge you a handling fee@KEY()↓
◆that is equal to the amount of your withdrawal.@KEY()↓
◆Is that okay with you?↓
;jpn:◆おかねのおひきだしには↓
;jpn: あつかいきんがくと どうがくの↓
;jpn: てすうりょうを いただきますが@KEY()↓
;jpn:◆よろしいですね?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_EGO_YES_2,_EGO_NO_2)
_EGO_NO_2;
◆I don’t think you’ve ever really gotten into bad trouble.

;jpn:◆まだ ほんとうに このせかいで↓
;jpn: こまっては いないようですね。
@KEYNP()
@!
_EGO_YES_2;
◆You have $@DSP_STS(STS_PARTY_BANK_MONEY) in your account now.↓
<Withdrawal>
<Deposit>

;jpn:◆あなたのぎんこうよきんは↓
;jpn: いま@DSP_STS(STS_PARTY_BANK_MONEY)ドルです。↓
;jpn:<ひきだす>
;jpn:<あずける>
@DSP_ITEM(2)
@SELGOTO(_EGO_HIKI,_EGO_AZU)
@GOTO(_EGO_NO_1)

_EGO_AZU;
@Q_BANK_MONEY(9999999)
@FALSE_GOTO(_EGO_AZU_FULL)
@GOSUB(_EGO_AZU_INPUT)
@FALSE_GOTO(_EGO_NO_1)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_EGO_AZU_NOMONEY)
@MONEYOUT(0)
@DEPOSIT_MONEY_BANK(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(10)
◆I have registered your deposit↓
  of $@DSP_NUM(0).@KEY()↓
    
;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn: たしかにおあずかりしました。
;@KEY()↓
@GOTO(_EGO_THANKS)

_EGO_HIKI;
@Q_BANK_MONEY(1)
@TRUE_GOTO(_EGO_HIKI_EMPTY)
@Q_MONEY(99999)
@FALSE_GOTO(_EGO_HIKI_MAX)
@GOSUB(_EGO_HIKI_INPUT)
@FALSE_GOTO(_EGO_NO_1)
@XCHG()
@Q_BANK_MONEY(0)
@TRUE_GOTO(_EGO_HIKI_NOMONEY)
@DRAW_MONEY_BANK(0)
@Q_BANK_MONEY(0)
@TRUE_GOTO(_EGO_HIKI_NOMONEY_2)
◆Your withdrawal↓
  is $@DSP_NUM(0),@KEY()↓
◆and the handling fee↓
  is $@DSP_NUM(0).@KEY()↓
◆Is it okay if I subtract this amount from your account?↓

;jpn:◆おわたしするぶんが↓
;jpn:  @DSP_NUM(0)ドル@KEY()↓
;jpn:◆てすうりょうが↓
;jpn:  @DSP_NUM(0)ドル@KEY()↓
;jpn:◆これだけ ひきだしますが↓
;jpn: いいですか?↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_EGO_HIKI_YES,_EGO_HIKI_NO)
_EGO_HIKI_NO;
@DEPOSIT_MONEY_BANK(0)
@GOTO(_EGO_NO_2)

_EGO_HIKI_YES;
@DRAW_MONEY_BANK(0)
@MONEYIN(0)
@WINR_MONEY()
@SE(SE_se74_my_get)
@WI(10)
◆Your withdrawal↓
 is $@DSP_NUM(0).@KEY()↓

;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn: たしかにおひきだししました。
;@KEY()↓
@GOTO(_EGO_THANKS)

_EGO_THANKS;
←
◆It was a very good opportunity for the both of us.↓
  Please come again.

;jpn:◆おたがいに とてもいい↓
;jpn: チャンスでしたね。@WI(20)↓
;jpn: また よろしく おねがいします。
@KEYNP()
』

_EGO_AZU_FULL;
◆I don’t think you can deposit any more money.@KEY()↓

;jpn:◆これいじょう↓
;jpn: あずけられないみたいですね。@KEY()↓
@GOTO(_EGO_NO_1)
_EGO_AZU_NOMONEY;
◆I don’t think you have that much money.@KEY()↓

;jpn:◆あなたは そんなに↓
;jpn: おかねを もっていませんよ。@KEY()↓
@GOTO(_EGO_AZU)
_EGO_HIKI_EMPTY;
◆You don’t have any money in your account.@KEY()↓

;jpn:◆あなたは まったく↓
;jpn: ちょきんをしていませんね。@KEY()↓
@GOTO(_EGO_NO_1)
_EGO_HIKI_MAX;
◆I think it’s impossible for you to carry any more money.@KEY()↓

;jpn:◆あなたは これいじょう↓
;jpn: おかねをもっていても↓
;jpn: しょうがないですよ。@KEY()↓
@GOTO(_EGO_NO_1)
_EGO_HIKI_NOMONEY;
◆You don’t have that much money in your account.@KEY()↓

;jpn:◆あなたは そんなに↓
;jpn: ちょきんをしていませんね。@KEY()↓
@GOTO(_EGO_HIKI)
_EGO_HIKI_NOMONEY_2;
@DEPOSIT_MONEY_BANK(0)
◆I don’t think you can cover my handling charge.@KEY()↓

;jpn:◆わたしのてすうりょうが↓
;jpn: もらえないみたいてす。@KEY()↓
@GOTO(_EGO_HIKI)

_EGO_TMP;
◆Hi!  I’m Ay−go.@KEY()↓

;jpn:◆ハーイ! エーゴです。@KEY()↓
@GOTO(_EGO_1)
_EGO_AZU_INPUT;
←
◆How much do you want to deposit?↓

;jpn:◆いくらあずけますか?↓
@GOSUB(_CD_INPUT_2)
@!
_EGO_HIKI_INPUT;
←
◆How much do you want to withdraw?↓

;jpn:◆いくらひきだしますか?↓
@GOSUB(_CD_INPUT_2)
@!

MSG_SUB_BGM_PIZZASTART;
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
;@FUNC(18)		;自転車から降りる
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
;@BGMSTART(0,BGM_piza)
@OPEN(1)
@!
MSG_SUB_BGM_PIZZAEND;
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
;@MUSISTART()
@!
