MSG_SUB_SHOPMES_1;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_1)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_1)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_1)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_1)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_1)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_1)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_1)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_1)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_1)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_1)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_1)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_1)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_1)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_1)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_1)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_1)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_1)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_1)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_1)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_1)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_1)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_1)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_1)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_1)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_1)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_1)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_1)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_1)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_1)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_1)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_1)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_1)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_1)
@!
MSG_SUB_SHOPMES_2;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_2)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_2)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_2)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_2)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_2)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_2)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_2)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_2)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_2)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_2)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_2)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_2)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_2)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_2)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_2)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_2)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_2)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_2)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_2)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_2)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_2)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_2)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_2)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_2)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_2)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_2)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_2)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_2)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_2)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_2)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_2)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_2)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_2)
@!
MSG_SUB_SHOPMES_3;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_3)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_3)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_3)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_3)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_3)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_3)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_3)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_3)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_3)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_3)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_3)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_3)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_3)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_3)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_3)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_3)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_3)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_3)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_3)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_3)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_3)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_3)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_3)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_3)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_3)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_3)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_3)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_3)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_3)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_3)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_3)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_3)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_3)
@!
MSG_SUB_SHOPMES_4;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_4)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_4)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_4)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_4)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_4)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_4)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_4)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_4)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_4)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_4)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_4)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_4)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_4)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_4)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_4)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_4)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_4)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_4)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_4)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_4)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_4)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_4)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_4)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_4)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_4)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_4)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_4)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_4)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_4)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_4)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_4)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_4)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_4)
@!
MSG_SUB_SHOPMES_5;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_5)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_5)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_5)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_5)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_5)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_5)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_5)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_5)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_5)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_5)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_5)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_5)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_5)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_5)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_5)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_5)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_5)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_5)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_5)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_5)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_5)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_5)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_5)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_5)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_5)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_5)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_5)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_5)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_5)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_5)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_5)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_5)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_5)
@!
MSG_SUB_SHOPMES_6;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_6)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_6)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_6)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_6)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_6)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_6)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_6)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_6)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_6)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_6)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_6)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_6)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_6)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_6)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_6)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_6)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_6)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_6)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_6)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_6)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_6)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_6)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_6)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_6)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_6)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_6)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_6)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_6)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_6)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_6)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_6)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_6)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_6)
@!
MSG_SUB_SHOPMES_7;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_7)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_7)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_7)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_7)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_7)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_7)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_7)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_7)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_7)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_7)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_7)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_7)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_7)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_7)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_7)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_7)
@!
MSG_SUB_SHOPMES_8;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_8)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_8)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_8)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_8)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_8)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_8)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_8)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_8)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_8)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_8)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_8)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_8)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_8)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_8)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_8)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_8)
@!
MSG_SUB_SHOPMES_9;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_9)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_9)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_9)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_9)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_9)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_9)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_9)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_9)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_9)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_9)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_9)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_9)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_9)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_9)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_9)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_9)
@!
MSG_SUB_SHOPMES_10;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_10)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_10)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_10)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_10)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_10)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_10)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_10)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_10)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_10)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_10)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_10)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_10)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_10)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_10)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_10)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_10)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_10)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_10)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_10)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_10)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_10)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_10)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_10)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_10)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_10)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_10)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_10)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_10)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_10)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_10)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_10)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_10)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_10)
@!
MSG_SUB_SHOPMES_11;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_11)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_11)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_11)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_11)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_11)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_11)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_11)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_11)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_11)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_11)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_11)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_11)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_11)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_11)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_11)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_11)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_11)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_11)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_11)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_11)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_11)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_11)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_11)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_11)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_11)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_11)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_11)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_11)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_11)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_11)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_11)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_11)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_11)
@!
MSG_SUB_SHOPMES_12;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_12)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_12)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_12)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_12)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_12)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_12)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_12)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_12)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_12)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_12)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_12)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_12)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_12)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_12)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_12)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_12)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_12)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_12)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_12)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_12)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_12)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_12)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_12)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_12)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_12)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_12)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_12)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_12)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_12)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_12)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_12)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_12)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_12)
@!
MSG_SUB_SHOPMES_13;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_13)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_13)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_13)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_13)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_13)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_13)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_13)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_13)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_13)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_13)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_13)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_13)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_13)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_13)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_13)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_13)
@!
MSG_SUB_SHOPMES_14;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_14)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_14)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_14)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_14)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_14)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_14)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_14)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_14)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_14)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_14)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_14)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_14)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_14)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_14)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_14)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_14)
@!
MSG_SUB_SHOPMES_15;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_15)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_15)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_15)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_15)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_15)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_15)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_15)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_15)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_15)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_15)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_15)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_15)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_15)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_15)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_15)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_15)
@!
MSG_SUB_SHOPMES_16;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_16)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_16)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_16)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_16)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_16)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_16)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_16)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_16)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_16)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_16)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_16)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_16)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_16)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_16)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_16)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_16)
@!
MSG_SUB_SHOPMES_17;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_17)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_17)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_17)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_17)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_17)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_17)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_17)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_17)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_17)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_17)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_17)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_17)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_17)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_17)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_17)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_17)
@!
MSG_SUB_SHOPMES_18;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_18)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_18)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_18)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_18)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_18)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_18)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_18)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_18)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_18)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_18)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_18)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_18)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_18)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_18)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_18)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_18)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_18)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_18)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_18)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_18)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_18)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_18)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_18)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_18)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_18)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_18)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_18)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_18)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_18)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_18)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_18)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_18)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_18)
@!
MSG_SUB_SHOPMES_20;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_20)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_20)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_20)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_20)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_20)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_20)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_20)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_20)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_20)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_20)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_20)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_20)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_20)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_20)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_20)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_20)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_20)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_20)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_20)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_20)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_20)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_20)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_20)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_20)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_20)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_20)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_20)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_20)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_20)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_20)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_20)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_20)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_20)
@!
MSG_SUB_SHOPMES_21;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_21)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_21)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_21)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_21)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_21)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_21)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_21)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_21)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_21)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_21)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_21)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_21)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_21)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_21)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_21)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_21)
@!
MSG_SUB_SHOPMES_22;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_22)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_22)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_22)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_22)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_22)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_22)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_22)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_22)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_22)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_22)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_22)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_22)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_22)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_22)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_22)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_22)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_22)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_22)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_22)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_22)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_22)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_22)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_22)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_22)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_22)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_22)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_22)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_22)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_22)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_22)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_22)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_22)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_22)
@!
;
;ショップタイプAのメッセージ
;
;男子店員(male clerk)
MSG_SUB_SHOPMES_DRUG1_1;
MSG_SUB_SHOPMES_TOYSHOP_1;
◆Hello there!↓
  How may I help you?↓

;jpn:◆いらっしゃいませ。@KEY()↓
;jpn:◆ごようは?↓
@!
MSG_SUB_SHOPMES_DRUG1_2;
MSG_SUB_SHOPMES_TOYSHOP_2;
◆Thank you very much.

;jpn:◆どうもありがとうございました。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG1_3;
◆Please come again.

;jpn:◆またよろしくおねがいします。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG1_4;
MSG_SUB_SHOPMES_TOYSHOP_4;
◆Can I get you↓
  anything?
;jpn:◆なにを おかいもとめですか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG1_5;
MSG_SUB_SHOPMES_TOYSHOP_5;
◆@DSP_GOODS(0)?↓
  All right.

;jpn:◆@DSP_GOODS(0)ですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_6;
MSG_SUB_SHOPMES_TOYSHOP_6;
◆Which of you will carry this?

;jpn:◆どなたが おもちになりますか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG1_7;
MSG_SUB_SHOPMES_TOYSHOP_7;
◆Thank you.  Are you going to equip it here?↓

;jpn:◆ありがとうございます。↓
;jpn: ここで そうびしてみますか?↓
@!
MSG_SUB_SHOPMES_DRUG1_8;
MSG_SUB_SHOPMES_TOYSHOP_8;
◆Would you like me to buy↓
  the @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0)?@KEY()↓

;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かいあげましょうか?↓
@!
MSG_SUB_SHOPMES_DRUG1_9;
MSG_SUB_SHOPMES_TOYSHOP_9;
◆@DSP_NAME(0) cannot equip this.@KEY()↓
◆Do you still want to buy it?↓

;jpn:◆@DSP_NAME(0)さんは これを↓
;jpn: そうびできませんが@KEY()↓
;jpn:◆それでも かいますか?↓
@!
MSG_SUB_SHOPMES_DRUG1_10;
MSG_SUB_SHOPMES_TOYSHOP_10;
◆Please come again.

;jpn:◆またよろしくおねがいします。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_11;
MSG_SUB_SHOPMES_TOYSHOP_11;
◆Excuse me, uhhh...  you don’t seem to have enough money.

;jpn:◆しつれいですが‥‥↓
;jpn: おかねが たりないみたいですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_12;
MSG_SUB_SHOPMES_TOYSHOP_12;
◆I’m afraid you cannot carry anything else.@KEY()↓
◆Do you want to sell some things that you don’t need?↓

;jpn:◆あいにくですが↓
;jpn: それいじょう にもつを↓
;jpn: もてないようですよ。@KEY()↓
;jpn:◆いらないにもつを うりますか?↓
@!
MSG_SUB_SHOPMES_DRUG1_13;
MSG_SUB_SHOPMES_TOYSHOP_13;
◆What do you want to sell?

;jpn:◆なにを おうりになりますか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG1_14;
MSG_SUB_SHOPMES_TOYSHOP_14;
◆@DSP_GOODS(0)?↓
  I can buy it↓
  for @XCHG()$@DSP_NUM(0).@KEY()↓
◆Would you like to do that?↓

;jpn:◆@DSP_GOODS(0)ですね。↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで↓
;jpn: おひきとりしますが。@KEY()↓
;jpn:◆よろしいですか?↓
@!
MSG_SUB_SHOPMES_DRUG1_15;
MSG_SUB_SHOPMES_TOYSHOP_15;
◆Please come again.

;jpn:◆また よろしくおねがいします。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_16;
MSG_SUB_SHOPMES_TOYSHOP_16;
◆I don’t think you have any thing that you can sell.

;jpn:◆おうりになるものが↓
;jpn: ないようですよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_17;
MSG_SUB_SHOPMES_TOYSHOP_17;
◆I am sorry,but we cannot buy the @DSP_GOODS(0).
;jpn:◆あいにくですが↓
;jpn: @DSP_GOODS(0)は↓
;jpn: おひきとりできかねます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_18;
MSG_SUB_SHOPMES_TOYSHOP_18;
◆Thank you very much.

;jpn:◆ありがとうございました。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_19;
MSG_SUB_SHOPMES_TOYSHOP_19;
◆Thank you for shopping here.

;jpn:◆まいど ありがとうございます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_20;
MSG_SUB_SHOPMES_TOYSHOP_20;
◆Can I get you anything else?↓
;jpn:◆ほかに ごようはございますか?↓
@!
MSG_SUB_SHOPMES_DRUG1_21;
MSG_SUB_SHOPMES_TOYSHOP_21;
◆What would you like to get next?↓
;jpn:◆こんどの ごようは?↓
@!
MSG_SUB_SHOPMES_DRUG1_22;
MSG_SUB_SHOPMES_TOYSHOP_22;
◆It looke like @DSP_NAME(0) can’t carry any more stuff.@KEY()↓
◆Would someone else like to carry it?↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn: にもつがいっぱいみたいですよ。@KEY()↓
;jpn:◆ほかのひとが もちますか?↓
@!
;オカマ(effeminate)
MSG_SUB_SHOPMES_DRUG2_1;
◆Hi, come in, come in!
@KEY()↓
◆What can I do for you today?↓
;jpn:◆いらっしゃーい。@KEY()↓
;jpn:◆どんなごようかしら?↓
@!
MSG_SUB_SHOPMES_DRUG2_2;
◆Thanks a bunch!

;jpn:◆どうも ありがとッ!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG2_3;
◆You don’t want to buy anything from me?@KEY()↓
◆Oh, you hurt my feelings.
;jpn:◆わたしからは↓
;jpn: かいたくないのね。@KEY()↓
;jpn:◆サミシイッ!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG2_4;
◆Can I help you find something?
;jpn:◆なにを おかいもとめかしら?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG2_5;
◆@DSP_GOODS(0)?
;jpn:◆@DSP_GOODS(0)ね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_6;
◆Who’s going to carry it?
;jpn:◆どなたが おもちになるの?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG2_7;
◆Do you want to, like, ”equip” it here?↓
;jpn:◆ここで↓
;jpn: 「そうび」とか してみる?↓
@!
MSG_SUB_SHOPMES_DRUG2_8;
◆I can buy your↓
  @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0).@KEY()↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かってあげるけど?↓
@!
MSG_SUB_SHOPMES_DRUG2_9;
◆@DSP_NAME(0)  can’t equip this.@KEY()↓
◆Do you still want to buy it?↓
;jpn:◆@DSP_NAME(0)さんは
;jpn: これって↓
;jpn: そうびできないけど@KEY()↓
;jpn:◆それでも↓
;jpn: かったりするー?↓
@!
MSG_SUB_SHOPMES_DRUG2_10;
◆So, you say you don’t want it... Hmmmm...

;jpn:◆かわないわけね。↓
;jpn: フン。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_11;
◆Oh no!↓
  Don’t tell me you don’t have enough money!!

;jpn:◆うっそー!@WI(10)↓
;jpn: おかねが たりないじゃないのー!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_12;
◆Oh, my!@KEY()↓
◆I just don’t think you can carry any more than what you already have.@KEY()↓
◆But you know, I might be able to buy some of the stuff you don’t need.@KEY()↓
;jpn:◆まあ@WI(10)↓
;jpn: それいじょう にもつを↓
;jpn: もてないみたいよー。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn: かいとるけど?↓
@!
MSG_SUB_SHOPMES_DRUG2_13;
◆What do you want to sell?

;jpn:◆なにを うりたいわけー?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG2_14;
◆The @DSP_GOODS(0)?↓
  I’ll buy it for @XCHG()$@DSP_NUM(0).@KEY()↓
◆Do you wanna sell it?↓
;jpn:◆@DSP_GOODS(0)ね。↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで ひきとるわよ。@KEY()↓
;jpn:◆いいかしら?↓
@!
MSG_SUB_SHOPMES_DRUG2_15;
◆Oh, so you don’t want to do that?↓
  Well, all right.

;jpn:◆あ@WI(10) そう。↓
;jpn: やめるのね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_16;
◆Well, it looks like you don’t have anything to sell to us.
;jpn:◆だって うるものが↓
;jpn: ないじゃない。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_17;
◆Oh,no!↓
  You can’t sell that here.

;jpn:◆イヤだーッ↓
;jpn: それって うちじゃ↓
;jpn: かえないわよ‥‥。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_18;
◆Thanks a bunch!

;jpn:◆どうも ア・リ・ガ・トッ!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_19;
◆Thanks again.

;jpn:◆いつも アリガトッ!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_20;
◆Do you need anything else from me?↓
;jpn:◆ほかに↓
;jpn: なにかようかしら?↓
@!
MSG_SUB_SHOPMES_DRUG2_21;
◆What can I do for you?↓
;jpn:◆どんな ごようかしら?↓
@!
MSG_SUB_SHOPMES_DRUG2_22;
◆@DSP_NAME(0) is already carrying too much stuff.@KEY()↓
◆Does anyone else want to carry it?↓
;jpn:◆@DSP_NAME(0)ちゃんは↓
;jpn: にもついっぱいね。@KEY()↓
;jpn:◆ほかのひとが↓
;jpn: もったりなんかするぅ?↓
@!
;スポーツ若者(jock)
MSG_SUB_SHOPMES_DRUG3_1;
◆Hey dudes!  It’s summer!↓
  It’s the manly time of year!↓
  Time for sports, guys!@KEY()↓
◆What can I do you for?↓
;jpn:◆なつだ!↓
;jpn: わかものだ!↓
;jpn: スポーツだ!@KEY()↓
;jpn:◆ごようは?↓
@!
MSG_SUB_SHOPMES_DRUG3_2;
◆Hey buddy, thanks!@KEY()↓
◆See you around!

;jpn:◆どうもありがとう!↓
;jpn: また こいよ!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG3_3;
◆If you ever need anything, come back here, and I’ll set you up!

;jpn:◆ようがあったら↓
;jpn: いつでも おいで!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG3_4;
◆So what’ll it be today?

;jpn:◆なにを かうんだい?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG3_5;
◆@DSP_GOODS(0)?
;jpn:◆@DSP_GOODS(0)だね!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_6;
◆Which of you is going to carry this?
;jpn:◆だれが もつんだい?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG3_7;
◆So, man, are you gonna equip it here?↓
;jpn:◆ここで そうびしてみるかい?↓
@!
MSG_SUB_SHOPMES_DRUG3_8;
◆Can I buy your↓
  @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0)?↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルでかいあげようか?↓
@!
MSG_SUB_SHOPMES_DRUG3_9;
◆@DSP_NAME(0) can’t equip this.@KEY()↓
◆Do ya still want to buy it?↓
;jpn:◆@DSP_NAME(0)くんは↓
;@XCHG()
;jpn: @DSP_GOODS(0)を↓
;jpn: そうびできないけれど@KEY()↓
;jpn:◆それでも かうのかい?↓
@!
MSG_SUB_SHOPMES_DRUG3_10;
◆Catch ya later!

;jpn:◆また よろしく!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_11;
◆Oh, most heinous!↓
  You dudes don’t have enough money for this.

;jpn:◆だめだ!↓
;jpn: おかねがたりないようだよ!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_12;
◆Dudes!↓
  You simply have too much stuff in your kit!
@KEY()↓
◆But don’t sweat it, I can buy some stuff you don’t need.↓
;jpn:◆だめだ!↓
;jpn: もちものがいっぱいだよ!@KEY()↓
;jpn:◆いらないにもつを↓
;jpn: かってあげよう!↓
@!
MSG_SUB_SHOPMES_DRUG3_13;
◆Now, you’re sure you want to sell this to me...

;jpn:◆なにをうるんだい?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG3_14;
◆The @DSP_GOODS(0)?↓
  I’ll buy it for @XCHG()$@DSP_NUM(0).@KEY()↓
◆You positive you want to sell it?↓
;jpn:◆@DSP_GOODS(0)だねー!@KEY()↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで↓
;jpn: ひきとるよ。@KEY()↓
;jpn:◆いいかい?↓
@!
MSG_SUB_SHOPMES_DRUG3_15;
◆OK.

;jpn:◆そうかい。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_16;
◆Man, you don’t have anything to sell me!

;jpn:◆きみはうるものを↓
;jpn: もってないじゃないか!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_17;
◆Sorry dude, but I can’t buy that.

;jpn:◆わるいけど↓
;jpn: それは かえないよ!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_18;
◆Thanks!

;jpn:◆ありがとう!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_19;
◆Thanks, buddy!

;jpn:◆ありがとう!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_20;
◆Is there anything else I can do for you?↓
;jpn:◆ほかになにか↓
;jpn: ようはあるかい?↓
@!
MSG_SUB_SHOPMES_DRUG3_21;
◆What is it?↓
;jpn:◆ようはなんだい?↓
@!
MSG_SUB_SHOPMES_DRUG3_22;
◆@DSP_NAME(0) has too many things.@KEY()↓
◆Does somebody else want to carry it?↓
;jpn:◆@DSP_NAME(0)くんは↓
;jpn: にもつがいっぱいだよ!@KEY()↓
;jpn:◆ほかのひとが もつかい?↓
@!
;女子店員(sales girl)
MSG_SUB_SHOPMES_DRUG4_1;
◆Hi!@KEY()↓
◆Can I help you?↓
;jpn:◆いらっしゃーい。@KEY()↓
;jpn:◆どんなごようかしら?↓
@!
MSG_SUB_SHOPMES_DRUG4_2;
◆Thanks so much!
;jpn:◆ありがとうございましたー。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG4_3;
◆Are you here just to say ”Hi”?  What a loser!

;jpn:◆ようもないのに↓
;jpn: こえをかけたのね。@KEY()↓
;jpn:◆ひどいひと!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG4_4;
◆So, what are you going to buy?

;jpn:◆なにを かうのかしら?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG4_5;
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)ね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_6;
◆Who’s going to carry this?

;jpn:◆だれが もちますか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG4_7;
◆Would you like to equip it here?↓
;jpn:◆ここで そうびしてみる?↓
@!
MSG_SUB_SHOPMES_DRUG4_8;
◆Do you want me to buy↓
  your @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0)?@KEY()↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かいあげましょうか?↓
@!
MSG_SUB_SHOPMES_DRUG4_9;
◆Even though @DSP_NAME(0) can’t equip this, do you still want to purchase it?↓
;jpn:◆@DSP_NAME(0)くんはこれを↓
;jpn: そうびできませんが@KEY()↓
;jpn:◆それでも かいますか?↓
@!
MSG_SUB_SHOPMES_DRUG4_10;
◆Please come again.

;jpn:◆また よろしくね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_11;
◆I’m sorry, but you don’t have enough money.

;jpn:◆わるいけど↓
;jpn: おかねが たりないみたいね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_12;
◆Oh, how are you planning to carry this?  You’ve got too much stuff!@KEY()↓
◆Well, I guess I could buy the stuff you don’t need.@KEY()↓
◆Do you want to sell anything?↓
;jpn:◆あら↓
;jpn: にもつが いっぱいだわ。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn: かいとるけど いい?↓
@!
MSG_SUB_SHOPMES_DRUG4_13;
◆What can you sell me?

;jpn:◆なにを うってくれるの?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG4_14;
◆@DSP_GOODS(0)?↓
  I’ll pay @XCHG()$@DSP_NUM(0) for it.@KEY()↓
◆Is that okay?↓
;jpn:◆@DSP_GOODS(0)ね。@KEY()↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで↓
;jpn: ひきとるわ。@KEY()↓
;jpn:◆それでいい?↓
@!
MSG_SUB_SHOPMES_DRUG4_15;
◆Hummm.  Is that so?

;jpn:◆ふーん そうなの。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_16;
◆Oh, so you don’t really have anything to sell?

;jpn:◆あら あなた↓
;jpn: うるものが ないわよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_17;
◆I’m sorry,but I can’t buy that.

;jpn:◆あら わるいけど↓
;jpn: そのしなものはひきとれないわ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_18;
◆Thank you very much.

;jpn:◆ありがとうございましたー。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_19;
◆Thank you.

;jpn:◆どうもありがとう。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_20;
◆Is there anything I can do for you?↓
;jpn:◆ほかに ごようは?↓
@!
MSG_SUB_SHOPMES_DRUG4_21;
◆What can I do for you now?↓
;jpn:◆こんどのごようは?↓
@!
MSG_SUB_SHOPMES_DRUG4_22;
◆@DSP_NAME(0) can’t carry any more.@KEY()↓
◆Will another one of you take it?↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn: にもつが いっぱいね。@KEY()↓
;jpn:◆ほかのひとが もちますか?↓
@!
;グラサン(guy with sunglasses)
MSG_SUB_SHOPMES_DRUG5_1;
◆Hi!  Welcome to my store.@KEY()↓
◆What do you need?↓
;jpn:◆ハーイ イラッシャーイ@KEY()↓
;jpn:◆ようは なんだい?↓
@!
MSG_SUB_SHOPMES_DRUG5_2;
◆Thank you!

;jpn:◆どうもありがとう!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG5_3;
◆This place isn’t for looky loos.  If you’re not buying, get out!

;jpn:◆ひやかしなら↓
;jpn: とっととかえんな!
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG5_4;
◆So, you’re going to buy something, eh?

;jpn:◆なにを かうんだい?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG5_5;
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)だね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_6;
◆Who’s going to carry it?

;jpn:◆だれが もつ?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG5_7;
◆Are you going to equip it here?↓
;jpn:◆ここで そうびしてみるかい?↓
@!
MSG_SUB_SHOPMES_DRUG5_8;
◆I’ll buy↓
  your @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0).↓
;jpn:◆@DSP_GOODS(0)なら↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルでひきとるけど?↓
@!
MSG_SUB_SHOPMES_DRUG5_9;
◆Even though @DSP_NAME(0) can’t put this on, you still want to buy it?@KEY()↓
◆Well, it’s your money...↓
;jpn:◆@DSP_NAME(0)は これを↓
;jpn: そうびできないけど@KEY()↓
;jpn:◆それでも かうのかい?↓
@!
MSG_SUB_SHOPMES_DRUG5_10;
◆Hurry back now.

;jpn:◆また よろしくな。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_11;
◆Hey!  What are you trying to pull?!  You haven’t got enough money!!

;jpn:◆おい! おれをなめてんのか!↓
;jpn: かねが たりないじゃないか!
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_12;
◆Hey!  You’ve already have got enough junk!@KEY()↓
◆Do you want to sell me some of the junk you don’t need?↓
;jpn:◆おい!↓
;jpn: にもつが いっぱいだぞ!@KEY()↓
;jpn:◆いらないにもつを↓
;jpn: かいとってやろうか?↓
@!
MSG_SUB_SHOPMES_DRUG5_13;
◆What can you sell me?

;jpn:◆なにを うってくれるんだい?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG5_14;
◆@DSP_GOODS(0)?↓
  I’ll give you @XCHG()$@DSP_NUM(0).@KEY()↓
◆How would that be?↓
;jpn:◆@DSP_GOODS(0)か‥‥@KEY()↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルだな。@KEY()↓
;jpn:◆それでいいかい?↓
@!
MSG_SUB_SHOPMES_DRUG5_15;
◆Hurrm.  Changed your mind, eh?

;jpn:◆ふん そうかい。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_16;
◆C’mon!↓
  You don’t have anything to sell, do you?!
;jpn:◆なんだよ!↓
;jpn: うるものが ないじゃないか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_17;
◆Sorry, but I have no use for that.

;jpn:◆わりいな そいつは↓
;jpn: ひきとれないんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_18;
◆Hey, it was nice doing business with you.

;jpn:◆ありがとよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_19;
◆Thanks.

;jpn:◆まいどありー。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_20;
◆Will there be anything else?↓
;jpn:◆ほかに なんか よう?↓
@!
MSG_SUB_SHOPMES_DRUG5_21;
◆What else do you want?↓
;jpn:◆こんどの ようは?↓
@!
MSG_SUB_SHOPMES_DRUG5_22;
◆@DSP_NAME(0) can’t carry anymore stuff.@KEY()↓
◆Can one of you others carry it?↓
;jpn:◆@DSP_NAME(0)は↓
;jpn: にもつが いっぱいじゃないか!@KEY()↓
;jpn:◆ほかのやつが もつか?↓
@!
;海の男(man of ocean)

MSG_SUB_SHOPMES_DRUG6_1;
◆If ye be headin’ to Scaraba, ye ought to shop here.@KEY()↓
◆Things’re expensive down there...@KEY()↓
◆So, what’re ye lookin’ fer?↓
;jpn:◆スカラビにゆくんだったら↓
;jpn: かっていきなよ。 あそこは↓
;jpn: もののねだんが たかいから。@KEY()↓
;jpn:◆ようは なんだい?↓
@!
MSG_SUB_SHOPMES_DRUG6_2;
◆Thanks much.@KEY()↓
◆If’n yer going to Scaraba, take care of yerself.
;jpn:◆ありがとう。↓
;jpn: スカラビにいくんだったら↓
;jpn: きをつけてな。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG6_3;
◆Please come again!

;jpn:◆また きておくれよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG6_4;
◆What would ye like, then?
;jpn:◆なににする?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG6_5;
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)だね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_6;

◆Which of ye is goin’ to carry this?

;jpn:◆だれが もつんだい?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG6_7;
◆Would ye like to equip it here, then?↓
;jpn:◆ここでそうび↓
;jpn: してみるかい?↓
@!
MSG_SUB_SHOPMES_DRUG6_8;
◆Would ye like it if I bought yer↓
  @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0)?↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルでひきとろうか?↓
@!
MSG_SUB_SHOPMES_DRUG6_9;
◆@DSP_NAME(0) cannot equip this.@KEY()↓
◆Do ye still want to buy it?↓
;jpn:◆これは↓
;jpn: @DSP_NAME(0)くんには↓
;jpn: そうびできないけれど@KEY()↓
;jpn:◆それでも かうのかい?↓
@!
MSG_SUB_SHOPMES_DRUG6_10;
◆Yer not goin’ to buy this thing?  All righty then.

;jpn:◆そうか やめるか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_11;
◆Beggin’ yer pardon, but it appears ye don’t have enough money...

;jpn:◆おかねがたりないようだよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_12;
◆You’ve got entirely too many goodies.@KEY()↓
◆Would ye like me to take some of those things off yer hands?@KEY()↓
◆I can buy the ones ye don’t need, if ye want.↓
;jpn:◆もちものが いっぱいだな。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn: かいとってあげようか?↓
@!
MSG_SUB_SHOPMES_DRUG6_13;
◆What would ye like to sell me, then?

;jpn:◆なにを うってくれるんだい。
@KEY()
@!
MSG_SUB_SHOPMES_DRUG6_14;
◆@DSP_GOODS(0)?
  I would pay @XCHG()$@DSP_NUM(0).@KEY()↓
◆Are ye happy with my offer?↓
;jpn:◆@DSP_GOODS(0)か。↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルだな。@KEY()↓
;jpn:◆このねだんで いいかい?↓
@!
MSG_SUB_SHOPMES_DRUG6_15;
◆Oh, it’s not quite what ye expected?  Well, all righty then.

;jpn:◆そうか やめるか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_16;
◆Oh?  Well, it appears to me that ye don’t have anything to sell.

;jpn:◆おや?↓
;jpn: うるものが ないようだね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_17;
◆Beggin’ yer pardon, but I can’t buy that.

;jpn:◆それは ちょっと↓
;jpn: ひきとれないんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_18;
◆Here ye go.  Thank ye.

;jpn:◆はい ありがとう。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_19;
◆Thank ye kindly.

;jpn:◆はい まいどあり
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_20;
◆Will ye be needin’ anything else?↓
;jpn:◆ほかにようはあるかい?↓
@!
MSG_SUB_SHOPMES_DRUG6_21;
◆What do ye need now?↓
;jpn:◆こんどのごようは?↓
@!
MSG_SUB_SHOPMES_DRUG6_22;
◆It appears @DSP_NAME(0) has a full load.@KEY()↓
◆Will someone else take this instead?↓
;jpn:◆@DSP_NAME(0)くんは↓
;jpn: にもつが いっぱいだね。@KEY()↓
;jpn:◆べつのひとが もつかい?↓
@!
;ターバン(man with turban)

MSG_SUB_SHOPMES_DRUG7_1;
◆Welcome, welcome!  Ach, the heat!  Is your body okay?@KEY()↓
◆Can I interest you in some of my merchandise?↓
;jpn:◆そとは あついね。↓
;jpn: カラダ だいじょうぶ?@KEY()↓
;jpn:◆ごようは?↓
@!
MSG_SUB_SHOPMES_DRUG7_2;
◆Ohh, thank you very much.  May you never find rocks in your sandals.

;jpn:◆どうもありがとう。↓
;jpn: カラダ きをつけてね。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG7_3;
◆Why don’t you buy something?  I’ve got a family to feed!

;jpn:◆なんか かえばいいのに。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG7_4;
◆What would you like?

;jpn:◆なんにしますか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG7_5;
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)ですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_6;
◆So, which of you will take this wonderful item?

;jpn:◆だれがもちますか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG7_7;
◆Will you equip it here?↓
;jpn:◆ここでそうびしてみますか?↓
@!
MSG_SUB_SHOPMES_DRUG7_8;
◆Would you be interested in selling your @DSP_GOODS(0)@KEY()↓
◆for @XCHG()$@DSP_NUM(0)?↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで↓
;jpn: かいあげましょうか?↓
@!
MSG_SUB_SHOPMES_DRUG7_9;
◆@DSP_NAME(0) will have no use for this.@KEY()↓
◆Do you still want to buy this marvelous thing?↓
;jpn:◆@DSP_NAME(0)さんには↓
;jpn: そうびできないけれど@KEY()↓
;jpn:◆それでも かいますか?↓
@!
MSG_SUB_SHOPMES_DRUG7_10;
◆Very well then.

;jpn:◆そうですか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_11;
◆A thousand pardons, but you do not seem to have the money required to make this purchase.

;jpn:◆おかね たりないみたいですよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_12;
◆Ahh, I can see that your caravan is overloaded.@KEY()↓
◆Would you like to sell some of your extra items to me?↓
;jpn:◆もちものが いっぱいですね。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn: かいとりましょうか?↓
@!
MSG_SUB_SHOPMES_DRUG7_13;
◆Very well then, what would you like to sell?

;jpn:◆なにを うってくれますか?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG7_14;
◆@DSP_GOODS(0)?↓
  Ahhh, I would pay you...↓
  @XCHG()$@DSP_NUM(0) for that.@KEY()↓
◆A trifle, I realize, but do you accept?↓
;jpn:◆@DSP_GOODS(0)ですね。↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで↓
;jpn: おひきとりしますが。@KEY()↓
;jpn:◆それでいいですか?↓
@!
MSG_SUB_SHOPMES_DRUG7_15;
◆Very well then.

;jpn:◆わかりました。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_16;
◆From my humble vantage point, it appears you have nothing to sell.

;jpn:◆うるものがないようですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_17;
◆A thousand pardons.  We do not carry that item here.

;jpn:◆すいません。↓
;jpn: そのしなものは↓
;jpn: あつかって ないんですよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_18;
◆Ahh, you are most gracious and kind.

;jpn:◆ありがとうございます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_19;
◆Thank you for visiting my poor shop.

;jpn:◆まいどありがとうございます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_20;
◆If there is anything else I can do for you,
please, do not hesitate to ask.↓
;jpn:◆ほかに ごようは?↓
@!
MSG_SUB_SHOPMES_DRUG7_21;
◆So, what more can I do for you?↓
;jpn:◆こんどのごようは?↓
@!
MSG_SUB_SHOPMES_DRUG7_22;
◆@DSP_NAME(0) simply cannot carry any more goods.@KEY()↓
◆Perhaps another of your party could bear this load?↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn: にもつが いっぱいですね。@KEY()↓
;jpn:◆ほかのひとが もちますか?↓
@!
;ブタのハナ売り(pig−kansaiben)

MSG_SUB_SHOPMES_DRUG8_1;

;◆めずらしいもの↓
; いろいろありまっせ。@KEY()↓

◆If you’ve already got what you need, great!@KEY()↓
◆But if you don’t, well, that would be a real shame.@KEY()↓
◆Take a good look at my menu and decide.@KEY()↓
◆Is there anything listed that you might want?↓
;jpn:◆あったらべんり↓
;jpn: なければ たいへん!↓
;jpn: メニューみて きめなはれ。@KEY()↓
;jpn:◆ごようは なんでっしゃろ?↓
@!
MSG_SUB_SHOPMES_DRUG8_2;
◆If you do decide that you need any of my goodies, you just hurry on back now, y’hear?

;jpn:◆ようができたら↓
;jpn: また きなはれ。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG8_3;
◆Come back any time, if do need any of my goods.

;jpn:◆ようができたら↓
;jpn: また きなはれ。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG8_4;
◆What’ll it be?

;jpn:◆なにが ええの?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_5;
◆The @DSP_GOODS(0), you say?

;jpn:◆@DSP_GOODS(0)ですな。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_6;
◆Who’s going to carry this?

;jpn:◆だれがもつの?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_7;
◆Will you be equipping that here?↓
;jpn:◆ここで そうびしはる?↓
@!
MSG_SUB_SHOPMES_DRUG8_8;
◆I can buy your↓
  @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0).@KEY()↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルでかいあげましょか?↓
@!
MSG_SUB_SHOPMES_DRUG8_9;
◆@DSP_NAME(0) won’t be able to equip this.@KEY()↓
◆Are you sure you really need it?↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn: これをそうびでけへんけど@KEY()↓
;jpn:◆それでも かいますか?↓
@!
MSG_SUB_SHOPMES_DRUG8_10;
◆Oh?  Decided you don’t want to buy it, huh?

;jpn:◆あら@WI(10)↓
;jpn: かわへんの?
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_11;
◆Hmmm... Hate to break this to you, but you don’t have enough money.

;jpn:◆あら@WI(10)↓
;jpn: ゼニがたらんようですな。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_12;
◆Oh... uh... it looks like you’ve got too many goods to carry.@KEY()↓
◆Would you be willing to sell me some of the goods you don’t need?↓
;jpn:◆あら@WI(10)↓
;jpn: にもつがいっぱいですな。@KEY()↓
;jpn:◆いらんにもつを↓
;jpn: かいとりましょか?↓
@!
MSG_SUB_SHOPMES_DRUG8_13;
◆Fantastic!  What do you wanna sell?

;jpn:◆なにをうるの?
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_14;
◆@DSP_GOODS(0)?↓
  I’d say it’s worth about...↓
  @XCHG()$@DSP_NUM(0).@KEY()↓
◆Whaddya say, partner?↓
;jpn:◆@DSP_GOODS(0)でっか↓
;@XCHG()
;jpn: それなら@DSP_NUM(0)ドルで↓
;jpn: おひきとりしまっせ。@KEY()↓
;jpn:◆よろしゅうおまっか?↓
@!
MSG_SUB_SHOPMES_DRUG8_15;
◆OK, I see.  Y’all come back now, hear?

;jpn:◆そうでっか↓
;jpn: また よろしゅう。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_16;
◆What gives?  You don’t have anything to sell.

;jpn:◆なんや@WI(10) うるものが↓
;jpn: おまへんがな。
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_17;
◆Look, I’m really sorry, but we can’t buy that.

;jpn:◆すいません おきゃくさん↓
;jpn: かんべんしてください。@KEY()↓
;jpn:◆それは うちでは↓
;jpn: ひきとれまへんのや。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_18;
◆Thanks a million!

;jpn:◆まいど おおきに。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_19;
◆Thanks a bunch!

;jpn:◆まいど おおきに。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_20;
◆Is there anything else I can get for you while you’re here?↓
;jpn:◆ほかにも ごようは↓
;jpn: ありまっか?↓
@!
MSG_SUB_SHOPMES_DRUG8_21;
◆What’ll it be?↓
;jpn:◆ごようは なんでっしゃろ?↓
@!
MSG_SUB_SHOPMES_DRUG8_22;
◆Sakes alive! @DSP_NAME(0) can’t carry another thing.@KEY()↓
◆Maybe someone else can carry it.↓
;jpn:◆あらま↓
;jpn: @DSP_NAME(0)さん↓
;jpn: にもつが いっぱいやね。@KEY()↓
;jpn:◆ほかのひとに↓
;jpn: もってもらったら?↓
@!
;おもちゃ屋(toy store)

MSG_SUB_SHOPMES_TOYSHOP_3;
◆Please come again.

;jpn:◆またよろしくね。
@KEYNP()
@!
;武器男(weapon seller)
MSG_SUB_SHOPMES_WEAPON_1;
◆Sssshhh!↓
  Don’t raise your voice with me!@KEY()↓

;jpn:◆しーっ!@WI(60)↓
;jpn: おおきなこえをだすな!@KEY()↓
;@CHKFGOTO(FLG_??,_SHOPMES_WEAPON_1_B)
◆What do you want?↓
;jpn:◆なんのようだ?↓
@!
_SHOPMES_WEAPON_1_B;
◆...you again?!↓
  What do you want now?↓
;jpn:◆‥‥またあんたか。@WI(20)↓
;jpn: なんのようだ?↓
@!
MSG_SUB_SHOPMES_WEAPON_2;
◆Will that be all?↓
  Good luck, buddy!

;jpn:◆じゃあな。@WI(20)↓
;jpn: しっかりやれよ あいぼう!
@KEYNP()
@!
MSG_SUB_SHOPMES_WEAPON_3;
◆So that’s everything?↓
  Keep on the watch for bad guys.

;jpn:◆じゃあな。@WI(20)↓
;jpn: わるいやつに きをつけろよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_WEAPON_4;
◆I’ve got what you need.

;jpn:◆なんでも そろってるぜ。
@KEY()
@!
MSG_SUB_SHOPMES_WEAPON_5;
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)だな。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_6;
◆Who’s gonna lug this around?

;jpn:◆だれが はこぶ?
@KEY()
@!
MSG_SUB_SHOPMES_WEAPON_7;
◆OK.  I suppose you’re going to want to equip it here?↓
;jpn:◆オーケイ@WI(20)↓
;jpn: ここで そうびしてみるかい?↓
@!
MSG_SUB_SHOPMES_WEAPON_8;
◆The @DSP_GOODS(0)....?↓
  I’d say about @XCHG()$@DSP_NUM(0).↓
  Take it or leave it.@KEY()↓
;jpn:◆@DSP_GOODS(0)か‥‥↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで いいか?↓
@!
MSG_SUB_SHOPMES_WEAPON_9;
◆@DSP_NAME(0) won’t be able to equip this.@KEY()↓
◆Are you intent on purchasing it anyway?↓
;jpn:◆@DSP_NAME(0)には これは↓
;jpn: そうびできないぜ。@KEY()↓
;jpn:◆それでもいいかい?↓
@!
MSG_SUB_SHOPMES_WEAPON_10;
◆Well, that’s showing good sense.  You shouldn’t strain yourself too much.

;jpn:◆そうだな。@WI(20)↓
;jpn: むりは きんもつだよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_11;
◆Hold it just a second!  You haven’t got enough money!

;jpn:◆ちょっとまった@WI(20)↓
;jpn: かねが たりないぜ!
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_12;
◆You aren’t going to be able to carry any more stuff.@KEY()↓
◆You’re dragging around all that junk...@KEY()↓
◆I guess I could help you out by buying some things that you don’t need...@KEY()↓
;jpn:◆おっと↓
;jpn: それいじょうは ヤバイぜ。@WI(15)↓
;jpn: にもつが いっぱいだ。@KEY()↓
;jpn:◆いらないにもつが あるなら↓
;jpn: ひきとってやるぜ。↓
@!
MSG_SUB_SHOPMES_WEAPON_13;
◆What are you going to pawn off on me?

;jpn:◆ブツは なんだい?
@KEY()
@!
MSG_SUB_SHOPMES_WEAPON_14;
◆@DSP_GOODS(0)?↓
  I’ll give you @XCHG()$@DSP_NUM(0), and not a penny more.@KEY()↓
◆Take it or leave it.↓
;jpn:◆@DSP_GOODS(0)か。@WI(20)↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルで ひきとろう。@KEY()↓
;jpn:◆それでいいか?↓
@!
MSG_SUB_SHOPMES_WEAPON_15;
◆...I don’t think you’ll find a better price anywhere else.

;jpn:◆‥‥こうかいするぜ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_16;
◆What are you trying to pull, anyway?@KEY()↓
◆You say you want to sell, but you have nothing to offer?!@KEY()↓
◆You’ve got some nerve, kid!

;jpn:◆ブツもなしに↓
;jpn: カネだけ↓
;jpn: ほしいっていうのか?@KEY()↓
;jpn:◆たいした どきょうだな。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_17;
◆Forget it!↓
  I don’t want to buy that junk!

;jpn:◆おっと@WI(15) そんなヤバイ↓
;jpn: とりひきは ごめんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_18;
◆Excellent.↓
  Glad we could work something out.

;jpn:◆ありがとよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_19;
◆Thank you.@WI(20)  Things must be pretty tough, especially for a kid like you.
;jpn:◆ありがとよ。@WI(20)↓
;jpn: こどもなのに たいへんだな。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_20;
◆So, will there be anything else?↓
;jpn:◆まだ ようじはあるか?↓
@!
MSG_SUB_SHOPMES_WEAPON_21;
◆What is it now?↓
;jpn:◆なんのようだ?↓
@!
MSG_SUB_SHOPMES_WEAPON_22;
◆@DSP_NAME(0)  can’t carry any more.@KEY()↓
◆Is anyone else willing to carry it?↓
;jpn:◆@DSP_NAME(0)は↓
;jpn: にもつがいっぱいだぜ。@KEY()↓
;jpn:◆ほかのやつが もつか?↓
@!
;土星さん(Saturn−san)

MSG_SUB_SHOPMES_DOSEI_1;
@FONTBAKA()
;akimiura
◆Hi Hi Hi.↓
  You come↓
  buying?@KEY()↓
◆You can sell,↓
  too.@KEY()↓
◆I, Mr. Saturn, boing@KEY()↓
◆can do all for you.@KEY()↓
◆What do you↓
  want zoom?↓
;jpn:◆できるます。@WI(10)↓
;jpn: うったり かったり↓
;jpn: どせいさんです。@KEY()↓
;jpn:◆どんな よう?↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_2;
@FONTBAKA()
◆Oh,↓
  you thank!

;jpn:◆ありがと。
@KEYNP()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_3;
@FONTBAKA()
◆Thank you.↓
  Boing!

;jpn:◆ありがと。@WI(10)↓
;jpn: ぷうー
@KEYNP()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_4;
@FONTBAKA()
;akimiura
◆What you↓
  buying zoom?

;jpn:◆なにを かう?
@KEY()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_5;
@FONTBAKA()
◆The @DSP_GOODS(0)?

;◆@DSP_GOODS(0)↓
;jpn: ですね。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_6;
@FONTBAKA()
;akimiura
◆Which↓
  you carry↓
  this burden?

;jpn:◆だれが もつ?
@KEY()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_7;
@FONTBAKA()
◆Equip↓
  here?↓
;jpn:◆ここで↓
;jpn: そうび する?↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_8;
@FONTBAKA()
;akimiura
◆@DSP_GOODS(0)?@KEY()↓
◆Uhh,↓
  that one is↓
  @XCHG()$@DSP_NUM(0).@KEY()↓
◆What think you about@KEY()↓
◆that price...zoom?↓
;◆@DSP_GOODS(0)↓
;@XCHG()
;jpn: なら @DSP_NUM(0) ドル@KEY()↓	;どせいさん数字
;jpn:◆このきんがくで‥‥↓
;jpn: いいのかな?↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_9;
@FONTBAKA()
;akimiura
◆@DSP_NAME(0) is not be able to equip this.@KEY()↓
◆Boing!@KEY()↓
◆Still wanna↓
  buy?↓
;jpn:◆@DSP_NAME(0)には↓
;jpn: そうびできない。@KEY()↓
;jpn:◆それでもかう?↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_10;
@FONTBAKA()
;akimiura
◆If you not↓
  gonna buy,@KEY()↓
◆don’t↓
  buy zoom!

;jpn:◆やめたいとき↓
;jpn: やめるといい。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_11;
@FONTBAKA()
◆Uhh,@KEY()↓
◆at a looking boing glance,↓
  no chance.@KEY()↓
◆No↓
  enough@KEY()↓
◆cashoooooola.↓
Zoicks!

;jpn:◆ぜんたいてきに↓
;jpn: おかねが↓
;jpn: たりない。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_12;松(このあとに「いらない荷物を買い取ろうか?」といれてほしい
@FONTBAKA()
;akimiura
◆What a happy happy@KEY↓
◆surprise.↓
  Zoom...@KEY()↓
◆You have↓
  much↓
  junk.
;jpn:◆はあ びっくり@WI(10)↓
;jpn: にもつがいっぱいです。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_13;
@FONTBAKA()
◆You want to↓
  sell me↓
  things@KEY()↓
◆at me boing?

;jpn:◆なにを うる?
@KEY()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_14;
@FONTBAKA()
◆@DSP_GOODS(0)?@KEY()↓

;◆@DSP_GOODS(0)↓
;jpn: ですね。@KEY()↓
;@XCHG()
;akimiura
◆The most↓
  us pay that↓
  is @XCHG()$@DSP_NUM(0).@KEY()↓
◆That kay−o↓
  on you?@KEY()↓
◆Ding! Ding!↓

;jpn:◆@DSP_NUM(0) ドルで↓			;どせいさん数字
;jpn: ひきとる。@KEY()↓
;jpn:◆それで いいかな?↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_15;
@FONTBAKA()
◆Oh Joy! Zooooom!

;jpn:◆ありがと。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_16;
@FONTBAKA()
;akimiura
◆Ah−choo!  Hi Hi Hi!@KEY()↓
◆try of↓
  tricking boing?@KEY()↓
◆’Cause you↓
  have no↓
  anything@KEY()↓
◆ selling.  Ding Ding!
;jpn:◆ヘックション!@WI(10)↓
;jpn: うるもの↓
;jpn: ないみたいです。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_17;
@FONTBAKA()
◆Dear, dear, dear...Boing!@KEY()↓
◆No can↓
  buy that.
;jpn:◆ごめんなさい。@KEY()↓
;jpn:◆それは うちでは↓
;jpn: ひきとれないです。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_18;
@FONTBAKA()
◆Oh,↓
  you thank.

;jpn:◆ありがと。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_19;
@FONTBAKA()
◆Thanks!  Ding Zoom!
;jpn:◆ありがと。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_20;
@FONTBAKA()
;akimiura
◆Is there
  anything
  Zoom@KEY()↓
◆else need?@KEY()
;jpn:◆ほかに なにか↓
;jpn: ようありますか?
↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_21;
@FONTBAKA()
◆What next, Boing?

;jpn:◆こんどのようは?
↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_22;
@FONTBAKA()
;akimiura
◆@DSP_NAME(0) has↓
  kookie much↓
  junk?@KEY()↓
◆Does anyone↓
  want help↓
  Zoom?@KEY()
;jpn:◆@DSP_NAME(0)さんは↓
;jpn: にもつ もちすぎ。@KEY()↓
;jpn:◆ほかのひとが↓
;jpn: もちますか?
↓
@FONTSTD()
@!
;グミ族(Gumi tribe)

MSG_SUB_SHOPMES_GUMI_1;
;akimiua
◆Let’s play store.  My friend Ay−go loves this game.  So...@KEY()↓
◆Hi!  May I help you?
;jpn:◆ともだちの エーゴに↓
;jpn: たのまれて↓
;jpn: おみせやさんゴッコをしてるだよ。@KEY()↓
;jpn:◆いらっしゃいませ。↓
;jpn: ごようは?
↓
@!
MSG_SUB_SHOPMES_GUMI_2;
;◆あんたから もらった↓
; えはがき みてぇなもの↓
; (おさつのことらしい)は@KEY()↓
;◆エーゴに わたしとくだよ。@KEY()↓

◆Bye bye!↓
  Let’s play again some time!

;jpn:◆じゃーな。@WI(20)↓
;jpn: また あそぼうぜ。
@KEYNP()
@!
MSG_SUB_SHOPMES_GUMI_3;
◆Bye bye!↓
  Let’s play again some time!

;jpn:◆じゃーな。@WI(10)↓
;jpn: またあそぼうぜ。
@KEYNP()
@!
MSG_SUB_SHOPMES_GUMI_4;
◆Are you looking for anything in particular?

;jpn:◆なにを かうだね?
@KEY()
@!
MSG_SUB_SHOPMES_GUMI_5;
◆@DSP_GOODS(0)?

;jpn:◆@DSP_GOODS(0)だな。
@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_6;
◆Who is going to carry this?

;jpn:◆だれが もちますか?
@KEY()
@!
MSG_SUB_SHOPMES_GUMI_7
◆Do you want to try equipping it here?

;jpn:◆ここでそうびしてみっか?
↓
@!
MSG_SUB_SHOPMES_GUMI_8;
◆Do you want me to buy
  your @DSP_GOODS(0)↓
  for @XCHG()$@DSP_NUM(0)?↓

;jpn:◆@DSP_GOODS(0)を↓			;7/26に修正
;@XCHG()
;jpn: @DSP_NUM(0)ドルでかったろうか?
↓
@!
MSG_SUB_SHOPMES_GUMI_9;
◆Did you realize that @DSP_NAME(0) can’t equip this?@KEY()↓
◆Do you still want to purchase it?

;jpn:◆@DSP_NAME(0)には↓
;jpn: そうびできないものだが@KEY()↓
;jpn:◆それでもかうか?
↓
@!
MSG_SUB_SHOPMES_GUMI_10;
◆Well, the customer is always right.

;jpn:◆そうかい。
@KEY()↓
@!
;※
MSG_SUB_SHOPMES_GUMI_11;@
◆(Sir/Ma’am), it appears you do not have the money necessary for this transaction.@KEY()↓
;jpn:◆おかね たりないだよ。@KEY()↓
;◆えはがきみてぇなの↓
; (おさつのことらしい)が↓
; たりねぇと@KEY()↓
;◆エーゴに おこられちまうだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_12;松
◆I really don’t think you can carry any more purchases.@KEY()↓
◆You can come again after you sell something,@KEY()↓
◆or you can simply discard an item to lighten your load.@KEY()↓
◆Or, you might want to sell the things you don’t need here!@KEY()↓

;jpn:◆にもつ もちすぎだーよ。↓
;jpn: うるか すてるかして↓
;jpn: また きてな。@KEY()↓
;jpn:◆それとも ここで↓
;jpn: いらない にもつを@KEY()↓
;jpn:◆うっちまうかね?↓
;◆にもつが いっぺぇで↓
; わたせねぇだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_13;
◆What would you like to sell?@KEY()

;jpn:◆なにを↓
;jpn: うってくれるんだい?@KEY()
@!
MSG_SUB_SHOPMES_GUMI_14;
◆@DSP_GOODS(0)?↓
  I’m authorized to pay up to @XCHG()$@DSP_NUM(0) for that.@KEY()↓
◆How about it?↓

;jpn:◆@DSP_GOODS(0)だな。↓
;@XCHG()
;jpn: @DSP_NUM(0)ドルでどうだね?↓
@!
MSG_SUB_SHOPMES_GUMI_15;
◆That’s fine.  It’s the customer’s prerogative to change his or her mind.
@KEY()↓
;jpn:◆そうかい。やめるかい。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_16;
◆Though I really would like to buy something from you, you have nothing to offer.@KEY()↓

;jpn:◆うるもの↓
;jpn: もっとらんようだね。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_17;
◆Sorry, I’m not authorized to buy that.@KEY()↓

;jpn:◆わりいね。↓
;jpn: それは ひきとれないんだーよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_18;@三浦
◆Thank you very much, sir.@KEY()↓

;jpn:◆ありがとな。@KEY()↓
;◆あんたらからもらった↓
; えはがきみたいなもの↓
; (おさつのことらしい)は@KEY()↓
;◆エーゴにわたしとくだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_19;
◆I’ll give Ay−go these colorful papers you gave me.@KEY()↓

;jpn:◆あんたらからもらった↓
;jpn: えはがきみたいなもの↓
;jpn: (おさつのことらしい)は@KEY()↓
;jpn:◆エーゴにわたしとくだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_20;
◆Will there be anything else today?↓

;jpn:◆ほかにも↓
;jpn: なんかようはあるかい?↓
@!
MSG_SUB_SHOPMES_GUMI_21;
◆What are you going to do now?↓

;jpn:◆どうするだね?↓
@!
MSG_SUB_SHOPMES_GUMI_22;
◆It looks like @DSP_NAME(0) is overloaded with items.@KEY()↓
◆You want to have one of your friends carry it?↓
;jpn:◆@DSP_NAME(0)は↓
;jpn: にもつもちすぎだーよ。@KEY()↓
;jpn:◆ほかのともだちが↓
;jpn: もつようにするかね?↓
@!
