;-------------------------------------------------
;"E_system.msg"
;
;■ Text for "Earth Bound".
;■ "@"箇所は未完成。要チェック
;■ "*"は"◆"に変換予定
;-------------------------------------------------

MSG_SYS_HANASU_NG;
@CHKFGOTO(FLG_HAPPY_SYSMSGCHG,MSG_WINS_CAPSULE_NO_RESPONSE)
◆Who are you talking to?
;◆だれに はなしているのだ。
@KEYNP()
@!


MSG_SYS_NOPROBLEM;
@CHKFGOTO(FLG_GUMI_9_BOOK,MSG_ADD_SKIP)	;432
◆No problem here.
;◆もんだいなし。
@KEYNP()
@!

;MSG_SYS_CARRY;@
@GET_PLAYER_GOODS(0,0)
@SAVE_REG()
@GOSUB(MSG_SUB_Q_DEAD_GOODS)
;@TRUE_GOTO(_SYS_CARRY_DEAD)
@LOAD_REG()
@XCHG()
;#;*(no verb. cannot translate.yuka)
;#◆@DSP_NAME(0)は↓
;#@XCHG()
;# @DSP_GOODS(0)を↓
;◆@DSP_NAME(0) gave the @XCHG()@DSP_GOODS(0) to (name)
@!

;_SYS_CARRY_DEAD;@
@LOAD_REG()
@XCHG()
;#◆@DSP_LCNAME() neatly arranged @DSP_NAME(0)'s @DSP_GOODS(0).
;#◆@DSP_LCNAME()は @DSP_NAME(0)の↓
;#@XCHG()
;# @DSP_GOODS(0)を↓
;松◆@DSP_LCNAME() took the @XCHG()@DSP_GOODS(0) from @DSP_NAME(0)’S stuff.  
@!

;MSG_SYS_CARRY_SELF;@
;#  きれいに せいとんした。
himself.
;松rearrange own items
;(Name) rearranged (his/her) own items and the (goods) moved.
;rearrange dead person's items
;(Name) rearranged (Name)'s items and the (goods) moved.
@KEYNP()
@!

;MSG_SYS_CARRY_OTHER;@
@SAVE_REG()
@GOSUB(MSG_SUB_Q_DEAD_GOODS)
@TRUE_GOTO(_SYS_CARRY_OTHER_DEAD)
@LOAD_REG()
@XCHG()
@DSP_NAME(0).@KEY()

; handed to @DSP_NAME(0).@KEY()
;# @DSP_NAME(0)にわたした。@KEY()
@!
_SYS_CARRY_OTHER_DEAD;@
@LOAD_REG()
@XCHG()
@DSP_NAME(0)’s belongings.

; added to @DSP_NAME(0)’s belongings.
;# @DSP_NAME(0)の もちものにくわえた。
@KEY()
@!

;MSG_SYS_CARRY_OTHER_NG;@
@XCHG()
@DSP_NAME(0) ・・・failed.
@KEY()
; tried to give it to @DSP_NAME(0),
;# わたそうとしたが
;@KEY()↓
;松*(name) tried to give the (goods) to (name).
;◆But (he/she) was already carrying too much stuff.
;◆@DSP_NAME(0)は↓
; もちものが いっぱいだった。
@KEYNP()
@!

MSG_SYS_GOODS_DROP;
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_FOOD_BUBBLE_GUM)
@TRUE_GOTO(_DROP_NG_GUM)
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@FALSE_GOTO(_GOODS_DROP_NG)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@SAVE_REG()
@GOSUB(MSG_SUB_Q_DEAD_GOODS)
@TRUE_GOTO(_SYS_GOODS_DROP_DEAD)
@LOAD_REG()
@XCHG()
◆@DSP_NAME(0) got rid of↓
  the @XCHG()@DSP_GOODS(0).
;◆@DSP_NAME(0)は↓
;@XCHG()
; @DSP_GOODS(0)を↓
; すててしまった。
@KEYNP()
@!

_GOODS_DROP_NG;
◆You shouldn’t throw the @DSP_GOODS(0) away.
;◆@DSP_GOODS(0)は↓
; すててはいけない。
@KEYNP()
@!

_DROP_NG_GUM;
◆Don’t spit your gum out. @KEY()↓
◆Even if it has lost its flavor...@KEYNP()
;◆ガムを↓
; すててはいけません。@KEY()↓
;◆ベタベタするから↓
; というだけでなく‥‥。@KEYNP()
』

_SYS_GOODS_DROP_DEAD;
@LOAD_REG()
@XCHG()
◆@GOSUB(MSG_ESUB_DSP_PARTY_SREG) got rid of @DSP_NAME(0)’s @XCHG()@DSP_GOODS(0).
;◆@DSP_LCNAME() threw @DSP_NAME(0)’s @XCHG()@DSP_GOODS(0) away.
;◆@DSP_LCNAME()は @DSP_NAME(0)の↓
;@XCHG()
; @DSP_GOODS(0)を↓
; すてた。
@KEYNP()
@!

MSG_SYS_GOODS_USE_NG;
@GET_CITEM()
@XCHG()
◆You can’t use↓
  the @DSP_GOODS(0).
;◆@DSP_GOODS(0)は↓
; つかえない。
@KEYNP()
@!

MSG_SYS_GOODS_NOCARRY;
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) is the only one who should carry↓
  the @XCHG()@DSP_GOODS(0).
;◆@DSP_GOODS(0)は↓
;@XCHG()
; @DSP_NAME(0)じしんが↓
; もっていてください。
@KEYNP()
』

MSG_SYS_GOODS_USE_NG_HERE;
@GET_CITEM()
@XCHG()
◆The @DSP_GOODS(0) can’t be used here.
;◆@DSP_GOODS(0)は↓
; ここでは つかえない。
@KEYNP()
@!


MSG_SYS_GOODS_EAT_NG;
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_FOOD_BUBBLE_GUM)
@TRUE_GOTO(_GOODS_EAT_GUM)
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
◆Why would you do that?↓
  The @DSP_GOODS(0) would probably make you barf.
;◆やめてください。
@KEYNP()
@!


MSG_SYS_GOODS_EQUIP;
@GET_PLAYER_GOODS(0,0)
◆The @DSP_GOODS(0) is one of the items that can be equipped.
@KEYNP()
;◆@DSP_GOODS(0)は↓
; 「そうび」するグッズです。@KEY()
@!

_GOODS_EAT_GUM;
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) chewed↓
  the @XCHG()@DSP_GOODS(0).
;◆@DSP_NAME(0)は↓
;@XCHG()
; @DSP_GOODS(0)を↓
; かんだ。
@KEYNP()
@!


MSG_SYS_HAVE_SUNSTROKE;
◆@DSP_NAME(0) got sunstroke.
;◆@DSP_NAME(0)は にっしゃびょうに↓
; かかってしまった。
@KEYNP()
@!

MSG_SYS_DEAD_POISON;
◆@DSP_NAME(0) was horribly poisoned and collapsed.
;◆@DSP_NAME(0)は↓
; ぜんしんに どくがまわって↓
; たおれてしまった‥‥
@KEYNP()
_DEAD_POISON_END;
@!

MSG_SYS_MAP_CRITICAL_SITUATION;
◆Alert!@KEY()↓
◆@DSP_ACTOR()’s condition is critical.@KEY()↓
;@
◆@GOSUB(MSG_ESUB_HE_SHE_GACT) will collapse if (his・her) condition isn’t treated.@KEY()↓
◆Be careful!
;◆CAUTION(ごちゅうい)!@KEY()↓
;◆@DSP_ACTOR()の↓
; たいりょくが よわってます。@KEY()↓
;◆このままだと↓
; たおれてしまいます。@WI(20)きをつけて。
@KEYNP()
』
;◆@DSP_ACTOR()は↓
; ききてきじょうたいに↓
; おちいった。


MSG_SYS_BICYCLE_TOO_MANY;
◆There is only one seat,@WI(15) so you can’t ride the bike now.
;◆Two people riding on one bike is prohibited.
;◆じてんしゃの ふたりのりは↓
; きんじられています。
@KEYNP()
@!


MSG_SYS_BICYCLE_NOT_HERE;
◆You cannot ride your bike here.
;◆ここで じてんしゃにのっては↓
; いけません。
@KEYNP()
@!

MSG_SYS_BICYCLE_ATARI_HERE;6/20
◆You should ride your bike in a less crowded area.
;◆じてんしゃは もうすこし↓
; ひろいところで のってください。
@KEYNP()
』
;◆ここは じてんしゃにのるには↓
; ちょっと せまいですね。

MSG_SYS_TLPT_NG;
@CHKFGOTO(FLG_SYS_DISTLPT,_SYS_TLPT_NG_TMP)
◆You cannot teleport here.
;◆ここでは↓
; テレポーテーションできない。
@KEYNP()
』
_SYS_TLPT_NG_TMP;
@CHKFGOTO(FLG_DUNGEONMAN,_SYS_TLPT_NG_DMAN)
@CHKFGOTO(FLG_DELIVERY_PIZZA,_SYS_TLPT_NG_PIZZA)
@CHKFGOTO(FLG_DELIVERY_UNSOU,_SYS_TLPT_NG_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_B,_SYS_TLPT_NG_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER,_SYS_TLPT_NG_KANBAN)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER_B,_SYS_TLPT_NG_KANBAN)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER_C,_SYS_TLPT_NG_KANBAN)
@CHKFGOTO(FLG_DELIVERY_CUSTOMER_D,_SYS_TLPT_NG_KANBAN)
@CHKFGOTO(FLG_DELIVERY_HOIHOI,_SYS_TLPT_NG_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_TAKOKESHI,_SYS_TLPT_NG_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_TAKANOME,_SYS_TLPT_NG_DELIVERY)
◆You cannot teleport now.
;◆いまは↓
; テレポーテーションできない。
@KEYNP()
』
_SYS_TLPT_NG_PIZZA;
◆You should wait to teleport until after the pizza arrives?
;◆ピザやがくるまで テレポーテーションは↓
; まつべきではないだろうか。
@KEYNP()
』
_SYS_TLPT_NG_KANBAN;
◆You should wait to teleport until after a customer has shown up.
;◆どうぐの かいてがくるまで↓
; テレポーテーションは まちなさい。
@KEYNP()
』
_SYS_TLPT_NG_DELIVERY;
◆You should wait to teleport until after Escargo Express arrives.
;◆エスカルゴうんそうがくるまで↓
; テレポーテーションは まっていてください。
@KEYNP()
』
_SYS_TLPT_NG_DMAN;
◆You cannot teleport while Dungeon Man is with you.
;◆ダンジョンおとこと いっしょには↓
; テレポーテーションできない。
@KEYNP()
』

MSG_SYS_BICYCLE_OFF;
@GET_ORDER_PLAYER(1)
@XCHG()
◆@DSP_NAME(0) got off the bike.
;◆@DSP_NAME(0)は↓
; じてんしゃから おりた。
@KEYNP()
@!
;------------------------------

MSG_SYS_SRAM_CRASH;
←
◆We’re very sorry...@KEY()↓
◆but the record of adventure number @DSP_CNUM() has been lost...
;◆どうしたことか?!@KEY()↓
;◆まことに おきのどくですが↓
; @DSP_CNUM()ばんの ぼうけんのきろくは↓
; きえてしまいました‥‥。
@KEYNP()
@!

;MSG_SYS_YET;
;◆(メッセージ せいさくちゅう。↓
;           エイプ)@KEYNP()
;@!
;--------------------------------------------

;^^^^^^^^電話:ストイッククラブ^^^^^^^^

MSG_SYS_PHONE_STOIC;
@CHKFGOTO(FLG_WIN_GIEGU,_SYS_PHONE_STOIC_END)
@GET_ORDER_PLAYER(1)
@XCHG()
◆Hello,@WI(15) this is the Stoic Club.@KEY()↓
◆Oh,@WI(15) @DSP_NAME(0), @XCHG()@GOSUB(MSG_ESUB_SIR_MAAM)!@WI(20)↓
  Would you like to make a reservation? @KEY()↓
◆Certainly.@KEY()↓
◆We are looking forward to having you here.@WI(15)  Thank you.@KEY()↓
◆Click!  Beep−beep−beep... @KEYNP()
;◆ハイ。@WI(15)こちらは↓
; ストイッククラブでございます。@KEY()↓
;◆@DSP_NAME(0)さま‥‥@WI(15)↓
; ごよやくですね。@KEY()↓
;◆かしこまりました。↓
; どうぞ いらしてくださいませ。@WI(20)↓
; ガチャン ツーツーツー@KEYNP()
@SE(SE_se0b_tel_put)
@SETF(FLG_SUMS_STOIC_RESERVED)
』
_SYS_PHONE_STOIC_END;
◆Yo, this is the ”The Lazy Cowpoke Stop’n Go”@KEY()↓
◆Yeah, we’re a new truck stop...we just opened...@KEY()↓
◆What’s that?  The Stoic Club?!  That lame old place shut down ages ago!@KEY()↓
◆We totally remodeled the place!@KEY()↓
◆Now we’ve got loud music, great food, and really rowdy crowds...@KEY()↓
◆Listen, buddy, I’m too busy to talk to you right now! @KEY()↓
◆Just drop by anytime!  You come, you enjoy...  I promise! @KEY()↓
  Click!  Beep−beep−beep...@KEYNP()
;◆へい まいどあり!@KEY()↓
;◆たいしゅう さかば↓
; 「どアホいちだい」でーす!@KEY()↓
;◆なにー@WI(15) ストイッククラブ?@WI(20)↓
; あんなげんきのねぇ みせは↓
; とっくに やめちまったよ。@KEY()↓
;◆いまは↓
; 「やすい・うまい・うるさい」の@KEY()↓
;◆‥‥たいしゅうさかばを↓
; やってるんだ。@KEY()↓
;◆ながでんわなんか↓
; してらんねぇんだー。↓
; へい@WI(10) らっしゃい!@KEY()↓
;◆ガチャン ツーツーツー@KEYNP()
@SE(SE_se0b_tel_put)
』


;^^^^^^^^電話:ママ^^^^^^^^

MSG_SYS_PHONE_MYHOME;@MiuraAppended
@GET_ORDER_PLAYER(1)
@SET_REG(0)
@EQ(PC_NESS)
@FALSE_GOTO(_SYS_PHONE_MYHOME_NES_DEAD)
;-----
@CHKFGOTO(FLG_WIN_GIEGU,_SYS_PHONE_MYHOME_END);ギーグ倒してたら
;-----
@CHKF(FLG_MYHOME_PHONE_TRACY)@FALSE_GOTO(_SYS_PHONE_MYHOME_FIRST)
@Q_SPECIAL(PC_NESS,6,2);ホームシック?
@TRUE_GOTO(_SYS_PHONE_MYHOME_HOMESICK)
@Q_SPECIAL(PC_NESS,1,8);風邪?
@TRUE_GOTO(_SYS_PHONE_MYHOME_COLD)
@CHKFGOTO(FLG_MYHOME_PHONE_PAULA,_SYS_PHONE_MYHOME_PAULA);ポーラ?
;@GET_ORDER_PLAYER(1)
;@SET_REG(0)
;@EQ(PC_NESS)
;@TRUE_GOTO(_SYS_PHONE_MYHOME_NES)
;
;_SYS_PHONE_MYHOME_NES;
@RAND(7)
@ONGOTO(_SYS_PHONE_MYHOME_NES_A,_SYS_PHONE_MYHOME_NES_A,_SYS_PHONE_MYHOME_NES_B,_SYS_PHONE_MYHOME_NES_B,_SYS_PHONE_MYHOME_NES_C,_SYS_PHONE_MYHOME_NES_C,_SYS_PHONE_MYHOME_NES_D)
_SYS_PHONE_MYHOME_NES_A;
◆@DSP_STS(STS_PC_NAME_NES)?@KEY()↓
◆... ...@KEY()↓
◆Don’t say a word;I know exactly what you’re thinking.@KEY()↓
◆My son, who’d have thought he was such a brave kid?@KEY()↓
  Oh, yeah...you’re a hero, honey!...@KEY()↓
◆Click!  Beep−beep−beep...@KEYNP()
;◆まあ @DSP_STS(STS_PC_NAME_NES)!@KEY()↓
;◆‥‥‥@KEY()↓
;◆なにもいわなくても いいの。@WI(15)↓
; ママは わかってるつもりよ。@KEY()↓
;◆じぶんの むすこながら↓
; たのもしいわぁ。@WI(15)↓
; イエイ!@KEY()↓
;◆ガチャン ツーツーツー@KEYNP()
@SE(SE_se0b_tel_put)
』

_SYS_PHONE_MYHOME_FIRST;最初の電話(エスカルゴ運送情報)
◆Is that you, @DSP_STS(STS_PC_NAME_NES)?@KEY()↓
  You called me back sooner than I thought...@KEY()↓
◆Everyone here is doing just fine.@KEY()↓
◆Oh yes, Tracy started working part−time for  Escargo Express.@KEY()↓
◆Here, I’ll let you talk to her.@KEY()↓
◆And call me when you have some time.  ...Oh...you don’t have any free time?@KEY()↓
◆Well, here’s Tracy.
;◆あら @DSP_STS(STS_PC_NAME_NES)ね。@WI(20)↓
; いがいと はやく↓
; でんわくれたのね。@KEY()↓
;◆こっちは みんな げんきよ。@KEY()↓
;◆そうそう トレーシーが↓
; アルバイトを はじめたのよ。@KEY()↓
;◆ちょっと かわるわね。@KEY()↓
;◆また ひまなときにでも↓
; でんわちょうだい。@WI(20)↓
; ‥‥ひまなんかないか?@KEY()@WI(15)↓
;◆じゃあ トレーシーにかわるわね。
@KEY()@WI(20)↓
@SETF(FLG_SYS_PHONE_MYHOME2)
@SETF(FLG_MYHOME_PHONE_TRACY);トレーシー(エスカルゴ)の番号聞いた
@GOTO(MSG_UNSOU_TEL);トレーシーの「アルバイトしてるの」に


_SYS_PHONE_MYHOME_COLD;風邪の場合
◆Hey, @DSP_STS(STS_PC_NAME_NES)!↓
  You sound terrible!@KEY()↓
◆Do you have a cold or something?@KEY()↓
◆Whatever dangeorous stuff you’re doing, remember that good health is very important! @KEY()↓
◆Try to keep as healthy as possible, even if it kills you!@KEY()↓
◆Well, I’d better go, I think my omlette might be on fire!  Bye!@KEY()↓
◆Click!  Beep−beep−beep... 
;◆まあ @DSP_STS(STS_PC_NAME_NES)ちゃん↓
; なんだか こえがへんねぇ。@KEY()↓
;◆かぜひいたのね。@KEY()↓
;◆どんなに あぶないことをするにも↓
; けんこうが きほんよ。@KEY()↓
;◆しんでも けんこうだけは↓
; まもりなさいね。@KEY()↓
;◆じゃ オムレツがこげちゃうから。@WI(15)↓
; バーイ音@WI(20)↓
; ガチャン ツーツーツー
@KEYNP()
@SE(SE_se0b_tel_put)
』

_SYS_PHONE_MYHOME_HOMESICK;ホームシック時
◆Hello, @DSP_STS(STS_PC_NAME_NES)?↓
  What’s wrong?  You sound so sad...@KEY()↓
◆Are you homesick?...Well, I knew there would be days like this. @KEY()↓
◆It must make you feel better, listening to your mom’s sweet voice.@KEY()↓
◆...So, do you feel any better?@KEY()↓
◆Well, I’d better get going.  I’m in the middle of my ironing.  Bye!@KEY()↓
@SE(SE_se0b_tel_put)
  Click!  Beep−beep−beep...
;◆まあ @DSP_STS(STS_PC_NAME_NES)ちゃん。@WI(20)↓
; どうしたのかしら↓
; そんな さみしそうなこえで。@KEY()↓
;◆うちが こいしくなったのかな?↓
; ‥‥ま そんなひも あるわよね。@KEY()↓
;◆ママの セクシーでステキな↓
; こえを きいて↓
; げんきになりなさい。@KEY()↓
;◆‥‥なった?@KEY()↓
;◆なったわね。@KEY()↓
;◆じゃ アイロンをかけてる↓
; とちゅうだから。@KEY()↓
;◆バーイ音@WI(20)↓
;@SE(SE_se0b_tel_put)
; ガチャン ツーツーツー
@KEY()
@CLOSEALL()
MSG_SYS_RECOVER_HOMESICK;ホームシック状態回復のナレーション
@WI(30)
@OPEN(1)
◆@DSP_STS(STS_PC_NAME_NES) got over being homesick.
;◆@DSP_STS(STS_PC_NAME_NES)は↓
; ホームシックを こくふくした。
@SET_SPECIAL(PC_NESS,6,1);ホームシック解除
@SE(SE_se25_b_healing)
@KEYNP()
@CLOSEALL()
』

_SYS_PHONE_MYHOME_PAULA;ポーラを仲間にした後
◆Hello, @DSP_STS(STS_PC_NAME_NES)?@KEY()↓
  So, I heard that you got a new girlfriend on your journey...@KEY()↓
◆Well, why don’t you tell me about her later...@KEY()↓
◆You see, I had this feeling that she was right next to you, or something.@KEY()↓
◆Well, if she is right there, say hello to her for me.@KEY()↓
◆I have to go now...I’m right in the middle of cleaning the toilet... Bye!@KEY()↓
@SE(SE_se0b_tel_put)
  Click!  Beep−beep−beep...
;◆あら @DSP_STS(STS_PC_NAME_NES)?↓
; たびさきで ガールフレンドが↓
; できたでしょ。@KEY()↓
;◆‥‥まあ ほうこくは↓
; いつかでいいわ。@KEY()↓
;◆‥‥な@WI(5)ん@WI(5)か@WI(5) ガールフレンドが↓
; そばにいるきが するんだなぁ。@KEY()↓
;◆もし いるんだったら↓
; よろしく いってね。@KEY()↓
;◆じゃ おふろに↓
; はいってたところだから。@KEY()↓
;◆バーイ音@WI(20)↓
;@SE(SE_se0b_tel_put)
; ガチャン ツーツーツー
@KEYNP()
@CLRF(FLG_MYHOME_PHONE_PAULA);ママの電話メッセージ切り替え用
』

_SYS_PHONE_MYHOME_NES_B;上にあてはまらなければランダムで
◆Hello, @DSP_STS(STS_PC_NAME_NES)?@KEY()↓
  So, how is your adventure going?@KEY()↓
◆...Hmmmm, I see...↓
  It sounds like you’re having some tough times, then.@KEY()↓
◆Your teacher dropped by, looking for you...  don’t worry−−I covered for you.@KEY()↓
◆Everything is fine here...you just keep on truckin’!@KEY()↓
◆Well, my soap opera is getting to a really steamy part, so I’d better let you go.@KEY()↓
  Bye!@KEY()↓
@SE(SE_se0b_tel_put)
◆Click!  Beep−beep−beep...
;◆まあ @DSP_STS(STS_PC_NAME_NES)ちゃん↓
; ぼうけんのたびは どう?@KEY()↓
;◆‥‥へーえ そう‥‥。@WI(20)↓
; それは たいへんだったわね。@KEY()↓
;◆がっこうの せんせいが↓
; かていほうもんに きたけど@KEY()↓
;◆ママが てきとうに↓
; ごまかしといたわ。@KEY()↓
;◆あんしんして↓
; たびを つづけなさい。@KEY()↓
;◆じゃ テレビのドラマが↓
; いいところだから。@KEY()↓
;◆バーイ音@WI(20)↓
;@SE(SE_se0b_tel_put)
; ガチャン ツーツーツー
@KEYNP()
』

_SYS_PHONE_MYHOME_NES_C;ランダムで
◆Hello?  Hello?!↓
  Is that you, @DSP_STS(STS_PC_NAME_NES)?@KEY()↓
◆I can hardly hear you...@KEY()↓
◆It sounds like you’re calling from the moon or something.@KEY()↓
◆... ... If you’re doing okay, that’s great. @KEY()↓
◆Listen, I have to get going.  I’m trying to give @DSP_STS(STS_PARTY_DOG_NAME) a flea bath.@KEY()↓
◆Bye!↓
@SE(SE_se0b_tel_put)
  Click!  Beep−beep−beep...
;◆もしもし もしもし‥‥↓
; ‥‥ああ @DSP_STS(STS_PC_NAME_NES)!@WI(15)↓
; なんか でんわが とおいわねぇ。@KEY()↓
;◆つきのせかいにでも↓
; いっているのかと おもったわ。↓
; ‥‥げんきなら なによりよ。@KEY()↓
;◆じゃ @DSP_STS(STS_PARTY_DOG_NAME)の↓
; ノミを とっているところだから。@KEY()↓
;◆バーイ音@WI(20)↓
;@SE(SE_se0b_tel_put)
; ガチャン ツーツーツー
@KEYNP()
』

_SYS_PHONE_MYHOME_NES_D;
◆Click! Beep−beep−beep...@KEY()↓
◆... No, no... I was just teasing...@KEY()↓
◆I wanted to see if my new impression would fool you.@KEY()↓
◆Everyone here is doing just fine.  *puff*@KEY()↓
◆Hope you’re doing all right, too.@KEY()↓
◆Well, I better go... I’m in the middle of my dance aerobics!@KEY()↓
◆Bye!↓
@SE(SE_se0b_tel_put)
  Click!  Beep−beep−beep...
;◆ガチャン ツーツーツー@WI(20)↓
; ‥‥あ うそうそ。↓
; いまのは わたしの ものまねよ。@KEY()↓
;◆こっちは みんな げんきだから↓
; あなたも げんきで いなさいよ。@KEY()↓
;◆じゃ いま↓
; バーベルあげてるところだから。@KEY()↓
;◆バーイ音@WI(20)↓
;@SE(SE_se0b_tel_put)
; ガチャン ツーツーツー
@KEYNP()
』

_SYS_PHONE_MYHOME_NES_DEAD;
@GET_ORDER_PLAYER(1)
@XCHG()
◆Oh, is this that darling little @DSP_NAME(0)?@KEY()↓
◆Is my sweet child @DSP_STS(STS_PC_NAME_NES) doing okay?@KEY()↓
◆Please come visit us sometime.@KEY()↓
@SE(SE_se0b_tel_put)
◆Click!  Beep−beep−beep...
;◆まあ @DSP_NAME(0)ちゃんね。@KEY()↓
;◆うちの @DSP_STS(STS_PC_NAME_NES)は↓
; げんきでやっているかしら?@KEY()↓
;◆また あそびにきてくださいね。@KEY()↓
;@SE(SE_se0b_tel_put)
;◆ガチャン ツーツーツー
@KEYNP()
』

_SYS_PHONE_MYHOME_END;
@CHKFGOTO(FLG_ONET_MYHOME_END_MAMA,_SYS_PHONE_MYHOME_END_2)
◆Hello, @DSP_STS(STS_PC_NAME_NES)?↓
  You can finally come home?  ... So that means...@KEY()↓
◆Oh, thank heavens!@KEY()↓
◆You did it and you’re safe!  I’m not exactly sure what you did, but...@KEY()↓
◆Anyway, if you come home quick, I’ll make some @DSP_STS(STS_PARTY_FAVORITE_FOODS).@KEY()↓
◆Get here as soon as you can.@KEY()↓
◆I can’t wait to see your bright and shining face!@KEY()↓
@SE(SE_se0b_tel_put)
◆Click!  Beep−beep−beep...
;◆あ @DSP_STS(STS_PC_NAME_NES)?@WI(20)↓
; もう かえってこられるのね?↓
; ‥‥ということは‥‥@KEY()↓
;◆コングラッチュレーション!@WI(15)↓
; やったわね!@WI(20)↓
; くわしいことは しらないけど。@KEY()↓
;◆じゃあ @DSP_STS(STS_PARTY_FAVORITE_FOODS)をつくって↓
; まってるから@WI(15)↓
; げんきなかおで もどってね。@KEY()↓
;@SE(SE_se0b_tel_put)
;◆ガチャン ツーツーツー
@KEYNP()
』
_SYS_PHONE_MYHOME_END_2;
◆I thought we would look at your album together...@KEY()↓
◆So what are you doing calling me?↓
@SE(SE_se0b_tel_put)
  Click!  Beep−beep−beep...
;◆せっかく いっしょに↓
; アルバムを みようと↓
; おもってるのに‥‥@KEY()↓
;◆なに のんびりでんわなんか↓
; かけてきてるの?@WI(20)↓
;@SE(SE_se0b_tel_put)
; ガチャン ツーツーツー
@KEYNP()
』
;------------------------------------------------------------------

;2時間パパ
MSG_SYS_PAPA_2H;
@CHKFGOTO(FLG_WIN_GIEGU,MSG_END);最終戦闘後はヤメ
@BGMSTART(0,BGM_msc1)
@WI(60)
@KEYNP()
@BGMSTOP(0)
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@SE(SE_se0b_tel_put)
@CHKFGOTO(FLG_PU,_PAPA_2H_NORMAL)
@CHKFGOTO(FLG_SUMS_RAMMA_START,_PAPA_2H_RAMA)
@CHKFGOTO(FLG_JEFF,_PAPA_2H_NORMAL)
@CHKFGOTO(FLG_WINS_START,_PAPA_2H_WINS)
_PAPA_2H_NORMAL;
@OPEN(1)
@GET_ORDER_PLAYER(1)
@EQ(PC_NESS)
@FALSE_GOTO(_PAPA_2H_NESS_DEAD)
◆Hello, it’s your dad.@KEY()↓
◆You’ve been out there for a long time now...@KEY()↓
◆It may be none of my↓
  business,@KEY()↓
◆but don’t you think it would be a good idea if you took a break?@KEY()↓
<YES>  <NO> 
;◆あ パパだ。@KEY()↓
;◆だいぶ ながいじかん↓
; ぼうけんを↓
; つづけているようだね。@KEY()↓
;◆おせっかいかもしれないが↓
; ちょっと きゅうけいしては↓
; どうだ?@KEY()↓
;  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SYS_PAPA_2H_YES,_SYS_PAPA_2H_NO)

_SYS_PAPA_2H_NO;
◆Ah, I see...@KEY()↓
◆Well, it doesn’t make me happy,@KEY()↓
◆but I understand your point about the fate of the world being at stake.
;◆そうか。↓
; ま ちきゅうの ききだからな。
@KEY()↓
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
』

_SYS_PAPA_2H_YES;
◆All right.@WI(20)  You should find a place to stay in the nearest town.@KEY()↓
◆When you get to the hotel,@WI(15) be sure to give your dear ol’ dad a call.@KEY()↓
◆And hey, keep an eye out for bad guys!
;◆そうか。@WI(20)↓
; じゃあ きょうは ちかくのまちで↓
; やすみなさい。@KEY()↓
;◆ホテルについたら かならず↓
; パパに でんわするんだぞ。@KEY()↓
;◆わるいやつらに きをつけてな。
@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
』

_PAPA_2H_RAMA;
@OPEN(1)
◆Hello, it’s your dad.@KEY()↓
◆You’ve been out there for a long time now...@KEY()↓
◆It may be none of my business,@KEY()↓
◆but don’t you think it would be a good idea if you took a break?@KEY()↓
<YES>  <NO>
;◆あ パパだ。@KEY()↓
;◆だいぶ ながいじかん↓
; ぼうけんを↓
; つづけているようだね。@KEY()↓
;◆おせっかいかもしれないが↓
; ちょっと きゅうけいしては↓
; どうだ?@KEY()↓
;  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_PAPA_2H_RAMA_YES,_PAPA_2H_RAMA_NO)

_PAPA_2H_RAMA_NO;
◆Ahhh...and this would be...?  So, this isn’t @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆Oh well, it’s okay...  Anyway, don’t strain yourself on your journey.@KEY()↓
◆Good luck... whoever you are.
;◆‥‥ありゃ そのこえは↓
; @DSP_STS(STS_PC_NAME_NES)じゃない??@KEY()↓
;◆でもいいや。@KEY()↓
;◆あんまり こんをつめて↓
; ぼうけんを つづけないようにね。@KEY()↓
;◆こううんを いのるよ↓
; みしらぬかた。
@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
』

_PAPA_2H_RAMA_YES;
◆Ahhh...and this would be...?  So, this isn’t @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆I’m glad that you decided to take my advice.@KEY()↓
◆All right, then.  Stay at a nearby town and get some rest.@KEY()↓
◆Before you take a break, be sure to call me.@KEY()↓
◆Be on the lookout for any shady characters...
;◆‥‥ありゃ そのこえは↓
; @DSP_STS(STS_PC_NAME_NES)じゃない??@KEY()↓
;◆よくぞ わたしのちゅうこくを↓
; きいてくださった!@KEY()↓
;◆では きょうは ちかくのまちで↓
; やすみなさい。@KEY()↓
;◆ぼうけんを やすむまえには↓
; かならず でんわを↓
; いっぽん いれるようにね。@KEY()↓
;◆じゃ わるいやつらに↓
; きをつけて。
@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
@!

_PAPA_2H_WINS;
@OPEN(1)
@GOSUB(_PAPA_2H_RAMA)
;◆ウィンタースへんでの↓
; 2じかんパパです。@KEYNP()
@!

_PAPA_2H_NESS_DEAD;
;◆ネスが きぜつのときの↓
; 2じかんパパです。@KEYNP()
@OPEN(1)
@GET_ORDER_PLAYER(1)
◆Hello, it’s your dad.@KEY()↓
◆You’ve been out there for a long time now...@KEY()↓
◆It may be none of my business,@KEY()↓
◆but don’t you think it would be a good idea if you took a break?@KEY()↓
<YES>  <NO>
;◆あ パパだ。@KEY()↓
;◆だいぶ ながいじかん↓
; ぼうけんを↓
; つづけているようだね。@KEY()↓
;◆おせっかいかもしれないが↓
; ちょっと きゅうけいしては↓
; どうだ?@KEY()↓
;  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_PAPA_2H_NESS_DEAD_YES,_PAPA_2H_NESS_DEAD_NO)
_PAPA_2H_NESS_DEAD_NO;
◆Ahhh...and this would be...?  So, this isn’t @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆I don’t know who you are, but thanks for taking care of my son, @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆Don’t work too hard while you continue your journey.@KEY()↓
◆You must be a hard worker, if you are a friend of @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆Remember, I’m rooting for you guys!
;◆‥‥ありゃ そのこえは↓
; @DSP_STS(STS_PC_NAME_NES)じゃない??@KEY()↓
;◆どなたか ぞんじませんが↓
; @DSP_STS(STS_PC_NAME_NES)が いつも↓
; おせわになっております。@KEY()↓
;◆あんまり むちゃなぼうけんを↓
; つづけては いけませんよ。@KEY()↓
;◆しかし @DSP_STS(STS_PC_NAME_NES)の↓
; ともだちだから きっと↓
; がんばりやなんでしょうな。@KEY()↓
;◆かげながら↓
; おうえんしとります。
@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
』
 
_PAPA_2H_NESS_DEAD_YES;
◆Ahhh...and this would be...?  So, this isn’t @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆Whoever you are, thank you for watching after my son, @DSP_STS(STS_PC_NAME_NES).@KEY()↓
◆I just wish that you guys would take a break.@KEY()↓
◆You’d feel so much more refreshed later on.@KEY()↓
◆You’d also probably have much better luck on your adventure.@KEY()↓
◆Stay in a nearby town and get some rest.@KEY()↓
◆If you see a phone, please call @DSP_STS(STS_PC_NAME_NES)’s father...well, actually, that’s me.@KEY()↓
◆And, be sure to be careful of the hoodlums.
;◆‥‥ありゃ そのこえは↓
; @DSP_STS(STS_PC_NAME_NES)じゃない??@KEY()↓
;◆どなたか ぞんじませんが↓
; @DSP_STS(STS_PC_NAME_NES)が いつも↓
; おせわになっております。@KEY()↓
;◆そろそろ やすんだほうが↓
; きっと あしたからの↓
; ぼうけんが うまくゆく@KEY()↓
;◆と おもってね。@KEY()↓
;◆‥‥きょうは ちかくのまちで↓
; ゆっくり おやすみください。@KEY()↓
;◆でんわを みつけたら↓
; また @DSP_STS(STS_PC_NAME_NES)のちち@KEY()↓
;◆つまり わたしですな。@KEY()↓
;◆に でんわしてください。@KEY()↓
;◆じゃ わるいやつらに↓
; きをつけて。
@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
@!

;
;宝箱のメッセージ
;

MSG_TBOX_PRESENT;
@SETF(FLG_SHOP_01)
@GOSUB(MSG_SUB_TBOX)
@CLRF(FLG_SHOP_01)
@!

MSG_TBOX_GOMIBAKO;
@SETF(FLG_SHOP_02)
@GOSUB(MSG_SUB_TBOX)
@CLRF(FLG_SHOP_02)
@!

MSG_TBOX_TAMATEBAKO;
@SETF(FLG_SHOP_03)
@GOSUB(MSG_SUB_TBOX)
@CLRF(FLG_SHOP_03)
@!

MSG_TBOX_HITSUGI;
@SETF(FLG_SHOP_04)
@GOSUB(MSG_SUB_TBOX)
@CLRF(FLG_SHOP_04)
@!

MSG_SUB_TBOX;
@SAVE_REG()
@CHKF_MSG()
@SAVE_GLOBAL_REG()
@GET_ORDER_PLAYER(1)
@XCHG()
@GOSUB(_SUB_TBOXMES_1)
@SE(SE_se10_present_open)
@SETF_MSG()
@KEY()↓
@LOAD_GLOBAL_REG()
@TRUE_GOTO(_TREASURE_EMPTY)
@GOSUB(_SUB_TBOXMES_2)
@LOAD_REG()
@FALSE_GOTO(_TREASURE_MONEY)
@XCHG()
@GOSUB(_SUB_TBOXMES_3)
_TREASURE_CHK_GOODSFULL;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TREASURE_RETURN)
@SAVE_REG()
@GOSUB(MSG_SUB_Q_DEAD_GOODS)
@TRUE_GOTO(_TREASURE_GET_DEAD)
@LOAD_REG()
@XCHG()
@GOSUB(_SUB_TBOXMES_4)
@GOODSIN_PLAYER(0,0)
@SE(SE_se74_my_get)
@!
_TREASURE_GET_DEAD;
@GOSUB(_SUB_TBOXMES_5)
@GOODSIN_PLAYER(0,0)
@SE(SE_se74_my_get)
@!
_TREASURE_RETURN;
@GOSUB(_SUB_TBOXMES_6)
@RESF_MSG()
@!
_TREASURE_MONEY;
@XCHG()
@FALSE_GOTO(_TREASURE_EMPTY_2)
_TREASURE_MONEY_2;
@XCHG()
@MONEYIN(0)
@WINR_MONEY()
@GOSUB(_SUB_TBOXMES_7)
@SE(SE_se74_my_get)
@!
_TREASURE_EMPTY;
_TREASURE_EMPTY_2;
@GOSUB(_SUB_TBOXMES_8)
@!

;
;宝箱用のサブルーチン
;

_SUB_TBOXMES_1;
@CHKFGOTO(FLG_SHOP_01,_SUB_TBOXMES_PSNT_1)
@CHKFGOTO(FLG_SHOP_02,_SUB_TBOXMES_GOMI_1)
@CHKFGOTO(FLG_SHOP_03,_SUB_TBOXMES_TAMA_1)
@CHKFGOTO(FLG_SHOP_04,_SUB_TBOXMES_HITSUGI_1)
@!
_SUB_TBOXMES_2;
@CHKFGOTO(FLG_SHOP_01,_SUB_TBOXMES_PSNT_2)
@CHKFGOTO(FLG_SHOP_02,_SUB_TBOXMES_GOMI_2)
@CHKFGOTO(FLG_SHOP_03,_SUB_TBOXMES_TAMA_2)
@CHKFGOTO(FLG_SHOP_04,_SUB_TBOXMES_HITSUGI_2)
@!
_SUB_TBOXMES_3;
←
◆There is a @DSP_GOODS(0) inside!
;◆@DSP_GOODS(0)が↓
; あった。
@KEY()
@!
_SUB_TBOXMES_4;
←
◆@DSP_NAME(0) takes it.
@XCHG()
;  @XCHG()@DSP_GOODS(0).
;◆@DSP_NAME(0)は↓
;@XCHG()
; @DSP_GOODS(0)を↓
; てにいれた。
@KEYNP()
@!
_SUB_TBOXMES_5;
@GET_ORDER_PLAYER(1)
@XCHG()
←
◆@DSP_NAME(0) added the
@LOAD_REG()
 @DSP_GOODS(0) ↓
 to @XCHG()@DSP_NAME(0)’s stuff.
@XCHG()
;◆@DSP_NAME(0)は↓
;@LOAD_REG()
;@XCHG()
; @DSP_NAME(0)のもちものに↓
;@XCHG()
; @DSP_GOODS(0)をくわえた。
@KEYNP()
@!
_SUB_TBOXMES_6;
←
@GET_ORDER_PLAYER(1)
◆But, @GOSUB(MSG_ESUB_HE_SHE) has got too much stuff already.
;◆しかしこれいじょう↓
; ものを もてない。
@KEYNP()
@!
_SUB_TBOXMES_7;
←
@SAVE_REG()
◆@GOSUB(MSG_ESUB_DSP_PARTY)
@LOAD_REG()
 got↓
  $@DSP_NUM(0) dollars.
;◆@DSP_LCNAME()は↓
; @DSP_NUM(0)ドル てにいれた。
@KEYNP()
@!
_SUB_TBOXMES_8;
@CHKFGOTO(FLG_SHOP_01,_SUB_TBOXMES_PSNT_8)
@CHKFGOTO(FLG_SHOP_02,_SUB_TBOXMES_GOMI_8)
@CHKFGOTO(FLG_SHOP_03,_SUB_TBOXMES_TAMA_8)
@CHKFGOTO(FLG_SHOP_04,_SUB_TBOXMES_HITSUGI_8)
@!



_SUB_TBOXMES_PSNT_1;
◆@DSP_NAME(0) opened the present.
;◆@DSP_NAME(0)は↓
; プレゼントのはこを あけた。
@!
_SUB_TBOXMES_PSNT_2;
@!
_SUB_TBOXMES_PSNT_8;
←
◆But it was empty.
;◆しかし からっぽだった。
@KEYNP()
@!
_SUB_TBOXMES_GOMI_1;
◆@DSP_NAME(0) dug around in the trash can.
;◆@DSP_NAME(0)は↓
; ごみばこを しらべた。
@!
_SUB_TBOXMES_GOMI_2;
←
@WI(20)
◆Here we go!!
;◆ジャン!!
@KEY()
@!
_SUB_TBOXMES_GOMI_8;
←
◆But there was just plain ol’ garbage in the trash can.
;◆ごみばこの なかは↓
; ほんとうに ごみばかりだった。
@KEYNP()
@!
_SUB_TBOXMES_TAMA_1;
◆@DSP_NAME(0) opened the chest.
;◆@DSP_NAME(0)は↓
; たまてばこを あけた。
@!
_SUB_TBOXMES_TAMA_2;
@WI(20)
◆WHOAAAAAAAAAAH!
;◆ホワワワン‥‥
@KEY()
@!
_SUB_TBOXMES_TAMA_8;
←
◆But the chest was empty.
;◆しかし たまてばこは↓
; からっぽだった。
@KEYNP()
@!
_SUB_TBOXMES_HITSUGI_1;
◆@DSP_NAME(0) opened the casket.
;jpn:◆@DSP_NAME(0)は↓
;jpn: ひつぎを あけた。
@!
_SUB_TBOXMES_HITSUGI_2;
@WI(20)
◆TAAAAAH−DAAAAAH!
;◆ジャカジャーン!!
@KEY()
@!
_SUB_TBOXMES_HITSUGI_8;
←
◆But the casket was empty.
;◆しかし ひつぎは↓
; からっぽだった。
@KEYNP()
@!

;
;はえみつ
;
MSG_TBOX_GOMIBAKO_HAEMITSU;
@GET_ORDER_PLAYER(1)
@XCHG()
@GOSUB(_SUB_TBOXMES_GOMI_1)	;「◆宝箱を調べた」
@SET_CHAR_DIR( PRSN_THRK_FIELD_3N, DIR_M_UP )	;蓋開ける
@SE( SE_se10_present_open )	;宝箱開け音
@KEY()↓
@CHKFGOTO( FLG_ITEM_HAEMITU, _SUB_TBOXMES_PSNT_8 )	;既に取ったら
@GOSUB( _SUB_TBOXMES_GOMI_2 )	;「◆ジャン!」
@SET_LOOPREG( GDS_FOOD_HAEMITSU )
@SET_REG( 1 )
@GOSUB( _SUB_TBOXMES_3 )
@Q_GOODSFULL( PC_ALL )		;グッズフルか?
@FALSE_GOTO( _HAEMITU_RETURN )	;if yes.
@SAVE_REG()
@GOSUB( MSG_SUB_Q_DEAD_GOODS )
@TRUE_GOTO( _HAEMITU_GET_DEAD )
@LOAD_REG()
@XCHG()
@GOSUB(_SUB_TBOXMES_4)
@GOODSIN_PLAYER( 0, 0 )
@XCHG()
@SE(SE_se74_my_get)		;グッズ入手音
@WI(30)
@SETF(FLG_ITEM_HAEMITU)
@!
_HAEMITU_GET_DEAD;
;入手処理
@GOSUB( _SUB_TBOXMES_5 )
@GOODSIN_PLAYER( 0, 0 )
@SE( SE_se74_my_get )		;グッズ入手音
@WI( 30 )
@SETF( FLG_ITEM_HAEMITU )
@!
_HAEMITU_RETURN;
;グッズフル時の処理
@GOSUB(_SUB_TBOXMES_6)
@SET_CHAR_DIR( PRSN_THRK_FIELD_3N, DIR_M_DOWN )	;再び閉じる
@!

;
;エンディングの手紙
;
MSG_TBOX_PRESENT_LETTER1;
;土星谷フィールド PKプレゼント1個目(ママの手紙)
@GET_ORDER_PLAYER(1)
@XCHG()
@GOSUB(_SUB_TBOXMES_PSNT_1)
@SE(SE_se10_present_open)
@SET_CHAR_DIR( PRSN_DOSE_FIELD_2B, DIR_M_UP )	;蓋開ける
@KEY()↓
@CHKFGOTO(FLG_ITEM_LETTER_1,_SUB_TBOXMES_PSNT_8)
@SET_LOOPREG(GDS_TOOL_LETTER_MAMA)
@SET_REG(1)
@GOSUB(_SUB_TBOXMES_3)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_LETTER1_RETURN)
@XCHG()
@GOSUB(_SUB_TBOXMES_4)
@GOODSIN_PLAYER(0,0)
@XCHG()
@SE(SE_se74_my_get)
@WI(30)
@SETF(FLG_ITEM_LETTER_1)
@!
_LETTER1_RETURN;
;グッズフル時の処理
@GOSUB(_SUB_TBOXMES_6)
@SET_CHAR_DIR( PRSN_DOSE_FIELD_2B, DIR_M_DOWN )	;再び閉じる
@!

MSG_TBOX_PRESENT_LETTER2;
;土星谷フィールド PKプレゼント2個目(トニーの手紙)
@GET_ORDER_PLAYER(1)
@XCHG()
@GOSUB(_SUB_TBOXMES_PSNT_1)
@SE(SE_se10_present_open)
@SET_CHAR_DIR( PRSN_DOSE_FIELD_2C, DIR_M_UP )	;蓋開ける
@KEY()↓
@CHKFGOTO(FLG_ITEM_LETTER_2,_SUB_TBOXMES_PSNT_8)
@SET_LOOPREG( GDS_TOOL_LETTER_TONY )
@SET_REG(1)
@GOSUB( _SUB_TBOXMES_3 )
@Q_GOODSFULL( PC_ALL )
@FALSE_GOTO( _LETTER2_RETURN )
@XCHG()
@GOSUB( _SUB_TBOXMES_4 )
@GOODSIN_PLAYER( 0, 0 )
@XCHG()
@SE(SE_se74_my_get)
@WI(30)
@SETF( FLG_ITEM_LETTER_2 )
@!
_LETTER2_RETURN;
;グッズフル時の処理
@GOSUB(_SUB_TBOXMES_6)
@SET_CHAR_DIR( PRSN_DOSE_FIELD_2C, DIR_M_DOWN )	;再び閉じる
@!

MSG_TBOX_PRESENT_LETTER3;
;土星谷フィールド PKプレゼント3個目(園児の手紙)
@GET_ORDER_PLAYER(1)
@XCHG()
@GOSUB(_SUB_TBOXMES_PSNT_1)
@SE(SE_se10_present_open)
@SET_CHAR_DIR(PRSN_DOSE_FIELD_2D,3)
@KEY()↓
@CHKFGOTO( FLG_ITEM_LETTER_3, _SUB_TBOXMES_PSNT_8 )
@SET_LOOPREG( GDS_TOOL_LETTER_CHILD )
@SET_REG(1)
@GOSUB(_SUB_TBOXMES_3)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_LETTER3_RETURN)
@XCHG()
@GOSUB(_SUB_TBOXMES_4)
@GOODSIN_PLAYER(0,0)
@XCHG()
@SE(SE_se74_my_get)
@WI(30)
@SETF(FLG_ITEM_LETTER_3)
@!
_LETTER3_RETURN;
@GOSUB(_SUB_TBOXMES_6)
@SET_CHAR_DIR(PRSN_DOSE_FIELD_2D,7)
@!
;------------------------------------------------------------------
;
;		SYSTEM用サブルーチン
;
;------------------------------------------------------------------

;#指定されたプレーヤーの性別によって「くん」「ちゃん」を返す。
;主レジにプレーヤーIDを入れること

MSG_SUB_KUN_CHAN;@
@ONGOSUB(_SUB_KUN,_SUB_CHAN,_SUB_KUN,_SUB_CHAN)
@!

_SUB_KUN;@
;#*kun(no translation:yuka)
;#くん
@!

_SUB_CHAN;@
;#*chan(no translation:yuka)
;#ちゃん
@!

;#パーティーが複数だったら「たち」を返す。
MSG_SUB_TATI;@
@SET_LOOPREG(1)
_TATI_LOOP;
@INC()
;@XCHG();不用
@SET_REG(1)
@GET_ORDER_PLAYER(0)
@FALSE_GOTO(_TATI_END_2)
@SAVE_REG()
@CMP(5,0)
@TRUE_GOTO(_TATI_END_1)
@LOAD_REG()
@Q_SPECIAL(0,1,2)
@TRUE_GOTO(_TATI_LOOP)
@LOAD_REG()
@Q_SPECIAL(0,1,3)
@TRUE_GOTO(_TATI_LOOP)
_TATI_END_1;@
;#*tachi(no translation:yuka)
;#たち
_TATI_END_2;@
@!

MSG_SUB_TATI_ONSEN;ポーラと別れてたら一人@
@CHKFGOTO(FLG_TWSN_POLA_APPEAR,_TATI_ONSEN_END_2)
_TATI_ONSEN_END_1;@
;#*tachi(no translation:yuka)
;#たち
_TATI_ONSEN_END_2;@
@!


;#指定されたプレーヤーが会話出来ないかどうかをチェックする。
;会話出来なければ1を主レジに返す。
;ループレジにプレーヤーIDを入れること

MSG_SUB_Q_DEAD;
@SET_REG(1)
@XCHG()
@SAVE_REG()
MSG_SUB_Q_DEAD_GOODS;
@Q_SPECIAL(0,1,2)
@TRUE_GOTO(_Q_DEAD_END)
@LOAD_REG()
@Q_SPECIAL(0,1,3)
_Q_DEAD_END;
@!

MSG_SUB_Q_PARTY;
@SET_REG(1)
@!

MSG_SUB_Q_FRONT;
@XCHG()
@SAVE_REG()
@EQ(1)
@TRUE_GOTO(_Q_FRONT_END)
@LOAD_REG()
@EQ(2)
@TRUE_GOTO(_Q_FRONT_END)
@LOAD_REG()
@EQ(8)
_Q_FRONT_END;
@!

MSG_SUB_GETGOODS_S;
@SE(SE_se74_my_get)
@WI(60)
@SAVE_GLOBAL_REG()
@CLOSEALL()
@SE(SE_se66_elevator_move);重要グッズ入手音
@WI(100)	;元は120だったが変えてみた:malta
@OPEN(1)
@LOAD_GLOBAL_REG()
@GOSUB(_SUB_GETGOODS_MES)
@!

MSG_SUB_GETGOODS;
@SE(SE_se74_my_get)
@WI(60)
@GOSUB(_SUB_GETGOODS_MES)
@!

_SUB_GETGOODS_MES;
@SAVE_REG()
@GOSUB(MSG_SUB_Q_DEAD_GOODS)
@TRUE_GOTO(_SUB_GETGOODS_DEAD)
@LOAD_REG()
@XCHG()
←
◆(@DSP_NAME(0) got↓
  the 
@XCHG()
@GET_PLAYER_GOODS(0,0)
@DSP_GOODS(0).)
;◆(@DSP_NAME(0)は↓
;@XCHG()
;@GET_PLAYER_GOODS(0,0)
; @DSP_GOODS(0)を↓
; てにいれた)
@!
_SUB_GETGOODS_DEAD;レジスタの使い方不明(三浦)←とりあえずなんかした(丸田)
@GET_ORDER_PLAYER(1)
@XCHG()
◆(@DSP_NAME(0) added the 
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@DSP_GOODS(0) to 
@XCHG()
@DSP_NAME(0)’s
 stuff.)
;◆(@DSP_NAME(0)は↓
;@LOAD_REG()
;@XCHG()
; @DSP_NAME(0)のもちものに↓
;@XCHG()
;@GET_PLAYER_GOODS(0,0)
; @DSP_GOODS(0)をくわえた)
@!

;主レジ:%PLAYER_ID・副レジ:グッズの位置で
;セーブレジ:%PLAYER_ID,%GOODS_ID・グローバルレジ:%PLAYER_ID,グッズの位置
;主レジ:%GOODS_ID・副レジ:%PLAYER_IDを返す
MSG_SUB_GOODS_PRE;
@SAVE_GLOBAL_REG()
@GET_PLAYER_GOODS(0,0)
@SAVE_REG()
@XCHG()
@!

;グッズを使った時のメッセージ
;主レジ:%PLAYER_ID・副レジ:%GOODS_IDを入れておく
MSG_SUB_GOODS_TUKATTA;
@XCHG()
◆@DSP_NAME(0) used↓
  the @XCHG()@DSP_GOODS(0).
;◆@DSP_NAME(0)は↓
;@XCHG()
; @DSP_GOODS(0)をつかった!@KEY()
@!


;#「はい」「いいえ」を表示する
MSG_SUB_YESNO_MONEY_PANEL;
@DSP_PL()
MSG_SUB_YESNO_MONEY;
@WINR_MONEY()
MSG_SUB_YESNO;
<Yes>
<No>
;<はい>
;<いいえ>
@DSP_ITEM(2)
@!

;#ムーンサイド「はい」「いいえ」に対応した@SELGOTO()
;FLG_SHOPTEMP_4で識別、戻った後に@ONGOTO()をすること
MSG_SUB_SELQ_FORMOON;
@SELQ()
@CLRLINE()
@CHKFGOTO(FLG_SHOPTEMP_4,_SELQ_FORMOON_MOON)
@!
_SELQ_FORMOON_MOON;
@NOT(1)
@!

;#3秒かけてBGMフェードアウト
MSG_SUB_BGM_FADEOUT_LONG;
MSG_SUB_BGM_FADEOUT_2SECOND;
@BGM_EFFECT(3)
@WI(180)
@BGMSTOP(0)
@!

;jpn:#0.5秒かけてBGMフェードアウト
MSG_SUB_BGM_FADEOUT_SHORT;
MSG_SUB_BGM_FADEOUT_05SECOND;
@BGM_EFFECT(2)
@WI(30)
@BGMSTOP(0)
@!

;#BGMフェードアウト3秒後ムシスタート
MSG_SUB_BGM_CHANGE_1;
@GOSUB(MSG_SUB_BGM_FADEOUT_2SECOND)
@MUSISTART()
@!

;#BGMフェードアウト0.5秒後ムシスタート
MSG_SUB_BGM_CHANGE_2;
@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@MUSISTART()
@!

;#現在配達処理中なら1を返す
MSG_SUB_Q_NOW_DELIVERY;
@CHKF(FLG_DELIVERY_PIZZA)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_UNSOU)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_UNSOU_B)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_CUSTOMER)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_CUSTOMER_B)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_CUSTOMER_C)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_CUSTOMER_D)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_HOIHOI)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_UNSOU_TAKOKESHI)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
@CHKF(FLG_DELIVERY_UNSOU_TAKANOME)@TRUE_GOTO(_Q_NOW_DELIVERY_END)
_Q_NOW_DELIVERY_END;
@!

;#配達員が帰るまで動けなくなる
MSG_SUB_DELIVERY_BYE;
@FRESH_CHAR(PRSN_GLOBAL_DELIVERY)
@WAITSYS()
@!

;#配達フラグを全てOFFにする。
MSG_SUB_DELIVERY_OFF;
@CLRF(FLG_DELIVERY_PIZZA)
@CLRF(FLG_DELIVERY_UNSOU)
@CLRF(FLG_DELIVERY_UNSOU_B)
@CLRF(FLG_DELIVERY_CUSTOMER)
@CLRF(FLG_DELIVERY_CUSTOMER_B)
@CLRF(FLG_DELIVERY_CUSTOMER_C)
@CLRF(FLG_DELIVERY_CUSTOMER_D)
@CLRF(FLG_DELIVERY_HOIHOI)
@CLRF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@CLRF(FLG_DELIVERY_UNSOU_TAKANOME)
@CLRF(FLG_SYS_DISTLPT);テレポート許可
@!

;#全滅時に呼ばれるメッセージ
MSG_SYS_ZENMETSU;
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@CLRF(FLG_BGM_FUNE1)
@CLRF(FLG_BGM_FUNE2)
@SETF(FLG_SYS_DIS_MOUSE)		;穴ぬけ鼠の使用禁止
@CHKFGOTO(FLG_DUNGEONMAN,_SYS_ZENMETU_2)
@CLRF(FLG_SYS_DISTLPT)
@CLRF(FLG_SYS_DISTLPT_EVENT)
_SYS_ZENMETU_2;
@!

;#ゲームスタート前に呼ばれるメッセージ
MSG_SYS_PRE_GAMESTART;
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!


;#受信電話の呼び出し
MSG_SUB_ZYUSHIN_CALL;
@BGMSTART(0,BGM_msc1)
@WI(60)
@KEYNP()
@BGMSTOP(0);電話の音はブツっと切れるがよい。
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@SE(SE_se0b_tel_put)
@!

;#電話を切る
MSG_SUB_TEL_PUT;
←
◆click!  Beeeeeeep...
;◆ガチャン ツーツーツー
@KEYNP()
@SE(SE_se0b_tel_put)
@!

;#受信電話を切る
MSG_SUB_ZYUSHIN_PUT;
@GOSUB(MSG_SUB_TEL_PUT)
@CLOSEALL()
@WI(10)
@MUSISTART()
@!

;#デリバリー中以外ならテレポート許可にする
MSG_SUB_TLPTOK_OTHERDELIVERY;
@CLRF(FLG_SYS_DISTLPT_EVENT)
@GOSUB(MSG_SUB_Q_NOW_DELIVERY)
@TRUE_GOTO(MSG_END)
@CLRF(FLG_SYS_DISTLPT)
@!

;#イベント中以外ならテレポート許可する
MSG_SUB_TLPTOK_OTHEREVENT;
@CHKFGOTO(FLG_SYS_DISTLPT_EVENT,MSG_END)
@CLRF(FLG_SYS_DISTLPT)
@!

;-------------------------------------------------

;★カムバックメッセージ

MSG_SYS_COMEBACK;
@GOSUB(MSG_SYS_ZENMETSU)		;全滅時の処理
@GOSUB(MSG_GLOBAL_DELIVERY_RESET);(場面転換時に配達を中止)
@OPEN(1)
@GOSUB(_SUB_Q_NESSJEFF)
◆@DSP_NAME(0)!@KEY()↓
◆It looks like you got your head handed to you.@KEY()↓
◆So, how about giving it another shot?↓
<Yes>  <No>
;◆@DSP_NAME(0)! @DSP_NAME(0)!@KEY()↓
;◆たたかいに つかれたようだな。↓
; もういちど チャレンジするか?↓
;  <はい>  <いいえ>
@DSP_ITEM(2)
@SELGOTO(_SYS_COMEBACK_YES,_SYS_COMEBACK_SURE)

_SYS_COMEBACK_SURE;警告
◆Are you sure?@KEY()↓
◆The next time you start your adventure,@KEY()↓
◆you’ll begin where you last saved.@KEY()↓
◆Is that okay?↓
<No>  <Yes>
;◆そうか。@KEY()↓
;◆つぎのぼうけんは↓
; このまえにセーブした↓
; ところから はじまることになるが@KEY()↓
;◆それでいいな?↓
;  <いいえ>  <はい>
@DSP_ITEM(2)
@SELGOTO(_SYS_COMEBACK_YES,_SYS_COMEBACK_NO)

_SYS_COMEBACK_YES;
◆@DSP_NAME(0) decided to return after summoning all the courage and energy he had.@KEY()↓
◆Good luck!
;◆@DSP_NAME(0)は↓
; さいごのきりょくを ふりしぼって↓
; たたかいのばに ふっかつした。@KEY()↓
;◆がんばってくれ @DSP_NAME(0)!
@KEYNP()
@CLOSEALL()
@SETF(FLG_SYS_COMEBACK)
』

_SYS_COMEBACK_NO;
◆It must have all just been a bad dream.@KEY()↓
◆See you, @DSP_NAME(0)!
;◆@DSP_NAME(0)は↓
; わるいゆめを みたのだ。@KEY()↓
;◆がんばれ! @DSP_NAME(0)!
@KEYNP()
@CLOSEALL()
@CLRF(FLG_SYS_COMEBACK)
』

_SUB_Q_NESSJEFF;		ネスかジェフかの名前を返す
@CHKFGOTO(FLG_JEFF,_NESSJEFF_NESS)
@CHKF(FLG_WINS_START)@FALSE_GOTO(_NESSJEFF_NESS)
@SET_LOOPREG(PC_JEFF)
@SET_REG(1)
@!
_NESSJEFF_NESS;
@SET_LOOPREG(PC_NESS)
@SET_REG(1)
@!

;--------------------------------------------------------------------------
;マジカントクリアによるネスのパワーアップ
;========================================
MSG_SYS_MGKT_NES_POWER_UP;

;ネス正面を向く
@SET_PLAYER_DIR( PC_NESS, DIR_M_UP_RIGHT )
@WI( 16 )
@SET_PLAYER_DIR( PC_NESS, DIR_M_RIGHT )
@WI( 12 )
@SET_PLAYER_DIR( PC_NESS, DIR_M_DOWN_RIGHT )
@WI( 8 )
@SET_PLAYER_DIR( PC_NESS, DIR_M_DOWN )
@WI( 60 )

@BGMSTART(0,BGM_vins1)

@FRESH_GOM_CHAR( GOM_HIT_CHR )		;ネスを白く光らせる
@WAITSYS()		;for ANIM_EVT_FLUCTUATE_MAGICANT
@COLD_GOM_CHAR( GOM_HIT_CHR )

;ステイタスパネル表示 on
@DSP_PL()

;ステイタスパネルのぐるぐるをスタート
@FUNC(13)

;ジャイアントステップのパワーを得る
;----------------------------------
@OPEN(1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Giant Step!
;◆ジャイアントステップのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s speed increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のスピードが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@SPEED_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s vitality increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のバイタリティが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@VITAL_UP_POINT(PC_NESS,5)
@KEY()↓

;リリパットステップのパワーを得る
;----------------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Lilliput Steps!
;◆リリパットステップのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s guts increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のガッツが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@GUTS_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s luck increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のラックが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@LUCK_UP_POINT(PC_NESS,5)
@KEY()↓

;ミルキーウェルのパワーを得る
;----------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Milky Well!
;◆ミルキーウェルのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s speed increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のスピードが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@SPEED_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s IQ increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のIQが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@IQ_UP_POINT(PC_NESS,5)
@KEY()↓

;マグネットヒルのパワーを得る
;----------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Magnet Hill!
;◆マグネットヒルのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s vitality increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のバイタリティが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@VITAL_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s luck increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のラックが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@LUCK_UP_POINT(PC_NESS,5)
@KEY()↓

;レイニーサークルのパワーを得る
;------------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Rainy Circle!
;◆レイニーサークルのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s guts increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のガッツが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@GUTS_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s IQ increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のIQが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@IQ_UP_POINT(PC_NESS,5)
@KEY()↓

;ピンククラウドのパワーを得る
;----------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Pink Cloud!
;◆ピンククラウドのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s speed increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のスピードが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@SPEED_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s guts increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のガッツが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@GUTS_UP_POINT(PC_NESS,5)
@KEY()↓

;ルミネホールのパワーを得る
;--------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Lumine Hole!
;◆ルミネホールのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s luck increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のラックが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@LUCK_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s IQ increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のIQが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@IQ_UP_POINT(PC_NESS,5)
@KEY()↓

;ファイアスプリングのパワーを得る
;--------------------------------
;@SE(SE_se40_b_pk_starstorm1)
◆@DSP_STS(STS_PC_NAME_NES) was filled with the Power of the Fire Spring!
;◆ファイアスプリングのパワーが↓
; @DSP_STS(STS_PC_NAME_NES)のなかに みなぎった!
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s speed increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のスピードが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@SPEED_UP_POINT(PC_NESS,5)
@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES)’s luck increased by 5!
;◆@DSP_STS(STS_PC_NAME_NES)のラックが↓
; 5 UPした!
@SE(SE_se28_b_offence_up)
@LUCK_UP_POINT(PC_NESS,5)
@KEY()

;ウインドウとステイタスパネルを閉じる
@CLOSEALL()

;HP、PPメータのぐるぐるを止める
@FUNC(14)

;MaxPP2倍を得る
;--------------
;@SE(SE_se40_b_pk_starstorm1)
@WI(60)
;@SE(SE_se40_b_pk_starstorm1)
@OPEN(1)
◆Instantly, @DSP_STS(STS_PC_NAME_NES)’s mind cleared,@KEY()↓  and he realized that he had possessed great power!
;◆そして @DSP_STS(STS_PC_NAME_NES)じしんの↓
; かくれた ちからが↓
; いま めざめた!
@KEY()↓
◆At that moment, @DSP_STS(STS_PC_NAME_NES)’s psychic powers radically expanded!
;◆@DSP_STS(STS_PC_NAME_NES)のサイキックパワーは↓
; ひやくてきに おおきくなった!
@SE(SE_se28_b_offence_up)
@SETF(FLG_WIN_OSCAR)
@KEY()
@CLOSEALL()

;@SE(SE_se40_b_pk_starstorm1)
@WI(30)
;@SE(SE_se40_b_pk_starstorm1)

@OPEN(14)
 @DSP_STS(STS_PC_NAME_NES) gained 200,000 exp.
; @DSP_STS(STS_PC_NAME_NES)は↓
; 200000の けいけんちをえた。
@KEY()
@EXP_UP_POINT(PC_NESS,200000)
;↑自動的にバトル用メッセージウインドウを開き、経験値取得処理を行ってくれる
;ハズです。
;以下追加、兄、上野、戸田
@MESSAGE_SOUND(3)
←
 And finally, he realized
@SE(SE_se67_elevator_stop)
 he had the power of Teleport β.
; そして さいごに@KEY()↓
; @DSP_STS(STS_PC_NAME_NES)は↓
; PKテレポートβを おぼえた!
@ADD_PSI(PC_NESS,1)			;テレポートαを念のため加える
@ADD_PSI(PC_NESS,4)			;テレポートβ加える
@FKEY()
@MESSAGE_SOUND(1)
@CLOSEALL()

;@SE(SE_se40_b_pk_starstorm1)
@WI(120)
;@SE(SE_se40_b_pk_starstorm1)
@WI(180)
;@SE(SE_se40_b_pk_starstorm1)
@WI(10)
;@SE(SE_se40_b_pk_starstorm1)

;白くなっているうちに「裸ネス」を「通常ネス」に変える
@HIDE_PLAYER( PC_NESS, OBJFX_HIDE_NONE )
@COLD_PLAYER( PC_ALL )
@MOVE_GOM_CHAR( GOM_NES, ANIM_POSSESS_PC_ALL_STILL, OBJFX_SHOW_NONE )
@WI( 10 )

@FRESH_GOM_CHAR( GOM_HIT_CHR )		;白く光っているネスを元に戻す
@WAITSYS()		;for ANIM_EVT_FLUCTUATE_MAGICANT(この後自殺)

@OPEN(1)
◆@DSP_STS(STS_PC_NAME_NES) made all of the hidden powers his own.@KEY()↓
◆@DSP_STS(STS_PC_NAME_NES) absorbed the power of the land into his heart, and Magicant was no more.
;◆かくされたちからの すべてを↓
; @DSP_STS(STS_PC_NAME_NES)は じぶんのものにした。@KEY()↓
;◆‥‥@DSP_STS(STS_PC_NAME_NES)の↓
; こころのなかの くに@WI(30)↓
; マジカントは きえた。
@KEY()
@CLOSEALL()
@GOTO(MSG_EVT_106_MAGICANT_OUT)
@!

;-------------------------------------------------
;■新システムメッセージ■


MSG_SYS_CARRY_SELF_ALIVE
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) rearranged 
@XCHG()@GOSUB(MSG_ESUB_HIS_HER)@XCHG()
 own items and the @XCHG()@DSP_GOODS(0) moved.
@KEYNP()
@!

MSG_SYS_CARRY_FAIL_OTHER_ALIVE_ALIVE
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) tried to give the @XCHG()@DSP_GOODS(0) to @DSP_NAME(0FFh),@KEY()↓
@LOAD_REG()
◆but 
@GOSUB(MSG_ESUB_HE_SHE)
 was already carrying too much stuff.
@KEYNP()
@!


MSG_SYS_CARRY_FAIL_OTHER_ALIVE_DEAD
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) tried to add the @XCHG()@DSP_GOODS(0) to @DSP_NAME(0FFh)’s stuff,
◆but there was no room for it.@KEY()↓
@KEYNP()
@!


MSG_SYS_CARRY_OTHER_ALIVE_ALIVE
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) gave the @XCHG()@DSP_GOODS(0) to @DSP_NAME(0FFh).
@KEYNP()
@!


MSG_SYS_CARRY_OTHER_ALIVE_DEAD
@GET_PLAYER_GOODS(0,0)
@XCHG()
◆@DSP_NAME(0) add the @XCHG()@DSP_GOODS(0) to @DSP_NAME(0FFh)’s stuff.
@KEYNP()
@!


MSG_SYS_CARRY_SELF_DEAD
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SAVE_REG()
@GET_ORDER_PLAYER(1)
@XCHG()
◆@DSP_NAME(0)
@LOAD_REG()
 rearranged @DSP_NAME(0)’s items and the @XCHG()@DSP_GOODS(0) moved.
@KEYNP()
@!



MSG_SYS_CARRY_FAIL_OTHER_DEAD_ALIVE
@GET_PLAYER_GOODS(0,0)
◆@DSP_NAME(0FFh) tried to took the @DSP_GOODS(0) from @XCHG()@DSP_NAME(0)’s stuff,@KEY()↓
@LOAD_REG()
◆but 
@GOSUB(MSG_ESUB_HE_SHE)
 was already carrying too much stuff.
@KEYNP()
@!


MSG_SYS_CARRY_FAIL_OTHER_DEAD_DEAD
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SAVE_GLOBAL_REG()
@GET_ORDER_PLAYER(1)
@XCHG()
◆@DSP_NAME(0)
@LOAD_GLOBAL_REG()
 tried to add @DSP_NAME(0)’s @XCHG()@DSP_GOODS(0) to @DSP_NAME(0FFh)’s stuff,@KEY()↓
◆but there was no room for it.
@KEYNP()
@!


MSG_SYS_CARRY_OTHER_DEAD_ALIVE
@GET_PLAYER_GOODS(0,0)
◆@DSP_NAME(0FFh) took the @DSP_GOODS(0) from @XCHG()@DSP_NAME(0)’s stuff.
@KEYNP()
@!


MSG_SYS_CARRY_OTHER_DEAD_DEAD
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SAVE_GLOBAL_REG()
@GET_ORDER_PLAYER(1)
@XCHG()
◆@DSP_NAME(0)
@LOAD_GLOBAL_REG()
 added @DSP_NAME(0)’s @XCHG()@DSP_GOODS(0) to @DSP_NAME(0FFh)’s stuff.
@KEYNP()
@!
;------------------------------
;
;	EARTH BOUND用サブルーチン
;
;------------------------------

;#ポーラだったらsheを、ポーラ以外だったらheを表示する
;(あらかじめ主レジに%PLAYER_IDを入れておくこと)
MSG_ESUB_HE_SHE;
@EQ(PC_PAULA)
@TRUE_GOTO(_HE_SHE_2)
he
@!
_HE_SHE_2;
she
@!

;#@GET_ACTOR用のMSG_ESUB_HE_SHE
MSG_ESUB_HE_SHE_GACT;
@GET_ACTOR(1)
@ONGOTO(_ESUB_HE_SHE_GACT_1,_ESUB_HE_SHE_GACT_2,_ESUB_HE_SHE_GACT_3)
_ESUB_HE_SHE_GACT_1;
he
@!
_ESUB_HE_SHE_GACT_2;
she
@!
_ESUB_HE_SHE_GACT_3;
it
@!

;#@GET_OBJECT用のMSG_ESUB_HE_SHE
MSG_ESUB_HE_SHE_GOBJ;
@GET_OBJECT(1)
@XCHG()
 @DSP_NUM(0) 
@GET_OBJECT(1)
@ONGOTO(_ESUB_HE_SHE_GOBJ_1,_ESUB_HE_SHE_GOBJ_2,_ESUB_HE_SHE_GOBJ_3)
_ESUB_HE_SHE_GOBJ_1;
he
@!
_ESUB_HE_SHE_GOBJ_2;
she
@!
_ESUB_HE_SHE_GOBJ_3;
it
@!

;#ポーラだったらhisを、ポーラ以外だったらherを表示する
MSG_ESUB_HIS_HER;
@EQ(PC_PAULA)
@TRUE_GOTO(_HIS_HER_2)
his
@!
_HIS_HER_2;
her
@!

;#@GET_ACTOR用のMSG_ESUB_HIS_HER
MSG_ESUB_HIS_HER_GACT;
@GET_ACTOR(1)
@ONGOTO(_ESUB_HIS_HER_GACT_1,_ESUB_HIS_HER_GACT_2,_ESUB_HIS_HER_GACT_3)
_ESUB_HIS_HER_GACT_1;
his
@!
_ESUB_HIS_HER_GACT_2;
her
@!
_ESUB_HIS_HER_GACT_3;
its
@!

;#@GET_OBJECT用のMSG_ESUB_HIS_HER
MSG_ESUB_HIS_HER_GOBJ;
@GET_OBJECT(1)
@ONGOTO(_ESUB_HIS_HER_GOBJ_1,_ESUB_HIS_HER_GOBJ_2,_ESUB_HIS_HER_GOBJ_3)
_ESUB_HIS_HER_GOBJ_1;
his
@!
_ESUB_HIS_HER_GOBJ_2;
her
@!
_ESUB_HIS_HER_GOBJ_3;
its
@!

;#ポーラだったma’amを、ポーラ以外だったらsirを表示する
;(あらかじめ主レジに%PLAYER_IDを入れておくこと)
MSG_ESUB_SIR_MAAM;
@EQ(PC_PAULA)
@TRUE_GOTO(_SIR_MAAM_2)
sir
@!
_SIR_MAAM_2;
ma’am
@!


;#パーティーの人数に合わせて「○○たち」にあたる言葉を表示する
MSG_ESUB_DSP_PARTY;
@GET_ORDER_PLAYER(1)			;先頭キャラ名表示
@XCHG()
@DSP_NAME(0)
@SET_LOOPREG(1)				;パーティー人数確認
_DSP_PARTY_LOOP;
@INC()
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_DSP_PARTY_0)
@GET_ORDER_PLAYER(0)
@Q_SPECIAL(0,1,2)			;気絶チェック
@TRUE_GOTO(_DSP_PARTY_0)
@GET_ORDER_PLAYER(0)
@Q_SPECIAL(0,1,3)			;ダイヤチェック
@TRUE_GOTO(_DSP_PARTY_0)
@GOTO(_DSP_PARTY_LOOP)
_DSP_PARTY_0;				;パーティー人数によって分岐
@SET_REG(1)
@XCHG()
@ONGOTO(_DSP_PARTY_1,_DSP_PARTY_1,_DSP_PARTY_2,_DSP_PARTY_3,_DSP_PARTY_3)
@!
_DSP_PARTY_1;
@!
_DSP_PARTY_2;
@GET_ORDER_PLAYER(2)
@XCHG()
 and @DSP_NAME(0)
@!

_DSP_PARTY_3;
 and 
@GET_ORDER_PLAYER(1)
@EQ(PC_PAULA)
@TRUE_GOTO(_DSP_PARTY_3_B)
his friends
@!
_DSP_PARTY_3_B;
her friends
@!

;#MSG_ESUB_DSP_PARTYのレジスタ保存版
MSG_ESUB_DSP_PARTY_SREG;
@SAVE_REG()
@GOSUB(MSG_ESUB_DSP_PARTY)
@LOAD_REG()
@!

;#モンスターの

;--------------------------------------------------------------------------
